### ISSUE TITLE
Marten.CommandLine should warn if AutoCreateSchemaObjects is set to None

### ISSUE THREAD

**Issue by droach282** [JasperFx/marten#1005]
Is there any chance we could update Marten.CommandLine to generate a warning if AutoCreateSchemaObjects is set to None?  Currently, the Execute(options) reports that no changes are detected, even if there are schema objects that need to be created or updated.

Example (both with no schema in Postgres):

`# With AutoCreate set to None`
`> marten patch patch1.sql --drop patch1.drop.sql`
`No differences were detected between the Marten configuration and the database`

`# With AutoCreate set to CreateOrUpdate`
`> marten patch patch1.sql --drop patch1.drop.sql`
`Wrote a patch file to patch1.sql`
`Wrote the drop file to patch1.drop.sql`

**Comment by jeremydmiller** [comment]
@droach282 I'm just going to get this one fixed. Related to https://github.com/JasperFx/marten/issues/983. Marten is a little torn up right now with the build broken after some unrelated "fixes". When I clear that, I'll circle back to this in the 2.8.0 timeframe.

**Comment by droach282** [comment]
Good deal, thank you much!

Sent from Mail for Windows 10

**Comment by jeremydmiller** [comment]
I'm going to claim this is addressed by the fix for #983. Will be in Marten 2.8 later today.
