### ISSUE TITLE
DuplicatedField has hard coded _dbtype

### ISSUE THREAD

**Issue by cchongchong** [JasperFx/marten#1011]
Hi,

I noticed that _dbType within DuplicatedField is hardcoded as NpgsqlDbType.TimestampTZ, this causes the data update issue if we give different PgType.

Reproduce Steps:

1. Duplicate your field to additional column with custom PgType: `For<YourModel>().Duplicate(x => x.YourDateTimeField, "timestamp without time zone");`
3. Try to insert or update YourModel, you will get error because it's trying to insert/update the data with NpgsqlDbType.TimestampTZ for YourDateTimeField.

Here is the [source code](https://github.com/JasperFx/marten/blob/master/src/Marten/Schema/DuplicatedField.cs#L43)
`if (MemberType.IsDateTime())
            {
                PgType = "timestamp with time zone";
                _dbType = NpgsqlDbType.TimestampTZ;
            }`
You can see that _dbType is hardcoded as NpgsqlDbType.TimestampTZ, no matter which PgType you give.

I'm thinking about if it's good or not that gives developer ability to set both PgType and DbType, but also check if those two fields are matched.

Thanks,
Chongzhao

**Comment by jeremydmiller** [comment]
@cchongchong I'm adding this ability now for 3.0, but I'm not sure if overriding the date time types won't through off the Linq querying
