### ISSUE TITLE
Feeback on ease of use

### ISSUE THREAD

**Issue by bobmcallan** [JasperFx/marten#1034]
Just a couple of points to note (second look and install):

1. Great idea to utilise Postgres and all the power this brings
2. There are many unknown dependencies on the lib, lowers my level of trust on the support-ability

However finally, 
3.  The install/setup has to many variables and few reasons/checks. In the end, I've not been able to cleanly get this to work and upon my second attempt  (1st 6 months ago), I'm still having the same issues. dlls, access to the db, ??? 

I suggest you start with a clean machine and build from scratch to iron out the setup/install issues.

Really wanted this to be great, but back to LiteDB and RethinkDB.

Bob

**Comment by jeremydmiller** [comment]
@bobmcallan A couple elements of feedback on your feedback:

Absolutely nothing here was actionable or specific. Many, many people have been able to use Marten and we've had 70+ contributors, so your experience might just be an outlier.

I'm sorry your experience wasn't positive, but I'm closing this as it's not helpful.

**Comment by bobmcallan** [comment]
Ok. Thanks.
