### ISSUE TITLE
Marten.CommandLine "patch" on up-to-date database drops and recreates indexes

### ISSUE THREAD

**Issue by droach282** [JasperFx/marten#1043]
When running against a fully updated database (ie, after running the Marten.CommandLine `apply` command), the `patch` command appears to drop and recreate all indexes that have previously been deployed.  Since indexing can be an expensive proposition, shouldn't these be skipped instead?

(Note that this script was created with `AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate` and `DdlRules.TableCreation = CreationStyle.CreateIfNotExists`.)

**Comment by jeremydmiller** [comment]
I think the bigger question might be why Marten thinks your indexes have changed

**Comment by droach282** [comment]
No idea, unless postgres 10 is doing something interesting when I'm not looking.

**Comment by mysticmind** [comment]
@droach282 are you using any multi-key indexes? I fixed #1018, a little while ago, this could possibly related to this issue.

In any case please post an example of the index which you created to check on this.

**Comment by mysticmind** [comment]
@droach282 thanks for the repro, I was able to zero in on the issue and the fix is on its way

**Comment by droach282** [comment]
Good deal, thanks Babu!

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/marten/pull/1047. Will be in Marten 2.9.0
