### ISSUE TITLE
Eliminate usage of reflection in TypeMappings

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1049]
Bits of code we need in Npgsql are inexplicably private, so we've always used Reflection to get at it. That's slow, and their code has been buggy in npgsql 4, so let's just write out own mappings from .Net type to NpgsqlDbType

**Comment by oskardudycz** [comment]
I placed the [issue on Npgsql](https://github.com/npgsql/npgsql/issues/2176) that would be imho good first step to push it forward.
