### ISSUE TITLE
Single HiLo id generator per document store

### ISSUE THREAD

**Issue by oakio** [JasperFx/marten#1054]

**Comment by mdissel** [comment]
Resulting in unique ID's for each record in every table? If yes, nice enhancement :+1:

**Comment by jeremydmiller** [comment]
@oakio I'd be worried about contention if you do this. Why is this valuable?

**Comment by oakio** [comment]
The main reason is if I want to merge two tables into one, I will not have conflicts by id

**Comment by jeremydmiller** [comment]
@oakio Okay, but this one is "I take pull requests";) Some kind of way to declare that the Hilo sequence is shared?

**Comment by mysticmind** [comment]
> The main reason is if I want to merge two tables into one, I will not have conflicts by id
I would argue that this is *not* a typical use case Marten users would encounter on a regular basis. 

So going ahead and closing this. Feel free to re-open if someone wants to send us a PR :-)

**Comment by mysticmind** [comment]
Follow on note, please have a look at https://dba.stackexchange.com/questions/193788/what-can-go-wrong-using-the-same-sequence-across-multiple-tables-in-postgres. I would veto this feature in Marten.

**Comment by mdissel** [comment]
@mysticmind Would you accept a pull request that changes the current HiLoSequence behaviour to make it possible to override the entitiyname? by default the enitityname equals the doctype, but it can be overridden so you can have a sequence that is used by multiple tables.

**Comment by mdissel** [comment]
@oakio have you already started working on this request?

**Comment by oakio** [comment]
@mdissel no

**Comment by mdissel** [comment]
Still relevant for you?

**Comment by mdissel** [comment]
At first sight it seems that this is necessary:
- extend HiLoSettings with an optional SequenceName property
- use SequenceName if set in this method https://github.com/JasperFx/marten/blob/c8016cd903fc1e349163ed44d19df21cf88fe726/src/Marten/Schema/Identity/Sequences/SequenceFactory.cs#L61
and https://github.com/JasperFx/marten/blob/c8016cd903fc1e349163ed44d19df21cf88fe726/src/Marten/Schema/Identity/Sequences/SequenceFactory.cs#L68
