### ISSUE TITLE
Duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by siberianguy** [JasperFx/marten#1057]
When using BulkInsert in RewriteExisting mode, I regularly receive the error in the title. I've googled it a little bit and it seems like it could be related to temporary tables creation which is exactly what goes behinds the scenes in Marten

**Comment by Miggleness** [comment]
@siberianguy it may be a better idea to cleanup your source to ensure that this problem doesn't happen.  From what I've read, bulk insert operation evaluates against the state of the target table at the time the operation starts, and not the latest uncommitted state.  

Consider:
1. Validate uniqueness integrity at the source
2. Not use bulk inserts
3. Do you really need the unique index?

**Comment by oskardudycz** [comment]
@siberianguy are you still facing this issue? Could you try to check with latest Marten version? I think that https://github.com/JasperFx/marten/pull/1110/files might fix this issue.
