### ISSUE TITLE
Get NotImplementedException on CountAsync

### ISSUE THREAD

**Issue by wayne-o** [JasperFx/marten#1067]
Trying this:

`await _documentStoreClient.Query<Order>().CountAsync(x => x.EventInstanceId == x.Id)`

Throws NotImplementedException (where EventInstanceId  is a Guid):

![image](https://user-images.githubusercontent.com/178060/43834086-cd746592-9b04-11e8-8e96-65b0af970518.png)

**Comment by Miggleness** [comment]
@wayne-o which version of Marten are you using?

**Comment by jeremydmiller** [comment]
@wayne-o It's the comparison to another property on the document. That isn't something we support in the Linq provider because it's never come up before. You'd have to go to a bit of custom WHERE clause in the Linq statement for now. 

This code:

```
        public static object Value(this Expression expression)
        {
            if (expression is PartialEvaluationExceptionExpression)
            {
                var partialEvaluationExceptionExpression = expression.As<PartialEvaluationExceptionExpression>();
                var inner = partialEvaluationExceptionExpression.Exception;

                throw new BadLinqExpressionException($"Error in value expression inside of the query for '{partialEvaluationExceptionExpression.EvaluatedExpression}'. See the inner exception:", inner);
            }

            if (expression is ConstantExpression)
            {
                // TODO -- handle nulls
                // TODO -- check out more types here.
                return expression.As<ConstantExpression>().Value;
            }

// --> this is where we'd need to see that it's an expression that points at a field within the document
            throw new NotSupportedException();
        }

```

I don't think this would be crazy to support in the next version or so though.
