### ISSUE TITLE
Inheritence Hierarchy query and a potential feature request

### ISSUE THREAD

**Issue by SeanFarrow** [JasperFx/marten#1073]
Hi,

In the documentation regarding inheritance hierarchies, it states that searchable fields can only be declared on the top most class. I was wondering how this plays out when the base class is abstract and has properties.
I've got a case where I know I'm going to want to add several concrete types with the same properties so have abstracted them in to a base class.

I need to query on a property in of the base class and was wondering wht the best way of doing it was:
Firstly, extract this to it's own column, but then the question becomes how I tell Marten to use a custom data type.
or Improve Marten such that fields in base classes can be searches, but then I would like to know how I would do this and what would need to change.

Any help appreciated.
Cheers
Sean.

**Comment by jeremydmiller** [comment]
@SeanFarrow,

That's not quite accurate. At *this moment*, you can only specify indexes against properties or fields on the base class (but there's work coming soon to change that). You can happily query against anything in the subclass or the super class that you could normally with Marten. I don't think there's anything in Marten that needs to change for what you're asking for here.

**Comment by SeanFarrow** [comment]
@JeremyDMiller,
How soon is soon?
Ok, thanks.
How do I tell marten to use a datatype from another nuget package if I am creating a column for a specific field?
Cheers
Sean.

**Comment by jeremydmiller** [comment]
@SeanFarrow All of that is documented in our website. You don't have to explicitly make any kind of searchable field upfront to be able to query on a field. What is it that you think is missing?

**Comment by SeanFarrow** [comment]
What I’m trying to do is create a column on a field that is of a type not natively supported by PostGres and the Npgsql provider, they provide a plugin for this specific type, so I was wondering how the extra columns are created, such that I can use an external type.
It’s one of the types from the Nodatime library for reference.

**Comment by jeremydmiller** [comment]
Meh, that's a bit of a different issue. If the Noda types can be serialized to JSON with Newtonsoft, you don't need to do anything else to add any kind of field to a Marten-ized database. If you want to search on the NodaTime data elements, I don't know. You'd have to teach Marten's Linq provider how to interpret that.

**Comment by jeremydmiller** [comment]
There's an open issue somewhere about adding NodaTime support to the Linq provider, but nobody has taken it up yet

**Comment by SeanFarrow** [comment]
Ok, and how extensible is the linq provider. I’m happy tro do the work and potentially produce an add-on/plugin.

**Comment by SeanFarrow** [comment]
Yep, I’ve just found it and commented, so feel free to close this.
