### ISSUE TITLE
Marten with CockroachDB

### ISSUE THREAD

**Issue by jinhong-** [JasperFx/marten#1075]
Did anyone try this before? Seems to have API compatibility with Postgres's API specifications

**Comment by mysticmind** [comment]
@jinhong- This is very interesting. CockroachDB fully supports PostgreSQL wire protocol compatibility and also supports JSONB since v2.0. I don't think anyone in the Marten community tried this. I think it will be worth trying out...

**Comment by jinhong-** [comment]
I personally have yet to try this. Was hoping someone here already have experience with it

**Comment by jinhong-** [comment]
Just a quick update, i deployed cockroachdb and attempted to hook it up with marten. Immediately after i attempted to run it, i get the following error: unknown function: pg_get_functiondef(). So i guess it's a no go

**Comment by mysticmind** [comment]
@jinhong, can you please go ahead and close this issue?

**Comment by jinhong-** [comment]
Will do. was hoping someone with more expertise on marten could give more insights and get it working

**Comment by mysticmind** [comment]
Even though CockroachDB has wire compatibility, Marten via Npgsql uses many
pg_* functions for schema management etc which won't be available in
CockroachDB. Besides we also use JavaScript functions via plv8 extensions.

I think it will be difficult to get it working with CockroachDB.

**Comment by dbist** [comment]
https://github.com/JasperFx/weasel/issues/78
