### ISSUE TITLE
Use long data type for Event Version

### ISSUE THREAD

**Issue by jinhong-** [JasperFx/marten#1080]
For the next version of Marten, it would be good to upgrade the version for events to long instead of int. This will give streams with high event counts more room to grow

**Comment by oskardudycz** [comment]
I think that it's a good idea. @jeremydmiller what do you think?

**Comment by jeremydmiller** [comment]
Ugh, yes, it's a good idea. Let me see if I can sneak that in right now

**Comment by jeremydmiller** [comment]
@oskardudycz @jinhong- So yes and no. I'm not gonna try to tackle it right now because we don't have any clean way to generate the table delta to bump the data type from int to long. Since we're in a hurry to get to 3.0, I think this slides to 4.0. But saying that, 4.0 might come reasonably soon.

**Comment by oskardudycz** [comment]
@jeremydmiller fine for me, I can help on bringing this long version
