### ISSUE TITLE
AutoCreate.CreateOrUpdate not being respected

### ISSUE THREAD

**Issue by MadMathMike** [JasperFx/marten#1083]
The comment on the AutoCreate.CreateOrUpdate enum says "Will never destroy existing tables. Attempts to add missing columns or missing tables", but when the AutoCreateSchemaObjects option is set to that value, a DROP statement is still being executed. Here is a failing test:
[Fact]
public async Task should_not_recreate_existing_matching_table()
{
    using (var store = DocumentStore.For("Server=localhost; Database=postgres; User Id=postgres; Password=postgres;"))
    {
        using (var session = store.OpenSession())
        {
            var users = await session.Query<User>().ToListAsync();
        }
    }

    // this second connection string just needs to use a login that isn't a superuser and isn't the owner of the previously created mt_doc_user table
    using (var store = DocumentStore.For(options =>
    {
        options.Connection("Server = localhost; Database = postgres; Integrated Security = true;");
        options.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
    }))
    {
        using (var session = store.OpenSession())
        {
            session.Store(new User());
            session.SaveChanges();
        }
    }
}

I have no idea why the formatting on the above code is whack.

**Comment by jeremydmiller** [comment]
@MadMathMike Dollars to donuts, it's a permission problem from the "not superuser" login. It probably doesn't have rights to query the metadata tables that Marten has to depend on to see whether or not the table actually exists or matches what's there. As to why there's a DROP instead of just a CREATE, I don't remember. When you're in the mode with restricted access, I'd strongly recommend going for AutoCreate.None.

**Comment by MadMathMike** [comment]
@jeremydmiller That makes sense. Curiously, and I suppose this is more of a postgres question, but when Marten is querying the metadata tables with a user that does not have rights to those tables, what happens with the query? I would expect an exception to be thrown, but perhaps zero results are returned instead? I did see the code in the Marten repository that queries the metadata tables, and I didn't see any special exception handling around executing that query (in Table.cs).

**Comment by MadMathMike** [comment]
Also, this is still a bug, correct? A DROP statement is being executed even though I specified AutoCreate.CreateOrUpdate.

**Comment by MadMathMike** [comment]
If my research is correct, you can successfully query the metadata tables, but only rows pertaining to objects for which you have sufficient permission (such as OWNER) are returned, which would explain the metadata issue you mentioned.

**Comment by jeremydmiller** [comment]
@MadMathMike I don't think it's something we can easily fix. Call it a bug all you want, but I'm not sure there's much to do other than update documentation on this kind of thing

**Comment by MadMathMike** [comment]
Yup, definitely a good idea to update documentation. Pretty dangerous to claim "Will never destroy existing tables" when it still tries to execute a DROP statement. :-)

**Comment by jeremydmiller** [comment]
@MadMathMike "Pretty dangerous to claim "Will never destroy existing tables" when it still tries to execute a DROP statement. :-)" -- if I'd anticipated how you happened to be configuring Postgresql and how that would impact the functionality in the way you saw here, the documentation wouldn't say that. I'm sorry that I have not attained omniscience yet.

**Comment by MadMathMike** [comment]
I'm sorry for my passive-aggressive action of closing the ticket after a final quip from me. I shouldn't have done that. 

That being said, I know this area of code is a sore spot for you, but this isn't about my configuration. Under what condition _should_ a `DROP TABLE` statement be sent to the npgsql connection if the configured setting says that it "Will never destroy existing tables"? I genuinely can't think of any. I'm not expecting omniscience, but unless there is a valid case for still writing that command, this is simply a bug.
