### ISSUE TITLE
Compiled queries with constant expressions causes Npgsql exceptions

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/marten#1089]
The following compiled query fails with an invalid set of command parameters:
```
public class CountAuthenticatedUsersForSubscriberQuery : ICompiledQuery<UserAuthentication, int>
{
	public string SubscriberId { get; set; }

	public Expression<Func<IQueryable<UserAuthentication>, int>> QueryIs()
	{
		return q => q.Count(ua => ua.SubscriberId == SubscriberId && ua.Expires >= DateTimeOffset.UtcNow && !ua.IsTemporary);
	}
}
```

This generates the following SQL:
```
select count(*) as number from public.mt_doc_userauthentication as d where ((d.data ->> 'SubscriberId' = :arg0 and public.mt_immutable_timestamp(d.data ->> 'Expires') >= :arg1) and CAST(d.data ->> 'IsTemporary' as boolean) = :arg2)
```

Clearly this expects 3 command arguments, but when running the code I get an error from Npgsql indicate that there was an error near ":", and upon command inspection I see that only `arg0` and `arg1` are included in the command.  Removing the `&& !ua.IsTemporary` causes the same problem, except that this time only `arg0` is generated.

Changing the compiled query definition to the following works as expected:
```
public class CountAuthenticatedUsersForSubscriberQuery : ICompiledQuery<UserAuthentication, int>
{
	public string SubscriberId { get; set; }

	// NOTE: The following properties are required in order for the compiled query to function properly
	public DateTimeOffset Now { get; } = DateTimeOffset.UtcNow;

	public bool IsTemporary { get; } = false;

	public Expression<Func<IQueryable<UserAuthentication>, int>> QueryIs()
	{
		return q => q.Count(ua => ua.SubscriberId == SubscriberId && ua.Expires >= Now && ua.IsTemporary == IsTemporary);
	}
}
```

**Comment by jeremydmiller** [comment]
This is going to have to be a documentation issue and not really a bug per se. The compiled query planning is never going to be able to handle DateTimeOffset.UtcNow internally because ReLinq reduces that to a value.

**Comment by jeremydmiller** [comment]
Tracking the documentation here: #1555
