### ISSUE TITLE
Unique index per tenant

### ISSUE THREAD

**Issue by Nysosis** [JasperFx/marten#1108]
Currently it doesn't seem possible to configure unique indices to take multi-tenancy into consideration.

Would it make sense to extend the `UniqueIndexType` enum to have a `ComputedPerTenant` option, which if set on a property will include the `tenant_id` column onto the index definition when building the table?

**Comment by oskardudycz** [comment]
@Nysosis sorry for long answer. I'll review such possibility and get back with a feedback.

**Comment by oskardudycz** [comment]
@Nysosis it's implemented in https://github.com/JasperFx/marten/pull/1212. It'll be available in Marten 3.5.0
