### ISSUE TITLE
Querying with .Any on simply type inner collections

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#112]
This works fine if you are querying a nested property such as .Single(x => x.MyCollection.Any(_ => _.MyProperty == 123)), but if the collection is just a simple collection of integers/string/whatever it doesn't work, for example 

.Single(x => x.MyCollection.Any(_ => _ == 123))

It fails with: Sequence contains no elements

**Comment by jeremydmiller** [comment]
Can you try _.MyCollection.Contains(123) instead? That is already supported

**Comment by phinett** [comment]
I get:  The method or operation is not implemented.

My query:
var users = session.Query<User>().Where(a => a.MyCollection.Contains(1)).ToList();

**Comment by jeremydmiller** [comment]
Hey @phinett, what's the type of your child collection? I'm guessing it's not `string[]`. `IEnumerable<string>`, `List<string>`?

**Comment by phinett** [comment]
List<int>

**Comment by jeremydmiller** [comment]
Bueno, thanks. I'll shoot for the fix for this this morning.

**Comment by phinett** [comment]
Brilliant thank you...have another issue which i'll post about shortly too.

**Comment by jeremydmiller** [comment]
@phinett I've got `List<T>.Contains(value)`, `IList<T>.Contains(value)`, and `IEnumerable<T>.Contains(value)` working in the v0.6.2 nuget I just published. `Collection.Any(_ => value)` is being a lot more work and that's missing as of yet.
