### ISSUE TITLE
Dependency Resolution

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#1122]
On the back of #1119, I wanted to start a discussion on the possibility of making Marten more extensible through dependency resolution.

At it's most basic, this could mean `StoreOptions` having a property `Func<T> GetInstance<T>` that users can set to provide custom implementations of interfaces (e.g. `IManagedConnection`) from their preferred IoC/DI container.

Thoughts?

**Comment by jeremydmiller** [comment]
To what end? What concrete use cases are you looking for here?

**Comment by cocowalla** [comment]
@jeremydmiller #1119 _was_ a good example of where this might have been useful - swapping out `IManagedConnection` for a version that included retry handling. That specific example is of course moot now that Marten has retries built-in 😄 

You did comment that `IManagedConnection` was really an implementation detail, and TBH since then I don't recall coming across any other situations where this might be helpful. Perhaps this should just be closed out for now, and potentially revisitied if any extensibility points emerge in the future?

**Comment by jeremydmiller** [comment]
Closed it is, thanks for the response

**Comment by oskardudycz** [comment]
I don't have opinion about `IManagedConnection` but I believe we should have some mechanism to inject plugins and replace parts of the Marten. Good example can be `NodaTime` issues. Imho we should really work on Marten modularity.
That will make Marten more flexible and also give user more options to contribute or swap some implementations without our work.
