### ISSUE TITLE
Feature proposal: General purpose event handlers

### ISSUE THREAD

**Issue by horsdal** [JasperFx/marten#1127]
When using the event store, I would find it useful to be able to register event handlers for doing other things than projections - like sending an integration event on a queue or whatever other application specific thing.

What I have in mind is to create a handler by implementing a new interface, `IAsyncEventHandler`:
``` 
public class MyHandler : IAsyncEventHandler<MyEvent>
{
    public Task Handle(MyEvent @event, IDocumentSession session, in CancellationToken token)
    {
        // Do something async to handle the event
        return Task.CompletedTask;
     }
} 
```

and registering a factory function with the document store:

```
    var docStore = DocumentStore.For(x =>
    {
        x.AddAsyncEventHandlers(@type => /* create instance of @type which is an IAsyncEventHandler */);
         // other config
    }
```
 
When an event of type `MyEvent` has been appended to a stream and `SaveChanges` is called on `DocStore` the factory would be called and the handlers it returns would be called.

There should probably also be a sync version.

Would that makes sense for Marten? If so, I'd be happy take a stab at contributing it.

PS. I made a prototype of this and put it in this gist: https://gist.github.com/horsdal/a05f051f20b24b40b0c210fb69120ea6

**Comment by jeremydmiller** [comment]
You can already do this with custom implementations of the `IProjection` interface that just doesn't build out any projected views. Or if you want the hook to be at SaveChanges() time, you can use an `IDocumentSessionListener`.

**Comment by horsdal** [comment]
Thanks for the quick response.
What I have today is an `IDocumentSessionListener` - I'll probably just put some added convenience in an add-on package that I can consume myself. That'll get me what I'm after.
Looking at `DocumentSession.SaveChanges` it looks like inline projections and 'BeforeSaveChangesAsync' on listeners run right after each other, and then `AfterCommitAsync` on listeners is after the transaction is commited, right?
