### ISSUE TITLE
Re-evaluate ManagedConnection and retry policy implementation for performance optimization

### ISSUE THREAD

**Issue by mysticmind** [JasperFx/marten#1128]
Re-evaluate `IRetryPolicy` and the `ManagedConnection` with an eye toward performance optimization. Having to do a Lambda on every command is a touch expensive. Refer #1124 review comment

**Comment by jeremydmiller** [comment]
I took this today. Did basically what @mysticmind said about eliminating Lambda usages, except I did leave the Lambdas within the Polly usage. It's an extra object allocation for the Lambda vs. needing to do a dictionary lookup from the Polly Context, so I left it alone.

**Comment by jeremydmiller** [comment]
Done in a branch.
