### ISSUE TITLE
Problems with HiLo sequence in ambient transaction

### ISSUE THREAD

**Issue by zminic** [JasperFx/marten#1140]
I have observed following behavior and I'm not sure whether it is a bug in Marten:

When session is enlisted in ambient transaction using "SessionOptions.ForCurrentTransaction()" and later calling .Store() method on this session (to insert record) throws "Nested/Concurrent transactions aren't supported."

I have tracked down this to "AdvaneceToNextHi" method in HiloSequence class. Per my understanding this method tries to create new transaction by calling "npgsqlConnection.BeginTransaction" instead of using ambient transaction (for my scenario).

Is this a bug or I missed something?

**Comment by jeremydmiller** [comment]
The HiloSequence wouldn't be related. The lookup of new HiLo sequence numbers happens on a separate connection, so that can't be your cause.


Can you show me the code you're using to activate the session w/ the ambient transaction? Whatever the problem is, it's in those mechanics. And a stacktrace too please?

**Comment by zminic** [comment]
Hi Jeremy, thanks for the response.

This is part of the code in question:

```csharp
using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
using (var session = store.OpenSession(new SessionOptions {
    EnlistInAmbientTransactionScope = true,
    OwnsTransactionLifecycle = false,
    Tracking = DocumentTracking.None
}))
{
    // load target subsystem
    targetSubsystem = await session.LoadAsync<Subsystem>(targetLayout.SubsystemId);

    // some modifications on targetSybsystem... not relevant

    // calling some other business layer logic which does saving (uses store.OpenSession(SessionOptions.ForCurrentTransaction())) to open new session and save this object inside this transaction. This works...
    await subsystemManager.UpdateSubsystem(mapper.Map<SubsystemUpdateDto>(targetSubsystem));

    // insert layout version
    var versionToInsert = mapper.Map<LayoutVersionDto>(importContainer.LayoutVersion);

    // some modifications on versionToInsert... not relevant

    // calling some other business layer logic which opens new session (uses store.OpenSession(SessionOptions.ForCurrentTransaction())). This also works...
    var nextVersion = await GetNextVersion(targetLayout.Id);
    versionToInsert.VersionMajor = nextVersion[0];
    versionToInsert.VersionMinor = nextVersion[1];

    // calling some other business layer logic which opens new session (uses store.OpenSession(SessionOptions.ForCurrentTransaction())). This fails with not supported exception!
    await UpdateLayoutVersion(versionToInsert);

    scope.Complete();
}
```

In the code above you can see the way I'm opening session, calling some other methods in class that have their own sessions opened with "SessionOptions.ForCurrentTransaction()".

The last call breaks with not supported exception. There I also open session with  "SessionOptions.ForCurrentTransaction()".

This is the call stack when visual studio breaks on exception:

![image](https://user-images.githubusercontent.com/5235407/48714921-1162f880-ec14-11e8-9226-358ff3108c2e.png)

Do you need some other info?

**Comment by jeremydmiller** [comment]
I guess a couple more questions then, and can you just give me the actual stacktrace message through and not the screen shot?

Is this behavior consistent, or does it only happen occasionally?
Do you have to use the ambient transaction, or could you just use the native transactions? Could you just have the session scoped so that it's shared between all the pieces involved in this operation so you can use a native transaction instead (which is always more efficient anyway)?

There might be something in Npgsql itself that tries to use the ambient transaction automatically that we didn't account for. I can clearly tell you I wasn't anticipating this combination of things when we added the ambient transaction support.

**Comment by zminic** [comment]
Complete stack trace:

    at Npgsql.NpgsqlConnection.BeginTransaction(IsolationLevel level) in C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:line 565
    at Marten.Schema.Identity.Sequences.HiloSequence.AdvanceToNextHi()
    at Marten.Schema.Identity.Sequences.HiloSequence.NextLong()
    at Marten.Schema.Identity.Sequences.LongHiloGenerator.Assign(ITenant tenant, Int64 existing, Boolean& assigned)
    at Marten.Schema.Identity.IdAssigner`2.Assign(ITenant tenant, TDoc document, Boolean& assigned)
    at Marten.DocumentSession.Store[T](T[] entities)
    at Holos.Middleware.BusinessLayer.LayoutManager.UpdateLayoutVersion(LayoutVersionDto layoutVersionDto) in D:\sources\Holos.Middleware\Holos.Middleware.BusinessLayer\LayoutManager.cs:line 192
    at Holos.Middleware.BusinessLayer.LayoutManager.ImportLayoutVersion(Stream inputStream, Int64 layoutId) in D:\sources\Holos.Middleware\Holos.Middleware.BusinessLayer\LayoutManager.cs:line 370

This is consistent behavior, happens every time.

I was hoping to reuse all methods I already have there with their own sessions, but if there is no way around it i will try to redesign everything to use native transactions. I can't change public interface, but i could create private methods that accept native transaction or create new for every affected use case.

**Comment by zminic** [comment]
After some digging I have found the solution.

Npgsql automatically enlists in ambient transactions (from ver 3.3), but this can be turned off by setting Enlist=false in connection string.

After this change I was getting error that prepared transactions are disabled and had to change "max_prepared_transactions" in postgresql.conf.
