### ISSUE TITLE
Async BulkInsert

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#1144]
`IDocumentStore.BulkInsert` is not async, whereas everything on `IDocumentSession` does have the option of async.

I was just wondering why `BulkInsert` did not use async/await?

**Comment by oskardudycz** [comment]
@cocowalla afaik probably noone ever had time to implement it. @jeremydmiller is that correct? 

I think that it would be good idea to add async option here as this method might be potentialy context blocking operation

**Comment by cocowalla** [comment]
I started on a PR for this, then realised that NPGSQL doesn't yet have async versions of the `COPY` methods that are used for bulk insertion: https://github.com/npgsql/npgsql/issues/1632

So this one is blocked for now.

**Comment by jeremydmiller** [comment]
I've got this one today after @mysticmind updated us to npgsql v5. About to push the changes in a minute. **Lots** of copy/paste/change code.
