### ISSUE TITLE
Query with entity's own property comparison not working as expected

### ISSUE THREAD

**Issue by kasparurban** [JasperFx/marten#1148]
When comparing entity's own properties in a query results in a query where properties are compared vice-versa.

Example: `session.Query<TestEntity>().Where(e => e.Second > e.First)`

Expected result: `select d.data, d.id, d.mt_version from public.mt_doc_testentity as d where CAST(d.data ->> 'Second' as integer) > CAST(d.data ->> 'First' as integer)`

Actual result: `select d.data, d.id, d.mt_version from public.mt_doc_testentity as d where CAST(d.data ->> 'First' as integer) > CAST(d.data ->> 'Second' as integer)`

Simple repro code here: https://gist.github.com/kasparurban/1e816c190d8f03abbf364ff4eb8f0e6f

**Comment by karelg** [comment]
Any news on this one? We have a workaround for now, but it would be great, if this eventually gets fixed.

**Comment by mysticmind** [comment]
@karelg I did have a brief look at this issue but didn't make much progress. Hopefully we can address this in the next release.

**Comment by oskardudycz** [comment]
@kasparurban should be fixed with https://github.com/JasperFx/marten/pull/1264, so in [Marten 3.6.0](https://github.com/JasperFx/marten/milestone/36)
