### ISSUE TITLE
AssertDatabaseMatchesConfiguration throws exception for Duplicate field with name same as PostgreSQL keyword

### ISSUE THREAD

**Issue by mstralenya** [JasperFx/marten#1151]
I am writing migration tool and when I'm calling AssertDatabaseMatchesConfiguration  it fails because field name for index is the same as reserved word (e.g. trim) and it's wrapped in quotes.

Looks like it issue in Marten.Schema.IndexDefinition.Matches method - it's adding additional set of quotes before comparing (https://github.com/JasperFx/marten/blob/master/src/Marten/Schema/IndexDefinition.cs#L108)

**Comment by mysticmind** [comment]
@mstralenya can you please provide a repro example?

**Comment by mstralenya** [comment]
@mysticmind sure
```
using System;
using Marten;

namespace ConsoleApp1
{
	class Car
	{
		public string Id { get; set; }
		public string Trim { get; set; }
	}
	
	class Program
	{
		static void Main(string[] args)
		{
			var store = DocumentStore.For(_ =>
			{
				_.Connection("host=localhost;database=test;password=password1;username=postgres");
				_.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
				_.Schema.For<Car>()
					.Duplicate(car => car.Trim);
			});
			
			store.Schema.ApplyAllConfiguredChangesToDatabase();
			store.Schema.AssertDatabaseMatchesConfiguration();
			
			Console.WriteLine("Hello World!");
		}
	}
}
```

**Comment by mysticmind** [comment]
@mstralenya Duplicate field column name in table becomes "trim" and it is a PostgreSQL keyword. Hence the error. Can you use a different column name and try?

**Comment by mstralenya** [comment]
@mysticmind problem is that we need use 'trim' as field name and looks like Marten does not allow to choose different name for duplicated column.
Also, as I said in first post, looks like `Matches` method does always adds quotes for field name, even if it's already has quotes (Marten adds quotes for plsql keywords as far as I know)

**Comment by mysticmind** [comment]
@mstralenya I am checking the codebase and noticing that `DuplicateField` has an option to set Column name albeit it is not exposed in the methods via the `StoreOptions.Schema`. I will need to debug this further.

**Comment by mysticmind** [comment]
@mstralenya I was able to run a test with your sample repro and observing that the column `trim` gets added to table fine. And as you had observed the different the the double quotes in the `IndexDefinition.Matches` i.e. actual=`CREATE INDEX mt_doc_car_idx_trim ON public.mt_doc_car (""trim"");` and `ToDDL()` generates `CREATE INDEX mt_doc_car_idx_trim ON public.mt_doc_car ("trim");`

**Comment by mysticmind** [comment]
@mstralenya I have fixed the issue to remove the double quotes, will send a PR with the fix and unit test. You can expect the fixes to the above in the next release update.
