### ISSUE TITLE
Global Interceptors for Insert/Update/Delete

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#116]
Feature Request:

Interceptors. 

Would be fun to implement I believe. But would be awesome to have document level interceptors. 

RavenDB has `IDocumentStoreListener` which I don't like because it's a global helper which handles only Before / After Store. And while this is helpful and good, I think it would be good to have interceptors at document level too so we can intercept and modify or raise events and such.

**Comment by jeremydmiller** [comment]
@phillip-haydon @CoreyKaylor & I were kicking a similar idea around for how to support the .Net flavor for projections. I think this is pretty similar to what we're thinking for plugging in the transactions.

**Comment by phillip-haydon** [comment]
@jeremydmiller did you reply to the right issue or did you mean to reply to #146 or ??

**Comment by jeremydmiller** [comment]
No, this one. What I'm thinking is that we have a very generic interface like:

IChangeListener
----------------------
void Before(IUnitOfWork, IDocumentSession)   // logging, but also give a chance to modify the unit of work or add other actions for .Net projections at the same time
void After(IUnitOfWork, IDocumentSession)      // logging maybe? post-processing in event capture

In this case, we'd have `IUnitOfWork` expose all of the queued up documents for updating and document/id's for deletes, but also have methods to alter the unit of work.

**Comment by jeremydmiller** [comment]
One more thing, I don't think we have a clean way to differentiate between inserts & updates

**Comment by phillip-haydon** [comment]
Without looking at the internals. If using HiLo can we not mark as insert when assigning the Id?

**Comment by phillip-haydon** [comment]
As long as you get access to the actual document then you could handle it yourself IF you needed to know if a doc is new or existing by marking it yourself.

So I don't see it as too much of an issue if we cannot differ on inserts/updates.
