### ISSUE TITLE
How to perform aggregates across multiple streams?

### ISSUE THREAD

**Issue by primalfear** [JasperFx/marten#1166]
Hi Guys,
Please excuse if this is a novice question, I am still ramping up with using marten :)

What i am trying to solve, is I have an aggregate, which is made up from multiple streams, and am trying to work out how it update it if any of the streams are updated.

I bit of info, into what we are actually trying to do, in case a bit more context is needed.
We are building a flavor of CRM and Marketing Automation platform, and are using event sourcing for management of consumer profiles.

When interacting with "Brand" online assets (websites, social pages, competitions, etc.) We receive interactions to our platform. These interactions contain at least 1 identifier for a consumer (mobile number, email address, social account id, etc...) along with other information relevant to the interaction.

We are planning on storing the events received per identifier, so that we can handle subscriptions and preferences, per identifier. (This basically allows us to build a complete "Profile" per identifier)

A Consumer, is basically a collection of identifiers. 
These are associated when we receive an interaction, with more than one identifier.
To create this consumer view, I need to be able to aggregate across multiple identifier streams.

Please let me know if there is additional info I can provide, etc.
I look forward to comments :)

**Comment by mysticmind** [comment]
@primalfear you will need to do a custom project from multiple streams, please check http://jasperfx.github.io/marten/documentation/events/projections/custom/

**Comment by primalfear** [comment]
Awesome.... Thanks for the pointer :)
Am not sure how i missed this bit of documentation, have been spending a fair bit of time in the doc of late. On a side note... the documentation for this project is really pretty good.... I have managed to get a mostly sort of prototype up in 3 days :)

**Comment by mysticmind** [comment]
@primalfear closing this issue.
