### ISSUE TITLE
Duplicated DateTime changed type from Marten version 2.5 to 3.4

### ISSUE THREAD

**Issue by Leh2** [JasperFx/marten#1177]
Has the db type for duplicated datetimes changed from version 2.5 to 3.3? In 2.5 it was created with timestamp with time zone, but 3.3 will like it to be timestamp without time zone.

Updated to 3.3 and 4 out of 5 tables fails on migration. All 4 tables has duplicated datetimes, and when I changed the type in the db to without time zone, migration goes well.

Seems this is the place where it did go wrong: https://github.com/JasperFx/marten/commit/24cbd707b31b8b6c85ccce32a157670aac33ff8f#diff-e8e0cf443036c7fa3e51325b1310fc96R40

**Comment by oskardudycz** [comment]
Ok, I made investigation. This is simmilar case as we had with enum. Version 3.0 provided fix for wrong mapping of datetime. In TypeMappings and in all other places `DateTime` is mapped to `timestamp without time zone` See in [TypeMappings](https://github.com/JasperFx/marten/blob/master/src/Marten/Util/TypeMappings.cs#L43)

```
PgTypes[typeof (DateTime)] = "timestamp without time zone";
```
Previous usage was not consistent. I'll provided switch for keeping backward compatible. Simmilar to `DuplicatedFieldEnumStorage `.

**Comment by oskardudycz** [comment]
@Leh2 @jeremydmiller I provided fix for that in https://github.com/JasperFx/marten/pull/1179
