### ISSUE TITLE
Querying by subclass across all tenants not working

### ISSUE THREAD

**Issue by kasparurban** [JasperFx/marten#1181]
Tenant id is still taken into account when querying by subclass across all tenants.

Example: `session.Query<AdminUser>().Where(u => u.AnyTenant()).ToArray()`

Result: `select d.data, d.id, d.mt_doc_type, d.mt_version from public.mt_doc_user as d where (1=1 and ((d.mt_doc_type = 'admin_user') and d.tenant_id = :tenantid))
  tenantid: *DEFAULT*
`

Querying by base class works as expected.

Simple repro here: https://gist.github.com/kasparurban/76708d415983b62e2feb7064e4396fae

**Comment by karelg** [comment]
Would be good, if someone can take a look at this. There are also no good workaround for this, so this is causing real pain.
