### ISSUE TITLE
Consider using shared code formatting rules

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#1184]
Possible options:
- style cop,
- resharper settings,
- rider settings.

**Comment by tonykaralis** [comment]
@oskardudycz I plan on doing the following:
* Will do some research on the various styles and get back to you with more info. 
* Will discuss details before refactoring anything.

**Comment by tonykaralis** [comment]
@oskardudycz not forgotten about these issues. I will get around to it, day job is quite hectic at the moment.

**Comment by loraderon** [comment]
Have you considered https://github.com/belav/csharpier (like prettier but for C#)?
