### ISSUE TITLE
Marten.Schema.MartenSchemaException

### ISSUE THREAD

**Issue by dapalmi** [JasperFx/marten#1185]
Code:

```
    var store = DocumentStore.For(_ =>
    {              
    _.Connection(Configuration.GetConnectionString("PostgresDb"));                
    _.DatabaseSchemaName = "structure";
    _.Schema.For<Structure>();
    });
    store.Schema.ApplyAllConfiguredChangesToDatabase();
```

```
public sealed class Structure : AggregateBase
    {
        public Structure() { }

        public Structure(Guid id, string field1, string field2)
        {
            Id = id;
            Field1 = field1;
            Field2 = field2;
        }

        public void UpdateStructure(string field1, string field2)
        {
            Field1 = field1;
            Field2 = field2;
        }

        public string Field1 { get; private set; }
        public string Field2 { get; private set; }
    }

```

```
public abstract class AggregateBase
    {
        // For indexing our event streams
        public Guid Id { get; protected set; }

        private readonly List<object> uncommittedEvents = new List<object>();
        private readonly Dictionary<Type, Action<object>> handlers = new Dictionary<Type, Action<object>>();

        // Get the deltas, i.e. events that make up the state, not yet persisted
        public IEnumerable<object> GetUncommittedEvents()
        {
            return uncommittedEvents;
        }

        // Mark the deltas as persisted.
        public void ClearUncommittedEvents()
        {
            uncommittedEvents.Clear();
        }

        // Infrastructure for raising events & registering handlers

        protected void Register<T>(Action<T> handle)
        {
            handlers[typeof(T)] = e => handle((T)e);
        }

        protected void RaiseEvent(object @event)
        {
            ApplyEvent(@event);
            uncommittedEvents.Add(@event);
        }

        private void ApplyEvent(object @event)
        {
            handlers[@event.GetType()](@event);
        }
    }
```

Exception:

"DDL Execution for 'All Configured Changes' Failed!\n\nDO $$\nBEGIN\n    IF NOT EXISTS(\n        SELECT schema_name\n          FROM information_schema.schemata\n          WHERE schema_name = 'structure'\n      )\n    THEN\n      EXECUTE 'CREATE SCHEMA structure';\n    END IF;\n\nEND\n$$;\n\nCREATE OR REPLACE FUNCTION structure.mt_immutable_timestamp(value text) RETURNS timestamp without time zone LANGUAGE sql IMMUTABLE AS $function$\n    select value::timestamp\n$function$;\n\nCREATE OR REPLACE FUNCTION structure.mt_immutable_timestamptz(value text) RETURNS timestamp with time zone LANGUAGE sql IMMUTABLE AS $function$\n    select value::timestamptz\n$function$;\n\nDROP TABLE IF EXISTS structure.mt_doc_structure CASCADE;\nCREATE TABLE structure.mt_doc_structure (\n    id                  uuid CONSTRAINT pk_mt_doc_structure PRIMARY KEY,\n    data                jsonb NOT NULL,\n    mt_last_modified    timestamp with time zone DEFAULT transaction_timestamp(),\n    mt_version          uuid NOT NULL default(md5(random()::text || clock_timestamp()::text)::uuid),\n    mt_dotnet_type      varchar \n);\nCOMMENT ON TABLE structure.mt_doc_structure IS 'origin:Marten.IDocumentStore, Marten, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null';\n\nCREATE OR REPLACE FUNCTION structure.mt_upsert_structure(doc JSONB, docDotNetType varchar, docId uuid, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$\nDECLARE\n  final_version uuid;\nBEGIN\nINSERT INTO structure.mt_doc_structure (\"data\", \"mt_dotnet_type\", \"id\", \"mt_version\", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp())\n  ON CONFLICT ON CONSTRAINT pk_mt_doc_structure\n  DO UPDATE SET \"data\" = doc, \"mt_dotnet_type\" = docDotNetType, \"mt_version\" = docVersion, mt_last_modified = transaction_timestamp();\n\n  SELECT mt_version FROM structure.mt_doc_structure into final_version WHERE id = docId ;\n  RETURN final_version;\nEND;\n$function$;\n\n\nCREATE OR REPLACE FUNCTION structure.mt_insert_structure(doc JSONB, docDotNetType varchar, docId uuid, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$\nBEGIN\nINSERT INTO structure.mt_doc_structure (\"data\", \"mt_dotnet_type\", \"id\", \"mt_version\", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp());\n\n  RETURN docVersion;\nEND;\n$function$;\n\n\nCREATE OR REPLACE FUNCTION structure.mt_update_structure(doc JSONB, docDotNetType varchar, docId uuid, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$\nDECLARE\n  final_version uuid;\nBEGIN\n  UPDATE structure.mt_doc_structure SET \"data\" = doc, \"mt_dotnet_type\" = docDotNetType, \"mt_version\" = docVersion, mt_last_modified = transaction_timestamp() where id = docId;\n\n  SELECT mt_version FROM structure.mt_doc_structure into final_version WHERE id = docId ;\n  RETURN final_version;\nEND;\n$function$;\n\n\nCREATE OR REPLACE FUNCTION structure.mt_transform_patch_doc(doc JSONB, patch JSONB) RETURNS JSONB AS $$\n\n  var module = {export: {}};\n\n  'use strict';\n\nfunction findDeep(doc, parts){\n    var element = doc;\n\n    for (var i = 0; i < parts.length; i++){\n        var child = parts[i];\n        if (!element.hasOwnProperty(child) || !element[child]){\n            element[child] = {};\n        }\n\n        element = element[child];\n    }\n\n    return element;\n}\n\nfunction locate(doc, path){\n    var parts = path.split('.');\n\n    var element, prop;\n\n    if (parts.length > 0){\n        prop = parts.pop();\n        element = findDeep(doc, parts);\n    }\n    else {\n        prop = path;\n        element = doc;\n    }\n\n    return {element: element, prop: prop};\n}\n\nfunction setValue(doc, patch, location){\n    location.element[location.prop] = patch.value;\n\n    return doc;\n}\n\nfunction deleteValue(doc, patch, location){\n    delete location.element[location.prop];\n\n    return doc;\n}\n\nfunction duplicateValue(doc, patch, location){\n    var value = location.element[location.prop];\n    for (var i = 0; i < patch.targets.length; i++) {\n      var copyTo = locate(doc, patch.targets[i]);\n      copyTo.element[copyTo.prop] = value;\n    }\n\n    return doc;\n}\n\nfunction incrementValue(doc, patch, location){\n    var interval = 1;\n    if (patch.increment){\n        interval = parseInt(patch.increment);\n    }\n\n    var existing = 0;\n    if (location.element[location.prop]){\n        existing = parseInt(location.element[location.prop]);\n    }\n\n    location.element[location.prop] = existing + interval;\n\n    return doc;\n}\n\nfunction incrementFloat(doc, patch, location){\n    var interval = 1;\n    if (patch.increment){\n        interval = parseFloat(patch.increment);\n    }\n\n    var existing = 0;\n    if (location.element[location.prop]){\n        existing = parseFloat(location.element[location.prop]);\n    }\n\n    location.element[location.prop] = existing + interval;\n\n    return doc;\n}\n\nfunction appendElement(doc, patch, location){\n    if (!location.element[location.prop]){\n        location.element[location.prop] = [];\n    }\n\n    location.element[location.prop].push(patch.value);\n\n    return doc;\n}\n\nfunction appendElementIfNotExists(doc, patch, location){\n     if (!location.element[location.prop]){\n        location.element[location.prop] = [];\n    }\n\n    var array = location.element[location.prop];\n    var patchValueAsJSONString = JSON.stringify(patch.value);\n    for(var i = 0; i < array.length; i++)\n    {\n        var elementAsJSONString = JSON.stringify(array[i])\n        if (patchValueAsJSONString === elementAsJSONString)\n            return doc;\n    }\n\n    location.element[location.prop].push(patch.value);\n\n    return doc;\n}\n\nfunction insertElement(doc, patch, location){\n    if (!location.element[location.prop]){\n        location.element[location.prop] = [];\n    }\n\n    var array = location.element[location.prop];\n\n    var index = 0;\n    if (patch.index){\n        index = parseInt(patch.index);\n    }\n\n    array.splice(index, 0, patch.value);\n\n    return doc;\n}\n\nfunction insertElementIfNotExists(doc, patch, location){\n    if (!location.element[location.prop]){\n        location.element[location.prop] = [];\n    }\n\n    var array = location.element[location.prop];\n\n    var index = 0;\n    if (patch.index){\n        index = parseInt(patch.index);\n    }\n\n    var patchValueAsJSONString = JSON.stringify(patch.value);\n    var elementAsJSONString = JSON.stringify(array[index]);\n    if (elementAsJSONString !== patchValueAsJSONString){\n        array.splice(index, 0, patch.value);\n    }\n\n    return doc;\n}\n\nfunction rename(doc, patch, location){\n    var actual = location.element[location.prop];\n    delete location.element[location.prop];\n\n    location.element[patch.to] = actual;\n\n    return doc;\n}\n\nfunction removeElement(doc, patch, location){\n    var array = location.element[location.prop];\n    if (!array) return doc;\n\n    var indices = [];\n    array.every(function(element, index, _array) {\n      if (!deepEquals(patch.value, element)) return true;\n      indices.push(index);\n      return patch.action === 1;\n    });\n\n    for (var i = indices.length - 1; i > -1; i--) {\n      array.splice(indices[i], 1);\n    }\n\n    return doc;\n}\n\nfunction deepEquals(x, y) {\n    if (x === null || x === undefined || y === null || y === undefined) { return x === y; }\n    if (x === y || x.valueOf() === y.valueOf()) { return true; }\n    if (Array.isArray(x) && x.length !== y.length) { return false; }\n\n    if (!(x instanceof Object)) { return false; }\n    if (!(y instanceof Object)) { return false; }\n\n    var p = Object.keys(x);\n    return Object.keys(y).every(function (i) { return p.indexOf(i) !== -1; }) &&\n        p.every(function (i) { return deepEquals(x[i], y[i]); });\n}\n\nvar ops = {\n    'set': setValue,\n    'delete': deleteValue,\n    'duplicate': duplicateValue,\n    'increment': incrementValue,\n    'increment_float': incrementFloat,\n    'append': appendElement,\n    'append_if_not_exists': appendElementIfNotExists,\n    'rename': rename,\n    'insert': insertElement,\n    'insert_if_not_exists' : insertElementIfNotExists,\n    'remove': removeElement\n}\n\nmodule.exports = function(doc, patch){\n    // TODO -- throw if not a handler\n    var handler = ops[patch.type];\n\n    var location = locate(doc, patch.path);\n\n    return handler(doc, patch, location);\n}\n\n\n  var func = module.exports;\n\n  return func(doc, patch);\n\n$$ LANGUAGE plv8 IMMUTABLE STRICT;"

**Comment by dapalmi** [comment]
I missed the Exception at the end:

`LANGUAGE plv8 IMMUTABLE STRICT; ---> Npgsql.PostgresException: 42704: language "plv8" does not exist`

Why is the PLV8 extension required when executing `ApplyAllConfiguredChangesToDatabase`?
Or do I misunderstand the usage of this option?
I thought this function can be called when it is required to create the database tables, indexes, etc. on startup of the application.

**Comment by oskardudycz** [comment]
As it's stated in [README file](https://github.com/JasperFx/marten/blob/master/README.md) 
```
You need to enable the PLV8 extension inside of PostgreSQL for running JavaScript stored procedures for the nascent projection support.
```
When you're running `ApplyAllConfiguredChangesToDatabase` then it applies **All** changes, so also all of stored procedures, from which some require `PLV8` being enabled.

**Comment by dapalmi** [comment]
Ok. Thank you.
Just to make sure I understand it right:
When I execute
```
using (var session = store.QuerySession())
            {
                var test = session.Query<Structure>().ToList();
            }
```
it creates the corresponding tables, indexes, etc. without any error, even when PLV8 is not installed, if no stored procedures have to be created which would need PLV8.
But as soon as I execute `ApplyAllConfiguredChangesToDatabase` it always throws an exception if PLV8 is not installed even when no stored procedures have to be created which would need PLV8.
Is that correct?

**Comment by oskardudycz** [comment]
@dapalmi yes, that's correct. PLV8 is used mostly for javascript functions, transformations etc.

In general - it's high recommendation to have PLV8 installed when using Marten - without that - some feaures might just not work.
