### ISSUE TITLE
System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by dapalmi** [JasperFx/marten#1189]
I have following LINQ query:
```
session.Query<Search>().Select(s => new TextSearchViewModel(s.ItemNumber, null, "Item Number"))
                    .Concat(session.Query<Search>().Select(s => new TextSearchViewModel(s.ProductName, null, "Product Name")));
```
Which throws following exception:

> System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
>    at Marten.Schema.Field..ctor(EnumStorage enumStorage, MemberInfo[] members)
>    at Marten.Schema.JsonLocatorField..ctor(String dataLocator, EnumStorage enumStyle, Casing casing, MemberInfo[] members)
>    at Marten.Schema.FieldCollection.<>c__DisplayClass8_0.<FieldFor>b__1(String _)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Marten.Linq.TargetObject.SetterBinding.ToJsonBuildObjectPair(IQueryableDocument mapping)
>    at System.Linq.Enumerable.SelectListIterator`2.ToArray()
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at Marten.Linq.TargetObject.ToSelectField(IQueryableDocument mapping)
>    at Marten.Linq.TargetObject.ToSelector[T](IQueryableDocument mapping, Boolean distinct)
>    at Marten.Linq.SelectorParser.ChooseSelector[T](String dataLocator, ITenant tenant, IQueryableDocument mapping, QueryModel query, SelectManyQuery subQuery, ISerializer serializer, IIncludeJoin[] joins)
>    at Marten.Linq.Model.LinqQuery`1.BuildSelector(IIncludeJoin[] joins, QueryStatistics stats, SelectManyQuery subQuery, IIncludeJoin[] includeJoins)
>    at Marten.Linq.Model.LinqQuery`1..ctor(DocumentStore store, QueryModel model, IIncludeJoin[] joins, QueryStatistics stats)
>    at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
>    at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
>    at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
>    at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
>    at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
>    at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
>    at Remotion.Linq.QueryableBase`1.GetEnumerator()
>    at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by oskardudycz** [comment]
@dapalmi currently Marten doesn't support Select with non-default constructor. Could you try to use in your mapping default constructor with something like:

```
new TextSearchViewModel
{
    ItemNumber = s.ItemNumber, 
    Title = null, 
    Description = "Item Number"
}
```

**Comment by dapalmi** [comment]
@oskardudycz Thanks for your quick response:
I tried it according to your suggestion but got following Exception:

> Marten.Schema.InvalidDocumentException: Could not determine an 'id/Id' field or property for requested document type SearchService.API.ViewModels.TextSearchViewModel
>    at Marten.Schema.DocumentMapping.Validate()
>    at Marten.Storage.DocumentTable..ctor(DocumentMapping mapping)
>    at Marten.Schema.DocumentMapping.toSchemaObjects()+MoveNext()
>    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
>    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at Marten.Storage.FeatureSchemaExtensions.AssertValidNames(IFeatureSchema schema, StoreOptions options)
>    at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType)
>    at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
>    at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
>    at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
>    at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
>    at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
>    at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
>    at Remotion.Linq.QueryableBase`1.GetEnumerator()

So I added an Id field to my ViewModel like this:

```
    public class TextSearchViewModel
    {
        public Guid Id { get; set; }
        public string Value { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
```

But when I executed it like this:

```
                var query = session.Query<Search>().Select(s => new TextSearchViewModel
                {
                    Value = s.ItemNumber,
                    Title = null,
                    Description = "Item Number"
                })
                .Concat(session.Query<Search>().Select(s => new TextSearchViewModel
                {
                    Value = s.ProductName,
                    Title = null,
                    Description = "Product Name"
                }));
                var result = test.ToList();
```

I got following Exception:

> System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
>    at Marten.Schema.Field..ctor(EnumStorage enumStorage, MemberInfo[] members)
>    at Marten.Schema.JsonLocatorField..ctor(String dataLocator, EnumStorage enumStyle, Casing casing, MemberInfo[] members)
>    at Marten.Schema.FieldCollection.<>c__DisplayClass8_0.<FieldFor>b__1(String _)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Marten.Linq.TargetObject.SetterBinding.ToJsonBuildObjectPair(IQueryableDocument mapping)
>    at System.Linq.Enumerable.SelectListIterator`2.ToArray()
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at Marten.Linq.TargetObject.ToSelectField(IQueryableDocument mapping)
>    at Marten.Linq.TargetObject.ToSelector[T](IQueryableDocument mapping, Boolean distinct)
>    at Marten.Linq.SelectorParser.ChooseSelector[T](String dataLocator, ITenant tenant, IQueryableDocument mapping, QueryModel query, SelectManyQuery subQuery, ISerializer serializer, IIncludeJoin[] joins)
>    at Marten.Linq.Model.LinqQuery`1.BuildSelector(IIncludeJoin[] joins, QueryStatistics stats, SelectManyQuery subQuery, IIncludeJoin[] includeJoins)
>    at Marten.Linq.Model.LinqQuery`1..ctor(DocumentStore store, QueryModel model, IIncludeJoin[] joins, QueryStatistics stats)
>    at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
>    at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
>    at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
>    at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
>    at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
>    at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
>    at Remotion.Linq.QueryableBase`1.GetEnumerator()
>    at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by dapalmi** [comment]
I just saw that the LINQ Query creates an empty mt_doc_textsearchviewmodel table in the database. Why does it do that?

**Comment by jeremydmiller** [comment]
@dapalmi Sorry for the extremely long delay, but we're deep into the V4.0 Linq overhaul and I think the naive mechanics that led to your last error have been addressed. I'm going to try to prove that out in a UT right now.
