### ISSUE TITLE
 is possible to be use DateTime.Date in Linq queries?

### ISSUE THREAD

**Issue by quicoli** [JasperFx/marten#1196]
Hi, 

I have the following query:

```
           using (var session = documentStore.LightweightSession())
            {
                list = session.Query<Sample>().Where(x => x.CompleteDate >= date).ToList();
                return list;
            }
```
This works perfectly returning my data from database and is translated to the following SQL:

`select d.data, d.id, d.mt_version from public.mt_doc_sample as d where (d.mt_deleted = False and d.complete_date >= :arg0)
`
Now if change my query to this:

```
           using (var session = documentStore.LightweightSession())
            {
                list = session.Query<Sample>().Where(x => x.CompleteDate.Date >= date).ToList();
                return list;
            }
```

It doesn't return any value and is translated to the following SQL

`select d.data, d.id, d.mt_version from public.mt_doc_sample as d where (d.mt_deleted = False and CAST(d.data -> 'CompleteDate' ->> 'Date' as timestamp without time zone) >= :arg0)`

Is this suppose to happen?

**Comment by oskardudycz** [comment]
@quicoli yes, it lies in the JSON storage nature. Normally dates are stored as strings. If you're doing `.Date` then query parser assumes that your type is object. So it generates such query with json selector - so `d.data -> 'CompleteDate' ->> 'Date'`. 
As there is no data like that as `CompletedDate` is something like `2019-02-21 18:50:11` and not
```
{
    Date: '2018-02-21'
}
```
Then it's just not able to find matching record.

Unfortunately our query parser is not smart enough for that case. We might concider at some point of supporting that, but it won't happen soon, as we have limited capacity...

For this time being I'd suggest you to add getter:

```
DateTime CompletedDateDay =>CompleteDate.Date
```
then you can query by this date.

It's not ideal, as it will make the data redundancy, but it will work.
```

**Comment by oskardudycz** [comment]
@quicoli I'm closing this issue for now. If you feel that suggested workaround is not enough. Please sennd comment and I'll reopen it.
