### ISSUE TITLE
Precise decimal values are not stored as-is

### ISSUE THREAD

**Issue by leypascua** [JasperFx/marten#1197]
We're saving very precise decimal values. Looks like decimal values are rounded up/down or truncated. 
```
{   
    "Precision": {        
        "Value": 0.8825346394845998,        
        "ValueString": "0.8825346394845997705409937",        
    }
}
```

Here's the class for the 'Precision' property of the sample document:
```
public class SomeData
{
     public decimal Value { get; set; }
     public string ValueString { get; set; }
}

```
How do you suggest to store decimal values in its entirety?

**Comment by jeremydmiller** [comment]
@leypascua That's going to be in Newtonsoft.Json, not Marten itself. See this topic for ways to customize the Json serialization: http://jasperfx.github.io/marten/documentation/documents/json/newtonsoft/.

**Comment by mysticmind** [comment]
@leypascua  You could possibly use the solution from [SO post](https://stackoverflow.com/questions/24051206/handling-decimal-values-in-newtonsoft-json) to create a `DecimalConverter` which you can plugin into Newtonsoft.Json serializer.
