### ISSUE TITLE
Allow specifying index order for Duplicated fields

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#1199]
Marten allows duplicating fields from JSON as relational fields, and creating an index for them.

I have a case where I want to duplicate a `timestamptz` field, and have it sorted in descending order, which Marten doesn't yet support (confirmed in gitter).

This issue is to track adding support for specifying the index order for Duplicated fields

I'll have a stab at this one when I get time, along with the similar #1198

**Comment by barryhagan** [comment]
It will be nice to have a declarative way to set this, but you can alter the index expression right now:

`For<T>().Duplicate(a => a.Timestamp, configure: idx => { idx.Expression = "? DESC"; });`

**Comment by cocowalla** [comment]
Created PR #1213
