### ISSUE TITLE
Error on store - some kind of assembly scanning / reflection issue

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#120]
Wrote a very small console app which connects to RavenDb, queries a collection and stores the same document into Marten.

However when doing martenSession.Store(doc); it throws a bunch of errors into my console window (attached).

![store_error](https://cloud.githubusercontent.com/assets/365283/12718994/426d8f12-c8ea-11e5-80ae-4686307111d1.png)

My code:

`var docStoreConfig = new Raven.Client.Document.DocumentStore
            {
                ConnectionStringName = "RavenDB"
            };
            docStoreConfig.Initialize();`

            using (var store = docStoreConfig.Initialize())
            {
                store.Conventions.IdentityPartsSeparator = "-";

                using (var mStore = DocumentStore.For("host=localhost;database=myravendb;password=mypassword;username=xxx"))
                {
                    using (var rSession = store.OpenSession())
                    {
                        using (var mSession = mStore.LightweightSession())
                        {
                            var enumerator = rSession.Advanced.Stream<Account>(Etag.Empty, 0, Int32.MaxValue);
                            int i = 0;
                            while (enumerator.MoveNext())
                            {
                                var account = enumerator.Current.Document;
                                mSession.Store(account); // fails here
                                if (i % 100 == 0) mSession.SaveChanges();
                                i++;
                                Console.WriteLine("{0} - {1} - {2}", i.ToString(), account.Id, account.ArtistName);
                            }
                            mSession.SaveChanges();
                        }
                    }
                }
            }`

**Comment by jeremydmiller** [comment]
@phinett What version of Marten do you have? This one was already reported and theoretically fixed in https://github.com/JasperFx/marten/commit/27cb3967fcddd2db0eef17dd7f7d04952e65460f. Can you bump up to the latest?

**Comment by jeremydmiller** [comment]
Oh, just read things. I'm keeping the Console junk for now just to get an indication of what's happening inside. So far we haven't seen any harm in swallowing the bad Sparrow reference

**Comment by phinett** [comment]
Ok that's fine with me.
