### ISSUE TITLE
Cannot have a ForeignKey use same member as Identity

### ISSUE THREAD

**Issue by barclayadam** [JasperFx/marten#1226]
It is not possible to have an entity that has a member that is used for both its Id and as a foreign key to another entity. For example:

````c#
For<FooExtra>()
    .IdStrategy(new NoOpIdGeneration())
    .Identity(x => x.FooId)
    .ForeignKey<Foo>(x => x.FoodId)
    .MultiTenanted();
````

The intention is to have a one-to-one relationship between parent `Foo` and it's child `FooExtra`.

This fails on the schema generation as no additional column is created for this foreign key.

Should this be supported, or should this throw earlier to identify this as being unsupported?

**Comment by jeremydmiller** [comment]
@barclayadam  Before I put much into fixing this, is this really necessary? If it's really one to one in the document, why not just have one single document type?

**Comment by barclayadam** [comment]
@jeremydmiller Good question. Strictly speaking, I'd say no, it's possible to work around it. Our use case for this is two-folder:

 1. We are migrating legacy code from Azure Table store and keeping them separate simplifies that path

 2. The entities change on a completely separate change axis, the parent is often only ever created and then not changed, the child is changed often. We have things that respond to changes in entities, so it is useful to keep the changes separate. We also have this the other way around, with supplementary data being updated often but we do not want that being "part of" the parent entity.

If this does not go through as an enhancement, could it be changed to throw an exception? Tracking down the root cause with only a SQL error is tricky. I cannot remember the exact message but it was non-obvious why it was failing

**Comment by mysticmind** [comment]
This issue looks to be fixed and working fine, will add a unit test for this.

**Comment by mysticmind** [comment]
Unit test passed, closing this.
