### ISSUE TITLE
Importing events causes incorrect seq_id entries

### ISSUE THREAD

**Issue by Crown0815** [JasperFx/marten#1228]
We recently encountered an event in our event store that was faulty (it should never have been created in the first place.) After **deleting the event manually** (PgAdmin) everything **worked fine** for a while.
After another issue with an event, we decided to clone the mt_events table using the **export and import** functionality provided by PgAdmin to allow debugging of the events on another database instance.

However **after import** of the table to the debugging database it was **impossible to write new events** to the clone. The `seq_id` was always lower than it was required to be by the unique constraint which (of course) through an exception.

I looked myself through the code but could not really find the place of determination for the `seq_id`. 

My questions are: 
* How is the `seq_id` generated? 
* Why is the automatic incrementation of PostgreSQL not used?

**Comment by Crown0815** [comment]
I found the answer! 
The sequence id is actually created and maintained by the database itself. It can be found as shown below

![image](https://user-images.githubusercontent.com/36126706/54982065-28db3500-4faa-11e9-9831-31e846d9bc41.png)

**Comment by oskardudycz** [comment]
@Crown0815 thank you for self service :D and sorry for lack of the answer for you -_-
