### ISSUE TITLE
Delete ordering issue

### ISSUE THREAD

**Issue by barclayadam** [JasperFx/marten#1229]
When trying to delete multiple different types of documents that have a FK relationship the deletes are ordered incorrectly.

I've not fully tracked down but believe it's because the operations are sorted topologically but for deletes that is the incorrect order. For now I've just got a failing test to check if my assumptions about it working are incorrect:

````c#
public class Bug_1229_delete_ordering: IntegratedFixture
{
    [Fact]
    public void delete_ordering_with_fk_relationships()
    {
        StoreOptions(_ =>
        {
            _.Schema.For<User>()
                .IdStrategy(new NoOpIdGeneration());

            _.Schema.For<Issue>()
                .IdStrategy(new NoOpIdGeneration())
                .ForeignKey<User>(u => u.AssigneeId);
        });

        var user = new User();
        var issue = new Issue { AssigneeId = user.Id };

        using (var query = theStore.OpenSession("Bug_1229"))
        {
            query.Store(user);
            query.Store(issue);

            query.SaveChanges();
        }

        using (var query = theStore.OpenSession("Bug_1229"))
        {
            query.Delete(issue);
            query.Delete(user);

            query.SaveChanges();
        }
    }
}
````

**Comment by baronfel** [comment]
Ran into this today as well.

for a group of entities A, B, C, where B is a join table between A and C, delete code that looks like:
```csharp
session.DeleteWhere<B>(b => b.Id = someId)
session.Delete<C>(b_entity)
session.Delete<A>(a_entity)
```

get sequenced like:
```
A-delete-clause
C-delete-clause
B-delete-clause
```

instead of the required
```
B-delete-clause
(A or B)-delete-clauses in either order
```

**Comment by baronfel** [comment]
I'd love to work on a fix for the ordering, if there are pointed to where some of that happens.

**Comment by baronfel** [comment]
Ordering code in question is [here](https://github.com/JasperFx/marten/blob/master/src/Marten/Services/UnitOfWork.cs#L208-L247).

Current algorithm seems to be:

```
typeOrdering = 
 for docType in operationsByDocType
   for dependentType in docType.dependents
    yield dependentType
   yield docType

for type in typeOrdering
  for operation in type.operations
   yield operation
```
The only ordering constraint here being 'for each document type, the operations to perform for that document type are ordered', and we should respect that order.

It's almost like the overall list of operations themselves should also/instead be tracked, and processing the operations should happen more like
```
for operation in operations
  for dependentOperation in getDependentOperations operation (would include checking the dependent types and generating the ordering of 'derived deletes/inserts for FKs here)
   yield dependentOperation
  yield operation
```

and then the various operations could be taught how to create derived inserts/upserts/deletes.

**Comment by barclayadam** [comment]
@baronfel have you made any progress on this? I'm shortly circling back around to this and will need to look at getting this fixed

**Comment by baronfel** [comment]
No, I haven't gotten to spend much more time on this either :-/

**Comment by barclayadam** [comment]
@baronfel I have a branch you could check out if you need a fix. PR #1238 opened
