### ISSUE TITLE
Add Options property to IDocumentStore interface

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#1230]
Options is a required part of the DocumentStore, so i think we should add this to the IDocumentStore interface (in the next major version of course)

`StoreOptions Options { get; }`

**Comment by jeremydmiller** [comment]
My vote is "no". If you dig back long enough there's an issue about only exposing a read only interface of StoreOptions, because users can actually modify the StoreOptions object after the DocumentStore is initialized, but most of that wouldn't actually take effect. I think this is just opening up users for confusion.

**Comment by mdissel** [comment]
Ok, the reason for my question is that inside a sessionlistener I have this code:

`if ((session.DocumentStore as Marten.DocumentStore)?.Options.Storage.MappingFor(entity.GetType()).DeleteStyle == m.Schema.DeleteStyle.SoftDelete) {
		// skip auditing
		return;
}
`

I need the storage definition via the IDocumentStore. Any alternative?

**Comment by oskardudycz** [comment]
@jeremydmiller maybe we could just add it as readonly? In thery we could only return some limited interface with only readonly members?

**Comment by mysticmind** [comment]
Check #745 which was closed with a code comment to expose `StoreOptions` as readonly

**Comment by jeremydmiller** [comment]
Still saying to only do this if we pull out a readonly interface. Not sure how much value it adds or what you'd use it for. Most of it shouldn't be altered at runtime. You can get at the connections & serializer in other ways. 

What @mdissel asked for would require a new read only interface for `IDocumentMapping`. And what he's after could technically be done differently if we'd just add something to `IDeletion` to let you know if it's a hard or soft delete.

**Comment by oskardudycz** [comment]
I think that it's worth adding a read-only interface.
