### ISSUE TITLE
Revamp IField model within the Linq provider and make it pluggable

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1243]
Part of #1201. The goal here is to:

* Reduce some code duplication within the Linq parsing
* Clean up some of the Linq code
* Make the Linq provider a little more pluggable for how it creates OrderBy or Where clauses against different member types, properties, fields, and even indexers 

For the `IField` interface, today it's 

```
    public interface IField
    {
        MemberInfo[] Members { get; }
        string MemberName { get; }

        string SqlLocator { get; }

        string SelectionLocator { get; }

        string ColumnName { get; }

        void WritePatch(DocumentMapping mapping, SchemaPatch patch);
        object GetValue(Expression valueExpression);

        Type MemberType { get; }
        bool ShouldUseContainmentOperator();
        string LocatorFor(string rootTableAlias);
    }
```

Recommendations so far:

- [x] `SqlLocator` renamed to `TypedLocator` as this means that it is CAST to the proper Postgresql type
- [x] `SelectionLocator` renamed to `RawLocator` that gives you the value in the JSON as is when that's appropriate
- [x] `WritePatch` doesn't appear to be used anymore
- [x] `GetValue` renames to `GetValueForCompiledQueryParameter` to make it clear what it does
- [x] `MemberType` renames to `FieldType` because it's no longer really bound to fields or properties
- [x] `ShouldUseContainmentOperator()` needs to die
- [x] Introduce a new `ToWhereFragment(BinaryExpression) : IWhereFragment` that encapsulates all the differences necessary for writing equality or other operator comparisons within the `IField` rather than doing a lot of if/then logic within the Linq code

At the same time, I want to introduce a little bit of a Field type hierarchy in addition to what we have now:

- [x] `MemberField` -- base class
- [x] `StringField`
- [x] `CastField` -- any other type besides string that serializes to a single attribute and just needs to be cast or parsed to a single value
- [x] `NodeField` -- a parent Field when you get into deep searches
- [x] `DateTimeField` -- weird rules here
- [x] `DateTimeOffsetField` -- weird rules here
- [x] `IntEnumField` -- even weirder
- [x] `StringEnumField` -- differently weird

and eventually some kind of field for dictionary indexers, `TimeSpan` child properties, extra DateTime properties maybe

The next thing is to overhaul how we discover `IField` objects for a given Expression. Today it's all done by an array of `MemberInfo`, and the Linq code duplicates the logic for finding `MemberInfo`s in an `Expression` assuming that's all there is. We need some new way that can instead find `IField` objects directly from an `Expression`.

**Comment by jeremydmiller** [comment]
I'm going to declare success on this one today, but there's probably going to be other changes to the model as we work through more Linq issues

**Comment by jeremydmiller** [comment]
Done in the Linq branch.

**Comment by mysticmind** [comment]
@jeremydmiller I am back in the station after long summer vacation, catching up and starting to learn more on the linq changes you have been working on. Please let me know if I can work on a small targeted task to start with to get my hands dirty :-)

**Comment by jeremydmiller** [comment]
*I* just got a chance to start working on this again yesterday and today, so I'm coming up to speed too. @oskardudycz is wanting all of us to finally do a google hangout or something to talk this all over. He's got some ideas. I *think* after a bad month or so at work I'm coming up on a spell where I could tackle bigger things.

I think I wanna see us start w/ an effort to parallelize the tests by using many, many more different schemas so we can get the tests running a lot faster.

**Comment by mysticmind** [comment]
Few things on top of my mind:
- We wanted to add the matrix tests we discussed before which will involve running unit tests targetting different Postgres versions. Let me take a crack at it.
- Overhaul our documentation site a bit on the structure/layout to include search via Algolia and all TOC/topic on the left like https://vuejs.org/v2/guide/.

**Comment by jeremydmiller** [comment]
A better website sounds great to me. The guy who laid out the doc website originally is horrible at web design;-). The matrix tests sound like a good idea. Definitely makes me want the tests running faster when we do that though.
