### ISSUE TITLE
Incorrect SQL generated while using Joins with FullTextIndex 

### ISSUE THREAD

**Issue by nmt1994** [JasperFx/marten#1245]
Hello Marten team,

I encountered a problem where querying with Marten Text Search function will result error with joins( Include ) . The same error happened for .PlainTextSearch/Search/PhraseSearch

`
PostgresException: 42702: column reference "data" is ambiguous
`

This is the generated query from Marten
`
select d.data, d.id, d.mt_version, user_id.data, user_id.id, user_id.mt_version from public.mt_doc_email as d INNER JOIN public.mt_doc_user as user_id ON CAST(d.data ->> 'UserId' as uuid) = user_id.id where to_tsvector('english', ((data ->> 'Content'))) @@ plainto_tsquery('english', 'content')
`

Expected 
`
where to_tsvector('english', ((data ->> 'Content')))
`
to be 
`
where to_tsvector('english', ((d.data ->> 'Content')))
`

The repro project is here: https://github.com/nmt1994/MartenTextSearchJoinBug

**Comment by jeremydmiller** [comment]
@nmt1994 I'm looking at this today
