### ISSUE TITLE
NpgsqlOperationInProgressException during Rebuild when running async query in a ViewProjection

### ISSUE THREAD

**Issue by tetious** [JasperFx/marten#1249]
If you are using ViewProjection, with a binding like this: 
```csharp
this.ProjectEvent<ProjectionEvent<UserNew>>(async (s, v, e) => await this.Apply(v, e, s));
```

and a projection method similar to this:
```csharp
private async Task Apply(User v, ProjectionEvent<UserNew> e, IQuerySession s)
{
    var account = await s.LoadAsync<Account>(e.Data.AccountId);
    v.DatabaseName = account.DatabaseName;
}
```

When you run a Rebuild using this projection, the LoadAsync line throws a ```NpgsqlOperationInProgressException```. 

If you use Load instead (non-async) everything is fine.

Hopefully there is enough information here to track this bug(?) down, or to help me understand what I'm doing wrong. :)

**Comment by tetious** [comment]
I figured this out while trying to write a repro test. It's fairly obvious now. Not sure why it wasn't yesterday! :)

The correct binding/setup for async Applys is, of course, ProjectEventAsync.
```
this.ProjectEventAsync<ProjectionEvent<UserNew>>((s, v, e) => this.Apply(v, e, s));
```

**Comment by oskardudycz** [comment]
Yeah, sorry for lack of response. Yes, that's suggested way.
I'll reopen the issue as we lack documentation around that http://jasperfx.github.io/marten/documentation/events/projections/custom/ .
As I'm author of `ProjectEventAsync` I need to be responsible and update that ;)
