### ISSUE TITLE
improved naming conventions for nested classes

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/marten#125]
Ability to override table names or specify conventions for naming. For a scenario like the code below, there are name collision issues.

```
public class Foo
{
    public class Aggregate {}
    public class State {}
}

public class Bar
{
    public class Aggregate {}
    public class State {}
}
```

**Comment by jeremydmiller** [comment]
@jeffdoolittle What's your preference here? I do vote for an attribute for the table name (might already exist, I've slept since then.) For nested types, what if the example above were to be `mt_doc_foo_aggregate` and `mt_doc_bar_aggregate`?

**Comment by jeffdoolittle** [comment]
I think that's the sensible default.

**Comment by jeffdoolittle** [comment]
@jeremydmiller I can work on this if you want to assign me the issue

**Comment by jeremydmiller** [comment]
@jeffdoolittle I'm taking you up on that;)

**Comment by jeremydmiller** [comment]
You might need to assign yourself, or I can add you to the GH team
