### ISSUE TITLE
Use unique index inference for upsert constraint

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#1262]
In Marten's upsert functions, it checks for an existing row using Postgres' `ON CONFLICT` feature, using a named constraint:

`ON CONFLICT ON CONSTRAINT mt_doc_mytable_pkey`

According to the [Postgres docs](
https://www.postgresql.org/docs/11/sql-insert.html#SQL-ON-CONFLICT):

> _It is often preferable to use unique index inference rather than naming a constraint directly using ON CONFLICT ON CONSTRAINT constraint_name._

Aside from the docs though, the reason I am bringing this up is that TimescaleDB hypertables [do not support](https://github.com/timescale/timescaledb/issues/1094) `ON CONFLICT` statements that reference constraints.

I'm using TimescaleDB with Marten, and get around this by post-processing the DDL that Marten generates to replace something like this:

`ON CONFLICT ON CONSTRAINT mt_doc_mytable_pkey`

with something like this:

`ON CONFLICT (my_timestamp, id, tenant_id)`

This works well enough for me, but if TimescaleDB support is desirable for others (I know @oskardudycz showed some interest in it), and the Postgres docs recommend it anyway, perhaps this is worth changing?

**Comment by jeremydmiller** [comment]
I'm going to unilaterally say this is a breaking change because of the function change, and kick it to v4. The good news though is the sooner we clear 3.12, the sooner we start on v4.

**Comment by jeremydmiller** [comment]
And this would require V6 now.
