### ISSUE TITLE
Table gets re-created every time i run my app

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#127]
Not sure if this is a user error or bug, but i am trying to write a console app to migrate data from RavenDB to Marten, however if i run the app and it migrates X amount of documents, i then restart the app and try to continue from the last document it migrated but Maten just wipes the table and re-creates a new one.

I have tried disabling the 'AutoCreateSchemaObjects' since the table already exists, but i then get this error:

Additional information: No document storage exists for type HM.Core.Documents.Advert and cannot be created dynamically unless the StoreOptions.AutoCreateSchemaObjects = true. See http://jasperfx.github.io/marten/documentation/documents/ for more information

**Comment by phinett** [comment]
I can see why...the id field type on the database is 'character varying', but the one it is comparing to is varchar.

Just trying to work out how to correct this...what would be the correct type to use?

**Comment by jeremydmiller** [comment]
So the postgresql table is one thing, even though we create it with another? The `TableColumn` class would need to have some kind of way to evaluate synonyms/type aliases so that its doing it's equality check correctly. Marten *thinks* the table is different and wants to re-generate.

**Comment by phinett** [comment]
I can see the script executed to create the table in postgresql is set to varchar for the Id field, but looking at the table with pgAdmin it's data type is set to character varying, why is it changing it from varchar?

I think if the postgresql respects that it should be varchar then the issue will go away, not sure if this is a sparten issue or postgresql?

**Comment by jeremydmiller** [comment]
The postgresql docs say that they're synonyms. I'll be starting on more Marten work this morning anyway, I can get to this one quickly.

**Comment by phinett** [comment]
Attempted my own quick fix, would be interested in your version of the solution though to see if i was on the same kind of track...not sure how flexible this will be for other types but works for this simple case.

TableColumn.cs:

` protected bool Equals(TableColumn other)
        {
            return string.Equals(Name, other.Name) && string.Equals(TypeMappings.ConvertSynomyns(Type), TypeMappings.ConvertSynomyns(other.Type));
        }`

TypeMappings.cs:

`public static string ConvertSynomyns(string type)
        {
            switch (type.ToLower())
            {
                case "character varying":
                case "varchar":
                    return "varchar";
            }
            return type;
        }`

**Comment by jeremydmiller** [comment]
that was basically where I was heading. Can I just take yours then?

**Comment by phinett** [comment]
Yes sure.

**Comment by phinett** [comment]
Correct the synonyms spelling mistake first though :-)

**Comment by jeremydmiller** [comment]
@phinett Hey, just to make sure, are you doing a PR for this, or should I just grab the code here and go?

**Comment by phinett** [comment]
Hi, I just grab the code this time round it's only minimal. 
Thank you
On 3 Feb 2016 19:39, "Jeremy D. Miller" <notifications@github.com> wrote:@phinett Hey, just to make sure, are you doing a PR for this, or should I just grab the code here and go?
