### ISSUE TITLE
Feature Request: Configure Table Aliases for generic tables all at once

### ISSUE THREAD

**Issue by baronfel** [JasperFx/marten#1271]
I've got a structure like

```fsharp
type PersistedState<'T> = 
  { Id: Guid
    State: 'T }
```

that I'm persisting to marten to represent some temporal state for a variety of folds over different types of incoming events, but I'd like all of the states to be persisted to the same underlying table. Marten specializes each usage of the generic type to generate the tablename, but I'd like to be able to say something like `_.Schema.For<PersistedState<'t>>().DocumentAlias("some_stable_name")` so that all versions of the table (unless manually overridden) would use the same set of storage configuration.  Right now I have a helper method to specialize the type and generate the alias, but I have to remember to do that for each new kind of state I introduce into my application, which can be error-prone.

**Comment by baronfel** [comment]
which, now that I'm actually running my code, doesn't work at all because Marten expects uniqueness across all document aliases :(

**Comment by jeremydmiller** [comment]
No, just no:)
