### ISSUE TITLE
Customized serializer causes Postgres queries to not match

### ISSUE THREAD

**Issue by uglybugger** [JasperFx/marten#1273]
I'm currently working on an app which serializes complex types, types with parent/child relationships and polymorphic child types. To do that, we use JSON.NET's serialization annotations to include type and reference metadata. That gives us JSON objects containing `$id` and `$ref` fields.

If we use the same serializer for that as our document serialization then when it creates its own query parameter class for the WHERE clause the same `$id` and `$ref` fields get included in the serialized output. Postgres doesn't fail (it's a valid JSON query parameter) but it also won't match documents without matching values in those fields - which means it won't match anything - and so our LINQ queries come back empty.

**I think this would be easily solved by allowing for a different serializer to be passed for document serialization versus query where clause serialization.**

Apologies - I just don't have time to send a pull request at the moment. Here's a quick snippet to illustrate the problem and my hacky work-around:

    var documentSerializer = new JsonNetSerializer();
    documentSerializer.Customize(jsonSerializer =>
    {
        // ...
        jsonSerializer.ReferenceLoopHandling = ReferenceLoopHandling.Serialize;
        jsonSerializer.PreserveReferencesHandling = PreserveReferencesHandling.Objects;
        jsonSerializer.ReferenceResolver = new ReferenceResolverThreadSafeDecorator(jsonSerializer.ReferenceResolver);
    });

    var documentStore = DocumentStore.For(storeOptions =>
    {
        // ...
        storeOptions.Serializer(documentSerializer);
    });

    var querySerializer = new JsonNetSerializer();
    var parser = new MartenExpressionParser(querySerializer, documentStore.Options);
    documentStore.SetReadOnlyProperty("Parser", parser);

**Comment by tonykaralis** [comment]
@uglybugger I am currently using NewtonSoft to do the serialisation and also working with lots of interfaces children etc. Here is my serializer that works nicely, have not had any issues with no results due to the id field existing in the data.

**Custom serialization**
```
private Marten.Services.JsonNetSerializer SetupCustomSerializer(ISerializationBinder customBinder = null)
        {
            var customJson = new Marten.Services.JsonNetSerializer();
            customJson.Customize(o =>
            {
                if (customBinder != null)
                {
                    o.SerializationBinder = customBinder;
                }

                o.Formatting = Formatting.Indented;
                o.TypeNameHandling = TypeNameHandling.Objects;
                o.PreserveReferencesHandling = PreserveReferencesHandling.Objects;
                o.ObjectCreationHandling = ObjectCreationHandling.Auto;
                o.DateFormatHandling = DateFormatHandling.IsoDateFormat;
            });
            customJson.EnumStorage = EnumStorage.AsString;

            return customJson;
        }
```

**Custom binder** Allows serializing/deserializing interfaces without knwoing the concrete type until runtime. 

```
public class KnownTypesBinder : ISerializationBinder
    {
        /// <summary>
        /// Default constructor
        /// </summary>
        public KnownTypesBinder(Assembly[] selectedAssemblies)
        {
            MapTypes(selectedAssemblies);
        }

        #region Properties
        /// <summary>
        /// List of known types
        /// </summary>
        public List<Type> KnownTypes { get; set; }
        #endregion

        #region Public methods
        /// <summary>
        /// Bind to the type
        /// </summary>
        /// <param name="assemblyName"></param>
        /// <param name="typeName"></param>
        /// <returns></returns>
        public Type BindToType(string assemblyName, string typeName)
        {
            return KnownTypes.SingleOrDefault(t => t.Name == typeName);
        }
        /// <summary>
        /// Binds to the name of the type
        /// </summary>
        /// <param name="serializedType"></param>
        /// <param name="assemblyName"></param>
        /// <param name="typeName"></param>
        public void BindToName(Type serializedType, out string assemblyName, out string typeName)
        {
            assemblyName = null;
            typeName = serializedType.Name;
        }
        #endregion

        #region Private methods
        /// <summary>
        /// Extracts the types contained in that assembly.
        /// </summary>
        /// <param name="selectedAssemblies"></param>
        private void MapTypes(Assembly[] selectedAssemblies)
        {
            if (KnownTypes != null) return;
            KnownTypes = new List<Type>();
            foreach (var assem in selectedAssemblies)
            {
                KnownTypes.AddRange(assem.GetTypes());
            }
            if (KnownTypes.Distinct().Count() != KnownTypes.Count)
            {
                throw new DuplicateItemException("Duplicate types found from multiple assemblies. Potentially added the same assembly twice, which is not allowed.");
            }
        }
        #endregion
    }
```

Dose this help at all?

**Comment by uglybugger** [comment]
Hi @tonykaralis :) . Thanks for the follow-up. I have a working solution (using a separate serializer) and I'm okay with that for now.

I think the broader issue is that at some point there will be a serialization requirement for storage that will be incompatible with serialization for querying, and allowing a different serializer configuration might resolve that issue.

**Comment by mysticmind** [comment]
@uglybugger Please note that while querying, Marten SQL statements use Postgres jsonb operators for querying hence it is imperative to store the serialized JSON without any type and reference meta-data. Also we have to use a single serializer for both storing and querying requirements.

**Comment by uglybugger** [comment]
Hi @mysticmind.. Thanks for your response. I'm aware that Marten uses Postgres' underlying JSON support for querying. That doesn't mean that storing records with type and reference data is impossible - storing polymorphic structures is one of the more attractive elements of a document database.

I'm curious about your statement that we have to use a single serializer for both. Why is that? It's working perfectly well for me to have two different serializers. I can have derived types stored correctly in Postgres using the $type field and query them via a slightly different serializer that doesn't include $type annotations.

$ref fields are a different issue as there's no deterministic way to have reference numbers assigned and the way Marten does change tracking currently precludes using them. That's an issue for another day, though.

**Comment by mysticmind** [comment]
> Also we have to use a single serializer for both storing and querying requirements

@uglybugger I meant to say, with the current Marten implementation and behavior, a single serializer will need to be used (you can only wire one serializer with a document store and we recommend the document store to be a singleton). When you say, you are successfully using 2 different serializers, possibly you might be using 2 different document stores i.e. one for storing and one for querying wired with different serializers.

**Comment by uglybugger** [comment]
Hi @mysticmind.. Thanks again for your response. If you check the code sample above I explained when I raised the issue that I am indeed using two different serialisers with the one document store.

It’s working perfectly happily for me, hence raising the issue with the suggested solution. I realise that if the serialisers’ settings diverge (e.g. casing changes etc.) then queries will erroneously return empty, but that’s currently not an issue.

To be clear: this isn’t a support request :) My solution is working for me; it’s just a bit hacky to use reflection to mess with Marten’s internals in order to fix the serialisation issue and I thought it might be helpful to let people know.

**Comment by mysticmind** [comment]
@uglybugger I do understand your intent to outline the problem and put forth your workaround to help other people who may be facing a similar issue. As maintainers, we never look at issues as a mere support request but genuinely put a lot of labour of love to maintain and resolve issues with Marten. That said, we will look at what best we can do regarding this issue so that you don't need to muck around using reflection. Also, we welcome PRs with open arms :-)

**Comment by mysticmind** [comment]
@jeremydmiller @oskardudycz @jokokko please weigh in with your thoughts around providing the ability to wire different serializers for storage and querying? By default, we could set the same for both but users can change that behavior to use different serializers as they see it fit.

**Comment by jeremydmiller** [comment]
I'm not following @uglybugger 's reasoning here, and I'd want to see a more concrete example of why this is necessary. How does that possibly "solve" anything? The only place where I could see this mattering at all is during LINQ queries that use the containment operator, and in those cases we **do** use a separate JSON.Net serializer internally that's "clean". It could be that the only thing that needs to change here is that the "clean" serializer doesn't get some of the same configuration he used in the original comment (or corrects for some of the settings).

I'd want to hear more about the queries and documents that aren't working.

**Comment by jeremydmiller** [comment]
We've eliminated the usage of the containment operator in almost all cases in the v4 Linq internals, so I don't think this is going to be an issue going forward. And we have been able to prove that the new Linq internals handle Newtonsoft metadata now.
