### ISSUE TITLE
Query("type name from string") rather than Query<T>?

### ISSUE THREAD

**Issue by softwareguy74** [JasperFx/marten#1277]
We have a need to pull records with Query using a type name from a string, such as  `Query("App.Models.User")` rather than passing in the type because we are generating classes at run-time with Roslyn and storing those with Marten.  Going in works because you can simply pass in an instantiated object with `Store()`, but getting back out with Query requires a `<T>,` which we don't have.

Is this a possible feature?

**Comment by jokokko** [comment]
@softwareguy74 possible with reflection at least. Btw. if you don't mind me asking, can you elaborate on the use case?

Not overly elegant, but a quick sample: https://gist.github.com/jokokko/775279e5361f7978aa21b8f096fc9ab8.

**Comment by oskardudycz** [comment]
Imho this can be wrapped with the method in the code using Marten. I don't see high benefit of that, as in Marten we would need to do exactly the same - so use reflection.

**Comment by oskardudycz** [comment]
@softwareguy74 I'm closing it with the above explanation. Feel free to send the feedback if you disagree :)
