### ISSUE TITLE
Delete by query

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#129]
Is it possible to support:

session.Delete<User>().Where(_ => _.Country == "UK");

This would be a replacement for RavenDB's DeleteByIndex in some ways.

**Comment by jeremydmiller** [comment]
I'd vote for `session.Delete<T>(Expression<Func<T, bool>>)`. I don't think it would be that hard, you'd just repurpose the DocumentQuery a bit. Do you wanna take this one? It really wouldn't hurt to have more eyes into that code.

**Comment by phinett** [comment]
I will have a stab at this, new territory but i'll see how i get on.

**Comment by jeremydmiller** [comment]
@phinett Hey, hadn't heard anything in awhile on this, but just to let you know, I'm going to knock this one out this morning to get a little closer to the next release.
