### ISSUE TITLE
 An item with the same key has already been added. Key: patch_doc

### ISSUE THREAD

**Issue by lucax88x** [JasperFx/marten#1306]
Ciao!

So, using Marten 3.3.0, I have this problem that happens pretty rarely, but which softlock my web app and I cannot use it until I restart the cluster.

you can see there:

![image](https://user-images.githubusercontent.com/6294464/60580926-33b21c80-9d86-11e9-8026-84bd04bcff10.png)

I've registered everything as SingleInstance.

I have handlers that are registered InstancePerRequest which are injecting the Repository and calling his methods, each methods of Repository creates a session, use it and dispose it. So it should be fine.

However, when the softlock happens is because Autofac CANNOT create the DocumentStore instance because of the error:

 An item with the same key has already been added. Key: patch_doc

which is happening in the constructor of DocumentStore with StoreOptions as parameter.

My quick thinking: It's possible that the DocumentStore failed for some reason the very first time (maybe DB was still booting up) and then when it tries to recreate the instance it reuses the SAME StoreOptions which already has some shit in memory and it explodes.

What I should do to prevent this?

**Comment by mysticmind** [comment]
@lucax88x Quick question, Is `DocumentStore` a Singleton? Also, it would help if you could provide us a repro use case/code for us to take a look.

**Comment by lucax88x** [comment]
Yes, you can see it in the screenshot it's registered as SingleInstance, which is Singleton.

Even if I was able to make a repro case, I think it's pretty hard to reproduce as it's pretty random.

**Comment by oskardudycz** [comment]
@lucax88x if you're using `IRepository` as singleton that has `IDocumentSession` injected then it won't work, as it's needs to be Scoped (eg. per request lifetime) or Transient (but that might end up with too many connections being open and also random failures).

If the DocumentSession is used as Singleton then it will leave until it gets maximum connection lifetime timeout. So at first it will work for some period of time, but after that it won't. So if you're starting your app each time from VS then you won't notice that isssue, but on test environment, or app kept alive for some time you'll get it.

**Comment by lucax88x** [comment]
@oskardudycz I don't confirm.

What I've registered as Singleton are:

- DocumentStore
- Repository
- SessionFactory

then, every method of the repository, creates a session on the fly, by using the SessionFactory, so the DocumentSessions are scoped for each request, example:

![image](https://user-images.githubusercontent.com/6294464/61391699-8f6bc200-a8bd-11e9-8b43-a34b856768bd.png)

**Comment by lucax88x** [comment]
try to focus on this statement:

"It's possible that the DocumentStore failed for some reason the very first time (maybe DB was still booting up) and then when it tries to recreate the instance it reuses the SAME StoreOptions which already has some shit in memory and it explodes."

better version:
1) Autofac creates StoreOptions as Singleton.
2) Autofac creates DocumentStore as Singleton, it uses StoreOptions as reference to create the connection and inject stuffs (patch stuffs, etc).
For some reasons, che creation of DocumentStore fails (should never happen..but..)
3) Autofac tries to recreates the DocumentStore, it uses the same instance of StoreOptions as before.
As the StoreOptions was used and contains a Dictionary of keys, it's trying to readd the same key, and you get the error of above.

Can't this possibly easily happen?

**Comment by mysticmind** [comment]
@lucax88x I was able to reproduce the issue and fixed the same. Fix will be available in the next release. 

Following is the code to reproduce the issue:
```
var options = new StoreOptions();
options.Connection(ConnectionSource.ConnectionString);

var store1 = new DocumentStore(options);
// pass with the same options and check it throws ArgumentException
// "An item with the same key has already been added. Key: <transform function name/feature schema name>"
var store2 = new DocumentStore(options);
```

**Comment by lucax88x** [comment]
Great! Thanks.
