### ISSUE TITLE
ExternalForeignKeyDefinition returns null for ReferenceDocumentType causing an exception

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/marten#1308]
Since an `ExternalForeignKeyDefinition` returns `null` for the `ReferenceDocumentType` the `DocumentMapping.DependentTypes()` will return a `null` causing an `ArgumentNullException` in `Tenant.ensureStorageExists()`.

**Comment by oskardudycz** [comment]
Fixed by https://github.com/JasperFx/marten/pull/1309
