### ISSUE TITLE
Unable to create a self referencing foreign key

### ISSUE THREAD

**Issue by softwareguy74** [JasperFx/marten#1311]
Doing the following results in a StackOverflowException:

    public class Tenant
    {
        public Guid Id { get; set; }
        [ForeignKey(typeof(Tenant))]
        public Guid? Parent { get; set; }
        public string Name { get; set; }
    }

Why can't we do this?

**Comment by oskardudycz** [comment]
Looks like a bug. I'll try to check that. Could you also provide information about the version of Marten that you're using?

**Comment by softwareguy74** [comment]
Latest version just pulled from nuget.

**Comment by oskardudycz** [comment]
Thank you. I'll try to check that asap.

**Comment by oskardudycz** [comment]
@softwareguy74 should be fixed by https://github.com/JasperFx/marten/pull/1329
