### ISSUE TITLE
How to prevent a foreign key field from being saved in the json field?

### ISSUE THREAD

**Issue by softwareguy74** [JasperFx/marten#1312]
Using the following:

    public class Tenant
    {
        public Guid Id { get; set; }
        [ForeignKey(typeof(User))]
        public Guid? CreatedBy { get; set; }
        public string Name { get; set; }
    }

how can I prevent the CreatedBy field from also showing up in the json field, and only getting stored as a column?  This would be much more efficient.  The CreatedBy field would of course have to then serialize back into the object in a query result.  I see no reason to store the foreign key twice.

**Comment by mysticmind** [comment]
@softwareguy74 Remember that Marten is a document store/event store and the primary unit of storage is JSON and a well-defined Postgres table structure. To enable Foreign Keys which is more of a RDBMS construct, Marten enables the mechanism to create a duplicate field (Postgres Column) of the `CreatedBy` from the JSON.

I understand you reasoning around efficiency of not storing the same data twice. But for Marten, the JSON is the primary storage structure and the duplicated field for Foregin key is a secondary data derived from the JSON to enable additional features such as Foreign keys, duplicated fields etc. Marten is designed to work in a certain way to enable a list of features to strike a balance to provide a strong document store/event store and other misc. features.

Hope I have provided a satisfactory answer to your query, closing the same.

**Comment by oskardudycz** [comment]
I'd need to doublecheck if that's not possible via duplicate field settings with current implementation.

**Comment by oskardudycz** [comment]
I checked that, and I second what @mysticmind wrote.
