### ISSUE TITLE
Change the Connection lifecycle to be sticky to a DocumentSession

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#132]
I’ve had conversations here and otherwise with 5-6 different people about the connection management in Marten. I think the clear feedback is that we should change the `DocumentSession`/`CommandRunner` mechanics so that each `IDocumentSession` has one and only one connection object (bound lazily though) for it’s lifetime, and expose that off of the IDocumentSession interface.

The changes:

- Moves some transaction mgmt out of the CommandRunner class and up into the DocumentSession itself
- `IDocumentSession.Connection` will give you access to the current connection w/ the transaction already started, so folks can use Dapper within the same DB transactions as the Marten session
- All of the `IDocument.OpenSession()` methods will get a new, optional argument specifying the isolation level for the transaction of that session

**Comment by CoreyKaylor** [comment]
Sounds like the ideal way I would think about the relationship between session, connection, transaction.

**Comment by kiliman** [comment]
:+1: Thanks! That's exactly what I'm looking for.

**Comment by jeremydmiller** [comment]
Mid week at the earliest though;)

**Comment by phatboyg** [comment]
Sounds perfect!

**Comment by jeffdoolittle** [comment]
:+1:

**Comment by phillip-haydon** [comment]
:+1:

**Comment by jeremydmiller** [comment]
I think I have this one done locally.
