### ISSUE TITLE
Searchable on multiple properties and where's

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#135]
2 feature requests around indexing.

**1) Ability to set multiple Searchable properties.**

Scenario is, I have a bunch of photos, there are 3 queries I will run often.

``` csharp
session.Query<Photo>().Where(x => x.MemberId = 123);
session.Query<Photo>().Where(x => x.MemberId = 123 && x.IsPrivate == true);
session.Query<Photo>().Where(x => x.IsPrivate == false);
```

I would like to be able specify an index which spans both `MemberId` and `IsPrivate`

**2) Ability to add conditions to an index**

``` csharp
_.Schema.For<Login>()
  .Searchable(x => x.Email, where: x => x.Status == Login.Status.Active);
```

This would generate a table with Email indexed with a where clause to pre-filter where the status is Active. 

Like:

``` sql
CREATE INDEX mt_doc_login_idx_email ON public.mt_doc_login (email) WHERE(data->>'Status') == 'Active';
```

**Comment by jeremydmiller** [comment]
@phillip-haydon Man, I'm sorry, but I'm declaring this one a little too much work prior to 1.0. Maybe in the next round. For now, I think we just need to say do this kind of index by hand.

**Comment by phillip-haydon** [comment]
No worries. I want to fix the date issue before I even look into this one.

**Comment by phillip-haydon** [comment]
Closing as conditional indexes is already implemented. Raising new ticket for multi-property indexing.
