### ISSUE TITLE
add IDbCommand Interceptors to add support for SET [LOCAL] and row level security 

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#1352]
Can we add an extension point for support of SET [LOCAL], see this implementation for an example
https://medium.com/@cazzer/designing-the-most-performant-row-level-security-strategy-in-postgres-a06084f31945

**Comment by mdissel** [comment]
A structural solution would be to add support for CommandInterceptors, something like
```
public interface IDbCommandInterceptor
    {
        void ReaderExecuting(IDbCommand command, DbCommandInterceptionContext<IDataReader> interceptionContext);
        void ReaderExecuted(IDbCommand command, DbCommandInterceptionContext<IDataReader> interceptionContext);

        void NonQueryExecuting(IDbCommand command, DbCommandInterceptionContext<int> interceptionContext);
        void NonQueryExecuted(IDbCommand command, DbCommandInterceptionContext<int> interceptionContext);

        void ScalarExecuting(IDbCommand command, DbCommandInterceptionContext<object> interceptionContext);
        void ScalarExecuted(IDbCommand command, DbCommandInterceptionContext<object> interceptionContext);
    }
```
The current logging and retry policy could be refactored and implemented as an IDbCommandInterceptor.

see [here](https://github.com/shuxinqin/Chloe/blob/a4b91af68830593cfad56639beca22051582a30a/src/Chloe/Core/InternalAdoSession.cs) for a sample implementation

**Comment by mdissel** [comment]
Adding interceptors seems te be a big refactoring of all the ExecuteReader and ExecuteNonQuery commands. the IManagedConnection should be extended with IDataReader functions and refactor all the Execute methods to only call ExecuteNonQuery. 
I think we should refactor this to only 3 IDbCommand methods (and the async variants) and remove the current Execute(..) methods.
```
IDataReader Read(NpgsqlCommand cmd);
int Execute(NpgsqlCommand cmd);
object Scalar (NpgsqlCommand cmd);
```

Other ideas? please let me know if this is a no-go.

**Comment by jeremydmiller** [comment]
The `SET LOCAL` or role setting could be done as an `IStorageOperation`. Doesn't require any kind of extension really. YOu could even do this today with an `ISessionFactory`, just needs docs. I think the interception pipeline is too heavyweight for just that.

**Comment by jeremydmiller** [comment]
This is very likely never getting done, and you could effect this yourself anyway.
