### ISSUE TITLE
Querying Documents with LINQ doesn't work when using JsonProperty name Attribute

### ISSUE THREAD

**Issue by mabeh** [JasperFx/marten#1358]
```
public class User
{
   [JsonProperty("first_name")]
   public string FirstName { get; set; }
}
```
`session.Query<User>().Where(x => x.FirstName == "SomeUser") `
Added a user with the name "SomeUser" before, but result is 0.
It works without the JsonProperty attribute.

**Comment by oskardudycz** [comment]
@mabeh Marten is JSON serializer agnostic. That means that it's unaware of the JSON.NET properties and its serialization consequences. SQL queries are generated based on the .NET lambda, so if you have property serialized with a different name than .NET property name then it won't be able to find it in the database.

**Comment by mabeh** [comment]
Thanks for the answer
