### ISSUE TITLE
More flexible Auto Create Schema Objects

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#136]
I would like a more flexible Auto Create Schema, out of fear :)

Auto creation in production is awesome.
Auto update of Columns in production are awesome too.

However auto re-creation in production is scary, but is awesome in development.

I would like to say something like:

Dev:
`_.AutoCreateSchemaObjects = AutoCreate.All`

Prod:
`_.AutoCreateSchemaObjects = AutoCreate.CreateAndUpdate`
or
`_.AutoCreateSchemaObjects = AutoCreate.CreateOnly`

Disabled:
`_.AutoCreateSchemaObjects = AutoCreate.Off`

-----

`All` would Create / Destroy / Recreate

`CreateAndUpdate` would create the tables and and/update indexes but never destroy the table.

`CreateOnly` would create the initial tables but never update anything, would require manual updates from the generated schema.

`Off` would disable all auto creation.

That's my thoughts so far.

**Comment by jeremydmiller** [comment]
We might need to be getting smarter with indexes here. Sounds good to me.

**Comment by jeremydmiller** [comment]
I've got this partway so far. Good hour might finish it off.

**Comment by dotnetchris** [comment]
What scenarios would not be covered by CreateAndUpdate that only All would sufficient?

Would that mostly be constrained to activities such as rename type, rename existing property?

**Comment by phillip-haydon** [comment]
@dotnetchris All will drop and re-create... Create and Update will not re-create so no data loss.

**Comment by dotnetchris** [comment]
What types of changes to c# classes result in schema changes that need drop to occur?
