### ISSUE TITLE
Calls to mt_immutable_timestampt/mt_immutable_timestamptz fail with duplicated fields

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#1378]
Similar to #837, after upgrading Marten I'm getting the following error message when updating a type with a duplicated column:

`schema "public" does not exist`

I can see a statement being executed like:

`update myschema.mt_doc_mytype as d set message_timestamp = public.mt_immutable_timestamptz(data -> 'Message' ->> 'Timestamp') where (d.tenant_id = :tenantid and d.id = :arg9)`

^ Note the `public.mt_immutable_timestamptz` - also note that when creating my document store I am setting `DatabaseSchemaName = myschema`. 

The problem seems to be here in [DuplicatedField](https://github.com/JasperFx/marten/blob/0839ec6d364cdfd07ead7ccba15785ae29e72cb8/src/Marten/Schema/DuplicatedField.cs#L101) - a _new_, default `StoreOptions` is being created, instead of using the configured one.

**Comment by cocowalla** [comment]
Will send a PR for this shortly

**Comment by stvoidmain** [comment]
Nice to see this worked out!
Letme know if you need help to try something.
(sorry for not camoing up before, was on a very tight spot with work)
