### ISSUE TITLE
NullReferenceException when IQueryable converting String.Equals 

### ISSUE THREAD

**Issue by evingle** [JasperFx/marten#1380]
Hi,

I am encountering an issue when using the latest Marten 3.9.0. The code throws a null reference exception and stack trace refers to Marten

Code:
`string Email = null;
var query = session.Query<UserAccount>().Where(x => string.Equals(x.Email, Email, StringComparison.OrdinalIgnoreCase)).ToList();`

Stack trace:
System.NullReferenceException: Object reference not set to an instance of an object. at Marten.Linq.WhereFragment.<>c.<.ctor>b__0_0(Object x) at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext() at System.Linq.Buffer`1..ctor(IEnumerable`1 source) at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) at Marten.Linq.WhereFragment..ctor(String sql, Object[] parameters) at Marten.Linq.Parsing.StringComparisonParser.Parse(IQueryableDocument mapping, ISerializer serializer, MethodCallExpression expression) at Marten.Linq.MartenExpressionParser.WhereClauseVisitor.VisitMethodCall(MethodCallExpression expression) at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor) at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node) at Marten.Linq.MartenExpressionParser.ParseWhereFragment(IQueryableDocument mapping, Expression expression) at Marten.Linq.Model.LinqQuery`1.buildWhereFragment() at Marten.Linq.Model.LinqQuery`1..ctor(DocumentStore store, QueryModel model, IIncludeJoin[] joins, QueryStatistics stats) at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel) at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor) at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor) at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor) at Remotion.Linq.QueryProviderBase.Execute(Expression expression) at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression) at Remotion.Linq.QueryableBase`1.GetEnumerator() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

Thank you for the help!

**Comment by oskardudycz** [comment]
@evingle could you provide your `UserAccount` structure and `DocumentStore` configuration?

**Comment by evingle** [comment]
Here is an example code:

```
public class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var documentStore = InitialDocumentStore();
                var userAccounts = documentStore.QuerySession().Query<UserAccount>()
                    .Where(x => string.Equals(x.Email, null, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        private static DocumentStore InitialDocumentStore()
        {
            var connectionString =
                "Host=localhost;Port=5433;Database=Test;Username=postgres;Password=123456;Pooling=false;";

            var serializer = new Marten.Services.JsonNetSerializer();
            serializer.Customize(_ =>
            {
                _.DateParseHandling = Newtonsoft.Json.DateParseHandling.DateTimeOffset;
                _.TypeNameHandling = Newtonsoft.Json.TypeNameHandling.None;
            });

            return DocumentStore
                .For(_ =>
                    {
                        _.Connection(connectionString);
                        _.Serializer(serializer);
                        _.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
                    }
                );
        }
    }

    public class UserAccount
    {
        internal UserAccount()
        {
        }

        internal UserAccount(string id, string email, bool? isNotPrimary = null)
        {
            Id = id;
            Email = email;
        }

        public string Id { get; private set; }

        public string Email { get; private set; }
    }
```
