### ISSUE TITLE
Question regarding DocumentSession.Query() with Linq

### ISSUE THREAD

**Issue by Gikerl** [JasperFx/marten#1387]
Hello,

I am trying to check if a PostgreSQL database contains an object with a certain Id. 
For this purpose, I used three approaches:

1. DocumentSession.Query<T>().Where(x => x.Id == id).Any()
2. DocumentSession.Query<T>().Where($"WHERE id = \'{id}\'").Any()
3. DocumentSession.Load<T>(id) != null

The Linq query was by far the slowest and required 1750ms on average. 
The query using the SQL string in contrast only required 25ms on average.
The workaround using the Load method required 140ms on average.

Am I using the Linq query wrong? Why is the query user a SQL string 70 times faster?
Thank you for the help in advance!

I'm using Marten 3.7.1, PostgreSQL 10.10 for Ubuntu, .Net Framework 4.62

**Comment by mysticmind** [comment]
@Gikerl There shouldn't be so much variance. Could you please share a test repo with the fuller representative code so that we can check and revert?

**Comment by Gikerl** [comment]
@mysticmind  

With an example project I could not recreate the issue. Here the times were as to be expected:

- Linq Query: 166ms
- String Query: 124ms
- Load: 186 ms

In the example project I noticed that the first time opening a session is very time consuming, which probably explains the long time the first query took.

**Comment by oskardudycz** [comment]
@Gikerl first time opening a session creates a Marten schema, tables, functions etc. (if you have empty db), so it's desired and unavoidable behaviour (unless you're using manual schema migration with AutoCreate.None and Patch scripts).
