### ISSUE TITLE
StartStream on EventStore does not throw exception if stream already exists

### ISSUE THREAD

**Issue by Crown0815** [JasperFx/marten#1388]
I am trying to ensure that a stream does not exist yet by creating it with the `StartStream` method. I found that I do not get an exception even if the stream exists. 

The following code snippet works without any exceptions although I would have expected one to be thrown in line 5.
```csharp
public void StartStream(Guid streamId)
        {
            DocumentSession.Events.StartStream(streamId);
            DocumentSession.SaveChanges();
            DocumentSession.Events.StartStream(streamId);
            DocumentSession.SaveChanges();
        }
```
Am I missing something? 

I'm using Marten 3.7.1, PostgreSQL 10.10 for Ubuntu, .Net Framework 4.62

**Comment by mysticmind** [comment]
@Crown0815 since you are not storing any events, in this case, it is essentially an empty stream hence does not get stored in DB even though you attempt to save changes. If you had added any events then you would see an exception `ExistingStreamIdCollisionException`.

**Comment by Crown0815** [comment]
@mysticmind There is a actually a stream in the database after calling the first `SaveChanges()`. It seems that the `StartStream` method does not actually check whether the steam exists but whether the stream is at a **version greater than zero**. 

Is this intentional?

**Comment by mysticmind** [comment]
Yes, you are right, it looks like there isn't a check for Stream Id exists. We would need to add a check. Marking this as a bug. We will discuss and take it up.

**Comment by mysticmind** [comment]
@Crown0815 Quick follow on note, even though there is an entry in the db with zero events, only when a stream contains events, there would be conflict and hence checking for stream exists for `StartStream` is essential to throw an exception. The current implementation satisfies this requirement. So I think we can go ahead and close this unless you think a check is required. Thoughts>

**Comment by jeremydmiller** [comment]
@mysticmind @Crown0815 We almost wiped out `StartStream()` several times in the early days and just saying that `AppendEvent` is a de facto *upsert*. I think we should do the check that @Crown0815 is suggesting, but it would be breaking behavior and shouldn't be done until 4.0.

**Comment by jeremydmiller** [comment]
From ongoing conversations, this will be enforced in Marten v4

**Comment by jeremydmiller** [comment]
Duplicate with #1648
