### ISSUE TITLE
Save enums as their string value rather than int value

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#139]
Unsure about this one but figured I should raise it so we can discuss it.

Right now enums are stored as `int` by default, but it's nice to be able to view the data in the database without having to look up what the value of it is. 

So would be good to store the `string` value of the enums.

**Comment by bojanv91** [comment]
It would be nice this to be configurable.

**Comment by jeremydmiller** [comment]
The JSON serialization configuration is easy, but I ran into trouble using Enum values as Npgsql parameters before.

**Comment by jeremydmiller** [comment]
Done!

```
StoreOptions.UseDefaultSerialization(EnumStorage.AsString);
```
