### ISSUE TITLE
Setup Sponsorship plan

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#1393]
Investigate and setup one of the sponsorship options on one of the existing solutions like:
- OneCollective,
- GitHub sponsorship, 
- Patreon, etc,
- others.

**Comment by mysticmind** [comment]
We don't need to restrict it to just one option, it can be one or more options.

**Comment by oskardudycz** [comment]
@mysticmind fully agree, however, we should not give our users too many options, so they didn't feel lost and don't need to spent too much time on decision what option to choose 👍

**Comment by Hawxy** [comment]
I'd be pretty happy with OpenCollective, akin to https://opencollective.com/vuejs.

Open-source sponsorship is something my workplace is considering going into the new year.
