### ISSUE TITLE
Create a separate domain name for Marten

### ISSUE THREAD

**Issue by mysticmind** [JasperFx/marten#1399]
We can host the main website at this domain which will establish as a go to place for users who want to know about Marten, docs, sponsors and everything can be aggregated at one place.

**Result:**
https://martendb.io/ was selected and used as the domain.

**Comment by oskardudycz** [comment]
@jokokko bought marten.io 👍

**Comment by mysticmind** [comment]
martendb.io or marten.io? I guess it is the former

**Comment by oskardudycz** [comment]
Right, my bad -martendb.io.

**Comment by oskardudycz** [comment]
@jokokko will you configure Github pages to use new custom domain?

**Comment by jokokko** [comment]
So the A records are now set.
```
id 45359
opcode QUERY
rcode NOERROR
flags QR RD RA
;QUESTION
martendb.io. IN A
;ANSWER
martendb.io. 1798 IN A 185.199.109.153
martendb.io. 1798 IN A 185.199.110.153
martendb.io. 1798 IN A 185.199.111.153
martendb.io. 1798 IN A 185.199.108.153
;AUTHORITY
;ADDITIONAL
```

**Comment by oskardudycz** [comment]
@jokokko I configured that on the GitHub settings. It's almost working.
![obraz](https://user-images.githubusercontent.com/5562528/70129691-866a6a00-167f-11ea-99bf-f55a1d7666f7.png)
Probably some paths to CSS needs to be tweaked. I'll try to have a look at that 👍

**Comment by mysticmind** [comment]
typically we also have to add a CNAME record pointing to `jasperfx.github.io` since Marten is hosted under `jasperfx.github.io/marten/` it could pose a problem.

**Comment by mysticmind** [comment]
I would suggest that we host the a seperate docs in netlify and then do the DNS settings pointing to it. this way, the existing site will work fine and at some point we can sunset the github.io url

**Comment by oskardudycz** [comment]
I like the idea of using Netlify. I can try to configure that.

**Comment by jokokko** [comment]
Alright. Once done, I'll update the DNS records (30 min TTL on the current A records)...

**Comment by mysticmind** [comment]
@oskardudycz if you to give it a shot go ahead, you can just use a manual deploy for now by dragging dropping the folder in the Netlify deploys page.

**Comment by oskardudycz** [comment]
@mysticmind I’ll try to configure automatic deployment in the evening  (I did that already for my other pages done in GatsbyJS)

**Comment by oskardudycz** [comment]
I managed to setup Netlify deploy.

URL: https://lucid-northcutt-013a56.netlify.com/

DNS Record: martendb.io A 104.198.14.52

Or it's possible to use Netlify DNS for the domain (as I did in my other Netlify deployments):
- dns1.p02.nsone.net
- dns2.p02.nsone.net
- dns3.p02.nsone.net
- dns4.p02.nsone.net

However, there is still the same issue as with github docs 🙃 It seems that our script is addin `marten` prefix for the paths. I'm trying to find out how it's done, but I don't know yet. I'll keep you posted. Probably PR will be needed.

**Comment by oskardudycz** [comment]
I prepared the PR https://github.com/JasperFx/marten/pull/1403 that updates the configuration.

I published already the fixed content to `gh-pages-netlify` and Netlify.

**Comment by jokokko** [comment]
So as discussed in Gitter, NS records updated...

**Comment by oskardudycz** [comment]
Thank you. It works! 🏆 
![obraz](https://user-images.githubusercontent.com/5562528/70213691-41efd480-173a-11ea-85c3-ed34808e045c.png)

I'll also configure additionally https on Netlify when DNS fully propagate. 

I think that after reviewing and merging my changes to the build script (https://github.com/JasperFx/marten/pull/1403) we're fine to close that task! 😄

**Comment by mysticmind** [comment]
Closed via #1403

**Comment by mysticmind** [comment]
![image](https://user-images.githubusercontent.com/2864208/70247460-69c55380-179f-11ea-9a04-16be0816b568.png)

since martendb.io is a https site, there are js files and images which are http resulting in mixed content.

**Comment by oskardudycz** [comment]
@mysticmind I’ll check that and try to provide a fix in a separate PR.

**Comment by mysticmind** [comment]
@oskardudycz I have fixed mixed content issue of http links in https. Also found some link and images linking issues in doc pages (already existing issues) which I have fixed as well. I will send a PR shortly.

**Comment by oskardudycz** [comment]
Closed via https://github.com/JasperFx/marten/issues/1399
