### ISSUE TITLE
Support for Load params

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#140]
Would like support for `Load` with multiple Ids

e.g
```
var ids = new [] { 1, 4, 6, 7 };

var result = session.Load<Member>(ids);
```

This would result in `List<Member>`

This can be achieved using:

`select data from mt_doc_photo where id = ANY(:arg0 ::int[])`

Where `:arg0` is a parameter of type `Text`

Using Npgsql

```
var command = con.CreateCommand();

command.CommandText = "select data from mt_doc_photo where id = ANY(:arg0 ::int[])";

var name = "arg0";

var parameter = command.CreateParameter();
parameter.ParameterName = name;
parameter.Value = "{90, 92, 93}";
command.Parameters.Add(parameter);

var result = new List<string>();

using (var reader = command.ExecuteReader())
{
    while (reader.Read())
    {
        Console.WriteLine(reader.GetString(0));
    }
}

con.Close();
```

**Comment by jeremydmiller** [comment]
@phillip-haydon How is that different from what we already do? You can load multiple documents by an array or enumerable of document id's:

http://jasperfx.github.io/marten/documentation/documents/loading/

**Comment by phillip-haydon** [comment]
Ah I guess it's already supported then.

I honestly never looked at the doco for that one, I looked at the code for `Load<T>` and saw there was no overloads or anything like `LoadAll<T>` and figured it was not supported.

I think the only difference is that the current API isn't intuitive in my opinion.

**Comment by jeremydmiller** [comment]
Yeah, I agree. What if it's called `LoadMany()` or something instead?

**Comment by phillip-haydon** [comment]
`LoadAll` or `LoadMany` works for me.
