### ISSUE TITLE
Rebrand look & feel of the Marten documentation

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#1401]
Make it more aligned with the current standards. Create proper landing page.

I like personally the look of Hasura web page: https://hasura.io/ and https://docs.hasura.io/1.0/graphql/manual/remote-schemas/index.html.

**Comment by mysticmind** [comment]
We are using VitePress for building the new v4 docs site. Currently VitePress does not support importing code snippets like what is available in VuePress. I have sent a PR https://github.com/vuejs/vitepress/pull/238 for the same.

In the interim, I will migrate the changes to use VuePress. That said, VitePress is blazing fast and would definitely I love to use it more.

Once the PR is merged and a new release is available, will migrate it back to VitePress.

**Comment by mysticmind** [comment]
We now have the VitePress based docs including handling of code snippets fully functional. Closing this.
