### ISSUE TITLE
Setup branded martendb.io email addresses for the maintainers

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#1415]
Setup branded martend.io email addresses for the maintainers and more generic contact email.

**Comment by mysticmind** [comment]
https://www.zoho.com/mail/ - we could possibly use this to start with, it provides a "free forever plan" as below:
> Up to five users, 5GB/User, 25MB attachment limit. Web access only. Email hosting for single domain.

**Comment by oskardudycz** [comment]
I can setup it also on my provider. I'm paying for my personal email and I have (more or less) unlimited emails and domain with the outlook support in my abonament.

**Comment by jokokko** [comment]
@oskardudycz, @mysticmind I remember using Zoho in the past... Should be fine. If we just setup the relevant records (SPF etc.) accordingly... Which reminds me that it's a bit problematic if these things are behind one person, i.e. a bus factor of one. At the very least should ensure that core maintainers all have access to DNS records.

**Comment by mysticmind** [comment]
@jeremydmiller @oskardudycz @jokokko I am going ahead and setting up Zoho email using MailLite plan (INR 59 i.e. less than 1 USD /user/month) which supports IMAP/POP clients, mobile apps and calendar rather than the "Forever Free" plan which only provides web access.  To start with, we will create 4 accounts i.e. one for each and in addition we could add say `support` account later.

**Comment by mysticmind** [comment]
We could create a gmail account like martendb@gmail.com and use it as a admin account to manage domain/DNS entries and also the the contact email for Zoho mail. The password for this can be maintained in a shared password manager like BitWarden or share it in email.

Thoughts?

**Comment by mysticmind** [comment]
I have setup few things for next steps:
- I have setup an account (Families Organization $1/month) in Bitwarden to manage shared passwords etc. Invite sent to the core maintainers
- Created an account in purelymail.com for martendb.io email addresses. this is $10/year. Admin account access is shared in Bitwarden. I will work with @jokokko to setup the DNS entries and then create the email accounts for each.

**Comment by mysticmind** [comment]
@jokokko I had provided the DNS entries as a DM in gitter, did you get a change to check it? Alternatively, if you login into purelymail.com using the credentials in Bitwarden and goto https://purelymail.com/manage/domains, you can access the same details.

**Comment by jokokko** [comment]
@mysticmind got your DM. So currently martendb.io has NS records for https://ns1.com/ so the entries need to be done there. Btw. not seeing any credentials in Bitwarden. Claims I belong to no organizations, yet invitation says that invitation already accepted. If you please re-invite me. If that doesnt work, then need I need to contact their support...

**Comment by mysticmind** [comment]
@jokokko Just figured out that, I have to confirm the accepted invite. Please check now and confirm.

**Comment by mysticmind** [comment]
![image](https://user-images.githubusercontent.com/2864208/84470711-8936bf00-aca1-11ea-8196-ca1f494082cb.png)

You can see the list users in the org.

**Comment by jokokko** [comment]
@mysticmind yep, working now, thanks! And then the next question: who has the NS1 creds and can they be shared? Since we need to do the MX & other records there.

**Comment by mysticmind** [comment]
DNS entries added and we have setup email accounts for each of the maintainers and also have a generic email as `support@`. I will share the details as DM in gitter

**Comment by mysticmind** [comment]
I am also planning to setup "Basecamp Personal" for internal discussions/communication around further commercial/sustainability aspects. Please let me know your thoughts.

@jeremydmiller @oskardudycz  @jokokko  Also let me know which email account i.e. personal or the martendb.io email address for the Basecamp account so that it is easier on you end.

**Comment by mysticmind** [comment]
We have created the email accounts for the maintainers.
