### ISSUE TITLE
Including an index before a document alias causes the index to be generated with an incorrect table name

### ISSUE THREAD

**Issue by TCBroad** [JasperFx/marten#1416]
When configuring marten using StoreOptions, it appears that if a DocumentAlias is used and it is the last expression in the statement then the names of indexes are generated incorrectly. This happens when adding an index to an existing table and running the command line tooling to generate a patch.

E.g. (class names changed, but otherwise the same)

```c#
Schema.For<OriginalNameEntity>()
   .Identity(x => x.Id)
   .IdStrategy(new CombGuidIdGeneration())
   .ForeignKey<RelatedEntity>(x => x.RelatedId)
   .Index(x => x.Username)
   .DocumentAlias("alias_name");
```

outputs the following schema migration:

```sql
-- snipped
CREATE INDEX mt_doc_originalname_idx_username ON public.mt_doc_originalname (  (data ->> 'Username'));
-- snipped
```

If the DocumentAlias and Index lines are swapped then the following sql is generated, which is correct:

```sql
-- snipped
CREATE INDEX mt_doc_alias_name_idx_username ON public.mt_doc_alias_name (  (data ->> 'Username'));
-- snipped
```

I didn't see in the documentation that these configuration calls need to happen in a specific order, so wondered if this was a bug?

**Comment by oskardudycz** [comment]
@TCBroad currently, unfortunately, the config ordering might be fragile for the ordering. I'm not sure how easy would be to make it less ordering-agnostic. If we can't come up with something then for sure we should updated documentation (as you suggested).

**Comment by jeremydmiller** [comment]
We can actually beat this easily. Just put the alteration registered by the `DocumentAlias()` first in order I think.
