### ISSUE TITLE
Support for extensions like IsOneOf(...)

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#142]
Would like support for extension methods.

Ability to pass an array of values to find one where the record matches.

```
session.Query<Product>(x => x.CategoryId.IsOneOf(new [] { 1, 4, 6 })).ToList();
```

Which would use PostgreSQL's `ANY(...)` 

-----

2nd would be to allow for case insensitive look ups like:

```
session.Query<Product>(x => x.Name.IEqual("hello world")).ToList();
```

Which would translate to something like `where d.data ->> 'Name' ILIKE 'hello world'`

**Comment by phillip-haydon** [comment]
I had a go at implementing this but I've never dived into expression trees or anything, so I can't figure out how to do the mapping in `JsonLocator` since Extension Methods don't give an Expression Object (`var @object = expression.Object;`)

Keen to help out where I can on this one.

**Comment by jeremydmiller** [comment]
@phillip-haydon I'm going to split this one into two issues for easier tracking. One for the extensibility mechanism, and another for the actual IsOneOf method if that's alright
