### ISSUE TITLE
RetryPolicy does not apply to AssertDatabaseMatchesConfiguration

### ISSUE THREAD

**Issue by mronnblom-cint** [JasperFx/marten#1424]
RetryPolicy is awesome, thanks for that feature!

I have found one minor issue with it, in that it does not apply to AssertDatabaseMatchesConfiguration, which I would expect it to. Might not be a bug per se, but I think that a common scenario is to call AssertDatabaseMatchesConfiguration quite early in the application startup, and having retries for the initial db connection is desireable IMO.

```
var documentStore = DocumentStore.For(_ =>
{
	...
	_.RetryPolicy(new FooRetryPolicy());
});

documentStore.Schema.AssertDatabaseMatchesConfiguration(); // No retries..
```

The workaround is rather simple though, so this could be considered low priority. ;)
```
var retryPolicy = new FooRetryPolicy();
var documentStore = DocumentStore.For(_ =>
{
	...
	_.RetryPolicy(retryPolicy);
});

retryPolicy.Execute(documentStore.Schema.AssertDatabaseMatchesConfiguration);
```

**Comment by oskardudycz** [comment]
@mronnblom-cint that seems legit.
Would you like to provide PR for that? It shouldn't be hard to do, I can provide the guidance.

**Comment by mronnblom-cint** [comment]
@oskardudycz I can give it a shot if you think it's not too time consuming. Inject IRetryPolicy into TenantSchema?

**Comment by oskardudycz** [comment]
@mronnblom-cint you should be able to get `IRetryPolicy` from the `StoreOptions` that are [already injected](https://github.com/JasperFx/marten/blob/master/src/Marten/Storage/TenantSchema.cs#L18)  into `TenantSchema` (using its [RetryPolicy](https://github.com/JasperFx/marten/blob/master/src/Marten/StoreOptions.cs#L264) method).

Then you would need to inject it to [https://github.com/JasperFx/marten/blob/master/src/Marten/Schema/SchemaPatch.cs] and use it in [Apply](https://github.com/JasperFx/marten/blob/master/src/Marten/Schema/SchemaPatch.cs#L192) method that's used inside `AssertDatabaseMatchesConfiguration` through [ToPatch](https://github.com/JasperFx/marten/blob/master/src/Marten/Storage/TenantSchema.cs#L92) method.

How does it sound for you?

**Comment by mronnblom-cint** [comment]
@oskardudycz I had a chance to look at the code a bit more. It seems to me that wrapping `SchemaPatch.Apply` in the RetryPolicy wouldn't be enough, since there is a conn.Open() call in `TenantSchema.ToPatch`, which might fail. I suppose you could wrap `TenantSchema.AssertDatabaseMatchesConfiguration` (and possibly also `TenantSchema.ApplyAllConfiguredChangesToDatabase` as these two methods are probably the ones you might use in runtime), but it feels a bit unclean. What do you think?

```
        public void AssertDatabaseMatchesConfiguration()
        {
            StoreOptions.RetryPolicy().Execute(() =>
            {
                var patch = ToPatch(false, withAutoCreateAll: true);

                if (patch.UpdateDDL.Trim().IsNotEmpty())
                {
                    throw new SchemaValidationException(patch.UpdateDDL);
                }
            });
        }

        public void ApplyAllConfiguredChangesToDatabase(AutoCreate? withCreateSchemaObjects = null)
        {
            StoreOptions.RetryPolicy().Execute(() =>
            {
                var defaultAutoCreate = StoreOptions.AutoCreateSchemaObjects != AutoCreate.None
                    ? StoreOptions.AutoCreateSchemaObjects
                    : AutoCreate.CreateOrUpdate;

                var patch = ToPatch(true, withCreateSchemaObjects ?? defaultAutoCreate);
                var ddl = patch.UpdateDDL.Trim();

                if (ddl.IsEmpty())
                    return;

                try
                {
                    _tenant.RunSql(ddl);
                    StoreOptions.Logger().SchemaChange(ddl);

                    _tenant.MarkAllFeaturesAsChecked();
                }
                catch (Exception e)
                {
                    throw new MartenSchemaException("All Configured Changes", ddl, e);
                }
            });
        }
```

**Comment by jeremydmiller** [comment]
Guys, this just isn't gonna happen. Or at least not in the main method. This functionality is in Weasel now.
