### ISSUE TITLE
SaveChangesAsync fails when storing documents with multiple FKs and sub classes

### ISSUE THREAD

**Issue by tonykaralis** [JasperFx/marten#1429]
### Issue
When calling save changes on several documents with a FK on another document, which has not been saved to the database yet, the save fails.
The following code fails, with the exception detailed below.
```
 _dataRepo.Store(RespondentIdMaps);
result.Questions.ForEach(x => _dataRepo.Store(x));
await _dataRepo.SaveChangesAsync();
```
When splitting the save into 2 calls, the operation is successful(see example.)
```
 _dataRepo.Store(RespondentIdMaps);
await _dataRepo.SaveChangesAsync();
result.Questions.ForEach(x => _dataRepo.Store(x));
await _dataRepo.SaveChangesAsync();
```

### Stack
Postgres v11
ASP.NET Core 2.2

### Store Config:

``` c-sharp
options.Schema.For<RespondentIdMapping>().ForeignKey<Survey>(x => x.SurveyId)
                                               .ForeignKey<Project>(x => x.ProjectId)
                                               .ForeignKey<Country>(x => x.MarketId);

options.Schema.For<IQuestionData()
.AddSubClassHierarchy(DocumentStoreConfigExtensions.GetQuestionDataTypes())
.ForeignKey<Survey>(x => x.SurveyId)
.ForeignKey<Country>(x => x.CountryId)
.ForeignKey<RespondentIdMapping>(x => x.RespMapId);
```

### Additional info
* Project, survey and country Id already exist in the database prior to any calls.
* A single IDocumentSession is used and scoped to a single httprequest.

### Stack trace
>Marten Command Failure:$ select data.mt_insert_iquestiondata(arg_country_id := :arg0, arg_resp_map_id := :arg1, arg_survey_id := :arg2, current_version := :arg3, doc := :arg4, docDotNetType := :arg5, docId := :arg6, docType := :arg7, docVersion := :arg8);select data.mt_insert_iquestiondata(arg_country_id := :arg9, arg_resp_map_id := :arg10, arg_survey_id := :arg11, current_version := :arg12, doc := :arg13, docDotNetType := :arg14, docId := :arg15, docType := :arg16, docVersion := :arg17);select data.mt_insert_iquestiondata(arg_country_id := :arg18, arg_resp_map_id := :arg19, arg_survey_id := :arg20, current_version := :arg21, doc := :arg22, docDotNetType := :arg23, docId := :arg24, docType := :arg25, docVersion := :arg26);select data.mt_insert_iquestiondata(arg_country_id := :arg27, arg_resp_map_id := :arg28, arg_survey_id := :arg29, current_version := :arg30, doc := :arg31, docDotNetType := :arg32, docId := :arg33, docType := :arg34, docVersion := :arg35);select data.mt_insert_iquestiondata(arg_country_id := :arg36, arg_resp_map_id := :arg37, arg_survey_id := :arg38, current_version := :arg39, doc := :arg40, docDotNetType := :arg41, docId := :arg42, docType := :arg43, docVersion := :arg44);select data.mt_insert_iquestiondata(arg_country_id := :arg45, arg_resp_map_id := :arg46, arg_survey_id := :arg47, current_version := :arg48, doc := :arg49, docDotNetType := :arg50, docId := :arg51, docType := :arg52, docVersion := :arg53);select data.mt_insert_iquestiondata(arg_country_id := :arg54, arg_resp_map_id := :arg55, arg_survey_id := :arg56, current_version := :arg57, doc := :arg58, docDotNetType := :arg59, docId := :arg60, docType := :arg61, docVersion := :arg62);select data.mt_insert_iquestiondata(arg_country_id := :arg63, arg_resp_map_id := :arg64, arg_survey_id := :arg65, current_version := :arg66, doc := :arg67, docDotNetType := :arg68, docId := :arg69, docType := :arg70, docVersion := :arg71);select data.mt_insert_iquestiondata(arg_country_id := :arg72, arg_resp_map_id := :arg73, arg_survey_id := :arg74, current_version := :arg75, doc := :arg76, docDotNetType := :arg77, docId := :arg78, docType := :arg79, docVersion := :arg80);select data.mt_insert_iquestiondata(arg_country_id := :arg81, arg_resp_map_id := :arg82, arg_survey_id := :arg83, current_version := :arg84, doc := :arg85, docDotNetType := :arg86, docId := :arg87, docType := :arg88, docVersion := :arg89);select data.mt_insert_iquestiondata(arg_country_id := :arg90, arg_resp_map_id := :arg91, arg_survey_id := :arg92, current_version := :arg93, doc := :arg94, docDotNetType := :arg95, docId := :arg96, docType := :arg97, docVersion := :arg98);select data.mt_insert_iquestiondata(arg_country_id := :arg99, arg_resp_map_id := :arg100, arg_survey_id := :arg101, current_version := :arg102, doc := :arg103, docDotNetType := :arg104, docId := :arg105, docType := :arg106, docVersion := :arg107);select data.mt_insert_iquestiondata(arg_country_id := :arg108, arg_resp_map_id := :arg109, arg_survey_id := :arg110, current_version := :arg111, doc := :arg112, docDotNetType := :arg113, docId := :arg114, docType := :arg115, docVersion := :arg116);select data.mt_insert_iquestiondata(arg_country_id := :arg117, arg_resp_map_id := :arg118, arg_survey_id := :arg119, current_version := :arg120, doc := :arg121, docDotNetType := :arg122, docId := :arg123, docType := :arg124, docVersion := :arg125);select data.mt_insert_iquestiondata(arg_country_id := :arg126, arg_resp_map_id := :arg127, arg_survey_id := :arg128, current_version := :arg129, doc := :arg130, docDotNetType := :arg131, docId := :arg132, docType := :arg133, docVersion := :arg134);select data.mt_insert_iquestiondata(arg_country_id := :arg135, arg_resp_map_id := :arg136, arg_survey_id := :arg137, current_version := :arg138, doc := :arg139, docDotNetType := :arg140, docId := :arg141, docType := :arg142, docVersion := :arg143);select data.mt_insert_iquestiondata(arg_country_id := :arg144, arg_resp_map_id := :arg145, arg_survey_id := :arg146, current_version := :arg147, doc := :arg148, docDotNetType := :arg149, docId := :arg150, docType := :arg151, docVersion := :arg152);select data.mt_insert_iquestiondata(arg_country_id := :arg153, arg_resp_map_id := :arg154, arg_survey_id := :arg155, current_version := :arg156, doc := :arg157, docDotNetType := :arg158, docId := :arg159, docType := :arg160, docVersion := :arg161);select data.mt_insert_iquestiondata(arg_country_id := :arg162, arg_resp_map_id := :arg163, arg_survey_id := :arg164, current_version := :arg165, doc := :arg166, docDotNetType := :arg167, docId := :arg168, docType := :arg169, docVersion := :arg170);select data.mt_insert_iquestiondata(arg_country_id := :arg171, arg_resp_map_id := :arg172, arg_survey_id := :arg173, current_version := :arg174, doc := :arg175, docDotNetType := :arg176, docId := :arg177, docType := :arg178, docVersion := :arg179);select data.mt_insert_respondentidmapping(arg_market_id := :arg180, arg_project_id := :arg181, arg_survey_id := :arg182, doc := :arg183, docDotNetType := :arg184, docId := :arg185, docVersion := :arg186);select data.mt_update_filerefs(arg_project_id := :arg187, doc := :arg188, docDotNetType := :arg189, docId := :arg190, docVersion := :arg191)$ $ 23503: insert or update on table "mt_doc_iquestiondata" violates foreign key constraint "mt_doc_iquestiondata_resp_map_id_fkey". Error Source = Marten. Inner Exception = Npgsql.PostgresException (0x80004005): 23503: insert or update on table "mt_doc_iquestiondata" violates foreign key constraint "mt_doc_iquestiondata_resp_map_id_fkey" at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<g__ReadMessageLong|0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<g__ReadMessageLong|0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) at Marten.Services.UpdateBatch.executeCallbacksAsync(NpgsqlCommand cmd, CancellationToken tkn, BatchCommand batch, List`1 list) at Marten.Services.UpdateBatch.<>c__DisplayClass27_1.<b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Marten.Services.ManagedConnection.ExecuteAsync(NpgsqlCommand cmd, Func`3 action, CancellationToken token). Error StackTrace = at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e) at Marten.Services.ManagedConnection.ExecuteAsync(NpgsqlCommand cmd, Func`3 action, CancellationToken token) at Marten.Services.UpdateBatch.ExecuteAsync(CancellationToken token) at Marten.Services.UnitOfWork.ApplyChangesAsync(UpdateBatch batch, CancellationToken token) at Marten.DocumentSession.SaveChangesAsync(CancellationToken token) at DataSchema.Repositories.Interfaces.DataRepo.SaveChangesAsync()
`

**Comment by mysticmind** [comment]
```csharp
using System;
using System.Threading.Tasks;
using Marten;

namespace marten_test
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var store = DocumentStore.For(_ =>
            {
                _.AutoCreateSchemaObjects = AutoCreate.All;
                _.Connection("host=192.168.99.100;database=marten_test1;password=postgres;username=postgres");
                _.Schema.For<DocB>()
                    .AddSubClassHierarchy(typeof(DocB1), typeof(DocB2))
                    .ForeignKey<DocA>(x => x.DocAId)
                    .ForeignKey<DocC>(x => x.DocCId);
            });

            using (var session = store.OpenSession())
            {
                var doc_a = new DocA
                {
                    Id = Guid.NewGuid()
                };
                
                var doc_c = new DocC
                {
                    Id = Guid.NewGuid()
                };

                var docB1_1 = new DocB1
                {
                    Id = Guid.NewGuid(),
                    DocAId = doc_a.Id,
                    DocCId = doc_c.Id,
                    NameB1 =  "test"
                };
                
                var docB2_1 = new DocB2
                {
                    Id = Guid.NewGuid(),
                    DocAId = doc_a.Id,
                    DocCId = doc_c.Id,
                    NameB2 =  "test"
                };
                
                session.Store(doc_a);
                session.Store(docB1_1);
                session.Store(docB2_1);
                await session.SaveChangesAsync();
            }
            
            Console.WriteLine("Run completed!");
        }
    }

    class DocA
    {
        public Guid Id { get; set; }
    }

    class DocB
    {
        public Guid Id { get; set; }
        public Guid DocAId { get; set; }
        public Guid DocCId { get; set; }
    }
    
    class DocC
    {
        public Guid Id { get; set; }
    }

    class DocB1 : DocB
    {
        public string NameB1 { get; set; }
    }
    
    class DocB2 : DocB
    {
        public string NameB2 { get; set; }
    }
}
```

Exception stack trace
```
Unhandled exception. Marten.Exceptions.MartenCommandException: Marten Command Failure:$
select public.mt_upsert_doca(doc := :arg0, docDotNetType := :arg1, docId := :arg2, docVersion := :arg3);select public.mt_upsert_docb(arg_doc_a_i
d := :arg4, arg_doc_c_id := :arg5, doc := :arg6, docDotNetType := :arg7, docId := :arg8, docType := :arg9, docVersion := :arg10);select public.m
t_upsert_docb(arg_doc_a_id := :arg11, arg_doc_c_id := :arg12, doc := :arg13, docDotNetType := :arg14, docId := :arg15, docType := :arg16, docVer
sion := :arg17)$
$
23503: insert or update on table "mt_doc_docb" violates foreign key constraint "mt_doc_docb_doc_c_id_fkey"
 ---> Npgsql.PostgresException (0x80004005): 23503: insert or update on table "mt_doc_docb" violates foreign key constraint "mt_doc_docb_doc_c_i
d_fkey"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Marten.Services.UpdateBatch.<>c__DisplayClass27_1.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Marten.Services.ManagedConnection.ExecuteAsync(NpgsqlCommand cmd, Func`3 action, CancellationToken token)
  Exception data:
    Severity: ERROR
    SqlState: 23503
    MessageText: insert or update on table "mt_doc_docb" violates foreign key constraint "mt_doc_docb_doc_c_id_fkey"
    Detail: Key (doc_c_id)=(3b0cb86d-2052-4180-9202-db49ced057d3) is not present in table "mt_doc_docc".
    Where: SQL statement "INSERT INTO public.mt_doc_docb ("doc_a_id", "doc_c_id", "data", "mt_dotnet_type", "id", "mt_doc_type", "mt_version", m
t_last_modified) VALUES (arg_doc_a_id, arg_doc_c_id, doc, docDotNetType, docId, docType, docVersion, transaction_timestamp())
  ON CONFLICT ON CONSTRAINT pk_mt_doc_docb
  DO UPDATE SET "doc_a_id" = arg_doc_a_id, "doc_c_id" = arg_doc_c_id, "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_doc_type" = docType, "
mt_version" = docVersion, mt_last_modified = transaction_timestamp()"
PL/pgSQL function mt_upsert_docb(uuid,uuid,jsonb,character varying,uuid,character varying,uuid) line 5 at SQL statement
    SchemaName: public
    TableName: mt_doc_docb
    ConstraintName: mt_doc_docb_doc_c_id_fkey
    File: ri_triggers.c
    Line: 3266
    Routine: ri_ReportViolation
   --- End of inner exception stack trace ---
   at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e)
   at Marten.Services.ManagedConnection.ExecuteAsync(NpgsqlCommand cmd, Func`3 action, CancellationToken token)
   at Marten.Services.UpdateBatch.ExecuteAsync(CancellationToken token)
   at Marten.Services.UnitOfWork.ApplyChangesAsync(UpdateBatch batch, CancellationToken token)
   at Marten.DocumentSession.SaveChangesAsync(CancellationToken token)
   at marten_test.Program.Main(String[] args) in D:\tinker_room\marten_test\Program.cs:line 52
   at marten_test.Program.<Main>(String[] args)
```

**Comment by jeremydmiller** [comment]
The "C" would have to be persisted, and that makes things work. See the UT that's about to be attached to this.

**Comment by tonykaralis** [comment]
Thanks @jeremydmiller but the repro code from @mysticmind does not represent my problem accurately. In the repro indeed C must be stored, however in my example C(respondentIdMaps) was being stored.

I'll try create a more accurate repro as this is still a problem for us. Im thinking there's some issue with the Subclass hierarchy that might be throwing it off.

**Comment by jeremydmiller** [comment]
@tonykaralis If you're going to do that, can you do it as a failing test in a PR?
