### ISSUE TITLE
How to store aggregates of different types that might have the same id?

### ISSUE THREAD

**Issue by raphaabreu** [JasperFx/marten#1430]
Hello! First of all, awesome project!

I have a question though: How can I use the event store when I have multiple aggregate roots and their Ids might be the same?

I am migrating a legacy project that used standard int64 sequence as primary key. Several root aggregates also use int64 sequences as primary keys. Is there any way to separate their streams? Using multi-tenancy is the only alternative?

Thanks in advance!

**Comment by mysticmind** [comment]
Please check [docs](https://martendb.io/documentation/events/identity), you can set the stream identity as string using `storeOptions.Events.StreamIdentity = StreamIdentity.AsString;` and then use some pattern like `/accounts/1`, `/users/1` etc for the stream id.

**Comment by oskardudycz** [comment]
@raphaabreu you can use also conjoined multitenancy and put as tenant the aggregate type. See more: https://martendb.io/documentation/documents/tenancy/configuring/

**Comment by jokokko** [comment]
One other option, if one wants to stick to `Guid`s, would be producing deterministic Guids and, if needed, namespace them differently. See something like https://github.com/Informatievlaanderen/deterministic-guid-generator

**Comment by oskardudycz** [comment]
@raphaabreu I'm closing the issue because of the inactivity. Feel free to ask further questions, then I'll reopen it.
