### ISSUE TITLE
Postgresql 12 support.

### ISSUE THREAD

**Issue by cszczotka** [JasperFx/marten#1433]
Hi,
Does the latest version of Marten support work with Postgresql 12 ? If not, when do you plan to support Postgresql 12 ?
Regards,

**Comment by apereiratl** [comment]
I'm currently using it with Postgres 12 (on windows) and it seems to be working fine. I've found nothing that indicates a lack of support. Is there a specific feature you're looking for that isn't supported?

**Comment by cszczotka** [comment]
Hi,
I just want to make sure ;-). For example on PLV8  page https://plv8.github.io/ I see info:
"PLV8 works with most versions of Postgres, but works best with 9.1 and above, including 10.0 and 11."
Regards,

**Comment by oskardudycz** [comment]
@cszczotka yes, we're supporting PG 12. The only potential issue is with the docker images with PLV8 that are not easily accessible, but PLV8 is used mostly for the PATCH API. Rest should work fine without any issues. PLV8 is additional feature, not the core one for Marten.

I'll prepare the PR with the updated build matrix and the information and readme about the support.

**Comment by apereiratl** [comment]
@cszczotka There is a commit from me that indicates how to setup plv8 for Postgres 12. The commit is at https://github.com/JasperFx/marten/commit/8c5240fa4c01baf9cf3e1d290465088f7e172aa7
That will help you get plv8 working on Postgres 12 as well if you so desire.

**Comment by oskardudycz** [comment]
@cszczotka please see PR https://github.com/JasperFx/marten/pull/1445. I added additional build for PG12. It's running and it's green 😉

**Comment by mysticmind** [comment]
> @cszczotka please see PR #1445. I added additional build for PG12. It's running and it's green 😉

Given the above confirmation, I am going ahead and closing this.
