### ISSUE TITLE
Issue with implementing FK on an array field.

### ISSUE THREAD

**Issue by apereiratl** [JasperFx/marten#1434]
.Duplicate(x => x.Tags, "bigint[]", NpgsqlDbType.Array | NpgsqlDbType.Bigint)

When defining a field which is 

```
public List<long> Tags { get; set; }
```
with
```
.ForeignKey<FormTag>(x => x.Tags)
```

I get the definition: 
```
tags                jsonb NULL,
```
and the error: 

42804: foreign key constraint "mt_doc_form_tags_fkey" cannot be implemented

Additionally, defining
```
.Duplicate(x => x.Tags, "bigint[]", NpgsqlDbType.Array | NpgsqlDbType.Bigint)
.ForeignKey<FormTag>(x => x.Tags)
```
still results in the column definition as above. Defining just the Duplicate definition defines the column correctly. 

I will look into fixing this issue as a ForeignKey should not override a Duplicate since the Duplicate provides an explicit definition for the column.

**Comment by apereiratl** [comment]
Incidentally, I believe this is related to the fact that when deriving schema, marten seems to have an issue with deriving column definitions for list<type> and defines it as jsonb.

**Comment by mysticmind** [comment]
@apereiratl `42804` error from Postgres means `data type mismatch`. For the issue at hand, Postgres does not allow creating foreign key on an array column (i.e. the duplicated field).

I am closing this issue. Please re-open and provide details if you still think it is a valid issue.
