### ISSUE TITLE
[Feature request] "Rollback" or "DiscardChanges" on IDocumentSession

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#1438]
Yesterday I ended up with a bit of a "weird" issue where my final solution was just...a bit too complex for my taste tbh. What I really would have needed in order to do a less crazy solution would have been a way to discard/rollback all changes in an `IDocumentSession`. 

Basically it would be nice to have an `IDocumentStore.DiscardChanges()` (I _think_ `DiscardChanges` is better naming than `Rollback` since it feels more related to `SaveChanges`) that just discards all currently registered changes in the `IDocumentSession`. 

Is this a feature that would be possible to introduce in Marten?

**Comment by oskardudycz** [comment]
@wastaz I think that's doable, we already have such for transaction handling. I'm fine with adding that.

@mysticmind @jeremydmiller @jokokko thoughts?

**Comment by mysticmind** [comment]
@oskardudycz yes, it looks like a useful functionality. `IdentityMap` has `ClearChanges` and if we add clear changes to `UnitOfWork` then it is trivial to expose the same in `DocumentSession`

**Comment by jeremydmiller** [comment]
I think this one should be relatively simple. I'm all in favor.

**Comment by raiiinyman** [comment]
> @oskardudycz yes, it looks like a useful functionality. `IdentityMap` has `ClearChanges` and if we expose `ClearChanges` (currently it is a private method) in `UnitOfWork` then it is trivial to impement the same in `DocumentSession`

when we have this feature in transaction , why need that  in IDocumentSession ?

after save change , change tracker is reset and we dont have changes for rollback ...
