### ISSUE TITLE
Generate schema's by type

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#144]
This is low priority, just thought it would be a nice to have.

Ability to write the DDL by type.

`martenStore.Schema.WriteDDLByType();`

This would simply add a folder to the bin (or overload for a path) and inside the folder would be each type as its own sql file: `photo.sql` / `member.sql`

This would make it easier to figure out what the change scripts for a particular type are when scripting stuff off manually without using the auto generate feature in production.

**Comment by jeremydmiller** [comment]
Want a master run_all.sql kind of file too? Might be important for ordering if we ever manage to do the foreign key feature.

Dump the system level sql too? There's quite a bit for the event store

**Comment by phillip-haydon** [comment]
I figured we would keep the `WriteDDL` which writes the run_all, but then `WriteDDLByType` would split by doc type. 

Not sure what the system level sql is?

**Comment by jeremydmiller** [comment]
@phillip-haydon You'd have some DDL for the event store support (when that exists). Moreover though, we'd eventually need these things to run in a certain order when (and if) we start creating the foreign key feature https://github.com/JasperFx/marten/issues/150. I'm not worrying about that part of this today though;)
