### ISSUE TITLE
Unable to execute command line tool to dump script to single output file

### ISSUE THREAD

**Issue by lowds** [JasperFx/marten#1448]
**Issue**
When attempting to use Marten.CommandLine to dump a single database script out to the file system I get the following exception:

> ERROR: System.UnauthorizedAccessException: Access to the path 'c:\temp\foo\db.sql' is denied.
>    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
>    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
>    at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
>    at System.IO.StreamWriter..ctor(String path)
>    at System.IO.File.WriteAllText(String path, String contents)
>    at Baseline.FileSystem.WriteStringToFile(String filename, String text)
>    at Marten.Storage.TenantSchema.WriteDDL(String filename, Boolean transactionalScript)
>    at Marten.CommandLine.Commands.Dump.DumpCommand.execute(IDocumentStore store, DumpInput input)
>    at Marten.CommandLine.MartenCommand`1.Execute(T input)
>    at Oakton.OaktonCommand`1.Oakton.IOaktonCommand.Execute(Object input)
>    at Oakton.CommandRun.Execute()
>    at Oakton.CommandExecutor.execute(CommandRun run)

Assume the (Windows) directory "c:\temp" already exists, then provide the following command line parameters:
`dump c:\temp\database.sql`

Instead of trying to create a "database.sql" file within "c:\temp" the code seems to create a directory called "database.sql" within "c:\temp".  It then attempts to write the file content to this directory (thinking it's a file) which then throws the above exception.

**Steps to reproduce**
1. Create a project that uses Marten.CommandLine
2. Configure the options as per https://martendb.io/documentation/cli/
3. Execute the command to dump a single script out to the file system:
`my-project.exe dump c:\temp\database.sql` 

**Investigation**
I've had a look through the code and I think the issue is linked to this call within DumpCommand.cs

`new FileSystem().CleanDirectory(input.FileName);`

https://github.com/JasperFx/marten/blob/fec62b50a0d30bc6b8860d76e9ed3f502d9d3052/src/Marten.CommandLine/Commands/Dump/DumpCommand.cs#L29

The CleanDirectory method within Baseline FileSystem seems to always treat the input string as a directory, deleting it if it exists, then creating the directory - thus we end up with a directory on the file system with the same name as our desired output file.

**Comment by mysticmind** [comment]
@lowds I will have a look at this issue and revert.

**Comment by mysticmind** [comment]
@lowds confirming this to be a bug, will look at providing a fix in the next release. In the interim, either pass just file name like `database.sql` or folder `c:\temp`. Failure happens only when a full path is passed containing both folder and file name fails.

**Comment by jeremydmiller** [comment]
@mysticmind I'm into things today, I can deal with this real quick
