### ISSUE TITLE
Disable default tenancy via store options

### ISSUE THREAD

**Issue by tonykaralis** [JasperFx/marten#1449]
In certain business cases all records added to a tenanted table should have a valid non-default tenant id.

It would be beneficial if we could disable the default tenant id that Marten injects if one is not provided via the store options. 

When disabling default tenancy, the desired behaviour would be to have an exception thrown and the transaction not committed.

@mysticmind is this sufficient?

**Comment by mysticmind** [comment]
@tonykaralis Thank for adding the issue, looks sufficient.
