### ISSUE TITLE
Allow update/delete of tenanted document from session with no TenantId

### ISSUE THREAD

**Issue by tonykaralis** [JasperFx/marten#1451]
### Use case:

The need to delete a tenanted document from within an "un-tenanted" session, similar to how the call to `.Store(tenantid, object)` works.

### Suggestions
1. Allow the tenant id to be changed/set from with an already created `IDocumentSession`
2. Potential methods as follows:
    * `_session.Update<T>(string tenantId, T object)`
    * `_session.Delete<T>(string tenantId, T object)`

**Comment by Miggleness** [comment]
Sounds reasonable.  

Shall we also add the following to `IDocumentSession`? It does make the API rather noisy

```csharp
void Delete<T>(string tenantId, T entity);
void Delete<T>(string tenandId, int id);
void Delete<T>(string tenantId, long id);
void Delete<T>(string tenantId, Guid id);
void Delete<T>(string tenandId, string id);
void Update<T>(string tenantId, params T[] entities);
```

**Comment by tonykaralis** [comment]
@oskardudycz @jeremydmiller Currently this is a pain point for us, the work around is to create a new session just to do the delete. Do you think this is something that could be addressed as part of 4.0? I am happy to help with a PR, but recall this not being as straight forward as it seems.

I have seen @Miggleness comment on adding various methods and i agree it does add a lot of noise to the API. Would my suggestion be feasible? Any other ideas or suggestions?

**Comment by jeremydmiller** [comment]
Finally updating this a bit. In the V4 branch so far, you can do:

* `IDocumentSession.DeleteByIdInTenant<T>(all the id types)`
* `IDocumentSession.Store(tenant Id, documents)`

We don't yet have anything for doing that with `Insert()` or `Update()` or `Delete(document)` operations. At this point after the V4 internals work, that's actually pretty low hanging fruit. Would you have any interest in doing the PR to finish this off?

If you start by looking at those two methods above, I *think* the code to finish that off will be self-explanatory and it should mostly be test coverage on the new methods.

**Comment by tonykaralis** [comment]
Sure, will have a stab at it 👍

**Comment by jeremydmiller** [comment]
If you go after that, it might be beneficial to make the method names consistent. I'm good with the `InTenant` suffix on everything rather than having yet more overloads.

**Comment by jeremydmiller** [comment]
@tonykaralis This ended up a little differently than we'd talked about in this issue. More in line w/ #1460, you can do **all** possible operations against a separate tenant within a single session by using syntax like `session.ForTenant("tenant id name").Store(doc)`. You effectively get a "nested" tenant session that still writes to the same transaction. Made the internals a lot simpler.
