### ISSUE TITLE
On a new database, auto create does not work as expected when there is a transaction scope

### ISSUE THREAD

**Issue by longility** [JasperFx/marten#1452]
I believe I simplified the issue. If I have more time, I may be able to create an example if needed to reproduce.

On a new database where there are no martendb generated functions, when my code has a transaction scope, postgres command fails to call the insert function when doing the following:

```csharp
using var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
using var session = documentStore.OpenSession(SessionOptions.ForCurrentTransaction());
session.Insert(entity); // Fails here. 
// cannot find db functions that are created by auto create says it does not exist
```

My guess is we need to autocreate the functions and maybe tables outside of the transaction scope or at least have an option to do that? Thoughts?

**Comment by oskardudycz** [comment]
@longility sorry for late answer. That sounds weird. Currently I don't know what might be the cause. We'll try to check that up.

**Comment by jeremydmiller** [comment]
I was able to reproduce this today, and I have no earthly idea why. I think this is going to need to be strictly a documentation item. Plus encouraging folks to not use ambient transactions.
