### ISSUE TITLE
MartenCommandException when use  operator == for DateTime in the Where after SelectMany 

### ISSUE THREAD

**Issue by abcelena** [JasperFx/marten#1454]
When use operator == to compare DateTime in the Where after SelectMany. Example:
```
 await searcher.GetQuery()
                .SelectMany(it => it.Charges)
                .Where(it => it.StartDate == date )
                .ToListAsync();
```

Exception is throwing:
Marten.MartenCommandException: 'Marten Command Failure:
42P01: missing FROM-clause entry for table "d"'

`"select x from (select jsonb_array_elements(CAST(d.data ->> 'Charges' as jsonb)) as x from mt_doc_chargesview as d where d.tenant_id = :tenantid) as sub1 where d.data @> :arg0"`

The problem is in the arg0:
"arg0" has value `"{\"StartDate\":\"2020-04-15T00:00:00\"}"`

Workaround use <= && >=  instead ==
```
 await searcher.GetQuery()
                .SelectMany(it => it.Charges)
                .Where(it => it.StartDate >= date &&  it.StartDate<= date )
                .ToListAsync();
```

**Comment by oskardudycz** [comment]
@abcelena That looks like a bug or missing feature. I'll try to have a look on that.

Sidenote: in general doing the `it.StartDate == date` is risky, as the .NET DateTime precision is higher than Postgres (same is for MSSQL).

**Comment by jeremydmiller** [comment]
@abcelena Querying against the exact value of a date is always dicey, especially if it's not a "round" date. You might have to use kind of a fuzzy "within a range" search if there are seconds/milliseconds as part of the time. As for the Linq not generating valid SQL, it appears that our huge overhaul of the Linq provider in v4 that eliminates the usage of the Containment operator fixes that issue at least.

Thanks for the feedback, and sorry it's taken so long to get this addressed.
