### ISSUE TITLE
Alternate syntax for nullable.HasValue doesn't work in LINQ

### ISSUE THREAD

**Issue by nbarbettini** [JasperFx/marten#1458]
This syntax works as documented:

```
.Query<Target>().Where(x => !x.NullableBoolean.HasValue)
```

This should be equivalent, but doesn't work:

```
.Query<Target>().Where(x => x.NullableBoolean.HasValue == false)
```

**Comment by oskardudycz** [comment]
@nbarbettini this currently does not work, as probably it treats that as a struct. Seems like a bug. We'll try to check that.
