### ISSUE TITLE
Please add DaemonSettings documentation

### ISSUE THREAD

**Issue by tetious** [JasperFx/marten#1464]
I'm a little mystified about what the properties do.

`LeadingEdgeBuffer` seems to need to be set to 0 if I want awaiting a Rebuild(or RebuildAll) to be deterministic and actually complete the rebuild before returning. No idea what it actually means or why I'd set it to something else, though. :)

`ExceptionHandling` seems to do nothing regardless of what I set it to. I'm sure I just don't understand how it works, though.

Many thanks for the help!

**Comment by oskardudycz** [comment]
@tetious I'll take that on me. Valid request 👍

**Comment by oskardudycz** [comment]
@tetious I started to add samples for AsyncDaemon in my repository. I hope to present also other settings there https://github.com/oskardudycz/EventSourcing.NetCore/pull/24

**Comment by jokokko** [comment]
This should be made a blocker for 4.0 right? No excuse for traversing into GH issues or unit tests to understand or discover the behavior?

**Comment by oskardudycz** [comment]
I planned to add it now, but as the Async Daemon will change significantly in v4 then after consultation we decided to add it in the v4. If I have enough time I'll try to squeeze it earlier.

**Comment by mysticmind** [comment]
Async Daemon docs are added in v4, closing this.
