### ISSUE TITLE
Replace the Dynamic Code Generation for v4

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1468]
If you look at the [pull request for Document Metadata](https://github.com/JasperFx/marten/pull/1364) and the code in `Marten.Schema.Arguments` you can see that our dynamic `Expression` to `Lambda` compilation code is getting extremely messy, hard to reason with, and difficult to extend.

**Idea**: Introduce a dependency on [LamarCodeGeneration and LamarCompiler](https://jasperfx.github.io/lamar/documentation/compilation/). LamarCodeGeneration has a strong model for dynamically generating C# code at runtime. LamarCompiler adds runtime Roslyn support to compile assemblies on the fly and utilities to attach/create these classes. We *could* stick with `Expression` to `Lambda` compilation, but that can't really handle any kind of asynchronous code without some severe pain and it's far more difficult to reason about (Jeremy's note: I'm uniquely qualified to make this statement unfortunately).

What gets dynamically generated today:

* Bulk importer handling for a single entity
* Loading entities and tracking entities in the *identity map* or version tracking

What could be generated in the future:

* Document metadata properties -- but sad trombone, that might have to stay with Expressions if the setters are internal/private :/
* Much more of the `ISelector` implementations, especially since there's going to be more variability when we do the document metadata
* Finer-grained manipulation of the `IIdentityMap` implementations and the `ISelector` mechanics to just flat out do less work on resolving objects

*Jeremy's note: After doing some detailed analysis through the codebase and the spots that would be impacted by the change to dynamic code generation, I'm convinced that this will lead to significant performance improvements by eliminating many existing runtime conditional checks and casts*

**Comment by pwhe23** [comment]
In the little bit I've played around with Lamar I was able to get it to work with internals using the InternalsVisibleTo attribute. I don't think this would help with privates though.

```c#
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Generated")]
var generator = new AssemblyGenerator { AssemblyName = "Generated" };
```

**Comment by jeremydmiller** [comment]
@pwhe23 Thanks for the reminder. We'll do the same here.

**Comment by jeremydmiller** [comment]
## Switchover tasks

- [ ] New storage-checking version of `IPersistenceGraph`
- [ ] Integrate `IPersistenceGraph` into `StoreOptions`
- [ ] Switch to the new generated bulk updaters
- [ ] Test bulk insert with hierarchies
- [ ] `PersistenceGraph` can return a storage object for a subclass
