### ISSUE TITLE
Internal/public accessor hunt

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1470]
As part of v4, ruthlessly go over the codebase and mark any type that shouldn't be exposed to clients as `internal`. Use the `[InternalsVisibleTo]` trick to sidestep that as a problem for the test suites.

**Comment by oskardudycz** [comment]
To clean up:

1. Remove the [AllProjectionsFor](https://github.com/JasperFx/marten/pull/1483/files#diff-ecf0d78902b9f2ac9ba5f43a409fa420R168) and [AllForView](https://github.com/JasperFx/marten/pull/1483/files#diff-f0d3ebe5f409ea63cf9cc1b18338b489R94) methods added to keep backward compatibility. Make `ProjectionsFor` and `ForView` methods return properly `IEnumerable`. Consider those and other related members as internal (they're not used anywhere besides single internal logic.
2. Move Async methods without token in QuerySession to QuerySessionExtensions (and look for similar places).
