### ISSUE TITLE
Using the Linq Where clause throws a Not Supported exception

### ISSUE THREAD

**Issue by RuymanCastello** [JasperFx/marten#1473]
When using the **Where** clause like :

`session.Query<MyClass>().Where(x => x.CustomObject == filter.customObject);`

The following exception is thrown:

```
System.NotSupportedException : The CLR type CustomObject isn't natively supported by Npgsql or your PostgreSQL. To use it with a PostgreSQL composite you need to specify DataTypeName or to map it, please refer to the documentation.
 at Npgsql.TypeMapping.ConnectorTypeMapper.GetByClrType(Type type)
   at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Marten.Services.CommandRunnerExtensions.<>c__DisplayClass3_0`1.<<FetchAsync>b__0>d.MoveNext()
```

MyClass is defined as:
```
public class MyClass
{
    public string Id { get; set; }
    public CustomObject CustomObject { get; set; }
}
```

and CustomObject implements `ToString()` and it's stored in the database as a string correctly.

How can we specify DataTypeName or map it?

**Comment by oskardudycz** [comment]
@RuymanCastello is `CustomObject` some specific type? We have the support for the nested objects so it should work. Is the `ToString()` specific? Could you provide more concrete sample?

**Comment by RuymanCastello** [comment]
Yes, the CustomObject could be MongoDb.ObjectId or a custom Id which has implemented the `ToString()` method.

Let's says we have this object:
```
public class CustomObject
{
    private string data;

   public override string ToString()
   {
      return data;
   }
}
```

That object is stored as `string` (so that works fine):

```
{
  id : 1,
  CustomObject : "specific custom data"
}
```

But it throws that exception when we try to use that property using Linq as :

`session.Query<MyClass>().Where(x => x.CustomObject == filter.customObject);`

The error message says: `you need to specify DataTypeName or to map it`

How can we do that?

**Comment by oskardudycz** [comment]
Ok, so that won't work. Linq treats this object as a basic type. As this type is not mapped in Postgres and Npgsql don't know such type. You'd need to register that in the NPGSQL - see more in https://www.npgsql.org/doc/types/enums_and_composites.html.

The other option is to expose the `Id` field and perform the query as:

session.Query<MyClass>().Where(x => x.CustomObject.iId == filter.customObject.Id);

**Comment by jeremydmiller** [comment]
@oskardudycz You'd be able to deal with this by extending new `IField` structure we're putting into v4. For right now, I'd say the best we could do is a better exception message.

**Comment by RuymanCastello** [comment]
@oskardudycz Do you mean I can map the CLR type as following:

` NpgsqlConnection.GlobalTypeMapper.MapComposite<CustomObject>("varchar"); `

I guess I can map it as `varchar`, is that correct?

**Comment by jeremydmiller** [comment]
@RuymanCastello I doubt that will work, depending on how Newtonsoft serializes that custom object. I'd try what @oskardudycz was saying about querying by the Id property of your custom type.

**Comment by oskardudycz** [comment]
@RuymanCastello, in theory, it's possible, however when I tried few times to define my own custom CLR type on PG then I've never succeeded. Still, this is more issue for Npgsql than Marten. 

I think that it would be easier to just use `.Id`. I understand that's a tradeoff for encapsulation, but that's the best concrete recommendation that I could give right now.

**Comment by jeremydmiller** [comment]
It's not just an issue for Npgsql, it's how the JSON is stored in the DB too

**Comment by oskardudycz** [comment]
@jeremydmiller right, it's a mixed issue.

**Comment by jeremydmiller** [comment]
I'm going to take this tomorrow morning for v4, but it's going to be done most likely by throwing a more descriptive exception telling you how to change the Linq query. Good enough for now?
