### ISSUE TITLE
Newtonsoft.Json PreserveReferencesHandling == Objects breaks many things

### ISSUE THREAD

**Issue by trullock** [JasperFx/marten#1475]
```
serializer.Customize(s => {
    s.PreserveReferencesHandling = PreserveReferencesHandling.Objects;
});
```

If you do this, then whereever the serialiser is used to create chunks of json, like in `DeleteWhere` you get an `$id` property on the json which breaks the `@>` operators.

It would be nice to fix this.

We should at least document this gotcha in the docs about customising serialization to save future souls

**Comment by trullock** [comment]
So, currently you can easily do the above ^ customisation and break Marten. Here is a proposal that so far seems ok:

```
        public PreserveReferencesHandling PreserveReferencesHandling
        {
            get
            {
                return this._serializer.PreserveReferencesHandling;
            }
            set
            {
                this._serializer.PreserveReferencesHandling = value;
            }
        }
```

Add this to JsonNetSerializer and encourage use of this property rather than via `Customize`. I cant promise this fixes all errors, but i haven't found any further errors/side effects yet and it can be documented as beta and is at least better than the current default position which is brokeness

**Comment by tonykaralis** [comment]
@trullock  Out of curiosity when does this break exactly? Is there a specific type of query thats failing?

You mentioned it breaking the `@> operators.`. Where are those used?

We have the following configuration and haven't noticed any breakage.

```chsarp
var customJson = new Marten.Services.JsonNetSerializer();
            customJson.Customize(o =>
            {
                if (customBinder != null)
                {
                    o.SerializationBinder = customBinder;
                }

                o.Formatting = Formatting.None;
                o.NullValueHandling = NullValueHandling.Ignore;
                o.TypeNameHandling = TypeNameHandling.Objects;
                o.PreserveReferencesHandling = PreserveReferencesHandling.Objects;
                o.ObjectCreationHandling = ObjectCreationHandling.Auto;
                o.DateFormatHandling = DateFormatHandling.IsoDateFormat;
            });
```

**Comment by trullock** [comment]
`DeleteWhere` is one case, I expect - although havent tested - `Patch` may also suffer from this

**Comment by jeremydmiller** [comment]
There's nothing actionable here.
