### ISSUE TITLE
General purpose logging mechanism for Marten

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#148]
I'm proposing a new interface that you can plug into Marten to receive logged events for:

* Opening or disposing a new session
* Each NpgsqlCommand executed by Marten, and hopefully in a way so that you can easily correlate
  requests to a session
* Command failures
* Command performance?

**Comment by phillip-haydon** [comment]
I'm not sure if its possible, but would be nice to extract `EXPLAIN` from queries too. Which probably falls under Command performance.

**Comment by jeremydmiller** [comment]
Before we put any effort into this, there is a facility in Npgsql to log commands. Might be worth either using that or even chipping into that project. It's just brute force logging with no context, but still.

**Comment by jeremydmiller** [comment]
Meh, I've tried a couple different concepts for this so far and there's too many issues with each. Npgsql's facility is limited, but at least it would catch everything that's done to the open connection. Right now, I'm leaning toward talking to that team and maybe trying to do some pull requests to them so that we could swap out their logger per command/connection so we could do session-based, contextual logging.
