### ISSUE TITLE
`.AddSubclass<T>()` does not behave the same as `.AddSubclassHierarchies()`

### ISSUE THREAD

**Issue by trullock** [JasperFx/marten#1492]
Calling `.AddSubclass<T>()` multiple times for a document does not behave the same as `.AddSublassHierarchy(T1, T2)`.

Using the former you are not able to perform actions (query/delete/load etc) on mid-hierarchy types. 

e.g. if you have `BaseType -> MidType -> LeafType` you cannot query against `MidType`.

The issue is because you end up with a `SubClassMapping` without the necessary aliases for the other types.

**Gitter chat on this subject**
https://gitter.im/JasperFx/marten?at=5ecfb35bff7a920a72191525

**Notes whilst I formulate the full scope of the issue**

`SubclassMapping.DeleteAllDocuments()` - is this buggy when using hierarchies? It looks to be. Investigate

**Comment by jeremydmiller** [comment]
Coming back to this after several years, I think it's just a potentially clumsy API that could use more docs
