### ISSUE TITLE
Compiled queries don't evaluate conditions that depend on parameters

### ISSUE THREAD

**Issue by ptmclean** [JasperFx/marten#1512]
I was hoping to use a single compiled query for filtering, paging and sorting of a set of aggregate models. In this scenario some of the parameters to the query would be nullable as they are optional. In this scenario the generated sql for the compiled query evaluates based on the first values used with the query. 

For example if I have the following query to search for quests, optionally filtered by Hero...
```c#
public class GetQuestsQuery : ICompiledListQuery<Quest>
{
    public Guid? Hero { get; set; }

    public Expression<Func<IQueryable<QuestDetails>, IEnumerable<QuestDetails>>> QueryIs()
    {
        return query => query.Where(x => !Hero.HasValue || x.Hero == Hero)
    }
}
```
The following is the sql that is generated...
``` sql
select d.data, d.id, d.mt_version 
from public.mt_doc_quest as d 
where ((true or CAST(d.data ->> 'Hero' as uuid) = :arg0) 
```

Note that the where condition includes a `true or`, I believe this equates to the `!Hero.HasValue ||` part of the Where clause in the Linq query. This occurs if the first usage of the query contains a null value for the Hero property. I believe the SQL generated should vary depending on the inputted parameter. 

I haven't yet dived into the code to see how this hangs together, but I can imagine why this might be hard to do. In anycase this feels like a common use case. I wonder how others have dealt with it.

**Comment by jeremydmiller** [comment]
"I can imagine why this might be hard to do" -- I can. Relinq reduces the expression `!Hero.HasValue` into the boolean value so the compiled query planner doesn't even know that the `Hero` property is used within the first part of the Where clause.

You're going to have to leave this open as a defect for now. I don't have any ideas for making this work without diving into Relinq itself.

**Comment by solyutor** [comment]
Stuck with the same problem. However I guess the original solution is  suboptimal. Besides complexity of parsing ling it creates cryptic SQL queries which are hard to read and may lead to messy execution plans. 

This can be fixed in a different way - caching not a single plan, but a set of `ICompiledQuery`s with custom `IEquatable` or `IEqualityComparer` implementations like this: 
```
public class GetQuestsQuery : ICompiledListQuery<Quest>, IEquatable<Quest>
{
    public Guid? Hero { get; set; }

    public Expression<Func<IQueryable<QuestDetails>, IEnumerable<QuestDetails>>> QueryIs()
    {
        if(Hero.HasValue)
		{
			return query => query.Where(x => x.Hero == Hero);
		}
		return query => query;
    }
	
    public bool Equals(Quest other) => Hero.HasValue == other.Hero.HasValue; 
	
    public int GetHashCode(Quest other) => Hero.HasValue.GetHashCode();
}
```
It will produce simpler SQL queries and avoid fighting with LINQ parsing. Still don't how hard it would be to implement the feature.

**Comment by jeremydmiller** [comment]
@solyutor What you're doing is never going to work because of the conditional inside of `QueryIs()`. In your case though, you could just use the user supplied query mechanism easily enough.

**Comment by solyutor** [comment]
@jeremydmiller Sorry for being unclear in my first message, I know (why) it doesn't work with current version.  What I meant was "Is it a good idea to create a PR for such a feature?" I've tried and here's what I've done https://github.com/solyutor/marten/commit/07cbf0ad928e68744e4d211740545862e85811f3. 

Hope you'll have some time to review it and decide whether it worth to create a PR.

**Comment by jeremydmiller** [comment]
@solyutor Sorry for taking so long to look at this. At this point, the compiled query implementation was rewritten for V4, so the potential PR wouldn't help. I'd honestly just say that you use separate compiled query types. I just don't want any more complexity in that code.
