### ISSUE TITLE
Enlisting in existing transaction scope fails

### ISSUE THREAD

**Issue by serefarikan** [JasperFx/marten#1514]
I noticed a behaviour that I cannot explain. If the first ever use of a session takes place under a `TransactionScope` , then the operation fails with a  `55000: prepared transactions are disabled` exception. 

Integration tests pass because text fixture accesses the document store prior to use of `TransactionScope ` 

I am not sure if this is a bug or me failing to see something fundamental in the way Marten is supposed to work, but I'm curious and would really like to understand what is going on here. I can try to trace the underlying reason but there are so many new things for me here it'd probably take way longer than asking the experts. 

**update**: the call prior to use of `TransactionScope` needs to be a write operation. Just querying for `User`  does not stop the exception but creating a new one does. 

Here is a standalone example to reproduce the issue:

```
using System;
using System.Linq;
using System.Transactions;
using Marten;
using Marten.Services;

namespace MartenApp
{
    public class UseMarten
    {
        private DocumentStore _docStore;

        static void Main(string[] args)
        {
            new UseMarten().enlist_in_transaction_scope();
        }

        public UseMarten()
        {
            _docStore = DocumentStore.For("host=localhost;database=marten_testing;password=postgres;username=postgres");
        }
        
        public void enlist_in_transaction_scope()
        {
            //remove comment, and this will work
            // CreateDocument();
            using (var scope = new TransactionScope())
            {
                using (var session = _docStore.OpenSession(SessionOptions.ForCurrentTransaction()))
                {
                    session.Store<User>(new User(){FirstName = "John", LastName = "Smith"});
                    session.SaveChanges();
                }
                scope.Complete();
            }
        }
        private void CreateDocument()
        {
            using (var lwSession = _docStore.LightweightSession())
            {
                var user = new User {FirstName = "Jane", LastName = "Smith"};
                lwSession.Store(user);
                lwSession.SaveChanges();
            }
        }
    }
    
    public class User
    {
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Internal { get; set; }
        public string UserName { get; set; }
        public string Department { get; set; }
    }
}
```

**Comment by serefarikan** [comment]
I spent quite a lot of time and learned a bit about how things work in Marten (just a bit though...) 
As far as I can see, the issue stems from a connection that is created and never disconnected as long as the application is running. 
I can see that first ever access to `DocumentStore` creates a connection which stays around until the application exists. This connection never goes away. If the first access to `DocumentStore` happens under a `TransactionScope`, then there are two connections created within that scope and that leads to an attempt to escalate to a distributed transaction, which leads to the exception I'm getting. So the reason calling `CreateDocument()` avoids the exception is because that single connection is opened outside of the `TransactionScope` and therefore does not enlist in the transaction,not leading to a distributed tx. 

If my understanding is correct, then the real question is why that particular connection is left open. If that's expected behaviour, then there is no issue here, this is something I have to live with. 

In case you're wondering, I'm experimenting with some metadata encoding that relates to multiple documents and I don't want to keep this metadata as documents, hence, the metadata and set of documents must be committed under a transaction to make sure that the whole commit succeeds or fails. 

Finally, what I should have said in the first place: fantastic work, really great library. Thanks!

**Comment by serefarikan** [comment]
It is the connection opened by the call to `generateOrUpdateFeature` in `Tenant`, called as a result of Marten making sure that storage exists for a document type (`Tenant.EnsureStorageExists(..)`). 

I'd say this behaviour is by design and I should watch for this gotcha. Closing this issue.

**Comment by kasparkallas** [comment]
Thank you! This helped out. The connection the `DocumentStore` opens is sneaky. We had to turn transaction enlistment off for it:
```
options.Connection(() =>
{
    var connectionStringBuilder = new NpgsqlConnectionStringBuilder(_connectionString);
    connectionStringBuilder.Enlist = false; 
    var connection = new NpgsqlConnection(connectionStringBuilder.ConnectionString);
    return connection;
});
```

But we kept the transaction enlistment for all `DocumentSession` instances by providing a connection source `Func`:

# 1.
```
services.AddScoped<NpgsqlConnection>(_ =>
{
    var connectionStringBuilder = new NpgsqlConnectionStringBuilder(connectionString);
    connectionStringBuilder.Enlist = true;
    var connection = new NpgsqlConnection(connectionStringBuilder.ConnectionString);
    connection.Open();
    return connection;
});
```

# 2. Note that `_npgsqlConnectionSource` is the `Func` from #1.
```
services.AddScoped<IDocumentSession>(sp => sp.GetRequiredService<DocumentStore>().OpenSession(
    new SessionOptions
    {
        Connection = _npgsqlConnectionAccessor(),
        OwnsTransactionLifecycle = false,
        EnlistInAmbientTransactionScope = true
    }
))
```

**Comment by serefarikan** [comment]
@kasparkallas  thank you! I cannot believe it's been months since I worked on Marten. I think your approach solves the problem I was having. I need to read it carefully, then dig out the code I wrote and refresh my memory. 

Many thanks for leaving this feedback.
