### ISSUE TITLE
Proposal for v4: Move the access for the DocumentMetadata to the Session level

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1517]
It'd make the mechanics a lot easier if we could move these methods that are today on `ITenant` to `IQuerySession`:

```
        /// <summary>
        ///     Fetch the entity version and last modified time from the database
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        DocumentMetadata MetadataFor<T>(T entity);

        /// <summary>
        ///     Fetch the entity version and last modified time from the database
        /// </summary>
        /// <param name="entity"></param>
        /// <param name="token"></param>
        /// <returns></returns>
        Task<DocumentMetadata> MetadataForAsync<T>(T entity,
            CancellationToken token = default(CancellationToken));
```

I'm not sure how commonly used these methods are outside the Marten testing suite, but the new v4 internals **really** want those method on `IQuerySession`. It's a breaking change, but it's the time we can do that and I think this is very minor.

**Comment by jeremydmiller** [comment]
Actually, I'm going to play benevolent dictator here and just make it so. The current location isn't even remotely discoverable, and there's a helluva lot of Law of Demeter violations going on in the test code to go find those methods.

**Comment by oskardudycz** [comment]
I'm not sure about the origins of why it was put inside the Tennant, but this change looks good to me. Will it then reuse an existing connection or still be opening the new one?

Btw. regarding the Metadata, do you plan to do more work on that? What's the plan?

**Comment by jeremydmiller** [comment]
@oskardudycz Sorry, I got impatient and just did it in the v4 branch. I'm happy to put the method back on ITenant, but it would quietly create a QuerySession. 

Getting back to a green build early this week is priority #1 to finish off the dynamic code generation and Linq overhaul. After that, the document metadata improvements should be a lot easier.
