### ISSUE TITLE
Duplicated field related generated sql, doesn't respect casing.

### ISSUE THREAD

**Issue by nikodemrafalski** [JasperFx/marten#1519]
Hi, probably a bug in Marten (3.12)

```
public class Something
{
   public Guid Id{get;set;}
   public Guid OtherId{get;set;
}
```

```
var store = DocumentStore.For(options =>
            {
                options.PLV8Enabled = true;
                options.Connection(config.ConnectionString);
                options.UseDefaultSerialization(EnumStorage.AsString, Casing.CamelCase);
                options.DatabaseSchemaName = config.SchemaName;
                options.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
                options.Schema.For<Something>()
                   .Duplicate(x => x.OtherId)
                   .VersionedWith(x => x.Version);
            });
```

When marten generates migration patch to populate duplicated  `other_id` it references to `OtherId` as `data ->> 'OtherId'` instead of `data -->> 'otherId'`.
At first id did not have duplicated column it is a migration to existing data.
 same patch like 
```
   session.Patch<Something>(x => x.OtherId== @event.StreamId && x.AnyTenant()).Set("anything", (string)null);
```
also generates SQL like that ```;update mt_doc_something as d set other_id= CAST(data ->> 'OtherId' as uuid) where (d.other_id= :arg19 and 1=1)```

I suspect there's a bug here (DefaultCasing hardcoded in both if branches)
https://github.com/JasperFx/marten/blob/61200af89aaafa1a71e76bcd95d20f2eb24ae9de/src/Marten/Schema/DuplicatedField.cs#L106

**Comment by mysticmind** [comment]
Fixed via #1520
