### ISSUE TITLE
Add EXPLAIN preview to the diagnostics

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#152]
See http://www.postgresql.org/docs/9.2/static/sql-explain.html. I don't think it's going to be too crazy to fetch the EXPLAIN plan behind a Linq query.

Might make an extension method off of IQueryable instead. This might get a little awkward when we introduce Include()

**Comment by nieve** [comment]
I can give that a go, if no one is looking into it (at least for non include queries). Should we add the optional parameters as well?

**Comment by jeremydmiller** [comment]
I don't think the code would be much different for the Includes. Just make sure we centralize the code for creating a DocumentQuery inside of the MartenQueryable, and you'd get the NpgsqlCommand object.

I'm drawing a blank, what do you mean about optional parameters?
