### ISSUE TITLE
Proposal for v4: Expose tenant meta data in DocumentMetadata

### ISSUE THREAD

**Issue by mysticmind** [JasperFx/marten#1522]
I propose to expose the following meta data pertaining to multi-tenancy:
- `IsTenanted` : If a document is tenanted, this value will be true
- `TenantId` : if tenanted, this will contain the tenant id otherwise empty

If you look at https://github.com/JasperFx/marten/issues/1460 and https://github.com/JasperFx/marten/issues/1451, there is a request for an option to update/delete tenanted documents in a non-tenanted session. In absense of this, currently users are resorting to mechanisms such as using a marker interface containing `TenantId` and all the tenanted documents will implement it. When data is queried, immaterial of tenanted or non-tenanted session, `TenantId` for the document is available to use. It works but is quite cumbersome.

Also when querying multi-tenanted documents, there is no way to know which tenant each of the document belonged to.

This meta data will help the Marten internals as well to use it in a non-tenanted session to deal with say updates/deletes easily. Also updates/deletes in tenanted/non-tenanted sessions open up some issues in terms of enforcing data isolation/security at a tenant level from an consumer standpoint, the mitigation strategy would be to provide some configuration options which will allow or disallow querying/updating/deleting tenanted documents in non-tenanted session or vice-versa which can configured at a per document level or at the global level.

Please let me now your thoughts.

**Comment by jeremydmiller** [comment]
I'm merging this into #1337
