### ISSUE TITLE
Exception on index creation when using uppercase characters in schema name

### ISSUE THREAD

**Issue by Thumann** [JasperFx/marten#1524]
Hi, 
This is sort of similar to the issue listed in https://github.com/JasperFx/marten/issues/799

Any uppercase characters in schema name will cause the DDL Change to fail when indexes are defined.

Example: 
With DatabaseSchemaName set to 'Midtvest' (uppercase M)
With AutoCreateSchemaObjects set to CreateOrUpdate and the following index being defined.
x.Schema.For<ElvaUser>().UniqueIndex(UniqueIndexType.DuplicatedField, x => x.UserName);

Which will generate the following change:
CREATE UNIQUE INDEX mt_doc_elvauser_idx_user_name ON Midtvest.mt_doc_elvauser ("user_name");

On the second intialization of the document store it will attempt to create the index again and fail with the following message:
" 42P07: relation "mt_doc_elvauser_idx_user_name" already exists"

Changing the schema name to being lowercase solves the issue.

I was helped by the friendly @oskardudycz here: 
https://gitter.im/JasperFx/marten?at=5f11757f724012319bb085b5

**Comment by jokokko** [comment]
Note to self: we need to link to https://www.postgresql.org/docs/current/sql-syntax-lexical.html in docs, especially on `quoted identifier`. Ofc things with Marten need to work OOTB, but a thing that can surprise devs (hopefully not DBAs, where they still exist).

**Comment by oskardudycz** [comment]
@Thumann could you provide details about the Marten version that you're using?

I tried your case with:

```
[Fact] // Control
        public void index_with_no_expression_should_match_DDL()
        {
            StoreOptions(_ =>
            {
                _.Schema.For<Company>()
                    .UniqueIndex(UniqueIndexType.DuplicatedField, c => c.Name);
                _.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
                _.DatabaseSchemaName = SchemaNameWithUpercase;
                _.PLV8Enabled = false;
            });

            theStore.Schema.ApplyAllConfiguredChangesToDatabase();
            theStore.Schema.ApplyAllConfiguredChangesToDatabase();
        }
```
and it's passing, I also checked how we're dealing with `_.DatabaseSchemaName`, and we're always doing `.ToLowerInvariant()`

```
 public string DatabaseSchemaName
{
        get { return _databaseSchemaName; }
        set { _databaseSchemaName = value?.ToLowerInvariant(); }
}
```
So it should not let us use schema other than lowe case.

Could you provide also your document store config?

**Comment by Thumann** [comment]
Update, 
The issues is caused by this line of code: 

x.Storage.MappingFor(entityType).DatabaseSchemaName = options.Schema.Name;

If I ToLower() it, everything works fine, if not, everything blows up.
