### ISSUE TITLE
Update the minimum Npgsql version for Marten to 4.1.4

### ISSUE THREAD

**Issue by mysticmind** [JasperFx/marten#1529]
With reference to a Gitter chat by @Hawxy quoted below:
> bleh, super annoying that nuget resolves the lowest version when a dependency has a version range. I thought I was on Npgsql 4.1.3 this whole time but it actually defaults to 4.1.2. I've been getting hit by the idle pruning bug for ages and thought I was going insane since it was already fixed. 
Yep, no more weird latency spikes due to connection recycling every 30 seconds 

It would be better to update the minimum required Npgsql version for Marten to 4.1.4 (the latest point release on Npgsql 4.x). Besides there are plenty of bug fixes happened between 4.12 through 4.1.4.

**Comment by oskardudycz** [comment]
CLosed by https://github.com/JasperFx/marten/pull/1531. Will be released in v3.12.4
