### ISSUE TITLE
QuerySession.Logger depends on concrete implementation

### ISSUE THREAD

**Issue by barclayadam** [JasperFx/marten#1548]
I have a custom `IManagedConnection` implementation that I want to use for better statement tracking (see #1284). Using `IMartenSessionLogger` is not sufficient for proper tracing as that is just a point in time _after_ the SQL has already executed, there is no way to get how long the command actually took.

The issue I have run in to is that `QuerySession.Logger` is hard-coded to expect a `ManagedConnection`, which breaks the contract of being passed in an `IManagedConnection`. 

So my question is, should `QuerySession` and / or `IManagedConnection` be changed to allow the contract to be fully public and not a hidden detail, or is there something further with statement tracking that we can look at?

I may be wrong but I cannot see any other obvious way of tracking performance over Npgsql _beneath_ Marten, so need to do in within Marten's usage.

**Comment by jeremydmiller** [comment]
@barclayadam First, I'm sorry it's taken so long to get to this. I made the tiny change so that you can override the `IManagedConnection` and still override the `Logger` on `IQuerySession`. Could I ask you to contribute your statement tracking connection to Marten and we'll work that in as an optional use thing? Sounds useful.

**Comment by barclayadam** [comment]
@jeremydmiller thanks for the update. I have actually just today been updating my code to work around this issue (by wrapping IDocumentSession, IBatchQuery and IMartenQueryable).

I'd be happy to contribute something back, but I'm not entirely sure the best route here to make it useful given the many different libraries for APM (i.e. Datadog, App Insights, Elastic APM, OpenTracing). Any thoughts?

In addition, although this will unblock me, the code will still rely on reflection to change the internals of `QuerySession` to actually override the `ManagedConnection` as it is not exposed anywhere to set/override it's creation (i.e. it's newed up in `DocumentStore.buildManagedConnection`).

**Comment by jeremydmiller** [comment]
@barclayadam,

"In addition, although this will unblock me, the code will still rely on reflection to change the internals of QuerySession to actually override the ManagedConnection as it is not exposed anywhere to set/override it's creation (i.e. it's newed up in DocumentStore.buildManagedConnection)." -- I'd vote to do something at the `DocumentStore.OpenSession()` methods the same way we today let you use your own NpgsqlConnection.

When Marten v4 is "done", I'm most likely going back to my Jasper tool to add Open Telemetry support. I'd be interested in hearing about what you're doing. I know there's the new Open Telemetry tracing built into .Net 5, but I haven't looked at all.

**Comment by barclayadam** [comment]
@jeremydmiller 

Being able to directly wire in a different implementation of IManagedConnection would certainly help, but I wonder if Marten should bake this in (i.e. from https://jimmybogard.com/building-end-to-end-diagnostics-activitysource-and-open/ implement the `Diagnostics` package code directly in Marten)? Having it built-in makes it a one-line light-up for consumers (`.AddSource("Marten")`) and should be lightweight for those not interested.

At the moment in our library we have a small APM abstraction with implementations for Elastic APM and a couple of others but Open Telemetry looks to make much more sense now.

Another thought is _what_ to track. I see 2 useful ways of tracing here... Either directly trace the actual SQL being executed, or, as I'm looking at doing at the moment, track the high-level operations. For example I _could_ have the "SQL" statement be either `Load<User>([id])` or `SELECT * FROM mt_doc_users WHERE id = [id]". I can see a benefit in both the options

I could look at a PR if you are interested, but wonder if it makes sense to wait for V4 as not sure on the state of that in terms of breaking changes?

**Comment by jeremydmiller** [comment]
@barclayadam,

I'd love to have this baked in, but my strong preference would be to do that only within V4 (master). And I'd absolutely take you up on the PR.

Hadn't talked to anyone else about this yet, but at a bare minimum now that we're going to only support .Net Core & .Net 5 is to wire up a new MartenLogger that wraps the .Net Core `ILogger` abstraction out of the box.
