### ISSUE TITLE
(Question) How to add 'LastModifiedBy' in a generic way?

### ISSUE THREAD

**Issue by mronnblom-cint** [JasperFx/marten#1550]
We are using Marten as a document storage. We would like to have a 'last_modified_by' on all document database tables, containing the user name who last modified each row. The logged on user is different from the account that accesses the database (the latter being a service account). The logged on user can be read from the current ClaimsPrincipal (AspNetCore 3.1).

We could add a property to all our objects and populate with the logged on user, but would prefer to avoid that, if it is possible to instead add it in a generic ("automatic") way. Searching the Marten documentation, I found [Document Policies](https://martendb.io/documentation/documents/customizing/document_policies/) but I cannot determine if/how this could be used for this purpose.

I also found [IDocumentSessionListener](https://martendb.io/documentation/documents/diagnostics/) that could trigger on all commits. Some kind of UserAccessor (reading from ClaimsPrincipal) could probably be injected into that Listener class. But I still need to put the user name somewhere. It doesn't feel quite right to have a LastModifiedBy property on all objects that is null most of the time (except when populated in the Listener).

Suggestions most welcome!

**Comment by jeremydmiller** [comment]
And I'm going to merge this into the bigger, "better document metadata" story for v4: #1337 

@mronnblom-cint So, the short answer is "you can't", but better document metadata is a frequent request and will be going into v4. I *think* that'll actually be the next biggish thing I tackle.
