### ISSUE TITLE
Multi-column index creation should throw if it makes no sense

### ISSUE THREAD

**Issue by lhaussknecht** [JasperFx/marten#1552]
I was a bit irritated, comming from an EF background, where index creation for multiple columns works by supplying an anonymous type.

Defining an index in Marten like that leads to an index, that makes no sense.

Given a Tour class with the following index creation

```csharp
configure.Schema.For<Tour>()
                    .Index(tour => new {tour.State, tour.City, tour.Depot, tour.Street});
```

This will result in an CREATE INDEX statement:

```sql
CREATE INDEX mt_doc_tour_idx_state_city_depot_street ON public.mt_doc_tour ( (data -> 'State' -> 'City' -> 'Depot' ->> 'Street'));
```

Of course this makes no sense and it is probably an pitfall for newbies, which might result in bad performance.

I know that the docs are right. You should supply an Expression to the Index method. But maybe we can add an exception here to make sure, that an index makes sense!

**Comment by jeremydmiller** [comment]
This wouldn't be a big story regardless if you decide to make Marten work the way you're implying (index spanning multiple property/fields) or to throw a helpful exception. I'm going to ask you to wait just until the end of this week and deal with it in master for v4 though.
