### ISSUE TITLE
Access DocumentMapping at runtime

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#1554]
I asked over in Gitter if there was a way to access `DocumentMapping` at runtime, for use building custom SQL queries, and Jeremy suggested I raise an issue about it - this is the issue :smile:

It's possible to access `DocumentMapping` from a `DocumentStore` (but not an `IDocumentStore`) using:

```c#
store.Options.Storage.MappingFor(typeof(MyType));
```

There are 2 points regarding this:

1. This should be discoverable (i.e. updated the docs) - I guess this should go under "Advanced Topics", or possible [here](https://martendb.io/documentation/schema/schema/)?
2. Consider making something accessible through `IDocumentStore`, but read-only, to ensure mappings can't get screwed up by users

**Comment by jeremydmiller** [comment]
You can do this now off of `IDocumentStore.Options`, but it's a read only view because it can't be changed at runtime.
