### ISSUE TITLE
Allow operation without metadata columns [Feature Request]

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#1557]
Some of my big tables (100,000,000+ rows) contain small document types, less than 1Kb, and the 3 existing Marten metadata columns (`mt_last_modified`, `mt_version` & `mt_dotnet_type`) take up 20% of the storage of these tables - it's GBs of disk space.

- `mt_version` is used for optimistic concurrency, but AFAIK you already need to opt-in to using this feature with `UseOptimisticConcurrency`
- `mt_dotnet_type` is only used if you are store type hierarchies
- `mt_last_modified` is used (I think) for some convenience methods to query based on last modified time

I personally sometimes do use these columns and their respective features, but I more often don't - as discussed in Gitter, this is a feature request to allow _opting out_ of having these metadata columns. I'm not suggesting changing the defaults, as that would affect backwards compatibility. I understand that this change would touch a lot of files, and realistically would only be considered for v4.

Thanks!

**Comment by jeremydmiller** [comment]
I'm merging this into #1337
