### ISSUE TITLE
Overhaul DocumentMapping model

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1558]
Just what it says. Its purpose has changed quite a bit.

Other things:

* memoize the construction of `DocumentTable`
* memoize the construction of the metadata columns?

**Comment by jeremydmiller** [comment]
Some tasks and ideas so far:

- [ ] Delete `IQuerableDocument` and use `IDocumentStorage` in all cases

**Comment by jeremydmiller** [comment]
**This is done in a branch, but not yet in master**

**Comment by toanxyz** [comment]
Hi @jeremydmiller , could you share why we remove the feature to have the custom MartenRegistry that has the schema.Include method?
