### ISSUE TITLE
Give users a friendly warning that Document types must be public

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1563]
Sorry folks, the new codegen model in v4 requires document types to be public. Make a good exception warning.

**Comment by oskardudycz** [comment]
Same for events? I like to keep all that’s possible as internal. Can we provide an option to add internal types manually via some config (as we do for other reasons with AddEventType method)?

**Comment by jeremydmiller** [comment]
Events don't have to be public. Different animal altogether fortunately

**Comment by jeremydmiller** [comment]
And we could go back to supporting internal document types if folks are willing to do an [InternalsVisibleTo] attribute I suppose.

**Comment by oskardudycz** [comment]
I’m not sure how others but I’m fine with using this attribute as a fallback.
