### ISSUE TITLE
Applying generic (where) predicate after (select) projection produces incorrect SQL query

### ISSUE THREAD

**Issue by kasparkallas** [JasperFx/marten#1569]
The following:
```
Expression<Func<T, bool>> IsBlueGenericPredicate<T>()
    where T : IHasColor =>
    t => t.Color == Colors.Blue;

var resultWithGenericPredicateForProjectedTarget = theSession
    .Query<ConcreteTarget>()
    .Select(x => new ProjectedTarget { Color = x.Color })
    .Where(IsBlueGenericPredicate<ProjectedTarget>());
```
Produces (incorrectly):
```
select jsonb_build_object('Color', CAST(d.data ->> 'Color' as integer)) as json from bugs.mt_doc_bug_xxx_generic_predicate_is_broken_for_linq_select_projections_concretetarget as d where CAST(d.data -> 'Color' ->> 'Color' as integer) = :arg0
  arg0: 1
```

The 2nd cast `CAST(d.data -> 'Color' ->> 'Color' as integer)` should be `CAST(d.data ->> 'Color' as integer)`.

This is broken in branch _3.13_ but works correctly in _master_. This is interesting because that is also the case for issue: https://github.com/JasperFx/marten/issues/1568

Repro: https://gist.github.com/kasparkallas/dbdbc64a1942a221191ad85b50bbc4a1

**Comment by jeremydmiller** [comment]
@kasparkallas master is the ongoing V4 work, and the Linq provider got in the neighborhood of a full rewrite. So the Linq code in Master damn well better be working better.

Doesn't help you get this solved right now though I know.

**Comment by jeremydmiller** [comment]
@kasparkallas I think the answer here has to be "hurry up and get V4 out" because this is just too time consuming to address with the V3 Linq support.
