### ISSUE TITLE
Support aggregate functions possible?

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#157]
From a little bit of googling, it appears postgresql will let you do aggregate functions from jsonb documents, i was hoping marten could do simple queries like the following test:

```
using (var session = store.OpenSession())
{
	session.Store(new Order() { Id = "order/1", Total = 10 });
	session.Store(new Order() { Id = "order/2", Total = 12 });
	session.SaveChanges();
}

using (var session = store.OpenSession())
{
	var result = session.Query<Order>().Sum(a => a.Total);
	result.ShouldBe(22);
}
```

However currently this returns the following error:
Marten.Schema.InvalidDocumentExceptionCould not determine an 'id/Id' field or property for requested document type System.Double

**Comment by nieve** [comment]
I'm looking into this. I think I've got an idea.

**Comment by jeremydmiller** [comment]
Go @nieve!

**Comment by phinett** [comment]
Brilliant thank you for this, will come in very handy!

What is the performance like for queries like this if you had say 500,000 rows with the data being inside the json document?

**Comment by nieve** [comment]
Great question- I got too bogged down by implementation details that I completely forgot about the bigger picture. I think tomorrow I'm gonna play about with benchmarking, just for fun. 

Btw, I think long count may have not been implemented as synchronous.

**Comment by jeremydmiller** [comment]
@nieve On your Sum(field), can you make sure that it's going through the IField.SqlLocator? Do that, and you could probably get a good perf boost by summing a "searchable" field.

**Comment by phinett** [comment]
I was thinking that if the performance isn't spectacular would it be worthwhile having the option to add the data into separate columns in the table, much like the search fields are at the moment which should work with large amounts of data.

**Comment by phinett** [comment]
Ah...there you go that's pretty much what i was getting at :-)

**Comment by nieve** [comment]
Cool, will look into it tomorrow.

**Comment by jeremydmiller** [comment]
@phinett Some day down the line we could also do "flattener" projections that write a doc into a flat, read-only table.

**Comment by nieve** [comment]
So that's what BenchmarkDotNet has to say:

```ini
BenchmarkDotNet=v0.9.2.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz, ProcessorCount=4
Frequency=2338446 ticks, Resolution=427.6344 ns
HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE [AttachedDebugger]

Type=SearchableVsJsonbAttributeSum  Mode=Throughput  

```
            Method |      Median |     StdDev |
------------------ |------------ |----------- |
 JsonbAttributeSum | 981.6329 ms | 26.0396 ms |
     SearchableSum | 548.5337 ms |  9.8045 ms |

**Comment by phinett** [comment]
Nice improvement for the searchable field, what was the data source, like how many rows of data?

**Comment by nieve** [comment]
1 million rows.

Code wise, btw, I didn't have to do anything, it's all being taken care of in `IDocumentMapping.JsonLocator`.
