### ISSUE TITLE
Document updates need to apply to the Patch API operations

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1570]
BOOOOO!!!!!

Shouldn't be too hard though.

**Comment by jeremydmiller** [comment]
This means things like "did a partial update against a document that has a version, so the version should be updated as well"

**Comment by jeremydmiller** [comment]
I'm unilaterally saying that we push anything around optimizing the Patch API to 4.1 just to cut scope.

**Comment by mysticmind** [comment]
Refer to #1834, closing this.
