### ISSUE TITLE
Race condition in Start method of Fetcher.cs

### ISSUE THREAD

**Issue by wwaniek5** [JasperFx/marten#1576]
I have a service with 9 projections implementing the `IProjection` interface. Each of them runs independently and has a separate Fetcher. Sometimes last_seq_id in the mt_event_progression table gets stuck and restart of the service is necessary. The problem is relatively reproducible for at least 10000 events. I managed to do a dirty workaround to fix the issue. In the Fetcher class I replaced the following code:

```
if (_fetchingTask != null && !_fetchingTask.IsCompleted)
{
       throw new InvalidOperationException("The Fetcher is already started!");
}

if (State == FetcherState.Active)
{
      return;
}
```

with

```

_logger.Verbose("Starting fetcher", _track.ViewType);

var i = 0;
var taskNotCompleted = _fetchingTask != null && !_fetchingTask.IsCompleted;
while (taskNotCompleted || State == FetcherState.Active)
{
    _logger.Verbose($" The Fetcher {_fetcherId} is already started or active, taskNotCompleted: {taskNotCompleted}, task status: {_fetchingTask?.Status} state: {State}",_track.ViewType);
    Thread.Sleep(1000);
    if (i > 5)
    {
        var e = new Exception(_fetcherId + "  " + track.ViewType.FullName + $" The Fetcher is still started or active, state: {State}");
        _logger.Error(e);
        throw e;
    }

    i++;
    taskNotCompleted = _fetchingTask != null && !_fetchingTask.IsCompleted;
}

_logger.Verbose("Finished waiting for the end of previous fetching task.", _track.ViewType);
```

After this fix I'm no longer able to reproduce the problem. Unfortunately, I'm not able to understand why sometimes the `taskNotCompleted` is true or `State == FetcherState.Active` (both cases can happen).

I hope someone more familiar with the code will be able to think of a better fix.

**Comment by jeremydmiller** [comment]
@wwaniek5 Honestly? This is going to be "fixed" in V4 by doing a 100% re-write of the async daemon with a little different concept and a lot more test coverage. We'll set up tests to simulate this many or more parallel projections running when we get there. If you need it faster, we can push this into 3.*.
