### ISSUE TITLE
Mapping with empty UniqueIndex() results in invalid DDL

### ISSUE THREAD

**Issue by ggmueller** [JasperFx/marten#1581]
Given a MartenRegistry:

```csharp
public class XRegistry : MartenRegistry
    {
      public XRegistry()
      {
        For<X>()
          .UniqueIndex();
      }
    }
```
UniqueIndex does not specify an expression. 

This creates the DDL

```sql
CREATE UNIQUE INDEX mt_doc_x_uidx_ ON public.mt_doc_x ();
```
The unique index would be created, but as no columns are specified it fails.

It would be nice to have an exception if you call `.UniqueIndex()` without providing any expressions.

**Comment by mysticmind** [comment]
Fixed via #1697
