### ISSUE TITLE
Improve startup speed

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/marten#159]
options:

* Roslyn ngen
* pre-generating the DocumentStorage code

**Comment by jeremydmiller** [comment]
To pre-generate it, we'd need to:

* Have a way to easily register all the document types upfront, even the ones that don't need any customization. I don't really wanna support type scanning directly for discovery, but we can expose just a "doc types are these types" method
* Definitely need a way to scan an assembly for the embedded IDocumentStorage types and load them
* New command off of Advanced to generate the code

**Comment by jeffdoolittle** [comment]
Awesome - curious what sort of speed improvements this brought about?

**Comment by jeremydmiller** [comment]
@jeffdoolittle 3-6 seconds on the initial hit

**Comment by jeffdoolittle** [comment]
beautiful. I'll check it out.
