### ISSUE TITLE
Method not found: 'Npgsql.NpgsqlDataReader Npgsql.NpgsqlCommand.ExecuteReader()' - Npgsql 5.x preview

### ISSUE THREAD

**Issue by kreditkenny** [JasperFx/marten#1595]
description
=========
getting a "Method not found: 'Npgsql.NpgsqlDataReader Npgsql.NpgsqlCommand.ExecuteReader()'." message when attempting to save an event.

dependencies
=========
- Npgsql (5.0.0-preview1)
- Marten (4.0.0-alpha.2)

code
====
public class SomeEvent : INotification
{
        public Guid Id { get; set; }
        public string Message { get; set; }
}

var event = new SomeEvent(); 
_session.Store(event);
await _session.SaveChangesAsync();

**Comment by mysticmind** [comment]
@kreditkenny Thanks for reporting this. Please note that Marten 4.x beta version is tested and works with Npgsql 4.x. Given that you are attempting to use Npgsql 5.x, there are bound to be breaking changes so I am not surprised to see the issue which you have reported. We will revisit this once we attempt to use Marten with Npgsql 5.x.

**Comment by kreditkenny** [comment]
thanks!

**Comment by mysticmind** [comment]
I am closing this one, refer to PR #1600
