### ISSUE TITLE
Remove the Lateral Join Query Support

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#160]
This strategy turned out to be slower for querying anyway, and it's making the internals more complicated. Can we just agree to nuke this?

See http://jeremydmiller.com/2015/11/09/optimizing-for-performance-in-marten/

**Comment by phillip-haydon** [comment]
If it's off by default then I'm not using it so I have 0 issues with it being ditched in favor of simplicity and performance.

:+1: :shipit:

**Comment by bojanv91** [comment]
I'm fine too, not using it. (y)
