### ISSUE TITLE
C# 9 Records Support

### ISSUE THREAD

**Issue by Hawxy** [JasperFx/marten#1601]
The code generation in Marten v4 does not compile when saving a [Record](https://devblogs.microsoft.com/dotnet/c-9-0-on-the-record/).

```
System.InvalidOperationException
Compilation failures!

CS1545: Property, indexer, or event 'document_inserts.RecordDocument.Id' is not supported by the language; try directly calling accessor methods 'document_inserts.RecordDocument.get_Id()' or 'document_inserts.RecordDocument.set_Id(?)'
```

[A failing test demonstrating this behaviour was added as part of my recent .NET 5 PR](https://github.com/JasperFx/marten/blob/master/src/Marten.Testing/Acceptance/document_inserts.cs#L55)

**Comment by oskardudycz** [comment]
@jeremydmiller ⬆️ 😅

**Comment by jeremydmiller** [comment]
@Hawxy I think that's more than a "just," but the fix would be only in Marten I think. We'll have to teach Marten's usage of the code generation to recognize w/ Reflection that this property isn't writeable and let it switch to using expressions (which is already supported for internal accessors).

**Comment by Hawxy** [comment]
That makes a lot more sense 😅 <sup><sup>I need to stop writing issues far too late at night</sup></sup>

**Comment by jeremydmiller** [comment]
@oskardudycz @Hawxy You get the dreaded "works on my box" from me. I don't see the compilation issue. That *maybe* was addressed by an update to the System.CodeAnalysis.* libraries through a LamarCodeGeneration/LamarCompiler update.

**Comment by jeremydmiller** [comment]
I'm closing this for now, but I did enable that test.
