### ISSUE TITLE
Event Store Improvements for V4

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1608]
This replaces #1307, but see the original conversations there. 

Also see @wastaz's [comments](https://github.com/JasperFx/marten/blob/v4/planning/MartenV4-WastazComments.md).

## Big Improvements

* [Improved Projection Support](https://github.com/JasperFx/marten/issues/1610)
* [Event Metadata](https://github.com/JasperFx/marten/issues/780)
* [Async Daemon Improvments](https://github.com/JasperFx/marten/issues/1609)
* [Partitioning Support for the Event Store](https://github.com/JasperFx/marten/issues/770)
* [Improved optimistic versioning of event stream append operations](https://github.com/JasperFx/marten/issues/922)
* [Mechanism to Import Events from external systems](https://github.com/JasperFx/marten/issues/1435)
* [Improved inline projections and event capture](https://github.com/JasperFx/marten/issues/1584)
* [Projection Snapshots](https://github.com/JasperFx/marten/issues/1611)
* [Stream Archiving](https://github.com/JasperFx/marten/issues/1612)
* [Event versioning and upcasting](https://github.com/JasperFx/marten/issues/1613)

## Tactical Changes

* [Event Store Feature Schema](https://github.com/JasperFx/marten/issues/1606)
* [Aggregate Stream for missing stream](https://github.com/JasperFx/marten/issues/1532)
* [StartStream() should enforce the stream is new](https://github.com/JasperFx/marten/issues/1388)
* [Using a long for the event sequence id](https://github.com/JasperFx/marten/issues/1080)
* [Stream locking for better event store concurrency](https://github.com/JasperFx/marten/issues/1614)
* [Recipe for easy testing of event projections](https://github.com/JasperFx/marten/issues/1615)

**Comment by oskardudycz** [comment]
@jeremydmiller we can consider also https://github.com/JasperFx/marten/issues/1639.

**Comment by jeremydmiller** [comment]
This epic story is reflected now in smaller stories. I'm closing just to make this list smaller.
