### ISSUE TITLE
Improved Projection Support

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1610]
# Dec. 17:  The current version of our thinking is here [v4eventstore](https://github.com/JasperFx/marten/blob/master/documentation/diagrams/v4eventstore.md)

There's some significant overlap with the [improved async daemon](https://github.com/JasperFx/marten/issues/1609) story. *Some* of the redesign is specifically to optimize the async daemon and projection rebuilds

At this point, here are what I think are the major points:

* The current `IProjection` interface should be an internal **runtime** detail of Marten and no longer something that
   is exposed as a plug in point
* Standardize the **definition** of a projection on a superset of the **interface** of the current `ViewProjection` mechanism, but rewrite the 
  internals of the existing `ViewProjection<T>` interface. The existing `ViewProjection` would be replaced with new internals. The new `ViewProjection` should also continue to support conventionally named public methods on the `ViewProjection` classes
* Use the same Roslyn runtime code generation we use in the document storage to take the new `ViewProjection` definitions and generate the absolutely most efficient runtime code possible to match the various apply/delete/create/etc. definitions
* Eliminate the original `IAggregator` & `AggregationProjection` mechanism for defining projections. Provide migration documentation for updating to v4's new model.
* Eliminate `DocumentsProjection` base class
* Allow for immutable aggregate documents (should be easy)
* The projections need to allow for defining steps by abstract or interface types instead of a concrete type the way you do today. That's been a big request.
* This **might** slip to >V4, but add support for `Partial` updates in projections through the Patching API. The code is gonna need to be smart enough to understand when it can use the patching API, or needs to go to full document updates. Also considering a model where you could define simple patches with `Expression` such that the projection could switch between the patching api and full document updates with only one place to configure things.

After going through all the feedback from @wastaz, @malscent, @oskardudycz and lots of other folks, I think we need to support 2-3 basic projection types (I'm suggesting that `ViewProjection` get split up a little bit):

1. Aggregate a document by the stream
1. Aggregate a document across streams by some other kind of grouping. This is obviously very similar to aggregating by streams in the mechanics, but you might add some additional duplicated fields to enable optimized async daemon support.
1. A more open, looser `Projector`(I think of as the @wastaz special) that let's you generate any number of low level Marten `IStorageOperation` from event types. More on this below. 

## V4 IProjection

These classes would be generated at runtime

```csharp
    public interface IV4Projection
    {
        // TODO -- probably some kind of identity like the old model
        // TODO -- probably some mechanism for setting up the async projection
        // model to try to highly optimize

        // TODO -- need a model for inline aggregation

        // Need this for the identity and tracking. Doesn't need to have any connection
        // to any kind of .Net type, but that's probably helpful for aggregates
        string ProjectionName { get; }

        // Might wanna expose something for diagnostics. I.e., what document types
        // it produces, what it consumes

        // Inline projections for the SaveChangesAsync() call
        ValueTask<IReadOnlyList<IStorageOperation>> ProjectAsync(EventPage page, QuerySession session, CancellationToken token);

        // Inline projections for the SaveChanges() call
        IReadOnlyList<IStorageOperation> Project(EventPage page, QuerySession session, CancellationToken token);

        // This would be used by the async daemon
        ValueTask ProjectInline(EventPage page, QuerySession session, CancellationToken token, Action<IStorageOperation> enqueue);
    }
```

## Projector

This kind of loose-y, goose-y projection would be letting you define transformations that take in a single event, and create zero to many storage operations. By depending on the `IStorageOperation` interface, the projection could do any kind of create, update, delete on as many different documents as you want. To build this, we need to scrape through the existing `ViewProjection` and support methods that let you pass in lambdas for updating documents, inserting many documents from a single event, deleting many documents by id from a single event.

We'll need to go through ViewProjection and see what's useful. 

but also have an end around "anything goes" method signatures like:

```
IStorageOperation Apply(SomeEvent @event);
IEnumerable<IStorageOperation> Apply(IEvent<SomeEvent> @event)
ValueTask<IEnumerable<IStorageOperation>> Apply(IEvent<SomeEvent> @event, IQuerySession session)
```

## Aggregate by Stream

Use a base class with a similar interface to the current ViewProjection<T>. 

## Aggregate across streams

Very similar to aggregating a stream, but you'd have to define how we know what the aggregate id is for an event. It'd be easiest
for Marten if we could do that by having a user use an abstract or interface for the events that exposes the aggregate id such that you could define the aggregate id by an `Expression` like `AggregateBy<SomeBaseEventType>(x => x.AggregateId)`. It'd be super, super useful if you could do it that way so you could pluck out the aggregate id from the JSON. That might be advantageous for projection replays

**Comment by wastaz** [comment]
> A more open, looser Projector(I think of as the @wastaz special) that let's you generate any number of low level Marten IStorageOperation from event types. More on this below.

I finally have something named after me! 😹 
Also, thanks for listening to my weird complaints <3

**Comment by oskardudycz** [comment]
@jeremydmiller I'd like to see more examples of the API for code generation. I'm still not convinced that this will be more user friendly and easier to maintain than the current explicit ViewProjections API (which maybe is not the best one but does the job).

> Aggregate by Stream
> Use a base class with a similar interface to the current ViewProjection

Any reason why would we want to have different projection APIs? In my opinion, currently, we have too many both APIs and internals doing similar stuff. I think that Stream Aggregation, Projections and Snapshoting should be more or less the same logic, as all of them are in fact projections, maybe we could inject some different strategies for them?

I'm not sure if this should be put here or into Async Daemon, but as you mentioned removing `IProjection` then I'd like to mention (as I did before) that it'd be good to have something like EventStoreDB subscriptions - so something that takes the event (or set of events) and allow a project that to do custom logic (eg. storing to other types of storage).

**Comment by jeremydmiller** [comment]
@oskardudycz I'll have something to show tomorrow.

Couple thoughts though:

* I've continuously said that we could keep the public interface of the current `ViewProjection`
* The internals of the `ViewProjection` are less than exemplary, it's very inefficient, and I don't think anybody really wants to continue supporting that
* I don't understand why you've been opposed to the code generation. My perspective is that generating C# code is way easier than dealing with the `Expression` model.
* My take is that any kind of subscription model should be an entirely different thing. I'd rather the projections be optimized for performance rather than also being a poor man's event subscription model.
* I'm wanting to eliminate all other projection abstractions except for the new `ViewProjection` (except I want that broken in two, one for aggregations and another for the loose projections)
* Most of this is around performance optimization, especially for async projections

**Comment by jeremydmiller** [comment]
# WORK IN PROGRESS

## New concepts as of Nov. 21, 2020

New clarification of goals:

* We need to retain a pluggable abstraction for simple, one-off projection types. I think this is mostly for inline projections
* Optimize the heck out of the async projections
* **Start** enabling the inclusion of other database engines or at least other database targets, but try to do this w/o adding
  unnecessary complexity or sacrificing performance

### Inline Projections

This is the current `IProjection` interface:

```
    public interface IProjection
    {
        Type[] Consumes { get; }
        AsyncOptions AsyncOptions { get; }
        void Apply(IDocumentSession session, EventPage page);
        Task ApplyAsync(IDocumentSession session, EventPage page, CancellationToken token);
        void EnsureStorageExists(ITenant tenant);
    }
```

For V4, I'd like to simplify that down for one-off kind of things to:

```
    public interface IInlineProjection
    {
        // EventStream is an existing class, but I think I'd vote to rename it to StreamFragment
        void Apply(IDocumentSession session, EventStream[] events);
        Task ApplyAsync(IDocumentSession session, EventStream[] events, CancellationToken token);
    }

```

with maybe a base class helper or two so if you want, you only need to implement either the sync or async version and delegate to the other. This implementation would still be usable in the async daemon with a wrapper around it, but it wouldn't have any of the optimizations the other types will. We'd still be able to trigger rebuilds of the inline projections.

**Comment by jeremydmiller** [comment]
## Tasking

- [ ] Relax the required "@event" parameter naming on conventional methods. Just say event is always going to be the parameter that isn't the aggregate, `IQuerySession`, or `CancellationToken`
- [ ] New codegen support for the current "self aggregating" type for usage in `AggregateStream<T>()` w/ zero configuration.

**Comment by jeremydmiller** [comment]
## Projection Types on Dec. 9th

It's a day ending in "y" in the year 2020, so it's time for Jeremy to change his mind yet again about recommendations for the projections for V4! After spending some significant time poking into `ViewProjection`, here's my latest thinking for the types of supported projections *in no particular order*:

1. Users can implement their own `IInlineProjection` classes and plug them in. This is a slimmed down interface from the current `IProjection` that should be simple enough for folks to just roll their own for simple use cases. We could still support this type
 as an async projection as well, but it's just not that optimized. There may need to be some kind of additional interface or base class to help optimize projection rebuilds or how this is used in the async daemon. More analysis necessary.
1. Today's `ViewProjection<TView, TId>`, but the internals will be all new. This will be for non-aggregating projections that produce, delete, or update a single view type. It may also support conventional methods, at least `ShouldDelete(EventType @event)`, `Create(event) : TView`. I'd strongly recommend doing some method renames on the existing `ViewProjection` method names to disambiguate what's going on instead of calling a half dozen different things `ProjectEvent()`. Maybe leave the old method names there marked as `[Obsolete]` that tells the user the new method to use. `ViewProjection` would **not** be used for aggregations
1. Self-aggregating aggregate types where the aggregate type itself has `Apply()` methods like we support today, but this would be **strictly used for live aggregations.** 
1. **New** `AggregateProjection<T>` projection type that's very heavily optimized for aggregating a single projected view across events. The main usage would be creating an aggregate per stream, but we'd also support aggregations across streams (somehow). This would be usable inline or even for live aggregations, but it's main advantage will be in optimizing the hell out of the async daemon usage as well as the aggregate rebuild processing in the daemon. We'd support a mix of conventional methods like `Apply()`, `Create()`, and `ShouldDelete()` as well as a subset of the inline lambda methods from the existing `ViewProjection` that still make sense in the aggregate usage.
