### ISSUE TITLE
Microsoft.CodeAnalysis dependency conflict for LamarCompiler+ASP.NET Core MVC5 on 4.x

### ISSUE THREAD

**Issue by kieranbenton** [JasperFx/marten#1619]
Realise this is a bit bleeding edge (as it was only released this week), but we've just rolled all of our dependencies up to 5.0 versions (.NET Core, EF Core, NpgSql) and I was surprised that Marten pins its NpgSql dependency to 4.x. Of course when running queries this results in MethodNotFoundException so its for a good reason!

Just wanted to log an issue to make sure you're aware this is a scenario that's broken right now.

**Comment by cocowalla** [comment]
Is [this](https://github.com/JasperFx/marten/pull/1600) what you are looking for 😃

**Comment by kieranbenton** [comment]
Ha, I am a moron, how did I not see that the first time I searched for it?
:-)

Thanks!

**Comment by kieranbenton** [comment]
Just tried to upgrade to that alpha version - and actually still having issues so reopening the ticket (let me know if you want me to either adjust the title or open a new separate one instead).

```error NU1107: Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.7.0 directly to project Ticketing.Apps.JobProcessing to resolve this issue.  

error NU1107:  Ticketing.Apps.JobProcessing -> Ticketing.Apps.Common -> Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 5.0.0 -> Microsoft.CodeAnalysis.Razor 5.0.0 -> Microsoft.CodeAnalysis.Common (>= 3.7.0) 

error NU1107:  Ticketing.Apps.JobProcessing -> Ticketing.Services -> Ticketing.Services.Common -> Marten 4.0.0-alpha.3 -> LamarCompiler 2.3.0 -> Microsoft.CodeAnalysis 3.6.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 3.6.0 -> Microsoft.CodeAnalysis.Common (= 3.6.0). ```

Looks like a pretty standard conflict (I think LamarCompiler is part of Marten?) - though not sure if that pinned version is intentional or not. I'm going to try adding the explicit reference and will test if there are any unforseen issues (I assume since these are analysis packages thats unlikely though).

Anything else you need let me know!

**Comment by mysticmind** [comment]
@kieranbenton Let me check and revert on the issue which you have outlined. It is not exactly related to Npgsql5 support but rather some common dependency issue when combined with ASP.NET Core MVC.

**Comment by mysticmind** [comment]
@kieranbentonv 4.0.0.0-alpha.4 is available in NuGet with updated version of LamarCompiler. Please get latest and confirm whether  the Microsoft.CodeAnalysis package resolves fine without any dependency conflict.

**Comment by mysticmind** [comment]
Fixes via https://github.com/JasperFx/marten/commit/5b76082ca8363a5df2e6c1cd6b423ebfcdd8c598

**Comment by kieranbenton** [comment]
Looking good @mysticmind thank you! 

Can I just check something? You've renamed the issue to "...when using with ASP.NET Core MVC on 4.x", what do you mean by 4.x? As far as I know I'm running all the latest .NET 5 bits now...

**Comment by mysticmind** [comment]
4.x is the current Marten version as a context. Bugs can reported on both 3.x and 4.x. I have added a tag now for tracking.

**Comment by kieranbenton** [comment]
Got it - thanks! Think we're good now.

**Comment by jannikbuschke** [comment]
Also see this message with fsharp/dotnet 6 and marten 4.3.1

Using marten 5.0.0-alpha.6 the message is not logged
