### ISSUE TITLE
Exception: Cannot access a disposed object. Object name: 'NpgsqlConnection'.

### ISSUE THREAD

**Issue by srasch** [JasperFx/marten#1622]
We are working on Marten 3.13.3.

In some cases we get the exception `Cannot access a disposed object. Object name: 'NpgsqlConnection'.`

We have found, that this is a secondary effect after another exception. If one query fails (maybe the sql could not generated correctly), the connection get closed and all following queries will die with this.

We find the following unit-test to reproduce this behavior:

```c#
[Fact]
public void connection_should_not_be_disposed()
{
    var user = new Marten.Testing.Documents.User {Age = 5, UserName = "testUser"};

    theSession.Store(user);
    theSession.SaveChanges();

    Assert.Throws<Marten.Exceptions.MartenCommandException>(() =>
    {
        var _ = theSession.Query<User>()
            .Where(x => x.Age.ToString() == "5") 
            .ToList();
    });

    var users = theSession.Query<User>().ToList();

    users.ShouldSatisfyAllConditions(
        () => users.ShouldNotBeNull(),
        () => users.Count.ShouldBe(1)
    );
}
```

This test is failing in my local cloned solution. Any hints?

Regargs,
Steve

**Comment by mysticmind** [comment]
Lot of improvements done in v4+ on dispose portion. Please check the latest version of Marten, closing this one.

**Comment by egorpavlikhin** [comment]
This is still an issue as of `5.3.0` - connection is disposed after an exception and even though `IDocumentStore` is scoped it is no longer usable violating the lifetime assumption from the DI container.

**Comment by mysticmind** [comment]
@egorpavlikhin Appreciate if you could provide a repro as a separate PR for us to take a look.

**Comment by egorpavlikhin** [comment]
The original test would still fail. Here is the offending line https://github.com/JasperFx/marten/blob/master/src/Marten/Internal/Sessions/QuerySession.Connection.cs#L24
All NpgsqlCommand exceptions are treated as unrecoverable even though some of them just report duplicate keys, for example.
The workaround seems to be to replace the default retry policy with your own and swallow the exceptions.
