### ISSUE TITLE
CompiledQuery: Error when using Any

### ISSUE THREAD

**Issue by srasch** [JasperFx/marten#1623]
Hi again,

the following test with fail an InvalidOperationException: "Sequence contains no elements", which makes no sense, because Any should always return one row - or instead transform empty sequence to false.

```c#
public class TestQuery: ICompiledQuery<User, bool>
{
    public Expression<Func<IQueryable<User>, bool>> QueryIs()
    {
        return query => query.Any(x => x.Age == Age);
    }

    public int Age { get; set; }
}
```

```c#
[Fact]
public async Task query_returning_should_return_empty_list()
{
    var user = new User {Age = 5, UserName = "testUser"};

    theSession.Store(user);
    await theSession.SaveChangesAsync();

    // this should pass => Any works.
    user.ShouldSatisfyAllConditions(
        () => theSession.Query<User>().Any(x => x.Age == 6).ShouldBeFalse(),
        () => theSession.Query<User>().Any(x => x.Age == 5).ShouldBeTrue()
    );

    // this should pass => AnyAsync works, too
    var asyncR1 = await theSession.Query<User>().AnyAsync(x => x.Age == 6);
    asyncR1.ShouldBeFalse();
    var asyncR2 = await theSession.Query<User>().AnyAsync(x => x.Age == 5);
    asyncR2.ShouldBeTrue();

    var q = new TestQuery() {Age = 6};
    var queryAsync = theSession.Query(q);  // theSession.QueryAsync(q, default) will fail also!
    queryAsync.ShouldBeFalse();
}
```

If you change the CompiledQuery return to `int` and use `Count()` it's working as expected...

**Comment by jeremydmiller** [comment]
@srasch This is fixed in the V4 codebase if you'd like to try the latest v4 alpha nuget. Otherwise, I pulled in your test just to verify that again (there was a duplicate issue to this before).

**Comment by srasch** [comment]
Thanks @jeremydmiller for your support 
Unfortunately we are on 3.13. Any chances to pull that down?

**Comment by jeremydmiller** [comment]
Yeah, unfortunately the compiled query feature was completely re-written to deal with this kind of systematic shortcomings of the compiled query usage, so the fix won't be applicable to v3. 

FWIW, upgrading from 3.* to the v4 alpha is pretty easy 'cause the breaking changes aren't in commonly used things (yet).
