### ISSUE TITLE
Execute custom sql during Session.SaveChanges

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#1663]
I want to propose a simple extension method to execute custom sql commands during savechanges.

Create ISqlOperation interface with one method Execute (NpgSqlConnection connection)
Extend session with two collections:
SqlOperationsAfterStartTransaction
SqlOperationsBeforeCommitTransaction

After start transaction can be used for Set Local #1352  or storing large objects (see #156 And the can save the oid inside a document that's stored in the same transaction

Thanks

**Comment by jeremydmiller** [comment]
@mdissel Use the existing `IStorageOperation` concept in the V4 branch to do that, and there's an exposed `QueueOperation(IStorageOperation)` method on `IDocumentSession` now. Just need to come up with some way to make this user friendly w/o having to know a lot about Marten internals.

**Comment by mdissel** [comment]
In my use case I want to execute insert/update/delete sql scripts during the same SaveChanges..() transaction. Currently I don't see how this is possible with the IStorageOperation.

**Comment by jeremydmiller** [comment]
@mdissel `IStorageOperation` builds the SQL for the command batching that's executed during `SaveChanges()`. So that's the natural extension point you're looking for here.

**Comment by mdissel** [comment]
I think a small sample would help :confused:

I don't see a connection object and/or transaction object in that interface..

**Comment by mdissel** [comment]
Thanks! 
Any tips how to implement the large object manager as part of the same transaction ? see #156

**Comment by jeremydmiller** [comment]
As for building the SQL, just look at the `CommandBuilder` class. That's just a little helper to append SQL and parameters to a batched NpgsqlCommand. The large object storage is a totally different animal because you can't do that in the same command as I recall. Someone did a Marten extension for large objects on GitHub in the very, very early days.
