### ISSUE TITLE
Improved transaction and concurrency prevention for appending events

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1665]
First off, it's not being honored in V4. Secondly, let's also have an explicit command to load the stream that way?

**Comment by ericgreenmix** [comment]
This is the PR where the discussion happened on this. https://github.com/JasperFx/marten/pull/1279

I have been so busy that I haven't been able to pay attention to the V4 work being done, as much as I would like to. However, if these circumstances still exist in the `mt_append_event` function in V4, I think this should be the default behavior when appending events, instead of being baked in as a setting like we did in V3. This is a serious bug for anyone on a distributed environment otherwise

**Comment by jeremydmiller** [comment]
@ericgreenmix `mt_append_event` was eliminated in V4, and Marten does do *some* level of optimistic update on appending event versions against the stream now, but it's not creating locks on the stream record at the time you start appending events. That I think needs to be an explicit operation.

**Comment by jeremydmiller** [comment]
@ericgreenmix Oh, but V4's built in optimistic updates is good enough to prevent the inconsistent version updates in concurrent situations. It issues an UPDATE against the streams table with the starting version number now, and rolls back the transaction if the stream version has incremented in between.

**Comment by ericgreenmix** [comment]
@jeremydmiller Fantastic. If that is the case, then I don't see a need for the "feature" to be put into V4

**Comment by jeremydmiller** [comment]
@ericgreenmix I still think it's worth doing to do it by locking instead of the optimistic check, but I'll probably recommend this slide into 4.1.

**Comment by ericgreenmix** [comment]
@jeremydmiller Thinking about this more. If I understand this correctly, I do think we will need the locking. 

With the optimistic check, that would prevent the inconsistent version updates, but would also lead to optimistic concurrency exceptions being thrown if that stream version had been incremented? So in a high load concurrent environment with multiple operations potentially happening on the same stream at the same time, we could see these failures/rollbacks from the optimistic updates without locking?

**Comment by jeremydmiller** [comment]
Here's my take on tasks for right now:

- [ ] Eliminate `EventGraph.UseAppendEventForUpdateLock` because this shouldn't be a global thing IMO
- [ ] New `IEventStore.AppendOptimistic(id/key, events)` that enforces that the event stream already exists at the point you call it, and uses the known version at that point as an optimistic check when it tries to append. 
- [ ] New `IEventStore.AppendExclusive(id/key, events)` that acts similar to `AppendOptimistic()`, but does a `SELECT FOR UPDATE` row lock on the stream row at the point `AppendExclusive()` is called
