### ISSUE TITLE
Use GinIndexed Attribute on a class is ignored

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#1669]
When I add for example the Marten.Schema.GinIndexed to a base class, this is not picked up for the subclasses.
The ForAttribute(..) from the BaseLine assembly is not picking up inherited attributes.

Is this a choice with a reason or something that can be changed?

https://github.com/JasperFx/marten/blob/b8cf42990464c43b85a60a63702fd8743cc239a7/src/Marten/Schema/DocumentMapping.cs#L69

Thanks

**Comment by jeremydmiller** [comment]
@mdissel That's a one line code change, so I'm a gonna say "I take pull requests":)

**Comment by mdissel** [comment]
After adding a test it I found out that the GinIndexedAttribute was not working at all due to the wrong implementation of an overload

**Comment by jeremydmiller** [comment]
This was addressed by https://github.com/JasperFx/marten/commit/36db4fe52749a7297ddf263471e7dc98735dc95c
