### ISSUE TITLE
Nullable<>.HasValue not supported (fully) in Linq

### ISSUE THREAD

**Issue by trullock** [JasperFx/marten#167]
this works
```
.Where(s => s.NullableDateTime == null || s.NullableDateTime > DateTime.UtcNow)
```
but this doesnt

```
.Where(s => !s.NullableDateTime .HasValue || s.NullableDateTime .Value > DateTime.UtcNow)
```

**Comment by nieve** [comment]
If no one is picking this up, I'm on it. I pretty much know what it is.

**Comment by jeremydmiller** [comment]
@trullock @nieve We have support for HasValue and !HasValue checks. Are you sure that's what's causing the issue, or is it possibly the date time type issue again?

See https://github.com/JasperFx/marten/blob/master/src/Marten.Testing/Linq/query_with_nullable_types_Tests.cs for an example of what the Linq provider *should* be able to do right now.

**Comment by trullock** [comment]
This is possibly related to the datetime issue. Ill open an issue for that

**Comment by jeremydmiller** [comment]
@trullock 

Didn't you already open one for that? It could be this code (w/ my comment):

```
        private static readonly Dictionary<Type, string> PgTypes = new Dictionary<Type, string>
        {
            {typeof (int), "integer"},
            {typeof (long), "bigint"},
            {typeof (Guid), "uuid"},
            {typeof (string), "varchar"},
            {typeof (Boolean), "boolean"},
            {typeof (double), "double precision"},
            {typeof (decimal), "decimal"},
            {typeof (DateTime), "date"}, // We need to change this to timestamp, right?
            {typeof(float), "decimal" },
            {typeof (DateTimeOffset), "timestamp with time zone"}
        };
```

**Comment by nieve** [comment]
From memory, a very quick debugging session done yesterday showed me it was this line causing the bug: https://github.com/JasperFx/marten/blob/master/src/Marten/Linq/MartenExpressionParser.cs#L109
the locator is basically a cast of the nullable datetime column into a datetime value and having the ::Boolean afterwards, as far as I could tell, messes things up.

But again, that was a very quick debug session. Will be able to look into it tomorrow, if no one else beats me to it.

**Comment by nieve** [comment]
FYI, apparently this doesn't work:
`.Where(s => !s.NullableDateTime.HasValue)`

So I think it's a different issue.

**Comment by jeremydmiller** [comment]
@nieve Fixed this in https://github.com/JasperFx/marten/pull/176/files.
