### ISSUE TITLE
New Linq selector to apply a live aggregation against any IQueryable<IEvent>

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1680]
The `AggregateStream()` methods would delegate to this new mechansim.

Something like:

```
session.Events.QueryAllRawEventData().Where(x => x.StreamId == something).AggregateTo<AggregateClass>();
```

**Comment by jeremydmiller** [comment]
@jedidja,

So these two methods:

```
        /// <summary>
        /// Query directly against ONLY the raw event data. Use IQuerySession.Query() for aggregated documents!
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <returns></returns>
        IMartenQueryable<T> QueryRawEventDataOnly<T>();

        /// <summary>
        /// Query directly against the raw event data across all event types
        /// </summary>
        /// <returns></returns>
        IMartenQueryable<IEvent> QueryAllRawEvents();
```

I think you'd only care about `IMartenQueryable<IEvent> QueryAllRawEvents();`. As a starting point, I'd look at the code behind `AggregateStreamAsync()` as a start for how to apply the aggregated projection. The immediate problem that I think is the only sticky point of this is that the aggregation today assumes that there's an identity value that has to be assigned to the aggregate model. That might need to be relaxed here. 

I'm thinking that the extension method effectively calls `IMartenQueryable<IEvent>.ToListAsync()`, then runs the events through the aggregated projection much like the `AggregateStreamAsync()` does today.

**Comment by jedidja** [comment]
PR #1793 is ready for review when you get a chance @jeremydmiller :)

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/pull/1793.

Thanks @jedidja!
