### ISSUE TITLE
Load aggregate from starting revision

### ISSUE THREAD

**Issue by adnang** [JasperFx/marten#1684]
Is there an `AggregateStreamAsync` behaviour that reads events from a specific version, and applies to an instance of an aggregate?
Our use case is snapshotting the aggregate is a json blob along with the version, so it can be read and only have the latest events applied to it, e.g.
```
var current = await session.LoadAsync<MyAggregate>(streamId);
var latest = await session.Events.AggregateStreamAsync(streamId, from: current.version, state: current);
```

**Comment by mysticmind** [comment]
@adnang currently, there is no readily available API for snapshotting from a specific version. You can use the below code to achieve the same result:

```csharp
// get events on the stream with version greater than current version
var events = await session.Events.QueryAllRawEvents().Where(x => x.StreamId == streamId && x.Version > current.Version)
    .OrderBy(x => x.Sequence).ToListAsync();

// create an aggregator which calls the `Apply` method on aggregate, I have used `AggregatorApplyPublicAndPrivate`. 
// You can choose to use `AggregatorApplyPrivate` if you have only private `Apply` methods
// or `Aggregator` if you are using only public `Apply` `methods
var aggregator = new AggregatorApplyPublicAndPrivate<MyAggegate>();

foreach (var @event in events)
{
    // Please be aware that this method may get deprecated in Marten v4 at some point.
   // apply the event on the aggregate
    @event.Apply<MyAggregate>(current, new AggregatorApplyPublicAndPrivate<MyAggregate>());
}
```

In v4, we are working towards making event store more robust especially with regards to projections/async daemon, we are yet to look at the use cases pertaining to snapshot projections. You can check https://github.com/JasperFx/marten/issues/1608 for details.

**Comment by adnang** [comment]
Thanks @mysticmind, might be worth adding this to the current documentation (unless it's there and I've missed it). Will close this

**Comment by mysticmind** [comment]
@adnang sure, we will add this to the docs 👍
