### ISSUE TITLE
Map  SQL (view) to DTO objects using Session.Query<>

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#1702]
Does Marten support querying and mapping to a DTO using the Session.Query<>().Where(...)?

(so we don't need Dapper or other alternatives anymore)

For example:
- make a sql view
- make a simple DTO class 
`public class DTO { public bool InActive {get;set;} public string Name {get;set;}}`
- start the query
`var result = session.Query<DTO>().Where(x => x.InActive = false).OrderBy(x => x.Name).Skip(20).Take(20);`
resulting in the query:
`Select InActive, Name from DTO order by Name limit 20 offset 20`

Thanks
Marco

**Comment by jeremydmiller** [comment]
@mdissel Marten has supported the Linq `Select` statement for quite awhile, and that'll do at least what you're showing above: https://martendb.io/documentation/documents/querying/projections/

**Comment by mdissel** [comment]
Projections seems to be only possible with "registered persistent objects". I want to fetch a 'normal' sql result  and convert it into a DTO class with hopefully some linq support (to eliminate dapper or other alternatives)

`var result = session.Query<DTO>().Where(x => x.Id >0)`

I expected this sql:
select * from DTO where Id > 0

Marten.Exceptions.MartenCommandException : Marten Command Failure:$
select d.data from public.mt_doc_dto as d where d.id > :p0$
$
42P01: relation "public.mt_doc_dto" does not exist

**Comment by jeremydmiller** [comment]
That's never going to work because Marten uses the type name to know what table to go to. Any reason why you can't just use `Query<DocType>().Select<DTO>(x => {})`?

**Comment by mdissel** [comment]
In this case the data is stored "relational" and not in a single jsonb column. But the same situation could also apply when you create functions that return multiple columns instead of one json column.

**Comment by jeremydmiller** [comment]
That sounds a lot like Dapper to me.

**Comment by jeremydmiller** [comment]
I'm closing this because I don't believe there's anything to do, and this isn't a feature I want to see Marten support.

**Comment by rosdi** [comment]
@mdissel How do you solve this? We have 'master data' tables that are easier to manage with relational tables instead of document. I am just querying these tables (no insert/update).
