### ISSUE TITLE
Build resiliency into the new async daemon

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1708]
Retry semantics on IO failures, circuit breaker on multiple failures. Will need to reset a ProjectionAgent if it hits a sequence out of order error.

**Comment by oskardudycz** [comment]
Currently AsyncDaemon, when `Stop` option is selected then whole page is being skipped. It might be worth adding possibility to just skip the failing event(s).

I'm not sure if that's for V4 but at some point we should consider handling poison events queue/storage to give user better option for diagnosing or understanding what went wrong - plus not being blocked by failing events.
