### ISSUE TITLE
Linq provider builds only string values for queries with anonymous types

### ISSUE THREAD

**Issue by lhaussknecht** [JasperFx/marten#1710]
In v4, when querying for anonymous types, the resulting postgres query contains only string values, regardless of the destination's type (in my case an int). 

See `->>` operator.

```sql
select jsonb_build_object(
'Id', d.id, 'State', d.state, 
'NumberOfDelivered', d.data ->> 'NumberOfDelivered',
'NumberOfLoaded', d.data ->> 'NumberOfLoaded')
 as data from public.mt_doc_tour as d
```

It looks like JSON.Net is handling such json strings just fine. I'm using JIL and JIL is expecting a digit not an " while deserializing.

**Comment by lhaussknecht** [comment]
Btw. this is a v4 issue.

**Comment by jeremydmiller** [comment]
As I said on the Gitter page, this was purposely introduced in V4 as an optimization to avoid doing unnecessary `CAST` in the `jsonb_build_object` function when doing a `Select()` transform. With the downside being that it apparently breaks Jil.

I think our options are something like:

1. Do the cast like v3 did no matter what and incur the extra perf cost when using JSON.Net
2. Don't support Jil anymore
3. Have Marten use a different mode of the `SelectTransformBuilder` that can vary behavior based on the underlying serializer behavior
