### ISSUE TITLE
AsyncDaemon ProjectionTrack does not stop processing pages immediately when in a stopped state (IsRunning=false)

### ISSUE THREAD

**Issue by tristal** [JasperFx/marten#1711]
From a gitter discussion between @oskardudycz, @jeremydmiller, and myself. It can be seen that a `ProjectionTrack` (and associated fetcher) do not stop attempting to process any pages of events that are already preloaded in a tracks cache.

A repro can be found [here](https://gist.github.com/tristal/8f8993298cfbb64c2c913b40f901396c).

The exception is forcefully thrown when processing page 2 (page size 10), which is event 16. I'd expect that based on the ExceptionHandling configuration (`Stop` or `StopAll`) that processing should stop after the exception thrown on event 16 (page 2), and not continue through to page 3, 4, ... (whatever is in that cache at the time the exception is thrown), and rather that no more pages are attempted to be processed.

A proposed fix for the `ProjectionTrack` code may start with adding verification for `!this.IsRunning` to [this](https://github.com/JasperFx/marten/blob/3.13.3/src/Marten/Events/Projections/Async/ProjectionTrack.cs#L201) line.

**Comment by jeremydmiller** [comment]
@tristal This is all completely rewritten in V4, and there it uses a CancellationToken to coordinate the shutdown. Then too, it's more of a "pull" model than the "push" model it was < V4.

**Comment by jeremydmiller** [comment]
Yeah, we're just never going to get around to this one. Not that it wasn't a real problem or not a good suggestion.
