### ISSUE TITLE
Support Structured Logging in the V4 Async Daemon

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1716]
I think this is a great idea, and I'm trying to nominate @Hawxy for this one:)

Just gotta make sure that the `ILogger` usage is still okay for folks that aren't gonna sure Seq or the like.

**Comment by Hawxy** [comment]
I'll pick this up once #1721 is merged.

> Just gotta make sure that the ILogger usage is still okay for folks that aren't gonna sure Seq or the like.

All of the Microsoft output sinks, as well as Serilog and NLog know how to handle structured logs out of the box. It's completely transparent to the consumer unless you're taking advantage of structure-related features.
