### ISSUE TITLE
Poison Message detection for the async projections

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1731]
Breaking out of #1708. Go beyond simple error detection. If we can detect that a certain event is failing repeatedly, skip that event in the async daemon.

**Comment by jeremydmiller** [comment]
@oskardudycz @babuannamalai I did some preliminary work on this today while not paying attention in hours upon hours of Zoom meetings. I've got it to the point where we can detect that a specific event could not be applied, but not because of any kind of postgresql/marten error that could be considered to be ephemeral. Fine, that's easy enough.

Next is what do we do about it? I want to say that we log everything regardless, so true production monitoring could be done w/ tools like Splunk w/o doing anything from the Marten side. Then we allow users to say either:

1. Stop the line, don't do anything else with this particular projection until the app is explicitly re-started. 
2. Skip this event. In this case we'd effectively restart the projection at its last known "good" point, but this time we'd have it ignore the bad event and continue processing.

My question to y'all is do we do anything more or better than 1. or 2.? It's easy to make that user configurable, but it's pretty heavyweight. The performance would go all to hell if the poison event failures were common, but maybe that's just a matter of making the projections more testable?

**Comment by oskardudycz** [comment]
@jeremydmiller I think that we should include some retry policy (e.g. how many time an event will be retried before dropping it - e.g. Kafka has such a setting). It would be good to have a "Dead/Poison Letter Queue" - so store such event in some separate table or keep the reference to the poison messages (e.g. sequence ids). It'd be good also to give users an option if projection should be stopped or continued for such a case.
From my experience, people usually are dropping such events to DLQ and define notifications around that. Then they typically ignore those notifications... ;) 
I'm okay with both 1 or 2 in the first version. We can take what's more straightforward, gather the feedback and, based on that, extend it in the next version (if needed).

**Comment by jeremydmiller** [comment]
@oskardudycz I'm pretty close on this one, but it's taken a lot of refactoring and reconsidering the async daemon internals to get here first. I think everything you suggested is pretty easy to do. Look for this *maybe* by Monday.

**Comment by seanswalling** [comment]
I like the idea of a poison queue that users can optionally configure.  Previously I've seen a custom ES system round robin between processing queued messages, a poison queue and out-boxing.  The poison queue also contained a flag to notify to the process if the queue needed to be processed or ignored.  This solution was obvious tailored to the needs of the devs at the time, but hopefully gives some ideas.
