### ISSUE TITLE
Marten v4 memory consumption problem

### ISSUE THREAD

**Issue by KasperDamgaard** [JasperFx/marten#1735]
This issue is also mentioned and discussed on the Gitter chat.

I noticed that Marten's v4.0.0-alpha.4 consumes large amounts of memory compared to v.3.13.3 - about 4 times the amount for the exact same operation. 
Our initial investigation leads to the suspect being the Lamar code compiler and the whole operation around using Roslyn on runtime. 

I could unfortunately not get deeper into the memory issue, but replication is easily done by just using any Linq expression and comparing memory consumption immediately after. A memory profiler such as dotMemory will also reveal this. 
The problematic issue is that memory consumption stays high after evaluation of the linq expression, leading us to think there might be a leak somewhere. 

The problem seems to increase when the expressions get bigger, as it seems the memory consumption is also 4x larger in our larger application after upgrading to Marten alpha4.

A sample program illustrating the problem can be found here: https://dotnetfiddle.net/uF1LV0 - running this locally with .NET5 and comparing Marten v.3.13.3 and alpha4 leads to approximately 50Mb and 200MB respectively.

**Comment by jeremydmiller** [comment]
So the latest, greatest Marten v4 uses 120 MB on @KasperDamgaard 's code sample. Still looks like the Roslyn compilation is to blame, but there's just nothing I can see yet to force the memory to release.

**Comment by jeremydmiller** [comment]
## Pre-generate ahead of time tasking

- [ ] Mechanism on StoreOptions to discover compiled query types
- [ ] Implement `IGeneratesCode` on `DocumentPersistenceBuilder`
- [ ] Implement `IGeneratesCode` on `StorageFeatures`, delegates to `DocumentPersistenceBuilder.AttachPreBuiltTypes()` and `DocumentPersistenceBuilder.AssemblyTypes()`. Also delegates to each compiled query
- [ ] Implement `IGeneratesCode` on `EventGraph`
- [ ] Add `IGeneratesCode` registrations in `AddMarten()` call
- [ ] Test with LamarCodeGeneration.Commands
- [ ] Document.

**Comment by jokokko** [comment]
Hmm, looking at the numbers without GC or forcibly inducing such (full GC, all gens, finalizers have run) seems a bit unfair.

I took a quick look by executing the sample code -> induce full GC -> memdump:

_WinDbg_:
```
Number of GC Heaps: 1
generation 0 starts at 0x0000023A40F79C08
generation 1 starts at 0x0000023A40ED0B08
generation 2 starts at 0x0000023A40BD1000
ephemeral segment allocation context: none
         segment             begin         allocated              size
0000023A40BD0000  0000023A40BD1000  0000023A40F8BC50  0x3bac50(3910736)
Large object heap starts at 0x0000023A50BD1000
         segment             begin         allocated              size
0000023A50BD0000  0000023A50BD1000  0000023A5109E138  0x4cd138(5034296)
Total Size:              Size: 0x887d88 (8945032) bytes.
------------------------------
GC Heap Size:    Size: 0x887d88 (8945032) bytes.
```
```
--- Usage Summary ---------------- RgnCount ----------- Total Size -------- %ofBusy %ofTotal
Free                                    304     7dfe`cae02000 ( 125.995 TB)           98.43%
<unknown>                               791      201`27fb9000 (   2.005 TB)  99.99%    1.57%
Image                                   890        0`07040000 ( 112.250 MB)   0.01%    0.00%
Heap                                     81        0`04018000 (  64.094 MB)   0.00%    0.00%
Stack                                    69        0`02000000 (  32.000 MB)   0.00%    0.00%
Other                                     9        0`001ae000 (   1.680 MB)   0.00%    0.00%
TEB                                      23        0`0002e000 ( 184.000 kB)   0.00%    0.00%
PEB                                       1        0`00001000 (   4.000 kB)   0.00%    0.00%
```

_DotMemory_

![image](https://user-images.githubusercontent.com/1404295/120281789-0e0b5600-c2c2-11eb-8328-1f43f030040e.png)

From my perspective, I am not worried at all.

**Comment by jeremydmiller** [comment]
I think I'm voting to close this, and come back with https://github.com/JasperFx/marten/issues/1839 for 4.1 after @jokokko's comments. I did attempt to do some work to LamarCompiler to make it clean up memory usage it leaves behind, and I think that will help unmanaged memory usage at least.
