### ISSUE TITLE
Calling ```UseDefaultSerialization``` before ```UseNodaTime``` break nodatime serialization.

### ISSUE THREAD

**Issue by RKopczynski** [JasperFx/marten#1737]
Hi,
I have found issue when using ```Marten.NodaTime``` while at the same time calling ```UseDefaultSerialization``` for parsing enum as string.

## Steps to reproduce
Create configuration and call ```UseNodaTime``` before ```UseDefaultSerialization```.
```
public class MartenConfiguration : StoreOptions
{
    private MartenConfiguration(string connectionString)
    {
        this.UseNodaTime();
        this.UseDefaultSerialization(enumStorage: EnumStorage.AsString);
    }
}
```

## Effect
Parsing LocalDate (or any kind of NodaTime object) fails.

## Problem
I have found in repo, that ```UseDefaultSerialization``` creates new serializator, so effect of calling ```UseNodaTime``` before makes configuration invalid.

## Solution

I see two solutions.
1. A the very least - write it in documentation of ```Marten.NodaTime```, that calling ```UseNodaTime``` should come before creating new serializator.
2. Make change to ```UseDefaultSerialization``` so it doesn't create new serializator, but update existing one like it's done in  ```UseNodaTime``` extension method.

**Comment by mysticmind** [comment]
Adding docs is a low hanging fruit, will add it.
