### ISSUE TITLE
`DateTime`s incorrectly mapped to `date`

### ISSUE THREAD

**Issue by trullock** [JasperFx/marten#175]
`Marten.Util.TypeMappings` is treating `DateTime`s as `date`s,

see line ~21 and and ~62

Suggest these are changed to `timestamp`s

**Comment by trullock** [comment]
@jeremydmiller said:
```
private static readonly Dictionary<Type, string> PgTypes = new Dictionary<Type, string>
        {
            {typeof (int), "integer"},
            {typeof (long), "bigint"},
            {typeof (Guid), "uuid"},
            {typeof (string), "varchar"},
            {typeof (Boolean), "boolean"},
            {typeof (double), "double precision"},
            {typeof (decimal), "decimal"},
            {typeof (DateTime), "date"}, // We need to change this to timestamp, right?
            {typeof(float), "decimal" },
            {typeof (DateTimeOffset), "timestamp with time zone"}
        };
```

**Comment by trullock** [comment]
> {typeof (DateTime), "date"}, // We need to change this to timestamp, right?

I think so, and what about the other line: 

```DateTime => NpgSqlType.Date?```

**Comment by jeremydmiller** [comment]
@trullock Probably the same. Npgsql itself has this exact functionality, but it's buried behind private/internal scoping. Might be worthwhile either getting them to take a PR for that or just cheating and grabbing things through reflection (shudder).

**Comment by jeremydmiller** [comment]
This was addressed in https://github.com/JasperFx/marten/pull/177
