### ISSUE TITLE
Add AddMarten overload with access to a service provider instance

### ISSUE THREAD

**Issue by ushenkodmitry** [JasperFx/marten#1775]
Hello,
It would be useful to have an access to a service provider instance in AddMarten method. So I could resolve components/options to build StoreOptions instance in runtime.
Let's say AddMarten method overload with signature:
`public static MartenConfigurationExpression AddMarten(this IServiceCollection services, Action<IServiceProvider, StoreOptions> configure);`

**Comment by jeremydmiller** [comment]
@ushenkodmitry,

I assume you mean `Func<IServiceProvider, StoreOptions>`? To what end though? Why do you want that?

**Comment by ushenkodmitry** [comment]
No matter what signature it will have. In my snippet i thought of a lambda that takes both as input parameters. 
Generally speaking i need access to both the service provider instance and the storeoptions instance in one place. To be able to configure options correctly. 
In my particular case one of my martenregistry implementation need to access some options, configured via container.
