### ISSUE TITLE
LoadMany/LoadManyAsync for events

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#1783]
I have one or two use cases where I want to load many events of the same type by event id. IDocumentSession has an `session.Events.LoadAsync<MyEventType>(eventId);` but there is not corresponding `LoadMany` versions. 

Right now Im working around this by using `QueryAllRawEvents` but for consistencys sake it would be nice to have a corresponding LoadMany to the Load on the events as well.

**Comment by jeremydmiller** [comment]
@wastaz I'd actually say that's too rarely used to add to the public API. If you want that though, I'd happily take a PR. Could do it cheaply and just delegate to Linq with the `IsOneOf()` Linq operation. Could even be an extension method.

**Comment by jeremydmiller** [comment]
Cleaning things up today, gonna say you just use IsOneOf here.
