### ISSUE TITLE
Allow users to supply custom IEventSlicer for custom aggregation strategies

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1784]
Some users will need to bounce through the database to make the "explosion" of events from a parent event.

See this conversation from Gitter:

Dariusz Firek @DariuszFirek 03:34
Hi, I've started transition to v4 in our production project. As for now almost everything is working. I just miss one feature we had in the past and used extensively. I saw similar discussion recently here.
ViewProjection<TDoc, TId> used to have an option to apply one event to multiple documents via ProjectEvent(Func<IDocumentSession, TEvent, IList<Guid>> idSelector, (...)) or something similar. Now it's missing, and all I have is Identity<TEvent>(Func<TEvent, TId> identityFunc) which only allows to select one Id to be updated.
Our use is similar to: https://0bin.net/paste/pEbbcvtw#m6caJOCjZbQf+-UT+5iSzF3xtDe5rY8KIkmbEmYYhc/ (sorry for raw form)
How can I replicate that behaviour in v4? I wouldn't like to migrate any data since it's already on production and spans trough gigabytes of data... Just by looking at the code and JasperFx/marten#1610 (and linked issues), I see some options (I don't know if they are valid):
override Task ApplyAsync(IDocumentSession session, EventPage page, CancellationToken token); and other methods from base class and provide own implementations (I see this as dangerous)
Maybe something like FanOut to <Touple<Guid, TEvent>>, where Guid would be modelId but what to do later?
Ditch ViewProjection as base class and go with EventProjection, like Oskar did here: https://github.com/oskardudycz/EventSourcing.NetCore/pull/38/files#diff-5246f5500eeddbee0e524da196022d2e669c5961f26f464565812515d9bbd504 but this still requires some more work to have something that was already provided by marten in the past.
Create my own IProjection implementation with all the features I need
Btw old/red code in Oskar's repository is very similar to the one we have already working.

Jeremy D. Miller @jeremydmiller 06:08
@DariuszFirek:

Jeremy D. Miller @jeremydmiller 06:14
This would fail spectacularly, so let’s just not do that:)
FanOut() effectively makes a collection of objects within a single event look like events to the ViewProjection. FanOut() here would work if it had an option to pass in an IQuerySession to do your query. What it would effectively do is “explode” the incoming event into a new virtual event for each manufacturer. After that, the ViewProjection mechanics are unchanged and you’d get all the optimizations built into the V4 aggregations
If you need this done fast, I’d say this is your best option
Same as 3., but you’d potentially lose some of the optimizations we’ve built into the built in projections if you’re running these in the async daemon
The good news is that doing the improved FanOut() wouldn’t take very long.

**Comment by jeremydmiller** [comment]
Then the next problem is how do you cache that data instead of repeatedly pounding the database? We could just say to users that they're responsible for caching within the projection class.

**Comment by oskardudycz** [comment]
@jeremydmiller does not need to accept the IQuerySession - the good enough solution would be to have the selector that returns the collection of ids. I'll send today a sample of how this can be done in v3.

**Comment by jeremydmiller** [comment]
@oskardudycz Read his sample a little closer, it would take IQuerySession. And I still need to see your use case to understand why the selector that returns a collection of ids would be necessary:)

**Comment by oskardudycz** [comment]
@jeremydmiller, you're right. We'll need both.

See my samples: https://github.com/JasperFx/marten/pull/1785.

**Comment by jeremydmiller** [comment]
Per a conversation on Gitter today w/ @oskardudycz & @jeremydmiller:

```
Oskar Dudycz @oskardudycz 10:00
I added samples JasperFx/marten#1785
If they're not clear, I could try to explain. I tried to prepare real-world case.
For sure they're not great candidates for inline projections, but for async projections, if those actions touching multiple streams are rare, then it'd be good to support that.
Or at least place recommendation how it can be done differently

Jeremy D. Miller @jeremydmiller 10:02
So what is the goal of this line:
 ProjectEvent<LicenseFeatureToggled>(FindUserIdsWithLicense, Apply);
Is that to apply the LicenseFeatureToggled event to multiple UserFeatureToggles aggregate documents?

Oskar Dudycz @oskardudycz 10:04
Yes, to build the read model of all the user available feature toggles
based on the toggles assigned to license that user has

Jeremy D. Miller @jeremydmiller 10:06
So it’s basically what he was trying to do too. Hmm.

Oskar Dudycz @oskardudycz 10:06
yup
The other example shows similar case, but a bit simpler
when you also want to update multiple documents

Jeremy D. Miller @jeremydmiller 10:07
Yeah, the V4 model doesn’t fit that yet.

Oskar Dudycz @oskardudycz 10:07
but you have the "correlation id"
It's a similar stuff as @jedidja was asking

Jeremy D. Miller @jeremydmiller 10:07
It doesn’t matter that much if you’re doing inline projections, but we need to find some way to make this efficient inside the async daemon to avoid an N+1 query.

Oskar Dudycz @oskardudycz 10:07
so updating the order amount based on the changing tax
@jeremydmiller yes, I understand

Jeremy D. Miller @jeremydmiller 10:08
That might have to be solved by some kind of user-supplied fetch ahead strategy.

Oskar Dudycz @oskardudycz 10:09
Yup, that's probably the possible scenario. This stuff can go even worse, because while handling the e.g. group assignment event

Jeremy D. Miller @jeremydmiller 10:09
Expanding the FanOut would work, but it’s clumsier than what you’re showing usability wise.

Oskar Dudycz @oskardudycz 10:09
someone would like to load the group document to get also name (that's not in the event)

Jeremy D. Miller @jeremydmiller 10:09
Yeah.

Oskar Dudycz @oskardudycz 10:09
I hope that at least the sample helped you to understand that scenario
I also used similar stuff in my project (the real one, not the sample one)

Jeremy D. Miller @jeremydmiller 10:10
Allowing for plugging in a custom event slicer is what I’m leaning toward offhand

Oskar Dudycz @oskardudycz 10:10
It helps to have flattened cache.

Jeremy D. Miller @jeremydmiller 10:10
And to what you just said, let them also opt into using a backing identity map to further reduce network hops
I think there’s a post 4.0 feature for a 2nd level cache in the async daemon aggregation anyway

Oskar Dudycz @oskardudycz 10:11
I think that we don't need to provide the end solution, but it would be good to at least give something that will work
or some sample showing how to handle that in other way
if it's too much work before v4 release

Jeremy D. Miller @jeremydmiller 10:13
Pluggable IEventSlicer is the most flexible way that still potentially gives you good performance in the async model
I think even for inline projections, I’d opt for that as well.

Oskar Dudycz @oskardudycz 10:14
How would the end-user API look like (approximately)?

Jeremy D. Miller @jeremydmiller 10:14
As of right now, slicer looks like this:
     public interface IEventSlicer<TDoc, TId>
    {
        IReadOnlyList<EventSlice<TDoc, TId>> Slice(IEnumerable<StreamAction> streams, ITenancy tenancy);
        IReadOnlyList<TenantSliceGroup<TDoc, TId>> Slice(IReadOnlyList<IEvent> events, ITenancy tenancy);
    }
So implement that, and we can do some base classes to make it easier. And maybe add an argument for IQuerySession?

Oskar Dudycz @oskardudycz 10:16
So they would need to load docs on their own and return EventSlice, right?

Jeremy D. Miller @jeremydmiller 10:16
On ViewProjection & AggregateProjection, just something like GroupEventsWith(IEventSlicer<TDoc, TId>)
But change the name from “Slicer” to “
Grouper” maybe, because that’s all it’s doing.

Oskar Dudycz @oskardudycz 10:16
Understood, that could work indeed if we provide some wrappers to make that easier for those common cases
GroupEventsWith(IEventSlicer<TDoc, TId>) - wouldn't that require also the event type?

Jeremy D. Miller @jeremydmiller 10:17
Yeah. A decent base class could hide the grouping by tenant id at a bare minimum.
“wouldn't that require also the event type?” — that would all be encapsulated inside your implementation of the IEventSlicer. We could maybe find some ways to help that out in the base class maybe.
The benefits here being:

Oskar Dudycz @oskardudycz 10:19
OK, sounds reasonable

Jeremy D. Miller @jeremydmiller 10:19
You can do anything
You can look at the full set of events at one time and hopefully reduce the number of round trips to the database for decent performance

Oskar Dudycz @oskardudycz 10:20
yes, that speaks to me

Jeremy D. Miller @jeremydmiller 10:20
Okay. I’ll re-write the issue a bit.

Oskar Dudycz @oskardudycz 10:20
Maybe I could try to implement that to get more into the details of new projection logic?

Jeremy D. Miller @jeremydmiller 10:20
I’m technically in meetings for the next 2 hours, but I’m working on Marten while listening anyway:)

Oskar Dudycz @oskardudycz 10:20
ah, if you prefers to do that on your own, it's also fine for me
I have still partitioning and imports on my plate

Jeremy D. Miller @jeremydmiller 10:21
Go for it. If you look in AggregateProjection, there’s an override for building the slicer. In your case, you’d bypass the codegen thing and just return the registered slicer.

Oskar Dudycz @oskardudycz 10:22
OK, I might not be able to work on that today, but if not today then I should be able to play with that tomorrows evening.

Jeremy D. Miller @jeremydmiller 10:22
I think you’ll wanna adjust the IEventSlicer signatures to add IQuerySession and/or rename it.
Sounds good.
```

**Comment by jeremydmiller** [comment]
Blech. This is still open.
