### ISSUE TITLE
IdentityMap may generate the same HashCode for different ids

### ISSUE THREAD

**Issue by jenspettersson** [JasperFx/marten#179]
In the IdentityMap (https://github.com/JasperFx/marten/blob/master/src/Marten/Services/IdentityMap.cs#L69) the generated HashCode is not always unique.

Really hard to provide a failing unit test as the generated hashcode differs from my lab project to a test in Marten.Testing. From MSDN:

> However, there is not a unique hash code value for each unique string value. Different strings can return the same hash code.

and

> ...they should never be used as key fields in a collection...

It's now used as a key in the dictionary in the IdentityMap and may or may not throw exceptions when trying to store two completely different objects in the same session just because their ids generated the same hashcode.

**Comment by jeremydmiller** [comment]
Meh, okay.
