### ISSUE TITLE
Support partial document updates?

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#18]
I used this feature a tiny bit with Raven. It's actually possible w/ Postgresql 9.5 to do partial updates to JSON documents, but I think you'd have to express the change as JSON. Not sure it'd be worth doing a strong typed facade over that, but could be wrong. Maybe use .Net's Dynamic type

**Comment by jeremydmiller** [comment]
Think this would be a lot easier in Postgresql 9.5: http://dba.stackexchange.com/questions/119089/postgres-function-to-merge-two-json-objects-with-overlapping-keys-into-one-objec

**Comment by jeremydmiller** [comment]
To make this quite a bit more concrete because it's on our "necessary for 1.0" roadmap. I did some research on the Postgresql JSON operators today, and I don't think that the new concatenation operator in 9.5 is going to be adequate for anything from very, very simple operations. `jsonb_set` **might** be useful for updating just one property/field at a time.

My thought is to say that partial document updates are going to require using PLV8 in your postgres db. I'm thinking that that option is getting pretty common in hosted postgres providers, but I can easily understand anyone not wanting to have to use that. I just think that this is going to be a lot easier to pull off using Javascript to do the JSON manipulation.

I also read over Raven's support today for their patching API: https://ravendb.net/docs/article-page/3.0/csharp/client-api/commands/patches/how-to-work-with-patch-requests. My thinking is that we'll have a mechanism where you *could* do document transforms with a user supplied JS function (https://github.com/JasperFx/marten/issues/253). That way we cover every possible use case that Raven does, one way or another. 

For a hard-coded API that hides the underlying JS from users, I'm thinking something like this:

```
// Set a property or field on one document by Id
session.Patch<User>(userId).Set(x => x.FirstName, "Some New Name");

// Append a new child to any kind of child collection by Id
session.Patch<Target>(id).Append(x => x.Children, [new element]);

// insert an element into a child collection at any index
session.Patch<Target>(id).Insert(x => x.Children, index, [new element]);

// The incremental value is optional, but set Number++
session.Patch<Target>(id).Increment(x => x.Number, 1);

// Also have a  Patch<T>(Expression<Func<T, bool>>) expression to do bulk updates
session.Patch<Target>(x => x.Color == Colors.Blue).Set(x => x.Number, 2);
```

**Comment by phillip-haydon** [comment]
I might be one of few people who actually don't like the patching API in RavenDB. I find the C# API so complicated I always end up going into the web console to try patch documents which still results in trial and error.

The hard coded API is what I want, however it's missing a couple of other use cases that I believe are important.


```
// Rename a property name from an old name to the new one defined on the target class
session.Patch<Target>(id).Rename("OldPropertyName", x => x.NewPropertyName);

// Remove an old property name
session.Patch<Target>(id).Remove("OldProperty");
```

These are strings because they probably should no longer exist on the class that is being patched. 


The two that would be super helpful right now for me are the `.Append / .Increment`.
