### ISSUE TITLE
Eliminate all usages of .ConfigureAwait(false) in the code

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1806]
Easy money, just putting this here to remember to do it

**Comment by lahma** [comment]
This might get a bit confusing as Marten 4 currently also targets netstandard2.0 which allows running on net461 and the rest, which then opens usage on classic web and winforms, [and this is also still a thing on .NET Core too](https://devblogs.microsoft.com/dotnet/configureawait-faq/#ive-heard-configureawaitfalse-is-no-longer-necessary-in-net-core-true).

So I don't strong opinions as I'm doing web APIs on .NET Core, but might bite later on 🙂

**Comment by jeremydmiller** [comment]
Marten v4 officially won't support anything < netcoreapp3.1

**Comment by jeremydmiller** [comment]
Done.
