### ISSUE TITLE
OrderBy on a dynamic column is not working

### ISSUE THREAD

**Issue by TimBrouwersBscript** [JasperFx/marten#1808]
When i want to order my query by a dynamic column name it always gives null. The sortby is the column name i get to sortby from my frontend.

query = query.OrderBy(x => x.GetType()
                                    .GetProperty(request.SortBy, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance)
                                    .GetValue(x, null));

Is there a solution for this?

**Comment by apereiratl** [comment]
I've updated a working way to do this in #2035.

**Comment by mysticmind** [comment]
Duplicate of #2035
