### ISSUE TITLE
Order By a field from a related table

### ISSUE THREAD

**Issue by gbrunton** [JasperFx/marten#1820]
Assuming the following.

``` c#
public class Ticket
{  
  public Guid Id {get;set;}
  public Guid CreatedByUserAccountId {get;set;}
}
public class UserAccount
{
  public Guid Id {get;set;}
  public string UserName {get;set;}
}
```

Is there a way to get the tickets ordered by their CreatedByUserAccount.UserNames? Something like the following.

``` c#
var tickets = session  
.Query<Ticket>()  
.OrderBy<UserAccount>(x => x.UserName);
```

More specifically, I'm wanting this done in sql.

**Comment by jokokko** [comment]
Hello.

Sounds a bit exotic query, but then again we don't know your use case. Anyway, somewhat crude way to achieve that would be

```csharp
var cmd = session.Query<Ticket>()
	.Include<UserAccount>(x => x.CreatedByUserAccountId, _ => { }).ToCommand();

var tickets = session.Query<Ticket>($"{cmd.CommandText} order by created_by_user_account_id.data->>'{nameof(UserAccount.UserName)}'").ToList();
```
(and customized according to your store & serialization settings).

**Comment by gbrunton** [comment]
Thank you for your response. You example is reasonable for me but I'm using 4.0.0-alpha.10 and Marten is no longer joining for includes. Instead it's using CTEs. Here's the command output.

``` sql
create temp table mt_temp_id_list1 as (
select id, CAST(d.data ->> 'CreatedByUserAccountId' as uuid) as id1 from public.mt_doc_ticket as d 
); select d.id, d.data from public.mt_doc_useraccount as d where id in (select id1 from mt_temp_id_list1);
 select d.id, d.data from public.mt_doc_ticket as d where id in (select id from mt_temp_id_list1)
```

I guess I can still parse this and include the join myself. That would work for me.

Again, thank you for your time on this.
