### ISSUE TITLE
Verify the changes in the naming convention

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#1826]
I noticed that when I switched to the latest version that it failed on some PK, It would be worth verifying that we don't have a lot of changes like that, and if we do, then we have the possibility and guidance on how to migrate from v3.

We could do some tests based on my samples on v3 and check what's failing for the v4 version. 

We could also use this PR https://github.com/oskardudycz/EventSourcing.NetCore/pull/38 as the source of ideas for the potential v4 upgrade path.

**Comment by jeremydmiller** [comment]
It didn't really, I made the judgement call that folks just need to run migrations.
