### ISSUE TITLE
Aggregate projection not being deleted when DeleteEvent is being fired and set as Async

### ISSUE THREAD

**Issue by julienperignon** [JasperFx/marten#1830]
Hey there . I'm currently trying to have the async daemon delete a projection row when a specific event is fired.
The projection row is correctly created but never deleted.
If i do change the projection lifecycle to ProjectionLifecycle.Inline. I can see the row gets deleted as part of the transaction when the delete event is being fired.

`Marten version : 4.0.0-alpha.10`

Here is the daemon setup : 

```
storeOptions.Events.Daemon.Mode = DaemonMode.HotCold;
```

Here is the projection registration
```
storeOptions.Events.Projections.Add<InspectionsPendingViewProjection>(ProjectionLifecycle.Async);
```

```
  public class InspectionsPendingViewProjection : AggregateProjection<InspectionPending>
    {

        public InspectionsPendingViewProjection()
        {
            DeleteEvent<InspectionCancelled>((d) => { return true; });
        }

        public void Apply(InspectionPending view, InspectionRequested @event)
        {
            view.Id = @event.Id;
            view.Address = @event.Address;
        }
      

    }
 public class InspectionPending
    {
        public Guid Id { get; set; }
        public string Address { get; set; }
    }
```

I doubled checked that events are there in the mt_events table : 
![image](https://user-images.githubusercontent.com/5164996/118756858-2b4a2880-b8af-11eb-8903-9c242d3870be.png)

and this is the projection : 
![image](https://user-images.githubusercontent.com/5164996/118756925-50d73200-b8af-11eb-9ec2-901d94d96c01.png)

Also the daemon logs : 
![image](https://user-images.githubusercontent.com/5164996/118757256-13bf6f80-b8b0-11eb-8a07-cf7cb6230be9.png)
![image](https://user-images.githubusercontent.com/5164996/118757275-1c17aa80-b8b0-11eb-9771-1a92c74d8603.png)

**Comment by jeremydmiller** [comment]
I might ask you to pull the latest the next time we're able to publish a Nuget (hopefully an RC), but otherwise, I'm closing this for now:(

**Comment by jeremydmiller** [comment]
@julienperignon I *did* make a change to the daemon internals in how it tracked progress to make the new tests pass that **could** maybe have caused some events to be skipped.
