### ISSUE TITLE
Code Generation Fixes

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1848]
Random things I found when building out the generate ahead model:

- [x] `AppendEventOperation` -- const for the SQL. Use `Setter.Constant()`
- [x] `BulkLoader` -- const for all strings
- [ ] `*InlineHandler.ApplyEvent()` -- don't use `async` keyword if no async methods. Will need to return `new ValueTask<T>()`
- [ ] `*InlineHandler.ApplyEvent()` -- will need to make the declaration of the aggregate object be nullable. Prefix the method argument with `?`. Will require changes to LamarCodeGeneration
- [x] `InlineHandler.ApplyEvent()` -- return value should be like `return new ValueTask<AGGREGATE>( aggregate ?? new AGGREGATE());`
- [x] Selector generation -- use the async version of the serialization `FromJsonAsync()`
- [ ] Compiled query generation -- constant for the SQL
- [x] `GeneratedInsertStream` -- use a constant for the SQL
- [x] `GeneratedStreamStateQueryHandler` -- use a constant for the SQL
- [x] `GeneratedStreamVersionOperation` -- use a constant for the SQL
- [x] `Insert/Upsert/Update*Operation` -- use a constant for the SQL
- [ ] `GeneratedEventDocumentStorage.ApplyReaderDataToEventAsync()` -- use async methods of DbDataReader
- [ ]

**Comment by Rob89** [comment]
Is it possible to have the generate ahead files have a `#pragma warning disable`? I like to have 'treat warnings as errors' enabled but the generated code is tripping me up. I can work around it with a separate configuration that has the option disabled in my pipeline but I thought I'd ask while the ticket was open :)

**Comment by jeremydmiller** [comment]
Today it's 

```
#pragma warning disable CS0108,CS0162,CS1998,CS0219
```

It's actually in LamarCodeGeneration, but I could use your suggestion.
