### ISSUE TITLE
Compilation failure when the compiled query type itself uses generics and the type parameters are types from a different assembly and are not referenced in ICompiledQuery interface type parameters.

### ISSUE THREAD

**Issue by rwasef1830** [JasperFx/marten#1851]
Hello,
The problem is in this part in CompiledQuerySourceBuilder:

```cs
    private void compileAssembly(GeneratedAssembly assembly)
    {
      AssemblyGenerator assemblyGenerator = new AssemblyGenerator();
      assemblyGenerator.ReferenceAssembly(typeof (IDocumentStorage<>).Assembly);
      assemblyGenerator.ReferenceAssembly(this._plan.QueryType.Assembly);
      assemblyGenerator.ReferenceAssembly(this._plan.OutputType.Assembly);
      assemblyGenerator.Compile(assembly);
    }
```

The code needs to recurse into the generic type parameters of the query type and output type and reference all relevant assemblies (of the inner type parameters). I'll try to come up with a PR for this as soon as possible. Fix to this is safe and non-breaking to consumers of Marten, so it should be no problem to take.

**Comment by jeremydmiller** [comment]
@rwasef1830 That doesn't sound bad if you're good with doing the PR for that.

**Comment by rwasef1830** [comment]
@jeremydmiller already done, see #1852

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/pull/1852
