### ISSUE TITLE
JSON reordering is not handled correctly for Newtonsoft

### ISSUE THREAD

**Issue by zagyar** [JasperFx/marten#186]
Hello,
I faced issue, can you please advice on below:

On Store Newtonsoft.Json generate valid json with leading $type, but on insert to postgres it's reordered (due to jsonb).
As result on deserialization step dictionary got extra row with $type.

How to check json reordering:
create table test_jsonb_dummy (data jsonb NOT NULL);
INSERT INTO test_jsonb_dummy (data) VALUES
('{"Fields": {"$type": "System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.String, mscorlib]], mscorlib","1": "one","test": "test"}}');

select * from test_jsonb_dummy; -- they will be ordered by name, by Newtonsoft.Json by default need $type to be leading

drop table test_jsonb_dummy;

Workaround:
implemented ISerializer interface based on Marten.Services.JsonNetSerializer with MetadataPropertyHandling.ReadAhead setting - see http://www.newtonsoft.com/json/help/html/DeserializeMetadataPropertyHandling.htm for more details

**Comment by jeremydmiller** [comment]
@zagyar Got it, thank you. This'll be fixed in the v0.8 nuget later this week.
