### ISSUE TITLE
Marten4 performance issues with nested structures

### ISSUE THREAD

**Issue by KasperDamgaard** [JasperFx/marten#1864]
I think you have a performance issue with Marten4 and nested queries. For even semi-large data quantities (e.g. 5000 entries), trying to do the following query is slower than Marten3:
classA.Where(a => a.ClassBs.Any(b => b.Id == someId)

In Marten4 this roughly translates to (taken from the IMartenSessionLogger's NpgsqlCommand's CommandText) :

```
WITH mt_temp_id_list1CTE as (
select id,
unnest(CAST(ARRAY(SELECT jsonb_array_elements(CAST(d.data ->> 'Guarantees' as jsonb))) as jsonb[])) as data
from treatment.mt_doc_treatmentcourse as d
)
, mt_temp_id_list2CTE as (
select id, data
from mt_temp_id_list1CTE as d
where CAST(d.data ->> 'Id' as varchar) = 'ae822ffd-672d-4539-bddf-4473ec1392cc'
)
select d.id, d.data
from treatment.mt_doc_treatmentcourse as d
where id in (select id from mt_temp_id_list2CTE)
LIMIT 1;
```

Whereas Marten3 would translate it into:

`select d.data, d.id, d.mt_version from treatment.mt_doc_treatmentcourse as d where d.data @> '{"Guarantees":[{"Id":"ae822ffd-672d-4539-bddf-4473ec1392cc"}]}' LIMIT 1`

The problem seems to be that you're not filtering in the first select statement, but rather just expands the entire table and then do a select on everything again. If you just merge the middle where clause with the first select as such:

```
WITH mt_temp_id_list1CTE as (
select id,
unnest(CAST(ARRAY(SELECT jsonb_array_elements(CAST(d.data ->> 'Guarantees' as jsonb))) as jsonb[])) as data
from treatment.mt_doc_treatmentcourse as d
where CAST(data ->> 'Id' as varchar) = 'ae822ffd-672d-4539-bddf-4473ec1392cc'
)
select d.id, d.data
from treatment.mt_doc_treatmentcourse as d
where id in (select id from mt_temp_id_list1CTE)
LIMIT 1;
```

Then it's much faster. Difference is 1.5s. vs. 200ms. when running against my test database with 5k entries. Almost a factor 10.
The positive thing is that it seems like this last approach is just as fast as the Marten3 approach - but that might change with data sizes and data structure. 

The problem only increases when the data structure is deeper nested. In general the issue seems to be that Marten unnests the entire table without filtering in the same operation. This basically just makes the searchspace larger once the next select comes along. 
I get that we cannot use Marten3's approach as that did not have support for nested queries (and other issues), but we should try to be smarter about when the basic Marten3 approach is maybe faster, or just improve upon the current Marten4 approach. 

This problem only shows itself with more data present than just a few entries, thus maybe you could consider creating performance tests which is only run manually or something like that. 
I would like to contribute, but due to vacation this is possible no sooner than 1 month from the issue creation date.

**Comment by jeremydmiller** [comment]
I'm going to pick this up in the next couple days and get it in for v4. At a bare minimum, we'll move the filters up to the top level as a first step. Reverting back to selectively using the containment operator isn't gonna be in that fix though, that one is a world of hurt.

**Comment by jeremydmiller** [comment]
We're going to move the filters up to the top level **for now**, and revisit the possibility of selectively switching back to the containment operator as part of >4.0
