### ISSUE TITLE
DefaultMartenLogger is always used then calling AddMarten 

### ISSUE THREAD

**Issue by darraghjones** [JasperFx/marten#1888]
If I write:

```
services.AddMarten(provider =>
            {
                StoreOptions options = new StoreOptions();
                options.Logger(new MyMartenLogger());
                options.AutoCreateSchemaObjects = AutoCreate.None;
                ...
                return options;
            });
```

MyMartenLogger is not used. It's gets replaced:

```
    public static MartenServiceCollectionExtensions.MartenConfigurationExpression AddMarten(
      this IServiceCollection services,
      Func<IServiceProvider, StoreOptions> optionSource)
    {
      services.AddSingleton<StoreOptions>(optionSource);
      services.AddSingleton<IDocumentStore>((Func<IServiceProvider, IDocumentStore>) (s =>
      {
        ILogger<IDocumentStore> logger = s.GetService<ILogger<IDocumentStore>>() ?? (ILogger<IDocumentStore>) new NullLogger<IDocumentStore>();
        StoreOptions requiredService = s.GetRequiredService<StoreOptions>();
        requiredService.Logger((IMartenLogger) new DefaultMartenLogger((ILogger) logger));
        return (IDocumentStore) new DocumentStore(requiredService);
      }));:
...

```

**Comment by darraghjones** [comment]
Great to see this get fixed so quickly! is there a way to see when this get's published to nuget?

**Comment by mysticmind** [comment]
@darraghjones fix is in 4.0.0-rc.7, available in NuGet.

**Comment by darraghjones** [comment]
just for context, the reason i needed to write my own logger is because the default logger was throwing an exception because my SQL parameter had a "{" in the name.  My EntityId is a record, and i'm using the default ToString implementation on this, e.g. `public string Id => EntityId.ToString();`

so i've basically copied the default logger and added:
`message = message.Replace("{", "{{").Replace("}", "}}");`
admittedly this is hacky.

**Comment by mysticmind** [comment]
I will have a look at the above issue which you have outlined and fix the same.

**Comment by darraghjones** [comment]
i think i've actually come up with a better fix, as the previous one actually is a bit crap
`
        public void LogFailure(NpgsqlCommand command, Exception ex)
        {
            this._stopwatch?.Stop();
            string message = "Marten encountered an exception executing \n{SQL}\n{PARAMETERS}\n";
            string parameters = command.Parameters.OfType<NpgsqlParameter>().Select<NpgsqlParameter, string>((Func<NpgsqlParameter, string>)(p => string.Format("  {0}: {1}", (object)p.ParameterName, p.Value))).Join(Environment.NewLine);
            this._logger.LogError(ex, message, (object)command.CommandText, parameters);
        }
`

**Comment by mysticmind** [comment]
If you are comfortable please send a PR with the above outlined fix and a unit test. Otherwise, I will take care of it.
