### ISSUE TITLE
v4, CompiledListQuery index outside the bounds of the array

### ISSUE THREAD

**Issue by willhausman** [JasperFx/marten#1891]
Using 4.0.0-rc.6

I have a problem using compiled list queries in my application. I want to have a compiled paginated result, but cannot get it to work for the life of me.  As I continued to remove items to get it as simple as I could, I found that even a bare minimum query did not work. Here is that code:

```csharp
    public class CompiledTimeline : ICompiledListQuery<TimelineItem>
    {
        public CompiledTimeline(string type) { Type = type; }
        public string Type { get; set; }
        public Expression<Func<IMartenQueryable<TimelineItem>, IEnumerable<TimelineItem>>> QueryIs() =>
            query => query.Where(i => i.Event == Type);
    }

    public record TimelineItem(Guid Id, string Event, User Raised);
```

Calling `var timeline = session.Query(new CompiledTimeline(nameof(PartyCreated)));` gives me this stacktrace:

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Marten.Generated.CompiledTimelineCompiledQuery.ConfigureCommand(CommandBuilder builder, IMartenSession session)
   at Marten.Util.CommandExtensions.BuildCommand(IMartenSession session, IQueryHandler handler)
   at Marten.Internal.Sessions.QuerySession.ExecuteHandler[T](IQueryHandler`1 handler)
   at Marten.Internal.Sessions.QuerySession.Query[TDoc,TOut](ICompiledQuery`2 query)
   at trial.Program.Main(String[] args) in /Users/willhausman/src/trial/Program.cs:line 71
```

I want to be able to paginate, but the properties for Skip and Take wind up throwing validation exceptions.
```csharp
            query => query.Where(i => i.Event == Type).Skip(SkipCount).Take(PageSize);
```
```
   Marten.Exceptions.InvalidCompiledQueryException : Unable to match compiled query member(s) SkipCount, PageSize with a command parameter
  Stack Trace:
     at Marten.Internal.CompiledQueries.CompiledQueryPlan.ReadCommand(NpgsqlCommand command, StoreOptions storeOptions)
   at Marten.Internal.CompiledQueries.QueryCompiler.BuildPlan[TDoc,TOut](IMartenSession session, ICompiledQuery`2 query, StoreOptions storeOptions)
   at Marten.StoreOptions.GetCompiledQuerySourceFor[TDoc,TOut](ICompiledQuery`2 query, IMartenSession session)
   at Marten.Internal.Sessions.QuerySession.QueryAsync[TDoc,TOut](ICompiledQuery`2 query, CancellationToken token)
```

Although, it would also be very nice if `MartenIgnore` were not marked `internal`, and worked to allow me to tell the `ICompiledQuery` not to validate certain properties.  It would be nice to be able to say this without it complaining the `Page` wasn't used in the command:

```csharp
    public class CompiledTimeline : ICompiledListQuery<TimelineItem>
    {
        public int PageSize { get; set; }
        [MartenIgnore]
        public int Page { get; set; }
        public int SkipCount => (Page - 1) * PageSize;
        public string Type { get; set; }
        public Expression<Func<IMartenQueryable<TimelineItem>, IEnumerable<TimelineItem>>> QueryIs() =>
            query => query.Where(i => i.Event == Type).Skip(SkipCount).Take(PageSize);
    }
```

**Comment by willhausman** [comment]
Ok, after yet more tinkering, I think I've narrowed it down to a tenancy issue. I can get the query to work if I drop all tenancy from my sample code.

This configuration works:
```chsharp
options.Connection(ConnectionString);
options.AutoCreateSchemaObjects = Weasel.Postgresql.AutoCreate.All;
options.Schema.For<TimelineItem>();
```

This configuration throws the exception:
```csharp
options.Policies.ForAllDocuments(x =>
{
    x.TenancyStyle = TenancyStyle.Conjoined;
});
```

I used `store.Diagnostics.PreviewCommand(query)` to see what was being run.  I saw that the the bound parameters were not getting values set as expected.
Here is the output I got from the previewed cmd when the query worked without tenancy:
```
select d.id, d.data from parties.mt_doc_timelineitem as d where d.data ->> 'Event' = :p0
p0: MegaSpecial
```

Here is the output I got from the previewed cmd when the query failed with tenancy:
```
select d.id, d.data, d.mt_version from parties.mt_doc_timelineitem as d where d.tenant_id = :tenantid  and  d.data ->> 'Event' = :p0
p0: 
tenantid: *DEFAULT*
```

**Comment by jeremydmiller** [comment]
@willhausman I've got a fix for the query planning issues, and that really required some new development. I honestly haven't tried the compiled query feature with multi-tenancy, and that's gonna be a separate issue -- but most likely a much simpler one to address.

**But**, your initial issue is going to have to be solved with some documentation in addition to some minor changes to Marten coming up.
