### ISSUE TITLE
v4, Can't use MartenIgnore attribute

### ISSUE THREAD

**Issue by willhausman** [JasperFx/marten#1898]
The solution for #1891 added more uses to the `MartenIgnoreAttribute`, but it still can't be accessed outside of Marten. #1894 attempts to resolve this naively, but perhaps a broader rename is appropriate if the attribute is not just intended for the `CodeGeneration` namespace.

**Comment by oskardudycz** [comment]
Fixed by https://github.com/JasperFx/marten/pull/1894 

@willhausman should be available in the next RC or the major v4 👍 

If you need it sooner, please ping us on Gitter, then we'll release an RC more shortly.
