### ISSUE TITLE
Modal queries no longer work

### ISSUE THREAD

**Issue by bVanHertum** [JasperFx/marten#190]
Since the latest master (commit afd9b50), modal Linq queries fail. Here's a (very simple) unit test demonstrating the issue:

>         [Fact]
        public void TestModalOrQuery()
        {
            var target1 = new Target { String = "Bert", Date = new DateTime(2016, 03, 10) };
            var target2 = new Target { String = null, Date = new DateTime(2016, 03, 10) };
            var targetList = new List<Target> { target1, target2 };
            theSession.Store(target1);
            theSession.Store(target2);
            theSession.SaveChanges();

            var startDate = new DateTime(2016, 03, 01);
            var endDate = new DateTime(2016, 04, 01);

            var query = theSession.Query<Target>().Where(item => (item.String != null && item.Date >= startDate && item.Date <= endDate) 
                || (item.String == null && item.Date >= startDate && item.Date <= endDate));

            Assert.True(query.ToList().Count >= 2);
        }

If you look at the generated query in Diagnostics, you'll see that the "or" becomes an "and" in the postgresql query, meaning the result will always be empty.

**Comment by jeremydmiller** [comment]
@bVanHertum Got it, and I think I know what the issue is. Probably related to https://github.com/JasperFx/marten/issues/133. I'll be trying to address this this morning

**Comment by bVanHertum** [comment]
@jeremydmiller  Thanks :) 

And, just to note, I was first using commit 56dda5b, in which this query worked perfectly. So I suspect it's related to a bug introduced with the refactoring of the ExpressionParser.

**Comment by jeremydmiller** [comment]
@bVanHertum It was a one line code fix. Something I'd forgotten to do in the refactoring -- and didn't have any test coverage on prior to this.

**Comment by bVanHertum** [comment]
Figures it was something small like that. Awesome that you found it so quickly!
