### ISSUE TITLE
event sourced Aggregate subclassing with inline projections creates tables for unused subclasses

### ISSUE THREAD

**Issue by danyo1399** [JasperFx/marten#1912]
Martendb 3.13.5
When creating event sourced tables as subclasses, the data is stored against the base class table, however tables for the subclasses are still generated even though from what i can see they are not used.

The store.Schema.ToDDL() method will create the subclass tables in the schema generation, and store.Advanced.Clean.DeleteDocumentsExcept() will throw an exception if  the subclass tables dont exist. 

However with martens default auto create tables as required, it does not create these additional tables. Only the schema generation and advanced db functions expect them.

Here is a repo to reporduce the issue.
https://github.com/danyo1399/marten-db-subclassing-bug

Notes from original discussion on gitter
https://gistdoc.tty.nz/shared/37c6b2470da0985940bcd7d4b629d40c

**Comment by jeremydmiller** [comment]
Didn't realize this was Marten 3. We probably won't touch this for the time being until 4 is out.

**Comment by danyo1399** [comment]
all good. Its prolly not a major issue. Thx again for your help earlier

**Comment by jeremydmiller** [comment]
Going to close this just because it's unlikely to ever get fixed in the 3.* branch:|
