### ISSUE TITLE
SelectTransformBuilder doesn't handle subqueries. Cannot make any kind of subquery projection

### ISSUE THREAD

**Issue by rwasef1830** [JasperFx/marten#1924]
Given this class:

```cs
class User 
{
    public Guid Id { get; set; }
    public List<Guid> RoleIds { get; set; }
}
```

```cs
var session = store.QuerySession();
session.Query<User>(x => new { x.Id, FirstRoleId = x.RoleIds.FirstOrDefault() });
```
This query does not work and throws an exception, it appears to be only expecting sub-member expressions from the RoleIds collection which doesn't work because it's a collection of scalar values.

PR with failing unit test coming.

**Comment by rwasef1830** [comment]
This is closer to what Marten generates:

```sql
SELECT
       jsonb_build_object('Id', d.data->>'Id',
       'RoleId', (SELECT id.data->'RoleIds'->>0 FROM mt_doc_user AS id WHERE id.id = d.id LIMIT 1))
```

**Comment by jeremydmiller** [comment]
Beating this for now w/ the ability to use array indexers and calling that good enough.

**Comment by jeremydmiller** [comment]
I'm closing this one. We're not going any farther for now.

**Comment by rud** [comment]
Should this be closed too? 
* #1925
