### ISSUE TITLE
Select<T>(x => x.ExplicitSql(text)) transform in Select statements

### ISSUE THREAD

**Issue by rwasef1830** [JasperFx/marten#1926]
In some cases it maybe desirable to express a projection to a property that Marten's LINQ provider is unable to parse (yet).
In such case it would be so nice if we could have something like

```cs
session.Query<User>(x => new 
{ 
    Id = x.Id, 
    FirstRoleId = Projection.For<Guid>("d.data->'RoleIds'->>0") 
});
```

or maybe

```cs
session.Query<User>(x => new 
{ 
    Id = x.Id, 
    FirstRoleId = x.SqlProjection<Guid>("d.data->'RoleIds'->>0") 
});
```

A certain convention will need to be established and documented perhaps for inner subqueries or related document fetches (where the "d" alias would perhaps differ).

**Comment by jeremydmiller** [comment]
Working on this one today

## Tasks

- [ ] Test with Select(x => x.ExplicitSql()) for scalar values
- [ ] Test with Select(x => new Persion{Name = x.ExplicitSql()})

**Comment by jeremydmiller** [comment]
Boom! Working locally.
