### ISSUE TITLE
Marten.AspNetCore 4.0.0 hasn't been published to NuGet

### ISSUE THREAD

**Issue by catfag** [JasperFx/marten#1930]
As the title states, it's missing. It seems like the GitHub Action for package deployment has been updated for the release, but it failed to upload Marten.AspNetCore due to a [permissions issue](https://github.com/JasperFx/marten/runs/3839109407?check_suite_focus=true#step:5:25). This is probably because package ownership of the main [Marten](https://www.nuget.org/packages/Marten) package is jeremydmiller and mysticmind, while [Marten.AspNetCore](https://www.nuget.org/packages/Marten.AspNetCore) (seems to be an legacy project?) is owned by jokokko.

@jokokko

**Comment by jokokko** [comment]
Package ownerships adjusted.

**Comment by catfag** [comment]
Thanks!
