### ISSUE TITLE
Infinite GetResult() of ensureStorageExists in Blazor Server App

### ISSUE THREAD

**Issue by Archangel603** [JasperFx/marten#1957]
Environment:
.NET SDK 5.0.205
Microsoft.AspNetCore.App 5.0.8
Marten 4.0.2
Docker 20.10.9, build c2ea9bc90b
Postgres 13-alpine in Docker

Repro link: https://github.com/Archangel603/marten-blazor-repro

Marten works fine in controllers and middleware (see /test in repro). 
However, when i try to use it in Blazor Components, call to session.Store(user) never finishes (see Pages/Index.razor:21). 
Call stack goes all the way to Marten.Storage.Tenant EnsureStorageExists(Type featureType)
and stops at this.ensureStorageExists((IList<Type>) new List<Type>(), featureType).GetAwaiter().GetResult();

Edit: Added the stack trace for ref.
<img width="1440" alt="Screenshot 2021-10-29 at 8 37 57 PM" src="https://user-images.githubusercontent.com/2864208/139458990-ded038da-ac42-4e1c-910c-3232bb05cc7c.png">

**Comment by mysticmind** [comment]
@solyutor addessed this in https://github.com/JasperFx/marten/pull/1960

**Comment by mysticmind** [comment]
Tested in dev environment with the repro project using Marten Master branch and it is working fine as expected. See the screenshots below for your ref.
<img width="1102" alt="Screenshot 2021-11-03 at 10 31 19 PM" src="https://user-images.githubusercontent.com/2864208/140122186-8fb6f92d-38f9-4ba9-988f-84d2d3d95a11.png">
<img width="688" alt="Screenshot 2021-11-03 at 10 31 35 PM" src="https://user-images.githubusercontent.com/2864208/140122277-8e061042-b485-4bf5-8057-44cd8388e1b2.png">

Marking this as fixed via #1960

**Comment by Archangel603** [comment]
Excellent!
