### ISSUE TITLE
Nested duplicate property and bulk insert error

### ISSUE THREAD

**Issue by Rensvind** [JasperFx/marten#1975]
Given the following document

  ```
   public class Test
    {
        public Guid Id { get; set; }

        public Nested Nested { get; set; }
    }

    public class Nested
    {
        public Nested(Guid id)
        {
            Id = id;
        }

        public Guid Id { get; set; }
    }
```
with a nested duplicate property
`options.Schema.For<Test>().Duplicate(x => x.Nested.Id);`

a bulk insert
```
documentStore.BulkInsertDocuments(new List<Test>
            {
                new Test
                {
                    Id = Guid.NewGuid(),
                    Nested = new Nested(Guid.NewGuid())
                }
            });
```

results in

![image](https://user-images.githubusercontent.com/282209/140928258-7bf13096-9c67-438c-b77b-07677bb6b4ab.png)

**Comment by jeremydmiller** [comment]
@Rensvind Which version are you seeing this happen? We've dealt with very similar issues earlier on in 4.0.

**Comment by Rensvind** [comment]
@jeremydmiller it's version 4.2.0.
