### ISSUE TITLE
Rebuilding Async Projection Does Not Wait for Batch to Complete Before Moving to Next Batch

### ISSUE THREAD

**Issue by kluhman** [JasperFx/marten#1988]
Marten Version: `4.1.0`
Target Framework: `net5.0`

I have a projection I am rebuilding using the async daemon and when I am rebuilding it, it produces incorrect results. I've been debugging and it appears when I am using a custom grouper it doesn't wait for a previous batch's result to be saved prior to grouping the next batch. This results in getting incorrect documents from my query, so events are not applied to the documents correctly. Using breakpoints, I'm seeing the `Group` being called before the `Apply` on the previous groupings. I've attached a reproducible example project that is similar to what I'm doing in my real app. 

When I run this app the first time, it generally succeeds (not all the time), but if I run it more than once, it always fails on subsequent runs. 

Note that the example is extremely arbitrary, and I realize that in this example app it could be modeled differently, but I promise in my real app I have to load the documents the way I do here.

[Minimal Reproducible Example](https://github.com/JasperFx/marten/files/7573664/MartenPlayground.zip)

**Comment by jeremydmiller** [comment]
Step 1 is just making sure the relevant ActionBlock is set to single file, ensured ordering. Not sure about this though, because *nothing* should be working well without that.

**Comment by jeremydmiller** [comment]
Okay, nevermind, duh. The design of the action blocks in the aggregation was built with the assumption that the "grouping" could be done in parallel to the application of the projection itself, so the grouping is in a separate action block from the application and update of a single event batch. Works wonderfully for aggregation by stream, and not so much for custom grouping where you use the data store in order to do the grouping. 

It's going to take some significant design changes to the async daemon internals to accommodate what you're trying to do here w/o losing the throughput optimizations we did for "not crazy" aggregations.

**Comment by kluhman** [comment]
@jeremydmiller Thanks for the response, I can understand the throughput optimization. I do want to note I think this is a use case that would arise somewhat frequently for anybody using projections to create denormalized, performant read side models, not just in my weird case here. For example, if you had a denormalized `Issue` model that contained the name of the assignee, if the assignees name changed, you would need to look up all the issues assigned to that employee to know which ones to apply the name change ever to. That would be impossible to do accurately if you cannot depend on the projections being up to date prior to the grouping. 

In the mean time, is there any documentation you could point me to for writing a custom `IProjection`? I'm not really sure what that entails but would love to read anything that points to a better long term solution than the current workaround I have.

Thanks again for your response and work on this

**Comment by jeremydmiller** [comment]
Specifically, it's using the aggregate build product itself within the grouping. That's just not gonna work as it is. The `IProjection` interface is pretty simple at least. Here's a batch of events organized by stream, go do whatever you want. In your case, you want to use a full identity map session I think so you can avoid doing unnecessary lookups.

I don't think there's anything to change on the Marten side other than documentation and maybe building a documented example.
