### ISSUE TITLE
Using NodaTime in Document Metadata

### ISSUE THREAD

**Issue by DJBMASTER** [JasperFx/marten#1989]
The metadata **SoftDeletedAt** field is a **DateTimeOffset**. If we are using the **Marten.NodaTime** package are we able to use NodaTime specific types to opt-in to automatic data/time metadata handling?

**Comment by jeremydmiller** [comment]
Not today, no. Wouldn't impact the database storage regardless. Better question back to you is why? To what effect? How would that even matter to you?

**Comment by DJBMASTER** [comment]
I guess in terms of the stored date values then it doesn't matter if it's coming from a BCL DateTimeOffset or a NodaTime type. I think I was just looking to use a standard typing across all documents and not mix and match BCL date/time types when using NodaTime.

**Comment by jeremydmiller** [comment]
Sure, but that's an internal detail to Marten
