### ISSUE TITLE
Create SQL Command For BulkInsert

### ISSUE THREAD

**Issue by robconery** [JasperFx/marten#199]
Hi guys - I was having a peak through the code and came across this:
https://github.com/JasperFx/marten/blob/master/src/Marten/DocumentStore.cs#L136

It looks like you're batching commands in a transaction - which is a fine way to do it - but I thought I would share with you some intense performance gains we saw with Massive/Moebius (Elixir). It seems a little hacky - but the perf gain is worth it.

Before we did this, we were seeing about 1000 inserts per second on our local machines using a batched command (this was Elixir) - but then @xivsolutions decided to see what would happen if we wrote a SQL string:

``` sql
insert into document_table(body)
values(@1),(@2),(@3) #...
```

This sped up our writes to (no exaggeration) **60K/second**. Of course that's my local machine at it's peak limit - but that's a massive gain.

There's a cap on how many parameters you can pass in - I believe it's around 50K. Also - an option you might consider for people running a bulk insert is to turn off indexing. I haven't seen if you guys are doing `jsonb_path_opts` or are leaving indexes up to the client - but if the former, a nice speed up would be to drop the index and concurrently re-add after the bulk load.

Those would be some impressive numbers :). Anyway - just thought I would share...

**Comment by jeremydmiller** [comment]
@robconery The `IDocumentSession.SaveChanges()` does a batched command where everything goes up in one ADO command. The method you were referring to uses Postgres's COPY mechanism under the covers: http://www.npgsql.org/doc/copy.html.

Did you guys try that? How did that compare?

**Comment by jeremydmiller** [comment]
@robconery Thanks for the suggestion Rob and the drive by;)

We haven't gotten around to full text search yet, but it'll look like what I remember from your blog posts.
