### ISSUE TITLE
ViewProjection does not get deleted when listening to DeleteEvent

### ISSUE THREAD

**Issue by BusschaertTanguy** [JasperFx/marten#1993]
Hello.

When storing an event to the event store, my ViewProjection doesn't execute the DeleteEvent method it's the AggregateProjection base class.

Here's the command handler

```cs
public async Task<Unit> Handle(Command request, CancellationToken cancellationToken)
{
    var category = await _categoryRepository.GetById(request.Id);
    category.Remove();
    await _categoryRepository.Delete(category);
    return Unit.Value;
}
```

The Category Remove method which raises the event ( add to list of events ) and apply it:

```cs
public void Remove()
{
    RaiseEvent(new CategoryRemoved(Id), Apply);
}
```

Here's the repository code for the delete (raises the event and archives the stream)

```cs
public async Task Delete(TRootEntity rootEntity)
{
    var events = rootEntity.DomainEvents.ToArray();
    await using var session = _store.OpenSession();
    session.Events.Append(rootEntity.Id, rootEntity.Version, events);
    await session.SaveChangesAsync();
    
    session.Events.ArchiveStream(rootEntity.Id);
    await session.SaveChangesAsync();
}
```

Here's the ViewProjection class

```cs
public class CategoriesViewProjection : ViewProjection<CategoriesView, Guid>
{
    public CategoriesViewProjection()
    {
        Identity<CategoryCreated>(@event => @event.Id);
        Identity<CategoryInformationChanged>(@event => @event.Id);
        DeleteEvent<CategoryRemoved>((view, @event) => view.Id == @event.Id);
    }

    public void Apply(CategoryCreated @event, CategoriesView view)
    {
        var (id, name) = @event;
            
        view.Id = id;
        view.Name = name;
    }
    
    public void Apply(CategoryInformationChanged @event, CategoriesView view)
    {
        view.Name = @event.Name;
    }
}
```

It's the
```cs
DeleteEvent<CategoryRemoved>((view, @event) => view.Id == @event.Id);
```

Part that's not working, the other events using Identity work well.

Here's my store configuration

```cs
services.AddMarten(options =>
{
    options.Connection(connectionString);

    if (hostEnvironment.IsDevelopment())
    {
        options.AutoCreateSchemaObjects = AutoCreate.All;
    }
    
    options.Projections.Add<CategoriesViewProjection>(ProjectionLifecycle.Inline);
});
```

**Comment by jeremydmiller** [comment]
Is there any reason why you're using ViewProjection here instead of AggregateProjection? You're de facto using the stream id as the aggregate id, so there's no real difference here. And you do want to do the append event & archive stream in the same logical transaction I would think up above, so only one call to SaveChangesAsync()

**Comment by BusschaertTanguy** [comment]
> Is there any reason why you're using ViewProjection here instead of AggregateProjection? You're de facto using the stream id as the aggregate id, so there's no real difference here. And you do want to do the append event & archive stream in the same logical transaction I would think up above, so only one call to SaveChangesAsync()

@jeremydmiller Where do I define in the aggregate projection that it is for a specific stream id ?

**Comment by jeremydmiller** [comment]
"Where do I define in the aggregate projection that it is for a specific stream id ?" -- that's implied by using an `AggregateProjection`. See https://martendb.io/events/projections/aggregate-projections.html#aggregate-by-stream.

**Comment by BusschaertTanguy** [comment]
Ok I refactored it using AggregateProjection, and it works perfectly now.

**Comment by jeremydmiller** [comment]
Still a bug though, so leave this open. Glad you're on your way. Not clear to me yet why it would function differently w/ a ViewProjection, but I'll try it out after Thanksgiving.

**Comment by jeremydmiller** [comment]
Oh man, no, this isn't a bug at all. I finally had enough sleep and coffee. This code would never ever work the way you think:

```
DeleteEvent<CategoryRemoved>((view, @event) => view.Id == @event.Id);
```

`IEvent.Id` is a unique Guid id for the event itself and not related to the stream id that I think you were depending on here. 

I'm closing this.
