### ISSUE TITLE
Paging in the querying. Do something similar to RavenDb's

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2]
Will need this sooner or later.

**Comment by jeremydmiller** [comment]
I'm specifically referring to the Statistics(out stats) feature in RavenDb: http://ravendb.net/docs/article-page/2.5/csharp/client-api/querying/paging

I'm frankly fine with copying the signature.

**Comment by phillip-haydon** [comment]
This should be achievable with `count(1) OVER() as total_rows`

`select *, count(1) OVER() as total_rows from mt_doc_photo limit 10;`
