### ISSUE TITLE
Marten v4.3.0 - EjectAllOfType does not clear pending changes

### ISSUE THREAD

**Issue by mronnblom-cint** [JasperFx/marten#2005]
For some reason, `EjectAllOfType` does not clear pending changes. The ItemMap is cleared though. I can't see any apparent problem with the code below.. Maybe `CanBeCastTo` doesn't work in this case? There are no tests for `EjectAllOfType`...

DocumentSessionBase:
```
public virtual void EjectAllOfType(Type type)
{
    ItemMap.Remove(type);
    ChangeTrackers.RemoveAll(x => x.Document.GetType().CanBeCastTo(type));
}
```

**Comment by oskardudycz** [comment]
@mronnblom-cint, thank you for the information. I don't recall any changes in this area recently. Could you send a PR with a test reproducing your issue? It'd help us to tackle this case.

**Comment by jeremydmiller** [comment]
`PendingChanges()` is based off the pending operations, which is independent of the identity map or automatic dirty checking tracking. Honestly, the functionality is working exactly as it was envisioned. 

To be clear, what you're really wanting is to clear our and remove previously *explicitly* registered actions to a session? I.e., you're wanting to remove pending operations resulting from `Store()` / `Insert()` / `Update()` calls to the same session? That honestly isn't something we ever anticipated.

**Comment by jeremydmiller** [comment]
And I'm removing the "Bug" tag here, because it's not.

**Comment by mronnblom-cint** [comment]
Is it your intention that `Eject` and `EjectAllOfType` should work differently? That seems very weird to me, and also not in line with the summary descriptions. The summary for `EjectAllOfType` clearly states that it should clear "unit of work tracking". Eject does. EjectAllOfType does not. I made this PR which also demonstrates this with tests:
https://github.com/JasperFx/marten/pull/2010

**Comment by jeremydmiller** [comment]
Can you go farther and send the PR in with whatever changes in functionality you want to purge operations as well? Dude, to be clear, I don't really approve of the way you're doing things, but I'm okay with the extra functionality here if you'll do the PR to also purge operations. What you're wanting is never what I intended the code to do, but I never thought to use a session in a reentrant way like you seem to be doing here.

**Comment by mronnblom-cint** [comment]
"The way I'm doing things"? And what way is that? Have you looked at the PR? If you had, you would have seen that it DOES contain the changes to the functionality, including tests for it (that you completely have omitted for `EjectAllOfType`). Also, if this was never your intention of how that method should work, can you explain how the summary for it should be interpreted?

```
        /// <summary>
        /// Completely remove all the documents of given type from this session's unit of work tracking and identity map caching
        /// </summary>
```

I mean, "completely remove all documents from unit of work tracking". Don't leave much room for misinterpretation there IMO. So when the method doesn't do what the summary says, developers like me get confused.

**Comment by oskardudycz** [comment]
Folks, let's bring it back to the point of change, and not get heated. @mronnblom-cint, I apologize for the confusion. I think that Jeremy overlooked your PR.

@jeremydmiller, looking at the changes in the @mronnblom-cint PR, they seem to be valid, as they're adding in the `EjectOfAllType` what's already in the `Eject` method. In my opinion, they're accurate, unless I'm missing some essential aspect.

**Comment by jeremydmiller** [comment]
Guys, I'm gonna pull this down, add just a little more testing, and pull it in.
