### ISSUE TITLE
New ToCommand() signature on IMartenQueryable

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#201]
I think this would be nice to have, a new extension method off of IQueryable that let's you preview what the underlying NpgsqlCommand would be. I kinda want this before we go too crazy into the Select() projections for obvious reasons.

In usage, I think it'd be:

```
session.Query<User>().Where(x => x.UserName == 'foo').ToCommand(FetchType.Many)

```

With the new `FetchType` would just represent the categories of fetching you can do (ToList(), Count(), Any(), etc.):

```
public enum FetchType
{
    Count,
    Any,
    FetchOne,
    FetchMany
}

```

**Comment by phillip-haydon** [comment]
That's actually pretty cool, and would be handy, last night I wrote a query and was thinking it would be nice to capture what its executing instead of having to go poke around in the `pg_stat_activity` table.
