### ISSUE TITLE
ThenBy missing on IBatchedQueryable

### ISSUE THREAD

**Issue by davidjamesb** [JasperFx/marten#2026]
Whilst attempting to batch together some non-batched queries I noticed that **IBatchedQueryable** doesn't expose **ThenBy**/**ThenByDescending** methods.

On the face of it there doesn't appear to be anything preventing this being done in a batched fashion so perhaps these methods were simply forgotten about?

For now I am using a workaround using reflection to grab the inner IMartenQueryable -> casting to IOrderedQueryable to be able to apply subsequent sort criteria.

```
var type = _batchedQueryable.GetType();
var innerField = type.GetField("_inner", BindingFlags.NonPublic | BindingFlags.Instance);
var martenQueryable = innerField!.GetValue(_batchedQueryable) as IMartenQueryable<T>;

if (martenQueryable is IOrderedQueryable<T> orderedMartenQueryable)
{
    innerField.SetValue(_batchedQueryable, orderedMartenQueryable.ThenBy(expression));
}
```

Perhaps an **IOrderedBatchedQueryable** interface could be introduced?

**Comment by jeremydmiller** [comment]
Sounds like a decently straight forward PR. Just an oversight.

**Comment by jeremydmiller** [comment]
And honestly glad just to see someone using batch querying. We've had very few questions about that over the years, but it still seems like something valuable to have.

**Comment by DJBMASTER** [comment]
> And honestly glad just to see someone using batch querying. We've had very few questions about that over the years, but it still seems like something valuable to have.

Yeah - given that postgres doesn't support MARS (news to me since being a SQL Server dev all my life), I had to re-jig a bit of my architecture such that multiple commands aren't processed using the same connection simultaneously. Batching up the commands and executing them at once was an easy change so I'm grateful that marten has this functionality.

**Comment by jeremydmiller** [comment]
It got some improvements in v4 such that the earlier results are usable before the later ones are completely read. Wasn't quite true in v3. So *kind* of like a future query in other tools.

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/pull/2029
