### ISSUE TITLE
Index on a list field generates an incorrect index definition. (v4)

### ISSUE THREAD

**Issue by apereiratl** [JasperFx/marten#2028]
Given a simple class as below:

```
public class Institution
{
    public long Id { get; set; }

    public string Name { get; set; }

    public List<string> EmailDomains { get; set; }
}
```

Index definition

```
this.For<Institution>()
      .Duplicate(x => x.Name)
      .NgramIndex(x => x.Name)

      .Index(x => x.EmailDomains);
```

Gives us the index definition: 

`CREATE INDEX mt_doc_institution_idx_email_domains ON public.mt_doc_institution USING btree ((CAST(data ->> 'EmailDomains' as varchar[])));`

which gives us the error:

```
ERROR:  functions in index expression must be marked IMMUTABLE
SQL state: 42P17
```

The same index in v3 would have been

```
CREATE INDEX IF NOT EXISTS mt_doc_institution_idx_email_domains
    ON public.mt_doc_institution USING btree
    (((data ->> 'EmailDomains'::text)::jsonb) ASC NULLS LAST)
    TABLESPACE pg_default;
```

The duplicate field definition looks correct—however, the rest of the functionality breaks.

I'll take a look at fixing the index generation over the next couple of days.

**Comment by mysticmind** [comment]
This looks like a similar issue as https://github.com/JasperFx/marten/issues/2018

**Comment by jeremydmiller** [comment]
@apereiratl Did that index actually work in v3? Meaning, did Postgresql actually use the index when you wanted it to?
