### ISSUE TITLE
Mechanism for targeting multiple Marten databases in one IHost

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2043]
This is not the same as "database per client", this is when you need to access two or more, semantically different Marten databases within one application.

What we need:

* Some sort of easy `AddMarten()` alternative to register multiple Marten document stores
* Support for running migrations across multiple databases at one time (well underway with Weasel 3.0)
* Some way to resolve the correct database from the underlying DI container that leverages the type system rather than named `IDocumentStore` instances, which aren't completely supported by every DI container anyway

So, here's a couple options that nobody completely like so far:

## Copy EF Core

Just like the way that EF Core let's you make your own subtype of `DbContext`, we could introduce a new abstract class like so:

```csharp
public abstract class MartenContext : IDocumentSession
{
    // There'd maybe be some protected constructors

    protected abstract void OnConfiguring(IConfiguration, IHostEnvironment, StoreOptions);
}
```

then:

```
services.AddMarten<MyMartenContext>();
```

## Custom Interface + a little codegen

In this case, let's say you have an interface like:

```
public interface IMyDatabase : IDocumentSession
{

}

and use:

```
services.AddMarten<IMyDatabase>(opts => {
    // configure the options here to suit
});
```

Behind the scenes, Marten would generate a concrete implementation for `IMyDatabase`, register that as a scoped service like normal, and also register a singleton for `IDocumentStore<IMyDatabase>` so that you could also customize how sessions are opened.

```

## Subclasses of StoreOptions

So if you had a sub class of `StoreOptions` (I was on a project where we did something similar to this), you could do:

```csharp
public static IMartenBuilder AddMarten<T>(Action<T> configure) where T : StoreOptions {}
```

which would give you registrations for:

`IDocumentStore<T> where T : StoreOptions` as a singleton that you would use directly and we don't even bother with
custom `IDocumentSession` types.

**Comment by Peartart** [comment]
For the second option, is it possible to keep going and register `IDocumentSession<T>` based on the same option type?

Either way would be helpful though, looking forward to both this and tenanting by database. :)

**Comment by jeremydmiller** [comment]
@Peartart If we went with `IDocumentStore<T>`, yeah, there'd be an `IDocumentSession<T>` as well.

**Comment by jeremydmiller** [comment]
## Current Concept -- unless someone else has a better idea in the next 24 hours!

```csharp

public interface IMySpecialStore : IDocumentStore {}

IServiceCollection.AddMarten<T>(Action<StoreOptions>) where T : IDocumentStore;
```

**Comment by elexisvenator** [comment]
I like the concept, have a couple of questions (may not be correct place) -

- Will properties like `DatabaseSchemaName` be configurable using `IMySpecialStore`? Asking because when doing tenant-per-schema its possible to pool connections by using the same connection then getting marten to use a different schema once connected.
- What will happen if some tenants share the same connection? Will those tenants act like conjoined tenancy?

**Comment by jeremydmiller** [comment]
@elexisvenator You'd have access to everything available on `StoreOptions`, and that'd still be the primary way you make the configuration. The subtype of `IDocumentStore` is just to be able to retrieve the right one in a type safe, traceable way.

This isn't exactly related to the database per tenant style of multi-tenancy, but I'm wanting to do these two stories together to share database management code. This is not related to conjoined multi-tenancy at all either, this would be for two semantically different databases touched by the same application.

For example, let's say you're a consultant whose client built on the iDesign architectural idea where every service talks to every database:)

YOu *could* use the same connection string and target different schema names, but you'd be able to do dumb things of course. There would be no relationship between the additional stores and the original one.

**Comment by claudioscatoli** [comment]
I was looking around these past few weeks on how to accomplish this.

I came across this [StackOverflow question](https://stackoverflow.com/questions/66315230/connect-to-2-different-martendb-datastores-with-asp-net-core) from exactly 1 year ago.

Might not be useful, but I wanted to put it here nonetheless.
