### ISSUE TITLE
`NullReferenceException` Thrown from `ShardAgent` when Exception Policy Handles Apply Exception

### ISSUE THREAD

**Issue by kluhman** [JasperFx/marten#2074]
I am trying to write an exception policy that retries event application when a failure occurs. However, no matter what policy I write, it doesn't seem to actually save the batch, even when the retry policy successfully recovers from the exception. The exception being written to the logs is

```
fail: Marten.Events.Daemon.IProjectionDaemon[0]
      Failure while trying to process updates for event range Aggregate for Event range of 'Identity: UserIssueCounter:All', 0 to 500, 1 slices for projection shard 'Identity: UserIssueCounter:All'
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Marten.Events.Daemon.ShardAgent.ExecuteBatch(ProjectionUpdateBatch batch)
         at Marten.Events.Daemon.ShardAgent.<>c__DisplayClass32_0.<<processRange>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Marten.Events.Daemon.ProjectionDaemon.TryAction(ActionParameters parameters)
```

I have been able to reproduce this in a simple top-level program. My projection throws an exception on the first few attempts, and then after 2 exceptions, it starts applying the events. Even though the whole batch is processed, the batch is never persisted to the database, and the above exception is logged.

[Program.cs.txt](https://github.com/JasperFx/marten/files/8036758/Program.cs.txt)

**Comment by jeremydmiller** [comment]
No clue. Can you try doing this in a failing test in a pull request? The NRE obviously isn't helpful at all in this case.

**Comment by kluhman** [comment]
@jeremydmiller I did attach the reproducible example I've been using to the issue. I can try to convert this into a failing test in a PR. It's slightly challenging in that the exception is logged and swallowed, then the shard is stopped. So there's not a great failure condition for me to check on
