### ISSUE TITLE
"codegen" command is busted with the new model

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2085]
This is really an issue with LamarCodeGeneration.Commands, but I'll test it here so it's tracked here.

Let's add to ICodeFileCollection and add a Rules property there. Stop expecting DynamicCodeBuilder to be registered.

**Comment by pablopioli** [comment]
In my case, when I follow the "prebuild types" sample using Marten 5 Beta 5  I get this exception.

```
ERROR: System.TypeLoadException: Could not load type 'LamarCodeGeneration.IGeneratesCode' from assembly 'LamarCodeGeneration, Version=0.0.0.0, Culture
=neutral, PublicKeyToken=null'.

```
I assume is the same problem.

**Comment by jeremydmiller** [comment]
Missing type/method exceptions are always an assembly mismatch. You just caught things in flight right now.
