### ISSUE TITLE
Npgsql version

### ISSUE THREAD

**Issue by PeterKneale** [JasperFx/marten#2095]
Hi, I'm finding conflicts between marten and other nuget libraries because of an older NpgSql dependency.

Is it possible to have a release that bumps the dependency up to >= 6.0.0. Happy to do a PR, not sure how much is involved but can dig into it.

ie:
XXXXXXXXX-> AspNetCore.HealthChecks.NpgSql 6.0.1 -> **Npgsql (>= 6.0.0)** 
 XXXXXXXXX-> Marten 4.3.1 -> Weasel.Postgresql 1.3.0 -> **Npgsql (>= 5.0.10 && < 6.0.0).**

**Comment by Hawxy** [comment]
The npgsql 6 upgrade was a breaking change and is available in the latest Maten v5 alphas.
