### ISSUE TITLE
Unit of Work Sort will throw due to a large number no-op delete operations

### ISSUE THREAD

**Issue by Hawxy** [JasperFx/marten#2132]
If you have a large number of inline aggregate projections with create handlers that handle a number of create events via a common interface but return null if they can't handle it/decide not to create the projection, at some point of critical mass you'll start getting this exception:

```cs
System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'Marten.Internal.UnitOfWork+StorageOperationWithDeletionsComparer'.
at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, IComparer`1 comparer)
at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
at System.Collections.Generic.List`1.Sort(IComparer`1 comparer)
at Marten.Internal.UnitOfWork.Sort(StoreOptions options)
at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
```
It starts throwing once the number of no-op delete operations queued up reaches 17 or more, which I believe lines up with .Sort() changing its internal algorithm from an Introspective sort to an Insertion sort.

It's likely related to this change made a while ago to prevent the daemon deadlocking on null operations: https://github.com/JasperFx/marten/pull/1970/files#diff-4204579e8f016af2f1bf28d89ff59d2156051611605b04561ecff8dd59937c60R97

**Comment by jeremydmiller** [comment]
Do you have a suggestion here? I'd go back to the original code you listed, but make sure the daemon is ignoring null storage operations. That or move to a model where you pass in IDocumentOperations with expected callbacks instead so there's never any nulls anyway.

**Comment by jeremydmiller** [comment]
When you say "no-op delete operations", what does that even mean?

**Comment by jeremydmiller** [comment]
I'm going to leave this as "do nothing if the aggregate did not already exist" for now. *Another* mild optimization I will consider later is consolidating the deletes into a kind of delete many command. That would at least eliminate the sort issue.

**Comment by Hawxy** [comment]
> When you say "no-op delete operations", what does that even mean?

I was referring to the original fix that returns a `Storage.DeleteForId` operation despite the aggregate not existing to begin with, therefore an effective no-op. 

> I'm going to leave this as "do nothing if the aggregate did not already exist" for now.

Looks good, thanks for the fix.
