### ISSUE TITLE
Checking version doesn't parameterize tenant Id

### ISSUE THREAD

**Issue by Jordan466** [JasperFx/marten#2150]
Hey guys.

We have a use case where we'd like multiple streams across different tenants to share the same stream Id. For the most part this works, except currently `AppendOptimistic` and `AppendExclusive` don't add the tenant Id as a parameter when checking version, leading to the wrong stream being pulled from the database and errors around unexpected version being thrown.

`Append` doesn't manifest the same issue. So I presume that function is already parameterizing the tenant Id

I've opened the following PR with a proposed change to help support this use case. Let me know what you think.
https://github.com/JasperFx/marten/pull/2149

**Comment by jeremydmiller** [comment]
Closed by #2149
