### ISSUE TITLE
Need a facility to add IInitialData only in testing

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2154]
For 5.1 maybe, just a quick way to register new `iinitialData` for testing that can be done completely outside of and in addition to the main `AddMarten()` or `AddMartenStore<T>()` calls. Would be done with an `IConfigureMarten()` and also by ensuring the MartenActivator is present.

**Comment by oskardudycz** [comment]
Could we do that based on the `Environment`? That sound to me like the easiest option.

**Comment by jeremydmiller** [comment]
You can do that now without any change, sure. I've got this completely done, but not documented in a local branch.

Think about the case where you have the application itself, but you want to use an IInitialData specifically for test data setup. In that case I think it would be very helpful to have a away inside of WebApplicationFactory or other mechanism to say, "oh yeah, and append this testing only IInitialData from the test lib into the Marten setup". That was the use case I wanted here.
