### ISSUE TITLE
Load codegen types from shared assembly?

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#2164]
I have a database that is shared by several web apps, with Marten types defined in a shared project (and thus, a shared assembly).

What I'd like to do is use codegen to pre-generate types once, for the shared project, and then load those types from the shared assembly at runtime. That way I can check the files into source control cleanly.

As it is, I have to pre-generate the types for each web app individually - so I have several sets of the same codegen files, which is not pretty 😄 

I tried setting `StoreOptions.ApplicationAssembly = typeof(SomeSharedType).Assembly`, but Marten fails to find the generated types at runtime, just the same as if I don't set `ApplicationAssembly`.

To try to be clear, what I'd like is a single source of truth for codegen types within a "Core" assembly:

```
┌────────────┐ ┌────────────┐ ┌──────────────┐
│ Web App #1 │ │ Web App #2 │ │ Web App #n.. │
└────┬───────┘ └─────┬──────┘ └──────┬───────┘
     │               │               │
     │               │               │
     │        ┌──────▼───────┐       │
     └───────►│     Core     │◄──────┘
              └──────┬───────┘
                     │
                     │
             ┌───────▼────────┐
             │ Generated Code │
             └────────────────┘
```

Thanks!

**Comment by xevilmaxx** [comment]
Have you tried to use Pre-Build events in Visual Studio (for each of your projects)?
I have similar structure too in my project.
I also noticed that it works with Console but not with Windows Service (Console + Topshelf).

**Comment by jeremydmiller** [comment]
"Works on my box" with master (5.1) --> https://github.com/JasperFx/marten/tree/GH2164

See if your usage was different than what I did. What I did notice was that you had to force the IDE to do a "Clean" and/or "Rebuild" to get it to rebuild the shared library.

**Comment by cocowalla** [comment]
So, my scenario is different because I'm using web apps, which means Marten doing a bunch of stuff with `IHostEnvironment`.

I've stepped through, and here is what happens:

1. `SetApplicationProject` sets `ApplicationAssembly` on an `IHostEnvironment` - specifically, an instance of  `Microsoft.AspNetCore.Hosting.HostingEnvironment`
2. `StoreOptions.ReadHostEnvironment` gets called, but it's passed a _different_ `IHostEnvironment` - specifically, an instance of  `Microsoft.Extensions.Hosting.Internal.HostingEnvironment`. So, it reads `ApplicationName` from a different environment from the one it was set on

It's pretty confusing for me though, as there are both `StoreOptions.ApplicationAssembly` and `IHostEnvironment.ApplicationName` (2x!) getting read and set and overwritten in different places 😕

**Comment by cocowalla** [comment]
FWIW, I have managed to find a workaround for reading types from the correct assembly at runtime. Instead of calling `services.AddMarten` and using `services.SetApplicationProject`, this is working:

```c#
services.AddSingleton<IDocumentStore>(ctx =>
{
    var options = new StoreOptions();
    ...
    options.ApplicationAssembly = typeof(SomeSharedType).Assembly;

    return new DocumentStore(options);
});

services.AddSingleton<ICodeFileCollection>((Func<IServiceProvider, ICodeFileCollection>) (s => (ICodeFileCollection) s.GetRequiredService<IDocumentStore>()));
services.AddSingleton<ICodeFileCollection>((Func<IServiceProvider, ICodeFileCollection>) (s => (ICodeFileCollection) s.GetRequiredService<StoreOptions>()));
```

In this way, the type assembly is set, and doesn't get written by Marten anywhere else.

This won't work for Event Store types, as `StoreOptions.EventGraph` is `internal` (I don't use Event Store 😌

**Comment by jeremydmiller** [comment]
Okay, so that's not really a fix at all and would knock out a lot of other functionality. At this point I'd rather have a real fix on `StoreOptions` itself that would take precedence over anything coming from IHostEnvironment. And yeah, there are other places in the HostBuilder code that add additional HostEnvironment registrations.
