### ISSUE TITLE
`db-patch` is not writing the file (contrary to output)

### ISSUE THREAD

**Issue by Rob89** [JasperFx/marten#2167]
Hey, I see some really odd behaviour with v5 command line tooling for generating database patch files. Despite seeing a message that a file has been written, it never appears in my filesystem. Any pointers on how to figure out what's going on here? I can work around it by manually copying the stuff I need out of the db-dump output so it's not blocking me. I didn't have any issues on v4 so a bit stumped on what might have changed to cause this in the upgrade.

db-patch
Example: dotnet run --project my-project -- db-patch 20220406_AddMeasures.sql

Output:

```
Building...
Searching 'LamarCodeGeneration.Commands, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' for commands
Searching 'Weasel.CommandLine, Version=5.2.0.0, Culture=neutral, PublicKeyToken=null' for commands
Searching 'Marten.CommandLine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' for commands
Wrote migration file to /Users/me/Code/strategy/my-project/20220406_AddMeasures.sql
```

**However, no file is actually written to disk.**

db-apply
Example: dotnet run --project my-project -- db-apply

Outputs the expected DDL commands*

The schema objects are created in the database.

*It also erroneously creates tables for SelfAggregates registered with Live lifecycle. I only do that so the codegen command generates the AggregationRuntimeXyZclasses but this could be a mistake on my part.

db-dump
Example: dotnet run --project my-project -- db-dump ./dump.sql

Outputs all the DDL correctly into the specified file*

*It also erroneously creates tables for SelfAggregates registered with Live lifecycle. I only do that so the codegen command generates the AggregationRuntimeXyZclasses but this could be a mistake on my part.

Note that unlike db-patch, if I do not specify ./ as part of the file I see:

```
Writing SQL file to dump.sql

ERROR: System.ArgumentException: Path cannot be the empty string or all whitespace. (Parameter 'path')
   at System.IO.Directory.CreateDirectory(String path)
   at Weasel.Core.Migrations.DatabaseBase`1.WriteCreationScriptToFile(String filename)
   at Weasel.CommandLine.DumpCommand.Execute(DumpInput input)
   at Oakton.CommandExecutor.execute(CommandRun run)
```

Marten and Marten.CommandLine are at 5.0.0, Weasel all at 5.2.0 and Oakton at 4.1.0

**Comment by Rob89** [comment]
`db-patch` works perfectly with an absolute/rooted path. When given a relative path, it outputs the file in my `bin/Debug/net6.0` directory.

**Comment by jeremydmiller** [comment]
Fixed by a weasel update
