### ISSUE TITLE
Marten is leaving the .NET Foundation

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#2183]
We joined .NET Foundation in March 2020 based on the [benefits](https://dotnetfoundation.org/projects/why-join) outlined and the possible upside it would bring to the project to increase adoption, visibility and engagement with the larger .NET community. We also hoped that the .NET Foundation would help us make our work more sustainable and increase collaboration with other maintainers. Unfortunately, we haven't seen any tangible benefits of being part of the foundation after two years.

.NET Foundation didn’t offer us anything more than what we were already getting for free from GitHub and Azure DevOps.

Also, an [event](https://github.com/dotnet-foundation/Home/discussions/39) with another .NET Foundation project eroded trust in the foundation and raised a wake-up call for us to assess our engagement going forward.

The maintainers discussed this matter, and everyone collectively agreed that it is best for the project to leave the .NET Foundation.

We reached out to .NET Foundation on 28th Oct 2021 [requesting the procedure for leaving](https://github.com/dotnet-foundation/Home/discussions/68). .NET Foundation didn't have a defined off-boarding process, and after persistent follow up, a draft was shared [here](https://github.com/dotnet-foundation/Home/discussions/68#discussioncomment-2168432). We have sent an official email to the foundation dated 8th Feb 2022 that we intend to leave the foundation. 

**After a few months, we finally managed to get to the final conclusion, and the agreed intent with .NET Foundation to leave by the end of April 2022.**

All said, please don’t worry. We are committed to enhancing, maintaining and supporting Marten, as we have been doing since 2015. Nothing changes in that regard. We released v4 and v5, which are big milestones and v5 providing full-fledged .NET 6 support. In 2021 alone, we have done around 35 releases, this should give you a good indicator of the project's health and our commitment to the project. We have strong plans for the future and will continue to work with our users and the whole .NET Community.

**Comment by houstonhaynes** [comment]
Thanks for the transparency - and also - a big thank-you to all of the work that contributors put into Marten.

**Comment by mysticmind** [comment]
This notice has been posted for 3+ months now closing this.
