### ISSUE TITLE
Use IDocumentStore.BulkInsert inside a TransactionScope?

### ISSUE THREAD

**Issue by youqingz** [JasperFx/marten#2184]
### Discussed in https://github.com/JasperFx/marten/discussions/2148

<div type='discussions-op-text'>

<sup>Originally posted by **youqingz** March 30, 2022</sup>
I can use IDocumentSession to enlist an ambient transaction inside a TransactionScope, but I also would like to use IDocumentStore.BulkInsert for some of the operations for performance reasons, but seems like it is not supported at the moment?

</div>

**Comment by jeremydmiller** [comment]
Closed by #2303
