### ISSUE TITLE
IQueryable extensions to retrieve the raw JSON 

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#219]
In many cases in web apps, you wouldn't want to bother deserializing the Json just to immediately serialize it back out to Json in the HTTP response. What if you could just skip that and get the raw Json? Even if there's a Select() in there.

- [ ] FirstJson() : string
- [ ] FirstOrDefaultJson() : string
- [ ] SingleJson() : string
- [ ] SingleOrDefaultJson() : string
- [ ] ToListJson() : string // Think this would wrap it in "[ ]"

- [ ] WriteJsonResults(Stream) // maybe a more efficient way to do this

and async of all of the above.

**Comment by phillip-haydon** [comment]
I love the idea of `ToListJson()` but my request is that at bare minimum if the result is empty, that the list returns `[]` to simulate an empty array, because `.ToList()` always creates atleast an empty list. It shouldn't be empty or null.

**Comment by jeremydmiller** [comment]
@phillip-haydon I definitely agree.

**Comment by nieve** [comment]
I wouldn't mind giving this a go- unless you've already got this.

**Comment by jeremydmiller** [comment]
Go @nieve! My next Marten trick is the Includes() feature.

**Comment by nieve** [comment]
So, following from Gitter- should I focus on FirstOrDefault and ToList and then we'll see about the Single/OrDefault/First?

**Comment by jeremydmiller** [comment]
I think that's fair. It should be rinse and repeat after those first tow. But a lot of rinse & repeat:(

**Comment by nieve** [comment]
I've got these left:
SingleJson()
SingleJsonAsync()
SingleOrDefaultJson()
SingleOrDefaultJsonAsync()
WriteJsonResults(Stream)
WriteJsonResultsAsync(Stream)

**Comment by jeremydmiller** [comment]
Gonna call this one closed via https://github.com/JasperFx/marten/pull/229
