### ISSUE TITLE
IDocumentSessionListener is no longer notified for projection document changes

### ISSUE THREAD

**Issue by vishnugude** [JasperFx/marten#2190]
We upgraded from V3 to V5. `AfterCommitAsync` in `IDocumentSessionListener` use to get notified when a projection changed and committed. When we upgrade to V5 only changes to Event Store are getting notified.  We want to know when a projection gets updated to send updated data to downstream.

```
public Task AfterCommitAsync(IDocumentSession session, IChangeSet commit, CancellationToken token)
{
    try
    {
        foreach (var change in commit.Updated)
        {
            Console.WriteLine("Projection Updated");
            // Get Updated projection from change
        }
        foreach (var change in commit.Inserted)
        {
            Console.WriteLine("New Projection Inserted");
            // Get Inserted Projection from change
        }
   }
    catch (Exception ex)
    {
        Console.WriteLine("Exception");
    }

    return Task.CompletedTask;
}
```

We are using self aggregate projections.
`options.Projections.SelfAggregate<Projection>(ProjectionLifecycle.Async);`

**Comment by mysticmind** [comment]
@vishnugude please change `options.Projections.SelfAggregate<Projection>(ProjectionLifecycle.Async);` to `options.Projections.SelfAggregate<Projection>(ProjectionLifecycle.Inline);` and let us know your results?

Note that `ProjectionLifecycle.Async` is used only when you use async daemon.

**Comment by vishnugude** [comment]
> @vishnugude please change `options.Projections.SelfAggregate<Projection>(ProjectionLifecycle.Async);` to `options.Projections.SelfAggregate<Projection>(ProjectionLifecycle.Inline);` and let us know your results?
> 
> Note that `ProjectionLifecycle.Async` is used only when you use async daemon.

Yes we are using async daemon

**Comment by jeremydmiller** [comment]
For some context for @oskardudycz & @mysticmind, the document session used to apply projection updates in the daemon is an alternative version that probably doesn't have any of the session listeners attached. It's maybe a quick win to just do that, but I'd rather make "notify when projected documents are changed" a first class, explicit feature whenever we get around to doing subscriptions

**Comment by jeremydmiller** [comment]
It's going to come out just a touch different. I'll add docs for this as part of 5.3
