### ISSUE TITLE
Define indexes by document type in code

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/Marten#22]
This is going to need a lot more thought. What I'd like is a way to define Marten index's in code for common queries that may:

1. Create extra fields and matching db indexes in the document tables to duplicate information in the son payloads specifically to make querying more performant

1. Somehow directs the Linq query support to use these extra fields
1. Adds something to the DB to duplicate that data upon inserts or updates

**Comment by jeremydmiller** [comment]
This is done *except* for creating db indexes. Not sure or not if we wanna try that in code or leave it to pure DDL

**Comment by jeremydmiller** [comment]
Done!

**Comment by tim-cools** [comment]
@jeremydmiller any special reason that you use an extra field instead of GIN indexes? gin indexes support indexing on properties of the json content (haven't checked the code yet)

**Comment by jeremydmiller** [comment]
@tim-cools I added another option for adding a gin index against the actual Json field at the end of yesterday. I'm collecting some performance numbers, but right now I can tell you that the btree index on a duplicated field is still a faster search than the containment operator + gin index. The gin + containment operator is clearly faster than the simplistic json operator queries. My next trick is trying to get an idea of the performance of doing inserts with and without gin indexes

**Comment by mdissel** [comment]
Why don't you add the gin + containment index by default (if it doesn't cost too much performance)? If you search for a field not defined as searchfield it will not start a table scan...

**Comment by jeremydmiller** [comment]
We can *talk* about doing that. It does have some impact on insert performance and I don't know how much on storage:

Newtonsoft.Json

Index	Bulk Insert	Batch Update	Command per Document
No Index	62	149	244
Duplicated Field w/ Index	53	152	254
Gin Index on Json	96	186	300
Jil

Index	Bulk Insert	Batch Update	Command per Document
No Index	47	134	224
Duplicated Field w/ Index	57	151	245
Gin Index on Json	79	180	270


Let me write up that blog post next week then we talk about this some more?
