### ISSUE TITLE
Existing transaction scope is ignored for when using EnlistAmbiantTransactionScope

### ISSUE THREAD

**Issue by jkrieg** [JasperFx/marten#2210]
## Scenario
Creating a document session through a `ISessionFactory` using the following options
```csharp
      protected virtual SessionOptions GetSessionOptions()
        {
            var options = SessionOptions.ForConnection(connection).EnlistInAmbientTransactionScope();
            options.TenantId = tenantId;
            options.IsolationLevel = IsolationLevel.ReadCommitted;
            options.Tracking = DocumentTracking.None;

            return options;
        }
```
In this scenario, we establish a connection through a transaction scope before reaching the above code as a transaction behavior in our pipeline as follows
```csharp
var transaction = new TransactionScope(
                activity.TransactionBehavior,
                new TransactionOptions
                {
                    Timeout = activity.TransactionTimeout,
                    IsolationLevel = activity.TransactionIsolation,
                },
                TransactionScopeAsyncFlowOption.Enabled);

            using (transaction)
            {
                /* READ
                 * We open the connection here to ensure it enlists in the transaction scope.
                 * If an error occurs, that means the connection is already open and the calling
                 * code probably has a bug or something, or perhaps the code is sending through
                 * the mediator more than once. If the latter is the case, we need to ask why.
                 * If there is a valid reason for it, then perhaps this code needs to be re-worked
                 * a bit to allow for activities to be sent through the mediator more than once,
                 * but that should be a rare exception.
                 * */
                connection.Open();

                var response = await next().ConfigureAwait(false);

                transaction.Complete();

                return response;
            }
```
## Problem
We establish that the transaction is ambient, and our connection is established in a transaction scope before assigning the connection to the session, but there is still a `BeginTransaction` being called when calling `IDocumentSession.SaveChangesAsync()` throwing the following error
```terminal
System.InvalidOperationException: A transaction is already in progress; nested/concurrent transactions aren't supported.
   at Npgsql.NpgsqlConnection.BeginTransaction(IsolationLevel level, Boolean async, CancellationToken cancellationToken)
   at Marten.Internal.Sessions.MartenControlledConnectionTransaction.BeginTransactionAsync(CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
```
## When did this start happening
Marten 5.x
Previously working in Marten 4.x
## Current Version
Marten 5.3.0
## Additional note
The caller for `SaveChangesAsync` is coming from an `IAmTransactional`

**Comment by jeremydmiller** [comment]
@jkrieg Can I ask, why are you doing this?

**Comment by willhausman** [comment]
@jeremydmiller the pipeline is making use of the same transaction and connection for all db operations in a single API request, so everything can be committed/rolled back together.  In this particular case, it means both Marten and an outbox pattern for events leaving the application.  Regardless, it seems wrong that we can create session options with a connection, enlist in an ambient transaction scope, and still wind up using `MartenControlledConnectionTransaction` when calling SaveChanges.  If that class doesn't actually mean Marten is controlling the connection and/or transaction (despite `OwnsConnection` and `OwnsTransactionLifecycle` both being false), I concede that I don't understand its actual purpose.

**Comment by jeremydmiller** [comment]
@willhausman Gotcha. How are you doing the outbox pattern
 in this case? And I will have an implementation of the outbox out soon-ish that still allows you to let Marten govern the connection, so now you've got me curious.
