### ISSUE TITLE
Support for expressions (e.g. null-coalescing) in order by clauses

### ISSUE THREAD

**Issue by kseitz10** [JasperFx/marten#2213]
Trying to sort results with an expression that accesses more than a single document property (e.g. using a null-coalescing operator or conditional operator) results in an `order by` clause that contains only a chain of JSON field accessors.

For example, if I have the following document, where both `PropertyA` and `PropertyB` are nullable and of the same type:

```
{
    "PropertyA": {
        "SubProperty": "Value1"
    },
    "PropertyB": {
        "SubProperty": "Value2"
    },
}
```
and I try to order it within `IQuerySession`:

```
someIQueryableOfDocument.OrderBy(x => (x.PropertyA ?? x.PropertyB).SubProperty)
```

it produces the following:

```
order by d.data -> 'PropertyB' -> 'SubProperty' -> 'PropertyA' ->> 'SubProperty'
```

The result is similar if you try to introduce a conditional/ternary operator in lieu of the null-coalescing operator.

I'm guessing this is a known limitation of how the order by clause is composed, but it would be nice if this were supported. Or if Marten would throw for this type of query if it isn't supported.

Using v5.3.0.

**Edit:** I do apologize for any tunnel vision with how this issue is named or worded in the description, since I'm mostly focused on one use case / expression type rather than something more holistic. I also see a PR to "support raw SQL projections" which could maybe be of help, but handling expression directly seems better.

**Comment by jeremydmiller** [comment]
@kseitz10 Sorry, this isn't likely going to happen. You've got a couple options:

* There's a feature to supply raw SQL to just an OrderBy()
* You can make a read-only, calculated property for the fallback that would be persisted to JSON and available for Linq queries

I'm of course happy to take a PR if you want to dive into the Linq provider, but I think an explanatory exception is the most likely thing here.

**Comment by kseitz10** [comment]
Thanks for the response. I did end up going with the calculated property. Having an exception thrown for this unsupported case sounds just fine, given that the calculated property was relatively painless.
