### ISSUE TITLE
[DuplicateField] and UTC Date Issues Failing

### ISSUE THREAD

**Issue by RickStrahl** [JasperFx/marten#2215]
I have a `[DuplicateField]` set up to allow searching by a date.

```cs
[DuplicateField(PgType = "timestamptz")]
public DateTime InvoiceDate { get; set; } = DateTime.UtcNow;
```

But when I update with the auto-filled value I get this error from the SQL driver.

>Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone', consider using 'timestamp with time zone'. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.

![image](https://user-images.githubusercontent.com/1374013/167493700-9139ad9f-5953-4816-aa3b-c277da640fbe.png)

Checked the DB to make sure that the field is indeed created as a `timestamptz` and that looks fine.

If I assign `DateTime.Now` there's no problem - only if use `DateTime.UtcNow` which base don the error message makes sense. What else than a `timestamptz` could PG be looking for?

The error message points at a workaround, but I'd rather not mess with db settings when it looks like this 

Any ideas why PostGres is not happy with the update here?

**Comment by jeremydmiller** [comment]
@RickStrahl It's a new Npgsql 6 behavior which Shay says is also ripping up the EF Core + Postgresql world. Can you move to using DateTimeOffset instead? That's the workaround for this.

I think the best "fix" we'll be able to do is just an explanatory exception message

**Comment by jeremydmiller** [comment]
Duplicate with #2198

**Comment by RickStrahl** [comment]
Thanks.

I tried using a DateTimeOffset:

```cs
[DuplicateField]
public DateTimeOffset InvoiceDate { get; set; } = DateTime.UtcNow;
```

but that also fails with a similar failure:

>  Cannot write DateTimeOffset with Offset=-07:00:00 to PostgreSQL type 'timestamp with time zone', only offset 0 (UTC) is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.

The only thing that seems to work is to force the legacy behavior. Either `DateTime` or `DateTimeOffset` seem to have the same behavior and require:

```cs
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior",EnableLegacyTimestampBehavior);
```

Not a big deal, just something that's non-obvious next time I start a new project :-)
