### ISSUE TITLE
First class support for automatically setting the current stream version on projected aggregates

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2233]
For the purposes of doing optimistic concurrency checks between clients and Marten, it would be very helpful if there was an automatic way to get the current version of a stream (or the latest event sequence id of a cross stream aggregate) when projecting events.

What I'd like to propose is to build something into the `AggregateProjection/ViewProjection/CrossStreamAggregateProjection` family that will set either the latest stream version on a projected document in the case of `AggregateProjection`, or the latest sequence number for any kind of cross-stream aggregation.

As to how -- and keep in mind I'm tired as I jot this down -- here's a couple possibilities:

1. A well known naming convention like our `id/Id` field/property is the identity of a document, but in this case a prop named `Version : int/long` would be assumed to be the stream/event table version. This would of course come with `[Version]` attributes to overwrite that
2. Make folks use the `[Version]` attribute explicitly on aggregate types. That's not idiomatic Marten, but we're brainstorming here!
3. Make it declared on anything that inherits from `AggregateProjection` like so:

```
    public class TicketProjection: AggregateProjection<Ticket>
    {
        public TicketProjection()
        {
            Lifecycle = ProjectionLifecycle.Async;

            // THIS WOULD BE NEW, AND COULD BE AN INTERNAL PROP FOR FOLKS WHO WASTE TOO MUCH TIME
            // WORRYING ABOUT THINGS THAT DON'T REALLY MATTER (*COUGH* DDD FOLKS *COUGH*)
            Version(x => x.Version);
        }

        public Ticket Create(TicketCreated created) =>
            new() { Id = created.TicketId, Name = created.Name };

        public void Apply(Ticket ticket, TicketAssigned assigned, IQuerySession session) {
            ticket.User = session.Load<User>(assigned.UserId);
        }

    }

    public class Ticket
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public User User { get; set; }
        
        public int Version { get; set; }
    }
```

4. Have a marker interface like so:

```
public interface IVersionedAggregate
{
    // Would anybody be crazy enough to use an event stream where the version had to be a long? Probably
    int Version {get;set;}
}
```

Number 4 is the very easiest thing to do, but I hate having to make interfaces like this mandatory. Guess it's just opt in behavior.

**Comment by oskardudycz** [comment]
If that also works for `AggregateStream`, then I'd be more than happy as I was asking for that for a few years 😅 My vote is for number 1, maybe 3. 

You know that I hate attributes, so I'd prefer not to make them mandatory (optional is fine). Same for marker interface.

Regarding the stream version being long, then, unfortunately, some people do such crazy stuff; however, I'd prefer them to come to us with the overflowing error, so they could get some help 😎

**Comment by ericgreenmix** [comment]
Really like this. My only issue with number 1 would be any existing projections that use a `Version` property already for other purposes. That is why number 3 seems cleaner to me
