### ISSUE TITLE
Short hand method to fetch a projected aggregate with exclusive or optimistic locking semantics

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2234]
Follow on to #2233 

When you're using CQRS to handle a command against an aggregate, you generally want to do these things:

* Fetch the latest version of the aggregate itself, which can be either "live" or let's say inline/async projected
* Evaluate the command, which will kick out 0 to many events that should be appended to the event stream
* Append the events with optimistic concurrency checks on the expected version of the aggregate upon completion

And now, let's consider a couple variations:
* I might want to use the append "exclusive" locking in Marten
* I might already have the starting version
* I might be performing a longish operation, and it would be good enough to have the aggregate version just before starting to execute the command

## Goal 

*Have a single API call* on `IEventStore` to fetch an aggregate, automagically know whether it's Live or persisted, and deal with all the mechanics of opting into optimistic concurrency and/or exclusive locking with *one, batched round trip* to the database.

I'd ideally like to have this in 5.4, selfishly for my That Conference talk. Before going into ideas about syntax, I'd at least like to talk over the concept of doing this.

**Comment by oskardudycz** [comment]
I like that idea. This will be super helpful.

I think that it'd be also good to provide the expected version. That's what I normally do, as it gives me the trust that I'm making decisions based on the expected state of my stream. Using the loaded method in the method call guarantees only the case that someone appended something in the meantime while running the business logic. It may be fine for many cases, but not for all. This can be an additional param.

It'd be great if we could pass a function. Tho here, we need to consider that this function can take:
- aggregate + command - when stream already exists,
- no-aggregate/default + command - when stream didn't exist.

@thinkbeforecoding described that well as Decider pattern, more on that:
- https://thinkbeforecoding.com/post/2021/12/17/functional-event-sourcing-decider
- https://www.youtube.com/watch?v=whFfzQfdJZg

@bartelink also described it in his Equinox docs: https://github.com/jet/equinox#what-is-a-decider-how-does-the-equinox-type-decider-relate-to-j%C3%A9r%C3%A9mies-concept-of-one-pray-rmaziarka

It's already becoming an established pattern in the Event Sourcing community. We don't need to go fully into that from the first version and provide at least a subset of permutations, but it'd be good not to close any path on expanding that to getting the full support.

It'd be also good to have also IQuerySession to load additional data.

Some inspirations on how I'm doing that currently:
- https://github.com/oskardudycz/EventSourcing.NetCore/blob/main/Sample/ECommerce/Carts/Carts/ShoppingCarts/AddingProduct/AddProduct.cs#L47, https://github.com/oskardudycz/EventSourcing.NetCore/blob/main/Core.Marten/Repository/RepositoryExtensions.cs#L20 (ignoring the repository pattern),
- and more functional way: https://github.com/oskardudycz/EventSourcing.NetCore/blob/main/Sample/EventStoreDB/Simple/ECommerce/ShoppingCarts/AddingProductItem/AddProductItemToShoppingCart.cs#L21, https://github.com/oskardudycz/EventSourcing.NetCore/blob/main/Sample/EventStoreDB/Simple/ECommerce.Core/EventStoreDB/EventStoreDBExtensions.cs#L36, 
-

**Comment by thinkbeforecoding** [comment]
Optimistic locking remove the need for sharding, while guaranteeing consistency.
If operations are costly, you can still load missing events proactively to reduce the risk of doing it twice.

**Comment by bartelink** [comment]
Yes, the signatures and impl in https://github.com/jet/equinox/blob/master/src/Equinox/Decider.fs are based on exactly this pattern (the other bit it covers is dealing with doing another lap around the loop in the case where the OCC check shows a conflict - in that case you want to catch up to the updated state by folding in the conflicting events, and let the decider reconsider against that state).

Starting options are defined via [`LoadOption`](https://github.com/jet/equinox/blob/master/src/Equinox/Decider.fs#L135)

Inspecting the stream state before you decide is via [`ISyncState`](https://github.com/jet/equinox/blob/master/src/Equinox/Decider.fs#L148) (the default/common case is that the 'state is enough, but in some cases you might want to do a version check etc)

**Comment by jeremydmiller** [comment]
@oskardudycz So you're proposing a variation with continuation passing style where maybe Marten does some limited retries on concurrency violations? I'll buy that. 

So I think I see these flavors of it:

* A flavor where you explicitly pass in the starting version. In this case I think we can have Marten throw a concurrency exception quickly
* A flavor where you use optimistic concurrency starting from the point where you first access the event data
* A flavor where you use exclusive locking on the stream 

And for all three of the flavors above, 1 option where you pass in a function to actually process things and append resulting events *and* call `SaveChanges()/SaveChangesAsync()`. This first option could do some limited retries. A 2nd option with no continuation passing style that leaves the user responsible for everything else. 

I want the 2nd option for the Jasper + Marten combination where Jasper middleware will take care of most of the work w/o the need for the extra object allocations from the inline functions and with Jasper's more robust error handling options.

**Comment by jeremydmiller** [comment]
@thinkbeforecoding 

> Optimistic locking remove the need for sharding, while guaranteeing consistency. If operations are costly, you can still load missing events proactively to reduce the risk of doing it twice.

But also, because we're built on top of Postgresql, we also have the option to attain an exclusive write lock on a single stream as part of this. That's an option that probably isn't possible with most NoSQL stores and definitely not with least common denominator abstractions over the actual event store.

**Comment by oskardudycz** [comment]
> @oskardudycz So you're proposing a variation with continuation passing style where maybe Marten does some limited retries on concurrency violations? I'll buy that.

I'm also fine with just getting the information that the expected version is different and letting users decide if they want to do retries. So similar to the samples I linked. Typically if I provide the expected version, then I mean to fail if there's other, as it means that I might need to reevaluate my decision and check invariants again (e.g. I'm trying to update hotel guest stay, but optimistic concurrency exception may mean that guest already checked out, and it's too late). So I'm more interested in accuracy rather than automatic retries.

Automatic retries (for me) are a good solution where optimistic concurrency is too optimistic, so we're getting too many concurrency failures than we initially expected. That's, of course, also useful.

> And for all three of the flavors above, 1 option where you pass in a function to actually process things and append resulting events and call SaveChanges()/SaveChangesAsync()

That makes sense. Just to double-check: appending events and SaveChanges, will happen behind the scenes in the newly added method we're discussing? So the method will return a list of events, right?

**Comment by jeremydmiller** [comment]
@oskardudycz Yes to both questions, but the automatic retries would be crude from a combination of wanting to do this in one single day plus really leaning on the Jasper + Marten combo for much more robust error handling.

"That makes sense. Just to double-check: appending events and SaveChanges, will happen behind the scenes in the newly added method we're discussing? So the method will return a list of events, right?" -- so yes, but I'm not 100% sold on that. We'd need a good method name to communicate the functionality.

I don't intend to depend on the bigger method for Jasper + Marten. In that case I want Jasper middleware and Jasper's command error handling to deal with retries Append() & SaveChangesAsync().

**Comment by jeremydmiller** [comment]
## Test Cases for FetchForWriting

- [ ] Conjoined tenancy of all fetch
- [ ] Not conjoined tenancy of all fetch
- [ ] FetchForWriting with initial version, already changed on server, fail fast
- [ ] Guid stream identity
- [ ] string stream identity
- [ ] Aggregate stream already exists
- [ ] Aggregate stream does not already exist
- [ ] Can add events happy path
- [ ] Can add events with optimistic version violation
