### ISSUE TITLE
Marten v5.3.1 drops indexes NOT prefixed with "mt_"

### ISSUE THREAD

**Issue by Powerz** [JasperFx/marten#2236]
1. As far as I understand, Marten is supposed to ignore indexes not prefixed with `mt_`.
2. It also ignores the fact that `CreateOrUpdate` doesn't imply DROP and deletes indexes anyway.

```
StoreOptions.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
```

**Comment by jeremydmiller** [comment]
I'm pretty sure that's documented, and yes. There's a PR going into Marten 5.4 in the next day or two that gives you the ability to tell Marten to ignore indexes that aren't under its control. 

Or you define your indexes through Marten itself. 

And maybe chill out just a little bit with the emojis please?

**Comment by Powerz** [comment]
Hi @jeremydmiller , you're absolutely right, it is [documented](https://martendb.io/documents/indexing/):
<img width="420" alt="image" src="https://user-images.githubusercontent.com/184072/169873808-9e7431ff-e886-4f88-a7a1-964ce51f18cc.png">

My apologies for emojis, just wanted to highlight the disturbing fact that Marten removes things it was supposed to ignore, which, in turn, may lead to awkward situations on production.

**Comment by jeremydmiller** [comment]
@Powerz That change came in V4 btw. We did a *lot* in V4 to enhance the change detection

**Comment by Powerz** [comment]
@jeremydmiller, anyway, I'm looking forward to v5.4 where this will be addressed in one way or another. And thank you for maintaining the project 👍

**Comment by jeremydmiller** [comment]
Got Weasel updated locally, will be pushed tomorrow.
