### ISSUE TITLE
Include and QueryStatistics, TotalResults incorrect

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#2243]
TotalResults is returned as the same value as the number of results in the page, rather than the total results overall.

I've modified the other bug i submitted the other day to highlight the issue:

` public async Task include_to_list_using_inner_join_and_paging()
        {

            var user1 = new User();
            var user2 = new User();

            var issue1 = new Issue { AssigneeId = user1.Id, Title = "1.Garage Door is busted" };
            var issue2 = new Issue { AssigneeId = user2.Id, Title = "aaa. Garage Door is busted" };
            var issue3 = new Issue { AssigneeId = user2.Id, Title = "3. Garage Door is busted" };
            var issue4 = new Issue { AssigneeId = null, Title = "4. Garage Door is busted" };

            theSession.Store(user1, user2);
            theSession.Store(issue1, issue2, issue3, issue4);
            await theSession.SaveChangesAsync();

            await using var query = theStore.QuerySession();
            query.Logger = new TestOutputMartenLogger(_output);
            var list = new List<User>();

            QueryStatistics stats;
            var issues = await query.Query<Issue>()
                .Stats(out stats)
                .Include<User>(x => x.AssigneeId, list)
                .Where(x => x.AssigneeId.HasValue)
                .OrderBy(x => x.Title)
                .Take(1)
                .ToListAsync();

            issues.Count().ShouldBe(1);
            list.Count.ShouldBe(1);
            stats.TotalResults.ShouldBe(3);
        }`

**Comment by jeremydmiller** [comment]
@phinett I started to look at all the Include + Skip + Take problems today, and it's a bit more complexity than I can deal with today. I think this won't hit until at least end of next week. I might try to do a bigger set of work on the Linq provider over the next week.
