### ISSUE TITLE
Duplicate key value violates unique constraint "pkey_mt_events_seq_id" exception on Tombstone events with a seq_id of "0"

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#2289]
`TryCreateTombstoneBatch` depends on the `session.WorkTracker.Streams` events having the `Sequence` set on it.
```
var tombstones = session.WorkTracker.Streams
    .SelectMany(x => x.Events)
    .Select(x => new Event<Tombstone>(tombstone)
    {
        Sequence = x.Sequence,
        ...
```

When `EventStreamUnexpectedMaxEventIdException` is thrown during `PrepareEvents` on the `StreamAction`, that happens before the Stream events are iterated and the `sequences` are dequeued. That means that sequence never gets set on the events, resulting in the tombstone event pulling `0` as the sequence id for it. As soon as this happens once, and the events table has that "0" seq_id in it, it will continuously throw the duplicate key constraint violation error when this scenario is hit.

**Comment by jeremydmiller** [comment]
Fixed by #2290
