### ISSUE TITLE
EventStore having Create() method and ctor on SelfAggregate, Create always takes precedence when projecting

### ISSUE THREAD

**Issue by ngoov** [JasperFx/marten#2295]
I have a class:

```
public sealed class User : MartenEventSourcedAggregate<long>
{
    private User()
    {
        Handles<UserCreated>(Apply);
    }

    private User(long id, string userName, string emailAddress) : this()
    {
        ApplyChange(new UserCreated(id, userName, emailAddress));
    }
    
    public static User Create(long id, string userName, string emailAddress)
        => new(id, userName, emailAddress);
    ...
}
```

With the Marten config set as SelfAggregate
`services.AddMarten(options => options.Projections.SelfAggregate<User>(ProjectionLifecycle.Inline));`

When running this, I get the following error:
```
Marten.Exceptions.InvalidProjectionException: Projection Marten.Events.Aggregation.SingleStreamAggregation<MartenTesting.Domain.Users.User> has validation errors:
Create(long, string, string) : User
 - No event type can be determined. The argument for the event should be named '@event'
```

This is because the Create() method is the convention for the [SelfAggregate](https://martendb.io/events/projections/aggregate-projections.html#self-aggregates).
Changing the method name to something like CreateUser() solves this issue and Marten uses the parameterless ctor.

I would like to be able to choose the precedence or only way of the projection creation by Marten between Constructor or CreateMethod. 
So I would suggest an enum like:
```
public enum ProjectionCreation { // or ProjectionCreationPrecedence
    Constructor,
    CreateMethod
}
```
that is used on all the places where the specific way of projection creation is called.

**Comment by jeremydmiller** [comment]
@ngoov Just decorate your Create() method with `[MartenIgnore]`. You're conflicting with Marten naming conventions, and that's the way to get around that.

Why are you doing it that way btw? That looks a little high ceremony. What does the base type do?

**Comment by ngoov** [comment]
Hey @jeremydmiller, thanks for the answer!

This indeed solves the issue. I did not know this attribute could be used for that too.
However, adding this to all my classes when I'm following my own conventions, so not using the naming conventions of Marten anywhere, seems a bit repetitive. Is there also a way to disable the naming conventions and just use the default empty ctor for any or all documents using the fluent builder? 
Something like `services.AddMarten(options => options.Policies.ForAllDocuments(m => m.UseNamingConventions = false))`?

To get to your question, it indeed doesn't make much sense to use a factory method is a small class like this used like this. I just do it because of my own convention of using the factory method for aggregates everywhere, for consistency. It's useful for more complex classes and also to return validation errors if needed. It has nothing to do with the base class however.
Just for the record, my base class is based on one for Nick Chamberlain https://buildplease.com/pages/fpc-9/.

```
public interface IMartenAggregate
{
    IReadOnlyList<IDomainEvent> UncommittedEvents { get; }
    string AggregateId { get; }
    long Version { get; }
    void MarkEventsAsCommitted();
}

public abstract class MartenEventSourcedAggregate<TKey> : Entity<TKey>, IMartenAggregate
{
    [JsonIgnore]
    private readonly Dictionary<Type, Action<IDomainEvent>> _handlers = new();
    
    [JsonIgnore]
    private readonly Queue<IDomainEvent> _uncommittedEvents = new();
    [JsonIgnore]
    public IReadOnlyList<IDomainEvent> UncommittedEvents => _uncommittedEvents.ToList();

    [Identity]
    public virtual string AggregateId
    {
        get => Id!.ToString()!;
        // ReSharper disable once ValueParameterNotUsed
        set {}
    }

    public long Version { get; private set; }

    public void MarkEventsAsCommitted()
    {
        _uncommittedEvents.Clear();
    }

    protected void Handles<TEvent>(Action<TEvent> handler)
        where TEvent : IDomainEvent
    {
        _handlers.Add(typeof(TEvent), @event => handler((TEvent)@event));
    }

    protected void ApplyChange(IDomainEvent domainEventBase)
    {
        ApplyChangeInternal(domainEventBase, () => _uncommittedEvents.Enqueue(domainEventBase));
    }

    private void ApplyChangeInternal(IDomainEvent domainEventBase, Action? addNewEvent = default)
    {
        Version++;

        if (_handlers.ContainsKey(domainEventBase.GetType()))
        {
            _handlers[domainEventBase.GetType()].Invoke(domainEventBase);
        }

        addNewEvent?.Invoke();
    }
}
```

**Comment by jeremydmiller** [comment]
@ngoov 

"However, adding this to all my classes when I'm following my own conventions, so not using the naming conventions of Marten anywhere, seems a bit repetitive. Is there also a way to disable the naming conventions and just use the default empty ctor for any or all documents using the fluent builder?
Something like services.AddMarten(options => options.Policies.ForAllDocuments(m => m.UseNamingConventions = false))?"

I'm not enthusiastic about adding customized naming conventions, sorry. What we *could* do is teach Marten to ignore any `Create()` method that has primitive inputs. I'd accept a PR for that. 

I'm closing this for now.

**Comment by ngoov** [comment]
> I'm not enthusiastic about adding customized naming conventions, sorry. What we could do is teach Marten to ignore any Create() method that has primitive inputs. I'd accept a PR for that.

Sure no problem, I get that, was just doing a suggestion. Thanks for taking the time anyway and the great product! I'll look into that PR, which indeed also solves my problem!
