### ISSUE TITLE
DocumentSession.ForTenant(...) needs to also allow users to make event store operations for the specific tenant

### ISSUE THREAD

**Issue by iamjustsam** [JasperFx/marten#2298]
When you want to query documents for all tenants, you can do so by using `.AnyTenant()` in your query. If you then want to store events for the respective tenants, you currently have to open a new session for every tenant because it is not possible to store events in the event store returned by `ITenantOperations`.

```csharp
var documents = await session.Query<Document>().Where(x => x.AnyTenant()).ToListAsync();

foreach(var document in documents)
{
    session.ForTenant(document.TenantId).Events.Append(new Event()) // This is not possible since session.ForTenant(...).Events returns an IQueryEventStore instead of an IEventStore
}
```

While it _is_ possible to downcast the `IQueryEventStore` to `IEventStore`, it is not safe to do so since Marten will query mt_streams using the tenant id from the parent session when calling session.SaveChanges().

**Comment by jeremydmiller** [comment]
Gonna rephrase this a bit, 'cause you're in tactical "how do I solve my immediate problem" and we need to think strategically about the API. Can't introduce a breaking change to the API until 6.0.
