### ISSUE TITLE
NGramIndex on Inner Property does not work (Runtime Error)

### ISSUE THREAD

**Issue by OptimusPi** [JasperFx/marten#2304]
@apereiratl here is an issue for what we briefly chatted about. 

Here is a simple Record I have: 

```
    public RentalProperty(Guid id, string name, PropertyDetails details, PropertySecurityInfo securityInfo)
    {
        Id = id;
        Name = name;
        Details = details;
        SecurityInfo = securityInfo;
    }
```

Here is a working NGramIndex, with the not-working index commented out

```
    public void Configure(IServiceProvider services, StoreOptions options)
    {
        // RentalProperty search indexes
        
        // Works great! Useful for whole-word matching.
        options.Schema.For<RentalProperty>().FullTextIndex(); 

        // Top-level string property works great! Useful for partial-match searching
        options.Schema.For<RentalProperty>().NgramIndex(x => x.Name); 
        
        // Inner Property NGramIndex does not work. There is a runtime error.
        // RentalProperty is a record, 
        // RentalProperty.Details is a record, 
        // RentalProperty.Details.MailingAddress is a record, 
        // RentalProperty.Details.MailingAddress.StreetAddress1 is a string.
        // BROKEN:
        // options.Schema.For<RentalProperty>().NgramIndex(x => x.Details.MailingAddress.StreetAddress1);
    }
```

Luckily, the NGramSearch still works fine. I just worry about not having that one field indexed properly, and speed concerns when we get more data in our database. 
```
  await using var session = await GetSession(cancellationToken);
  var rentalProperties = await session.Query<RentalProperty>()
      .Where(x => x.Name.NgramSearch(searchText) 
                  || x.Details.MailingAddress.StreetAddress1.NgramSearch(searchText)  // TODO - make sure there is a way to index this? 
                  || x.PlainTextSearch(searchText))
      .ToListAsync(cancellationToken);

  return rentalProperties;
```

So on to the error, when trying to NGramIndex on an inner property, this occurs:

```
[10:18:50 ERR] An unhandled exception has occurred while executing the request. <s:Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware>
Weasel.Postgresql.PostgresqlIdentifierInvalidException: Database identifier mt_doc_rentalproperty_idx_ngram_details as jsonb) ||   || cast(data ->> mailingaddress as jsonb) ||   || data ->> streetaddres
s1 is not valid. See https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html for valid unquoted identifiers (Marten does not quote identifiers).
   at Weasel.Postgresql.PostgresqlMigrator.AssertValidIdentifier(String name)
   at Weasel.Core.Migrations.DatabaseBase`1.generateOrUpdateFeature(Type featureType, IFeatureSchema feature, CancellationToken token)
   at Weasel.Core.Migrations.DatabaseBase`1.ensureStorageExists(IList`1 types, Type featureType, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ensureStorageExistsAsync(LinqHandlerBuilder builder, CancellationToken cancellationToken)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token)

```

**Comment by tonykaralis** [comment]
I haven't been able to get the basic NGramSearch to work both with and without specifying the index on the config. I originally had a full text and gin index set on a document. Removed those but still not working. It throws an error 
```function mt_grams_vector(text) does not exist```

**Comment by apereiratl** [comment]
@tonykaralis Can you please post how you're trying to use this feature?

**Comment by OptimusPi** [comment]
I believe you need PostgreSQL 10+ or else it is not supported.
Make sure you have mt_grams_vector available in public/routines in your database as shown here (screenshot from DataGrip) 
![image](https://user-images.githubusercontent.com/16853743/182935134-c626c9e2-32bd-4ab8-af22-a1cd90b07d30.png)

If that all looks good, then it's potentially related to this bug. 

I have found that you can still NgramSearch without the NgramIndex just fine, however it's probably slower especially with a lot more data! 

@tonykaralis When I was learning how to use this, I encountered the same error `function mt_grams_vector(text) does not exist` but it was because the method was not attached to some property correctly. Share your usage example please? :)

**Comment by mysticmind** [comment]
@tonykaralis @OptimusPi Could please update us on this issue with a repro?

**Comment by mysticmind** [comment]
> I haven't been able to get the basic NGramSearch to work both with and without specifying the index on the config. I originally had a full text and gin index set on a document. Removed those but still not working. It throws an error `function mt_grams_vector(text) does not exist`.
> 
> I checked the DB and according to PGAdmin the function does exist.

Most likely you are using multiple database schema. Most likely, it is related to https://github.com/JasperFx/marten/issues/2398

**Comment by mysticmind** [comment]
@OptimusPi Probably you could use a [duplicate field](https://martendb.io/documents/indexing/duplicated-fields.html) for the nested property as a workaround and create an NGramIndex on the duplicated field.

**Comment by tonykaralis** [comment]
@mysticmind Thank you for getting back to us. This is definitely the issue I'm facing then as all of my data resides in a separate schema called `Data`
