### ISSUE TITLE
Missing fields for basetypes

### ISSUE THREAD

**Issue by srasch** [JasperFx/marten#2308]
Hi there,

I'm currently trying to upgrade to latest Marten 5.8.0 (from 3.14.X). 

I found that the fields from basetypes are not persisted in postgres after upgrading. Is this a bug?

```c#
public class MyBaseClass 
{
  public string Foo {get;set;}
  public int Bar {get;set;}
}

public class AnotherClass : MyBaseClass
{
  public string AnotherVal {get;set;}
}
```

when registering and using only `AnotherClass` the Fields `Foo` and `Bar` are left out. 
Worked in 3.14

**Comment by mysticmind** [comment]
@srasch We do have many unit tests on for the hierarchical documents and are working as expected in the latest version. I did a test using your above example and looks to work fine. Please provide a repro for us to check further.

**Comment by srasch** [comment]
hm, that's crazy. I tried to setup a test for this case. Now it works... ⁉️
