### ISSUE TITLE
Unable to re-build projections manually. Projection agent is stuck

### ISSUE THREAD

**Issue by NikiforovAll** [JasperFx/marten#2317]
I've encountered issues that make projections re-building via CLI to be stuck/deadlock. Only after a while, I see the error message.

![image](https://user-images.githubusercontent.com/8037439/184217504-8095fc3c-58c5-4720-a488-ca005d348583.png)

🐛 After further investigation, I discovered it was related to type mismatch in the event model. So the issue occurred during the development/design time.

It would be great to see errors reported when something goes wrong. Is this something that can be added? Do you accept PRs?

**Comment by jeremydmiller** [comment]
@NikiforovAll I'm certainly happy for any and all pull requests to improve the logging. There's quite a bit of logging in the daemon, so where is an exception happening that you don't see in logs?

**Comment by NikiforovAll** [comment]
@jeremydmiller the console app halts when I run the `projections` command. It is like a deadlock or something. When I spin up a visual studio without "Just My Code" option I can see that JSON deserialization exception is thrown but is not propagated to the client code. 

Steps to reproduce:

1. Store event
2. Make breaking change to the event model
3. Rebuild projects

**Comment by jeremydmiller** [comment]
@NikiforovAll I think I'm going to describe this as "Marten can't rebuild projections where there's a poison pill message". I think the error handling that's supposed to stop the rebuilding when there's an invalid event is kicking in and stopping it. 

I think I can mimic the serialization problems

**Comment by jeremydmiller** [comment]
Notes:

* In rebuild mode, automatically skip any event that has serialization failures for now, and automatically make them dead letter events
* Assert no dead letter events in rebuild command? Make that opt in, opt out??? Fail fast???
* May need to change the Rebuild mode to also pass in rebuild settings
