### ISSUE TITLE
Evaluate native vite press snippets usage

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#2349]
Per @Hawxy finding: https://vitepress.vuejs.org/guide/markdown#import-code-snippets

**Comment by mysticmind** [comment]
Quick note that I added the VitePress snippets feature as in VuePress. Our initial version of docs used it but @jeremydmiller was not happy with using the file path since when we reshuffle code, the file paths can get broken.

So I eventually implemented mdsnippets which is the current mechanism.

**Comment by jeremydmiller** [comment]
The Vitepress usage is not viable IMO. It's higher friction and lower capability than what we get w/ mdsnippets, even with having to manually call mdsnippets once in a while. I'm going dictatorial and shutting this one down folks.

**Comment by oskardudycz** [comment]
I think it's viable, as I managed to make Vuepress native snippeting work well for ESDB docs reusing regions, so I think that the same can be done here. The fewer moving pieces the better IMHO. Still, this is not the hill I'll die on :wink:
