### ISSUE TITLE
Provide an option to specify projection rebuild command timeout for Marten.CommandLine

### ISSUE THREAD

**Issue by NikiforovAll** [JasperFx/marten#2360]
The default timeout is hardcoded and it is not possible to extend the migration period. 

Example: https://github.com/JasperFx/marten/blob/0315c77fdf883b1db16784de6aec35de06dad40d/src/Marten/Events/Daemon/ProjectionDaemon.cs#L256

Example application: 

```csharp
using Microsoft.Extensions.Hosting;
using Oakton;

await Host.CreateDefaultBuilder(args)
    .ConfigureServices((hostContext, services) => services.AddInfrastructure(hostContext.Configuration))
    .RunOaktonCommands(args);
```

**Comment by mysticmind** [comment]
@NikiforovAll please run through the following pointers and you can attempt to send us a PR:
- https://github.com/JasperFx/marten/blob/c848c99067c43926cefb4263b4958f6765aac54c/src/Marten.CommandLine/Commands/Projection/ProjectionInput.cs#L11, Add a new property `ShardTimeout` as a TimeSpan
- https://github.com/JasperFx/marten/blob/c848c99067c43926cefb4263b4958f6765aac54c/src/Marten.CommandLine/Commands/Projection/IProjectionHost.cs#L17, Add an optional arg named `TimeSpan? shardTimeout=null`  to `IProjectionHost.TryRebuildShards`
- https://github.com/JasperFx/marten/blob/c848c99067c43926cefb4263b4958f6765aac54c/src/Marten.CommandLine/Commands/Projection/ProjectionHost.cs#L111, change this line to `await daemon.RebuildProjection(projectionName, shardTimeout ?? 5.Minutes(), token).ConfigureAwait(false))`
- Update the unit tests code under https://github.com/JasperFx/marten/blob/c848c99067c43926cefb4263b4958f6765aac54c/src/Marten.CommandLine.Tests/ProjectionControllerTests.cs#L42 and also add unit tests with and without passing ShartTimeout.
