### ISSUE TITLE
Avoid using IHostEnvironment.IsDevelopment in OptimizeArtifactWorkflow

### ISSUE THREAD

**Issue by vguzmanp** [JasperFx/marten#2367]
Hi, 
first of all, thank you for the amazing job done in the library! In my company we use it and it's proven extremely helpful.

We are migrating from v3 to v5, and we were going to use the `OptimizeArtifactWorkflow` method. However, our stack uses a slightly different environment naming than usual: our local machine uses the environment `Local` and `Development` is used in one of the deployed environments.
This causes issues when using the above method, as `IHostEnvironment.IsDevelopment` returns false, and we run the "production" flow in local.
https://github.com/JasperFx/marten/blob/4c61958127ad65b9f9a13da0756a65a4bfcb120b/src/Marten/MartenServiceCollectionExtensions.cs#L696

The Microsoft documentation on the IHostEnvironment extension methods ([link](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostenvironmentenvextensions?view=dotnet-plat-ext-6.0)) remarks that they shouldn't be used by libraries, I think because of this same situation.

Would you be open to changing the method, so that a parameter `developmentEnvironment` is passed to it, and use `IHostEnvironment.IsEnvironment(developmentEnvironment)`?
That way we can default to "Development", and keep the same behaviour, but also enable us to call it with "Local".

**Comment by jeremydmiller** [comment]
@vguzmanp I'm happy to take a PR making that an **optional** environment name. You'll have to do it with an overload though and not an optional parameter as that will break backward compatibility.
