### ISSUE TITLE
BadLinqExpressionException when using Contains in Query Where clause

### ISSUE THREAD

**Issue by mroberts91** [JasperFx/marten#2383]
I am attempting to add Marten as a DB provider to the [elsa-core](https://github.com/elsa-workflows/elsa-core) project, as it is our preferred provider for these types of workloads.

They have extensive use of filter expressions that are similar to this, where IEnumerable.Contains() is used to filter a query:
``` csharp
// Filter Example
public class Filter
{
    public IEnumerable<string> Ids { get; }
    public override Expression<Func<Entity, bool>> ToExpression() => entity => Ids.Contains(entity.Id);
}

// Filter Usage is Query
public class Store
{
    public List<T> FindMany(Filter filter)
        => _session.Query<T>().Where(filter.ToExpression()).ToList()
}
```
The exception bubbles up from the query building process ultimately from [FieldCollection.cs Line 107](https://github.com/JasperFx/marten/blob/master/src/Marten/Linq/Fields/FieldCollection.cs)

```
Marten.Exceptions.BadLinqExpressionException: 'The sub query is not sourced from a supported collection type'
Inner: ArgumentOutOfRangeException: No members found in this Expression (Parameter 'members')
```

Here is a small console program to replicate:
``` csharp
using var store = DocumentStore.For("Host=localhost;Port=5432;Database=marten_testing;Username=postgres;password=postgres;Command Timeout=5");

store.Options.UseDefaultSerialization(serializerType: SerializerType.SystemTextJson);
store.Options.Serializer(new SystemTextJsonSerializer
{
    EnumStorage = EnumStorage.AsString,
    Casing = Casing.CamelCase
});

store.Options.AutoCreateSchemaObjects = AutoCreate.None;
store.Options.GeneratedCodeMode = TypeLoadMode.Auto;

store.Storage.Database.EnsureStorageExists(typeof(Something));


using var session = store.OpenSession(new SessionOptions());
session.Store(new Something { Id = "1", Message = "Does this work?" });
await session.SaveChangesAsync();

var ids = new string[1] { "4" };
try
{
    _ = await session.Query<Something>()
        .Where(s => ids.Contains(s.Id))
        .ToListAsync();
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
#nullable disable
public class Something
{
    public string Id { get; set; }
    public string Message { get; set; }
}
```

As I am attempting to add on to the Elsa project and not make invasive changes through the code base on how they write these filter expressions, would there be an alternative way to achieve the same result as `.Where(x => list.Contains(x.Id)` would provide in another .NET ORM? This does not seem to be an issue with any of their EF Core or Mongo DB providers.

**Comment by jeremydmiller** [comment]
I'll take a look tomorrow. You've gotta understand that Linq is extremely expensive in man hours to support, and pretty well every unique usage requires explicit code. 

But please, please don't call Marten an ORM:-)

**Comment by mroberts91** [comment]
I will refrain from any usages of said term :). 

I understand that it's no small feat to maintain that portion of the codebase. I did try and debug that portion locally, but it did seem slightly over my head or 5:00 p.m. on a Friday.

I appreciate your help @jeremydmiller, I may try and take another swing at it with fresh eyes later.

**Comment by mroberts91** [comment]
@jeremydmiller It does not seem to be limited to just `.Contains()` but any expression that is handled by `FindMembers.Determine` that is a `ConstantExpression` and/or `IEnumerable` results in the same exceptions being thrown due to the `FindMembers` visitor not being able to get a populated member array.

Example expressions with the same code path and exceptions thrown
```
.Where(s => ids.Contains(s.Id))
.Where(s => ids.Any(i => i == s.Id))
.Where(s => ids.All(i => i == s.Id))
.Where(s => ids.Count(i => i == s.Id) > 0)
```

**Comment by razvanradeanuitsonix** [comment]
@mroberts91 we recently found out in our project that it is depending on the compile-time type. Declaring the `public IEnumerable<string> Ids { get; }` as `public List<string> Ids { get; }` was a quick (and hopefully temporary) fix on our side.

Maybe this also works for you?

**Comment by radeanurazvan** [comment]
@mroberts91  we recently found out in our project that it is depending on the compile-time type. Declaring the `public IEnumerable<string> Ids { get; }` as `public List<string> Ids { get; }` was a quick (and hopefully temporary) fix on our side.

Actually we didn't change the declaration of our properties, we rather just `.ToList `the hell of any collections before passing them to a `.Contains` query.

Maybe this also works for you?

**Comment by CoreyKaylor** [comment]
Even though @mroberts91 didn't confirm. I'm assuming the answer is no as this is meant to be a provider level integration with an existing project that he doesn't own.

> They have extensive use of filter expressions that are similar to this, where IEnumerable.Contains() is used to filter a query:

**Comment by jeremydmiller** [comment]
I'll take a better look at this after Christmas. @mroberts91 Next time you need something w/ Marten, the magic phrase is "I work with Corey" :-)

**Comment by mroberts91** [comment]
@jeremydmiller @CoreyKaylor I appreciate it very much! I like to keep my Corey namedrops to a minimum since I only get a certain number of them per year :)

@radeanurazvan
As for materializing any `IEnumberable<T>` with a ToList() before passing it to marten's expression handling, it is just not a feasible solution in this scenario and the MartendDB provider I am trying to create is just one of many providers of the project following a generic repository pattern which can be called internally or externally. 

It would be pretty invasive to the Elsa project to modify all the internal calls to the repository but impossible to enforce library consumers down that path.

Either way, I appreciate your help in determining a solution for this.

**Comment by jeremydmiller** [comment]
Hey all, sorry for the long delay, but this finally gets knocked out by the Linq improvements in v7 today.
