### ISSUE TITLE
Write Migration guide for Marten v6

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#2403]

**Comment by davit-asryan-sveasolar** [comment]
Is there going to be a migration guide for v5->v6, or no need to change anything apart from some namespaces?

**Comment by mysticmind** [comment]
> Is there going to be a migration guide for v5->v6, or no need to change anything apart from some namespaces?

Yes, as part of the docs outlining the breaking changes etc. If you follow the deprecated method warning etc, you should be able to migrate your code without much hassles.

**Comment by mysticmind** [comment]
> Is there going to be a migration guide for v5->v6, or no need to change anything apart from some namespaces?

@davit-asryan-sveasolar Yes, as part of the docs outlining the breaking changes etc. If you follow the deprecated method warning etc, you should be able to migrate your code without much hassles.

**Comment by davit-asryan-sveasolar** [comment]
Thanks for the quick response!

**Comment by oskardudycz** [comment]
You can also see https://github.com/JasperFx/marten/pulls?q=is%3Apr+milestone%3A6.0.0+is%3Aclosed+label%3A%22breaking+change%22

I’ll try to provide a migration guide this or the next week, but it’s like @mysticmind wrote, we tried to make obsolete markers helpful. In any case, if something is unclear, feel free to ask here or in Discord.

**Comment by oskardudycz** [comment]
The migration guide is also available in docs: https://martendb.io/migration-guide.html#key-changes-in-6-0-0

If something is missing/unclear/etc. Please ping us. 🙂
