### ISSUE TITLE
Fix multitenancy CoreTests failing on CI

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#2404]
There seems to be an environmental issue causing multitenancy `CoreTests` to fail on CI. They're currently skipped. See more in:
- https://github.com/JasperFx/marten/blob/master/src/CoreTests/DatabaseMultiTenancy/using_per_database_multitenancy.cs
- https://github.com/JasperFx/marten/blob/master/src/CoreTests/DatabaseMultiTenancy/using_static_database_multitenancy.cs

**Comment by jeremydmiller** [comment]
This has already been addressed. Believe it was fixed by just making the multi-tenancy tests run single file
