### ISSUE TITLE
Web app hangs when debugging with Rider and using RunOaktonCommands

### ISSUE THREAD

**Issue by stevemossquill** [JasperFx/marten#2411]
I've added `Marten` and `Marten.CommandLine` v5.11.0 to a .NET6.0 web application.

It runs and debugs fine, using JetBrains Rider 2022.2.3, when the startup is:

````C#
public static void Main(string[] args) =>
     CreateHostBuilder(args).Build().Run();
````

When I switch to:

````C#
public static Task<int> Main(string[] args)
{
    return CreateHostBuilder(args).RunOaktonCommands(args);
}
````
then running is still fine, but when debugging the Swagger web-page it is trying to open isn't displayed.

The browser just displays:
> Unable to connect
> Firefox can’t establish a connection to the server at localhost:5000.

In Rider, it behaves as if it is hitting an invisible break-point.  Clicking the "Resume Program" button to continue debugging just breaks again immediately at the same place:

![image](https://user-images.githubusercontent.com/103118727/205121984-973ba197-fcdf-44a1-a757-0aa10c646378.png)

**Comment by jeremydmiller** [comment]
@stevemossquill Not sure what to tell you here, but it's going to take a lot more information than that to solve this. Do you have any custom `IHostedService` registrations? What are you trying to do at start up time? Anything overwriting the port number?

And I very seriously doubt this is directly related to Marten itself

**Comment by stevemossquill** [comment]
Ok, I'm suitably embarrassed.. this was just down to my Rider debug settings for exceptions:

The `RunOaktonCommands` extension leads to `RegisterCommandsFromExtensionAssemblies` which scans all assemblies for the `OaktonCommandAssemblyAttribute`.

This automatically included scanning all the `Microsoft.Code.Analysis.*` files that appear in my `bin` directory.

The "problem" was this tries to load the `.pdb` file for each DLL, and when not found threw an exception.

In release mode, this exception is just swallowed (correctly), but my exception settings were set to break on any CLR exception.

Once I stopped breaking on CLR exceptions, the app started up fine.
