### ISSUE TITLE
IDocumentOperations.QueueSqlCommand to insert into jsonb-column

### ISSUE THREAD

**Issue by gfoidl** [JasperFx/marten#2422]
E.g.
```c#
// Setup
Table myTable = new("my_table");
myTable.AddColumn("data", "jsonb");

options.Storage.ExtendedSchemaObjects.Add(myTable);
```
Creates a table with a _jsonb_-column.

```c#
internal class MyProjection : IProjection
{
    public void Apply(IDocumentOperations operations, IReadOnlyList<StreamAction> streams)
    {
        foreach (IEvent @event in streams.SelectMany(static s => s.Events))
        {
            const string Sql = "insert into my_table (data) values (?);";

            // Use the object as parameter directly
            operations.QueueSqlCommand(Sql, @event.Data);
        }
    }
}
```
fails with 
```
System.InvalidCastException: Can't write CLR type XYZ with handler type TextHandler
         at Npgsql.Internal.TypeHandlers.TextHandler.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
         at Npgsql.NpgsqlParameter.ValidateAndGetLength()
         at Npgsql.NpgsqlParameterCollection.ProcessParameters(TypeMapper typeMapper, Boolean validateValues, CommandType commandType)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
```

Trying to insert the JSON as string like
```c#
internal class MyProjection : IProjection
{
    public void Apply(IDocumentOperations operations, IReadOnlyList<StreamAction> streams)
    {
        foreach (IEvent @event in streams.SelectMany(static s => s.Events))
        {
            const string Sql = "insert into my_table (data) values (?);";

            string json = JsonSerializer.Serialize(@event.Data);
            operations.QueueSqlCommand(Sql, json);
        }
    }
}
```
fails with 
```
 Npgsql.PostgresException (0x80004005): 42804: column "data" is of type jsonb but expression is of type text
```

Is there any way to insert JSON into a _jsonb_-column via IDocumentOperations?

If not, then I believe the problem results from https://github.com/JasperFx/marten/blob/56fb16e3342088df5498049bd7d3670af31883e1/src/Marten/Internal/Operations/ExecuteSqlStorageOperation.cs#L40 (at for the "insert json as string"-case), as the type is `string`, so it tries to insert via TextHandler.
If this gets changed to 
```c#
                var dbType = PostgresqlProvider.Instance.TryGetDbType(_parameterValues[i].GetType());

                parameters[i].NpgsqlDbType = dbType != null
                    ? dbType.Value
                    : NpgsqlTypes.NpgsqlDbType.Jsonb;
```
then the object could be used a parameter directly, and NpgSql would care about serialization and the insert to the _jsonb_-column.

Could this have any downsides? Is there possibly a better way by getting the actual underlying db-column-type and set the `NpgsqlDbType` based on that?

A different approach could be to pass the DB-types as arguments to `QueueSqlCommand` (additional overload).

**Comment by mysticmind** [comment]
Use `const string Sql = "insert into my_table (data) values (?::jsonb);";` to convert the json string value to jsonb using `::jsonb`

**Comment by gfoidl** [comment]
Fantastic 👍🏻 Thank you!

In [Execute custom SQL in session](https://martendb.io/documents/execute-custom-sql.html) a hint could be added that Postgres casting operator can be appended to parameters and that these casts aren't changed / removed by Marten. Then it would be ideal.

Something like
> "?" placeholders can be used to denote parameter values. Postgres [type casts `::`](https://www.postgresql.org/docs/15/sql-expressions.html#SQL-SYNTAX-TYPE-CASTS) can applied to the parameter if needed.

If that sounds good, I can do a PR for this.

**Comment by mysticmind** [comment]
@gfoidl Quick note, the use case which you outlined is not a typical one which users would use especially `jsonb`.

**Comment by gfoidl** [comment]
Yep, I know. Normally the document store features are sufficient. I came accross this issue while playing around with the [outbox pattern](https://event-driven.io/en/push_based_outbox_pattern_with_postgres_logical_replication/#postgres-logical-replication) (and wanted to have the _jsonb_ column, not a plain string / text column).

**Comment by mysticmind** [comment]
Got you!
