### ISSUE TITLE
Npgsql 6.0 Batching with `NpgsqlBatch`

### ISSUE THREAD

**Issue by gfoidl** [JasperFx/marten#2424]
Npgsql 6.0 introduced `NpgsqlBatch` which is natively supported Postgres. 
Marten uses so called [legacy batching](https://www.npgsql.org/doc/basic-usage.html#legacy-batching), so the new mechanism should be considered.

The work with `NpgsqlBatch` needs more object allocations, but as described in the Npgsql-docs no parsing and rewriting of the commands needs to be done. So perf should be validated if the more object allocations outweigh the cost of the rewriting.

I did a very rough and dirty [attempt](https://github.com/JasperFx/marten/compare/master...gfoidl:marten:9830dbf77c460d9747f81af86e9b53315da4adb5). The `CommandBuilder` from Weasel should be extended to have a `Reset` or `Clear` method, so that the builder can be re-used for creating the batched commands and to avoid unneeded allocations. Or have a _BatchBuilder_ in Weasel for even easier use.

**Comment by jeremydmiller** [comment]
Moving this to #2787, but this might need to go into Weasel somehow
