### ISSUE TITLE
Exception on postprocessUpdateAsync (Non async use side effect)

### ISSUE THREAD

**Issue by horego** [JasperFx/marten#2428]
Hello everyone,

I have not digged to deep into the issue but i observe an error when rebuilding the projection. I ran into the issue where i got an exception from postprocessUpdateAsync while trying to execute
`await reader.IsDBNullAsync(0, token).ConfigureAwait(false)
`after
`!await reader.ReadAsync(token).ConfigureAwait(false)
`
since there is no data so IsDBNullAsync throw an exception. When compared to the non async method postprocessUpdate all is written in one line with conditional or operator ||. For me it looks like it should behave the same. What do you think?

i created a pr
https://github.com/JasperFx/marten/pull/2427

btw. should i create a ticket and pr for the same issue? it feels redundant.

best regards

**Comment by jeremydmiller** [comment]
Fixed by #2427 

Thanks @horego!
