### ISSUE TITLE
Error during rebuilding projection of type EventProjection

### ISSUE THREAD

**Issue by horego** [JasperFx/marten#2429]
Hello everyone,

first of all i wanna say thx for your work. I'm currently running into an issue where i'm not able to rebuild my projection.

### What i'm using
Nothing special. Marten in net6 app with inline projection derived from EventProjection.

The code looks like the following. Slightly modified to keep it simple
```

ProjectAsync<MyEvent>(async (e, ops) =>
{
    var lookup = await ops.LoadAsync<MyView>(myEventId);
    if (lookup == null)
        throw Ex(); 

    lookup.Value = e.newValue;
    ops.Update(lookup); // <-- After the creation of the MyView. This code line leads somehow to the problem i'm trying to describe.
});

```

### What i'm doing
Inserting roughly 50k up to 500k events with inline projection. Everything works fine as expected. But when i try to rebuild the projection i'm running into an error (NonExistentDocumentException).

### What i observed so far
When i skip the execution of postprocessUpdateAsync which produce an NonExistentDocumentException exception everything is fine. Even the projection i'm updating has the most recent value from the event provides by the example above.

However this is not the solution i would guess. So i digged a little bit deeper.

Within the ApplyCallbacksAsync from UpdateBatch.cs this error only occur if the command is of type
`Marten.Generated.DocumentStorage.Update...Operation...`
this does no happen if the operation is of type
`Marten.Generated.DocumentStorage.Upsert...Operation...`
When following the execution path of ...Update...Operation i end up inside the method postprocessUpdateAsync where `await reader.ReadAsync(token).ConfigureAwait(false)` returns false and therefor adds an exception.

i hope everything i wrote is understandable.

Do you have any idea / solution for this problem?

### Investigation update
I ended up using .Store() instead of .Update() Update is causing the NonExistentDocumentException while .Store() is not. Some code below i'm using:
```

ProjectAsync<NewEvent>(async (e, ops) =>
{
	ops.Insert(new MyView(
		id,
		value));
	return;
});

ProjectAsync<UpdateEvent>(async (e, ops) =>
{
	var lookup = await ops.LoadAsync<MyView>(id);
	if (lookup == null)
		return;

	lookup.Value = e.newValue;
	//ops.Update(lookup); // leads to an error
	ops.Store(lookup); // success
});
```

Best regards

**Comment by jeremydmiller** [comment]
Well, yeah, don't use Update or Insert in EventProjection if you hit this kind of problem. It's just making your code potentially brittle to timing/ordering issues. The upsert mechanism in Postgresql is efficient enough that you don't need to worry about inserts or updates.

**Comment by jeremydmiller** [comment]
I'm actually going to close this as I don't think there's anything actionable.
