### ISSUE TITLE
Need to assert on identity type mismatch in FetchForWriting()

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2454]
Had a user issue the other day. When using the `FetchForWriting()` functionality, the aggregate document identity type has to match the stream type in order to function. We need to make the exception be very clear about what's wrong when this happens.

**Comment by dgrozenok** [comment]
I don't remember why (maybe based on some older examples), but I had this line in the Marten configuration code for the `Product` aggregate:

```csharp
_.Events.AddEventType(typeof(Product));
```

As a result the issue with the mismatch reproduced to me. When I removed that line everything started working normal. According to the description of that `AddEventType` method it's optional, but helps Marten in some way. How would I need to call it not to break the `FetchForWriting()`?
