### ISSUE TITLE
PostgresException not transformed to ExistingStreamIdCollisionException for same stream Id

### ISSUE THREAD

**Issue by appetere** [JasperFx/marten#2459]
**Summary**
If trying to add a stream with the same ID as an existing stream, the expected behaviour is that an `ExistingStreamIdCollision` exception is thrown.  When an inline projection is being used, the underlying `PostgresException` is surfaced instead.

Using Marten 5.11.0

**Steps to reproduce**
An existing test shows that you should expect an `ExistingStreamIdCollision` exception if trying to create a new new stream with the same Id as an existing one:

https://github.com/JasperFx/marten/blob/master/src/EventSourcingTests/start_stream_should_enforce_that_it_is_a_new_stream.cs

However, the original PostgresException (`23505: duplicate key value violates unique constraint "pkey_mt_streams_id`) is returned when creating a new stream, when there is an inline projection configured for the stream's events.

To show this, you can adapt the existing test at: https://github.com/JasperFx/marten/blob/master/src/EventSourcingTests/Aggregation/fetching_inline_aggregates_for_writing.cs#L16 (see below).

When you run the modified test it will throw `PostgresException` rather than the expected `ExistingStreamIdCollision`.

The difference seems to be that the passing test throws the exception in `Marten.Internal.UpdateBatch.ApplychangesAsync -> session.ExecuteReaderAsync` which then gets transformed in the `catch`.  But the "failing" test throws the exception in the `Marten.Internal.UpdateBatch.ApplychangesAsync -> UpdateBatch.ApplyCallbacksAsync` code, where the PostgresException doesn't get transformed when there are three operations in the batch (Upsert the document, InsertStream and Insert Event to Stream).

```c#
public class fetching_inline_aggregates_for_writing : OneOffConfigurationsContext
{
    [Fact]
    public async Task fetch_new_stream_for_writing_Guid_identifier()
    {
        StoreOptions(opts => opts.Projections.SelfAggregate<SimpleAggregate>(ProjectionLifecycle.Inline));

        var streamId = Guid.NewGuid();

        var stream = await theSession.Events.FetchForWriting<SimpleAggregate>(streamId);
        stream.Aggregate.ShouldBeNull();
        stream.CurrentVersion.ShouldBe(0);

        stream.AppendOne(new AEvent());
        stream.AppendMany(new BEvent(), new BEvent(), new BEvent());
        stream.AppendMany(new CEvent(), new CEvent());

        await theSession.SaveChangesAsync();

        /********* ADD THESE FIVE LINES *********/
        var sameStream = theSession.Events.StartStream(streamId, new AEvent());
        Exception<ExistingStreamIdCollisionException>.ShouldBeThrownBy(async () =>
        {
             await session.SaveChangesAsync();
        });

        var document = await theSession.Events.AggregateStreamAsync<SimpleAggregate>(streamId);
        document.ACount.ShouldBe(1);
        document.BCount.ShouldBe(3);
        document.CCount.ShouldBe(2);
    }
```

**Comment by jeremydmiller** [comment]
Done in a branch, but it's bundled in a PR with other fixes. Soon.
