### ISSUE TITLE
Move all the IQueryable extension methods into the root namespace

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#247]
I think it makes Marten just a tad easier to use if all the user facing extension methods are in the root namespace.

**Comment by nieve** [comment]
I'll clean that later on today.

**Comment by jeremydmiller** [comment]
@nieve You might wanna put that off for now. I know there's a biggish PR coming from @CoreyKaylor relatively soon that might cause some ugly merge conflicts with that.

**Comment by nieve** [comment]
@jeremydmiller thanks for the heads up. Will wait with it then.

**Comment by jeremydmiller** [comment]
I'm getting this now. Doing some housecleaning this morning.
