### ISSUE TITLE
Easy to use fake inmemory for testing

### ISSUE THREAD

**Issue by DarriusWrightGD** [JasperFx/marten#248]

**Comment by nieve** [comment]
If you're talking about something similar to RavenDB's famous embedded DB, unfortunately that's probably going to have to wait- more info here: https://www.youtube.com/watch?v=2pl_44IREng#t=19m50s

**Comment by jeremydmiller** [comment]
This was originally just to have a pre-built stub for our `IDocumentSession`. Honestly, after thinking about this, I'm shutting it down as "will not fix." The things that are easy to stub/mock in Marten are easily done w/ any mocking tool and the things that aren't really appropriate to mock have to be integration tests anyway.

**Comment by jeffdoolittle** [comment]
Time to re-open? https://www.nuget.org/packages/PostgreSql.Binaries.Lite/

`Marten.Embedded` for the win!

**Comment by jeremydmiller** [comment]
@jeffdoolittle I've been mulling this one over all weekend. I'm thinking that we go for it.

**Comment by jeffdoolittle** [comment]
I think this would be a huge win for the growing Marten community.

**Comment by jeremydmiller** [comment]
I'm opening a new issue for the "embedded option"
