### ISSUE TITLE
Enable to specify custom IdStategy sub-class

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#250]
Would be great to have the option to override the default IdStategy genrator with my own sub-class, this would let me implement a RavenDb style generator to make my migration much easier.

Either at the document type level, or maybe a global level if possible for all documents?

**Comment by tim-cools** [comment]
@jeremydmiller I will look into this. I need it anyway for https://github.com/JasperFx/marten/issues/244

**Comment by jeremydmiller** [comment]
@tim-cools Thanks for taking this.
