### ISSUE TITLE
AnyTenant not working on QueryRawEventDataOnly<> 

### ISSUE THREAD

**Issue by radeanurazvan** [JasperFx/marten#2518]
Tenant id is still taken into account when querying only by raw event data

Example: `querySession.Events.QueryRawEventDataOnly<ProductCreatedEvent>().Where(e => e.AnyTenant());`

Result: `select data from catalog.mt_events as d where (((d.type = 'product_created_event' and  d.is_archived = FALSE) and  d.tenant_id = :tenantid)  and  d.is_archived = FALSE  and  1=1)`

Querying by `querySession.Events.QueryAllRawEvents().Where(e => e.AnyTenant())` works as expected.

I don't know tho if this is supposed not to be supported?

Taking a very quick look at the source code, I think it's something caused by  `FilterDocuments` method in `EventDocumentStorage`?

```
        public ISqlFragment FilterDocuments(QueryModel model, ISqlFragment query)
        {
            var shouldBeTenanted = Events.TenancyStyle == TenancyStyle.Conjoined && !query.SpecifiesTenant();
            if (shouldBeTenanted)
            {
                query = query.CombineAnd(CurrentTenantFilter.Instance);
            }

            return query.SpecifiesEventArchivalStatus()
                ? query
                : query.CombineAnd(IsNotArchivedFilter.Instance);
        }
```

I can provide a small repro if needed.

**Comment by oskardudycz** [comment]
@radeanurazvan, it'd be great if you could provide a reproduce steps. Having the PR with a failing test would be much appreciated.

**Comment by oskardudycz** [comment]
I'm closing this issue because of the inactivity. @radeanurazvan feel free to comment if the issue still exists in the v6 and I'll reopen it after getting reproduce steps.
