### ISSUE TITLE
Tooling to help migrate data from RavenDb to Marten

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#252]
We're gonna want it at work before too long, and most of our early adopters are moving over from Raven anyway.

**Comment by nieve** [comment]
I'm particularly interested in this one- I'm hoping to be able to convince my new employer to migrate from mongodb to marten. Mongo is pervasively used in .net shops in my part of the world & postgresql is highly popular as well. This could be a huge win for the project.

Anyway- keep this in mind when you do the raven work if possible. I'd be happy to add mongodb support for this.

**Comment by jeremydmiller** [comment]
We could keep the code for writing to Marten itself in a shared place I suppose. I'll have work time to do this for a project that's converting from RavenDb to Marten.

**Comment by nieve** [comment]
That'll be awesome, yeah.

**Comment by jeremydmiller** [comment]
I'm shutting this one down. It's worth a blog post or some documentation, but I'm unilaterally saying this isn't necessary right now.

**Comment by ltobiasgcm** [comment]
Was there a blog post or documentation made for how to migrate data between Raven and Postgres?

**Comment by ltobiasgcm** [comment]
Was there a blog post or documentation on moving data between Ravendb and Postgres?

**Comment by bradyclifford** [comment]
We just migrated a big project from RavenDb to Marten.  I will see if I can find some time to get a blog up on it.
