### ISSUE TITLE
Side Effects from Aggregation Projections

### ISSUE THREAD

**Issue by nmowatt** [JasperFx/marten#2533]
Issue discussed in Discord with @oskardudycz:

EventProjection:

```
public class ServiceExternal : EventProjection {
    private readonly HttpClient _httpClient;

    public ServiceExternal(IConfiguration configuration) {
        _httpClient = new HttpClient();
        _httpClient.BaseAddress = new Uri(configuration.GetConnectionString("url");
    }

    public async Task Project(Events.SessionRequested e, IDocumentOperations ops) {
     
        var response = await _httpClient.GetAsync("users?delay=1");
        if (response.IsSuccessStatusCode) {
            var result = await response.Content.ReadAsStringAsync();
            Console.WriteLine(result);
            ops.Events.Append(e.SessionId, new Events.SessionSuccess(e.SessionId, e.UserId));
        }
    }
}
```
Registered as:

```
options.Projections.Add(new ServiceExternal(builder.Configuration), ProjectionLifecycle.Async);
```
Fails with error:

```
fail: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Failure while trying to process updates for event range Tenant Group Range for: Event range of 'Identity: API.External.ServiceExternal:All', 1 to 2 for projection shard 'API.External.ServiceExternal
:All'
      Marten.Exceptions.ApplyEventException: Failure to apply event #2 (SessionRequested { SessionId = 3fa85f64-5717-4562-b3fc-2c963f66afa6, UserId = 3fa85f64-5717-4562-b3fc-2c963f66afa6 }.)
       ---> System.NotSupportedException: Specified method is not supported.
```

**Comment by jameswoodley** [comment]
Adding my projection code here as discussed with @oskardudycz - a different issue, but wondering if similar cause

[Archive.zip](https://github.com/JasperFx/marten/files/11027419/Archive.zip)

**Comment by oskardudycz** [comment]
@nmowatt, @jameswoodley, indeed, that's a missing feature for now. We want to deliver that, but it'll require more work than I initially anticipated. For now, you can use the [IDocumentListener](https://martendb.io/diagnostics.html#listening-for-document-store-events) `AfterCommitAsync` method. It'll be triggered once the event was commited.

**Comment by jeremydmiller** [comment]
Hey, I finally read through this a bit more. I would strongly recommend the solution to this is **not** Marten all by itself. Honestly, you need to be using Wolverine or something similar to be publishing a separate command for the call to HttpClient that can succeed/fail/be retried independently of the original transaction.

**Comment by oskardudycz** [comment]
I'm not saying we should support all messaging scenarios and push people to do that through Marten, but I believe we should support appending events in our projections. Event transformations and pipelines, or storing information about the success/failure of publishing, are a valid scenario for many cases or even must-haves.

I agree that this should not be the core of Marten, and we should encourage people to use Wolverine, but I also believe that we should not do vendor locking here. We should be explicit about limitations and let people decide.

**Comment by jeremydmiller** [comment]
> I'm not saying we should support all messaging scenarios and push people to do that through Marten, but I believe we should support appending events in our projections. Event transformations and pipelines, or storing information about the success/failure of publishing, are a valid scenario for many cases or even must-haves. See, e.g. EventStoreDB _projections_.
> 
> I agree that this should not be the core of Marten, and we should encourage people to use Wolverine, but I also believe that we should not do vendor locking here. We should be explicit about limitations and let people decide.

I'm not as convinced that we should be emitting events so much as having a hook for side effects (maybe just part of subscriptions) that's somewhat independent of the event appending. I'd say a little bit stronger that doing things like calling a web service in a projection is probably going to be a hard to maintain architecture. 

Let's maybe just talk about this more in terms of a subscription model rather than trying to force fit this into the projection model

**Comment by mattburton** [comment]
What if projections are just a kind of subscription? Then things like first-class support for event transformations could just be abstractions built on that same foundation, or if the abstraction doesn't suit your needs you can drop all the way down to `ISubscription` or whatever just like `IProjection` today. There would still need to be guidance for things like calling a web service in a subscription - should probably send an async message in Wolverine instead of doing it right then and there - but conceptually you'd have one model to deal with - it's subscriptions all the way down, but if your use case fits here are some nice abstractions you can use for XYZ.

**Comment by oskardudycz** [comment]
My take on that is that projection should be able to emit events and subscriptions should be responsible for external integrations.

I understand the current internal complexity, but we don’t need to throw on us accidental complexity. For instance, can initially allow people to append it without giving the option to e.g. apply inline projection when doing that.

I also think that having such a feature can open a lot of doors for: event transformations, pipelines, map-reduce projections, and workflows.

**Comment by mattburton** [comment]
> My take on that is that projection should be able to emit events and subscriptions should be responsible for external integrations.

Yeah, I guess my mental model is that a projection is a kind of subscription - the system needs to track the progress of the projection just like a subscription. What EventStoreDB calls "projections" are what I think of as "transformations" - since it's really transforming one event into another event(s) and not updating some form of projected state - document, etc... Anywho... `</tangent>`.

**Comment by oskardudycz** [comment]
@mattburton, ESDB projections are not projections in the typical naming; as you said, they are instead transformations.

Logically, projections can be seen as a subset of subscriptions, especially from the ESDB perspective. Still, Marten is a different beast; we may need to optimise differently for the storage updates and forwarding externally. We have the same storage for events and read models, giving more optimisation and handling options. From the resiliency fault tolerance, they may have different needs. So we're still determining how much they will share technically. For now, we perceive that they may differ.

**Comment by jeremydmiller** [comment]
Back to thinking about this for the first time in awhile as it's still outstanding. 

My main concern from a mechanical standpoint is concurrency issues by trying to append to a stream that might be getting edited at the same time online. That potentially makes this brittle.  

The amelioration I think is to have an alternative event appending process that's:
* Optimized for bigger batches, which the current event appending in `EventGraph` is absolutely optimized for one or few streams at a time
* No inline projections will apply to these events
* The event capture data mechanics should try to capture the stream version and event sequence as part of a new function generated for this specific operation. That eliminates a lot of the overhead of our current event appending
* This is latched for projection rebuilds **at least for now**

I still personally like the side effect through Wolverine mechanism a lot better, but this has come up enough that it's worth supporting soon.

**Regardless**, the guidance in the documentation should be to only do this for processes that are absolutely not error prone. I also think as part of a first class subscription model that there should be a "side effect" registration mechanism to queue up extra operations outside of the initial processing. That hook would be there at least for Wolverine subscriptions, but would help for other options maybe.

**Comment by jeremydmiller** [comment]
## Tasks & Tests

- [ ] Append event given an IEventSlice. Need to be able to use quick append
- [ ] If appending event to single stream projection, verify the version is set by calling LoadAsync() later
- [ ] If appending event to multi stream projection, verify the version is set to the sequence number by calling LoadAsync() later
- [ ] Ability to register outgoing messages and push
