### ISSUE TITLE
Ability to override mt_deleted index name

### ISSUE THREAD

**Issue by jessetechie** [JasperFx/marten#2534]
I would like to make an existing table `.SoftDeleted()`. The table's name is 42 characters long. When the index is created for the mt_deleted column, its name is `mt_doc_` + 42 + `_idx_mt_deleted` for a total of 64 characters, past Postgres' default limit of 63. So of course, I get a `Marten.PostgresqlIdentifierTooLongException`.

I got excited when I saw [`SoftDeletedWithIndex(Action<IndexDefinition> configure)`](https://github.com/JasperFx/marten/blob/master/src/Marten/MartenRegistry.cs#L631) but this adds the configured index for `mt_deleted_at` instead. There doesn't appear to be a way to configure the index name that gets created for the `mt_deleted` column.

**Comment by jessetechie** [comment]
Just to add, since the [documentation](https://martendb.io/configuration/storeoptions.html#postgres-limits-on-naming) suggests increasing NAMEDATALEN:

https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

> If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h.

In other words, it is a compile-time constant. This is pretty much a no-go for cloud Postgres services like ElephantSQL and Azure Postgres. It's also non-trivial for Docker scenarios.

**Comment by mysticmind** [comment]
@jessetechie if you do something like below, it should set the name of index as defined by you:

```csharp
storeOptions.Schema.For<MyDoc>()
    .SoftDeletedWithIndex(x =>
    {
                x.Name = "my_index";
     });
```

Could you please try the above and keep me posted?

**Comment by mysticmind** [comment]
@jessetechie if you look at the [index definition](https://github.com/JasperFx/marten/blob/c15223d88e1afc93246301087b48b8192e597fb0/src/Marten/Schema/DocumentMapping.cs#L353) being created for SoftDeletedWithIndex, there is a predicate on `mt_deleted` which is a partial index. So I believe your queries on soft deleted documents should work fine.

With regards to index character limit, you can set the index name as below:
```csharp
storeOptions.Schema.For<MyDoc>()
    .SoftDeletedWithIndex(x => x.Name = "my_index");
```

Please check and revert to us.

**Comment by oskardudycz** [comment]
Closing this because of the inactivity. @jessetechie if the [suggestion provided by @mysticmind](https://github.com/JasperFx/marten/issues/2534#issuecomment-1529955380) didn't help, please ping us and we'll reopen it.
