### ISSUE TITLE
IUnitOfWork.AllChangedFor does not return tracked objects by BaseType

### ISSUE THREAD

**Issue by bojanv91** [JasperFx/marten#254]
I hit issue working with `DocumentSessionListener` and `BeforeSaveChanges` method.

Example entity:
```
public abstract class BaseEntity 
{
   public DateTime CreatedOn { get; set; }
}

public class Customer : BaseEntity
{
}
```

Usage:
```
session.Store(new Customer());
session.SaveChanges();
```

The listener which should set current datetime to `CreatedOn` property.
```
public override void BeforeSaveChanges(IDocumentSession session)
{
  var utcnow = DateTime.UtcNow;
  foreach (var entity in session.PendingChanges.AllChangedFor<BaseEntity>()) {
    entity.CreatedOn = utcnow;    // It never goes inside the loop
  }
}
```

My expectation is that the above scenario would work - AllChangedFor<> should return all objects that derive from the given type.

I spot the problem at this line: https://github.com/JasperFx/marten/blob/5315ef52fc0cc6cee3c2152fa54559c022d23527/src/Marten/Services/UnitOfWork.cs#L103

**Comment by jeremydmiller** [comment]
I've got the fix coming in 0.8.5 within an hour
