### ISSUE TITLE
Hilo table is getting erroneously re-generated

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#255]
As reported on Gitter the other night. Put it into AutoCreate == All, blows away the hilo table and re-generates. Not sure when this would have creeped in, or why it's happening.

**Comment by jeremydmiller** [comment]
Got it. We're getting messed up with schema name canonization after introducing the configurable schemas

**Comment by tim-cools** [comment]
@jeremydmiller Damn, missed that one. Nice catch...

**Comment by jeremydmiller** [comment]
@tim-cools I wanna at least think about putting in some kind of value object for "schema, name" pairs to keep this from creeping in again.

**Comment by tim-cools** [comment]
@jeremydmiller I thought the same this morning. Extracting this in some kind of DatabaseObjectReference object that exposes the Name and QualifiedName...
I might look into this if I find some free time this week
