### ISSUE TITLE
Couldn't find _.Projections.Snapshot<T>(SnapshotLicecycle) is the documentation outdated?

### ISSUE THREAD

**Issue by rosdi** [JasperFx/marten#2555]
I am following the documentation here: https://martendb.io/events/projections/#snippet-sample_registering-quest-party

But I couldn't find this Snapshot method in marten 5: https://github.com/JasperFx/marten/blob/02d321ccb25b5bf62c5c7e5a9f7ea528e0d439f1/src/EventSourcingTests/Projections/inline_aggregation_by_stream_with_multiples.cs#L45

Is the documentation outdated? The closest I could find is `_.Projections.Add<T>(ProjectionLifecycle.Inline);`

**Comment by rosdi** [comment]
Nevermind..., should have check the proj file first..., the sample code is using Marten 6 RC

**Comment by mysticmind** [comment]
@rosdi  The docs point to the latest. We will look at enabling docs for 4.x and 5.x. Currently there is only 3.x and the latest.
