### ISSUE TITLE
Support database timestamps on changes

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#256]
Make an opt in configuration that adds an automatic timestamp field to the document tables?

It's dirt simple to do this in .Net code with the `IDocumentSessionListener`, but some folks are not gonna trust server clock synchronizations and want the database to do that.

**Comment by maggiepint** [comment]
I'll take a stab at this.

**Comment by jeremydmiller** [comment]
@maggiepint Hey, I knocked this one out tonight just to start clearing more issues. There's definitely going to be more stuff like this in the future if you're interested.

**Comment by maggiepint** [comment]
My bad. I've been thinking of that issue and ending up with one thing or
another being more important for, well, quite a while as you can see :-)
