### ISSUE TITLE
how to set ValueCasting?

### ISSUE THREAD

**Issue by jerry-sileon** [JasperFx/marten#2563]
The document on ValueCasting still has ToDo so I guess I need to ask here... Using Marten 5.11, I am trying to set ValueCasting and leave everything as it is. How does one do that?

To give some background information, we're saving dates as UTC ISO8601 strings everywhere, but when Marten reads a document and has to save it again after something changes, the date values are set at server timezone and in an unpredictable format. We really need those strings to remain strings. (If ValueCasting is not the way to do it, please let me know! :) )

In a project's `Startup.cs` we do this for injecting the DocumentStore wherever it is needed:
```
services.AddSingleton<IDocumentStore, DocumentStore>();
// ...
services.AddMarten(options =>
{
  options.Connection(BuildPostgresConnectionString());
}
```
(Again, if this is not the right way, please let me know!)

Any feedback is much appreciated!

**Comment by oskardudycz** [comment]
@jerry-sileon, could you expand on what do you mean by ValueCasting?

**Comment by jerry-sileon** [comment]
Well, I found this page:
https://martendb.io/configuration/json.html

It sounds like it is what we need, but I am not sure. The problem is this. We have documents with dates in UTC in ISO formatted strings (we are using strings to prevent conversion, it is a different discussion on why we want this but it's become a requirement now). When Marten reads a document, it converts those ISO strings to a date and when Marten writes the document again, the date is NOT in UTC and NOT in ISO string.

So we are looking for a way to either prevent Marten from converting the ISO strings to date objects. (As far as I can tell, ValueCasting was the way to do this but there could be a different way.)
Or, if it is easier, we would like to tell Marten to write ISO strings AND in UTC.

Does this make sense?

**Comment by jerry-sileon** [comment]
@oskardudycz , any help in this is much appreciated. I am trying to avoid a solution like adding a prefix to the date string to prevent Marten to try and interpret the string as a date.

It's either telling Marten not to convert stuff or to tell Marten, when it writes a date/time back to the document, to always use UTC timezone and ISO8601.

Thanks!

**Comment by jerry-sileon** [comment]
@jeremydmiller @oskardudycz 
Digging and debugging some more, I am starting to see that it is happening in this part of the process:

1. marten reads DB document
2. marten converts JSON to object: here the ISO8601 string is converted to a DateTIme object
3. object is converted to `Customer` object: here the DateTIme object is converted to a string

Where in the code is the conversion from plain object (deserialised from the JSON) into our own class?

I could try and make .net use a proper serialisation for the DateTime value into an ISO8601 string using the UTC date (step 3). But I would really like to stop converting DateTime values completely (step 2). So I think the ValueCasting option is the one I would like to use. Back to the original question: how do I set the ValueCasting? The documentation says there is an example under the JIL header but it is not clear enough (for me).

**Comment by jerry-sileon** [comment]
It sounds a bit overkill to implement a whole new ISerializer just to set ValueCasting.

**Comment by oskardudycz** [comment]
@jerry-sileon AFAIK, we're not doing any casting of the date. We're following the Npgsql behaviour, and the suggested is to, in general, use `DateTimeOffset`, Npgsql will do the automatic conventions in some cases on the DateTime object depending on the kind. See more at https://www.npgsql.org/doc/types/datetime.html.

**Comment by jerry-sileon** [comment]
@oskardudycz , the documentation on ValueCasting with Strict as the default says it is converting the strings in the JSON to types it recognises.

I got some good results using a custom ISerializer with ValueCasting.Relaxed and it works as expected: date strings in ISO format stay as such.

One problem I am having with that is that I needed to implement *everything* from ISerializer just to override the ValueCasting setting, which was a bit much. Especially since it appeared that the method `public T FromJson<T>(Stream stream)` gave an error. I debugged and the stream appeared to have an SOH character (\u0001) at the beginning. I was not able to find whether that one was added by PG or Marten but when I removed it everything went as expected.

```c#
    public T FromJson<T>(Stream stream)
    {
        var reader = new StreamReader(stream);
        var s = reader.ReadToEnd();
        s = s.Replace("\u0001", string.Empty);
        return JsonConvert.DeserializeObject<T>(s);
    }
```

I could not find the default serializer to override or even include, that would make things a bit easier.

**Comment by oskardudycz** [comment]
@jerry-sileon, could you provide us with a failing test scenario? It'd be easier to evaluate if that's something we'll support out of the box or not. We'd need your configuration and sample documents.

Regarding SoH, check the System Text Json implementation:
- https://github.com/JasperFx/marten/blob/master/src/Marten/Services/SystemTextJsonSerializer.cs#L65
- https://github.com/JasperFx/marten/blob/9a1a67f8c5a7c7697f3697f37a14fff465a9c35c/src/Marten/Util/StreamExtensions.cs#L15

StreamExtensions are internal, but if that helps, we may consider making them public. Still, before that, I'd need to understand your use case better.

**Comment by oskardudycz** [comment]
@jerry-sileon I'm closing this issue because of the inactivity, please ping us with reproduce steps and we'll reopen the issue.
