### ISSUE TITLE
ApplyAllConfiguredChangesToDatabaseAsync() does not create the database even if specified

### ISSUE THREAD

**Issue by Maicelicious** [JasperFx/marten#2564]
Hello everyone,

I am using Marten as my DocumentStore Library in multiple applications.
In one of my newest applications the version 6.0.0-alpha.9 is used (for now).
I got to the case where I wanted to retry a DatabaseConnectionFailure at startup.
In a previous application I used the version 5.11.0 and there it is already implemented and working in production.
So then I got to a point where I did the same as in the other application (An example project can be found attached of the case).
So I catch the ErrorCase that the db is not available and then retry infinitely when this occurs.
And then I start the database and this should result in a creation of a database with all schemas but and exception is thrown that the database does not exist.
I tried upgrading the version to 6.0.0-rc.1 but it results in the same issue.

Kind regards,
Marco

[MartenBug_verison_rc1_and_alpha9.zip](https://github.com/JasperFx/marten/files/11330646/MartenBug_verison_rc1_and_alpha9.zip)

**Comment by mysticmind** [comment]
@Maicelicious  I did take a look at the zip which contains compiled code which will be difficult to inspect. It would help if you could provide repro code so that we can take a look.

**Comment by Maicelicious** [comment]
Hi @mysticmind,
I added the code to a repository: https://github.com/Maicelicious/MartenApplyAutoCreateBeforeRun
Thank you for looking at the issue.

**Comment by mysticmind** [comment]
Thanks @Maicelicious, I am taking look at this today, will keep you posted.

**Comment by JT-Bruch** [comment]
Running into the same issue here.

**Comment by Maicelicious** [comment]
The Issue still exists in Marten Version 6.0.0.

**Comment by jeremydmiller** [comment]
Add `ApplyAllDatabaseChangesOnStartup()` to your set up code for the separate document store
