### ISSUE TITLE
Using `Casing.CamelCase` together with `SerializerType.SystemTextJson` breakes using of `IQueryable.Select()`

### ISSUE THREAD

**Issue by laya-alsh** [JasperFx/marten#2593]
Hello,

i probably found a problem when `Casing.CamelCase` is used together with `SerializerType.SystemTextJson`:
```c#
options.UseDefaultSerialization(
    EnumStorage.AsString,
    serializerType: SerializerType.SystemTextJson,
    casing: Casing.CamelCase,
    nonPublicMembersStorage: NonPublicMembersStorage.All
);
``` 

When doing a `.Select()` projection, the data is not correctly deserialized/mapped:

![image](https://github.com/JasperFx/marten/assets/110024370/5d566a17-d9d5-461c-b73a-0e8e058196f9)

..when evaluating the data (with `.ToList()`) before executing `.Select()`, it works, so i can assume it has something to do with marten's logic..

Is it a bug or my wrong configuration?

---

I forked your example repository and made 2 tiny changes in `Tickets` sample:
https://github.com/oskardudycz/EventSourcing.NetCore/commit/b59eee3dae2fab9813cc042c9ca272fb8ee8e72c

In order to reproduce this behavior:
1. clone my forked repo https://github.com/laya-alsh/marten-select-bug
2. run `docker compose up -d postgres` from the root
3. start `Sample\Tickets\Tickets.sln` solution in debug mode
4. place a breakpoint in `Tickets\Reservations\GettingReservationById\GetReservationById.cs` (like on a screenshot above)
5. in swagger
- create any reservation with `POST /api/Reservations` endpoint
- copy the result and use it in `GET /api/Reservations/{id}` endpoint
- you will land at breakpoint and can observe the problem

Thanks!

**Comment by oskardudycz** [comment]
Thanks, @laya-alsh, for the detailed reproduction steps. The fix is underway https://github.com/JasperFx/marten/pull/2612 :)
