### ISSUE TITLE
Skip/take/projection query returns all records

### ISSUE THREAD

**Issue by tim-cools** [JasperFx/marten#260]
The query in the following PR https://github.com/JasperFx/marten/compare/master...tim-cools:Skip-take-projection-query-does-return-all-records?expand=1 should return 10 records instead of 100.

```
            Add100Users();
            var ids = theSession.Query<User>()
                        .Skip(10)
                        .Take(10)
                        .Select(entity => entity.Id)
                        .ToArray();

            ids.Length.ShouldBe(10);   // instead of 100
```

**Comment by jeremydmiller** [comment]
@tim-cools I'm looking at this now.

**Comment by jeremydmiller** [comment]
@tim-cools Going to call this one a Relinq issue so far. It loses the ResultOperators collection when it bounces to the Select(). Surely a workaround somewhere.

**Comment by jeremydmiller** [comment]
Got it. It'll be in a new nuget later this morning. Would have been a systematic thing with any other result operator.
