### ISSUE TITLE
Async projections lose events in concurrent scenario

### ISSUE THREAD

**Issue by jaceks2106** [JasperFx/marten#2606]
**Short domain description**
We have app for creating public Events. When multiple users organise some event, they want to make changes on Todos page at the same time. So any change on this page produces Domain Events such as "EventTodoSaved", "EventTodoRemoved", "EventTodoChecked" and so on. The problem shows up, when changes are done concurrently.

**What is the problem?**
Inline aggregate projection is updated properly. When todo is changed, inline projection is built without losing any domain events. But when it comes to async projection, it saves projection with randomly chosen events, which I cannot predict. I want really badly to achieve that in async manner, because I treat them as a read models, which are recreated in eventual consistency way. 

**Marten configuration**

```c#

services.AddMarten(_ =>
    {
        _.Connection(configuration.GetConnectionString("Db"));
        _.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
        _.GeneratedCodeMode = LamarCodeGeneration.TypeLoadMode.Auto;

        // Events
        // registering some events for EventTodos manipulation

        // Aggregates
        _.Projections.SelfAggregate<EventTodosAggregate>(ProjectionLifecycle.Inline);

        // Read models
        _.Projections.Add<EventTodosProjection>(ProjectionLifecycle.Async);
    })
    .UseLightweightSessions()
    .ApplyAllDatabaseChangesOnStartup()
    .AddAsyncDaemon(DaemonMode.HotCold);
```

EDIT:/ I found that EnableTrackingByIdentity option was solving the issue, but I do not see this option anymore.

Best regards

**Comment by oskardudycz** [comment]
Hi, we'd need to understand better what your projections look like. What you're describing is not the usual behaviour. Could you provide your EventTodosProjection definition?

EnableDocumentTrackingByIdentity is available from v6; see docs: https://martendb.io/events/projections/event-projections.html#reusing-documents-in-the-same-batch. But the intention behind it is to support advanced scenarios where you're doing additional manipulation on a document manually, without the default mechanics. Default options should cover most of the common cases.

**Comment by jaceks2106** [comment]
Sure,

Here you have EventTodosProjection:

```c#
public class EventTodosProjection : EventProjection
{
    public async Task Project(EventTodoSavedDomainEvent evt, IDocumentOperations ops)
    {
        var doc = await ops.LoadAsync<EventTodosModel>(evt.EventId);
        doc ??= new()
        {
            EventId = evt.EventId,
        };

        var todo = doc.Todos.SingleOrDefault(x => x.Id == evt.TodoId);
        if (todo == null)
        {
            doc.Todos.Add(new EventTodo
            {
                Id = evt.TodoId,
                Name = evt.Name,
                Checked = false,
            });
        }
        else
        {
            todo.Name = evt.Name;
            todo.Checked = evt.Checked;
        }

        ops.Store(doc);
    }

    public async Task Project(EventTodoRemovedDomainEvent evt, IDocumentOperations ops)
    {
        var doc = await ops.LoadAsync<EventTodosModel>(evt.EventId);

        doc.Todos.RemoveAll(x => x.Id == evt.TodoId);

        ops.Store(doc);
    }
}
```

EventTodosModel:
``` c#
public sealed class EventTodosModel
{
    [Identity]
    public Guid EventId { get; set; }

    public List<EventTodo> Todos { get; set; } = new List<EventTodo>();
}
```

**Comment by oskardudycz** [comment]
@jaceks2106 thank you for the follow-up. Indeed, if you're using such a projection, you have to use `EnableDocumentTrackingByIdentity` property. Marten processes async projections in batches, and it calls the Apply functions sequentially within the batch. 

By the way, is there any reason you're not using regular SingleStreamProjection or MuliStreamProjection? If you used them, you'd have the most benefit of the projections, and it could simplify your case a lot (also, you wouldn't need to use the mentioned setting). Read more about our projections in my article: https://event-driven.io/en/projections_in_marten_explained/

Could you also expand on how you recognise that events are "randomly chosen"? What exact symptoms did you observe?

**Comment by jaceks2106** [comment]
Ok, I will try this SingleStreamProjection.

To be honest, I misunderstood the concept of Event Projections. Their purpose is to process side effects, based on some singular events, without the context of specific stream, isn't it?

Randomly chosen means, that I cannot predict, which event (EventTodoSaved) will win the race :). Once we add multiple todos at the same time (e.g. 10 new todos with content "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"), the final readmodel will contain randomly considered new todos (race condition), e.g. 0, 3, 7, 9 or 1, 5, 7, 8.

Will answer soon once I update the code and make some tests ;)

**Comment by oskardudycz** [comment]
> Update: Works like a charm :)

Great, so I'm closing the issue.

> Their purpose is to process side effects, based on some singular events, without the context of specific stream, isn't it?

Event projections could be called "do-whatever-you-want-with-events" - typically, we recommend that for more sophisticated cases. They still give some boilerplate removal compared to raw `IProjection` implementation, but yeah, we recommend them when neither of the other projections suffice.

Still, that:

> Randomly chosen means, that I cannot predict, which event (EventTodoSaved) will win the race :). Once we add multiple todos at the same time (e.g. 10 new todos with content "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"), the final readmodel will contain randomly considered new todos (race condition), e.g. 0, 3, 7, 9 or 1, 5, 7, 8.

Intrigues me, as we have the order guarantee of the event processing. Could you send us some reproduce steps to achieve that?

**Comment by jaceks2106** [comment]
> Intrigues me, as we have the order guarantee of the event processing. Could you send us some reproduce steps to achieve that?

I suppose that it's concurrency "last write wins". So, when two concurrent commands adds new todos (3 and 4), projection loaded old document which had previously added [0, 1, 2], then first command will save [0,1,2,3], but concurrently second command will override read model with [0,1,2,4]. But it's my suspicion.
