### ISSUE TITLE
Security: Marten logging exposes connections strings to logs

### ISSUE THREAD

**Issue by elexisvenator** [JasperFx/marten#2614]
In the past we have had issues with `MartenCommandException` including the `NpgsqlCommand` in the exception. This led to PII issues where sensitive information in the sql query parameters was exposed in logs.

Last week we had a security incident when we identified secure database credentials including passwords had been sent to our centralized logging system. The underlying exception was a `System.OperationCancelledException` - a query running too long. But the resulting log had the following included in the Error.StackTrace.Data property:

```json
{
    "NpgsqlCommand": {
        "AllResultTypesAreUnknown": false,
        "CommandText": "select data, type, mt_dotnet_type, seq_id, id, stream_id, version, timestamp, tenant_id, correlation_id, causation_id, headers, is_archived from <censored>.mt_events as d WHERE (d.is_archived = FALSE and  d.tenant_id = :p0 and  d.stream_id = :p1) ORDER BY d.seq_id",
        "CommandTimeout": 30,
        "CommandType": 1,
        "Connection": {
            "CanCreateBatch": true,
            "CommandTimeout": 30,
            "ConnectionString": "Host=<censored>.rds.amazonaws.com;Port=5432;Database=<censored>;Username=<censored>",
            "ConnectionTimeout": 15,
            "DataSource": "",
            "Database": "<censored>",
            "FullState": 0,
            "IntegratedSecurity": false,
            "Port": 0,
            "Settings": {
                "Database": "<censored>",
                "Host": "<censored>.rds.amazonaws.com",
                "Password": "<censored!!!!!!!!!!!!!!!!>",
                "Port": "5432",
                "Username": "<censored>"
            },
            "State": 0,
            "UserName": "<censored>"
        },
        "DesignTimeVisible": false,
        "IsPrepared": false,
        "Parameters": [
            {
                "DataTypeName": "text",
                "DbType": 16,
                "Direction": 1,
                "IsNullable": false,
                "NpgsqlDbType": 19,
                "NpgsqlValue": "<censored>",
                "ParameterName": "p0",
                "Precision": 0,
                "Scale": 0,
                "Size": 0,
                "SourceColumn": "",
                "SourceColumnNullMapping": false,
                "SourceVersion": 512,
                "Value": "<censored>"
            },
            {
                "DataTypeName": "text",
                "DbType": 16,
                "Direction": 1,
                "IsNullable": false,
                "NpgsqlDbType": 19,
                "NpgsqlValue": "<censored>",
                "ParameterName": "p1",
                "Precision": 0,
                "Scale": 0,
                "Size": 0,
                "SourceColumn": "",
                "SourceColumnNullMapping": false,
                "SourceVersion": 512,
                "Value": "<censored>"
            }
        ],
        "Statements": [],
        "UpdatedRowSource": 3
    }
}
```

This is the full content of the `NpgsqlCommand` object, complete with connection string (note that the password is not in the string, as the setting `Persist Security Issue=false` was configured). Inside the connection class though there is a "settings" class which contains the connection string again including password.

As a workaround, we have modified our opentelemetry to include a filter that strips the "data" property from exceptions.

The command object is attached [here](https://github.com/JasperFx/marten/blob/8840c189566cc80f46e557786c0a56c05dfb8899/src/Marten/Internal/Sessions/QuerySession.Connection.cs#L112C1-L118C6) and [here](https://github.com/JasperFx/marten/blob/985cc5e015392db5e3f869be9624235993ceea2f/src/Marten/Exceptions/MartenExceptionTransformer.cs#L39-L47). The intention appears to be to help include the query in logs for debugging, but far too much sensitive information is also included, and it appears that neither `NpgsqlCommand` nor any of its child properties were ever intended to be safely serialised. 

Is it possible to get a review of the value of adding the command to console logs, and if there is still command, an option to disable this functionality in production environments? Or maybe some cleverness needs to be done to extract the important information from the command object for logging.

**Comment by jeremydmiller** [comment]
As a cheesy, quick fix, I'm having that exception do in effect a clone of the NpgsqlCommand so that you get the command information, but not the connection.

**Comment by elexisvenator** [comment]
@jeremydmiller This definitely fixes the connection string issue but there is still the concern that by including the sql parameters that sensitive client information will be logged (eg serialised events)
