### ISSUE TITLE
Snapshot subclasses create extra tables

### ISSUE THREAD

**Issue by markotny** [JasperFx/marten#2629]
I'm having some issues trying to get EventStore working with hierarchies (latest version 6.0.3).
Here's my config (full repro code [here](https://github.com/markotny/MartenSubClassAggregateTest)):
```csharp
	options.Schema.For<Foo>()
		.AddSubClass<Bar1>()
		.AddSubClass<Bar2>();

	options.Projections.Snapshot<Bar1>(SnapshotLifecycle.Inline);
	options.Projections.Snapshot<Bar2>(SnapshotLifecycle.Inline);
	options.Projections.Snapshot<Foo>(SnapshotLifecycle.Inline);
```

When using the `ApplyAllDatabaseChangesOnStartup()`, it seems that the tables are created for the subclasses though only the base class table is actually used to store projections. Interestingly, not all subclasses seem to have tables created (in my example, the base `foo` base class and the `bar1` subclass have tables created, but not `bar2`.

I also found another thing though I'm not sure if Marten supports this scenario, where the base class is _not abstract_ and can handle events on its own?
I had to declare the `Foo` projection last, otherwise `Foo` objects are stored as one of the subclasses. If it's declared last then it works, though when looking at the SQL executed when inserting event consumed by the base class, it seems the `mt_upsert_foo` command is executed three times, once as `bar1`, then as `bar2` and finally as `foo`. I understand that's because of the order in which I declared the projections and each projection type has an inherited `Apply(FooCreated event)` method.
If I make the `Foo` abstract and only store events for subclasses, upsert commands are correct but the schema still has the extra table. I also found a similar issue #1912 but it was closed as it was on old version

**Comment by jeremydmiller** [comment]
@markotny This isn't a scenario that Marten has ever directly supported before. It has absolutely nothing to do with whether the base class is concrete, abstract, or interface. And the only way this would ever work is if your three aggregates all supported completely different events.

You could more easily pull this off with a custom aggregate where you're dealing with the subclass selection yourself.

**Comment by markotny** [comment]
I see, using a simple CustomProjection<Foo> to handle the events instead of the snapshot-per-subclass indeed no longer produces the additional tables so this issue can be closed :) [Here's the working code](https://github.com/markotny/MartenSubClassAggregateTest/blob/custom_aggregation/MartenSubClassAggregateTest/Foo.cs#L48) in case anyone ever tries the same thing I did.
Thanks!
