### ISSUE TITLE
`codegen write` does not generate `*Provider.cs` for `LiveStreamAggregation`

### ISSUE THREAD

**Issue by agross** [JasperFx/marten#2645]
After upgrading from Marten 6.0.2 to 6.0.4 `dotnet run -- codegen write` no longer creates `*Provider.cs` files for `LiveStreamAggregation`s registered in the Marten config.

Probably related to the changes in 6.0.3 where tables for `LiveStreamAggregations` are no longer created in the DB schema. Generating providers might also have gotten lost in the process of making that change.

**Comment by devployment** [comment]
Most likely introduced by my bug report  https://github.com/JasperFx/marten/issues/2610
