### ISSUE TITLE
Append Tombstone events immediately after known set of failures

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#2658]
I think that we should consider appending Tombstone Events immediately. For some scenarios, unique constraints may be obvious enough to do that.

@jeremydmiller pointed out that
> It's maybe simpler than a "retry", which never really works. Have the tombstoning spawn an isolated connection. The "retry" we have doesn't really work because the connection is often put into an unusable state.

**Comment by jeremydmiller** [comment]
It does append the tombstone events immediately, but uses the existing session. We should isolate that, and use the new retry block
