### ISSUE TITLE
NGramIndex is always dropped & recreated

### ISSUE THREAD

**Issue by masterpoi** [JasperFx/marten#2663]
We've noticed that our NGram indexes are always being emitted in the DDL created by the schema generator (even when there is no reason to do so / index is identical) 

For instance:
```sql
      drop index if exists public.mt_doc_storedmessage_idx_ngram_body;
      drop index if exists public.mt_doc_storedmessage_idx_ngram_subject;
      CREATE INDEX mt_doc_storedmessage_idx_ngram_body ON public.mt_doc_storedmessage USING gin (mt_grams_vector( data ->> 'Body'));
      CREATE INDEX mt_doc_storedmessage_idx_ngram_subject ON public.mt_doc_storedmessage USING gin (mt_grams_vector( data ->> 'Subject'));
```

Looking at the canonicalized ddl in IndexDefinition's,  "Matches"  i see these values:

```
expected:  
create index mt_doc_storedmessage_idx_ngram_body on public.mt_doc_storedmessage using gin mt_grams_vector data->>'body'
actual: 
create index mt_doc_storedmessage_idx_ngram_body on public.mt_doc_storedmessage using gin mt_grams_vectordata->>'body'
```

The extra space in `expected` seems to originate here:
https://github.com/JasperFx/marten/blob/054e99f6e5d6005462fb6904612d9f8625ce7276/src/Marten/Schema/NgramIndex.cs#L47

But i'm not 100% sure the bug is here or in the parser.

**Comment by mysticmind** [comment]
Most likely a bug, will have a look and keep you posted.

**Comment by oskardudycz** [comment]
@masterpoi which version are you using? I fixed inversion 6.0.5 some issues to the FTS indexes diffs.

**Comment by masterpoi** [comment]
I was using an older version, but I've now tried 6.0.5. Same issue.

**Comment by oskardudycz** [comment]
Could you provide us your config? This may be needed to troubleshoot.

**Comment by masterpoi** [comment]
Here's how we configure Marten:

```csharp
  builder.Services.AddMarten(options =>
        {
            var cc = builder.Configuration.GetConnectionString("pmail") ;
            
            options.MultiTenantedWithSingleServer(cc)
                .WithTenants("<redacted>").InDatabaseNamed("<redacted>");
            options.RegisterDocumentType<StoredMessage>();
            
            options.Schema.For<StoredMessage>()
                .UseOptimisticConcurrency(true)
                 .NgramIndex(static x => x.Body)
                 .NgramIndex(static x => x.Subject)
                .Duplicate(static x=> x.MessageId)
                .Duplicate(static x => x.Receiver.Id) // "PARTITION KEY"
                .Duplicate(static x => x.Received)
                .IndexLastModified()
                .Duplicate(static x => x.Read!)
                .Duplicate(static x => x.Deleted!)
                .Duplicate(static x => x.Folder)
                .Duplicate(static x => x.Topic)
                .Duplicate(static x => x.Sender.Name)
                .Duplicate(static x => x.SenderRole);


            
            options.Policies.ForAllDocuments(static m =>
            {
                if (m.IdType == typeof(Guid))
                {
                    m.IdStrategy = new CombGuidIdGeneration();
                }
            });
        
        }).ApplyAllDatabaseChangesOnStartup();
        
        ```

**Comment by oskardudycz** [comment]
@masterpoi, thank you 👌

**Comment by mysticmind** [comment]
There are couple of ways to fix this:
- Change `get => new[] { $"mt_grams_vector( {_dataConfig})" };` to `get => new[] { $"mt_grams_vector({_dataConfig})" };` by removing space space after `(`.
- A better fix will be to update `IndexDefinition.CanonicizeDdl(...)` to replace `(<one_or_more_spaces>` by `(` and `<one_or_more_spaces>)` to `)`. This way the diff check can be more tolerant to deal with spaces.

**Comment by oskardudycz** [comment]
@mysticmind thank you for your investigation. I plan to move the Full-Text search index definition from Marten to Weasel, together with tests. That should help stabilise it and have a single source of truth.

**Comment by mysticmind** [comment]
The changes what I have proposed to do is in existing Weasel code.

**Comment by oskardudycz** [comment]
Yes, I'm aware of that, as I was just recently changing that place to fix the other issue https://github.com/JasperFx/weasel/pull/94 🙂

**Comment by mysticmind** [comment]
got you.

**Comment by mysticmind** [comment]
I already have a fix, just have to add a unit test.

**Comment by mysticmind** [comment]
PR https://github.com/JasperFx/weasel/pull/96 added as a fix for this.
