### ISSUE TITLE
SingleStreamProjection throws  Marten.Exceptions.InvalidProjectionException for invalid Create method using Marten 6.0.5

### ISSUE THREAD

**Issue by Thorstensen** [JasperFx/marten#2675]
Hello.

First and foremost, thanks for a superb library!

We're trying to create a read model of our events by using the `SingleStreamProject<T>` base class, but we're always facing the same validation issues. I've come to the conclusion, after reading the documentation thoroughly, that I might ask here as we're unsure what we are doing wrong. 

So we have a really simple projection: 

```
public sealed class StatisticsProjection : SingleStreamProjection<Statistics>
{
    public Statistics Create(Registered @event)
    {
        return new Statistics 
        {
            Id = @event.Id
            ....
        };
    }
} 
```

Registered the following way: 

`options.Projections.Snapshot<StatisticsProjection>(SnapshotLifecycle.Async);`

Throws the following exception during start up: 

```
Marten.Exceptions.InvalidProjectionException: Projection Marten.Events.Aggregation.SingleStreamProjection<Infrastructure.Projections.StatisticsProjection> has validation errors:
Create(Registered) : Statistics
 - Return type 'Infrastructure.Projections.Statistics' is invalid. The valid options are System.Threading.CancellationToken, Marten.IQuerySession
```

What am I missing here?  Again thanks!

**Comment by Thorstensen** [comment]
For projections, the registration should use `options.Projections.Add` instead of `options.Projections.Snapshot`. Closing this issue..

**Comment by mysticmind** [comment]
@Thorstensen thanks for the heads up and figuring out the issue yourself.
