### ISSUE TITLE
Adding nested object containment 

### ISSUE THREAD

**Issue by nieve** [JasperFx/marten#268]
The following code will fail today:
```csharp
var address = new Address { Number = 5, Street = "foo st.", City: "Hem" };
var user = new User { Name = "user 1", Address = address };

theSession.Store(user);
theSession.SaveChanges();

var userFromDb = theSession.Query<User>().Where(x => x.Address == address).Single();
userFromDb.ShouldNotBeNull();
```
Should be feasible as this returns true in pg: 
`SELECT '{"goo": 5, "foo": {"bar": "baz"}}'::jsonb @> '{"foo": {"bar": "baz"}}'::jsonb;`

**Comment by nieve** [comment]
I'll be happy to do this, unless anyone thinks this isn't a good idea :)

**Comment by nieve** [comment]
I believe this is not as important a feature as I thought it would be.
This can be achieved with something like:
`var user = theSession.Query<User>().Where(x => x.Address.Number == number && x.Address.Street == street && x.Address.City == city).Single();`
Don't think this will be frequently needed. 
@mdissel - what do you think? Would you still like to see this feature in?

**Comment by jeremydmiller** [comment]
@nieve I finally read this closely enough, I say to shut this down. We'd never be able to "know" how to do the equality checks here against non-simple types.
