### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by mattburton** [JasperFx/marten#2680]
After upgrading to Marten 6.0.5 from 5.x, I'm getting the following error when trying to run migrations during startup:
```
[red]ERROR:[/]System.InvalidOperationException: The ConnectionString property has not been initialized.
  at Task Npgsql.NpgsqlConnection.Open(bool async, CancellationToken cancellationToken)                                                      
  at Task Npgsql.NpgsqlConnection.OpenAsync(CancellationToken cancellationToken)                                                             
  at async Task Weasel.Core.Migrations.DatabaseBase`1.executeMigration(ISchemaObject[] schemaObjects, CancellationToken ct)  
  ...
```
This is the result of running:
```
await store.Storage.ApplyAllConfiguredChangesToDatabaseAsync();
```
`store` in this case is a `DocumentStore` that is created using a custom options object where the connection string is passed via `Connection(connectionString);` in the constructor.

I tried upgrading to the latest version of Weasel explicitly as well as I saw mention by @oskardudycz that there were some additional fixes, but that didn't help either. Looking at the code for Marten and Weasel I'm not sure where the disconnect is here - am I doing something wrong or something that isn't supported anymore in 6.x?

**Comment by oskardudycz** [comment]
@mattburton I think that I'd need to know more about your setup. Could you provide us with a sample repo with the reproduce steps?

**Comment by mattburton** [comment]
Hi @oskardudycz - thanks for the quick response - got tangled up at work today, just got a chance to put a repro together. Of course I wasn't able to reproduce my exact issue, but in case it helps here's the repo:

https://github.com/mattburton/marten-issue-2680

It turns out that the migrations do in fact run, it's actually this line that is the culprit:

`var schemas = store.Storage.AllSchemaNames();`

In the repo version it actually works fine, and I've been unable to figure out what the difference is. Basically we are creating a custom options object with a connection string that has permissions to run the migrations, and applying the changes in a hosted service at startup. So the mechanics are identical, but again, not sure what is different about our setup compared to this version.

I messed around with it a bit more and was able to replace the above line with this:

`var schemas = (await store.Storage.Database.DocumentTables()).Select(x => x.Schema).Distinct();`

So problem solved for now on this end, but if you think of anything that might have caused the above issue that might impact us down the road (i.e. we have something misconfigured somehow that's going to bite us later) that would be most appreciated - thanks!

**Comment by jeremydmiller** [comment]
I'm voting to close this as a one off to clean up the issue list.
