### ISSUE TITLE
Daemon enters unrecoverable state if event sequence is higher than high water mark

### ISSUE THREAD

**Issue by Hawxy** [JasperFx/marten#2681]
The gap detector will retry continuously, always returning a null sequence result.
![image](https://github.com/JasperFx/marten/assets/975824/5be1adf8-98e0-4438-9858-da6a8bb6aff8)

**Comment by jeremydmiller** [comment]
@Hawxy I need you to explain this one a bit more. The event sequence should pretty well *always* be higher than the high water mark. 

Is this specifically the case of having **nothing but** gaps between the last known high water mark and the current event sequence?

**Comment by Hawxy** [comment]
> Is this specifically the case of having nothing but gaps between the last known high water mark and the current event sequence

Yes, that was the scenario as I recall.
