### ISSUE TITLE
The Great Linq Overhaul of 2023

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2684]
Master issue and notes to track work for the v7 overhaul of the Linq provider support. This work is well underway already in the `linq` branch.

Goals:

* Eliminate CTE queries as much as possible for child collection filtering
* Utilize containment operator or JSONPath operators instead of CTE's where possible to enable GIN index usage
* Remove the Relinq dependency
* Fix all the open Linq related issues
* Improve the Select() support
* Put the Linq provider on a better technical foundation

**Comment by jeremydmiller** [comment]
## Scenarios for Later

- [ ] `Where(x => x.Target.Children.Any(c => c.StringValue.StartsWith("pre") && c.Children.Any(x => x.StringValue.StartsWith("_"))`
- [ ]

**Comment by jabellard** [comment]
Quick question. Let's say I have this entity:
```c#
public class BookAttribute
{
    public string Key { get; set; }
    public string Value { get; set; }
}
public class Book
{
     public Guid Id { get; set; }
     public List<BookAttribute> Attributes { get; set; }
}
```
Then I write the following queries:
```c#
var resultSet1 = querySession.Query<Book>()
                    .Where(b => b.Attributes.Any(b => b.Key == "myKey") && b.Attributes.Any(b => b.Key == "myValue"))
                    .ToListAsync();
                
var resultSet2 = querySession.Query<Book>()
    .Where(b => b.Attributes.Contains(new BookAttribute { Key = "myKey", Value = "myValue"}))
    .ToListAsync();

```

Query 1 will use CTEs, whereas query 2 will use the containment operator. Do you think it's possible to make query 2 use the containment operator as well?

I'm not a LINQ expert, so I'm just curious.

**Comment by jeremydmiller** [comment]
@jabellard Yes, and that's a first class goal -- but I'm not even completely sure the 2nd would even work today. Does it?

**Comment by jeremydmiller** [comment]
@jabellard If you were curious and had a lot of time on your hands, the "linq" branch is running end to end without Relinq now. The only thing not technically working yet is Marten's compiled query feature anytime it hits containment operators or JSONPath usage.
