### ISSUE TITLE
BuildProjectionDaemonAsync Does Not Use The "tenantIdOrDatabaseIdentifier" Correctly 

### ISSUE THREAD

**Issue by BrettGFleischer** [JasperFx/marten#2686]
Hi there,

I have implemented the `OnApplyEventException().SkipEvent()` policy for projections within my multi-tenanted DB, so that I can take action on specific streams that may have failing events.

When spinning up the async projection daemon and triggering a rebuild on a specific projection, I pass the correct `tenantIdOrDatabaseIdentifier` according to the [documentation ](https://martendb.io/events/projections/async-daemon.html#using-the-async-daemon-from-documentstore): 

```csharp
using var daemon = await session.DocumentStore.BuildProjectionDaemonAsync("MYTENANTID", logger);
await daemon.RebuildProjection<MYPROJECTION>(ct);
```

However, when events are skipped and stored within the _mt_doc_deadletterevent_ table, the _tenant_id_ is set to the default (**`*DEFAULT*`**):

![image](https://github.com/JasperFx/marten/assets/56686138/65f52665-5a6f-4de3-b0e6-744db1b3d6fc)

There seems to be something missing to show deadletter events as multi-tenanted with the correct tenant ID.

@jeremydmiller FYI

**Comment by BrettGFleischer** [comment]
Many thanks @oskardudycz.

**Comment by jeremydmiller** [comment]
@BrettGFleischer @oskardudycz & talked this over this morning. That really doesn't matter. The event sequence id in the dead letter event table refers right back to the event and the actual tenant id. I'm honestly voting to do nothing here. Oskar is looking at a double insert problem w/ dead letter events though.

**Comment by BrettGFleischer** [comment]
Thank you for the feedback, @jeremydmiller. 

Each request uses a scoped instance of our `IQuerySession` and `IDocumentSession` based on the tenant required. 

When using our scoped sessions and querying for all `DeadLetter` events (for a specific tenant due to scoping), the query will return nothing because all `DeadLetter` events are untenanted (**`*Default*`**). 

A custom query can act as a workaround, but this feels like somewhat of an anti-pattern, and therefore, I would ask for you to either:

1.  Populate this column with the tenant that raised the `DeadLetter` event
2.  Remove the ability for multi-tenancy from this document type to avoid future ambiguity

@oskardudycz FYI

**Comment by oskardudycz** [comment]
@BrettGFleischer, I understand your need for convenience, yet as @jeremydmiller wrote, DeadLetterEvent logically links to the event in the global log. If you're using a conjoined tenancy, all the events are placed in the same `mt_events` table; adding a tenant will be a bit artificial. 

Having all of that, I went with your suggestion number 2 and explicitly set `DeadLetterEvent` as single-tenanted, which should remove the tenant from it. 

If you're using a tenanted session, you can always use `AnyTenant` in the queries selector, or create a nested session using `ForTenant` method that will be using the default tenant.

**Comment by BrettGFleischer** [comment]
I agree with your standpoint regarding the importance of adhering to the existing logic within the architecture, even when it may involve sacrificing convenience.

Thank you for the combined effort @jeremydmiller and @oskardudycz, it is much appreciated.
