### ISSUE TITLE
`IChangeListener` registered for Async Daemon on `AsyncListeners` get executed before DB transaction is committed

### ISSUE THREAD

**Issue by svrx** [JasperFx/marten#2691]
**Issue**
`IChangeListener.AfterCommitAsync()` for Async Daemon, registered in `AsyncListeners`, get executed before the actual DB transaction is committed to DB. 

From my observation and review of the code this is the current sequence:
- `ProjectionUpdateBatch.Page` run to DB (`ProjectionUpdateBatch.ApplyChangesAsync()`)
- `IChangeListener` run (`ProjectionUpdateBatch.ApplyChangesAsync()`)
- DB transaction commits (`DocumentSessionBase.ExecuteBatchAsync()`)

**Versions**
At least from version 5 to latest of version 6.

**Impact**
Due to information in docs can be misleading at the least. 
On typical usage scenario to produce side effects across a system, through follow-up actions triggered by events or direct calls, due to the race condition between subsequent reads and commits process still ongoing, resulting in potential errors and inconsistencies.

**Comment by oskardudycz** [comment]
This hook means currently is executing after all the changes to projection were applied. 

I think that if we want to change the behaviour of the AfterCommit hook then it has to be in the major version. Plus we should have the BeforCommit then. I agree that the name is not great but I know that there are  users that depend on the behaviour as is to publish read model changes as I described here: https://event-driven.io/en/publishing_read_model_changes_from_marten/

If we change that then they will lose at-leathe projection were applied.

**Comment by jeremydmiller** [comment]
I think this changes as part of our "First Class Subscription" feature in V7 -- which I'm not sure we've even added to the backlog yet.

**Comment by svrx** [comment]
From my perspective this issue can be closed, as even though semantics can be somewhat misleading, the rationale for current implementation is understandable at light of the "at least once" guarantee. 
For future API should be made clearer, feel free to reopen if useful to keep in backlog for v7.
