### ISSUE TITLE
Re-enable the All() function for Linq support

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2693]
It's gotten busted in the V7 work so far as we've tried really hard to avoid CTE usage, and @jeremydmiller honestly just wants to skip this for the moment and go on to other work

Start by reenabling all the tests in `all_operator`

**Comment by robconery** [comment]
If you could point me in the right direction I would be happy to take a crack at this. I forked - but it's a rather large solution :) and I see the LINQ stuff but not entirely sure I'm looking at the right thing. I did a global find on `all_operator` and couldn't see it.

**Comment by jeremydmiller** [comment]
This is done now in the "linq" branch

@robconery Dunno if you're a Wheel of Time fan Rob, but if you are, wanna try yourself against a Trolloc first before facing a Halfman? That's just about the very most complicated, "I almost want to take hallucinogens before I tangle with it", code in the entire Marten codebase.

**Comment by robconery** [comment]
Oh man I so remember trying to implement LINQ with SubSonic so, so many years ago. Wow. And yeah - I'm happy to do whatever and if you want to assign me something (to make it easier) I'm good with that too. I didn't see a "First Bug" label (I'll look again) and I certainly don't want to take up too much time...

**Comment by jeremydmiller** [comment]
Done in the main branch.
