### ISSUE TITLE
Mechanism to copy Marten data from one database to another

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#273]
For one of my internal teams, they want to be able to easily transfer data from a testing database to their local database for help troubleshooting issues.

**Comment by nieve** [comment]
Were thinking of [pg_dump](http://www.postgresql.org/docs/9.5/static/app-pgdump.html)?

**Comment by jeremydmiller** [comment]
@nieve I am now. That looks easy.

**Comment by nieve** [comment]
Actually, the fact this is so easy makes me wonder if this really should end up _in_ marten. That was one of the biggest wins of building on top of postgresql, no?

**Comment by jeremydmiller** [comment]
Sounds like pg_dump is the way to go here. I'm closing this out.
