### ISSUE TITLE
Marten Session closes connection on sql error making it unusable after an error

### ISSUE THREAD

**Issue by DanCymonz** [JasperFx/marten#2752]
I discussed this on the discord. 

Session.Query<SomeDTO>("Some invalid SQL")

will close the connection after an error making it unusable. This behaviour changed from v5 to v6 and tbh not something i would have expected to happen.
In some cases you might want to keep the session open for diagnostic logging or cleanup. 

I found this while trying to upgrade from 5 to 6 as we have tests that reuse the session in certain circumstances for perf reasons in application integration tests.

**Comment by jeremydmiller** [comment]
This will be addressed by #2887
