### ISSUE TITLE
ArgumentOutOfRangeException - Linq Contains query does not supported on IQuerySession

### ISSUE THREAD

**Issue by gergelyurbancsik** [JasperFx/marten#2754]
Hello.
The contains query is not supported ? 
I try to write a contains query for a simple string field, but the lib throws an exception.

Code snippet:
`
var ids = new[] { "id1", "id1", "id2" };
var result = querySession
    .Query<ProductState>()
    .Where(c => ids.Contains(c.Product.code))
    .ToArray();
            `

Exception:
System.ArgumentOutOfRangeException: 'No members found in this Expression (Parameter 'members')'

Stack:
   at Marten.Linq.Fields.FieldMapping.resolveField(MemberInfo[] members)
Message:
No members found in this Expression (Parameter 'members')

**Comment by jeremydmiller** [comment]
For now, try `c.Product.code.IsOneOf(ids)`
