### ISSUE TITLE
Apply `EditorBrowsable` to now obsolete members like `SelfAggregate`

### ISSUE THREAD

**Issue by gfoidl** [JasperFx/marten#2773]
After https://github.com/JasperFx/marten/pull/2525 the naming with "Aggregation" is gone and the types are obsoleted.
Intellisense lists them (although with an `[deprecated]` note), but I'd like them to be completly hidden from intellisense to
* avoid noise and make it easiert for new users to jump right into the new names
* make it easiert to pick the correct type (i.e. not the oboseleted one and then fix the warning by moving to the new type)

Thus I propose to apply `EditorBrowsable`-attribute to the obsolete members.

Note: this is solely for editors, otherwise no runtime change, i.e. no breaking change.

**Comment by jeremydmiller** [comment]
Go for it, I'd happily take that PR
