### ISSUE TITLE
Documentation Updates for v0.9

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#278]
The pace of Marten development has been absolutely nuts over the past month and I have gotten very far behind in keeping the docs up to date. The following is a task list of the topics that need to be updated in preparation for a v0.9 release. 

If you're willing to help out, please just tag a note in this issue that you're taking it. I'm figuring that we'll update the docs in its current structure, then go for the [new documentation structure](https://github.com/JasperFx/marten/issues/279) in a later wave of effort.

- [ ] Foreign key relationships in Marten
- [x] Event Store basics, append event, fetch stream, etc. This is churning pretty hard right now, so maybe wait for it
- [x] Noop Id strategy for document types that don't have a settable Id member
- [x] Using custom Id strategies
- [x] Comb Guid usage
- [x] Select() transforms
- [x] Case insensitive searches by string - this one I'm thinking will go into ST specs embedded into the docs
- [x] string.Equals Linq searches. See the above
- [x] Generic enumerable searches besides Array's, just the fact that you *can* do `Contains()` searches with `IEnumerable<T>`, `IList<T>`, `List<T>`
- [x] min/max/avg/sum operators in the Linq support
- [x] Request count off of `IQuerySession`. Part of diagnostics?
- [x] Include()'s
- [x] Configuring the schema name, overriding on doc by doc basis, for all, event store objects
- [x] More on fetching and writing JSON directly? May be good enough as is
- [x] Compiled Queries
- [x] Improvements to mapping hierarchies of subclasses

**Comment by nieve** [comment]
Might be a good idea to share the list between a few of us. I'll have a proper look later on today to let you know what I'll be happy to take.

**Comment by jeremydmiller** [comment]
I've got some other stuff to write up, then I was going to announce this on the Gitter room. It's helping to have this in a task list instead of buried in my notebook;)

**Comment by nieve** [comment]
I'll be starting with these and see what else will I be able to take afterwards:
- Select() transforms
- Case insensitive searches by string - this one I'm thinking will go into ST specs embedded into the docs
- string.Equals Linq searches. See the above
- Generic enumerable searches besides Array's, just the fact that you can do Contains() searches with IEnumerable<T>, IList<T>, List<T>
- min/max/avg/sum operators in the Linq support

Fetching JSON & mapping hierarchies are done.

**Comment by jamesfarrer** [comment]
I will take foreign keys

**Comment by jeremydmiller** [comment]
In the past, I've relied on unit tests as much as possible for the example code. Mostly, I just hunt down the existing tests and use them OOTB. It's a lazy way to make the docs, but it's far, far better than nothing.

**Comment by jamesfarrer** [comment]
Plus in theory the unit testing code works :)

**Comment by nieve** [comment]
What's left:
* Event Store basics, append event, fetch stream, etc. This is churning pretty hard right now, so maybe wait for it
* Noop Id strategy for document types that don't have a settable Id member
* Using custom Id strategies
* Comb Guid usage
* Request count off of IQuerySession. Part of diagnostics?
* Include()'s
* Configuring the schema name, overriding on doc by doc basis, for all, event store objects
* Compiled Queries

**Comment by nieve** [comment]
I'll continue with:
Include() 
configuring schema name 
overriding doc name (if this is what you meant)

Any proof reading would be highly appreciated.

**Comment by jeremydmiller** [comment]
@nieve @jamesfarrer Hey, if you don't mind, can you just go click on the checkbox's for the things that are done, or is it not letting you do that w/ permissions?

**Comment by nieve** [comment]
Cool, I tried before I had the permissions and it didn't work.

**Comment by tim-cools** [comment]
I added some info about document id's and added a bit to the db schema name.

**Comment by nieve** [comment]
I'm gonna look into the compiled queries, unless anyone else is keen on doing it..?

**Comment by jeremydmiller** [comment]
@nieve Hold off just a little bit on compiled queries until I'm done w/ #280 maybe. That looks like it could be in later today or tomorrow.

**Comment by jeremydmiller** [comment]
I'm going to take the compiled queries now
