### ISSUE TITLE
Usage of new Npgsql features

### ISSUE THREAD

**Issue by gfoidl** [JasperFx/marten#2787]
Npgsql offers some new features that should be considered in Marten / evaluated for use in Marten.

### Parameters w/ positional placeholders

See [Positional and named placeholders](https://www.npgsql.org/doc/basic-usage.html#positional-and-named-placeholders).

Area: perf-optimization, as Npgsql doesn't need to rebuild the SQL to substitute the named parameters with the PostgreSQL expected positional ones.

Available since Npgsql 6.

### Batch API

Cf. https://github.com/JasperFx/marten/issues/2424 and [Raw SQL mode and new batching API](https://www.npgsql.org/doc/release-notes/6.0.html#raw-sql-mode-and-new-batching-api)

Area: perf-optimization

### DbDataSource and NpgsqlDataSourceBuilder

See [DbDataSource](https://www.npgsql.org/doc/release-notes/7.0.html).
Accept a `DbDataSource` in `StoreOptions.Connection()`, and use that for creating the connections instead of the connection-string.

Area: usability

This would also be useful for hosted scenarios, e.g. Azure PostgreSQL flexible server, where authentication is done via "Managed Identities" and the [access-token needs to be refreshed](https://www.npgsql.org/doc/security.html#auth-token-rotation-and-dynamic-password).

For reference: https://github.com/JasperFx/marten/discussions/2550 mentions that point too.

---

PS: I'd like to contribute to these improvements (at the moment I'm quite busy, but starting with next year I think to have to time in order to dive into this)

**Comment by jeremydmiller** [comment]
Subsuming this into #2887

@gfoidl Can you follow into that issue and chime in? @oskardudycz did the work to move us to DbDataSource

**Comment by gfoidl** [comment]
@jeremydmiller sure, thanks for moving this forward. I try (and like) to help where I can.

Side note: ATM I'm working on a larger project with Marten 6.x, and when things in that project stabilize I'll give Marten 7-prereleases a try to see how it goes in production.
