### ISSUE TITLE
Consider using central package management.

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#2804]
We could try to make dependencies management easier via central package management as @gfoidl suggested in https://github.com/JasperFx/marten/pull/2789#discussion_r1400711573.

**Comment by jeremydmiller** [comment]
I'm voting no on this one. We don't have that many projects, and that central package thingies doesn't have any equivalent to Paket's lock file, so there's no reproducible builds.

**Comment by Xeinaemm** [comment]
@oskardudycz I can pick up this one. I looked at MSBuild stuff and there is room for improvement. CPM is only one feature to consider based on @gfoidl's comment.

**Comment by jeremydmiller** [comment]
Just not happening, and I really need the issue list slimmed down just to find things easier. Would be way more helpful for Wolverine though.
