### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#2822]
I'm reopening the feature request from @darky https://github.com/JasperFx/marten/issues/2639. I might be working on it in the next month. Already did some thought process around it.

### Discussed in https://github.com/JasperFx/marten/discussions/2799

<div type='discussions-op-text'>

<sup>Originally posted by **darky** July  7, 2023</sup>
Would be great to have REST API for exposing **Marten** outside of .NET community</div>

**Comment by gfoidl** [comment]
REST implies HTTP-based. Is gRPC also considered?
I don't know what will be better for usage, but I see advantage for gRPC as a strong contract of the API can be defined with the proto-files. Sure, to some extend that can be done for REST with OpenAPI too, but it's way weaker.

**Comment by oskardudycz** [comment]
Yes, gRPC is also considered, although I'm not an extreme fan of gRPC tbt.

**Comment by jeremydmiller** [comment]
sorry folks, there's no world in which this will ever be high enough priority to be worked on anytime soon.
