### ISSUE TITLE
Aggregate functions with no data returning null instead of 0

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#283]
I would expect the query in this test to return 0 rather than null?

```
public class sum_on_null : DocumentSessionFixture<NulloIdentityMap>
    {
        public class User
        {
            public string Id { get; set; }
            
            public int Logins { get; set; }
        }

        [Fact]
        public void can_query_for_sum_on_no_data()
        {
            theSession.Query<User>().Sum(a => a.Logins).ShouldBe(0);
        }
    }
```

**Comment by phinett** [comment]
Sorry it's not actually returning null, but throwing an error about DBNull.

**Comment by jeremydmiller** [comment]
I think this one gets a lot easier to deal w/ systematically after #280.

**Comment by nieve** [comment]
Am on it.

**Comment by jeremydmiller** [comment]
@nieve I'm gonna get cocky and say that this is going to be fixed w/ #280 and we just need a test to prove it, but I've been wrong before:)

**Comment by nieve** [comment]
Too cocky.

**Comment by jeremydmiller** [comment]
Ugh. Look at `AggregateQueryHandler` now.

**Comment by jeremydmiller** [comment]
This was addressed by https://github.com/JasperFx/marten/pull/310

**Comment by nieve** [comment]
We haven't addressed the case where we do Average, Min or Max on an empty table. In EF they raise an InvalidOperationException. We currently throw an InvalidCastException : column is null. Are you happy with it?

**Comment by jeremydmiller** [comment]
Shoot, I misunderstood. I can take that one tomorrow morning.

**Comment by nieve** [comment]
I can sort it- what should we do with it though? I think InvalidCastException is good enough.

**Comment by jeremydmiller** [comment]
I say we make it do exactly what EF does.
