### ISSUE TITLE
[7.0.rc2] Count Distinct throws error

### ISSUE THREAD

**Issue by elexisvenator** [JasperFx/marten#2848]
The following code produces an exception:

```csharp
await TheSession.Events.QueryAllRawEvents()
            .Where(x => x.MaybeArchived())
            .Select(x => x.StreamKey)
            .Distinct()
            .CountAsync();
```

The exception being:

```
System.NotSupportedException : The database operator 'DISTINCT' cannot be used with non-simple types
```

This previously worked in Marten 6.3.0 and was picked up by tests when upgrading.

**Comment by mysticmind** [comment]
I did test your use case with the latest code and it looks to be working fine. @jeremydmiller  looked to have added few fixes yesterday. Please test the same in the next release.

**Comment by jeremydmiller** [comment]
Fixed in my local branch.
