### ISSUE TITLE
ApplyEventException can leak event data to logs

### ISSUE THREAD

**Issue by elexisvenator** [JasperFx/marten#2849]
This exception will leak the contents of your events to logs if you are using records for your events:

```csharp
public ApplyEventException(IEvent @event, Exception innerException): base(
        $"Failure to apply event #{@event.Sequence} ({@event.Data}.)", innerException)
```

Its a unfortunate side effect of records :(

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/pull/2854
