### ISSUE TITLE
Expected version check doesn't work if the stream doesn't exist yet

### ISSUE THREAD

**Issue by smfields** [JasperFx/marten#2864]
**Summary:**
If you specify an expected version that is greater than the actual current version it won't cause a concurrency exception if the stream doesn't exist yet.

**Steps to reproduce:**
1. Use Append to append events to a stream that does not exist yet.
2. Specify an expected version > 0
3. SaveChanges

**Expected Result:**
A `EventStreamUnexpectedMaxEventIdException` should be thrown because the specified expected stream version (>0) does not match the actual stream version (0).

**Actual Result:**
No exception is thrown and the stream is created with the appended events as the first events.

**Additional Info:**
It seems like [this check](https://github.com/JasperFx/marten/blob/e3303354e74d02f7bda28f3f183744f7b905d4f8/src/Marten/Events/StreamAction.cs#L300C7-L313) is to blame:
```csharp
        if (currentVersion != 0)
        {
            // Guard logic for optimistic concurrency
            if (ExpectedVersionOnServer.HasValue)
            {
                if (currentVersion != ExpectedVersionOnServer.Value)
                {
                    throw new EventStreamUnexpectedMaxEventIdException((object?)Key ?? Id, AggregateType,
                        ExpectedVersionOnServer.Value, currentVersion);
                }
            }


            ExpectedVersionOnServer = currentVersion;
        }
```

So it's not a matter of the expected version being greater than the actual version, but just that the current version is 0. I don't know what real-life reason someone might have for specifying an expected version greater than the current version, but I wouldn't expect the current behavior if they did.

**Comment by jeremydmiller** [comment]
This is all covered by tests at https://github.com/JasperFx/marten/blob/master/src/EventSourcingTests/asserting_on_expected_event_version_on_append.cs. Do you see something about your use case that isn't covered by those tests? All those tests are currently green

**Comment by smfields** [comment]
@jeremydmiller So none of the existing tests actually create the stream using `Append` and check the expected version in the same call. They all either use `StartStream` to create the stream first, or they use `Append`, but they use the overload that doesn't accept an expected version.

Here's an example of a test that would exercise my use case, and it indeed fails:
```csharp
    [Fact]
    public void should_check_max_event_id_on_append_to_empty_stream()
    {
        var joined = new MembersJoined { Members = new string[] { "Rand", "Matt", "Perrin", "Thom" } };

        var stream = Guid.NewGuid();
        theSession.Events.Append(stream, 1, joined);

        Assert.Throws<EventStreamUnexpectedMaxEventIdException>(() => theSession.SaveChanges());
    }
```

In the above test the `Append` call is asserting that the expected version should be `1`, but because the stream doesn't exist yet the actual version will be `0`. So even though current != expected in this case, no exception is being thrown.
