### ISSUE TITLE
Marten version 6.4.1 has not been published to NuGet

### ISSUE THREAD

**Issue by baltie** [JasperFx/marten#2867]
From the github actions logs, it seems it tried to push version 6.4.1 as version 6.4.0. The "Marten NuGet Manual Publish" silently failed, see https://github.com/JasperFx/marten/actions/runs/6970238109/job/18967733853.

See https://www.nuget.org/packages/Marten/6.4.0#versions-body-tab - version 6.4.1 does not exist on nuget.org.

This is not critical to us, but you might want to check what went wrong. :)

**Comment by oskardudycz** [comment]
@baltie thank you for catching that! Now it should be fine: https://github.com/JasperFx/marten/actions/runs/7262627328/job/19786170907 :)
