### ISSUE TITLE
Sample for CustomGrouper is not robust

### ISSUE THREAD

**Issue by Blackclaws** [JasperFx/marten#2881]
The sample in the documentation for CustomGrouper is misleading:

https://martendb.io/events/projections/multi-stream-projections.html#using-custom-grouper-with-fan-out-feature-for-event-projections

It states right at the top that needing to access the aggregate view itself disqualifies a CustomGrouper somewhat. However this is exactly what the example shows.

Furthermore when examining the sample:

src/EventSourcingTests/Projections/MultiStreamProjections/CustomGroupers/custom_grouper_with_document_session.cs

Reordering the license assignment to the users and the license feature toggles being assigned breaks the example. Those two things should be interchangeable however for this to be a good example.

**Comment by jeremydmiller** [comment]
I just don't care enough to do anything about this to be honest.
