### ISSUE TITLE
Slow start up time

### ISSUE THREAD

**Issue by pawelpabich** [JasperFx/marten#289]
I've been playing with Marten and PG 9.5 and  so far I really like what I see. Great job!

But there is one thing that bothers me every time I hit F5. On my reasonably fast laptop i7 + SSD it takes Marten between 5-6 seconds to store a single document. I profiled the code a bit and it looks like most of that time is spent in Roslyn. Is there anything that can be done to optimize this path? 
Code: https://github.com/pawelpabich/random-marten-hacks

![slowstartup-timings](https://cloud.githubusercontent.com/assets/347637/14519508/d0293aca-0262-11e6-985e-05fe14a32b44.png)

![slowstartup-profiler](https://cloud.githubusercontent.com/assets/347637/14519510/d4b31dc2-0262-11e6-8581-447819201bc2.png)

**Comment by jeremydmiller** [comment]
@pawelpabich It's a known problem with the first usage of Roslyn. I'm still hoping that the Roslyn team gets the warmup time down. Otherwise, you can try this too: http://jasperfx.github.io/marten/documentation/precompiling/

**Comment by pawelpabich** [comment]
Yeah, that would be great. 5-6 sec delay gets annoying quickly when you try to prototype something quickly.  Do you know whether Microsoft is actively working on this problem ? I couldn't find anything specific in Rosly repo on Github.

**Comment by jeremydmiller** [comment]
@pawelpabich I don't know. I've bugged them about it, but that was 6 mos ago. We're paying a bit of a cost for going to the bleeding edge -- but it's just so much easier to code than building Expression trees.
