### ISSUE TITLE
Can't create index on DateOnly field

### ISSUE THREAD

**Issue by WeyensLuk** [JasperFx/marten#2917]
I have a class with a DateOnly field, something like this:

```
    public class SampleClass
    {
        public DateOnly Date { get; set; }
    }
```

I make the index like so:

```
    _.Schema.For<SampleClass>()
        .Index(c => c.Date)
```

Then I get the error:

```
CREATE INDEX mt_doc_sampleclass_idx_date ON public.mt_doc_sampleclass ((CAST(data ->> 'Date' as date)));
---- Npgsql.NpgsqlException : 42P17: functions in index expression must be marked IMMUTABLE
```

Can the same changes be made for DateOnly as has been done with DateTime? 

I'm using Marten v6.4.1

**Comment by jeremydmiller** [comment]
@WeyensLuk Not sure if we'll get this in for the v7 cutoff, but you can make that field a "duplicate field" where the index would be off the separate postgres field. That *should* work as is now

**Comment by WeyensLuk** [comment]
@jeremydmiller Thanks for getting back to me.
I agree, a Duplicate field should probably work. But I'm not sure it's a solution that fits well for our current production environment. Inserting data would then take longer, and the workload of our application is primarily inserting data.
