### ISSUE TITLE
string.IsNullOrEmpty is being ignored within conditional LINQ (v7)

### ISSUE THREAD

**Issue by Hawxy** [JasperFx/marten#2937]
The below should be returning a single item, but returns the entire collection instead.
```cs
public record ObjectWithString(Guid Id, string String);

[Fact]
public async Task broken_linq_condition_4()
{
    theSession.Store(new ObjectWithString(Guid.NewGuid(), "Item A"));
    theSession.Store(new ObjectWithString(Guid.NewGuid(), "Item B"));
    await theSession.SaveChangesAsync();


    var queryValue = "Item A";
   var items = await theSession.Query<ObjectWithString>()
        .Where(x => string.IsNullOrEmpty(queryValue) || x.String == queryValue).ToListAsync();

   Assert.Single(items);
}
```

**Comment by Blackclaws** [comment]
I've hit this as well, `queryValue` gets treated as a property here as can be seen in the generated SQL. I've been looking into the Linq subsystem to try and find out why this is the case but haven't found the correct spot yet and it wasn't too high on my list. @jeremydmiller if you'd like me to keep looking for a bit let me know.

**Comment by jeremydmiller** [comment]
Fixed locally
