### ISSUE TITLE
Serialization Failure Behavior in Async Daemon

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2938]
Today we let the projections break on serialization failures, but record "dead letter events" during rebuilds. The question for the future is what do we want to do? @oskardudycz pointed out that our existing behavior is probably backward from what it should be. And either way, we can make it user configurable in both usages.

From Discord:

Hey all, I'm looking hard into the async daemon this week as part of (hopefully) finishing V7. Question for folks, today we potentially stop async projection handling if a projection encounters serialization errors in normal function. But when rebuilding projections, we shove serialization errors off to the side into a "dead letter event queue" so the rebuild won't fail. My question today is "what do we want that to do in the future?"
Jeremy Miller — Today at 10:55 AM

I think the rebuild behavior makes sense, but what about the normal mode? And there's a separate question about how to handle unknown event types, with my thought being that you should have the choice to either ignore or throw.
Oskar Dudycz — Today at 10:57 AM

I think that for rebuild it actually makes sense to stop more than in real usage
In real you want to continue operating, as you always can rebuild it later
When you’re rebuilding then when you faced an error, you can fix the code and restart
Jeremy Miller — Today at 10:58 AM

And next question, take this to a GitHub issue, or leave it here?
And that makes complete sense to me
Oskar Dudycz — Today at 10:58 AM

Sounds like GH issue to me
I think that for both cases it’d be good to make it configurable
Jeremy Miller — Today at 10:58 AM

Yeah, I'd buy that too

**Comment by gfoidl** [comment]
> In real you want to continue operating, as you always can rebuild it later
> When you’re rebuilding then when you faced an error, you can fix the code and restart

👍🏻 

(side note: the quoting authors are shuffled around)

**Comment by jeremydmiller** [comment]
"Fixed" in my branch such that serialization errors go to the dead letter events and get skipped when running async, but by default, fail rebuilds immediately
