### ISSUE TITLE
[v7] Improper SQL generated for Enum-keyed dictionary access when EnumStorage.AsInteger

### ISSUE THREAD

**Issue by migajek** [JasperFx/marten#2953]
@jeremydmiller  got some more LINQ hell for you :( 

Consider the following code - please note this time `EnumStorage` is `AsInteger` .

```c#
public enum EnumA { Whatever }

public record Order(string Id,
    Dictionary<EnumA, string> EnumStringMap);

...
var query = qs.Query<Order>()
    .Where(x => x.EnumStringMap.ContainsKey(EnumA.Whatever))
    .Where(x => x.EnumStringMap[EnumA.Whatever] == "abc");
var commandText = query.ToCommand().CommandText;
```

the generated sql where segment is:
```sql
d.data -> 'EnumStringMap' ->> 'Whatever' = :p0 
and d.data #> '{EnumStringMap, 0}' is not null
```

For the comparison, the proper JSON chained access is built, using enum string value for dictionary key access.
However for the `ContainsKey`, the JSON path uses integer enum values instead.

When switching to `EnumStorage.AsString` both access operators are built correctly.

**Comment by migajek** [comment]
the full repro code

```c#
internal class Program
{
    static async Task Main(string[] args)
    {
        await RunExample(EnumStorage.AsInteger);
        await RunExample(EnumStorage.AsString);
    }

    public static async Task RunExample(EnumStorage storage)
    {
        using var store = DocumentStore.For(cfg =>
        {
            cfg.Connection("...");
            cfg.UseDefaultSerialization(storage);
        });
        await store.Advanced.Clean.CompletelyRemoveAllAsync();
        await store.BulkInsertAsync(new[]
            { new Order("o1", new Dictionary<EnumA, string>() { [EnumA.Whatever] = "abc" }) });

        using var qs = store.QuerySession();

        var query = qs.Query<Order>()
            .Where(x => x.EnumStringMap.ContainsKey(EnumA.Whatever))
            .Where(x => x.EnumStringMap[EnumA.Whatever] == "abc");
        var commandText = query.ToCommand().CommandText;
        var count = query.Count();

        Console.WriteLine($"Count: {count} | Cmd: {commandText}");
    }
}
```

**Comment by jeremydmiller** [comment]
On it today

**Comment by jeremydmiller** [comment]
@migajek I *hate*, *hate*, *hate* this exact kind of issue. Here's the deal, both Newtonsoft and STJ will serialize `Enum` values as strings if they are key values within a dictionary. And that's independent of how the enums are stored as straight up property/fields.

**Comment by migajek** [comment]
Frankly, I was going to comment on that part in the original issue, but I gave up as I'm not sure how I feel about it :) On one hand it feels inconsistent (with Marten setting, when set "as int"), on the other hand I admit I still kinda expect the keys to be strings, regardless of the setting. 
Maybe it depends on the context of the usage (thinking of a dictionary as a map, vs as a "property bag"). 

Anyway, thanks!
