### ISSUE TITLE
BulkInsert/BulkInsertAsync with IEnumerable / IAsyncEnumerable

### ISSUE THREAD

**Issue by e-tobi** [JasperFx/marten#2956]
BulkInsert<T>() currently consumes a IReadOnlyCollection<T>. I think, it would be nice to allow IEnumerable<T> too and even IAsyncEnumerable. This would allow to "stream" a large amount of documents into the database.  I can provide a PR for this, if this is something that might get accepted

BTW: BulkInsertDocuments()/BulkInsertDocumentsAsync() already takes an IEnumerable<T>, but I think this is misleading, because the documents will be grouped by type, causing the whole enumerable to be enumerated and loaded into memory. Having a potentially large data source, which provides an IEnumerable<T> via yielding, this may cause trouble.

**Comment by jeremydmiller** [comment]
@e-tobi Happy to take a PR for this, but nobody else has commented on this, and I'm closing it for now.
