### ISSUE TITLE
Possibly excessive locking in the upsert function

### ISSUE THREAD

**Issue by pawelpabich** [JasperFx/marten#296]
I continue my journey with Marten and the most recent part of it is a simulation of 1000 concurrent users inserting 1 document each. The first run on an empty database works OK but then all subsequent runs end up sooner or later with TimeoutException and  "Timeout while getting a connection from pool". This problem goes away when I remove`LOCK TABLE {TableName} IN SHARE ROW EXCLUSIVE MODE;` from the upsert function. PostgreSQL docs indicate that SQL dml commands acquire required locks themselves (http://www.postgresql.org/docs/9.1/static/explicit-locking.html). I checked the Git history but did not find anything there. 

Is there a specific reason why this lock is acquired manually?

Test case: StoreLotsOfData - https://github.com/pawelpabich/random-marten-hacks/blob/master/MartenPlayground/Program.cs

**VS**

![image](https://cloud.githubusercontent.com/assets/347637/14552183/fe1b5d98-031e-11e6-8a9a-879f4c9a72a4.png)

**PGAdmin**

![image](https://cloud.githubusercontent.com/assets/347637/14552188/097389a4-031f-11e6-9f55-25617038edc4.png)

**Comment by jeremydmiller** [comment]
Are you on Postgres 9.5 by chance? If you are, can you switch the UpsertStyle = "Standard" to take advantage of the built in upsert support and see how that's different.

@jeffdoolittle  What do you think about this one?

**Comment by pawelpabich** [comment]
@jeremydmiller yes I'm. I changed the option to Standard and I'm not getting timeouts. Thanks!

**Comment by jeremydmiller** [comment]
@pawelpabich I'm gonna keep this one open to make sure we do a little more research on 9.4 mode;)

**Comment by jeremydmiller** [comment]
We went to the 9.5 style of native upsert functions being the default, and I *think* that's going to solve this problem just fine. I'm closing this.
