### ISSUE TITLE
Handle DateTimeOffset? same as DateTime?

### ISSUE THREAD

**Issue by tomap** [JasperFx/marten#2975]
Hello,

I have this error:

`BadLinqExpressionException : Can only compare property type System.DateTimeOffset by '=' or '!='`

When I try to have a query using <= operator to compare DateTimeOffset? (nullable)

This occurs on a field that is a Nullable System.DateTimeOffset

It seems that for DateTime, there is an extension method checking for DateTime & DateTime?

But not for DateTimeOffset

=> https://github.com/JasperFx/marten/blob/253326b6f7f566eebcc3ddd79efd074e3d4c45f9/src/Marten/Linq/Members/ValueCollections/ElementComparisonFilter.cs#L32

I might be wrong about the analysis & those lines of code, but if I am right, I would be glad if a fix was applied :)

Thank you

**Comment by jeremydmiller** [comment]
@tomap The call right above the line you highlighted for `IsDateTime` does the same thing. Are you trying to use a date time that's within a child collection? We're somewhat limited by the underlying Npgsql library here. What's the actual LINQ expression you are using?

**Comment by jeremydmiller** [comment]
@tomap What's the actual LINQ expression you're needing to use? <= against a nullable DateTimeOffset type? From the parent document, or was this within a child collection?
