### ISSUE TITLE
Full control over how the JsonNetSerializer is built and configured internally

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#3]
Json.Net options. Aw, Json.Net, how I've missed all your binding conflicts. (Not).

**Comment by flq** [comment]
:laughing: you know RavenDb went for internalizing it, and it probably wasn't a bad move from this perspective.

**Comment by jeremydmiller** [comment]
@flq And so did we. If you want to customize the JSON serialization you can just create your own adapter and plug in. I'm closing this.
