### ISSUE TITLE
Wrong name for RevisionColumn

### ISSUE THREAD

**Issue by aurelienhayet** [JasperFx/marten#3013]
Hi Jeremy,

I think there is an error in the source code of the RevisionColumn in **version 7.0.0**

https://github.com/JasperFx/marten/blob/master/src/Marten/Storage/RevisionColumn.cs#L11

` public RevisionColumn(): base(SchemaConstants.VersionColumn, x => x.CurrentRevision)`

The base class is called with SchemaConstants.VersionColumn instead of SchemaConstants.RevisionColumn

This leads to errors at startup because Marten tries to alter the mt_version column type to int.

`alter table <schema>.<document> alter column mt_version type integer;`

**Comment by jeremydmiller** [comment]
Sigh, I purposely made it "mt_version" to be consistent with the Event Store "Version" concept, which was exactly what it was meant for. You're going to have to manually drop the `mt_version` column on whatever that document type was to go from old fashioned "UseOptimisticConcurrency" to the new revisioned model. 

I'm going to leave this open, but mark it as a documentation issue.

**Comment by aurelienhayet** [comment]
After better reading of your documentation, you explained the 2 versioning systems pretty well here : https://martendb.io/documents/concurrency.html#optimistic-concurrency

But I would like to add more context on my issue description, just to ensure that we understand together well.

The issue raised on a projected document in the context of Event Store after migrating Marten from 6.2.0 to 7.0.0.

We tried to decorate the document class with [UseOptimisticConcurrency] attribute and also tried to configure Marten with 

`
                options.Policies.ForAllDocuments(x =>
                {
                    x.UseOptimisticConcurrency = true;
                    x.UseNumericRevisions = false;
                });
`

But these 2 options do not seem to be taken into account.

Do we have any alternative to stay on the optimistic concurrency with guid column type on our projection documents ?

Thanks a lot for your help.

**Comment by jeremydmiller** [comment]
@aurelienhayet Then the next thing is to write in the docs that it's strongly recommended that you don't combine the Guid-based optimistic concurrency and projected documents. I don't think it ever made sense to do that, and that's caused other people friction in the past. So no, that combination of things is not supported in 7.0
