### ISSUE TITLE
Marten has started leaking DB connections since 7.x

### ISSUE THREAD

**Issue by JonnyWideFoot** [JasperFx/marten#3033]
In martendb 6.x the attached code was fine, as of 7.x this now leaks DB connections until it fails with "Npgsql.PostgresException 53300: remaining connection slots are reserved for roles with the SUPERUSER attribute"

In my migration application, the following code is called in a for loop.

```
    public override async Task ExecuteAsync(IDatabaseConfiguration databaseConfiguration, CancellationToken cancellationToken)
    {
        var store = BuildDocumentStore(
            databaseConfiguration,
            x => x.UseJavascriptTransformsAndPatching(t =>
        {
            t.LoadJavascript(Name, JsScript);
        }));

        await using IDocumentSession session = store.LightweightSession();
        await DoTransformsAsync(session, cancellationToken);
        await session.SaveChangesAsync(cancellationToken);
    }

    private async Task DoDocumentTransformAsync<TEntity>(IDocumentSession session, CancellationToken cancellationToken)
        where TEntity : IEntity
    {
        string entityName = typeof(TEntity).Name;
        session.Transform(PerformDocumentTransforms<TEntity>);
        await session.SaveChangesAsync(cancellationToken);
    }
```

![image](https://github.com/JasperFx/marten/assets/1295224/4f694dd3-886b-4bb1-b19e-46b4005b6775)

**Comment by JonnyWideFoot** [comment]
Realised this is fixed by changing to:

```
await using var store = BuildDocumentStore(
```

So you may want to close this as an application bug, although the behaviour does seem to have changed..

**Comment by jeremydmiller** [comment]
That change happened quite awhile ago in 6.* I believe. All this kind of "am I correctly cleaning up after services" kind of thing goes much, much better if you just pull things in from an IoC tool. Is there any reason why you're building a DocumentStore like that on the fly? That's actually pretty expensive.

**Comment by JonnyWideFoot** [comment]
We are currently using 6.4.1, which is "6.x" above. The code sample is from in a small JavaScript utility that applies a set of migrations/transformations in turn to an existing database.

The JS transformations are each loaded using the code:

```
x => x.UseJavascriptTransformsAndPatching(t =>
        {
            t.LoadJavascript(Name, JsScript);
        }
```

.. hence the creation of the store on the fly, as "JsScript" changes each time.

The performance of the migration code isn't really an issue as this isnt run very often.

For our main Asp.Net web application, everything is created using the standard IoC container
