### ISSUE TITLE
Async daemon is double processing event slices for new single stream projections

### ISSUE THREAD

**Issue by murlakatam** [JasperFx/marten#3059]
Reproducing repository (based on Helpdesk from Marten samples) 
https://github.com/murlakatam/MartenBugWithAsyncProjectionSnapshot

Marten 7 (atm of writing 7.3.0)
has a bug in upsert function that updates the async snapshot projection. (or at least in the projection engine)

```csharp
options.Projections.Snapshot<IncidentDetailsSnapshotAsyncProjection>(SnapshotLifecycle.Async);
```

If you would run the only test in this project,  https://github.com/murlakatam/MartenBugWithAsyncProjectionSnapshot
that merely creates 2 events and expects async snapshot projection to catch up with the latest version,

it will fail with the following error:

```bash
Xunit.Sdk.XunitException
Expected property root.Aggregated.Category to be equivalent to IncidentCategory.Database {value: 3}, but found <null>.

```

if you look at the logs you would see that the expected call is made by the daemon
that should have updated the projection with the new value, but it didn't.

```sh
[dbug] [Helpdesk.Api.Core.Marten.MartenLogger] SQL Batch starting 214668f9-f45c-4e7e-9b9e-b752f3a95229 select helpdesk.mt_upsert_incidentdetailssnapshotasyncprojection($1, $2, $3, $4); (@p0, Jsonb, {"Id":"018e4f4f-7480-43c0-8d73-5f5d877520ac","Aggregated":{"Id":"018e4f4f-7480-43c0-8d73-5f5d877520ac","CustomerId":"4a8c1416-2907-4d4d-8581-7d2c5ac44141","Status":"Pending","Notes":[],"Category":"Database","Priority":null,"AgentId":null,"Version":1}}), (@p1, Varchar, Helpdesk.Api.Incidents.GetIncidentDetails.IncidentDetailsSnapshotAsyncProjection), (@p2, Uuid, 018e4f4f-7480-43c0-8d73-5f5d877520ac), (@p3, Integer, 2)

```

however if you pause the test before running the second upsert batch for Categorized event (for example by putting a breakpoint in the MartenLogger) and run the query manually 

```sql
select * 
	FROM helpdesk.mt_doc_incidentdetailssnapshotasyncprojection;
```

you would see that the projection version is already set to 2 (while the category is not applied). which means that the upsert call for the Categorized with version 2 is going to be ignored

if you debug the code and put a breakpoint into projection creation code (IncidentLogged Apply)

```csharp
public IncidentDetailsSnapshotAsyncProjection(IncidentLogged logged)
    {
        Id = logged.IncidentId;
        Aggregated = new(logged.IncidentId, logged.CustomerId, IncidentStatus.Pending, Array.Empty<IncidentNote>());
    }
```

you would notice that the breakpoint
is hit twice despite the fact that there is only one incident creation event in the stream.

So something forces marten to build projection twice from a single event and 
produce 2 duplicate upsert calls with the same version number = 1

which then goes into the following upsert function code block

```sql
if revision = 1 then
  SELECT mt_version FROM helpdesk.mt_doc_incidentdetailssnapshotasyncprojection into current_version WHERE id = docId ;
  if current_version is not null then
    revision = current_version + 1;
  end if;
end if;
```
and sets the version to 2, which is wrong, as the very next update with version 2 is ignored and not applied

**Comment by murlakatam** [comment]
Marten 6 was working fine in this scenario. 

There are two possible workarounds:
1) hack the sql to include the same version (e.g make upsert function to use >= instead of > here 
```sql
where revision > helpdesk.mt_doc_incidentdetailssnapshotasyncprojection.mt_version;
```
but that is not fixing the root cause and might be dangerous
2) Switch of numeric revision enforced on projections, but that also has a problem https://github.com/JasperFx/marten/issues/3057


Btw unrelated question, I noticed that integration test execution halts to deadlock even for a single test in Rider. The test finishes but the host never stops. Is there a potentially thread blocking bug there now?

**Comment by jeremydmiller** [comment]
"
Btw unrelated question, I noticed that integration test execution halts to deadlock even for a single test in Rider. The test finishes but the host never stops. Is there a potentially thread blocking bug there now?
"

That's not behavior I've seen before. There are tests for the daemon as is, and none of them are exhibiting any of the behavior that you're describing here.

**Comment by jeremydmiller** [comment]
@murlakatam Man, I'm sorry, but "It works on my box". I cloned your repo and ran that one test, and it's admittedly very slow, but it passes

**Comment by danyo1399** [comment]
thanks for finding and reporting the bug @murlakatam. Sounds like a nasty bug. Glad it got addressed before i start upgrading to 7.

**Comment by murlakatam** [comment]
Thanks for fixing it @jeremydmiller. Not sure why it wasn't reproducible on your machine. It failed every time on my. It was really really hard to describe and I went into reflection and debugging for a few days to get to what I thought might have been the cause.
