### ISSUE TITLE
Searchable to move pgType to configuration and add Drop

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#306]
Right now in order to specify the definition options we need to specify the pgType:

`.Searchable(x => x.MemberId, null, definition => { definition.IsConcurrent = true; })`

Which means passing in null just to get to the definition config.

Change this to be:

```csharp
.Searchable(x => x.MemberId, definition => 
                              { 
                                  definition.IsConcurrent = true; 
                                  definition.PgType = "..."; 
                              });
```

Secondly add the ability to specify that the index should be dropped before being created:

```csharp
.Searchable(x => x.MemberId, definition => 
                              { 
                                  definition.IsConcurrent = true; 
                                  definition.DropAndCreate = true
                              });
```

**Comment by jeremydmiller** [comment]
You can call:

```
.Duplicate(x => x.MemberId, configuration:def => {

});
```

I don't think that the DropAndCreate would be necessary with the patching capability. Marten would already generate a DROP INDEX statement if the index has changed.
