### ISSUE TITLE
New resiliency configuration via `.ConfigurePolly()` does not allow to extend default marten policies

### ISSUE THREAD

**Issue by a-shtifanov-laya** [JasperFx/marten#3071]
As discussed on discord, previously (before v7) it was possible to extend marten default resilience policy.
v7 introduced resilient policy configuration with Polly (a breaking change), and there is no possibility right now to extend default marten configuration - only overwrite it.

**Comment by a-shtifanov-laya** [comment]
..pr is comming

**Comment by jeremydmiller** [comment]
Closed by #3072
