### ISSUE TITLE
Document Projections

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#31]
Just a placeholder for now. Have *some* kind of model that allows you to do transforms to _read side_ views in the database. Might finally get into PLV8 code inside of postgres. I'm thinking that we could do this in lieu of supporting truly crazy LINQ queries of the real model.

**Comment by andrewm1986** [comment]
I think this would be ideal for supports CQRS scenarios

Does the PLV8 support ecmascript 6?  You could look at doing some arrow function based indexes

**Comment by tim-cools** [comment]
I was also thinking about implementing something like this. My current idea was to implement async projections to use pgq (a queue insiide pg developed by skype) to create Document update events. These events would be consumer by a .NET service in order to update the re

**Comment by jeremydmiller** [comment]
@tim-cools I'm finally poking at this one a little bit today. I looked at pgq a couple years ago, but didn't get very far with it. I didn't feel like there was much information on it.

For pg-events, I used a rolling buffer table as the de facto queue: http://kejser.org/implementing-message-queues-in-relational-databases/.

**Comment by jeremydmiller** [comment]
Alright everyone, I'm thinking that I'm going to finally put just a little bit of time into this this week. See https://github.com/JasperFx/marten/pull/262 for more of a discussion.

I'm focusing on the event store right now, but there's no reason why we can't do something with normal documents

**Comment by jeremydmiller** [comment]
This is being subsumed by #320 and #321 for now.
