### ISSUE TITLE
Possible regression in .QueryAllRawEvents with .In operator

### ISSUE THREAD

**Issue by AlexSikilinda** [JasperFx/marten#3103]
Hi, I've tried to upgrade from v6.4 to v7.5 and encountered what I think is a regression.

We have the following query: 

```
session.Events.QueryAllRawEvents()
    .Where(e => e.Id.In(eventsIds))
    .Where(e => e.AnyTenant());
```

In v6.4 it produces the following SQL (which works fine):
```
select data, type, mt_dotnet_type, seq_id, id, stream_id, version, timestamp, tenant_id, is_archived from public.mt_events as d where ((d.id = ANY(:p0) and  1=1) and  d.is_archived = FALSE)
```

but in the latest v7.5 it produces SQL checking **d.data ->> id**, which I believe is incorrect since it should check the ID column instead of going to data:

```
select data, type, mt_dotnet_type, seq_id, id, stream_id, version, timestamp, tenant_id, is_archived from public.mt_events as d where (1=1 and CAST(d.data ->> 'Id' as uuid) = ANY(:p0) and d.is_archived = FALSE);
```

As I understand, .QueryAllRawEvents should query IEvent properties (ID column in this case), not the data itself.

Thanks!

**Comment by jeremydmiller** [comment]
Bug. Not a use case where we have a test at all apparently.
