### ISSUE TITLE
Regression in dictionary querying

### ISSUE THREAD

**Issue by Hawxy** [JasperFx/marten#3126]
This regressed somewhere between 7.3-7.6 as it was previously working.

`42883: operator does not exist: text ->> unknown`

```cs
    public record DictObject(Guid Id, Dictionary<Guid, HashSet<Guid>> GuidDict, Dictionary<Guid, NestedObjectWithinDict> NestedObject);
    public record NestedObjectWithinDict(Guid Id);

    [Fact]
    public async Task broken_linq_condition_3()
    {
        var id = Guid.NewGuid();
        await theSession.Query<DictObject>()
            .Where(x => x.GuidDict.ContainsKey(id) || x.NestedObject.Values.Any(s => s.Id == id)).ToListAsync();
    }
```

**Comment by jeremydmiller** [comment]
@Hawxy It didn't work before either, it just didn't throw an exception. Not the answer you want, but for now it's going to throw a BadLinqExpressionException telling you that Marten doesn't support the Dictionary.Values.Any() usage yet. I honestly don't know what SQL to build for this yet. As I recall, I was stymied on this before. 

Happy to come back to this later, but it's too much work for this week and 7.7

**Comment by Hawxy** [comment]
> It didn't work before either, it just didn't throw an exception.

Whoops, that means we're missing a test on our side for that permutation. All good.

**Comment by jeremydmiller** [comment]
I rolled back to 7.3, and that creates SQL for the 2nd part of the "OR" that would never work, but is valid SQL at least
