### ISSUE TITLE
Adding Live projections and Subclass with Snapshot projection generates unnecessary schema on patch command

### ISSUE THREAD

**Issue by murlakatam** [JasperFx/marten#3140]
There is inconsistency in projections registrations API behaviour:

1) registering live projection via 
```csharp
options.Projections.Add(new SingleStreamProjection<MyAggegate>(), ProjectionLifecycle.Live);
```
still creates the table for the aggregate when you invoke patch command, but
```csharp
options.Projections.LiveStreamAggregation<MyAggegate>();
```
does not. 

2) Similar problem applies when you register Snapshot projection for a Subclass (all subclasses are stored in parent table)

```csharp
options.Schema.For<BaseAggregate>()
            .AddSubClassWithSnapshotProjection<BaseAggregate, Child1Aggregate>(options, SnapshotLifecycle.Inline)
            .AddSubClassWithSnapshotProjection<BaseAggregate, Child2Aggregate>(options, SnapshotLifecycle.Inline);
```
where AddSubClassWithSnapshotProjection
is 

```csharp
public static MartenRegistry.DocumentMappingExpression<T> AddSubClassWithSnapshotProjection<
        T, TSubclass>(
        this MartenRegistry.DocumentMappingExpression<T> registry,
        StoreOptions options,
        SnapshotLifecycle lifecycle,
        Action<AsyncOptions>? asyncConfiguration = null)
        where TSubclass : T
    {
        registry.AddSubClass<TSubclass>();
        options.Projections.Snapshot<TSubclass>(lifecycle, asyncConfiguration);
        return registry;
    }

```

patch command attempts to create snapshot tables for subclasses but they are not needed. 

I guess the source of inconsistency is lack of the following code for the misbehaving examples
```csharp
this._options.Storage.MappingFor(typeof (T)).SkipSchemaGeneration = true;
```

But seems like SkipSchemaGeneration completely ignores the changes for the patch command. Is that intentional? 

So for example if you had a snapshot projection for MyAggegate and you migrated it to Live projection using LiveStreamAggregation the patch command won't detect the need to drop the table used for the snapshot. 
With SkipSchemaGeneration = true it falls out of Marten patch control and the only way to get rid of it is manual migration creation.

**Comment by jeremydmiller** [comment]
> But seems like SkipSchemaGeneration completely ignores the changes for the patch command. Is that intentional?

Yes. That's a hack that was all about live aggregations in the first place

**Comment by jeremydmiller** [comment]
@murlakatam Got a fix coming for the first issue, for the `AddSubClassWithSnapshotProjection` thingie, sorry, but that one's "I take pull requests" territory. We've never had first class support for subclass projections like that, and that's a place where I'd need to ask for community help right now. Or wait until we can push through the support for explicit code for live aggregators then you do whatever you want.
