### ISSUE TITLE
updating two event streams in one session configured with inline snapshot fails

### ISSUE THREAD

**Issue by danyo1399** [JasperFx/marten#3142]
when appending to two different event streams in the same session and calling save changes fails with Marten.Exceptions.DocumentAlreadyExistsException.

We are running marten 7.5.0

The streams are configured with inline snapshots.

Simple reproduction
```csharp
 var store = Services.GetRequiredService<IDocumentStore>();
        var session = store.IdentitySession();
        var id1 = Guid.NewGuid().ToString();
        var id2 = Guid.NewGuid().ToString();

        session.Events.Append(
            id1,
            new StopManualAdjustmentRequestLinked
            {
                StopManualAdjustmentRequestId = "bla"
            });

        session.Events.Append(
            id2,
            new StopManualAdjustmentRequestLinked
            {
                StopManualAdjustmentRequestId = "bla"
            });
        await session.SaveChangesAsync();

        session = store.IdentitySession();
        var _ = await session.LoadAsync<ManualAdjustmentPlanAggregate>(id1);
        var __ = await session.LoadAsync<ManualAdjustmentPlanAggregate>(id2);

        session.Events.Append(
            id1,
            new StopManualAdjustmentRequestLinked
            {
                StopManualAdjustmentRequestId = "bla"
            });

        session.Events.Append(
            id2,
            new StopManualAdjustmentRequestLinked
            {
                StopManualAdjustmentRequestId = "bla"
            });

        await session.SaveChangesAsync();
```

**Comment by jeremydmiller** [comment]
@danyo1399 That's not enough for a reproduction. What's the projection that might be causing this? I'm inclined to point the finger there rather than saying this is a Marten issue until you can prove otherwise.

**Comment by danyo1399** [comment]
All good I thought I’d start there first to see if it rings a bell. I’ll do a proper repo today.

**Comment by danyo1399** [comment]
Still struggling to repro it in another repo. in the original repo all the events get turned into tombstones on when i look in the db at the end of the test. 

![CleanShot 2024-04-18 at 16 53 07](https://github.com/JasperFx/marten/assets/45319227/4d7924d7-b675-44d8-9c72-22cd6a46a323)

**Comment by danyo1399** [comment]
I have not been able to reproduce it in a new repo. Ill reopen if i find an issue.
