### ISSUE TITLE
Incorrect constraints change detection for multi-tenanted documents

### ISSUE THREAD

**Issue by misha-p** [JasperFx/marten#3145]
**Behavior:**

Marten change detection (on startup with apply, db-assert/db-apply) keeps finding constraints configuration mismatch on multi tenant documents even if correct constraint already exists.
`alter table public.mt_doc_multitest drop constraint pkey_mt_doc_multitest_tenant_id_id CASCADE;`
`alter table public.mt_doc_multitest add CONSTRAINT pkey_mt_doc_multitest_tenant_id_id PRIMARY KEY (tenant_id, id);`

**Reason:**

The reason is in the columns order. The above behavior manifests only on tables where column 'tenant_id' is the last column.
If db-apply is done for brand new multi-tenanted document, created table will be generated with tenant_id at first position `tenant_id, id, data, mt_last_modified, mt_version, mt_dotnet_type`. Change detection in that case works correctly.
Column tenant_id can easily become last, e.g. document tenancy added after schema already generated and table was altered by Marten.

**Workaround:**

The only workaround is to reorder columns in the doc tables so that tenant_id is the first column (which is quite cumbersome in postgres)

PS: I believe this issue started with Marten 7+

**Comment by jeremydmiller** [comment]
@misha-p Hey, we're going to need a bit more in terms of reproduction steps. How have you made that happen? What was your starting point, and what did you move to? Not sure I understand how you got there

**Comment by misha-p** [comment]
Hi Jeremy, sure, here's the example:

1. Create document without multi tenancy.
```csharp
public record TestDoc(Guid Id, string Column);
...
// configure Marten - anything that will persist that document in DB, add index for example:
storeOptions.Schema.For<TestDoc>().Index(x => x.Column);
```
2. Run application or db-apply to get TestDoc created in database.
   Database table will be `mt_doc_multitest (id, data, mt_last_modified, mt_version, mt_dotnet_type)`
3. Add tenancy to TestDoc
```csharp
storeOptions.Schema.For<TestDoc>().Index(x => x.Column).MultiTenanted();
```
4.  Run application or db-apply to get TestDoc altered in database.
   Database table will be `mt_doc_multitest (id, data, mt_last_modified, mt_version, mt_dotnet_type, tenant_id)`

At this point Marten will keep seeing the change in CONSTRAINT pkey_mt_doc_testdoc_tenant_id_id
E.g. running dotnet run -- db-assert, will produce:
```
Database 'Marten' does not match the configuration!
Weasel.Core.Migrations.DatabaseValidationException: Configuration to Schema Validation for Database 'Marten' Failed! These changes detected:

alter table public.mt_doc_testdoc drop constraint pkey_mt_doc_testdoc_tenant_id_id CASCADE;
alter table public.mt_doc_testdoc add CONSTRAINT pkey_mt_doc_testdoc_tenant_id_id PRIMARY KEY (tenant_id, id);
```

To fix it I should either drop mt_doc_testdoc and do db-apply (not good for production system) or move tenant_id column to first position (e.g. create new table, copy data, drop old table, rename new)

**Comment by jeremydmiller** [comment]
The relevant code in Weasel to detect PK columns on an existing table weren't considering column ordering. It's going to take a Weasel change to get this fixed -- which is done, just pending the next Weasel release
