### ISSUE TITLE
Invalid documentation and samples for EventUpcaster

### ISSUE THREAD

**Issue by denis-tsv** [JasperFx/marten#3147]
Hi,

Documentation for [EventUpcaster<TEvent> ](https://martendb.io/events/versioning.html#raw-json-transformation-with-system-text-json-1)tells that is is needed to implement Upcast method.
But base class [EventUpcaster<TEvent>](https://github.com/JasperFx/marten/blob/master/src/Marten/Services/Json/Transformations/EventUpcaster.cs#L175) doesn't have an Upcast method. It has only FromDbDataReader method.

So I think that it is needed to update documentation.

**Comment by jeremydmiller** [comment]
@denis-tsv The base `EventUpcaster<TOldEvent, TEvent>` type does have that method. The documentation is all pulled from live code samples in the codebase. I get the confusion though. I'm putting a note about that in the docs.
