### ISSUE TITLE
Tombstone process is generating multiple errors due to implementation issue 

### ISSUE THREAD

**Issue by svrx** [JasperFx/marten#3158]
**Context**
Recently upgraded to 6.4.1 and noticed that error rate has increased significantly for the same workloads.
Upon investigation found that most of the errors aren't representative of a functional issue but rather originated by an issue in the tombstone process triggered when a concurrency version error occurs, which requires tombstones to be created.

The issue seem to have been introduced by the changes  cb232d79cd29765cd0b0a3ae17189487d8c081f8 and  39288c2c7b03c23fcd7d900c518017ed414ba15a.

**Issue**
1. When tombstones are posted a new `LightWeightSession()` is created with default isolation level of `ReadCommited`, which as per implementation **doesn't** start a transaction underneath.
2. On calling `ExecuteBatch()` for the tombstone batch, on the new session, the command is executed and committed  automatically 
3. `ExecuteBatch()` assumes the session has a transaction and calls `_connection.Commit()` getting immediately an exception `InvalidOperationException("Trying to commit a transaction that was never started")` 
4. The applicable retry policy may retry the `Commit()`  an additional number of times which subsequently posts the batch to the `_tombstones` (`RetryBlock<>`) which tries another 3 times deferred in time.

```c#
// marten\src\Marten\Events\EventGraph.Processing.cs
internal void PostTombstones(UpdateBatch tombstoneBatch)
{
    try
    {
        using var session = (DocumentSessionBase)_store.LightweightSession();
        session.ExecuteBatch(tombstoneBatch);
    }
 ...

// marten\src\Marten\Internal\Sessions\DocumentSessionBase.SaveChanges.cs
internal void ExecuteBatch(IUpdateBatch batch)
{
    try
    {
        batch.ApplyChanges(this);
        _retryPolicy.Execute(_connection.Commit);
    }
...
``` 

In all this try and retry process, none of the retries has any chance of success, since the same issue is present, although on step 2 the desired effect has already been applied.

Even though has been identified in 6.4.1, it looks to still be present in the latest version of master.

**Comment by jeremydmiller** [comment]
@svrx "Even though has been identified in 6.4.1, it looks to still be present in the latest version of master."

I'm going to contest that statement and tell you to just move up to Marten 7. The entire execution pipeline is significantly different in Marten 7, and the issues you're calling out here would not exist there.

I'll accept a pull request to address this in the 6.* branch if you'd like, but otherwise my advice is to move to 7. 

This also isn't an issue that's been reported by anyone else, so I'm curious what's maybe different about your project or database setup.

**Comment by svrx** [comment]
@jeremydmiller, I can confirm that after rewrite for 7, the execution takes a different path where `ExecuteBatch()` always beginning the transaction beforehand hence this issues affects only 6.2.0 to 6.4.1.

Closer inspection shows that the issue is only present in synchronous `ExecuteBatch()`, as async implementation explicitly begins the transaction. 

```c#
 internal async Task ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
 {
     await BeginTransactionAsync(token).ConfigureAwait(false);

     try
     {
         await batch.ApplyChangesAsync(this, token).ConfigureAwait(false);
...
``` 

Since posted tombstones always run async, the described behaviour occurs only when using sync `SaveChanges()` version as failure occurs after tombstones is committed and batches posted to `_tombstones` will then always fail with a `seq_id` violation.

The upgrade to version 7 is in my backlog, but will require some time for upgrade and testing of changes. 
Do you know what level of DB schema or data migrations is required when moving to 7?

I can submit a PR for this one in meantime if you're willing to promote a release for 6.4.2.

**Comment by jeremydmiller** [comment]
IS there a reason why you have to use the synchronous version? Not saying that can't be valid, but that's certainly not recommended. And that does maybe explain why nobody has hit this otherwise.

I actually proposed killing off the synchronous APIs years ago, but we've been too scared to do that

**Comment by svrx** [comment]
I completely agree with the recommendation. In our case it sort of went under the radar as it usage was hidden behind an abstraction.
