### ISSUE TITLE
AllAsyncProjectionShardNames returns all projections, live, inline and async

### ISSUE THREAD

**Issue by Richard87** [JasperFx/marten#3165]
Hi, playing around I noticed `AllAsyncProjectionShardNames` returns all projections, possible bug?
```csharp
IDocumentStore.Advanced.AllAsyncProjectionShardNames()
```

> Convenience method to retrieve all valid "ShardName" identities of asynchronous projections

**Comment by jeremydmiller** [comment]
I've got this one
