### ISSUE TITLE
Bug? WaitForNonStaleProjectionDataAsync waits for all projections, inline and live, not only Async projections

### ISSUE THREAD

**Issue by Richard87** [JasperFx/marten#3166]
When executing `WaitForNonStaleProjectionDataAsync`, it finds all projections, including `Inline`, and tries to wait for them to get past `initial.EventSequenceNumber`

https://github.com/JasperFx/marten/blob/4ffd106f4e6acf1d722affa37ecd1be9544bfb70/src/Marten/Events/AsyncProjectionTestingExtensions.cs#L85

In my testing, inline projections doesn't get updated before a new event that is used by the projection is applied, so its almost always lagging. In those cases `WaitForNonStaleProjectionDataAsync` will fail.

**Comment by Richard87** [comment]
Probably the most hacky and slow bugfix:

```csharp

        Dictionary<string,string> shardNames = store.Advanced.AllAsyncProjectionShardNames()
            .ToDictionary(x => x.ProjectionName, x => x.Identity);

        var projectionsToCheck = store.Options
            .Events
            .Projections()
            .Where(x => x.Lifecycle == ProjectionLifecycle.Async)
            .Select(x => shardNames[x.ProjectionName]);

///and

            if ((projections.Count >= projectionsCount &&
                 projections.Where(x => projectionsToCheck.Contains(x.ShardName)).All(x => x.Sequence >= initial.EventSequenceNumber))
                || cancellationSource.IsCancellationRequested)
            {

```

**Comment by jeremydmiller** [comment]
@Richard87 I'm happy to take a pull request for that, but I'd just fix the AllAsyncProjectionShardNames() in the first place

**Comment by jeremydmiller** [comment]
Basically a duplicate with #3165
