### ISSUE TITLE
Cannot shutdown async daemons to do tidy up between integration tests

### ISSUE THREAD

**Issue by danyo1399** [JasperFx/marten#3171]
We need to shutdown the async daemon's between tests in integration tests so we can do cleanup. the marten daemon exposes a Stop method but there is something polling in the IProjectionCoordinator that auto restarts stopped daemons. There is no way to stop and restart the IProjectionCoordinator. 

Is there any way to accomplish the desired behaviour

![CleanShot 2024-04-30 at 10 54 06](https://github.com/JasperFx/marten/assets/45319227/473e46d1-0aa5-4211-b5f3-bc1bd40e7fc1)

**Comment by jeremydmiller** [comment]
I think I'm going to ask for a PR for that one to add something to ProjectionCoordinator to pause all daemons, then restart. there's a polling mechanism internally that's making sure that every known projection & subscription is assigned. 

Another alternative would be to *not* start the daemon when you bootstrap the application, then manually build a daemon in tests. It's not *exactly* like real life, but close.

**Comment by jeremydmiller** [comment]
Use IProjectionCoordinator.StopAsync(), then IProjectionCoordinator.StartAsync() again later.

**Comment by danyo1399** [comment]
is this a new change? StopAsync disposes the daemons which could not be started again.
