### ISSUE TITLE
nuget pipeline is broken? 

### ISSUE THREAD

**Issue by murlakatam** [JasperFx/marten#3187]
Seems like last version available on nuget is 7.10.1 (2 releases behind) https://www.nuget.org/packages/Marten/

**Comment by mysticmind** [comment]
Yes, I see an error with the 7.11.0 NuGet push, we will take a look. Thank for reporting this.

**Comment by mysticmind** [comment]
There was a compile error which has been fixed and v7.11.0 pushed to NuGet successfully. 7.10.2 not available in NuGet is yet to be looked at.
