### ISSUE TITLE
Consider More Proven Document Stores

### ISSUE THREAD

**Issue by mishfit** [JasperFx/Marten#32]
Don't take this as knocking postgres, which I like in other contexts...but it seems that using something slightly less new (and in use in more projects or companies) would be worthwhile. There's always redis.

**Comment by jeremydmiller** [comment]
Redis is an in-memory cache, and Postgresql is about as proven as it gets. The JSON support and JS/V8 embedding is fairly new, but postgres itself is 20-30 years old.

**Comment by mishfit** [comment]
As I understand it, it has persistence to disk by default and has had JSON
support much longer than Postgres without the overhead required to be an
RDBMS

**Comment by jeremydmiller** [comment]
@mishfit Do a spike on it some OSS Friday when things settle down. I'm going to be in the office the week of Nov. 9. Talk about it then?

**Comment by jeremydmiller** [comment]
@mishfit Actually, that's a no on Redis. It's not ACID compliant and that makes it a no go to be an actual transactional db store
