### ISSUE TITLE
DuplicateSubscriptionNamesException: Bug or Feature?

### ISSUE THREAD

**Issue by dvlprx** [JasperFx/marten#3231]
We would use the following configuration, to have each instance of the subscription publish different events to different external system.
- each subscription instance has different filter-options and a unique subscriptionName

This code throws a `DuplicateSubscriptionNamesException`, although we expected it to work, since every instance has it's own unique subscriptionName:

```
// publish all events of "Invoice" streams to an external service
.AddSubscriptionWithServices<MartenSubscriptionTest>(ServiceLifetime.Singleton, o =>
{
    o.SubscriptionName = "TestSubscription_1";
    o.FilterIncomingEventsOnStreamType(typeof(Invoice));
    o.Options.SubscribeFromPresent();
})

// publish all events of "User" streams to another external service
.AddSubscriptionWithServices<MartenSubscriptionTest>(ServiceLifetime.Singleton, o =>
{
    o.SubscriptionName = "TestSubscription_2";
    o.FilterIncomingEventsOnStreamType(typeof(User));
    o.Options.SubscribeFromPresent();
})
```

Sadly there is no overload, that accepts a factory.

**Comment by dvlprx** [comment]
Thanks for clarification.

Maybe you just want to update documentation, telling that a subscription-TYPE can only be used once in the whole system and duplicate-names exception is thrown although there are no duplicate names.

**Comment by jeremydmiller** [comment]
@dvlprx "Maybe you just want to update documentation, telling that a subscription-TYPE can only be used once in the whole system." -- also a good pull request idea for a community project. 

The easy workaround of course is to just use two different types for two different subscriptions.

**Comment by dvlprx** [comment]
> The easy workaround of course is to just use two different types for two different subscriptions.

In our case that is not an options, because it would lead to an unnecessary amount of projects, to isolate the dependency to marten, just to derive subscriptions for each specific projection-type. 

With the above attempt, we could have had a single configurable "exporter-subscription", that is built eg via reflection and feeds our external projection-logic with the already correct events.

**Comment by dvlprx** [comment]
Found a workaround, by using MartenSubscriptionTest<T> in the above sample.
