### ISSUE TITLE
Need a convenience method for finding committed events in the AfterCommit hook

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#324]
Just to make things more discoverable

**Comment by jarroda** [comment]
Are committed events always on the `Updated` collection of the committed `ChangeSet` (and never `Inserted`)? 

![Example](http://i.imgur.com/tz5AGeb.png)
Here I have committed a single new event to the event stream.  The stream was new as well.

**Comment by jarroda** [comment]
Thoughts on PR above? Is `IDocumentSession` the best place for this?

**Comment by jeremydmiller** [comment]
Addressed by https://github.com/JasperFx/marten/pull/332
