### ISSUE TITLE
Compiled queries don't honor new values

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#325]
Note: I'm on holiday in so dont have the project setup on my laptop to write tests or anything. 

------

Ok so I just worked out, given the following query:

```csharp
    public class LoginByIdentifierQuery : ICompiledQuery<Login>
    {
        public Guid Identifier { get; set; }

        public Expression<Func<IQueryable<Login>, Login>> QueryIs()
        {
            return logins => logins.SingleOrDefault(x => x.Identifier == Identifier);
        }
    }
```

Then executed like so:

`var login = session.Query(new LoginByIdentifierQuery {Identifier = identifier});`

Even tho a new value is passed into the query, the executed query is always the first compiled query.

i.e if I pass in:

6a753e7e-05dc-4b83-ad14-1567bcb16bab

Then the next query I pass in:

9d744e88-a34d-4524-b90b-94f9fe799e37

The query is executed with the first GUID not the 2nd.

**Comment by nieve** [comment]
This passes on most recent master:
``` csharp
        public class UserById : ICompiledQuery<User>
        {
            public Guid Id { get; set; }

            public Expression<Func<IQueryable<User>, User>> QueryIs()
            {
                return query => query.SingleOrDefault(x => x.Id == Id);
            }
        }

        [Fact]
        public void a_single_item_reusable_compiled_query()
        {
            var user = theSession.Query(new UserById { Id = _user1.Id });
            user.ShouldNotBeNull();

            var otherUser = theSession.Query(new UserById() {Id = _user5.Id});
            user.ShouldNotBeSameAs(otherUser);
            user.ShouldNotBeTheSameAs(otherUser);
            user.ShouldNotBe(otherUser);
        }
```

**Comment by tim-cools** [comment]
Maybe he meant:  

            var query = new UserById { Id = _user1.Id };
            var user = theSession.Query(query);
            user.ShouldNotBeNull();

            query.Id = _user5.Id;
            var otherUser = theSession.Query(query);
            user.ShouldNotBeSameAs(otherUser);
            user.ShouldNotBeTheSameAs(otherUser);
            user.ShouldNotBe(otherUser);

I haven't tested it though...

**Comment by nieve** [comment]
That passes too:
``` csharp
        [Fact]
        public void a_single_item_reusable_compiled_query()
        {
            var userById = new UserById { Id = _user1.Id };
            var user = theSession.Query(userById);
            user.ShouldNotBeNull();

            userById.Id = _user5.Id;
            var otherUser = theSession.Query(userById);
            user.ShouldNotBeSameAs(otherUser);
            user.ShouldNotBeTheSameAs(otherUser);
            user.ShouldNotBe(otherUser);
        }
```

**Comment by tim-cools** [comment]
Nice, then I don't have a clue...

**Comment by nieve** [comment]
Same here. Thanks for trying though.

**Comment by phillip-haydon** [comment]
I think it's to do with the Guid. I have a couple of queries which use int and there are no problems with them.

**Comment by nieve** [comment]
Yeah, I did use Guids in this test...

**Comment by jeremydmiller** [comment]
@phillip-haydon I wanna close this one if nobody's been able to repro it.
