### ISSUE TITLE
NotSupportedException on a Patch

### ISSUE THREAD

**Issue by Sinvit** [JasperFx/marten#3261]
If to use numeric revision (UseNumericRevisions(true)) and execute Patch, what happens exception NotSupportedException.
As I understand it, this is because in RevisionColumn not imlemented method  WriteMetadataInUpdateStatement and ShouldUpdatePartials=true.

What is the logic of using optimistic locking with revision anyway?

**Comment by jeremydmiller** [comment]
@Sinvit The optimistic concurrency logic is completely described in the documentation here: 

https://martendb.io/documents/concurrency.html#numeric-revisioned-documents

And I need more information from you on what exactly your exception and bug was. Can you give us some repro steps for this? The description isn't really clear what you were trying to do exactly

**Comment by Sinvit** [comment]
1. My DTO:
 `class DocDto 
{
  public long Id { get; set; }
  public string Name { get; set; }
  public int Version { get; set; }
}`

2. Mapping:
` For<DocDto>()
     .DocumentAlias(TableName)
     .DatabaseSchemaName(SchemaName)
     .Identity(d => d.Id)
     .GinIndexJsonData()
     .UseNumericRevisions(true)
     .MultiTenanted();` 

3. When I execute:
 `var patch = session.Patch<DocDto>(d => d.Id == id && d.AnyTenant()).Set("name", "newvalue");`

happens exception NotSupportedException.
As I understand it, this is because in RevisionColumn not imlemented method WriteMetadataInUpdateStatement and ShouldUpdatePartials=true.
