### ISSUE TITLE
Reusing the Event Store always resets the Event Store

### ISSUE THREAD

**Issue by jvdvleuten** [JasperFx/marten#327]
There is a mismatch in the table names used in the mt_stream.sql and the TableName in EventGraph.

Reusing the EventStore with `_.AutoCreateSchemaObjects = AutoCreate.None;` should pass.

**Comment by jvdvleuten** [comment]
@jeremydmiller I am not sure if the test is good enough. It looked scary the everything was getting deleted when it wasn't supposed to. Maybe have a better test to check if the `TableExist` function is actually using the right `TableName`?

**Comment by jeremydmiller** [comment]
@jvdvleuten That's about what I would have done to test that. I'll take a closer look in awhile, but yep, I'll test the TableExists()

**Comment by jeremydmiller** [comment]
This was addressed by #328
