### ISSUE TITLE
Helpers to retrieve the raw JSON

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#33]
For web app scenarios, when all you wanna do is spit the raw json directly over the outgoing HTTP response, just get the raw json data as a string and spit it out over the wire.

Synchronous and Async. Might investigate some kind of lightweight way to strip out the type information that comes in from Json.Net or whatever the serializer is gonna be.

**Comment by ekulakov** [comment]
What methods should be implemented?

**Comment by jeremydmiller** [comment]
@ekulakov Right now, I think all we should do is find by id until we have more concrete use cases, but definitely that one.
