### ISSUE TITLE
Bug: IMartenQueryable doesn't work well with Projection.

### ISSUE THREAD

**Issue by kacey90** [JasperFx/marten#3350]
Spot the difference:

![image](https://github.com/user-attachments/assets/8c558628-bb05-4de7-b6d0-f42810cd1a99)

The above screenshot queries the `MemberKycVerificationStep` with the Marten's Linq IQueryable implementation.

![image](https://github.com/user-attachments/assets/7e39b3b8-10ef-4e4e-a4a4-85dd75243241)

This one uses System.Linq AsEnumerable().

This is a new issue spun from my last [issue](https://github.com/JasperFx/marten/issues/3349) when I decided to try out alternatives.

**Comment by jeremydmiller** [comment]
@kacey90 Hey, you've really got to provide more detail about this for us to have any possible chance of addressing your issue. I can't even see what your queries were. And can you please paste in code and/or exception messages instead of screen shots next time? That would be much more helpful.

**Comment by kacey90** [comment]
@jeremydmiller Forgive me.

```
var results = await _querySession
    .Query<MemberKycVerificationStep>()
    .Where(x => x.MemberId == request.UserId)
    .Select(x => new MemberKycVerificationStepDto
    {
        KycVerificationStepId = x.KycVerificationStepId,
        Name = x.KycVerificationStep.Name,
        DateUpdated = x.DateUpdated,
        Status = x.Status,
        MemberId = x.MemberId
    })
    .ToPagedListAsync(request.PageIndex, request.PageSize, cancellationToken);
return await Result<IPagedList<MemberKycVerificationStepDto>>.SuccessAsync(results);
```

The above snippet returns `Name` of `MemberKycVerificationStepDto` as null as shown in the first screenshot.

```var results = _querySession
    .Query<MemberKycVerificationStep>()
    .Where(x => x.MemberId == request.UserId)
    .AsEnumerable()
    .Select(x => new MemberKycVerificationStepDto
    {
        KycVerificationStepId = x.KycVerificationStepId,
        Name = x.KycVerificationStep.Name,
        DateUpdated = x.DateUpdated,
        Status = x.Status,
        MemberId = x.MemberId
    })
    .ToList();
```
This on the other hand, works for my requirement where the `Name` parameter of `MemberKycVerificationStepDto` gets the expected value as displayed in second screenshot.
I hope it's clear enough.

**Comment by jeremydmiller** [comment]
@kacey90 I'm sorry, I really just don't have enough bandwidth to parse out exactly what it is you're trying to say isn't working. Can you do this through a failing test maybe?

At a guess, I'm not sure if `        Name = x.KycVerificationStep.Name,` would work as a deeply nested member. I think so, but not sure. Might need a real reproduction to help with this. As a workaround, you can always call ToList() before Select() so that it's done in memory.

**Comment by jeremydmiller** [comment]
And sorry, but trying to repro this, I get a "works on my box"
