### ISSUE TITLE
When using paging with an include, Stats.TotalResults is equal to the number of results on the page only instead of the total overall results

### ISSUE THREAD

**Issue by kenuriarte** [JasperFx/marten#3360]
We encountered an unexpected behavior for Stats `TotalResults` after we added an `Include()` call into our query.
Example below:

```
public async Task query_with_include_can_get_the_total_in_results(
    IQuerySession session, 
    int pageNumber,
    int pageSize)
{
    // Example: this returns 40
    var count = session.Query<Target>().Count(x => x.Number > 10);

    var targetInclude = new Dictionary<string, TargetInclude>();
    var list = await session
        .Query<Target>()
        .Where(x => x.Number > 10)
        .Include(x => x.TargetIncludeId, targetInclude)
        .Stats(out var queryStats)
        .Skip((pageNumber - 1) * pageSize)
        .Take(pageSize)
        .ToListAsync();

    // fails because queryStats.TotalResults = results on the page only
    queryStats.TotalResults.ShouldBe(count);
}
```
`count` corresponds to the expected number but `queryStats.TotalResults` matches the number of results in the page

**Notes**
- Checking the generated SQL, there appears to be a duplication of `total_rows` on both the temp table and the primary query. 
- Removing `Include()` produces the expected results

**Related/Similar issues**
https://github.com/JasperFx/marten/issues/2243

**Other info**
Version: Marten 7.23.1

**Comment by elexisvenator** [comment]
More info here - this is a sample of the sql we are seeing being generated. The issue is that the first total rows saved to temp table is forgotten and a new total rows is created based on the temp table itself

```sql
create temp table mt_temp_id_list2 as (
	select d.data, d.document_id, count(*) OVER() as total_rows 
	from flexible_forms.mt_doc_document_list_view as d 
	where (d.tenant_id = $1 and CAST(d.data ->> 'IsArchived' as boolean) = $2 and 
		d.document_id LIKE $3)
		desc OFFSET $4 LIMIT $5
);
select d.data from flexible_forms.mt_doc_userprojection as d where (d.tenant_id = $1 and d.id in (select d.data ->> 'UserId' from mt_temp_id_list2 as d));
select d.data, d.document_id, count(*) OVER() as total_rows from mt_temp_id_list2 as d;
```

**Comment by jeremydmiller** [comment]
@kenuriarte @elexisvenator Try the same with 2.26.1. There have been a couple bug fixes lately with different permutations of Include() + any usage of QueryStatistics.

**Comment by kenuriarte** [comment]
Thanks @jeremydmiller , we'll try out the updated version.

**Comment by kenuriarte** [comment]
Hi @jeremydmiller , upgrading to `7.26.1` resolves the issue. Thank you for the guidance.
Closing the issue.
