### ISSUE TITLE
MetadataToken collisions causing unpredictable Linq query execution when using custom method call parsers

### ISSUE THREAD

**Issue by bittercoder** [JasperFx/marten#3371]
## Problem

The current implementation of `LinqParsing` class utilises the `MetadataToken` of the extension method being resolved to a method call parser to speed up future lookups of the same extension method.  I think this was approach was originally introduced in v7.0.  https://github.com/JasperFx/marten/blob/master/src/Marten/LinqParsing.cs#L140

As per the [.Net docs for MetadataToken](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.metadatatoken?view=net-8.0) it is only guaranteed to be unique within the scope of the a module (so the same Token can be repeated in different assemblies).

As you increase the number of method call parsers (and extension methods) being registered in your own project, you begin to increase the chance of potential collisions with the inbuilt method call parsers registered in the Marten assembly.  Changes in either assembly over time (e.g. adding more types) means that over time collisions may occur just by updating your own project or Marten by adding classes with methods completely unrelated to Linq parsing.

Further confounding things is that the **_order_** in which you execute queries during runtime impacts behaviour - for my particular application the collision was occurring with one of my method call parsers and the inbuilt `MaybeArchived` method.  If I ran a test in my test suite just exercising my extension method, it would work, if I ran the whole suite of tests (which include other tests that execute queries using `MaybeArchived` first) then my later tests would fail sometimes, depending on xunits random order of test execution.

This has ended up being a bit of a nightmare for me because `MaybeArchived` actually just translates to `1 = 1` in the executed query - so it's like our custom Linq expression was never applied to the query 😬 depending on your application this can have security-impacting implications (thankfully for us it only impacted correctness not security because of multi-tenancy) but it has been a confounding bug to track down.

## Proposed fix

I think the method call parser needs to take the module of the method's declaring type into account when caching the lookup of method call parsers.  There may be more efficient ways to do it, but I think something like this would work:

```
private ImHashMap<Module, ImHashMap<int, IMethodCallParser>> _methodParsersByModule =
        ImHashMap<Module, ImHashMap<int, IMethodCallParser>>.Empty;

    internal IMethodCallParser FindMethodParser(MethodCallExpression expression)
    {
        var module = expression.Method.Module;

        if (!_methodParsersByModule.TryFind(module, out var methodParsers))
        {
            methodParsers = ImHashMap<int, IMethodCallParser>.Empty;
            _methodParsersByModule = _methodParsersByModule.AddOrUpdate(module, methodParsers);
        }

        if (methodParsers.TryFind(expression.Method.MetadataToken, out var parser))
        {
            return parser;
        }

        parser = determineMethodParser(expression);

        _methodParsersByModule = _methodParsersByModule.AddOrUpdate(module, methodParsers.AddOrUpdate(expression.Method.MetadataToken, parser));

        return parser;
    }
```

I've created a fix PR for review here: https://github.com/JasperFx/marten/pull/3372

## Detection / work-around

For anyone finding this issue who is maybe stuck on an older version of Marten v7.x (pre this getting fixed) I would suggest adding a rudimentary test to detect instances of collision, something along the lines of the below - the impact of the collision on the correctness of your queries can be highly impactful, particularly if your unlucky and end up colliding with the `MaybeArchived` (most other collisions will probably just result in a runtime error if the arguments don't line up).

```
    public class MethodCollision(MethodInfo method, MethodInfo collidedMethod)
    {
        public string MethodName => method.Name;
        public string MethodDeclaringType => method.DeclaringType!.Name;
        public string ColidedMethodName => collidedMethod.Name;
        public string ColidedMethodDeclaringType => collidedMethod.DeclaringType!.Name;
    }
    
    [Fact]
    public void MetadataTokenUniqueness()
    {
        var extensionMethodsByToken = typeof(SomeTypeInYourProject).Assembly.GetTypes()
            .Where(x => x.Name.Contains("extension", StringComparison.OrdinalIgnoreCase))
            .Where(x => x.IsStatic())
            .SelectMany(x => x.GetMethods(BindingFlags.Public | BindingFlags.Static))
            .ToDictionary(x => x.MetadataToken);
        
        var martenExtensionMethodsByToken = typeof(Marten.LinqExtensions).Assembly.GetTypes()
            .Where(x => x.Name.Contains("extension", StringComparison.OrdinalIgnoreCase))
            .Where(x => x.IsStatic())
            .SelectMany(x => x.GetMethods(BindingFlags.Public | BindingFlags.Static))
            .ToDictionary(x => x.MetadataToken);
        
        var collisions = new List<MethodCollision>();
        
        foreach (var extensionMethod in extensionMethodsByToken)
        {
            if (martenExtensionMethodsByToken.TryGetValue(extensionMethod.Key, out var martenMethod))
            {
                collisions.Add(new MethodCollision(extensionMethod.Value, martenMethod));
            }
        }

        if (collisions.Count > 0)
        {
            Assert.Fail("Collisions detected: " + JsonSerializer.Serialize(collisions));
        }
    }
```

Once you determine there are collisions the you can make changes to your code to prevent them - generally just adding a dummy class in the same file before the extension methods are declared with 1 or more methods can cause the metadata token numbering to change enough to stop the collisions 😢 though there's no guarantee they wont come back when adding other classes/methods to your project later on (the metadata tokens are assigned roughly based on the order of C# files being compiled in your project).

```
public class DummyClassToImpactMetadataToken 
{
    public string Method1() {}
    public string Method2() {} // keep going until you don't have collisions / tests pass again.. good luck!
}
```

**Comment by Hawxy** [comment]
We did have a proposed fix for this a few months ago that got missed by the pile of other PRs: https://github.com/JasperFx/marten/pull/3060. I'm not super fussed by either implementation; whichever one is better for performance is the preference.

**Comment by bittercoder** [comment]
> We did have a proposed fix for this a few months ago that got missed by the pile of other PRs: #3060. I don't have a strong opinion of either implementation; whichever one is better for performance is the preference.

Ahh I missed that earlier issue, sorry to open up a duplicate @Hawxy 😬 

I would need to profile both implementations as I suspect they will be quite close in terms of performance but I would guess the version that relies on bit-shifting (https://github.com/JasperFx/marten/pull/3060/files#diff-5aa1724a43832824d3e1c1ec9a95e5844dbf1f8cc7b5f53decc6eb4c16976195R143) is probably going to be faster as it won't rely on a second level of indirection.  There is (however tiny) a small chance of potential hash collisions between modules, but it's going to be very statistically unlikely, but my proposed PR would avoid that ever happening.  I'm not fussed either way as long as it gets fixed 😁

**Comment by jeremydmiller** [comment]
Looks to be closed by https://github.com/JasperFx/marten/pull/3372

**Comment by bittercoder** [comment]
Thanks for merging this @jeremydmiller @Hawxy much appreciated!
