### ISSUE TITLE
FetchForWriting should assert that it is only usable for single stream projections

### ISSUE THREAD

**Issue by CptWesley** [JasperFx/marten#3379]
Is my understanding correct that the new `FetchForWriting` API is currently not usable for `MultiStreamProjection` cases? I've been running into some trouble trying to set it up accordingly:

```csharp
public sealed record NameChanged
{
    public required string AggregateId { get; init; }

    public required string Name { get; init; }

    public required DateTime Timestamp { get; init; }
}

public sealed record ValueChanged
{
    public required string AggregateId { get; init; }

    public required decimal Value { get; init; }

    public required DateTime Timestamp { get; init; }
}

public sealed class LastChangeDocument
{
    public string Id { get; set; }

    public DateTime LastChange { get; set; }
}

public sealed class LastChangeProjection : MultiStreamProjection<LastChangeDocument, string>
{
    public LastChangeProjection()
    {
        ProjectionVersion = 7;
        Identity<NameChanged>(e => e.AggregateId);
        Identity<ValueChanged>(e => e.AggregateId);
    }

    public LastChangeDocument Apply(NameChanged @event, LastChangeDocument view)
    {
        view.Id = @event.AggregateId;
        view.LastChange = @event.Timestamp;
        return view;
    }

    public LastChangeDocument Apply(ValueChanged @event, LastChangeDocument view)
    {
        view.Id = @event.AggregateId;
        view.LastChange = @event.Timestamp;
        return view;
    }
}
```

I have tried registering the projection as such:
```csharp
StoreOptions.Projections.Add<LastChangeProjection>(ProjectionLifecycle.Async);
```

And am trying to retrieve the projection in the following way:
```csharp
using var session = store.LightweightSession();
var stream = await session.Events.FetchForWriting<LastChangeDocument>(id);
```

I can see the table being correctly crated in the database that holds the projections. But when I run the `FetchForWriting` command, I run into the following exception:

```text
Marten.Exceptions.InvalidProjectionException: AggregateProjection for MartenProjectionsExperiment.Features.Read.LastChangeDocument has no valid create or apply operations
   at Marten.Events.Aggregation.GeneratedAggregateProjectionBase`1.AssembleAndAssertValidity()
   at Marten.Events.Projections.ProjectionOptions.AggregatorFor[T]()
   at Marten.Events.Fetching.FetchLivePlan`2..ctor(EventGraph events, IEventIdentityStrategy`1 identityStrategy, IDocumentStorage`2 documentStorage)
   at Marten.Events.Fetching.LiveFetchPlanner.TryMatch[TDoc,TId](IDocumentStorage`2 storage, IEventIdentityStrategy`1 identity, StoreOptions options, IAggregateFetchPlan`2& plan)
   at Marten.Events.EventStore.determineFetchPlan[TDoc,TId](IDocumentStorage`2 storage, StoreOptions options)
   at Marten.Events.EventStore.findFetchPlan[TDoc,TId]()
   at Marten.Events.EventStore.FetchForWriting[T](String key, CancellationToken cancellation)
```

Which is fair, since the `LastChangeDocument` does indeed not have an `Apply` or `Create` method, but I expect it to be using the ones defined by `LastChangeProjection`.

Is this a known limitation or am I making some obvious mistake?

**Comment by jeremydmiller** [comment]
"Is my understanding correct that the new FetchForWriting API is currently not usable for MultiStreamProjection cases?"

Correct. It's only usable for single stream projections. Its whole point was for "write" models in command handlers. There's no easy way you *could* adapt that for multi-stream projections if you think about it for a bit.

**Comment by CptWesley** [comment]
@jeremydmiller

I understand that for using them as write models this does not make much sense (and goes against certain DDD principles). but in this particular cases I was actually trying to create a read-model. I hoped this could benefit from the cool zero-downtime versioned mechanics for `FetchForWriting` described here https://jeremydmiller.com/2024/03/05/marten-7-makes-write-model-projections-super/

I'm not that familiar with the actual implementation, but I feel like it must be possible to have a similar mechanic for multiple source streams. But this is ofcourse talking about the solution, not the actual problem. I'm mainly trying to find a way to avoid the situation where we have to take down all our pods when deploying a new version in order to rebuild our multi-stream projections instead of our regular Blue/Green deployments. Or even worse: a developer forgetting to rebuild a business-critical projection leading to incorrect results being passed down to the next business unit.

**Comment by jeremydmiller** [comment]
@CptWesley The problem is that there's no easy way for Marten to reason about exactly what the events are for a multi-stream projection. Plus FetchForWriting() also does some locking work on the stream table. It's very much purpose written for "write" models on a single stream at a time.

What you're trying to do is definitely an interesting use case suggestion, but you'd need a brand new API and mechanism for doing that.
