### ISSUE TITLE
Quotation marks incorrectly stripped from json string for System.Text.Json

### ISSUE THREAD

**Issue by CptWesley** [JasperFx/marten#3391]
Currently running into some odd issue with a custom type that is stored in json as a string. When querying the encompassing object everything is well, but when we do a `Select` on that specific field, it seems that it eventually runs the `System.Text.Json` deserializer on the string without the surrounding quotation marks, resulting in an exception.

Stack trace:
```
  Message: 
System.Text.Json.JsonException : '-' is an invalid end of a number. Expected a delimiter. Path: $ | LineNumber: 0 | BytePositionInLine: 4.
  ----> System.Text.Json.JsonReaderException : '-' is an invalid end of a number. Expected a delimiter. LineNumber: 0 | BytePositionInLine: 4.

  Stack Trace: 
ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
SystemTextJsonSerializer.FromJson[T](Stream stream)
SystemTextJsonSerializer.FromJson[T](DbDataReader reader, Int32 index)
SerializationSelector`1.Resolve(DbDataReader reader)
ListQueryHandler`1.Handle(DbDataReader reader, IMartenSession session)
IEnumerable<T>>.Handle(DbDataReader reader, IMartenSession session)
MartenLinqQueryProvider.ExecuteHandler[T](IQueryHandler`1 handler)
--- End of stack trace from previous location ---
ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
ExceptionTransforms.TransformAndThrow(Exception ex)
MartenExceptionTransformer.WrapAndThrow(Exception exception)
MartenLinqQueryProvider.ExecuteHandler[T](IQueryHandler`1 handler)
MartenLinqQueryProvider.Execute[TResult](Expression expression)
MartenLinqQueryable`1.GetEnumerator()
```

The format of the string is `<4 number>-<4 letters>-<more numbers>` e.g. `1234-ABCD-1234567890`, hence the deserializer failing on the `-` (pos 4), because it tries to interpret it as a number up until that point.

Using the debugger I verified that indeed the `ReadOnlySpan<byte>` passed to `JsonSerializer.Deserialize` does not include the surrounding `"` (e.g. `1234-ABCD-1234567890` instead of `"1234-ABCD-1234567890"`).

**Comment by jeremydmiller** [comment]
You're going to have to add more context than this if you want us to have any hope of addressing anything here. Or if you're willing to dive into the code to address this, go for it.

**Comment by CptWesley** [comment]
Minimal reproducable example:
```csharp

using Marten;
using NpgsqlTypes;
using System.Data;
using System.Text.Json;
using System.Text.Json.Serialization;
using Weasel.Postgresql;

namespace MartenSelectKeyIncident;

public static class Program
{
    public static async Task Main(string[] args)
    {
        var store = DocumentStore.For(o =>
        {
            o.Connection("User ID=username;Password=password;Host=localhost;Port=5432;Database=test;");
            o.UseSystemTextJsonForSerialization();

            AddNpgsqlMap(NpgsqlDbType.Varchar, typeof(TrackingId)); // Causes query to fail later.
        });

        var data = Enumerable.Range(0, 10)
            .Select(i => new Dto())
            .ToArray();

        using var saveSession = store.LightweightSession();
        saveSession.Insert(data);
        await saveSession.SaveChangesAsync();

        using var loadSession = store.QuerySession();
        var plainResults = await loadSession.Query<Dto>().ToListAsync(); // No issues
        var plainDeeperResults = await loadSession.Query<Dto>().Select(x => x.TrackingId).ToListAsync(); // Throws exception if type map is registered.
    }

    private static void AddNpgsqlMap(NpgsqlDbType dbType, Type clrType)
    {
        var prev = NpgsqlTypeMapper.Mappings[dbType];
        var clrTypes = prev.ClrTypes.Append(clrType).ToArray();
        NpgsqlTypeMapper.Mappings[dbType] = new(
            prev.NpgsqlDbType,
            prev.DbType,
            prev.DataTypeName,
            clrTypes);
    }
}

public sealed record Dto
{
    public Guid Id { get; init; } = Guid.NewGuid();

    public TrackingId TrackingId { get; init; } = new();
}

[JsonConverter(typeof(TrackingIdConverter))]
public sealed record TrackingId
{
    public string Value { get; init; } = Guid.NewGuid().ToString("N");

    public override string ToString()
        => Value;
}

public sealed class TrackingIdConverter : JsonConverter<TrackingId>
{
    public override TrackingId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => new TrackingId
        {
            Value = JsonSerializer.Deserialize<string>(ref reader, options),
        };

    public override void Write(Utf8JsonWriter writer, TrackingId value, JsonSerializerOptions options)
        => JsonSerializer.Serialize(writer, value.Value, options);
}

```

It appears that registering an `NpgsqlTypeMapper` entry for a type as a `Varchar` (or `Text`) causes the stream returned from the `DbDataReader` to no longer have surrounding `"` around its string value, which causes the deserialization to fail later on.

**Comment by jeremydmiller** [comment]
@CptWesley Man, not trying to be so obnoxious about this, but I think the hard new rule is that if you're having problems with Marten because of custom value types or unusual use cases and you're not a paying JasperFx customer, it's automatically "I take pull requests" territory.

**Comment by jeremydmiller** [comment]
But on a less obnoxious note, see what this PR did: https://github.com/JasperFx/marten/pull/3402

Not saying that directly helps you, but might help you address this. His PR dealt w/ Vogen & StronglyTypedId types. Also this is the idiomatic way in Marten to use value types like that:

https://github.com/JasperFx/marten/blob/db32b919e24c5b31e5533fd4cbe74ddab05786e6/src/ValueTypeTests/registration.cs#L14

**Comment by CptWesley** [comment]
@jeremydmiller That's fully fair, it's just that I'm not in control of my employers budget unfortunately (I'm a big advocate of sponsoring open source projects that are mission critical for us). Yet I am the one having to deal with these issues and any contributions I do have to be done in my personal time, so I'm a bit stuck between a rock and a hard place with these situations. It was never my intent to keep pestering you with these issues.

I'll give it a shot and otherwise will look into making a pull request down the line if I ever find the time and energy.
