### ISSUE TITLE
Tombstone Events Discussion

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#3398]
After moving an event store to be partitioned, the prevalence of tombstone events is much more apparent in the `default` partition, since tombstone events don't get archived. The purpose of partitioning the event store is to help the scaling/speed in larger stores. Having the tombstone events stick around in the active partition, after they have already served their purpose for the high water mark detection, doesn't seem optimal.

Questions for discussion:
- Does archiving tombstone events provide more value than removing them entirely? I can't see much value in keeping archived tombstone events around, unless I am missing something about them.
- At what point could this process happen to the tombstone events? It clearly has to be after the High Water Mark Detection has happened and used it.

**Comment by jeremydmiller** [comment]
@ericgreenmix Sorry for the slow response.

1. No real value after the high water mark is passed that location
2. You can delete the tombstone events anytime after the high water mark is past that point, and I do mean when the event progression is written deeper.

I'm going to close this issue after adding some documentation to this point. For Marten 8 we can consider a more automatic deletion policy
