### ISSUE TITLE
Value types support improvement

### ISSUE THREAD

**Issue by murlakatam** [JasperFx/marten#3401]
1) Currently marten allows to register custom value types but LINQ support for those is limited. 
It is not possible to use them in Select clauses or in marten custom Is-One-Of (any), cause neither [StringValueTypeMember ](src/Marten/Linq/Members/StringValueTypeMember.cs) nor [ValueTypeMember](src/Marten/Linq/Members/ValueTypeMember.cs) implement [IValueTypeMember](https://github.com/JasperFx/marten/blob/a2ac808fa690caa7005b8720417fe2756d4c5456/src/Marten/Linq/Members/IdMember.cs#L15)

2) Exising StringValueTypeMember implementation has a bug that is using [converter ](https://github.com/JasperFx/marten/blob/a2ac808fa690caa7005b8720417fe2756d4c5456/src/Marten/Linq/Members/StringValueTypeMember.cs#L19) instead of value accessor (value accessor needs be used cause we want to reach to the string, not the outer struct type)

3) The ability to enhance LINQ support through a custom [IMemberSource](https://github.com/JasperFx/marten/blob/a2ac808fa690caa7005b8720417fe2756d4c5456/src/Marten/Linq/Members/IMemberSource.cs#L11) is limited since the following types are internal:
- [ValueTypeMember](src/Marten/Linq/Members/ValueTypeMember.cs)
- [StringValueTypeMember ](src/Marten/Linq/Members/StringValueTypeMember.cs) 
Their base classes:
- [StringMember](https://github.com/JasperFx/marten/blob/a2ac808fa690caa7005b8720417fe2756d4c5456/src/Marten/Linq/Members/StringMember.cs#L8)
- [SimpleCastMember](src/Marten/Linq/Members/SimpleCastMember.cs)
Helper classes:
- [MemberComparisonFilter](https://github.com/JasperFx/marten/blob/a2ac808fa690caa7005b8720417fe2756d4c5456/src/Marten/Linq/SqlGeneration/Filters/MemberComparisonFilter.cs#L12C16-L12C38) to implement CreateComparison
- [IValueTypeMember](https://github.com/JasperFx/marten/blob/a2ac808fa690caa7005b8720417fe2756d4c5456/src/Marten/Linq/Members/IdMember.cs#L15) to implement Select and IsOneOf support

**Comment by jeremydmiller** [comment]
@murlakatam Oh, wow, I haven't looked at this yet, but thanks for taking this on! You can't possibly imagine -- well, now you certainly can -- how time consuming and nasty it is to work on the LINQ provider. Endless permutation hell.

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/pull/3402
