### ISSUE TITLE
Unable to pull document when mt_deleted is null for ISoftDeleted documents

### ISSUE THREAD

**Issue by kamalsivalingam** [JasperFx/marten#3410]
Steps:
- Add ISoftDeleted implementation to any existing document model
- Save the document
- Try to fetch the document
- We get an error that the document is not found

Apparently mt_deleted is set to null and when it is null, we are not able to pull the document

Fix:
Needed to run a data migration script to set mt_deleted to false

**Comment by jeremydmiller** [comment]
To be more specific, this is from adding soft delete semantics to an existing table/document

**Comment by jeremydmiller** [comment]
@kamalsivalingam Sorry man, it's "works on my box". The default value for that column when it's added is FALSE. That should be good enough. I just tested this, and it worked just fine. I think you've got something else going on.
