### ISSUE TITLE
Exception should probably be raised if automatically generated index name is truncated

### ISSUE THREAD

**Issue by nkosi23** [JasperFx/marten#3430]
I just faced a development-time issue related to the fact that Marten seemed unable to detect that an index for which it has already created a migration (that has been applied to the DB) is already present, thus making the `assert database changes` at startup fail, the changes detected were:

```
drop index if exists myproject_operations.mt_doc_appointmentscheduling_appointment_idx_calendar_idappoint;
CREATE INDEX mt_doc_appointmentscheduling_appointment_idx_calendar_idappointment_date_time ON myproject_operations.mt_doc_appointmentscheduling_appointment USING btree ((CAST(data ->> 'CalendarId' as uuid)), (myproject_operations.mt_immutable_timestamptz(data ->> 'AppointmentDateTime')));
```

Upon further inspection, I noticed that the name `mt_doc_appointmentscheduling_appointment_idx_calendar_idappoint` used in the `drop index clause` is truncated compared to the actual index name created `mt_doc_appointmentscheduling_appointment_idx_calendar_idappointment_date_time`.

Setting the index name manually to a shorter one indeed solved the issue. Maybe throwing an exception to require the user to manually set an index name when the one provided is too long could be a most appropriate approach? I figured it out within 5-10 minutes but I was left scratching my head for a little while initially.

**Comment by jeremydmiller** [comment]
@nkosi23 You just walked right into an "I take pull requests", but yes

**Comment by jeremydmiller** [comment]
@nkosi23 I'm looking at this one now. Got the hood up on Weasel index definition detection
