### ISSUE TITLE
!.Any() regression

### ISSUE THREAD

**Issue by AlexSikilinda** [JasperFx/marten#3439]
It seems like Marten is generating an incorrect SQL for scenarios when we want to check if a nested collection is empty, e.g.:

```
session.Query<MyDocument>().Where(doc => !doc.NestedCollection.Any());
```
will produce something like 

```
  select d.id, d.data, d.mt_version 
  from public.mt_doc_mydocument as d 
  where d.data @? '$ ? (@.NestedCollection[*] == null || @.NestedCollection[*].size() == 0)' 
```

If the collection is empty (`"NestedCollection":[]`), the second part will be always false which is caused by applying `[*]` to the collection, so 
`@.NestedCollection[*].size() == 0` is `false`, but `@.NestedCollection.size() == 0` seems to work fine.

I believe the issue was introduced with this change in **CollectionIsEmpty**:
![image](https://github.com/user-attachments/assets/741dcaa6-1bcf-4e65-917f-0fb23fd588bf)

**Comment by jeremydmiller** [comment]
@AlexSikilinda Since you're already deep into that, would you mind just doing the pull request to address it?

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/commit/c82ea9e480871610ad6bf8f65c7bb7ae8b5b56d5
