### ISSUE TITLE
Querying Vogen value types throws exception

### ISSUE THREAD

**Issue by rena0157** [JasperFx/marten#3450]
When using the new value type integration in Marten an exception is thrown when trying to query the value.

Reproduction can be seen [here](https://github.com/rena0157/marten-issue-2/blob/main/MartenIssue2/Program.cs)

**Comment by jeremydmiller** [comment]
@nkosi23 Marten supports using the logical Where() clause in any kind of First/Single/OrDefault operator.

**Comment by jeremydmiller** [comment]
The existing value type support was assuming that the value types would be `struct`. The `record` usage is breaking it for now. I can work around that I think

**Comment by jeremydmiller** [comment]
Okay, so this was a couple different things:

1. Marten was assuming that all the value types were going to be `struct`, so I had to make it work around that a little bit
2. The LINQ support had to be explicitly taught how to do `ValueType == SimpleType` comparisons in the SQL generation
