### ISSUE TITLE
Just use OrderBySql()

### ISSUE THREAD

**Issue by overwidee** [JasperFx/marten#3463]
Why should I waste my working time sorting by date, so that values ​​with **null** are displayed at the end of the list?
I read everything, but your shitty library can't do such basic things.
Why can't I write an expression `.OrderBy(x => x.LastModified == null).ThenByOrdering(x => x.LastModified)`?
And **hasValue**, and **.OrderByDescending(x => x.LastModified ?? minimumDate)** - Nothing helps!
Write that we use linq methods that can be translated into a sql query, but shockingly, what I want to do is easy to write
`ORDER BY (data->>'LastModified')::timestamp WITH TIME ZONE DESC NULLS LAST`

Some degenerate linked this to the project, and now I'm sitting here suffering. 
If you want me to do it with separate requests, but no guys, adequate technology should be able to handle such things easily.
Many years of experience with Linq are crossed out by this technology. The things that work are so basic that they will only be useful in lab work in college, but definitely not in a real project.

**Comment by jeremydmiller** [comment]
If anyone else sees this, you can easily use the `OrderBySql()` operator to do exactly what this guy was trying to do. In the meantime, I'm blocking this clown because life is short
