### ISSUE TITLE
Clarification needed : FetchForWriting usage with MultiStream projection

### ISSUE THREAD

**Issue by Astenna** [JasperFx/marten#3478]
According to [docs](https://martendb.io/scenarios/command_handler_workflow.html#fetchforwriting)  and [issue 3379](https://github.com/JasperFx/marten/issues/3379) `FetchForWriting` API is only possible with single stream aggregation projections. Hence, I would expect some kind of exception / error on an attempt to use `FetchForWriting<T>` where T is an aggregate coming from an inline, multi-stream projection. However, it seems to work correctly without any problems.

Can someone clarify? It's probably either of these two:
- the `FetchForWriting<T>` can be used with multistream, inline projections (then docs need clarification/update)
- the `FetchForWriting<T>` can NOT be used with multistream (then why is no exception thrown?)

I'm using marten 7.29.0.

**Comment by jeremydmiller** [comment]
"the FetchForWriting<T> can NOT be used with multistream (then why is no exception thrown?)"

-- because I'm not omniscient and it never even occurred to me that anyone would try that. The docs are correct. We'll do something to make the api throw an exception telling you that's invalid.
