### ISSUE TITLE
Wait for non stale results extension for LINQ

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#3489]
I **hated** this about RavenDb years ago, but here we are.

For multi-stream projections, it's just not feasible to run them as Inline if there's any contention between threads. But other folks want to query the results of multi-stream projections with strong consistency.

As a workaround, how about an option to add a "wait for non stale results" waiter in LINQ specifically for multi-stream projections. This would "wait" until the multi-stream projection was seen to be caught up w/ the the high water mark at the initial request, then proceed

**Comment by AlexZeitler** [comment]
Since I have already entered the territory of multi-stream projections, I can imagine that I will (have to) use it sooner or later.

**Comment by jeremydmiller** [comment]
## Notes

* Add an option to search on multiple shard names on `ProjectionProgressStatement`
* Easy ability to find the shard names for a named projection
* On the first pass, query for the high water mark & all shards of the projection for that database
* New `IMartenDatabase.ProjectionProgressFor(string projectionName)` that returns the high water mark & all for that shard. Make sure it fills in for any projection shards that have not yet started
* Track some kind of "wait for action" on `MartenLinqQueryProvider`? Execute *first* as part of ExecuteHandlerAsync

**Comment by jeremydmiller** [comment]
## Test Cases on LINQ operators

- [ ] With ToListAsync()
- [ ] With FirstOrDefaultAsync()
- [ ] to AsyncEnumerable
- [ ] StreamOne
- [ ] StreamMany
