### ISSUE TITLE
BulkInsert hangs on specific data and never returns

### ISSUE THREAD

**Issue by meixger** [JasperFx/marten#350]
I have found specific data in my bulk insert witch reproducibly hangs on DataStore.BulkInsert()

This bug seems to bubble up from https://github.com/npgsql/npgsql/issues/816 which was resolved in  `npgsql >= 3.0.4`

My workaround is to simply `Update-Package Npgsql -Version 3.0.4`

**Comment by jeremydmiller** [comment]
@meixger Thanks for the heads up. I'm updating things right now.
