### ISSUE TITLE
Live aggregations may be erroneously handled when adding Marten-managed tenant partitions

### ISSUE THREAD

**Issue by kseitz10** [JasperFx/marten#3504]
We have observed an issue in our test environment where one of our live aggregations is getting detected by the code that registers new partitioned tenants in Marten, `DocumentStore.Advanced.AddMartenManagedTenantsAsync(...)`.

Reproduction of the issue depends upon whether the live aggregation has been invoked since the application started up. Partitioning is successful for all documents/results if I do not access the API that makes use of the live aggregation prior to partitioning. Happens regardless of the projection code being pre-generated.

When reproduced, the live aggregates are returned in the partitioning operation results as `RequiresTableRebuild`.

Marten v7.30.2

(For what it's worth, it would be very helpful to be able to ensure that this operation either is a) entirely successful or b) the changes get rolled back.)

**Comment by jeremydmiller** [comment]
@kseitz10 Checked it out, and Marten is not building table storage for live aggregated projections, so that part is working correctly as is.

here's the regression test I added to verify:

```csharp

    [Fact]
    public async Task should_not_build_storage_for_live_aggregations()
    {
        StoreOptions(opts =>
        {
            opts.Policies.AllDocumentsAreMultiTenanted();
            opts.Policies.PartitionMultiTenantedDocumentsUsingMartenManagement("tenants");

            opts.Events.TenancyStyle = TenancyStyle.Conjoined;

            opts.Schema.For<Target>();
            opts.Schema.For<User>();

            opts.Projections.LiveStreamAggregation<SimpleAggregate>();
        }, true);

        var streamId = theSession.Events.StartStream<SimpleAggregate>(new AEvent(), new BEvent()).Id;
        await theSession.SaveChangesAsync();

        var aggregate = theSession.Events.AggregateStreamAsync<SimpleAggregate>(streamId);
        aggregate.ShouldNotBeNull();

        await theStore
            .Advanced
            // This is ensuring that there are tenant id partitions for all multi-tenanted documents
            // with the named tenant ids
            .AddMartenManagedTenantsAsync(CancellationToken.None, "a1", "a2", "a3");

        await theStore.Storage.ApplyAllConfiguredChangesToDatabaseAsync();

        // Seeing if the table for SimpleAggregate exists, and it should *not*
        var table = await theStore.Storage.Database.ExistingTableFor(typeof(SimpleAggregate));
        table.ShouldBeNull();
    }
```
