### ISSUE TITLE
When Using Archived Stream Partitioning Tombstone Stream creation fails on insert 

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#3514]
NPGSQL Exception -`there is no unique or exclusion constraint matching the ON CONFLICT specification`

`is_archived` needs to be factored into the `ON CONFLICT` pk fields of the insert statement in `EstablishTombstoneStream`.

PR incoming

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/pull/3515
