### ISSUE TITLE
StreamAction AddEvents sets @event.Id = CombGuidIdGeneration.NewGuid(), but AddEvent doesn't

### ISSUE THREAD

**Issue by haefele** [JasperFx/marten#3533]
I personally didn't run into any problems because of it, I just stumbled upon this difference, and thought "is that wrong?".

[The difference is right here](https://github.com/JasperFx/marten/blob/119a461c052b34fedabfd8dd6829048930d06964/src/Marten/Events/StreamAction.cs#L115-L141).

**Comment by jeremydmiller** [comment]
That's an I take pull requests. Just an oversight. How did you even get to that?

**Comment by haefele** [comment]
I was checking out when the IEvent.Id is assigned when appending new events to a stream.
And then I stumbled upon this little oversight.

Anyways, PR will be ready in a couple of minutes, just running the `EventSourcingTests` to make sure everything is still working!
