### ISSUE TITLE
Add support for .NET 9

### ISSUE THREAD

**Issue by glen-84** [JasperFx/marten#3553]
> warning NU1608: Detected package version outside of dependency constraint: JasperFx.RuntimeCompiler 3.5.0 requires Microsoft.Extensions.Logging.Abstractions (>= 6.0.0 && < 9.0.0) but version Microsoft.Extensions.Logging.Abstractions 9.0.0 was resolved.

**Comment by tomap** [comment]
It's funny how 9.0.0-rc1 was lower (<) than 9.0.0 

Maybe when doing the migration to support .Net 9, choose < 9.99.99 to meaning < 10 AND < 10.0.0-preview... so that it will fail even with version 10 preview/rc

**Comment by tomap** [comment]
And it seems this doc is not 100% accurate: https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#semantic-versioning-200

**Comment by jeremydmiller** [comment]
https://bsky.app/profile/did:plc:af62br4qi2dl43eogb3jqimk/post/3laqr57pvm227

**Comment by tomap** [comment]
> https://bsky.app/profile/did:plc:af62br4qi2dl43eogb3jqimk/post/3laqr57pvm227

Faire enough :) 

https://github.com/JasperFx/jasperfx/pull/18 but absolutely not sure I got everything right

**Comment by jeremydmiller** [comment]
@tomap Hey, that's not actually used by Marten yet. That codebase is for Marten 8 / Wolverine 4

**Comment by glen-84** [comment]
Thanks for the update. Will you be updating the version of `JasperFx.RuntimeCompiler`?
