### ISSUE TITLE
Live aggregations do not map metadata fields

### ISSUE THREAD

**Issue by michaeltnguyen** [JasperFx/marten#3567]
We have the following setup:

```
public record MyProjection {
   public DateTimeOffset LastModified { get; set; }
   public int Version { get; set; }
}

Schema
    .For<MyProjection>()
    .Metadata(m =>
    {
        m.LastModified.MapTo(x => x.LastModified);
        m.Revision.Mapto(x => x.Version);
    };
```

When loading the projection via `session.LoadAsync<MyProjection>`, the both the `LastModified` and `Version` fields are populated correctly.  However, when using `session.Events.AggregateStreamAsync(version: 3)`, only the `Version` field is populated.  `LastModified` is not.

I would have expected either both metadata fields to be applied, or neither.

For now, our workaround is to, when using `AggregateStreamAsync`, to apply metadata manually.  Please let me know if this is intended, or if you'd like a PR.  Thanks!

**Comment by jeremydmiller** [comment]
@michaeltnguyen Meh, that's not really a bug, you just hit an unusual combination. The `Metadata` stuff you're using up there is all in regards to document storage, and when you're using "aggregate stream", you're not loading the projected data as a document.

If this is Marten 7.*, the usage of `m.Revision.Mapto(x => x.Version);` is not necessary. For the equivalent of `m.LastModified.MapTo(x => x.LastModified);`, see the `ApplyMetadata()` from event sourcing

I might try to improve the documentation I guess on this, but I don't think there's anything actionable in terms of code in this issue.

**Comment by michaeltnguyen** [comment]
Got it, thanks for the reply.

We were previously just putting the `Apply` methods inside the `MyProjection` record itself, per https://martendb.io/events/projections/aggregate-projections.

```
public record MyProjection {
    public void Apply(MyProjection p, Event e);
}
```

Does this mean that the recommended structure for a projection is to have both a `record T` AND a class extending `SingleStreamProjection<T>`?  (since we are required to subclass SingleStreamProjection in order to override `ApplyMetaData`?

**Comment by jeremydmiller** [comment]
@michaeltnguyen None of that changed. If you prefer to just keep the `Create` or `Apply` methods in the aggregated document and don't need any kind of fancy workflow, just keep doing that. Marten creates a `SingleStreamProjection<T>` around your type behind the scenes. If you want to use `ApplyMetadata()`, then yeah, you'd have to move the `Apply` / `Create` to a dedicated `SingleStreamProjection<MyProjection>`
