### ISSUE TITLE
NotSupportedException thrown with complex query

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/marten#357]
The following query throws `NotSupportedExeption` (CollectionAnyContainmentWhereFragment.cs line 102):

```csharp
var userDinners = documentSession.Query<Dinner>()
								 .Where(
									 x =>
										 x.HostedById == nerdName || x.HostedBy == nerdName ||
										 x.RSVPs.Any(
											 r =>
												 r.AttendeeNameId == nerdName ||
												 (r.AttendeeNameId == null &&
												  r.AttendeeName == nerdName)))
								 .OrderBy(x => x.EventDate)
								 .AsEnumerable();
```

The query _does run_ however if you split the `Any()` call into two different clauses such as:

```csharp
var userDinners = documentSession.Query<Dinner>()
								 .Where(x => x.HostedById == nerdName || x.HostedBy == nerdName ||
											 x.RSVPs.Any(r => r.AttendeeNameId == nerdName) ||
											 x.RSVPs.Any(
												 r =>
													 r.AttendeeNameId == null &&
													 r.AttendeeName == nerdName))
								 .OrderBy(x => x.EventDate)
								 .AsEnumerable();
```

It seems as if the `CollectionAnyContainmentWhereFragment.gatherSearch()` doesn't support anything other than `ExpressionType.AndAlso` or `ExpressionType.Equal`.  This seems like a reasonable query to me, so I would imagine it _should_ work, but the work-around is also simple enough, so it may not be worth fixing.

**Comment by jeremydmiller** [comment]
@CodingGorilla I honestly think the answer here is going to be to doc it. This would be a fair amount of work for something that I don't think would be that common and has a workaround.

**Comment by CodingGorilla** [comment]
Understood and agreed.  At least there's a record of the potential problem and fix in case others run into it.
