### ISSUE TITLE
Issue wit soft delete and partitioning

### ISSUE THREAD

**Issue by keyroll-99** [JasperFx/marten#3572]
Hi, I encountered an issue with migration when using soft delete and partitioning via the SoftDeletedWithPartitioning method.

When I try to generate a migration, the first migration works well, but for the second and subsequent migrations, it generates code even though I haven't made any changes. When I inspect the SchemaMigration object, it seems like Marten expects the value "TRUE" but receives "true". Please see the screenshot below.

![Screenshot 2024-11-28 at 13 54 37](https://github.com/user-attachments/assets/f8cc2f1b-2328-4cb2-a205-6950198c9262)

![Screenshot 2024-11-28 at 13 54 59](https://github.com/user-attachments/assets/77cfd17b-5db3-4d61-8e5a-ed96b5b02512)

Here code sample
```cshar
using Marten;
using Microsoft.AspNetCore.Http.HttpResults;
using Oakton;
using WebApplication1;



var builder = WebApplication.CreateBuilder(args);
builder.Host.ApplyOaktonExtensions();

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddMarten(opt => {
    opt.Connection("Server=127.0.0.1;Port=5432;Database=marten;User Id=admin;Password=passwd;Command Timeout=3600");
    opt.DatabaseSchemaName = "Sample";
    opt.Schema.For<SampleDocument>().SoftDeletedWithPartitioning();
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.MapGet("/Test", async (IDocumentStore store) => {
    var migration = await store.Storage.Database.CreateMigrationAsync();
    return Results.Ok(migration.Deltas);
});


return await app.RunOaktonCommands(args);

public class SampleDocument
{
    public Guid Id { get; set; }
}

```

**Comment by jeremydmiller** [comment]
@keyroll-99 I'm looking at this now, thanks for the issue write up!
