### ISSUE TITLE
Application does not start if subscription is dependent in any level on Marten services

### ISSUE THREAD

**Issue by piotreksda** [JasperFx/marten#3576]
Infected version: 7.31.0 and above

[Discord thread](https://discord.com/channels/1074998995086225460/1311691240009629778)

[Repository for reproduction of error](https://github.com/piotreksda/marten-scoped-subscriptions-issue)

![image](https://github.com/user-attachments/assets/6aca242a-a2ff-4ee7-87c6-16fb343890ee)

**Comment by jeremydmiller** [comment]
For anybody reading this, the very easy workaround is to *not inject Marten services into a subscription*. Instead use the IDocumentOperations service that is pushed into your class.

**Comment by jeremydmiller** [comment]
@piotreksda sorry, but the way I'm "beating" this is through documentation and maybe a better error message. The real answer is "don't do it that way"

**Comment by jeremydmiller** [comment]
Might have to address this in Marten 8. We need to redo how the IoC-loaded subscriptions work and move all the event filtering rules out of base classes. Or finally give up and use constructor injection around the projection. For right now, this is strictly a documentation issue.
