### ISSUE TITLE
Usage of CombGuid

### ISSUE THREAD

**Issue by tim-cools** [JasperFx/marten#359]
I did some tests insert/read tests on large tables with the different ID generation algorithms. And I believe the SequentialGuid (former ComGuid) can be used to improve performance of inserts in big tables:

![image](https://cloud.githubusercontent.com/assets/2794618/15240647/626f6d84-18eb-11e6-8fe5-02234700158f.png)

The test does inserts in batches 100000 from a single client, each ID type after each other and the Guid (organg) is slower by a rough 25% (table size 46.300.000, the tests are still running) than the 3 other sequential id types.
. 
- The X axis values should be multiplied by 100
- the tests were running on an AWS RDS db.t2.micro
- I'm still not sure why the time almost doubles around 12M, but I have seen this with almost all my other benchmarks on RDS...

I also measured 3 kinds of reads. The results of the read tests make less sense are not as different as the writes and very similar.
- the first 2048 records in history: the SequentialGuid has a slight advantage over the other, 
![image](https://cloud.githubusercontent.com/assets/2794618/15240549/d37abf84-18ea-11e6-8840-13262a3f4f79.png)

- the last 2048 all very similar
![image](https://cloud.githubusercontent.com/assets/2794618/15240598/1a54d1ec-18eb-11e6-8fb2-434fb5f1e415.png)

- 2048 random documents: here the default (random) guid has a small performance advantage
![image](https://cloud.githubusercontent.com/assets/2794618/15240577/00956e7e-18eb-11e6-91d8-373e60a2a25f.png)

This off-course only tests the PK in an unusual way and does not represent most real life scenario. Except for batch insert will most transactions only insert a couple id's in the same PK index.And I'm happy to run the tests again based on feedback. 
But nevertheless I believe that it is useful to use the the SequentialGuid by default for documents and especially for events. As the table can become very big. Having records in the (almost) correct order in the PK index makes sense in many use-cases.

I say almost because since the id (timestamp) is generated on the clients it can happen that the clients clocks are out of sink and generate an ID in the wrong order. But I don't think that is an issue as long as the event sequence number is correct.

I will rename the CombGuid to SequentialGuid because CombGuid is the implementation name, and is the more SequentialGuid general definition. And try to update the doc a bit.

A nice article recently found concerning ID generation in distributed environments is this one from Instgram: http://instagram-engineering.tumblr.com/post/10853187575/sharding-ids-at-instagram
They use a more advanced approach that combines a timestamp, a node id and a sequence number.

All feedback welcome!

**Comment by jeremydmiller** [comment]
@tim-cools Everything here sounds good to me. Just as a heads up, I'm doing a lot of work on the id generation today and I'm probably moving things around into its own "Identity" namespace. If there's any nasty merge conflict problem that I cause you here, I'll deal with that.
