### ISSUE TITLE
Missing support for DateTimeOffset with offset in LINQ queries?

### ISSUE THREAD

**Issue by Torgeir-Hansen** [JasperFx/marten#3590]
Hi,

When I try to query with LINQ using a DateTimeOffset with a timezone, it throws an exception.
If I use UTC time it works as expected.

It seems I can read and store documents with a timezone offset just fine, I'm hoping this is just a minor tweak that needs to be done to the linq provider? 🤔

Code to reproduce (LastUpdated on Person is a DateTimeOffset):
```csharp
IQuerySession session = _database.AsQueryable().Session!;
DateTimeOffset queryTime = DateTimeOffset.Now.AddDays(-1);
IReadOnlyList<Person> queryResult = await session.Query<Person>()
   .Where(p => p.LastUpdated < queryTime).ToListAsync(token: cancellationToken);
```

Exception message: 

> Cannot write DateTimeOffset with Offset=01:00:00 to PostgreSQL type 'timestamp with time zone', only offset 0 (UTC) is supported.  (Parameter 'value')

Stack trace:

>    at Npgsql.Internal.Converters.DateTimeOffsetConverter.WriteCore(PgWriter writer, DateTimeOffset value)
>    at Npgsql.Internal.PgBufferedConverter`1.Write(PgWriter writer, T value)
>    at Npgsql.Internal.PgBufferedConverter`1.WriteAsObject(Boolean async, PgWriter writer, Object value, CancellationToken cancellationToken)
>    at Npgsql.Internal.PgConverter.WriteAsObjectAsync(PgWriter writer, Object value, CancellationToken cancellationToken)
>    at Npgsql.NpgsqlParameter.WriteValue(Boolean async, PgWriter writer, CancellationToken cancellationToken)
>    at Npgsql.NpgsqlParameter.Write(Boolean async, PgWriter writer, CancellationToken cancellationToken)
>    at Npgsql.Internal.NpgsqlConnector.WriteBind(List`1 parameters, String portal, Byte[] asciiName, Boolean allResultTypesAreUnknown, Boolean[] unknownResultTypeList, Boolean async, CancellationToken cancellationToken)
>    at Npgsql.NpgsqlCommand.<Write>g__WriteExecute|101_0(NpgsqlConnector connector, Boolean async, Boolean flush, CancellationToken cancellationToken)
>    at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
>    at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
>    at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteReaderAsync(NpgsqlBatch batch, CancellationToken token)
>    at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteReaderAsync(NpgsqlBatch batch, CancellationToken token)
>    at Polly.ResiliencePipeline.<>c__9`2.<<ExecuteAsync>b__9_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Polly.Outcome`1.GetResultOrRethrow()
>    at Polly.ResiliencePipeline.ExecuteAsync[TResult,TState](Func`3 callback, TState state, CancellationToken cancellationToken)
>    at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
>    at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
>    at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
>    at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
>    at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
>    at Marten.Linq.MartenLinqQueryable`1.ToListAsync[TResult](CancellationToken token)
>

**Comment by jeremydmiller** [comment]
It's a limitation in more recent versions of Npgsql. And the "fix" is probably going to be just having Marten quietly convert the time to UTC for you anyway. This is going to be an "I take pull requests" issue most likely if you're interested.

**Comment by jeremydmiller** [comment]
@Torgeir-Hansen Meh, I'm trying to do a bug sweep and release today. I'll take a shot at this, but all it's going to do is make a ToUniversal() conversion as it builds the NpgsqlCommand.

**Comment by jeremydmiller** [comment]
The NodaTime LINQ support is a nightmare too, no free lunch here.
