### ISSUE TITLE
Notify/Listen for Documents and Events

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/marten#362]
For document insert/update/delete as well as for event source append events, use the postgresql notify/listen feature to allow for notifications. This would allow some interesting scenarios such as listening for event notifications and then publishing to a bus. This could then be expanded to fulfill more reactive style scenarios for pub/sub notifications when documents are created/modified/deleted and/or events are appended.

This might be as easy as modifying the functions for document upsert/delete to add a call to the notify function. I see that @jeremydmiller may already be thinking along similar lines for events as well:

https://github.com/JasperFx/marten/blob/master/src/Marten/Schema/SQL/mt_rolling_buffer.sql#L113

Open for dicussion would be how to configure this. Always on by default, turned all for all document types, configurable on a per document type basis, etc.? Similar questions related to appending events as well.

**Comment by tim-cools** [comment]
This would be great for updating user interfaces real-time based on read models! And it also can be used to be used implement a catch-up subscription..

I tend to lean to an opt-in approach for this to avoid overhead, but I'm not really aware of the cost of using pg_notify. It might be not worth it.

Possible config:

```
DocumentStore.For(options => {
  option.Schema.For<User>().WithNotifications()
  option.Schema.For<User>().WithNotifications(for => for.Inserts())
  option.Events.WithNotifications();
});
```

For the client side I was thinking of something like this:

```
using (var session = store.NotificationSession()) {
  
  session.ListenToAll<User>(handlerMethod);
  session.ListenToUpdates<User>(handlerMethod);
  session.ListenToInserts<User>(handlerMethod);
  session.ListenToDeletes<User>(handlerMethod);
  
  session.ListenToAllEvents(handlerMethod);
  session.ListenToEvent<UserCreated>(handlerMethod);  
  
}
```

But other approaches might be worth looking into. Like listener classes that implement specific interfaces: `IListenToDocumentUpdates<User>`, `IListenToAllEvents`, ...

One other thing we need to take into account is connection recovery.

**Comment by jeffdoolittle** [comment]
My consideration of pg_notify is related to trying to avoid publishing phantom messages/events or experiencing dropped notifications. If you put the notifications into Marten itself, you're going to have the possibility of either one or the other of these two nefarious scenarios:

1) you publish before you persist, and the persist fails, leading to a phantom notification
2) you persist before you publish, and the publish fails, leading to a dropped notification

Of course pg_notify doesn't necessarily perfect deal with item 3 either, but I was thinking it could at least help address issue 1.

I'm not an expert on pg_notify by any means, but I think Marten would benefit from some notion of adopting a reactive approach.

**Comment by jeremydmiller** [comment]
@jeffdoolittle @tim-cools My thought with the event store is to only really use pg_notify as a ["Claim Check"](http://www.enterpriseintegrationpatterns.com/patterns/messaging/StoreInLibrary.html) that some kind of data is available, but really depend on the rolling buffer table as a de facto queueing mechanism.

In this case, the rolling buffer table is the real thing, and pg_notify would just be used to tell a listener that there's some new stuff available in the queue. Mostly just to try to optimize the polling.

I don't know that I completely trust pg_notify for any kind of high volume activity or anything that requires guaranteed delivery. I thought it was flakey when I was using it against older versions of Postgres a couple years ago.

**Comment by jeffdoolittle** [comment]
so basically, subscribe and tell me if if something has changed, but in case I miss anything, I can still ask for anything after a specific version/sequence number?

**Comment by jeremydmiller** [comment]
You'd subscribe through a queueing mechanism maybe, but yeah. 

What kinds of things are you wanting to do? This is specifically to subscribe for notifications outside of the original TX, right?

**Comment by tim-cools** [comment]
I was thinking to push updates of my view models by listening to marten and then publishing them through web-sockets to the web client . If you could subscribe to this you don't need an external bus to send these messages. This can be useful in case you have multiple web-servers, with only one server you can send these updates from the software itself

I had only visualization in mind. And not intended to use this for logic that need consistency. If I send view model updates on a bus I don't use persistent messaging anyway...

**Comment by jeffdoolittle** [comment]
I'm thinking about client updates in near-real-time like firebase and meteor

**Comment by jvdvleuten** [comment]
Should this really be implemented in Marten? You can already opt in to it like this right?

```
public class MartenEventPublisher : DocumentSessionListenerBase
{
    private readonly IEventBus _eventBus;

    public MartenEventPublisher(IEventBus eventBus)
    {
        _eventBus = eventBus;
    }

    public override async Task AfterCommitAsync(IDocumentSession session, CancellationToken token)
    {
        var last = session.LastCommit;

        foreach (var @event in last.GetEvents())
        {
            await _eventBus.PublishAsync((dynamic)@event.Data).ConfigureAwait(false);
        }
    }
}
```

The IEventBus can be anything you want right?

The only thing missing right now, is that the `IEvent` version does not get properly updated after the insert and a global version/sequence number is missing.

In your services you could query of the Event store yourself, based on version numbers and catch up if needed.

Or I am missing something important?

**Comment by jeremydmiller** [comment]
The feedback from 2nd Quadrant was that notify/listen is really only useful to prompt other processes to "wake up." There's absolutely no guaranteed delivery and it doesn't guarantee the order. 

For the event store, the current theory is that we'll use sequential Guid's for the event Id, then just use that to "know" where to start catching up in the async daemon. If that works out, it becomes pretty easy to poll for new events, but we could still use pg_notify() in the event capture as just a "wake up, there are events ready for you" coat check kind of message.

**Comment by jeffdoolittle** [comment]
sounds very reasonable to me. basically, notify/listen may be nice-to-have but certainly not required nor particularly reliable for anything except "hey, you may want to check for more stuff."

**Comment by tim-cools** [comment]
Good to know! Sounds valuable feedback!

**Comment by jeremydmiller** [comment]
Hey everyone, just for the sake of pruning the GH list, I'm going to close this one for now. You *could* do this on your own in a document listener and I probably will add this to the event store as part of the async daemon.
