### ISSUE TITLE
HiLo generation not working

### ISSUE THREAD

**Issue by superlogical** [JasperFx/marten#363]
I've tried specifying that the HiLo generation should start at 1000, but it starts at 1 so I'm not sure what I am doing wrong. I've even specified it in every place I can e.g:

````csharp

//
// On the entity
//

[HiloSequence(Increment = 1, MaxLo = 1000)]
public class Order
{
    ...
}

//
// In container setup..
//

IDocumentStore store = DocumentStore.For(options =>
{
    options.Connection(config.ConnectionString);

    options.HiloSequenceDefaults.Increment = 1;
    options.HiloSequenceDefaults.MaxLo = 1000;

    options.Schema.Include<SprightlyMartenRegistry>();
    options.Schema.For<Order>().HiloSettings(new HiloSettings { Increment = 1, MaxLo = 1000 });
});

//
// Using the registry...
//
public class SprightlyMartenRegistry : Marten.MartenRegistry
{
    public SprightlyMartenRegistry()
    {
        ...
        
        var hilo = new HiloSettings { MaxLo = 1000, Increment = 1 };
        For<Order>().IdStrategy(new HiloIdGeneration(typeof(Order), hilo));
        For<Order>().HiloSettings(hilo);
    }
}
````

**Comment by phillip-haydon** [comment]
MaxLo is max number of IDs that will be generated by the document store without round-tripping to the database.

Given: 

 * Lo = 1000 (specified in code)
 * Hi = 0 (value stored in the database)

Then:

 * 0 * 1000 = 0
 * 0 / 0 * 1000 + 1000 = 1000

This will generate Ids from 1 to 1000 before asking the database for the next Hi. 

-----

This avoids an application with multiple instances of a store stealing each other's Ids by pre-defining a range up front. 


If you have 2 web servers both have a an instance of the store.

Server 1 queries the HiLo table:

 * Lo = 1000 (specified in code)
 * Hi = 0 (value stored in the database)

Updates the Hi from 0 to 1

Server 2: (locked until server one completes row to be available)

 * Lo = 1000 (specified in code)
 * Hi = 1 (value stored in the database)

Updates Hi from 1 to 2

Then:

 * 1 * 1000 = 1000
 * 1 / 1 * 1000 + 1000 = 2000

Server 2 will generate Ids from 1001 to 2000

Once Server 1 has finished generating all it's Ids, it will go back to the server, see the current Hi is 2 and take that value, and update it to 3. Generating Id's from 2001-3000.




Is there any reason why you want to seed at 1000?

**Comment by superlogical** [comment]
Oh haha, looks like I totally misunderstood how HiLo works! 

Thanks for explaining it, will do some more reading.
