### ISSUE TITLE
System.InvalidOperationException when used with Odata v4 $select

### ISSUE THREAD

**Issue by mariotoffia** [JasperFx/marten#368]
Hi, 
I have no clue why it throws this exception. I have a super simple demo that fires up a docker container containing postgres and run marten as IQueryable<...> as OData Result.

It works perfectly for filtering etc. but when I try to project i.e. $select it fails with (below exception). Do you know off hand why it is doing that?

The selection was: http://localhost:53233/odata/PlayerInContests?$select=FirstName
Code: https://github.com/mariotoffia/api-workshop

Cheers,
 Mario

{
  "error":{
    "code":"","message":"An error has occurred.","innererror":{
      "message":"Exception has been thrown by the target of an invocation.","type":"System.Reflection.TargetInvocationException","stacktrace":"   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)\r\n   at System.Web.OData.Query.ODataQueryOptions.LimitResults(IQueryable queryable, Int32 limit, Boolean& resultsLimited)\r\n   at System.Web.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at System.Web.OData.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)\r\n   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)\r\n   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","internalexception":{
        "message":"Sequence contains no elements","type":"System.InvalidOperationException","stacktrace":"   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)\r\n   at Marten.Schema.Field..ctor(MemberInfo[] members)\r\n   at Marten.Schema.JsonLocatorField..ctor(MemberInfo[] members)\r\n   at Marten.Schema.DocumentMapping.<>c__DisplayClass86_0.<FieldFor>b__1(String _)\r\n   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\r\n   at Marten.Schema.DocumentMapping.FieldFor(IEnumerable`1 members)\r\n   at Marten.Linq.SetterBinding.ToJsonBuildObjectPair(IDocumentMapping mapping)\r\n   at Marten.Linq.TargetObject.<>c__DisplayClass7_0.<ToSelectField>b__0(SetterBinding x)\r\n   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at Baseline.GenericEnumerableExtensions.Join(IEnumerable`1 values, String separator)\r\n   at Marten.Linq.TargetObject.ToSelectField(IDocumentMapping mapping)\r\n   at Marten.Linq.SelectTransformer`1..ctor(IDocumentMapping mapping, TargetObject target)\r\n   at Marten.Linq.TargetObject.ToSelector[T](IDocumentMapping mapping)\r\n   at Marten.Linq.SelectorParser.ToSelector[T](IDocumentMapping mapping)\r\n   at Marten.Linq.QueryModelExtensions.BuildSelector[T](IDocumentSchema schema, IDocumentMapping mapping, QueryModel query)\r\n   at Marten.Linq.QueryHandlers.LinqQueryHandler`1.BuildSelector(IDocumentSchema schema, QueryModel query, IIncludeJoin[] joins, QueryStatistics stats)\r\n   at Marten.Linq.QueryHandlers.LinqQueryHandler`1..ctor(IDocumentSchema schema, QueryModel query, IIncludeJoin[] joins, QueryStatistics stats)\r\n   at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)\r\n   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)\r\n   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)\r\n   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)\r\n   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)\r\n   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)\r\n   at Remotion.Linq.QueryableBase`1.GetEnumerator()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Web.OData.Query.TruncatedCollection`1..ctor(IQueryable`1 source, Int32 pageSize)\r\n   at System.Web.OData.Query.ODataQueryOptions.LimitResults[T](IQueryable`1 queryable, Int32 limit, Boolean& resultsLimited)"
      }
    }
  }
}

**Comment by jeremydmiller** [comment]
@mariotoffia Do you know what's going on in the Select() clause? I think it's just hitting something we didn't anticipate. Is it selecting a constant value in the Select() somehow?

**Comment by mariotoffia** [comment]
@jeremydmiller I'd guess so. It is based on projection i.e. a sql select where you can obtain one or more properties from an object (or as with entity framework a column) value. I'd guess this is off-topic for marten (but it is a shame, it is a perfect match for odata v4 otherwise :))

Cheers,
 Mario

**Comment by jeremydmiller** [comment]
@mariotoffia It's probably something we could fix, but I need to know what oData is trying to do in the Select() transform.

**Comment by CoreyKaylor** [comment]
Haven't heard any updates on this. Going to close for now unless more details are forthcoming.
