### ISSUE TITLE
DeleteWhere with hierarchical storage

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#378]
Looking at the code for this while researching something else, I think that the DeleteWhere() against a type that is a subclass needs to apply the default filter of the document mapping.

Going to say this is probably a subtle bug that nobody has hit or noticed yet.

**Comment by nieve** [comment]
Will have a look into it later on today.

**Comment by nieve** [comment]
I presume you don't mean the following test, since it already exists and passes:
``` csharp
        [Fact]
        public void can_delete_by_subclass()
        {
            loadData();

            theSession.DeleteWhere<SuperUser>(x => x.FirstName.StartsWith("D"));
            theSession.SaveChanges();

            theSession.Query<SuperUser>().Count().ShouldBe(1);
            theSession.Query<AdminUser>().Count().ShouldBe(2);
            theSession.Query<User>().Count().ShouldBe(5);
        }
```

This one though fails, but it doesn't corresponds to what you've written:
``` csharp
        [Fact]
        public void can_delete_all_subclass()
        {
            loadData();

            theSession.DeleteWhere<SuperUser>(x => true);
            theSession.SaveChanges();

            theSession.Query<SuperUser>().Count().ShouldBe(0);
            theSession.Query<AdminUser>().Count().ShouldBe(2);
            theSession.Query<User>().Count().ShouldBe(4);
        }
```

**Comment by jeremydmiller** [comment]
@nieve Okay, I raised this issue because I thought that I hadn't tested that and found some things in the internals that made me think it might not work. If those existing tests pass, I'm closing this one.

**Comment by nieve** [comment]
The second test fails, but with a "Marten does not (yet) support this Linq query type".
