### ISSUE TITLE
Consider publishing symbols to aid debugging

### ISSUE THREAD

**Issue by baronfel** [JasperFx/marten#379]
When you package with paket pack, you can add the ['symbols' parameter](https://fsprojects.github.io/Paket/paket-pack.html#Symbol-Packages) to enable step-into debugging for users of Marten.  When this is added, paket pack will make a Marten.XXXX.nupkg and a Marten.XXXX.Symbols.nupkg, which should both be published to nuget/myget/etc.  Then, users with a symbol feed configured can easily step into your code when debugging.

**Comment by jeremydmiller** [comment]
Hey, we're looking at doing this in the near future. Thanks for the tip.

**Comment by CoreyKaylor** [comment]
@jeremydmiller I know the symbols package is included with the artifacts now. Have you been publishing them with the latest nugets so we can close this?

**Comment by jeremydmiller** [comment]
@CoreyKaylor Nuget can't seem to differentiate between the two packages:

```
A package with id 'Marten' and version '1.0.0-alpha-639' already exists and cannot be modified.
```

Should I be just loading the symbols nupkg file?

**Comment by scottoffen** [comment]
http://docs.nuget.org/create/creating-and-publishing-a-symbol-package

**Comment by CoreyKaylor** [comment]
@jeremydmiller When you have the symbols package in the same folder as the primary package it will also push the symbol package when `nugget push ...` Is used

**Comment by jeremydmiller** [comment]
Finally done today.
