### ISSUE TITLE
Introduce a global sequence number in the event store

### ISSUE THREAD

**Issue by jvdvleuten** [JasperFx/marten#381]
We currently only support a version number per aggregate, but for catch-up subscriptions, it might be easier to have a (non-duplicate) global sequence number. 

I do not want to use a a timestamp as that can be a duplicate.

We could use the `bigserial` type (64-bit) or `serial` (32-bit), but this can cause a 'hole' in the sequence numbers, being described here:

> Note: Because smallserial, serial and bigserial are implemented using sequences, there may be "holes" or gaps in the sequence of values which appears in the column, even if no rows are ever deleted. A value allocated from the sequence is still "used up" even if a row containing that value is never successfully inserted into the table column. This may happen, for example, if the inserting transaction rolls back. See nextval() in Section 9.16 for details. 

What are some other thoughts about this?

Some background information:

http://www.postgresql.org/docs/current/static/datatype-numeric.html#DATATYPE-SERIAL
http://www.neilconway.org/docs/sequences/

**Comment by jeremydmiller** [comment]
@jvdvleuten So I don't think we really care about gaps as long as the ordering is maintained. **If** the sequential Guid strategy for event Id's really pans out, I'm not sure you're really going to need the sequence field.
