### ISSUE TITLE
Remove all traces of the rolling buffer table

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#385]
2nd Quadrant is recommending that we just rely on sequential guid's and reading the event table directly in the async daemon. @CoreyKaylor, @bobpace, & I did quite a bit of whiteboard work on the async daemon yesterday, and the design concept we were coming up with wouldn't have worked well with the rolling buffer queueing anyway.

**Comment by tim-cools** [comment]
One concern is that if you appends event from different app servers you should could end up with event in the wrong order due to small timing differences of the app servers. It might be better to generate the sequental guid in the db server in this case.

**Comment by jeremydmiller** [comment]
Yeah, we talked about that one. For just the moment, we're taking the attitude that you just need to sync up your application servers. If necessary though, we could use this on the server just like you're suggesting: https://www.postgresql.org/docs/9.5/static/uuid-ossp.html.
