### ISSUE TITLE
Remove support for Postgresql 9.4

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#398]
Everybody has spoken, and we can drop support for Postgresql 9.4. Makes our internals simpler, fewer things to test.

**Comment by jeffdoolittle** [comment]
so if you need someone to look at this, I can take it on since the 9.4 support is my fault anyway. :)

**Comment by jeremydmiller** [comment]
@jeffdoolittle Thanks for the offer, but it's just going to take a few minutes. I've got it this morning.
