### ISSUE TITLE
Async Projection Daemon

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#402]
More content coming soon....

**Comment by Serguzest** [comment]
Did you forget to add "Event Store" tag or are we going to have this for regular documents? :)

**Comment by jeremydmiller** [comment]
There, added. Other folks have asked about using this with regular documents, but I don't particularly have any ideas on that score. Got any suggestions or requests?

**Comment by jeremydmiller** [comment]
Just needs docs.

**Comment by jeremydmiller** [comment]
This has been done for awhile, just missing docs. I'm going to go ahead and close it.
