### ISSUE TITLE
Inline projection of many events

### ISSUE THREAD

**Issue by tim-cools** [JasperFx/marten#404]
For my demo last week I created an IProjection that allow to project multiple event types. This can be used to create synchronous view models.

You can use it like this:

https://github.com/tim-cools/soloco-talks/blob/master/20160516-PolyglotPersistence/Soloco.Talks.PolyglotPersistence/F_InlineTransformationWithDomainEvents/Projection.cs#L12

And the base projector looks like this:

https://github.com/tim-cools/soloco-talks/blob/master/20160516-PolyglotPersistence/Soloco.Talks.PolyglotPersistence/Infrastructure/BaseProjection.cs#L13

Do you want me to create a PR to include this in library? Or do you  plan to support it differently?

**Comment by jeremydmiller** [comment]
@tim-cools I'm all for it, or at least get it in with some test coverage and then just see what shakes out in the async projection support.

The async daemon is going to force some additions to the IProjection interface for dependencies between projections and your approach should make that pretty easy.

**Comment by tim-cools** [comment]
@jeremydmiller cool! I've been outside the country for some time, but I will look into this by the end of the week...
