### ISSUE TITLE
Index not working on a DateTime column

### ISSUE THREAD

**Issue by bVanHertum** [JasperFx/marten#416]
Creating an index does not work on a DateTime column. The following unit test throws an exception:

>         [Fact]
        public void date_test()
        {
            StoreOptions(_ => _.Schema.For<Target>().Index(x => x.Date));            
            var data = Target.GenerateRandomData(100).ToArray();
            theStore.BulkInsert(data.ToArray());           
        }

In the output, you will find the following SQL and NpgSqlException:

> CREATE INDEX mt_doc_target_idx_date ON public.mt_doc_target ((CAST(data ->> 'Date' as timestamp without time zone)));
---- Npgsql.NpgsqlException : 42P17: functions in index expression must be marked IMMUTABLE

**Comment by jeremydmiller** [comment]
Guys, for 1.0, we're going to beat this w/ a defensive check telling you you're going to have to use a duplicated field for DateTime's. We can revisit this after 1.0.

**Comment by bVanHertum** [comment]
@jeremydmiller Given the nature of the fix, it might be prudent to mention I had the same exception when attempting to use a DateTimeOffset instead of a DateTime.

**Comment by siberianguy** [comment]
Is there any update on calculated indexes for DateTime fields?

**Comment by jeremydmiller** [comment]
Sorry, no. I had honestly forgotten about this. We could do it with the immutable timestamp function that we already use for querying.

**Comment by siberianguy** [comment]
It's funny cause I've seen that function in queries and was curious why it was not used for indexing :)

Could you please reopen this issue?
