### ISSUE TITLE
Revisit Event Type Registration

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#419]
Today, Marten needs to know about event types before you can query against existing Event store data. Tripped up a user and likely will more. Do we possibly add a dot net type column to the event data? Do more deriving of event types from either the db, or aggregates, or projections?

It's a usability issue that probably needs to be sorted out before 1.0

**Comment by zagyar** [comment]
I think this is not critical as it can be done via configuration/manual type registration.
But it may be not clear and lead to unexpected behaviour if not documented properly (currently it's documented as test case).
May be before adding the column (or related table) it would be good to decide on supported ways to persist configuration between assemblies, if there will be options other then wiring.

**Comment by jeremydmiller** [comment]
I'm wrapping this one up today with just a little bit more validation and a rename on the API to try to disambiguate the usage. Some of the work probably happens later in the async daemon story.
