### ISSUE TITLE
Optionally use Sequence for numeric Id property (and/or high/low implementation)

### ISSUE THREAD

**Issue by mdissel** [JasperFx/Marten#43]
Implement an attribute to identify a Id property as [Identity] with one or more implementations:
- fetch next number from sequence when DocumentSession.Save(..) is called and assign to Id property
- use high-low algorithm at domain level to assign next number from range or fetch next range from sequence. Set Id property when DocumentSession.Save(..) is called

**Comment by jeremydmiller** [comment]
We definitely need this. I've changed the `IDocumentSchema` classes to a runtime codegen strategy with an eye toward making this a little easier. Rob Conery linked to this one in a different comment:

http://rob.conery.io/2014/05/29/a-better-id-generator-for-postgresql/

**Comment by mdissel** [comment]
The advantage of a client based ID is that you don't need to save documents/records to the database before they can be used as a reference in other records/documents.

**Comment by kamranayub** [comment]
@mdissel Pretty much a must-have for doing batch insert/processing. Client ID gen is definitely :+1:

**Comment by jeremydmiller** [comment]
I'm splitting Sequences out to its own issue in just a second.
