### ISSUE TITLE
mt_doc_type column added on initial table creation, but not on patch

### ISSUE THREAD

**Issue by scottoffen** [JasperFx/marten#431]
Setting up a brand new document in a document store like this:

```csharp
var store = DocumentStore.For(_ =>
{
    _.AutoCreateSchemaObjects = AutoCreate.All;
    _.Connection(connection);
    _.DatabaseSchemaName = "testbed";
    _.Schema.For<User>();
});
```

Creates a `CREATE TABLE` statement when using `WriteDDL()` that looks like this:

```sql
CREATE TABLE testbed.mt_doc_user (
    id                  uuid CONSTRAINT pk_mt_doc_user PRIMARY KEY,
    data                jsonb NOT NULL,
    mt_last_modified    timestamp with time zone DEFAULT transaction_timestamp(),
    mt_version          uuid NOT NULL default(md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar 
);
```

Setting up a brand new document in a document store **with a subclass** like this:

```csharp
var store = DocumentStore.For(_ =>
{
    _.AutoCreateSchemaObjects = AutoCreate.All;
    _.Connection(connection);
    _.DatabaseSchemaName = "testbed";
    _.Schema.For<User>();
    _.MappingFor(typeof(User)).AddSubClass(typeof(SuperUser));
});
```

Creates a `CREATE TABLE` statement when using `WriteDDL()` that looks like this:

```sql
CREATE TABLE testbed.mt_doc_user (
    id                  uuid CONSTRAINT pk_mt_doc_user PRIMARY KEY,
    data                jsonb NOT NULL,
    mt_last_modified    timestamp with time zone DEFAULT transaction_timestamp(),
    mt_version          uuid NOT NULL default(md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar ,
    mt_doc_type         varchar 
);
```

Given that the last column - `mt_doc_type` - that allows for subclasses is only generated when you *start* with subclasses, if I were to have no subclasses initially, and add subclasses later, the column would need to be added to the table. However, when doing exactly that, **`WritePatch()` does not create an alter table statement**. Moreover, it would also need to provide a default value of the name of the base class.

**Comment by jeremydmiller** [comment]
@scottoffen I'll turn this around tomorrow morning. It'll be quick.

**Comment by scottoffen** [comment]
:+1: Or, just add the column every time, subclasses or no...just a thought.
