### ISSUE TITLE
Queries with DateTime comparison ignore timezone offset

### ISSUE THREAD

**Issue by mholland** [JasperFx/marten#432]
Example gist: https://gist.github.com/mholland/7f9037ba39ad69d49f7840d2db6d05ff

If UTC `DateTime` values are stored in a document, when querying based upon the `DateTime` property with a UTC `DateTime`, the query ignores the offset. Sample query from Postgres logs: 

```
select d.data, d.id, d.mt_version from public.mt_doc_testclass as d where CAST(d.data ->> 'DateTimeField' as timestamp without time zone) >= $1
parameters: $1 = '2016-06-17 16:06:31.580404+01'
```

In this example `2016-06-17 16:06:31.580404` is used in a >= comparison instead of `2016-06-17 15:06:31.580404`. Changing the parameter to `dateTimeParameter.AddHours(-1)` yields the correct results (at least when in BST)

**Comment by jeremydmiller** [comment]
@mholland I'm looking at it now, thanks for the repro steps

**Comment by jeremydmiller** [comment]
I'm working on this one this morning. So far what I know is:

* Querying against the DateTime field fails, both searching within the JSON and as a duplicated field
* Querying against a DateTimeOffset field succeeds both within the JSON and the duplicated field **if you search via another `DateTimeOffset` value**. I'm not sure that querying by a DateTime against the DateTimeOffset works w/ the implicit cast.
