### ISSUE TITLE
HiLoSequence Increment is not used

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#438]
What is the purpose of the Increment option in https://github.com/JasperFx/marten/blob/15056c05f53a3e917ef4060403ebe1b528f11e71/src/Marten/Schema/Identity/Sequences/HiLoSequence.cs#L26
At the moment it's not used.

**Comment by jeremydmiller** [comment]
@mdissel I'd be lying if I told you I remember. It was theoretically for folks who wanted the id version to go up by more than 1. I'm inclined to just delete it.

**Comment by mdissel** [comment]
Agreed, just delete the increment property

**Comment by jeremydmiller** [comment]
I take pull requests.

**Comment by jeremydmiller** [comment]
Closed by #440
