### ISSUE TITLE
Store Hierarchy / subclassed documents in the same table

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#44]
By default store every class in it's own table, except when on one of the parent classes an attribute [DocumentRoot] is declared.
or always stored subclassed documents into the root class..

**Comment by phinett** [comment]
Is there an ETA for this to be implemented, this would be a showstopper for my project at the moment and probably many others.

I am working through a throw away test project converting my existing RavenDb based app and it would be great if I could test everything end to end.

**Comment by jeremydmiller** [comment]
@mdissel @phinett I started work on this this morning. Not sure what the configuration is going to look like just yet, but it's on the way.

**Comment by phinett** [comment]
Great looking forward to this.

Things look to be taking shape quite nicely, theirs a couple more must have features left on the table i think before 1.0 release but so far I am pretty optimistic.

**Comment by jeremydmiller** [comment]
There is a working implementation in master now. I'm claiming that the mechanics of this work as of commit https://github.com/JasperFx/marten/commit/c2dc4f09c2c45ad2bee3bc14a21e343eab85f420 and I'm closing for now. We can add new issues later for changes to the configuration model -- and it's a near certainty that those will happen.
