### ISSUE TITLE
Optionally allow users to specify the schema owner for DDL generation

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#441]
Request from work, will need to evaluate this and add to:

- [ ] CREATE TABLE
- [ ] CREATE SCHEMA (?)
- [ ] CREATE FUNCTION (?)
- [ ] The Sequence in the event store?

**Comment by bradyclifford** [comment]
Need the ability to specify the owner.  When setting up the store options, would be nice to specify the following:

```
AlterSettings<StoreOptions>(s =>
 {
                s.Connection("postgres-server");
                s.DatabaseSchemaName = "OneExchange";
                
               // Set owner for all objects. Sure there is a better name you can come up with.
                s.AllObjectsSchemaOwner = "DatabaseSchemaOwnerRole";

                // Or if we need to be more specific
                s.DatabaseOwner = "DatabaseSchemaOwnerRole";
                s.SchemaOwner = "SchemaOwnerRole";
                s.TableOwner = "TableSchemaOwnerRole";
                s.FunctionOwner = "FunctionSchemaOwnerRole";
});
```

When the AutoCreate, WriteDDL or WritePatch generates the necessary SQL scripts, add the owner when it is specified in the StoreOptions:

```
CREATE DATABASE databaseName OWNER "DatabaseSchemaOwnerRole";
CREATE SCHEMA schemaName AUTHORIZATION "SchemaOwnerRole";

ALTER TABLE tableName OWNER TO "TableSchemaOwnerRole";
ALTER FUNCTION functionName(param1, param2) OWNER TO "FunctionSchemaOwnerRole";
```

**Comment by jeremydmiller** [comment]
Ugh, the tables & schemas will be easy, but the functions are going to be a PITA. I'm on it.

**Comment by jeremydmiller** [comment]
@bradyclifford Is it really necessary to set separate owners for databases, schema, tables, and functions? Or can we just do the "all objects owner"?

**Comment by bradyclifford** [comment]
That's fine Jeremy
