### ISSUE TITLE
Events table is created even tho I don't use events

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#443]
This changed in v0.9.###

Not sure which, but now when setting up a new app it creates the event table even tho there are no events. 

Expected behavior is mt_events is created when events are used.

**Comment by jeremydmiller** [comment]
@phillip-haydon How are you generating tables that you get this? I tried a couple different things and I can't reproduce the issue in master. I'm just about to close this, but there's a commit coming now that has repro tests that all pass.
