### ISSUE TITLE
DocumentStore throw misleading exception when Database doesn't exist

### ISSUE THREAD

**Issue by bradyclifford** [JasperFx/marten#446]
When a database doesn't exist and you spin up a DocumentStore, we get back a **System.Exception**. _Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host._  It is probably coming directly from Npgsql.

It takes a few double takes to realize that the database doesn't exist or there aren't permissions to access the Database, Schema or Table in question. Would it be possible to proved a more meaningful exception in these cases?

We are concerned that when our dev's try getting our project built and running on their local box that they will struggle too long with these exception when all they are missing is their local PostgreSQL database.

**Comment by jenspettersson** [comment]
Hm, trying to reproduce but I get the following exception when trying to access an existing server, but to a database that doesn't exist:

`"3D000: database \"NONEXISTING\" does not exist"`

This is when running a test on the latest source code and @CoreyKaylor updated Npgsql very recently (60d2292793cb93d6). Might have changed there?

**Comment by CoreyKaylor** [comment]
Yeah regardless, that sounds like a great improvement for Npgsql ;) if it's not already handled in the latest nuget.

**Comment by bradyclifford** [comment]
@jenspettersson thats a better message then I am getting.  Might be related to how I am spinning up the DocumentStore with StructureMap.  I will dig into a little more and see if I can provide a better argument.  As it stands now, @CoreyKaylor is right...

**Comment by CoreyKaylor** [comment]
@bradyclifford considering you're not using the latest of everything I believe, I would start there.
