### ISSUE TITLE
Document projections on an array field (SelectMany)

### ISSUE THREAD

**Issue by superlogical** [JasperFx/marten#448]
I have a product type that has an array of tags. I'd like to run a query that get's the distinct set of tags in the database.

````csharp
public class Product 
{
  public string Title  { get; set; }
  public string[] Tags { get; set; }
  ...
}

var tags = session.Query<Product>().SelectMany(x => x.Tags).Distinct().OrderBy(x => x).ToList();
````
The `TypeMappings` class has a `GetPgType` function that takes a type, in my case `typeof(string[])` which is not in the `PgTypes` dictionary.

Not sure if this is a hard/easy one for someone like me to pickup :)

**Comment by superlogical** [comment]
I found out how to do it using a postgres json query if anyone is interested.

````sql
select distinct jsonb_array_elements(data -> 'Tags') as x
from mt_doc_product
order by x;
````

**Comment by jeremydmiller** [comment]
@superlogical Wouldn't we eventually need to support Where()'s chained after the SelectMany()? Any thoughts on how to pull that one off?

**Comment by jeremydmiller** [comment]
Okay, time to task this bad boy up.

- [ ] Handle arrays of simple types
- [ ] Handle lists of simple types
- [ ] Handle arrays of complex types
- [ ] Handle lists of complex types
- [ ] Chain a Where() clause behind SelectMany()

**Comment by jeremydmiller** [comment]
Note, I'm cutting separate issues for combining SelectMany() with Where(), OrderBy(), Select(), and Take/Skip(). 

See #572, #573, #574, #575, and #576
