### ISSUE TITLE
Configurable Exception Handling in Async Daemon

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#452]
Which exceptions would cause the daemon to shut down?
When would you immediately retry?
When would you pause, then retry?

In the Fetcher, and in ProjectionTrack

**Comment by khalidabuhakmeh** [comment]
Why not just make all exceptions handling strategies configurable. By default all strategy is to shutdown the daemon.

```csharp
Store.AsyncDaemon(cfg => {
     cfg.OnException<TimeOutException>(RetryStrategy.Immediately);
     cfg.OnException<ApplicationException(RetryStrategy.PauseThenRetry, retryInSeconds: 3);
});
```

Additionally, you may want individuals to give a retry strategy of their own.

```csharp
Store.AsyncDaemon(cfg => {
     cfg.OnException<TimeOutException, TheCloudSucksStrategy>( new TheCloudSucksStrategy());
});
```

Some thoughts.

**Comment by jeremydmiller** [comment]
That's pretty well what I'm doing right now;)

**Comment by khalidabuhakmeh** [comment]
Mind meld!

![](http://media3.giphy.com/media/xT5LMxw4Z2lmqhnXkA/giphy.gif)
