### ISSUE TITLE
Marten Logo Candidate #2

### ISSUE THREAD

**Issue by khalidabuhakmeh** [JasperFx/marten#456]
The raven feather is tongue and cheek, and I started with not having it in the image. This candidate also has the ability to be turned into a circular sticker for those inclined to have it on their laptop.

---
[Download marten.pdf](https://github.com/JasperFx/marten/files/366887/marten.pdf)
---
![marten_feather](https://cloud.githubusercontent.com/assets/228256/16889316/74e18872-4ab3-11e6-8fa4-5a67a02a8a1a.png)

![marten_logos](https://cloud.githubusercontent.com/assets/228256/16889319/794237d6-4ab3-11e6-876d-48aeeefa4d19.png)

![marten_ms](https://cloud.githubusercontent.com/assets/228256/16889320/7b5ba08e-4ab3-11e6-87e4-d69a0b823dfd.png)

**Comment by jeremydmiller** [comment]
I think we're going with this one: https://github.com/JasperFx/marten/issues/498
