### ISSUE TITLE
Provide a way to see query duration through session logger and QueryStatistics

### ISSUE THREAD

**Issue by kamranayub** [JasperFx/marten#457]
It seems reasonable to assume in dev/test/production folks will want to profile their setup to find any performance bottlenecks and to do so they might use a tool like Glimpse or logging to the debug console.

I looked around Marten's codebase and npgsql's but did not see anything suitable as an extension point to add this kind of logging for query execution duration. npgsql has a [logging provider](http://www.npgsql.org/doc/logging.html) implementation but only command text is passed through.

The `IMartenSessionLogger` is very close to what I'd need to add Glimpse support but duration of the command execution is not exposed. I was thinking it was something that `ManagedConnection` might be able to take care of and pass along, as well as exposing it off of `QueryStatistics` for one-offs.

For example, `IMartenSessionLogger` could change to pass a wrapper object that contains the command + any relevant statistics.

Statistics I'd be interested in:
- Query Duration (Time to execute raw query)
- Total Duration (Total time including Marten + Serialization overhead)

**Comment by jeremydmiller** [comment]
I completely buy the idea of using Glimpse to understand Marten behavior and we're already doing that kind of thing with FubuMVC diagnostics in our shop. But for performance, I think I'd rather opt for something like New Relic or some other kind of performance monitoring tooling instead of trying to build something into Marten itself.

**Comment by kamranayub** [comment]
Makes sense, I was only thinking of query logging in scope for this to
allow plugin integration. I'm on Azure so I need all the help I can get.

**Comment by rdcm** [comment]
@jeremydmiller Does the way exist at this moment(marten 2.8.0) write custom interceptor to measure query duration? 

Something like this or via `app metrics`:

```
	var sw = Stopwatch.StartNew();

	//query execution

	sw.Stop();
```

**Comment by jeremydmiller** [comment]
This can be done now with the latest logging changes for v4
