### ISSUE TITLE
Improve query generation when querying against Dictionary

### ISSUE THREAD

**Issue by baronfel** [JasperFx/marten#459]
When a Linq query is comparing against `Dictionary<K,V>.Contains(KeyValuePair<K,V>)` or `dictionary[key] == value`, we should be able to optimize the comparison by generating the dictionary for the comparison and then converting that the json.

Example:

`Session.Query<Doc>().Where(d => d.Guys.Contains(new KeyValuePair<string,string>("foo", "bar")))`  
should result in a comparison json of `{ "Guys" : { "foo" : "bar" } }`. 
Right now we give `{"Guys": [{"Key":"foo", "Value":"bar"}]}` instead

Per Jeremy's pointer this can probably be done using http://jasperfx.github.io/marten/documentation/documents/advanced/customizing_linq/

**Comment by baronfel** [comment]
So I'm working on this and I think there's a small problem in the WhereFragment code with regards to the operator I want to use. Specifically, I want to use the `?` operator to check if a top-level text element exists in a jsonb object, but the escaping in the WhereFragment is obliterating my first `?` symbol.  

Specifically I want to write the sql query `{fieldLocator} ? ?`, where fieldLocator is the found field and the second `?` is my key parsed from the expression.  

I think we should change the token used to signal a variable in the query DSL, especially given that more of the json operators contain special symbols like `|`, `?`, `@` and `&`.

**Comment by CoreyKaylor** [comment]
Going to close this now. Feel free to open a new issue if you think the other issues you ran into that were "hairy" need to be discussed further.
