### ISSUE TITLE
Marten logo candidate #3

### ISSUE THREAD

**Issue by hougasian** [JasperFx/marten#462]
<img width="495" alt="screen shot 2016-07-19 at 9 14 25 am" src="https://cloud.githubusercontent.com/assets/6231956/16951044/42c750de-4d91-11e6-87cf-ddde579e7c69.png">
Clean, iconic, easy for stickers/shirts.
[marten2.pdf](https://github.com/JasperFx/marten/files/371495/marten2.pdf)

**Comment by jeremydmiller** [comment]
@hougasian I'm trying to get folks to vote on this and the other options in the Gitter room. I like both of them - but I'm useless at this kind of thing so I'm deferring to everyone else.

**Comment by kiliman** [comment]
I don't get the odd nose treatment or the check "highlights". I do like the font though.

**Comment by hougasian** [comment]
eyebrows, eyes, and someone suggested it be more threatening... thus the nose. Open to alteration.

**Comment by drusellers** [comment]
> EDIT: Actually, perhaps those are eyes, and there are some really big eyebrows... anyway, it's strange.

Yeah, it took me a bit to see the eyes vs eyebrows.

**Comment by jeremydmiller** [comment]
I think the semi-consensus is to go with this one: https://github.com/JasperFx/marten/issues/498.

Thank you again for doing this.
