### ISSUE TITLE
Problem using AggregateStream

### ISSUE THREAD

**Issue by Tazer** [JasperFx/marten#465]
I wrote about a problem I had in the gitter chat. 

The problem is that I can't get AggregateStream to run my Apply methods. 
And AggregateStreamAsync gives just back a empty result. AggregateStream at least sets the Id of the Projection/Stream.

Here is my code:
https://gist.github.com/Tazer/5c69e5170f57a109ec171a97ce56e237

And I'm running 1.0.0-alpha-625 on asp.net core

**Comment by nmt1994** [comment]
Did you try to iterate your listofEvents , then Append each event into the event stream ?

**Comment by Tazer** [comment]
@nmt1994 nope haven't tried that , I will give it a shot! Was just assuming that I could do like I did :)

**Comment by jeremydmiller** [comment]
@Tazer Hey, I'm sorry I haven't gotten to this yet. I think maybe I could finally get to it today or tomorrow.

**Comment by Tazer** [comment]
@nmt1994  that worked! :) 

@jeremydmiller  no worries, @nmt1994  suggestion worked. But there is still a problem when using `AggregateStreamAsync` that the Id property isn't filled, it gets filled in `AggregateStream`

so I'm doing like this now:

```
            foreach (var @event in listOfEvents)
                    {
                        session.Events.Append(existing.SerieLibraryId, @event);
                    }
```

Cause seems if I'm passing `List<object>` directly marten things that it's just ONE event and it's type is `List<object>`

**Comment by jeremydmiller** [comment]
@Tazer Meh, it's a usability issue. It's because the signature is `params object[] events`. That's burned us before in other areas. 

What we *could* do is recognize `List<object>` and explode that out behind the scenes. 

I'll fix the Id, that won't be hard.
