### ISSUE TITLE
Define a different Function Owner

### ISSUE THREAD

**Issue by bradyclifford** [JasperFx/marten#471]
We need the ability to specify a unique owner for all Marten upsert functions.  Currently, there is only an overarching OwnerName property that we can set in the StoreOptions.  We need the following:

```
var StoreOptions = new StoreOptions()
{
    OwnerName = "SchemaOwner",
    FunctionOwnerName = "FunctionOwner",
    DatabaseSchemaName = "app1"
};
```

_Stay tuned for additional details on the reasons why we need this feature._

**Comment by bradyclifford** [comment]
We were able to find a workaround...

**Comment by jeremydmiller** [comment]
@bradyclifford How did this change? You can set a different owner for each document type if you want to.

**Comment by bradyclifford** [comment]
Our database team decided they didn't need to specify a unique owner for all functions. Setting an owner for each document type would of helped, but they (our database team) had originally wanted to set a global owner for all functions. They decided instead to use the 'VOLATILE SECURITY DEFINER' option that is part of a function to execute specific privileges.
