### ISSUE TITLE
WritePatchByType

### ISSUE THREAD

**Issue by bradyclifford** [JasperFx/marten#473]
We need the ability to output DDL scripts by type, similiar to that of the `WriteDDLByType()` method.

Due to our database team's strict requirements, each DocumentType table will need to have its own DDL script that will include `GRANT` privileges all the way down to the column level.  Separating each DocumentType into its own DDL patch script will help in automating the creation of these delta scripts and managing those grants by our database team.

Included in this is the ability to persist these document types with a different file naming convention that will work with our database versioning framework; adding an iterative prefix to the filename is all we require.  So the ability to pass a function into the method that would be ran on each document type, overwriting the default file name, would suffice.  We are using a versioning framework called `Sqitch`.  the file naming convention we plan on using as an example is `2016-07-27T130102.TW-15485.{documentTypeName}.sql`.  We would want to prepend a ISO 8601 timestamp with our database team ticket number to the original file name; the document type name.

This is a low priority item.  We can name and split these scripts up by hand for now.

**Comment by jeremydmiller** [comment]
@bradyclifford That's already possible, though arguably complicated and ugly. Here's how you'd do that today, assuming that you had your own tooling around it.

For the short term, how about an extension method on `IDocumentSession` for `WritePatch(Type documentType)` that just encapsulates the mess below.

For the longer term (the week of the 15th), I'd like to go ahead and make a 2nd Marten package w/ a command line tool that includes some kind of mechanism to allow you to write Sqitch files w/ WritePatch().

```
var mapping = store.Schema.MappingFor(typeof(YourDocumentType));
var patch = new SchemaPatch();
mapping.SchemaObjects.WritePatch(store.Schema, patch);

var sql = patch.UpdateDDL;

```
