### ISSUE TITLE
Don't run DateTime's through the `mt_immutable_timestamp` function as part of a `Select()`

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#479]

**Comment by jeremydmiller** [comment]
@ericgreenmix Can you give me a failing test for this? I'm trying it tonight, and so far I can't make it fail when doing a select transform on DAteTime's.

**Comment by ericgreenmix** [comment]
I can get you a failing test tomorrow. The issue is that since `mt_immutable_timestamp` returns `timestamp with time zone`, all DateTime's are made local time when doing a `Select()`, even if they were persisted as UTC.

**Comment by jeremydmiller** [comment]
*That's* what I needed. On it.
