### ISSUE TITLE
IList<T>.Contains LINQ query does not work

### ISSUE THREAD

**Issue by JesperTreetop** [JasperFx/marten#484]
The following doesn't work:

```
public class TestModelObject {
    public Guid Id { get; set; }
    public string Title { get; set; }
    public IList<string> Tags { get; set;}
}

using (var session = _documentStore.LightweightSession()) {
    var tag = $"tag-{Guid.NewGuid().ToString()}";

    var obj = new TestModelObject {
        Title = $"Object created at {DateTime.Now}",
        Tags = new List<string> { "abc", "xyzzy", tag } 
    };

    session.Store(obj);
    session.SaveChanges();

    var objByTag = session
        .Query<TestModelObject>()
        .Where(tmo => tmo.Tags.Contains(tag))
        .FirstOrDefault();
}
```

`objByTag` is `null`. As long as `Tags`' type is either `List<string>` or `string[]`, it works, but not when `Tags` is `IList<string>`. [According to your documentation, this should be supported](http://jasperfx.github.io/marten/documentation/documents/querying/linq/#sec14).

This is as of Marten 1.0.0-alpha-644 on .NET Core 1.0 on OS X 10.11.5.

(PS: Could you also add support for querying on `IReadOnlyList<T>` the same way as on `IList<T>`?)

**Comment by jeremydmiller** [comment]
@JesperTreetop I'll deal w/ IReadOnlyList<T> shortly, but for right now, I'm not able to reproduce your problems with `IList<string>`. This test passes for me:

```
        public class DocWithLists
        {
            public Guid Id;

            public IList<string> Names = new List<string>();

        }

        [Fact]
        public void can_do_contains_against_IList()
        {
            var doc1 = new DocWithLists {Names = new List<string> {"Jeremy", "Josh", "Corey"} };
            var doc2 = new DocWithLists {Names = new List<string> {"Jeremy", "Lindsey", "Max"} };
            var doc3 = new DocWithLists {Names = new List<string> {"Jack", "Lindsey", "Max"} };

            using (var session = theStore.OpenSession())
            {
                session.Store(doc1, doc2, doc3);
                session.SaveChanges();

                var ids = session.Query<DocWithLists>().Where(x => x.Names.Contains("Jeremy")).Select(x => x.Id).ToList();

                ids.Count.ShouldBe(2);
                ids.ShouldContain(doc1.Id);
                ids.ShouldContain(doc2.Id);
            }
        }
```

The existing tests on IList<T> are also passing.

**Comment by jeremydmiller** [comment]
@JesperTreetop `IReadOnlyList`'s aren't going to happen without some customizations to Newtonsoft. I'm sorry, but that's a no-go for now.

**Comment by JesperTreetop** [comment]
Very strange, I will re-check and if I still get the same result I'll clone the repository and see if the test passes for me. Mine was a property and not a field but that probably does not make any difference.

Since [`IReadOnlyList<T>` support has been in Json.NET since 5.0](http://james.newtonking.com/archive/2013/04/07/json-net-5-0-release-1-net-4-5-biginteger-read-only-collections), what's missing that would require the customizations? Just curious.
