### ISSUE TITLE
Bug with document heirarchy and include

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#490]
Gives a weird exception about converting a varchar to guid.

public class Bug_Query_by_abstract_type_in_hierarchy_with_include : DocumentSessionFixture<IdentityMap>
    {

        public Bug_Query_by_abstract_type_in_hierarchy_with_include()
        {
            StoreOptions(_ =>
            {
                _.Schema.For<Activity>()
                    .AddSubClass<StatusActivity>();
            });
        }

        public class Account
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

        public abstract class Activity
        {
            public Activity()
            {
                Id = Guid.NewGuid();
            }

            public Guid Id { get; set; }

            public int AccountId { get; set; }

            public abstract string Type { get; }
        }

        public class StatusActivity : Activity
        {
            public override string Type
            {
                get { return "StatusUpdate"; }
            }
            public string StatusText { get; set; }
        }

       
        [Fact]
        public void load_abstract_type_with_include()
        {
            var account = new Account()
            {
                Id = 1,
                Name = "Paul"
            };
            theSession.Store(account);

            var activity = new StatusActivity()
            {
                Id = Guid.NewGuid(),
                StatusText = "testing status",
                AccountId = 1
            };

            theSession.Store(activity);
            theSession.SaveChanges();

            using (var session = theStore.QuerySession())
            {
                List<Account> accounts = new List<Account>();
                session.Query<Activity>()
                    .Include(a => a.AccountId, accounts)
                    .ToList()
                    .ShouldNotBeTheSameAs(activity).ShouldNotBeNull();

                accounts.First().Id.ShouldBe(1);
            }
        }
    }
`

**Comment by jeremydmiller** [comment]
@phinett I'm finally looking at this now.
