### ISSUE TITLE
Add GRANTS to tables and functions

### ISSUE THREAD

**Issue by bradyclifford** [JasperFx/marten#494]
We need ability to add `GRANTS` to tables and functions. 

> Note: Postgres breaks up GRANTS after they are added to a table, I would suggest that they not be part of the `SchemaObject` comparison.

# Requirements
- Grant to multiple roles and users
- Grant at column level 
- Grant at table / function level (not sure if you can grant at a function level without defining the columns explicilty)
- Grant without having to specify each column
- Grant only to specific columns
  - Use an enum instead of string to specify columns
- Global grants for all document types
- Ability to overwrite or add grants at document specify level

Here is a usage example.  The ability to add "global" grants and then document specific overwrite grants would be a plus.

```
var store = DocumentStore.For(_ =>
    {
        _.Connection(ConnectionSource.ConnectionString);

        // Add global grants
        _.DdlRules.Grants = {
             new Grant {
                Type = GrantType.SELECT,
                Roles = { "ServiceAccountRole", "SchemaOwners" },
                GrantAtObjectLevel = false // Or maybe name this GrantAtColumnLevel = true
                // Columns aren't specified and grant level is not at table level, so it adds an explicit grant to all of them
                // GRANT SELECT (column1, column2, column3, ...) ON TABLE oe.mt_doc_all TO "ServiceAccountRole", "SchemaOwners";
             },
             
             new Grant {
                Type = GrantType.INSERT,
                Roles = { "SchemaOwners" }, // ServiceAccountRole uses the function to insert
                Columns = {
                    DocumentColumnType.Id,
                    DocumentColumnType.JsonData,
                    DocumentColumnType.LastModified
                }
                // Only grants to the 3 columns
                // GRANT INSERT (id, data, mt_last_modified) ON TABLE oe.mt_doc_all TO "SchemaOwners";
             },

             new Grant {
                Type = GrantType.UPDATE,
                Roles = { "SchemaOwners" }, // ServiceAccountRole uses the function to update
                Columns = {DocumentColumnType.JsonData } // only allows SchemaOwners to update the data column
                // Only grants update to the json data column
                // GRANT UPDATE (data) ON TABLE oe.mt_doc_all TO "SchemaOwners";
             },

            new Grant {
                Type = GrantType.EXECUTE,
                Roles = {"ServiceAccountRole"}
                // GRANT EXECUTE ON FUNCTION oe.mt_upsert_user(column1, column2, ..) TO "ServiceAccountRole"
             },
       
        };

        // Add or overwrite grants at table, function level
        _.Schema.For<User>().Grant(new Grant {
             Type = GrantType.DELETE,
             Roles = {"ServiceAccountRole", "User"},
             // Instead of defining the columns, the option to add grant delete to the table as a whole
             GrantAtObjectLevel = true
             // GRANT DELETE ON oe.mt_doc_user TO "ServiceAccountRole", "User";
        });

    });
```

# Example of Script

```
SET ROLE "SchemaOwners";

CREATE TABLE oe.mt_doc_example
(
  ...
);
ALTER TABLE oe.mt_doc_example OWNER TO "SchemaOwners";
GRANT SELECT (column1, column2, column3, ...) ON TABLE oe.mt_doc_example TO "ServiceAccountRole", "SchemaOwners"; --GRANT to muliple roles / users
GRANT INSERT (column1, column2, column3, ...) ON TABLE oe.mt_doc_example TO "SchemaOwners";  --GRANT on specific columns
GRANT UPDATE (column1, column2, column3, ...) ON TABLE oe.mt_doc_example TO "SchemaOwners";
GRANT DELETE ON oe.mt_doc_example TO "ServiceAccountRole"; --GRANT on all columns

--------------
CREATE OR REPLACE FUNCTION oe.mt_upsert_example
(
    ...
)
$$ LANGUAGE plpgsql SECURITY DEFINER VOLATILE COST 100;
ALTER FUNCTION oe.mt_upsert_example(...) OWNER TO "SchemaOwners";
GRANT EXECUTE ON FUNCTION oe.mt_upsert_example(...) TO "ServiceAccountRole"; --GRANT EXECUTE to one or more roles / users

RESET ROLE;
```

**Comment by bradyclifford** [comment]
Currently there is already a `DdlRules.GrantToRoles` collection.  I would suggest that be renamed to just Grants because there are future possibilities of granting to a `USER`, not just a `ROLE`.

**Comment by jeremydmiller** [comment]
@bradyclifford,

A few points and what I'm thinking this morning:

* I did the rename of `GrantToRoles` to just `Grants` like you suggested. Made sense.
* Except for deletions, I'm voting against having any differences in grants between document types. I really don't see that coming up and it's too much work.
* I've added the insert & update grants. I don't see it making any sense to do it column by column for Marten, so I'm leaving that out
* SystemFunctions have an EXECUTE grant (really just the mt_immutable_timestamp)
* Transform Functions have an EXECUTE grant for each thing on DdlRules

* I'm still missing the event store, but we don't need it ourselves, so...

* By default, it will add a DELETE grant to each document type unless it has the Deletions.CannotDelete configuration on an individual document mapping. I'll catch up on the docs for that this week.

**Comment by phixed** [comment]
@jeremydmiller, just putting in my two cents here. If we don't get all the way to fully automating grants by providing the ability to specify column-level permissions, then I think it somewhat defeats the purpose. Ideally, @bradyclifford and I think it would be best to either do 100% of generating the grants, because anything in between is going to require it to be modified by hand; even if a little. As far as I'm aware, I think the column-level grants is the only thing left to implement that would allow the developers to generate their DDL without having to touch it at all.

The only other thing I'd mention is that it may be a better default to set Deletions.CannotDelete to true, and opt in to it otherwise.

Just my thoughts... :)

**Comment by jeremydmiller** [comment]
@phixed I take pull requests.

**Comment by jeremydmiller** [comment]
And no, we're not going to set any of these grants up as defaults. It's pure friction to any other users than us. I'm not infecting Marten with Kevin's nonsensical OCD tendencies

**Comment by phixed** [comment]
@jeremydmiller, I'll let @bradyclifford decide if that's worth the dev effort, since that is something that will only affect them. Regarding my suggestion for reversing the default on DELETE, I wasn't at all suggesting that because of a recommendation from Kevin, or even in the context of OE's usage of Marten; I was merely suggesting that (IMHO) defaulting delete grants to true will probably require that it's changed more often than not, but I would again defer to @bradyclifford who made the same observation at the same time, but I don't feel strongly one way or the other.
