### ISSUE TITLE
Working with AggregateException sucks

### ISSUE THREAD

**Issue by dotnetchris** [JasperFx/marten#496]
AggregateException is one of the worst classes in the BCL. It is monumentally painful to deal with meaningfully. 

Please consider an alternative to using this regularly. 

At the minimum please consider making ConcurrencyException be a regular exception even if you just 
make it something like

```c#
public class ConcurrencyException  : Exception {
    public AggregateException Details { get;set; }
}
```

I pretty much never care about the details of a concurrency exception. Either i have an explicit retry policy around an item or i just want the request to die. But having to interrogate an aggregate exception `ex.InnerExceptions.OfType<ConcurrencyException>().Single();` is really silly.

**Comment by jeremydmiller** [comment]
@dotnetchris This one falls under the "I take pull requests" category.

**Comment by jeremydmiller** [comment]
Actually, now that I think about it, I kept it to AggregateException on purpose because there could be other ex's down the line than concurrency exception.
