### ISSUE TITLE
Marten Logo Candidate #4

### ISSUE THREAD

**Issue by khalidabuhakmeh** [JasperFx/marten#498]
Updated version of #456 

![marten_futura](https://cloud.githubusercontent.com/assets/228256/17930827/2c577a8e-69d6-11e6-84a9-00ff3f74c77e.png)

Fixed visual issues from rushing

**Comment by khalidabuhakmeh** [comment]
![marten_futura_orange](https://cloud.githubusercontent.com/assets/228256/17936241/26388b46-69ec-11e6-9bcb-9ca8d2b6e541.png)

**Comment by khalidabuhakmeh** [comment]
![marten_blue_futura](https://cloud.githubusercontent.com/assets/228256/17936389/a4d4963e-69ec-11e6-875a-16ff7119d985.png)

**Comment by khalidabuhakmeh** [comment]
![marten_futura_black](https://cloud.githubusercontent.com/assets/228256/17936446/d7ba8388-69ec-11e6-8583-5c554e0c5cc1.png)

**Comment by khalidabuhakmeh** [comment]
![marten_black](https://cloud.githubusercontent.com/assets/228256/17937659/db340418-69f0-11e6-9421-8f091e3fc21b.png)

**Comment by jeremydmiller** [comment]
Sounds like the consensus is to use the chocolate themed version of this one.

**Comment by khalidabuhakmeh** [comment]
![marten_sticker](https://cloud.githubusercontent.com/assets/228256/18131617/869aa7b0-6f61-11e6-86ad-aa61a36da77e.png)
![marten_text](https://cloud.githubusercontent.com/assets/228256/18131618/86a56d30-6f61-11e6-9d45-f313fe7d7bcf.png)
