### ISSUE TITLE
DB schema initialization fails with "DDL Execution for 'public.mt_transform_patch_doc Diff' Failed!"

### ISSUE THREAD

**Issue by haamaanaa** [JasperFx/marten#502]
Hi!

Am trying to initialize empty schema using marten DocumentStore object

`
var store = DocumentStore.For( _ => {

                    _.AutoCreateSchemaObjects = AutoCreate.All;

                    _.Connection(conn);

                    _.DatabaseSchemaName = Marten.StoreOptions.DefaultDatabaseSchemaName;

                    _.Schema.For<InventoryItem>();

                });

store.Schema.ApplyAllConfiguredChangesToDatabase();
`

And DB schema initialization fails with "DDL Execution for 'public.mt_transform_patch_doc Diff' Failed!"

Domain (InventoryItem) and mt_hilo tables are initialized correctly and also some functions. 

What would be the incorrect thing I am trying to do here?

Dev-env: 
marten 0.9.12.563
postgres 9.5.4 DB
VS 2015 update 3
Win10

Full stacktrace:
****************
Executing DDL change:
DO $$
BEGIN
    IF NOT EXISTS(
        SELECT schema_name
          FROM information_schema.schemata
          WHERE schema_name = 'public'
      )
    THEN
      EXECUTE 'CREATE SCHEMA public';
    END IF;

END
$$;

'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/2/ROOT-5-131171165371455411): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/2/ROOT-5-131171165371455411): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Threading\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'Marten.Schema.MartenSchemaException' in Marten.dll
exception m: DDL Execution for 'public.mt_transform_patch_doc Diff' Failed!

CREATE OR REPLACE FUNCTION public.mt_transform_patch_doc(doc JSONB, patch JSONB) RETURNS JSONB AS $$

  var module = {export: {}};

  function findDeep(doc, parts){
    var element = doc;
    
    for (var i = 0; i < parts.length; i++){
        var child = parts[i];
        if (!element.hasOwnProperty(child)){
            element[child] = {};
        }
        
        element = element[child];
    }
    
    return element;
}

function locate(doc, patch){
    var parts = patch.path.split('.');
    
    var element, prop;
    
    if (parts.length > 0){
        prop = parts.pop();
        element = findDeep(doc, parts);
    }
    else {
        prop = patch.path;
        element = doc;
    }
    
    return {element: element, prop: prop};
}

function setValue(doc, patch, location){
    location.element[location.prop] = patch.value;
    
    return doc;
}

function incrementValue(doc, patch, location){
    var interval = 1;
    if (patch.increment){
        interval = parseInt(patch.increment);
    }
    
    var existing = 0;
    if (location.element[location.prop]){
        existing = parseInt(location.element[location.prop]);
    }
    
    location.element[location.prop] = existing + interval;
    
    return doc;
}

function incrementFloat(doc, patch, location){
    var interval = 1;
    if (patch.increment){
        interval = parseFloat(patch.increment);
    }
    
    var existing = 0;
    if (location.element[location.prop]){
        existing = parseFloat(location.element[location.prop]);
    }
    
    location.element[location.prop] = existing + interval;
    
    return doc;
}

function appendElement(doc, patch, location){
    if (!location.element[location.prop]){
        location.element[location.prop] = [];
    }
    
    location.element[location.prop].push(patch.value);
    
    return doc;
}

function insertElement(doc, patch, location){
    if (!location.element[location.prop]){
        location.element[location.prop] = [];
    }
    
    var array = location.element[location.prop];
    
    var index = 0;
    if (patch.index){
        index = parseInt(patch.index);
    }
    
    array.splice(index, 0, patch.value);
    
    return doc;
}

function rename(doc, patch, location){
    var actual = location.element[location.prop];
    delete location.element[location.prop];
    
    location.element[patch.to] = actual;
    
    return doc;
}

var ops = {
    'set': setValue,
    'increment': incrementValue,
    'increment_float': incrementFloat,
    'append': appendElement,
    'rename': rename,
    'insert': insertElement
    
}

module.exports = function(doc, patch){
    // TODO -- throw if not a handler
    var handler = ops[patch.type];
    
    var location = locate(doc, patch);
    
    return handler(doc, patch, location);    
}

  var func = module.exports;

  return func(doc, patch);

$$ LANGUAGE plv8 IMMUTABLE STRICT;

exception s:    at Marten.Schema.DocumentSchema.Marten.Schema.IDDLRunner.Apply(Object subject, String ddl)
   at Marten.Schema.FunctionDiff.WritePatch(StoreOptions options, SchemaPatch patch)
   at Marten.Transforms.TransformFunction.GenerateSchemaObjectsIfNecessary(AutoCreate autoCreateSchemaObjectsMode, IDocumentSchema schema, SchemaPatch patch)
   at Marten.Schema.DocumentSchema.ApplyAllConfiguredChangesToDatabase()
   at CQRSGui.MvcApplication.Application_Start() in 

****************

**Comment by jeremydmiller** [comment]
Have you enabled PLV8 on your Postgresql database? That’s my first guess.

**Comment by haamaanaa** [comment]
propably not as i dont know what that is :)

**Comment by jeremydmiller** [comment]
@haamaanaa Okay, sorry about that. PLV8 is starting to come built into a lot of the common postgresql hosting so we've kinda forgotten about that in the docs.

Here's a link on what it is and enabling it if it's there: https://github.com/plv8/plv8
Assuming you're on Postgres 9.5, here's the download for the binaries if you need that: http://www.postgresonline.com/journal/archives/360-PLV8-binaries-for-PostgreSQL-9.5-windows-both-32-bit-and-64-bit.html.

**Comment by haamaanaa** [comment]
Yup, those helped!

Awesome super-fast support :+1:
