### ISSUE TITLE
Skip/Take with Select can cause Where clause to be excluded from generated SQL

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/marten#504]
If you `Skip/Take` before calling `Select` then Marten ignores any `Where` clause you may have included in your Linq query. If you put `Skip/Take` after the call to `Select` then the `Where` clause is applied appropriately.

I can understand why you need to put `Skip/Take` after a `Where` or `OrderBy` but it seems like this is a bug that you have to place the `Skip/Take` after the `Select` for it to work properly.

# Examples:

```csharp
var items = await session
    .Query<User>()
    .Where(x => x.OrganizationId == organizationId)
    .OrderBy(x => x.Name)
    .Skip(0) // before the select clause
    .Take(10)
    .Select(x => new
    {
        Id = x.Id,
        Name = x.Name
    })
    .ToListAsync();
```

results in the following SQL being generated:

```sql
select json_build_object('Id', d.id, 'Name', d.data ->> 'Name') as json, count(1) OVER() as total_rows from public.mt_doc_user as d LIMIT 20 OFFSET 0
```

Notice that there is no `order by`, and there is no filter by the specified OrganizationId from the `Where` clause.

However this:

```csharp
var items = await session
    .Query<User>()
    .Where(x => x.OrganizationId == organizationId)
    .OrderBy(x => x.Name)
    .Select(x => new
    {
        Id = x.Id,
        Name = x.Name
    })
    .Skip(0) // after the select clause
    .Take(10)
    .ToListAsync();
```

results in this:

```sql
select json_build_object('Id', d.id, 'Name', d.data ->> 'Name') as json, count(1) OVER() as total_rows from public.mt_doc_user as d where d.organization_id = :arg0 order by d.data ->> 'Name' LIMIT 20  OFFSET 0
```

**Comment by jeffdoolittle** [comment]
So I can see a few ways to address this:

1) Do nothing, but update the documentation somewhere to make it clear how this is meant to work with an explanation of why it works this way

2) Throw an exception if someone tries to `Skip/Take` before a `Select`

3) Alter the SQL generation process to handle `Skip/Take` both before and after a `Select`

The first option seems unhelpful and violates the principle of least surprise in my opinion. The second option I think would be better than nothing. But ideally, I think the third option is the way to go.

**Comment by jeremydmiller** [comment]
We'll do 3. I'll take a look at it later today or tomorrow morning. Shouldn't be that bad to fix.

**Comment by jeffdoolittle** [comment]
here's a passing test for when the skip/take is after the `Select` and a failing one for when it comes after:

https://github.com/jeffdoolittle/Marten/commit/3ebb448dd64afdcff3049dced1e10f25006f2ffb
