### ISSUE TITLE
Support Select() from the MartenQueryable() ????

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#51]
If you do session.Query<MyDocument>().Where(blah blah blah).Select(x => x.Something) it goes pear shaped. You have to do an intermediate ToArray() or ToList() in between.

Think about this and see if anyone really wants projections directly over the top of the document tables. Might temporarily have it fetch and deserialize, then do the projection in memory. Because you know that no one would kill their perf by using that naively.

**Comment by ekulakov** [comment]
IMO it's nice to have. But I vote for true projection (in DB) or no projection at all.

**Comment by jeremydmiller** [comment]
@ekulakov It will happen in the database. I'm not too far away from having this done. I've got some of the obvious use cases working locally now.
