### ISSUE TITLE
WriteDDLByType requires live connection to PostgreSQL to execute

### ISSUE THREAD

**Issue by bradyclifford** [JasperFx/marten#510]
Is it possible to invoke the `WriteDDLByType()` method without having to provide a connection string to the DocumentStore and a live connection to a PostgreSQL instance?

I haven't checked it with the last build, but have noticed that currently, this is its behavior.

> This might be resolved with your latest build that includes the ability to inherit a Marten CLI. Have not yet looked into that.

**Comment by jeremydmiller** [comment]
@bradyclifford According to this test, you can do that, but you may need to throw the switch on AutoCreate.None:

```

        [Fact]
        public void can_write_ddl_by_type_with_no_database_connection()
        {
            using (var store = DocumentStore.For(_ =>
            {
                _.RegisterDocumentType<User>();
                _.RegisterDocumentType<Company>();
                _.RegisterDocumentType<Issue>();

                _.AutoCreateSchemaObjects = AutoCreate.None;

                _.Connection("");
            }))
            {
                store.Schema.Events.IsActive.ShouldBeFalse();
                store.Schema.WriteDDLByType(@"bin\allsql");
            }

            var fileSystem = new FileSystem();
            fileSystem.FindFiles(@"bin\allsql", FileSet.Shallow("*mt_streams.sql"))
                .Any().ShouldBeFalse();
        }

```

**Comment by jeremydmiller** [comment]
I'm closing this one for now.
