### ISSUE TITLE
Prevent Marten to handle questionmarks in operators as parameters

### ISSUE THREAD

**Issue by robinvanderknaap** [JasperFx/marten#518]
The following statement in a custom query: data->'Hashtags' ?& ARRAY['something'], will break because the question mark in the operator is being replaced with a parameter value.

A number of jsonb operators containing a questionmark exist: https://www.postgresql.org/docs/9.5/static/functions-json.html

Several solutions here:

- Create a list of known operators, which will not be touched by Marten
- Named parameters, which can be passed in using an anonymous object  
- Escaping the questionmark

**Comment by robinvanderknaap** [comment]
I personally like the named parameter approach, which is also used by Dapper ORM. Queries could look like this:

`session.QueryAsync<Dog>("where Age = @Age and Id = @Id", new { Age = 23, Id = 34 });`

**Comment by robinvanderknaap** [comment]
I don't mind doing a pull request for this, but I would like to know if named parameters is the preferred  way.

**Comment by jeremydmiller** [comment]
I've gone back and forth several times. I'm good with the named parameter approach. If you saw the Gitter room this morning, I'm saying that this would probably roll into a 1.1 release.

**Comment by jeremydmiller** [comment]
@robinvanderknaap Would you still be interested in trying this one? If not, I'll take it early next week.

**Comment by robinvanderknaap** [comment]
I'll give it a try this weekend. I'll let you know if I succeeded. If not, I'll be happy if you take it on.

**Comment by robinvanderknaap** [comment]
To enable named parameters without breaking the current positional parameter, I check if the first parameter is an anonymous object. Maybe not the best approach, because a normal object should also be allowed.

**Comment by robinvanderknaap** [comment]
Another solution would be to create a separate Query method on the session, e.g. QueryWithNamedParameters.

**Comment by jeremydmiller** [comment]
Addressed by #586
