### ISSUE TITLE
`ITransform` not receiving event version when called

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/marten#523]
When my implementation of the `ITransform` method `TView Transform(EventStream stream, Event<TEvent> input)` is called, the `Version` property of the `Event<TEvent> input` parameter is always zero.

**Comment by jeremydmiller** [comment]
Is this an inline projection? The version wouldn't be assigned until the unit of work is saved to the DB.

**Comment by jeffdoolittle** [comment]
That makes sense, I think I was unclear on what "inline" meant. Is there a way to get an event version number that can be included in a projection/transformation? I'm guessing maybe this will only work in the async daemon?

**Comment by jeremydmiller** [comment]
It will work in the async daemon. If need be, you can initiate a raw SQL request to get the current version for that stream and number the events from there.

What are you doing that you'd want the version number anyway?

**Comment by jeffdoolittle** [comment]
Building up a generic projection of events that have a shared base type to reduce direct queries against the primary event stream and the `mt_events` table. Meant to be used as part of synchronizing the event stream with other systems.

**Comment by jeffdoolittle** [comment]
Our concern (possibly premature) is contention around the `mt_events` table if we have to query it directly to synchronize the event stream across multiple systems.

**Comment by jeffdoolittle** [comment]
I'm going to close this. We'll go ahead and resolve this by directly querying the event stream and move to using the async daemon in the future if contention ever materializes as a real-world issue.
