### ISSUE TITLE
Do no schema verification checks if AutoCreate == None

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#524]
You do still have the explicit IDocumentSchema.AssertDatabaseMatchesConfiguration(), but otherwise, if AutoCreate == None, don't check the schema at all.

Causing us issues at work. We suspect it's from getting too cute with database GRANT's and ROLE's, but we don't know that for sure.

**Comment by jeffdoolittle** [comment]
Any benefit from adding a fifth option between "None" and "CreateOnly" perhaps called "CheckOnly"? Maybe YAGNI but possibly makes the auto create api clearer and more explicit. Just a thought.

**Comment by jeremydmiller** [comment]
Um, yeah, maybe. You do have the Assert() to find any differences. Mind adding that as an enhancement issue?

**Comment by jeffdoolittle** [comment]
will do
