### ISSUE TITLE
Environment check support

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/marten#525]
GH-524 removed a call to `IDocumentSchema.AssertDatabaseMatchesConfiguration()` when the `AutoCreate` option is set to `None` (which of course makes logical sense).

While it is possible for someone to manually call `IDocumentSchema.AssertDatabaseMatchesConfiguration()` consider adding an additional `AutoCreate` option called `CheckSchemaOnly` that does exactly and only what it says - make the call to `IDocumentSchema.AssertDatabaseMatchesConfiguration()` and do nothing else.

**Comment by jeremydmiller** [comment]
I'm moving this to 2.0 when we do the full overhaul of the mechanisms for checking and updating the DDL objects

**Comment by tonykaralis** [comment]
@oskardudycz  Will do a bit of research and formulate a plan of how to implement.

**Comment by jeffdoolittle** [comment]
@jeremydmiller @tonykaralis is this even relevant anymore? I haven't used Marten in a couple of years, but will be diving back in again soon.

**Comment by jeremydmiller** [comment]
At this point now that we have `HostBuilder` integration, I'd vote to make this an option in the bootstrapper that adds an optional `IHostedService` that does this check if the users opt into it. Another option is to make it be an environment test through Oakton.AspNetCore through the command line support. I think I'd prefer that TBH.
