### ISSUE TITLE
Issues with Visual Studio 2015

### ISSUE THREAD

**Issue by lsusatyo-gcmlp** [JasperFx/marten#526]
HI,

I'm using Visual Studio 2015, .net framework 4.6.2, marten version 1.0.1. Running the following code:

    public class User
    {
        [Identity]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
            var store = DocumentStore.For(_ =>
            {
                _.Connection("Host=somehost;Port=5439;Database=somedatabase;Username=user;Password=pass");
                _.Schema.For<User>().DocumentAlias("users");
                _.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
            });

            using (var session = store.OpenSession())
            {
                try
                {
                    session.Store(user);
                    session.SaveChanges();
                } catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }

And an exception is thrown during the "Store" method

"DDL Execution for 'Storage Table and Upsert Function for PostgreSQL_JSONB.User' Failed!\n\nDROP TABLE IF EXISTS public.mt_doc_users CASCADE;\r\nCREATE TABLE public.mt_doc_users (\r\n    id                  integer CONSTRAINT pk_mt_doc_users PRIMARY KEY,\r\n    data                jsonb NOT NULL,\r\n    mt_last_modified    timestamp with time zone DEFAULT transaction_timestamp(),\r\n    mt_version          uuid NOT NULL default(md5(random()::text || clock_timestamp()::text)::uuid),\r\n    mt_dotnet_type      varchar \r\n);\r\n\r\n\r\n\r\nCREATE OR REPLACE FUNCTION public.mt_upsert_users(doc JSONB, docDotNetType varchar, docId integer, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$\r\nDECLARE\r\n  final_version uuid;\r\nBEGIN\r\nINSERT INTO public.mt_doc_users (\"data\", \"mt_dotnet_type\", \"id\", \"mt_version\", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp())\r\n  ON CONFLICT ON CONSTRAINT pk_mt_doc_users\r\n  DO UPDATE SET \"data\" = doc, \"mt_dotnet_type\" = docDotNetType, \"mt_version\" = docVersion, mt_last_modified = transaction_timestamp();\r\n\r\n  SELECT mt_version FROM public.mt_doc_users into final_version WHERE id = docId;\r\n  RETURN final_version;\r\nEND;\r\n$function$;\r\n\r\n\r\n\r\n\r\n\r\n"

{"42601: syntax error at or near \"ON\""}

**Comment by jeremydmiller** [comment]
Can you stick the exception in a text block? Like so?

```
your text
```

**Comment by lsusatyo-gcmlp** [comment]
Exception Message:

<pre><code>

DDL Execution for 'Storage Table and Upsert Function for PostgreSQL_JSONB.User' Failed!\n\nDROP TABLE IF EXISTS public.mt_doc_users CASCADE;
CREATE TABLE public.mt_doc_users (
    id                  integer CONSTRAINT pk_mt_doc_users PRIMARY KEY,
    data                jsonb NOT NULL,
    mt_last_modified    timestamp with time zone DEFAULT transaction_timestamp(),
    mt_version          uuid NOT NULL default(md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar 
);



CREATE OR REPLACE FUNCTION public.mt_upsert_users(doc JSONB, docDotNetType varchar, docId integer, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$
DECLARE
  final_version uuid;
BEGIN
INSERT INTO public.mt_doc_users (\"data\", \"mt_dotnet_type\", \"id\", \"mt_version\", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp())
  ON CONFLICT ON CONSTRAINT pk_mt_doc_users
  DO UPDATE SET \"data\" = doc, \"mt_dotnet_type\" = docDotNetType, \"mt_version\" = docVersion, mt_last_modified = transaction_timestamp();

  SELECT mt_version FROM public.mt_doc_users into final_version WHERE id = docId;
  RETURN final_version;
END;
$function$;

</code></pre>


Stack Trace:

<pre><code>

at Marten.Schema.DocumentSchema.Marten.Schema.IDDLRunner.Apply(Object subject, String ddl)
   at Marten.Schema.DocumentSchemaObjects.rebuildTableAndUpsertFunction(IDocumentSchema schema, SchemaPatch runner)
   at Marten.Schema.DocumentSchemaObjects.rebuildAll(IDocumentSchema schema, SchemaPatch runner)
   at Marten.Schema.DocumentSchemaObjects.buildOrModifySchemaObjects(SchemaDiff diff, AutoCreate autoCreateSchemaObjectsMode, IDocumentSchema schema, SchemaPatch runner)
   at Marten.Schema.DocumentSchemaObjects.GenerateSchemaObjectsIfNecessary(AutoCreate autoCreateSchemaObjectsMode, IDocumentSchema schema, SchemaPatch patch)
   at Marten.Schema.DocumentSchema.<>c__DisplayClass57_0.<buildSchemaObjectsIfNecessary>b__2(IDocumentMapping x)
   at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Marten.Schema.DocumentSchema.buildSchemaObjectsIfNecessary(IDocumentMapping mapping)
   at Marten.Schema.DocumentSchema.<>c__DisplayClass30_0.<StorageFor>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Marten.Schema.DocumentSchema.StorageFor(Type documentType)
   at Marten.DocumentSession.Store[T](T[] entities)
   at PostgreSQL_JSONB.Program.Main(String[] args) in D:\\Development\\PostgreSQL_JSONB\\PostgreSQL_JSONB\\Program.cs:line 40

</code></pre>

The version of postgresql is "PostgreSQL 9.4.5 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit"

**Comment by jeremydmiller** [comment]
Yup, Marten requires Postgresql 9.5+. We rely on the "upsert" additions in 9.5.

**Comment by jeremydmiller** [comment]
I'm going to go ahead and close this. I think all it is is needing to move up to 9.5.

**Comment by lsusatyo-gcmlp** [comment]
Hi Jeremy,

Thank you for resolving this issue. I can use the framework 1.0.1 now with the latest postgresql.
