### ISSUE TITLE
[Documentation] PostgreSQL Options

### ISSUE THREAD

**Issue by khalidabuhakmeh** [JasperFx/marten#530]
In @jeremydmiller latest blog post ["Why you should give Marten a look before adopting an ORM like EF"](https://jeremydmiller.com/2016/09/23/why-you-should-give-marten-a-look-before-adopting-an-orm/#comment-10563), one of the arguments for why you wouldn't choose Marten is:

> You don’t have any experience with Postgresql

I believe a good section for the documentation, would be getting started with PostgreSQL.
- Where To Download PostgreSQL
- Setup based on OS (Windows, macOS, Linux, or even Docker)
- Your first database, creating / naming

In addition to starting with PostgreSQL for development. Having some documentation on how to use PostgreSQL in production in Windows Azure or other cloud providers that community members are familiar with.

**Comment by jeremydmiller** [comment]
I think we're in good shape on this one now after all of @phillip-haydon 's docs
