### ISSUE TITLE
IndexName is not validated to be < 64 bytes

### ISSUE THREAD

**Issue by jimgolfgti** [JasperFx/marten#535]
The default value for NAMEDATALEN is 64, although this can be overridden in the source code (Postgres) and recompiled.
See https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

Generated, or specified, Index Names longer than this will be truncated to NAMEDATALEN - 1 when created and a notice emitted but it is unlikely to be seen by users.

Because the actual index name and the configured index name now differ when DocumentSchemaObjects performs a diff the index will be assumed to be missing and an attempt will be made to regenerate, dependent on the value of StoreOptions.AutoCreateSchemaObjects.

**Comment by jimgolfgti** [comment]
I would create a pull request for this but I'm not sure what the behaviour should be;
One option is that Marten assumes default is 64, can be overridden via StoreOptions, and truncates object names when diffing

Another option is that Marten truncates generated name to < 64, configurable via StoreOptions, and throws on configured names >= 64.

Any others?

**Comment by jeremydmiller** [comment]
@jimgolfgti This kind of thing hasn't been the fun part of working with Marten. I think we do about what you said up above. Make the MaxConfiguredLength be configurable w/ 64 as the default. I think I'd prefer to have Marten throw an exception offhand.

Think we'd have to deal with this on:

- [ ] Index's
- [ ] Tables
- [ ] Procedures

**Comment by jeremydmiller** [comment]
@jimgolfgti Ugh, I'm sorry, but I'm going to have to push this to 1.2 because it'll be a new public member on StoreOptions. I'll try to get that going soon too.

**Comment by jimgolfgti** [comment]
@jeremydmiller We're working around issues as they come up, infrequently.

Hopefully I'll find some time to help out with it.

**Comment by jeremydmiller** [comment]
Please do report anything that gets in your way though.

**Comment by jeremydmiller** [comment]
And awesome, I just accidentally made this happen trying to fix another bug. Ugh.
