### ISSUE TITLE
Marten.Embedded

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#538]
Continuing from https://github.com/JasperFx/marten/issues/248.

Let's see if we can build a new nuget that can effectively spin up Postgresql for you and use that as a special "embedded" database equivalent.

**Comment by jeremydmiller** [comment]
Checkout https://www.nuget.org/packages/PostgreSql.Binaries.Lite/

**Comment by jeremydmiller** [comment]
I think this is just going to be some doc's pointing to @mysticmind 's https://github.com/mysticmind/mysticmind-postgresembed package. Might not be a bad idea to rig up the Marten codebase itself to use this.

**Comment by jeremydmiller** [comment]
I'm actually going to shut this one down and just point folks at @mysticmind's project

**Comment by SbiCA** [comment]
Hi @jeremydmiller not sure how far you are this. 

For what it's worth I've used marten in combination with test containers and was quite happy so far https://sbica.github.io/posts/2020/07/17/how-net-testcontainers-simplify-your-life-for. Let me know if that's something that could serve in the meantime or as an alternative to the "Embedded" option.

Cheers
