### ISSUE TITLE
Marten.Dapper

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#545]
I think that fixing https://github.com/JasperFx/marten/issues/544 might be likely to mess up Dapper usage. Let's go ahead and add some extension methods to IDocumentSession to make Dapper easier to integrate w/ IDocumentSession.

**Comment by phillip-haydon** [comment]
I took a look at this, and I believe the only change that needs to happen is to this line:

https://github.com/JasperFx/marten/blob/master/src/Marten/QuerySession.cs#L315

This should change to:

```csharp
public NpgsqlConnection Connection
{
    get
    {
        if (!_connection.InTransaction)
        {
            _connection.BeginTransaction();
        }
        
        return _connection.Connection;
    }
}
```

This should make it function the same again but still defer the transaction until it's required.

**Comment by jeremydmiller** [comment]
Doesn't that completely defeat the purpose of making the transaction lazy? A read through Dapper would cause it to start a TX, which would give you the magic ROLLBACK; behavior after the connection is returned to the pool.

**Comment by phillip-haydon** [comment]
So what is the problem we are trying to solve?

Transactions are now deferred until the first use of the connection. 

1. If you use Marten to select something it will start a transaction, and if you don't save changes it will roll back.
2. If you use Marten to only insert data then the transaction is started / committed when you call save changes.
3. If you use Marten to select / update, it will start a transaction on select and commit on save changes.
4. If you use Dapper to select ?!?!? <-- My proposal here is, start the transaction, and commit on save changes...

**Comment by jeremydmiller** [comment]
What we found in production is that it caused problems to start transactions but not commit or roll them back. Npgsql mostly takes care of that for you when it returns the connection to the pool, but our guys found cases where an exception of some sort would make the connection with the hanging TX be unusable.

So I'm trying to avoid tx's getting started when all you're doing is reading.

Are you saying to add TX rollback to the `DocumentSession.Dispose()` if it's already in a tx?

I'm good with 4., but again think it's worth the itty bitty Marten.Dapper nuget.

**Comment by mdissel** [comment]
> Are you saying to add TX rollback to the DocumentSession.Dispose() if it's already in a tx?

Yes, good idea ;)

I agree with @phillip-haydon  .. SaveChanges chould check if there's already an active transaction, if not start and commit. If the transaction is already active, the commit should be done manually. 
This way you can mix regular SQL queries with Marten queries..
We could even use the SAVEPOINT <name> ROLLBACK TO <name> inside the SaveChanges(), throw an exception and let the caller decide to do a full rollback or continue..

I'm no postgresql expert, but in SQL Server for optimal performance you should encapsulate multiple separate sql commands into a single transaction. If this is also valid for postgresql, another reason to make the transaction in the SaveChanges more intelligent.

And one last point, maybe introduce the BEGIN TRANSACTION READ_ONLY in the QuerySession class if we want to encapsulate all queries within an transaction..

**Comment by jeremydmiller** [comment]
@mdissel -->

"SaveChanges chould check if there's already an active transaction, if not start and commit" -- basically what it already does.

I really don't want anything to do with nested transactions in Marten. `SaveChanges()` should be assumed to mean "finish all outstanding changes in one logical transaction". I missed a detail in the API to allow you to easily combine your own SQL commits with a Marten session Unit of Work (it is possible, just not clear how to do that). That'll be addressed in 1.3. @tim-cools bumped into that one too.

**Comment by mdissel** [comment]
Ahh.. I missed the code in transactionstate.BeginTransaction(..). 
One easy implementation could be to return true when a new transaction is started and only commit if a new transaction is started so we minimize the number of transactions and connection opening/closing.

**Comment by jeremydmiller** [comment]
Nope, double checked the connection mechanics in QuerySession today and this is completely unnecessary. We just need some documentation on it.

**Comment by jeremydmiller** [comment]
Meh, I'm never getting around to this one.

**Comment by jeremydmiller** [comment]
Closing because it's just not gonna happen
