### ISSUE TITLE
PostgreSQL precision quirk surfacing on Duplicate Field

### ISSUE THREAD

**Issue by matthewtamm** [JasperFx/marten#550]
Having an issue whereby Marten is upset that my table definitions vary but they kinda don't.  As I am wanting to use in an ES capacity, I added a simple duplicate field to an inline projection:

``` csharp
_.Schema.For<QuestParty>().Duplicate(qp => qp.Name, "character varying (100)");
_.Events.InlineProjections.AggregateStreamsWith<QuestParty>();
```
And that works as expected, I get a duplicated name field on in my **mt_doc_questparty** table:

```sql
CREATE TABLE public.mt_doc_questparty (
   --// omitted
    name character varying (100) 
);
```

When the `AutoCreateSchemaObjects` option is `AutoCreate.All` - this all works as expected, but if I use say, `AutoCreate.CreateOnly` it blows up as the upsert function differs, which I think is due to this - [not from official docs](http://postgresql.nabble.com/Function-args-TEXT-vs-VARCHAR-tc5777968.html#a5778147):

>parenthesized type modifiers (e.g., the precision field for type numeric) are discarded by CREATE FUNCTION

When the upsert function is created, the following is passed to PG:

```sql 
CREATE OR REPLACE FUNCTION public.mt_upsert_questparty ( 
   arg_name character varying (100), 
   doc JSONB, 
   docDotNetType varchar, 
   docId uuid, docVersion uuid
) RETURNS...
```
But, seems that PG actually only creates the following, dropping the precision on the first `arg_name` parameter:

```sql
CREATE OR REPLACE FUNCTION public.mt_upsert_questparty(
    arg_name character varying,
    doc jsonb,
    docdotnettype character varying,
    docid uuid,
    docversion uuid
) RETURNS...
```

So now, when Marten fires up (using `AutoCreate.CreateOnly` ) it scripts the first version, compares that to the PG version, and raises an **InvalidOperationException** in `DocumentSchemaObjects.buildOrModifySchemaObjects`

`The table for document type QuestParty is different than the current schema table, but AutoCreateSchemaObjects = 'CreateOnly'`

Digging into the `SchemaDiff`, there is a `Function` diff, with as described above, the `Actual` does not have the precision, and the `Excepted` does.

Now, if I go back and change my duplicate to not have any precision, all good:

``` csharp
_.Schema.For<QuestParty>().Duplicate(qp => qp.Name, "character varying");
_.Events.InlineProjections.AggregateStreamsWith<QuestParty>();
```

This is fine for my simple explorations, but believe will trip others in the near future.  I don't have [any] experience with PostgreSQL to comment on how it (and Marten) should behave here.

Thanks for Marten - just diving in now and enjoying so far!

**Comment by matthewtamm** [comment]
Just to add, turns out these is a `TableDiff` too, `Expected` has the precision, and the `Existing` does not.  I _believe_ this could be addressed by changing the first SELECT in **SchemaObjects.sql** to include the precision, similar to how it is done for the indexes, something like:

```sql
SELECT a.attname as column_name, format_type(a.atttypid, a.atttypmod) AS data_type
FROM pg_attribute a
INNER JOIN pg_class b ON (a.attrelid = b.relfilenode)
INNER JOIN information_schema.columns c ON (b.relname = c.table_name)
WHERE c.table_schema = :schema
    AND c.table_name = :table_name 
    AND a.attname = c.column_name
ORDER BY c.ordinal_position;
```

The above, and changing the duplicate field definition to remove the space before the precision, eliminates the TableDiff

``` csharp
_.Schema.For<QuestParty>().Duplicate(qp => qp.Name, "character varying(100)");
```

Sorry - I am not yet building and running tests to _actually_ contribute as yet

**Comment by matthewtamm** [comment]
As for the function diff, it leads me to the ctor in `UpsertFunction`  where the duplicated fields are added to the Arguments collection:

``` csharp
Arguments.AddRange(mapping.DuplicatedFields.Select(x => x.UpsertArgument));
```
If this were to remove any precision specified in the duplicated field ..

``` csharp
Arguments.AddRange(mapping.DuplicatedFields.Select(x => RemovePrecision(x.UpsertArgument)));

private UpsertArgument RemovePrecision ( UpsertArgument argument )
{
    argument.PostgresType = argument.PostgresType.Substring ( 0, argument.PostgresType.LastIndexOf ( '(' ) )?.TrimEnd ( );
    return argument;
}

```

These feels a bit cheap, lazy even, but it does get the job done?

**Comment by jeremydmiller** [comment]
@matthewtamm Oh man, I hate Postgresql's metadata tables. I'm not proud of this **at all**, but for now I'm doing the equivalent to what you were saying about ignoring the precision/length/et al in the schema comparisons. Going to play the "perfect is the enemy of the good card";)

This test passes for me in my branch now:

```

    public class Bug_550_schema_diff_with_precision : IntegratedFixture
    {
        [Fact]
        public void can_handle_the_explicit_precision()
        {
            // Configure a doc 
            StoreOptions(_ =>
            {
                _.Schema.For<DocWithPrecision>().Duplicate(x => x.Name, "character varying (100)");
            });

            theStore.Schema.ApplyAllConfiguredChangesToDatabase();


            var store = DocumentStore.For(_ =>
            {
                _.AutoCreateSchemaObjects = AutoCreate.CreateOnly;
                _.Connection(ConnectionSource.ConnectionString);
                _.Schema.For<DocWithPrecision>().Duplicate(x => x.Name, "character varying (100)");
            });

            var diff = store.Schema.MappingFor(typeof(DocWithPrecision))
                .SchemaObjects.As<DocumentSchemaObjects>().CreateSchemaDiff(store.Schema);

            diff.FunctionDiff.HasChanged.ShouldBeFalse();
            diff.TableDiff.Different.Any().ShouldBeFalse();

            diff.HasDifferences().ShouldBeFalse();
        }


    }

    public class DocWithPrecision
    {
        public Guid Id;


        public string Name { get; set; }
    }
```
