### ISSUE TITLE
gh-pages?

### ISSUE THREAD

**Issue by hougasian** [JasperFx/marten#552]
@jeremydmiller want any help on the `gh-pages` branch? I have some time now :D

**Comment by jeremydmiller** [comment]
@hougasian If you're up for it, I'm never going to say no to that offer. All the docs are in the /documentation folder in the main repo. I only publish the exported html to gh-pages, but the authoring is all in markdown files.

I think we need more content and examples on the Event Sourcing, especially projections, than anything else, but anything you wanna add will help. We do need to start building up some Postgresql tips and integrating with other tools.

What were you thinking?

**Comment by jeremydmiller** [comment]
@hougasian Absolutely. The actual website is in the main Marten repo with all the content in /documentation as markdown files.  If you're on Windows, there's a command called `run-docs.cmd` that should spin up a browsable website and pop open a browser window to it. You do get auto-refresh w/ the runner.

The main page is just a static html file (w/ some Markdown-esque extensions) called "splash.htm." Every other page uses the de facto template file "layout.htm." All I've done is download a bootstrap theme and followed along.

I **will** have it able to run the docs on the Mac soon, but it's not quite there yet, so you're stuck w/ Windows.

**Comment by hougasian** [comment]
@jeremydmiller Any reason to not go the Jekyll path for the actual website? I'd like to leverage the jekyll/sass combo. The documentation can then stand solely on Storyteller. Thoughts?

**Comment by jeremydmiller** [comment]
@hougasian I don't really know enough to have an opinion tbh. As long as I can still author the content w/ Storyteller, I'm good with anything. It's perfectly feasible to change ST itself if that would help.

**Comment by khalidabuhakmeh** [comment]
I've told @hougasian, but you no longer need a `gh-pages` branch to serve the github pages site. You can go into the repos settings and pick a branch and a folder. I suggest moving it into the `master` branch, so you can keep it in sync with the projects code.

**Comment by jeremydmiller** [comment]
Nothing happening here and this was just a question. I'm closing this.
