### ISSUE TITLE
Foreign key index support

### ISSUE THREAD

**Issue by pblachut** [JasperFx/marten#553]
I`ve just tried to use foreign key support as it was described [here](http://jasperfx.github.io/marten/documentation/documents/customizing/foreign_keys/).

I`ve noticed two issues:
- ForeignKey attribute on document definition does not create index in postgres, where fluent definition does as it should.

[Used attribute definition](https://github.com/pblachut/MartenWebApp/blob/master/src/MartenWebApp/User.cs)
[Used fluent definition](https://github.com/pblachut/MartenWebApp/blob/master/src/MartenWebApp/DocumentDatabaseStoreFactory.cs)

- I`ve noticed some unexpected behavior for me during inserting new document with invalid foreign key. It just allowed me to do that without any error and additional column contained invalid id. Should I add some additional configuration to force checking this constraint?

My example of usage can be found [here](https://github.com/pblachut/MartenWebApp/blob/master/src/MartenWebApp/Controllers/DocumentDbController.cs).

**Comment by jeremydmiller** [comment]
@pblachut I'm looking at this now.

**Comment by jeremydmiller** [comment]
@pblachut I've got the `[ForeignKey]` behavior fixed. From my experimentation this morning, it's behaving the way I'd expect. You can insert data with NULL fk id's, but using a nonexistent FK id threw an exception from Postgresql the way you'd expect it to.

We have a test for this behavior from when the feature was built that's been passing every since.

**Comment by jeremydmiller** [comment]
There was a 2nd problem with using FK's against a nullable field or property. That's fixed as well.

**Comment by pblachut** [comment]
Yes, it was indeed. Constraint for not nullable id worked correctly. Thanks.
