### ISSUE TITLE
LINQ Queries with .Any() or .Count() throw or return wrong results

### ISSUE THREAD

**Issue by lngr** [JasperFx/marten#554]
The following code on an `List<Guid>` returns the wrong number of results if the list is empty:

`theSession.Query<Target>().Where(x => x.GuidList.Any()).ToList();
`

The following code throws an exception "Sequence contains no elements".

`theSession.Query<Target>().Where(item => item.NumberArray.Length == 3)`
`theSession.Query<Target>().Where(item => item.GuidList.Count() == 1)`

The attached pull-request has testcases.

**Comment by jeremydmiller** [comment]
This one's probably going to be easy to fix by just sticking an AND [locator] IS NOT NULL in the where clause.
```
theSession.Query<Target>().Where(x => x.GuidList.Any()).ToList(); 
```

These two?

```
theSession.Query<Target>().Where(item => item.NumberArray.Length == 3)
theSession.Query<Target>().Where(item => item.GuidList.Count() == 1)
```

You can work around that by just having a calculated field for the child count and query against that. I bet it'd be more efficient to do it that way than trying to do the JSON operators to get in there anyway. I'd honestly vote against trying to "fix" that in the Linq support.

**Comment by lngr** [comment]
OK, then we'll use the workaround here.

**Comment by jeremydmiller** [comment]
The `Any()` looks like it'll be fixed by #564. I'll try to address the `Count()` usage this week.

**Comment by jeremydmiller** [comment]
Got it this morning.

**Comment by lngr** [comment]
@jeremydmiller nice, thanks!
