### ISSUE TITLE
Auto-assign Guid id's if none is provided by client

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/Marten#56]
Should be easy.

**Comment by tim-cools** [comment]
I can implement this with a DynamicMethod (instead of reflection) if you want. I did something similar in the past: https://github.com/tim-cools/composition/blob/master/src/Soloco.Composition/Construction/ThisFieldSetterGenerator.cs

**Comment by jeremydmiller** [comment]
@tim-cools Hey, I appreciate that, but the Roslyn usage -- once you get past the Paket version problems -- makes this almost trivial because it's just code generation at runtime.

It'll be something like `if (doc.Id == default(Guid)) doc.Id = Guid.NewGuid();` directly in the code generation.

If the Roslyn thing actually does work out, I'm hoping to retire w/o seeing IL generation or even Expression munging ever again;-)

The only thing that's bugging me right now is that Roslyn has a warmup hit on the first access.

**Comment by tim-cools** [comment]
Haha, totally agree about the IL and Expression stuff :-)

I'm sure you find a solution for the Roslyn warmup. You can probably get around the first access hit by adding a post-compilation or deployment step. In this step you can generate the assemblies
