### ISSUE TITLE
Inline Projections - IProjection ApplyAsync stream events missing data

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#560]
In the ApplyAsync method of the `IProjection` interface, the `EventStream[]` Events all have the `Sequence`, `Version` and `Timestamp` not populated and set to the `default()` for their data types. 

`Data`, `Id` and `StreamId` are all populated correctly.

**Comment by jeremydmiller** [comment]
This has come up before. It'd be a significant performance hit to have that data during inline projections. It *is* available during async projections.

Today it's built to generate the projected documents **before** making the batched update to the server. If you wanted that in the projections, you'd have to calculate that afterward and make a second db request.

**Comment by ericgreenmix** [comment]
Ah, that makes sense.

**Comment by jeremydmiller** [comment]
I think this is more of a documentation failure here. I'm closing this one.
