### ISSUE TITLE
Revamp the Linq testing

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#567]
Think we could radically clean up the testing project and even the documentation if we could move most of the Linq testing to Storyteller tables and then embed the specs into the docs.

**Comment by oskardudycz** [comment]
@jeremydmiller is it still applicable?

**Comment by jeremydmiller** [comment]
Still applicable, and I think this is actually the first step in the Linq overhaul just trying to make the tests faster and quicker to extend. *But*, I don't think the Storyteller tests are even being executed these days, so let's go backward and get everything in to xUnit tests instead. 

More content forthcoming in a couple hours....

**Comment by mysticmind** [comment]
@jeremydmiller storyteller tests are executed in CI runs

**Comment by jeremydmiller** [comment]
@mysticmind My mistake. I'd definitely leave the ones for the event store there.

**Comment by jeremydmiller** [comment]
I'm declaring success for now. The way it is, it'll be pretty easy to add more stuff

**Comment by jeremydmiller** [comment]
Done in a branch.
