### ISSUE TITLE
SelectMany().Distinct().Count() in Linq

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#572]
Going to make this one a _low_ priority for right now, but later on be able to do queries like:

```
                query.Query<Product>().SelectMany(x => x.Tags).Distinct()
                    .Count().ShouldBe(6);
```

`Count()` by itself works, `Distinct()` by itself works, but not both.

**Comment by bsmith-sw** [comment]
It appears that whenever a count follows a SelectMany, the filtering clauses added after the SelectMany are dropped.

            return session.Query<CustomerDto>()
                .Where(c => c.IdAsString == customerId)
                .SelectMany(c => c.Workplaces)
                .Count(w => w.IdAsString == newWorkplace.IdAsString);

select sum(jsonb_array_length(CAST(d.data ->> 'Workplaces' as jsonb))) as number 
from public.mt_doc_customerdto as d where d.id = :arg0

 return session.Query<CustomerDto>()
                            .Where(c => c.IdAsString == customerId)
                            .SelectMany(c => c.Workplaces)
                            .Where(w => w.IdAsString == newWorkplace.IdAsString)
                            .Count();

**Comment by jeremydmiller** [comment]
@benprime The problem you tagged on this issue is addressed in the v4 branch.

**Comment by jeremydmiller** [comment]
Done in a branch. For both issues here.
