### ISSUE TITLE
AsyncDaemon: Rebuild after projections not working

### ISSUE THREAD

**Issue by tim-cools** [JasperFx/marten#577]
In my application I try to add Rebuild projections feature in the admin page. When I try to rebuild with the daemon that I also use to project my projections, the projections are not rebuild. The data is removed from the database, but the projections are not rebuild. I believe it is because as _lastEncountered in the Fetcher is not reset but stays at the event number of the previous projections.

The same behavior is happening when you rebuild twice from the same daemon. I added this in a test that fails.

**Comment by jeremydmiller** [comment]
@tim-cools The easy workaround is to just build a new daemon object each time you do that. I'm trying to make a fix for this now, but I'm running into trouble w/ postgres itself.
