### ISSUE TITLE
CombGuid implementation not correct for Postgres

### ISSUE THREAD

**Issue by barryhagan** [JasperFx/marten#579]
Currently the CombGuid generator does not produce uuids that will be sequential or ordered correctly in Postgres.

Postgres stores all uuids as big endian, in fact, it simply converts the string representation into a byte array without considering whether the system is big/little endian.

Given that the string representation of a Guid is always assumed to be big endian, Marten should be setting the timestamp portion of the comb in a way that will sort correctly in string representation rather than the byte order.  This will allow Postgres to sort correctly, and in .Net, the default Equality comparison of Guids can be used rather than byte order, which is more natural when doing things like .OrderBy() anyway.

**Comment by jeremydmiller** [comment]
This was addressed by #580
