### ISSUE TITLE
Create tests database automatically 

### ISSUE THREAD

**Issue by tim-cools** [JasperFx/marten#58]
For a project I'm working on I (re-)create a test pg database from code by calling psql with a script. It is not the cleanest way but you don't need a password for this. Assuming that the calling user has the rights and a default installation is used.

Doing so you don't need to create the database and enter a connection string manually and the tests run without any modification. I ported this to the Elephanet project. But I would be happy to add it to Marten too if you want?

I think that managing db's (create, delete) should be part of the core framework later. But I suspect that you want to use sql execution and authentication for that.

You can see the main code here: (Is still for 9.4) 
https://github.com/tim-cools/elephanet/blob/master/Elephanet.Tests/Infrastructure/CreateStore.sql
https://github.com/tim-cools/elephanet/blob/master/Elephanet.Tests/Infrastructure/TestStoreDatabaseFactory.cs

Let me know what you think?

**Comment by jeremydmiller** [comment]
Actually gonna close this one after a related PR came in today.
