### ISSUE TITLE
Use streams instead of JSON strings internally wherever possible

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#584]
The one criticism Ayende made about Marten that I thought was valid.

**Comment by jeremydmiller** [comment]
This one is going to be a no go for right now. Npgsql doesn't support reading JSONB types as a string. And I don't see any kind of GetStreamAsync() either. I think this is going to have to wait for later and maybe an Npgsql update.

**Comment by mdissel** [comment]
But according to this https://github.com/npgsql/npgsql/issues/885 and http://stackoverflow.com/questions/36112839/npgsql-support-for-getting-jsonb-field-as-stream this seems to supported.

**Comment by jeremydmiller** [comment]
Huh. Didn't work when I tried to spike that our today, but I was doing GetStream(). Let me try reader.GetTextReader(0) tomorrow instead.

**Comment by jeremydmiller** [comment]
Okay, that works. Not sure if it's as advantageous, but I'll still try that.

**Comment by jeremydmiller** [comment]
Looks like an exercise in tedium to deal with **reading** JSON data as a text reader wrapped around the stream. As for **writing**, I don't see anything that would work except for possibly writing a char[] to the parameter. Not sure why or how that would be helpful.

**Comment by jeremydmiller** [comment]
This isn't going well. There's a few places in the synchronous methods where it was easy to use a TextReader instead of a string to avoid the allocation hit, but I don't see anyway to do this with async fetching without mixing in blocking code.

Also, it's going to take a redesign of the identity map interface and interactions that's going to take a while. I'm pushing the easy fixes now, and going to come back to this one later. I think this might even take some changes to Npgsql to do well.

**Comment by jeffdoolittle** [comment]
It would be great if we had some metrics to tell us what we'd actually gain performance-wise. Otherwise it's hard to tell if this is a necessary or reasonably beneficial optimization.

**Comment by jeremydmiller** [comment]
@jeffdoolittle Going to easily agree with that one. I was too lazy to try it this morning, but I'd like to use this and the StringBuilder issue as an excuse to get into [Benchmark.Net](https://github.com/PerfDotNet/BenchmarkDotNet)

**Comment by jeremydmiller** [comment]
Gonna declare victory on this w/ one caveat. It's using the GetTextReader feature in Npgsql now, but there isn't an async version of that one. Not sure if that's a problem yet or not.

**Comment by jeffdoolittle** [comment]
@jeremydmiller can you point to the commit where the changes were made in marten?

**Comment by jeffdoolittle** [comment]
Hmm...

https://github.com/npgsql/npgsql/blob/e1259225c35b9664f8471de8456a72c8d473da50/src/Npgsql/NpgsqlDataReader.cs#L1026

look at line 1036

Seems like `GetTextReaderAsync` is just sitting there waiting to be implemented. Instead, the async is simply hidden behind a synchronous method call. Strange.

**Comment by jeremydmiller** [comment]
@jeffdoolittle It's spread over a couple commits in the 2.0 branch, but the first round of it was here: https://github.com/JasperFx/marten/commit/3c412eee5e0d0d34953dadcd388c4af3373ce74f.

There's a bunch of TODO's in there about using GetTextReaderAsync when it exists.

**Comment by jeffdoolittle** [comment]
Is there an Npgsql issue for adding `GetTextReaderAsync`?
