### ISSUE TITLE
Load should return objects from unit of work

### ISSUE THREAD

**Issue by tim-cools** [JasperFx/Marten#59]
Scenario:
- session.Store(student.id = 1)
- session.Load<Student>(1) returns null
(SaveChanges not called yet)

I expect that the second call returns the object stored by the first call from a cache. What do you think?

**Comment by jeremydmiller** [comment]
@tim-cools That probably needs to be part of a larger Identity Map feature. I've gone back and forth on whether or not we should do that underneath DocumentSession.

I can be convinced either way. I can think of a scenario or two within the system at work we're building Marten for that could use it.

**Comment by tim-cools** [comment]
I agree that it normally doesn't happen. But I'm creating an implementation of http://www.asp.net/identity backed-up by PG and I face this situation when I plug in the library for storage.

I also think you need an Identity map to detect dirty objects when doing a SaveChanges to the store if you want to support automatically updates like ravendb and the orm's does.

**Comment by jeremydmiller** [comment]
Done, but there's a separate issue for Select()
