### ISSUE TITLE
DDL Templating for patch_doc and immutable_timestamp functions

### ISSUE THREAD

**Issue by bradyclifford** [JasperFx/marten#594]
It would also be nice if these 2 functions would be able to apply similar formating as is done with the document DDL scripts.
- The `SECURITY DEFINER` setting similar to what is done with the document upsert functions using `StoreOptions.DdlRules.UpsertRights = SecurityRights.Definer`.
- The `StoreOptions.DdlRules.Role = "ROLE1";`.  We need the 2 functions to be wrapped by a `SET ROLES = "ROLE1"`.

We also have to set grants on these 2 functions.  If we could apply templating to these 2 functions like we do with the documents, that would be a plus.

**Comment by jeremydmiller** [comment]
@bradyclifford The grants or set roles are never going to be part of the schema validation. Both of these functions strictly work on arguments passed to them (non volatile), so I don't think that the security rights are going to matter at all.

All DDL getting dumped out is always surrounded by the SET ROLE thing as I recall. That's actually done at the export file level, not at the individual object level

That being said, does the templating actually still matter here?

**Comment by bradyclifford** [comment]
We just need to be able to run the Marten.Assert.  Currently, if either function has SECURITY DEFINER in its definition, the schema assertion fails.

**Comment by bradyclifford** [comment]
I believe this is still a problem @jeremydmiller.  We are unable to use the assertion method you have created with Marten.

**Comment by jeremydmiller** [comment]
We're definitely not going to do this now that we've gotten our DB team to stop being so insane about their DDL rules.
