### ISSUE TITLE
AsyncDaemon needs an explicit "start over on this projection" feature

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#596]
See #577. `Rebuild()`/`RebuildAll()` was meant for doing an explicit rebuild of a projection at one time. I saw it as useful for development and production migrations.

Now, if you want to tell a running AsyncDaemon to rebuild the projection against all the existing data, but continue to process new events, I think we need a separate mechanism.

cc // @tim-cools

**Comment by tim-cools** [comment]
@jeremydmiller good to know the rebuild was only designed to run once from the Daemon. Thinking about this again, i'm not sure if I really need the continue process. If we extract the rebuild mechanism out of the daemon and into a Projection(Re)builder class can be sufficient. It might prevent people from making the error I made...

**Comment by jeremydmiller** [comment]
@tim-cools Can you get by w/o this over the next couple weeks? *A* workaround is to have the daemon shut down that projection, do the rebuild, then tell it to start again. 

I'm running out of steam hard to squeeze out 1.2 and looking for ways to cut scope;)

**Comment by tim-cools** [comment]
@jeremydmiller sure! the workaround should works for me. no problem at all...

**Comment by jeremydmiller** [comment]
I see two big options:

1. New operations where you can override the tenant id. Change the projections (all the projections) to be aware of this
1. Have the async daemon "split" the flow of events coming in by tenant and use a separate document session for the matching tenant so that nothing but the async daemon has to deal w/ the tenancy. 

I think I vote number 2, but it's a big change to the async daemon. This is starting to get into areas where ReactiveExtensions might be better than the existing TPL DataFlow usage

**Comment by oskardudycz** [comment]
I'd vote for 2nd option, imho that'd make it cleaner.

Using ReactiveExtensions is imho good idea, this give a lot of possibilities, observability, etc.

My only concern is how soon could we tackle that and if we have right not the capacity.

**Comment by jeremydmiller** [comment]
@oskardudycz Heh, I wrote this up in the wrong issue. And I agree w/ the 2nd option.

**Comment by oskardudycz** [comment]
👍

**Comment by jeremydmiller** [comment]
Replacing this with #1609
