### ISSUE TITLE
Patch API does not modify duplicated columns

### ISSUE THREAD

**Issue by jimgolfgti** [JasperFx/marten#611]
Patching operations on duplicated fields do not modify the duplicated column value.

Some operations such as `Set`, `Duplicate`, `Increment`, `Decrement` should be able to be extended to make the necessary updates.

Some `Delete` operations should be able to support also.

The enumerable operations `Insert`, `Append` and `Remove` should be immune from change depending on whether Duplication is forbidden on enumerable members (needs clarification @jeremydmiller)

**Comment by jimgolfgti** [comment]
Example failing test case for `Set` operation
```csharp
[Fact]
public void duplicate_field_is_updated_by_set_operation()
{
    var mapping = theStore.Schema.StoreOptions.MappingFor(typeof(Target));
    var field = mapping.DuplicateField("String");
    theStore.Schema.ApplyAllConfiguredChangesToDatabase();

    var entity = Target.Random();
    theSession.Store(entity);
    theSession.SaveChanges();

    var newval = new string(entity.String.Reverse().ToArray());
    theSession.Patch<Target>(entity.Id).Set(t => t.String, newval);
    theSession.SaveChanges();

    using (var command = theSession.Connection.CreateCommand())
    {
        command.CommandText = $"select count(*) from {mapping.Table.QualifiedName} " +
                              $"where data->>'String' = '{newval}' and {field.ColumnName} = '{newval}'";
        var count = (long) (command.ExecuteScalar() ?? 0);
        count.ShouldBe(1);
    }
}
```

**Comment by jeremydmiller** [comment]
@jimgolfgti I'm finally looking at this this morning. I've got a plan I think.
