### ISSUE TITLE
Optional "auto-close" connection mode

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#614]
Have an opt-in mode where Marten closes every connection it opens as soon as it can without waiting for session.Dispose(). 

Not really sure we're gonna do this one.

**Comment by mdissel** [comment]
See #617 .. I really think a session should just be a wrapper around a IDbConnection and behave the same.. It's responsibility of the developer to properly close /dispose the connection, open will be handled by the session (only open the connection if a command is executed in the database)

**Comment by jeremydmiller** [comment]
@mdissel I'm doing this in reaction to problems at work in production where things aren't getting cleaned up the way they should be. So yes, if all our developers were perfect and I was omniscient, this wouldn't have been necessary, but since we're not, here we go.

**Comment by jeremydmiller** [comment]
I'm dropping this one. It's de facto fixed at work.
