### ISSUE TITLE
session.StoreObjects and versions

### ISSUE THREAD

**Issue by dotnetchris** [JasperFx/marten#615]
Currently there's not any straight forward method for storing multiple objects while supplying version information.

I ended up having to write code ala

```c#
private MethodInfo storeGeneric = typeof(IDocumentSession).GetMethods()
.Where(x=> x.Name == nameof(IDocumentSession.Store))
.Single(x=>
{
var @params = x.GetParameters();
return @params.Length == 2 && @params.Last().ParameterType == typeof(Guid);
});

void StoreGeneric<T>(IDocumentSession session, T document, Guid version)
{
    var invoker = storeGeneric.MakeGenericMethod(document.GetType());
    invoker.Invoke(session, new object[] {document, version});
}
```
So i could use it similar to 

```c#
using (var session = _store.LightweightSession())
{
    foreach (var document in documents)
        //session.Store(document, Guid.Empty);
        StoreGeneric(session, document, Guid.Empty);

    session.SaveChanges();
}
```

This works. 

But i think the true underlying issue is that `session.Store` does not invoke GetType() and instead infers it off the T argument. This breaks down when you have the scenario that ends up being equivalent to `Store( (object)foo )`

Maybe there should be an overload to Store with a signature akin to  `Store(Type, object, Guid)`.

Alternatively, maybe a solution would be to check `if T == object` or `if T is interface` to directly call GetType(). [Reviewing the source, i see it does `if (typeof (T) == typeof (object)) {       this.StoreObjects(entities.OfType<object>());` i'm not really sure this is optimal behavior]

I feel like there's some potential pitfalls with typing depending on how the document object is currently casted when it's passed to Store. I had encountered exceptions when i was originally trying to persist disparate object types in a single method call, which i went down the `MakeGenericMethod` route which made things happy.

**Comment by jeremydmiller** [comment]
What kind of signature would you want? Not sure how you'd do that w/o it being awkward

**Comment by dotnetchris** [comment]
Probably just `Store(Type type, object obj, Guid version)`

This leaves it up to the user to implement a StoreObjects method that is aware of version in terms of their own business domain. (In my domain i'm using IVersionedDocument : IDocument, i agree it would be weird to attempt to force this into anything)

The one other alternative I see would be

`StoreObjects(params Tuple<object, Guid>[] documentAndVersion)`

However this option is somewhat poor in my opinion.

**Comment by jeremydmiller** [comment]
Going to veto the 2nd option as just too ugly

The 1st sounds like a good pull request for 1.3;)

**Comment by dotnetchris** [comment]
I concur with your conclusion on option 2.

So in the database i see there is a persisted "mt_dotnet_type" string column.  I also see there's a relationship between the type name and the table name.

How do these two mix together when you have polymorphism? Suppose you have the textbook Cat : Animal, Dog : Animal.

With `Store(Type type, object document, Guid version)` I could easily write

```c#
Store(typeof(Animal), cat, Guid.Empty);
Store(typeof(Animal), dog, Guid.Empty);
```

or 

```c#
Store(typeof(IAnimal), cat, Guid.Empty);
Store(typeof(IAnimal), dog, Guid.Empty);
```

This would (seemingly) allow me to persist document hierarchies in a single pg table. For this to work right the dotnet_type would need the correct clr type that it could be deserialized.

Does Marten have any concepts related to this yet? That a single pg table could hold more than 1 dotnet type?

**Comment by jeremydmiller** [comment]
Marten already supports that w/ just a little bit of human intervention: http://jasperfx.github.io/marten/documentation/documents/advanced/hierarchies/

**Comment by jeremydmiller** [comment]
I'm shutting this down to a lack of activity.
