### ISSUE TITLE
Not possible to use Serializable transactions

### ISSUE THREAD

**Issue by tim-cools** [JasperFx/marten#616]
It is currently not possible to prevent write collision with a serializable transaction.

>             using (var session1 = store.DirtyTrackedSession(IsolationLevel.Serializable))
>             using (var session2 = store.DirtyTrackedSession(IsolationLevel.Serializable))
>             {
>                 var session1AcountA = session1.Load<Account>("A");
>                 session1AcountA.Substract(500);
> 
>                 var session2AcountA = session2.Load<Account>("A");
>                 session2AcountA.Substract(350);
> 
>                 session1.SaveChanges();
>                 session2.SaveChanges();
>             }

Previous code should throw an exception, but doesn't because the transactions is only started when SaveChanges is called...

Solution suggested by @jeremydmiller on chat: when Serializable the transaction should be opened when session is opened

**Comment by tim-cools** [comment]
@jeremydmiller 

> when Serializable the transaction should be opened when session is opened

Is this solution ok for you? I might have some time to fix this in the coming days...

**Comment by jeremydmiller** [comment]
That's the best suggestion I'd have anyway. I'll gladly take it. I think I'd try to roll your fix and whatever it takes for #624 into a 1.2.4 nuget

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/marten/pull/626
