### ISSUE TITLE
Close any open connection if any command fails

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#617]
Paranoid connection cleanup. session.Dispose() should clean things up by itself, but let's not count on users to do things right every time.

**Comment by mdissel** [comment]
So this means that after an exception you're session can't be used anymore? Properly disposing is in my opinion something an user should do..

**Comment by jeremydmiller** [comment]
If you're counting on users knowing what they're doing, sure. We can make this configurable later, but I'm rushing this one into a private build for our shop today.

**Comment by jeremydmiller** [comment]
We'll make this an opt-in behavior before 1.3 is released. It's going into a private 1.2.2 build this morning though.

**Comment by mdissel** [comment]
It's exactly the same as when they're using the IDbConnection. If they don't properly dispose it you have the same result.

**Comment by jeremydmiller** [comment]
@mdissel FFS, I'm very well aware of the design issues and I'm reacting to real production issues, not having a discussion about theory here.

**Comment by mdissel** [comment]
Yes, but this is breaking change, not catched by a full code coverage unit test.. for example:

```
try {
 ...
 session.Store(..);
} catch (Exception ex){
  Log log = new Log(..);
  session.Store(log);
}

```

will fail with this update.

**Comment by jeremydmiller** [comment]
See what I said about "opt in" behavior above.

**Comment by jeremydmiller** [comment]
@mdissel Actually, your example would work as is. The first connection would be slammed shut, but you'd be able to still use the session w/ a new transaction. Not sure it's really all that useful at that point though.

`Store()` by itself wouldn't make any database calls w/ the exception of needing to fetch a new Hilo data set.

**Comment by jeremydmiller** [comment]
Going to call this one closed for now. We'll open a separate issue later if this causes any harm.
