### ISSUE TITLE
Switching schemas ad-hoc via Advanced.Options.DatabaseSchemaName

### ISSUE THREAD

**Issue by shanomacadaemia** [JasperFx/marten#618]
Hello,

We are trying to switch schemas using the property above so that we can save documents for different clients under different schemas, much as RavenDB would allow you to specify a database name when opening a documentsession; however, this seems to only work about half of the time. I'm imagining that this is not the best solution as we are setting the schema at the DocumentStore level rather than at the Session level (which would likely affect all other open sessions). Is there any existing means of executing this or an analogue of this functionality currently?

My other idea is to lazily load a collection of document stores per client and inject them into the services dynamically.

Any assistance would be greatly appreciated.

**Comment by jeremydmiller** [comment]
@shanomacadaemia Sorry, but we haven't addressed multi-tenancy at all yet: https://github.com/JasperFx/marten/issues/435

For now, having a separate IDocumentStore per tenant is all we've got. That's not going to be super-efficient for application "warmup", but should be fine at runtime. Can you drop into that issue above and drop any ideas you might have for how it would work from a usability perspective?

**Comment by shanomacadaemia** [comment]
Thanks for the swift reply, will do
