### ISSUE TITLE
DateTime comparison in linq expression produces npgsql error

### ISSUE THREAD

**Issue by shanomacadaemia** [JasperFx/marten#619]
We are using the following code to filter rules with datetime values:

`rules =
                        await
                            session.Query<Rule>()
                                .Where(
                                    rule =>
                                        rule.ModelType == modelType &&
                                        rule.RuleType == ruleType &&
                                        (rule.BeginDate <= now && now <= rule.EndDate ||
                                        rule.BeginDate <= now && rule.EndDate == null))
                                .ToListAsync();`

However, this produces the following result:

> "Error: Marten Command Failure:\nselect d.data, d.id, d.mt_version from tenant.mt_doc_rule as d where ((((d.data ->> 'ModelType' = :arg0) and (CAST(d.data ->> 'RuleType' as integer) = :arg1)) and (tenant.mt_immutable_timestamp(d.data ->> 'BeginDate') <= :arg2)) and (tenant.mt_immutable_timestamp(d.data ->> 'EndDate') <= :arg3)) or ((tenant.mt_immutable_timestamp(d.data ->> 'BeginDate') <= :arg4) and ((tenant.mt_immutable_timestamp(d.data ->> 'EndDate')) is null))\n\n42883: function tenant.mt_immutable_timestamp(text) does not exist"

**Comment by jeremydmiller** [comment]
@shanomacadaemia What's your AutoCreateSchemaObjects setting? Are you letting Marten do things automatically, or trying to control schema creation yourself? The missing function there is something that Marten should have built out for you.

**Comment by shanomacadaemia** [comment]
That was exactly the issue, I discovered it a few moments ago. It was due to us switching the schema after creation again (errant code that should have been removed). Apologies.
