### ISSUE TITLE
Exception is thrown when first saving data with AutoCreateSchemaObjects = 'All' and then with AutoCreateSchemaObjects = 'CreateOrUpdate'

### ISSUE THREAD

**Issue by samirski** [JasperFx/marten#620]
I'm pretty much new to Marten and might be missing something here, but after spending several hours trying to figure out what is going on, decided to ask for help. The issue is that whenever I try to save some data to a database with AutoCreateSchemaObjects = 'All' using some classes, and then using the same classes but this time AutoCreateSchemaObjects = 'CreateOrUpdate' I'm getting an exception:

`The table for document type 'some type here' is different than the current schema table, but AutoCreateSchemaObjects = 'CreateOrUpdate'`

I have no idea why this exception is being thrown. The classes don't change, I even try to save the same data with no luck. Below is a test .Net Core application to showcase the issue

`using System;
using System.Collections.Generic;
using System.Linq;
using Marten;
using Marten.Schema;
using Newtonsoft.Json;

namespace TestMarten
{
    public class SomeRandomData
    {
        public List<string> MyList { get; set; } = new List<string> {"lala", "rara", "gaga"};
        public string WhatEver { get; set; } = "some data";

        public DateTime SomeDate { get; set; } = DateTime.Now;
    }

    [PropertySearching(PropertySearching.ContainmentOperator)]
    public class PersistedTestA
    {
        public int Id { get; set; }

        [DuplicateField(PgType = "varchar(50)")]
        public string ClientName { get; set; }

        [DuplicateField(PgType = "bool")]
        public bool Active { get; set; }

        public string Data { get; set; }

        [DuplicateField]
        public DateTime CreateDateUtc { get; set; }

        [DuplicateField]
        public DateTime UpdateDateUtc { get; set; }

    }

    [PropertySearching(PropertySearching.ContainmentOperator)]
    public class PersistedTestB
    {
        public int Id { get; set; }

        [DuplicateField(PgType = "varchar(50)")]
        public string Name { get; set; }

        public string Data { get; set; }

        [DuplicateField]
        public DateTime CreateDateUtc { get; set; }

        [DuplicateField]
        public DateTime UpdateDateUtc { get; set; }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            //create a store
            var store = DocumentStore.For(options =>
            {
                options.Connection("host = 127.0.0.1; database = marten; password = marten; username = marten;");
                options.AutoCreateSchemaObjects = AutoCreate.All;
            });

            //store some data in database
            var someRandomData = new SomeRandomData();

            var myObject1 = new PersistedTestA();
            myObject1.Active = true;
            myObject1.ClientName = "Some name";
            myObject1.CreateDateUtc = DateTime.UtcNow;
            myObject1.UpdateDateUtc = DateTime.UtcNow;
            myObject1.Data = JsonConvert.SerializeObject(someRandomData);

            using (var session = store.LightweightSession())
            {
                session.Store(myObject1);
                session.SaveChanges();
            }

            var myObject2 = new PersistedTestB();
            myObject2.Name = "Some name";
            myObject2.CreateDateUtc = DateTime.UtcNow;
            myObject2.UpdateDateUtc = DateTime.UtcNow;
            myObject2.Data = JsonConvert.SerializeObject(someRandomData);

            using (var session = store.LightweightSession())
            {
                session.Store(myObject2);
                session.SaveChanges();
            }

            //and now get it back
            using (var session = store.QuerySession())
            {
                var allData = session.Query<PersistedTestA>().ToList();
            }

            using (var session = store.QuerySession())
            {
                var allData = session.Query<PersistedTestB>().ToList();
            }
        }
    }
}
`

**Comment by jeremydmiller** [comment]
Can you try this? Use the `store.Schema.AssertDatabaseMatchesConfiguration();` method after you open the store as `AutoCreate.CreateOrUpdate` and paste in what Marten thinks is different? If it fails that comparison, the exception thrown should list the required delta DDL.

What version of Marten are you on by the way? This does sound like a bug we (thought we) fixed for 1.2 with comparing schema object names that Postgresql quietly truncates. If that's it, there's a workaround that's not too bad.

**Comment by samirski** [comment]
I should have mentioned that I already tried `store.Schema.AssertDatabaseMatchesConfiguration();` but could not figure why Marten thinks the schema is different. Also I'm using the later version of Marten 1.2. Here is the message after the assert:

`Configuration to Schema Validation Failed! These changes detected:

-- public.mt_transform_patch_doc Diff

CREATE OR REPLACE FUNCTION public.mt_transform_patch_doc(doc JSONB, patch JSONB) RETURNS JSONB AS $$

  var module = {export: {}};

  'use strict';

function findDeep(doc, parts){
    var element = doc;

    for (var i = 0; i < parts.length; i++){
        var child = parts[i];
        if (!element.hasOwnProperty(child) || !element[child]){
            element[child] = {};
        }

        element = element[child];
    }

    return element;
}

function locate(doc, path){
    var parts = path.split('.');

    var element, prop;

    if (parts.length > 0){
        prop = parts.pop();
        element = findDeep(doc, parts);
    }
    else {
        prop = path;
        element = doc;
    }

    return {element: element, prop: prop};
}

function setValue(doc, patch, location){
    location.element[location.prop] = patch.value;

    return doc;
}

function deleteValue(doc, patch, location){
    delete location.element[location.prop];

    return doc;
}

function duplicateValue(doc, patch, location){
    var value = location.element[location.prop];
    for (var i = 0; i < patch.targets.length; i++) {
      var copyTo = locate(doc, patch.targets[i]);
      copyTo.element[copyTo.prop] = value;
    }

    return doc;
}

function incrementValue(doc, patch, location){
    var interval = 1;
    if (patch.increment){
        interval = parseInt(patch.increment);
    }

    var existing = 0;
    if (location.element[location.prop]){
        existing = parseInt(location.element[location.prop]);
    }

    location.element[location.prop] = existing + interval;

    return doc;
}

function incrementFloat(doc, patch, location){
    var interval = 1;
    if (patch.increment){
        interval = parseFloat(patch.increment);
    }

    var existing = 0;
    if (location.element[location.prop]){
        existing = parseFloat(location.element[location.prop]);
    }

    location.element[location.prop] = existing + interval;

    return doc;
}

function appendElement(doc, patch, location){
    if (!location.element[location.prop]){
        location.element[location.prop] = [];
    }

    location.element[location.prop].push(patch.value);

    return doc;
}

function insertElement(doc, patch, location){
    if (!location.element[location.prop]){
        location.element[location.prop] = [];
    }

    var array = location.element[location.prop];

    var index = 0;
    if (patch.index){
        index = parseInt(patch.index);
    }

    array.splice(index, 0, patch.value);

    return doc;
}

function rename(doc, patch, location){
    var actual = location.element[location.prop];
    delete location.element[location.prop];

    location.element[patch.to] = actual;

    return doc;
}

function removeElement(doc, patch, location){
    var array = location.element[location.prop];
    if (!array) return doc;

    var indices = [];
    array.every(function(element, index, _array) {
      if (!deepEquals(patch.value, element)) return true;
      indices.push(index);
      return patch.action === 1;
    });

    for (var i = indices.length - 1; i > -1; i--) {
      array.splice(indices[i], 1);
    }

    return doc;
}

function deepEquals(x, y) {
    if (x === null || x === undefined || y === null || y === undefined) { return x === y; }
    if (x === y || x.valueOf() === y.valueOf()) { return true; }
    if (Array.isArray(x) && x.length !== y.length) { return false; }

    if (!(x instanceof Object)) { return false; }
    if (!(y instanceof Object)) { return false; }

    var p = Object.keys(x);
    return Object.keys(y).every(function (i) { return p.indexOf(i) !== -1; }) &&
        p.every(function (i) { return deepEquals(x[i], y[i]); });
}

var ops = {
    'set': setValue,
    'delete': deleteValue,
    'duplicate': duplicateValue,
    'increment': incrementValue,
    'increment_float': incrementFloat,
    'append': appendElement,
    'rename': rename,
    'insert': insertElement,
    'remove': removeElement
}

module.exports = function(doc, patch){
    // TODO -- throw if not a handler
    var handler = ops[patch.type];

    var location = locate(doc, patch.path);

    return handler(doc, patch, location);
}


  var func = module.exports;

  return func(doc, patch);

$$ LANGUAGE plv8 IMMUTABLE STRICT;



`

**Comment by samirski** [comment]
Hmm, I just check the database and I can't find `public.mt_transform_patch_doc` function the my database. Somehow I think this one is not created while Marten in `AutoCreate.All` mode.

**Comment by jeremydmiller** [comment]
So it's just the patch function and that's it? That's not the same problem though. The patch wouldn't be there until you actually use that, so that does make some sense. Doesn't address whatever problem you're having with that doc type though.

Can you try instead to export the patch DDL for only the doc type that's giving you fits?

See this http://jasperfx.github.io/marten/documentation/schema/migrations/

**Comment by samirski** [comment]
Sure, I'll do that later today.

**Comment by samirski** [comment]
Ok, was able to do that earlier than expected. Right now I see two files generated one with drop files and the other with the changes to the schema.

--drop
`DO LANGUAGE plpgsql $tran$
BEGIN

-- public.mt_transform_patch_doc Diff
DROP FUNCTION IF EXISTS public.mt_transform_patch_doc(JSONB, JSONB) cascade;




END;
$tran$;
`
--create/update
`DO LANGUAGE plpgsql $tran$
BEGIN

DO $$
BEGIN
    IF NOT EXISTS(
        SELECT schema_name
          FROM information_schema.schemata
          WHERE schema_name = 'public'
      )
    THEN
      EXECUTE 'CREATE SCHEMA public';
    END IF;

END
$$;

-- public.mt_transform_patch_doc Diff

CREATE OR REPLACE FUNCTION public.mt_transform_patch_doc(doc JSONB, patch JSONB) RETURNS JSONB AS $$

  var module = {export: {}};

  'use strict';

function findDeep(doc, parts){
    var element = doc;

    for (var i = 0; i < parts.length; i++){
        var child = parts[i];
        if (!element.hasOwnProperty(child) || !element[child]){
            element[child] = {};
        }

        element = element[child];
    }

    return element;
}

function locate(doc, path){
    var parts = path.split('.');

    var element, prop;

    if (parts.length > 0){
        prop = parts.pop();
        element = findDeep(doc, parts);
    }
    else {
        prop = path;
        element = doc;
    }

    return {element: element, prop: prop};
}

function setValue(doc, patch, location){
    location.element[location.prop] = patch.value;

    return doc;
}

function deleteValue(doc, patch, location){
    delete location.element[location.prop];

    return doc;
}

function duplicateValue(doc, patch, location){
    var value = location.element[location.prop];
    for (var i = 0; i < patch.targets.length; i++) {
      var copyTo = locate(doc, patch.targets[i]);
      copyTo.element[copyTo.prop] = value;
    }

    return doc;
}

function incrementValue(doc, patch, location){
    var interval = 1;
    if (patch.increment){
        interval = parseInt(patch.increment);
    }

    var existing = 0;
    if (location.element[location.prop]){
        existing = parseInt(location.element[location.prop]);
    }

    location.element[location.prop] = existing + interval;

    return doc;
}

function incrementFloat(doc, patch, location){
    var interval = 1;
    if (patch.increment){
        interval = parseFloat(patch.increment);
    }

    var existing = 0;
    if (location.element[location.prop]){
        existing = parseFloat(location.element[location.prop]);
    }

    location.element[location.prop] = existing + interval;

    return doc;
}

function appendElement(doc, patch, location){
    if (!location.element[location.prop]){
        location.element[location.prop] = [];
    }

    location.element[location.prop].push(patch.value);

    return doc;
}

function insertElement(doc, patch, location){
    if (!location.element[location.prop]){
        location.element[location.prop] = [];
    }

    var array = location.element[location.prop];

    var index = 0;
    if (patch.index){
        index = parseInt(patch.index);
    }

    array.splice(index, 0, patch.value);

    return doc;
}

function rename(doc, patch, location){
    var actual = location.element[location.prop];
    delete location.element[location.prop];

    location.element[patch.to] = actual;

    return doc;
}

function removeElement(doc, patch, location){
    var array = location.element[location.prop];
    if (!array) return doc;

    var indices = [];
    array.every(function(element, index, _array) {
      if (!deepEquals(patch.value, element)) return true;
      indices.push(index);
      return patch.action === 1;
    });

    for (var i = indices.length - 1; i > -1; i--) {
      array.splice(indices[i], 1);
    }

    return doc;
}

function deepEquals(x, y) {
    if (x === null || x === undefined || y === null || y === undefined) { return x === y; }
    if (x === y || x.valueOf() === y.valueOf()) { return true; }
    if (Array.isArray(x) && x.length !== y.length) { return false; }

    if (!(x instanceof Object)) { return false; }
    if (!(y instanceof Object)) { return false; }

    var p = Object.keys(x);
    return Object.keys(y).every(function (i) { return p.indexOf(i) !== -1; }) &&
        p.every(function (i) { return deepEquals(x[i], y[i]); });
}

var ops = {
    'set': setValue,
    'delete': deleteValue,
    'duplicate': duplicateValue,
    'increment': incrementValue,
    'increment_float': incrementFloat,
    'append': appendElement,
    'rename': rename,
    'insert': insertElement,
    'remove': removeElement
}

module.exports = function(doc, patch){
    // TODO -- throw if not a handler
    var handler = ops[patch.type];

    var location = locate(doc, patch.path);

    return handler(doc, patch, location);
}


  var func = module.exports;

  return func(doc, patch);

$$ LANGUAGE plv8 IMMUTABLE STRICT;





END;
$tran$;
`

This is all I'm seeing right now.

**Comment by samirski** [comment]
Ok, after doing some debugging I've found the issue. One of my classes that I'm persisting to the database has a type `bool` property. This however is being returned back from the database as type `boolean`. Same type but being compared incorrectly: `bool != boolean`.

`protected bool Equals(TableColumn other)
        {
            return string.Equals(Name, other.Name) &&
                   string.Equals(TypeMappings.ConvertSynonyms(RawType()), TypeMappings.ConvertSynonyms(other.RawType()));
        }`

**Comment by jeremydmiller** [comment]
@samirski You had set the type of a duplicated field manually to "bool"? That does make sense.

It's going to be a one line code fix + a test if you'd be up for a PR for that: https://github.com/JasperFx/marten/blob/master/src/Marten/Util/TypeMappings.cs#L48-L50

Or just change your code to this:

```
    // Marten *can* derive the pg type for a boolean by itself
    [DuplicateField]
    public bool Active { get; set; }
```

**Comment by samirski** [comment]
@jeremydmiller Thanks, last night while in bed I came to the the same conclusion :).  The issue indeed not because of the property type but the type I was setting on the `DuplicateField`. The reason why I was setting it manually is because I'm coming from SqlServer where `boolean `data type does not exists as you know. And thus to make sure everything works as expected put the type explicitly and forgot about it. To my defense `bool `is a valid alias for `boolean`. Thanks and sorry for taking your time to look into this!

**Comment by jeremydmiller** [comment]
Nevermind that, I'm into the code this morning for something else and I'll address it real quick.
