### ISSUE TITLE
Async Daemon Projection Rebuild breaks when seq_id of event is over 101 greater than last event seq_id

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#624]
So this is a strange issue. I have been able to consistently reproduce it. If I have multiple events of the same type in the `mt_events` table, and the `seq_id` of one of those events is 101 greater than the `seq_id` of a previous event of that same type. The streams of that type, starting with the one that was 101 greater than the previous, will left out of the call to `ApplyAsync` (from the `IProjection` interface)

Ex. that fails
```
seq_id | type
8      | user_created
109    | user_created     -> this one will not be passed to `ApplyAsync`
```

Ex. that works
```
seq_id | type
8      | user_created
108    | user_created   
```

**Comment by ericgreenmix** [comment]
@jeremydmiller did you mean to close #632 instead of #624 with 88cd64b ?

**Comment by jeremydmiller** [comment]
@ericgreenmix No, I was pushing that branch up to deal w/ #624. I had been trying to work through a couple different daemon issues at one time. I'm going to let you close #632 if you're okay with the explanation. Or add the "docs" tag and make it a "go make the documentation better" issue

**Comment by jeremydmiller** [comment]
This will be in 1.2.4
