### ISSUE TITLE
Patch Append - possible to treat list as a set?

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#629]
The [docs](http://jasperfx.github.io/marten/documentation/documents/advanced/patch_api/) explain how you can patch a document to append an element to a child array.

Is there some way to treat the child array as a set, such that the element will only be added if it's not already there? The aim is to prevent duplicates being added to the array.

**Comment by jeremydmiller** [comment]
@cocowalla Not today, but that wouldn't be a big task to add that. I'd make that an all new patching operation to make the behavior more apparent, and to not break existing code.

The patching is actually done w/ Javascript running against the JSON data, so it's pretty easy to modify.

**Comment by jamesfarrer** [comment]
@jeremydmiller  this also looks a simple issue. what are you preferred names (I was thinking it should cover both append and insert?)

**Comment by jeremydmiller** [comment]
@jamesfarrer I honestly don't know. @cocowalla Do you have any suggestions for what would make sense for that?

**Comment by cocowalla** [comment]
How about `SetAdd`?

**Comment by jamesfarrer** [comment]
Better to keep Append & Insert in the command imo. Two options :-

`AppendAsSet`, `InsertAsSet` or `AppendIfNotExists` `InsertIfNotExists`

**Comment by jeremydmiller** [comment]
I like `AppendIfNotExists` & `InsertIfNotExists`

**Comment by jeremydmiller** [comment]
@jamesfarrer If I end up pushing the 1.5 nuget before this gets in, I can just turn around and do this one in 1.6

**Comment by jeremydmiller** [comment]
@jamesfarrer Reminded me that this one's done;)
