### ISSUE TITLE
Unable to use Query<T1>().Include<T2>() when both T1 and T2 use soft deletes

### ISSUE THREAD

**Issue by barryhagan** [JasperFx/marten#631]
If both types used in a Marten LINQ .Include() query are configured to use soft deletes, running an .Include() query will result in this exception:

[PostgresException (0x80004005): 42702: column reference "mt_deleted" is ambiguous]

It looks like the where clause to handle soft deletes is not scoped properly as `d.mt_deleted`.  Instead, you get `where (mt_deleted = False)` in the generated command, causing the ambiguous table reference.

**Comment by jeremydmiller** [comment]
Got it. Do you want to take this one on, or let me get it sometime this week?

**Comment by barryhagan** [comment]
I'm not completely familiar with that code yet, so I'm not sure if it is as simple as adding the "d." prefix.  Please take a look at the commit in my fork and I can do a PR if that is all it is.

**Comment by jeremydmiller** [comment]
Gotcha. I'm looking at this one now.

**Comment by jeremydmiller** [comment]
So it wasn't *that* bad to fix this, but it brings up another point I hadn't thought about at all. If you do an Include() against a related, soft-deleted document, Marten isn't today filtering out *those* deleted documents.

Not sure if I think that behavior should be that way or just return the document if it exists period.

Any thoughts about that one?

**Comment by jeremydmiller** [comment]
This will be in 1.2.5 later today or maybe tomorrow

**Comment by jeremydmiller** [comment]
Correction, it'll be in 1.2.4

**Comment by barryhagan** [comment]
I guess my expectation would be that soft deleted includes would be filtered the same way as the primary docs in the query.  i.e. the IsDeleted or MaybeDeleted clauses would flow through to the includes.

I like the way that soft deleted docs are invisible unless you supply IsDeleted or MaybeDeleted, so it would be odd to get back soft deleted includes.

**Comment by jeremydmiller** [comment]
Would you mind then opening a separate issue for that? That unfortunately is a more involved fix.

**Comment by barryhagan** [comment]
will do.
