### ISSUE TITLE
AsyncDaemon Projection Rebuild - Using Query on new document before SaveChanges is called returns null

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#632]
`session.Load<MyDoc>(123)` works. `session.Query<MyDoc>(_ => _.Id == 123).FirstOrDefault()` returns null. Adding failing test..

**Comment by ericgreenmix** [comment]
Test was added to my currently open PR #625

**Comment by jeremydmiller** [comment]
@ericgreenmix, 

See my comments in the code below. I think you're getting tripped up on how Marten uses the identity map. When you run a Linq query, Marten **first** queries the database, then as it iterates over the reader it tries to resolve known documents through the identity map where they already exist. In your case here, Marten hasn't persisted that document yet, so the Linq query returns no records.



```
        public void Apply(ProjectStarted @event, IDocumentSession session)
        {
            var newId = Guid.NewGuid();
            var model = new TestLoadAndQueryProjection();
            model.Id = newId;
            model.ProjectCount++;
            session.Store(model);

            var loadModel = session.Load<TestLoadAndQueryProjection>(newId);
            loadModel.ProjectCount++;
            session.Store(loadModel);

            // If you insert a session.SaveChanges() here, this test passes

            // This query can't work because nothing has been persisted yet.
            var queryModel = session.Query<TestLoadAndQueryProjection>().Where(_ => _.Id == newId).FirstOrDefault();
            if (queryModel != null)
            {
                queryModel.ProjectCount++;
                session.Store(queryModel);
            }
        }

```

IMO, this isn't a bug. The docs on the identity map could be improved to make this behavior clearer.

**Comment by ericgreenmix** [comment]
Ah, that makes sense. Thank you for explaining that. It was confusion on my part on how the Identity Map is being applied.
