### ISSUE TITLE
how can this be used in .NET 4.5?

### ISSUE THREAD

**Issue by ChangePlaces** [JasperFx/marten#637]
Is this compatible with Mono?

**Comment by jeremydmiller** [comment]
Marten only supports .Net 4.6 or Netstandard. I'd think you'd be better off going to CoreCLR than trying Mono, but it should work w/ 4.6.

**Comment by ChangePlaces** [comment]
Unfortunately Quartz.net is nowhere near ready for core

**Comment by TheAngryByrd** [comment]
@ChangePlaces What version of mono are you using? [As of Mono 4.4 they can compile against TargetFrameworkVersion 4.6.1](http://www.mono-project.com/docs/about-mono/releases/4.4.0/).  I've used Marten on Mono 4.6.3 and seems to work fine.
