### ISSUE TITLE
Prepare package and publish to NuGet

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/marten#64]

**Comment by jeremydmiller** [comment]
Yeah, I know. I want to stand up a CI build first. I'm going to make the excuse that the person that I need to give me access to that server to get Postgresql setup is out this week;)

Early next week I think.

**Comment by jeffdoolittle** [comment]
sounds good, no rush just one of those things that will probably help with early adoption and testing.

**Comment by jmkelly** [comment]
I've setup on build and deploy to nuget on Travis CI.  Feel free to butcher since we are doing the same things

https://github.com/YoloDev/elephanet/blob/master/.travis.yml
https://github.com/YoloDev/elephanet/blob/master/deploy.sh

**Comment by jeremydmiller** [comment]
@jmkelly I appreciate that, but we've got a TeamCity server I can use & I'll use Paket for now.

Hey, I'm sorry that I completely dropped the ball on chatting with you about this & elephanet. Would you be up for talking early next week? Just catch me on Gitter if you want.

**Comment by jeremydmiller** [comment]
Done.
