### ISSUE TITLE
Using Marten with existing tables and schema for CRUD operations

### ISSUE THREAD

**Issue by ewcindia** [JasperFx/marten#641]
We are trying to integrate Marten in one of our existing project, where we have migrated from Azure DocumentDB to Postgres Document Database. We are trying integration but facing issues as our tables that are already created with a combination of relational and document structures. We have already seen the Pluralsight training "Getting Started with .NET Document Databases Using Marten". However, we have some specific issues where we need guidance.

We have a table with 6 columns:
1) table_id (bigserial) {Primary Key}
2) foreign_table_id (bigserial) {Foreign Key}
3) item_count (int)
4) data (jsonb)
5) creation_date (timestamp [ (p) ] [ without time zone ])
6) search (tsvector)

We have different forms that are used to update these specific fields for example one form to update 'data' field only and another form to update 'item_count'. We have created separate classes (a. Store, b. Item) to handle these forms. However, when we are trying to insert records using Store class and lightweight session (as mentioned in your training) Marten generates a new table named 'mt_doc_store' instead of using our existing table 'store'. Additionally, we are not able to use primary key for these CRUD operations. 

However, when we use Querysession for fetching data using a Postgres Function, it is working fine. But if we try to use it for Update/Delete it requires an ID field in jsonb data as well. In this case our Primary key is not utilized. 

Do we need the primary key to be stored in jsonb data. Also what will be the impact on foreign key in this case?

Please advise on how to use Marten with our existing tables and schema for CRUD operations. We want to use the power of both relational and document structures, so please consider that in your recommendation.

**Comment by jeremydmiller** [comment]
@ewcindia Sorry, but that's just not going to work. Marten cannot be used against tables that don't conform to Marten's schema. You're going to have to migrate your data.

And one way or another, you're going to need either an `Id` or `id` Field/Property or use the `[Identity]` attribute so that Marten knows what the primary key should be.

See this for the identity stuff on Marten: http://jasperfx.github.io/marten/documentation/documents/identity/

And this for using FK's: http://jasperfx.github.io/marten/documentation/documents/customizing/foreign_keys/

**Comment by ewcindia** [comment]
Thanks Jeremy. Will try to restructure the project to fit it in Marten.

 

Warm Regards,

Gourav Ladha

**Comment by jeremydmiller** [comment]
@ewcindia Can I close this one?

**Comment by ewcindia** [comment]
Sure.

 

Warm Regards,

Gourav Ladha

**Comment by jeremydmiller** [comment]
No new activity, so I'm closing.
