### ISSUE TITLE
SelectMany only supports arrays - not generic lists

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#646]
Before I attempt to tackle adding support for `SelectMany` to work with generic lists, is there a reason why only arrays are currently supported?

**Comment by jeremydmiller** [comment]
Check the json structure of your document in the db. Bet it's an issue w/ serialization and not the Linq support per se

**Comment by cocowalla** [comment]
On mobile now, but the issue is that the code checks for the element type using a method that only works for arrays - not generic lists. It looked straightforward to add support for generic lists by simply checking for such lists and getting the generic type parameter as the element type. Because it looked simple, I thought I should ask if there was a reason first.

**Comment by jeremydmiller** [comment]
@cocowalla Gotcha. I used the built in `GetElementType()` on TypeInfo? There might be an appropriate extension method in Baseline already for that. If not, there's definitely a working version of that in the StructureMap code I could dig up.

**Comment by cocowalla** [comment]
Yes, it looks like `TypeExtensions.DeriveElementType` from Baseline can be used as a drop-in replacement for the existing call to `GetElementType`

**Comment by jeremydmiller** [comment]
@cocowalla Are you addressing this? I'm in the codebase this morning and I can make the change if you want, but I never turn down bug fix pull requests;)

**Comment by cocowalla** [comment]
I'm happy to do this - is a single test OK, just copying one of the existing tests but using an `IList` instead of an array??

**Comment by jeremydmiller** [comment]
Sounds good to me, and that's all I would have done anyway;)

**Comment by cocowalla** [comment]
Great, I'll try to submit a PR tonight then

**Comment by cocowalla** [comment]
PR sent!

**Comment by jeremydmiller** [comment]
Fixed by #652. Thanks!
