### ISSUE TITLE
Update and Delete in the same session for docs with optimistic concurrency throws

### ISSUE THREAD

**Issue by barryhagan** [JasperFx/marten#651]
If I attempt to delete one document and update another in the same session, and the updated doc uses optimistic concurrency, a currency exception is always thrown attempting to save the changes.

Down in the Postprocess callback, the reader.Read() is false, presumably due to the delete command (or update command in case of SoftDeleted).

See the currently failing test added here:
https://github.com/barryhagan/marten/commit/d8b8c1a987b6a5cc2059473ded34410e29bf50e4

**Comment by jeremydmiller** [comment]
Good timing, 'cause I'm working on a bugfix release right now. I'll look at it in a bit.

**Comment by jeremydmiller** [comment]
@barryhagan Ugh, I think this is more systematic than this. I think it's doing an upsert on an optimistic concurrency enabled document and any other kind of operation going first in the batch that doesn't return a record set. The fix might not be that bad, but it's a bigger problem:(
