### ISSUE TITLE
Is that possible to load document by using Interface and ID?

### ISSUE THREAD

**Issue by cchongchong** [JasperFx/marten#668]
Hi There,

We're using RavenDB before and trying to switch to PostgreSQL with Marten. But seems Marten Session Load only supports specify the type first to map to the specific table name.

Since ID can contain collection name (the type name), is that possible to load the document only by ID?

An alternative solution is to allow the developer to pass both the type and ID to Load method.

Which one do you think it's better and can be done?

Regards,
Chongzhao

**Comment by jeremydmiller** [comment]
I've never been wild about the old Raven "collection/{id}" pattern. Why wouldn't you know the document type collection you're looking for in the first place?

Having an overload that does it by `Load(Type, id)` isn't that big of a deal.

**Comment by cchongchong** [comment]
@jeremydmiller Thank you for your quick response!
Yes, the new method `Load(Type, id)` is what we're using right now, but it would be better if Marten can support this by default. Because our implementation is using reflection to call the generic Load method which is not good, but this can be done in Marten much easier.

**Comment by jeremydmiller** [comment]
@cchongchong Sounds like a good pull request;)

**Comment by cchongchong** [comment]
@jeremydmiller Thank you!
BTW, would you mind let us know which ID conversion you suggest? We're still using "collection/{id}" because this can let us know the collection name in the first time which is useful.

**Comment by jeremydmiller** [comment]
That depends on your usage. Most of us use the sequential Guid, other users are using the Hilo sequence
