### ISSUE TITLE
BaseLine 1.2 and Marten 1.2.5 causes typeloadexception when using AsyncProjections

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#671]
When attempting to execute this piece of code

`var daemon = docStore.BuildProjectionDaemon();`

This blows up with a `System.TypeLoadException` with the current message.

`Could not load type 'Baseline.TimeSpanExtensions' from assembly 'Baseline, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'.`

I'm using Marten 1.2.5, Baseline 1.2 and Im running on .net 4.6.2. Downgrading Baseline to 1.1 solves this.

**Comment by jeremydmiller** [comment]
I'm bumping Marten to Baseline 1.2 now. The 1.3 nuget later today will have that change.
