### ISSUE TITLE
Multiple calls to eventstore append with different expected version causes exception

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#673]
Lets say that I want to use the eventstore and the optimistic concurrency with `expected_version`.

I would expect to do be able to do something like this:

```
var state = session.Events.FetchStreamState(streamId);
// ... do some stuff 
var expectedVersion = state.Version + 1;
session.Events.Append(streamId, expectedVersion, new WhateverEvent());
// ... do some more stuff
expectedVersion += 1;
session.Events.Append(streamId, expectedVersion, new WhateverEvent());
session.SaveChanges()
```

However this seems to blow up in my face because the `expected_version` does not match. I noticed that when you call Append with `expected_version` it adds an `AssertEventStreamMaxEventId` storage operation. And when you call Append a second time for the same stream it just adds another one instead of updating or removing the old one. 

Now, I understand the reasoning that I could just have called
```
session.Events.Append(streamId, state.Version + 2, new WhateverEvent(), new WhateverEvent());
```
but then I have to create my own unit of work implementation to collect all events that I produce before adding them to Martens unit of work...which feels a bit backwards.

I had a look at maybe just dropping the whole `expected_version` part and just adding my own `AssertEventStreamMaxEventId` storage operation. But in order to do that it seems that I have to cast the `session.PendingChanges` to a real `UnitOfWork` and then I need to somehow get a hold of the schema name for the events table unless I want to hard-code that name...and this just feels wrong.

Should I implement my own unit of work or is this a case that you think that Marten should handle?

**Comment by wastaz** [comment]
Looking at the code it seems like I should be able to do something like

```
var state = session.Events.FetchStreamState(streamId);

session.Events.Append(streamId, new WhateveEvent());
session.Events.Append(streamId, new WhateverEvent());

var expectedVersion = state.Version + session.PendingChanges.Streams().First(s => s.Id == streamId).Events.Count();

session.Append(streamId, expectedVersion);
session.SaveChanges();
```

It feels a bit weird though, and it also feels like I might be writing fragile code relying on implementation details?

**Comment by jeremydmiller** [comment]
@wastaz I'm looking into this one right now. Think it'll have to be in a 1.4 nuget later this week.
