### ISSUE TITLE
Images dont work in the documentation

### ISSUE THREAD

**Issue by ax4413** [JasperFx/marten#674]
All of your images seem to be using the wrong relative path, because none of the images in the docs work.

**Comment by jeremydmiller** [comment]
"works on my box" -- there's only the one image on the home page and I verified that it's all there. Are you talking about some kind of missing code sample?

**Comment by ax4413** [comment]
Thanks for the documentation it's looking great. I was in a hury earlier so I didn't really validate or report accurately in the bug. I can see that indeed most of the images are present, there are however missing images on the Postgres for sql server users section, but I hadn't realised that it was still under construction. An example of a missing image can be found on the types page http://jasperfx.github.io/marten/documentation/postgres/types/ 

Thanks for the great work

Steve




On Fri, Feb 10, 2017 at 1:12 PM +0000, "Jeremy D. Miller" <notifications@github.com> wrote:












"works on my box" -- there's only the one image on the home page and I verified that it's all there. Are you talking about some kind of missing code sample?

**Comment by jeremydmiller** [comment]
Yeah, I'm not gonna worry about this one for now.
