### ISSUE TITLE
AggregationLookupStrategy.UsePrivateApply causes typename not to be written in mt_streams

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#677]
When using the private apply strategy with the following configuration 

```
_.Events.UseAggregatorLookup(AggregationLookupStrategy.UsePrivateApply);
```

Then the type name of the aggregate type is not written in `mt_streams`. This causes any call to `FetchStreamState` or `FetchStreamStateAsync` to explode with an `InvalidCastException` since it doesnt check for nulls properly in that column.

I have created a PR with the fix for this bug: https://github.com/JasperFx/marten/pull/676

**Comment by jeremydmiller** [comment]
Fixed by #676
