### ISSUE TITLE
Event tables are not created before an eventstream is saved.

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#681]
If you attempt to read from the eventstore part of marten

```
session.Events.AggregateStreamAsync<Aggregate>(Guid.NewGuid());
```

Then you get an exception saying that `mt_events` does not exist (which it doesnt if its a new database). If you store an event in it, then the tables are created. But this means that in order to guarantee that these tables exists we must always store a random event at program startup?

**Comment by jeremydmiller** [comment]
@wastaz,

Dunno, this passes for me in master:

```

    public class Bug_681_event_tables_not_created_on_demand_from_state_fetches : IntegratedFixture
    {
        [Fact]
        public void fetch_first_time_do_not_blow_up()
        {
            theStore.Advanced.Clean.CompletelyRemoveAll();

            using (var session = theStore.OpenSession())
            {
                // really just seeing this not blow up
                session.Events.AggregateStreamAsync<QuestParty>(Guid.NewGuid()).ShouldNotBeNull();
            }
        }
    }
```

Do you have something else going on? What's your DocumentStore setup look like? Is it set to AutoCreate?

**Comment by jeremydmiller** [comment]
I'm closing this just out of housekeeping.
