### ISSUE TITLE
ASP.NET MVC/Core Identity Provider

### ISSUE THREAD

**Issue by eSPiYa** [JasperFx/marten#683]
Is there or will there be an ASP.NET MVC/Core Identity Provider? I found another project but it looks like it is inactive for around 6 months now and it is still in alpha.

**Comment by mysticmind** [comment]
@eSPiYa You could look at any Ravendb implementation and do a similar implementation using Marten. Have a look at https://github.com/tugberkugurlu/AspNet.Identity.RavenDB or https://github.com/terrasynq/RavenDB.AspNetCore.Identity. In summary, you will need to define your entities and implement IUserStore.

**Comment by eSPiYa** [comment]
@mysticmind Will definitely do that. I have experience implementing a custom Identity before but I wasn't able to cover everything because I don't need those things before. It might happen again if case I'm going to build one for Marten. I don't have experience in spear-heading open source projects, mostly small contribution on things.

Currently using the "Microsoft.AspNet.Identity.Marten" library name and project namespace. I don't know if it is correct or not.

**Comment by eSPiYa** [comment]
@mysticmind Will definitely do that. I have experience implementing a custom Identity before but I wasn't able to cover everything because I don't need those things before. It might happen again if case I'm going to build one for Marten. I don't have experience in spear-heading open source projects, mostly small contribution on things.

Currently using the "Microsoft.AspNet.Identity.Marten" library name and project namespace. I don't know if it is correct or not.

**Comment by eSPiYa** [comment]
Sorry, clicked the wrong button. LOL

Anyway, I'm also considering forking this project: https://github.com/kedarvaidya/AspNetCore.Identity.Marten

**Comment by mysticmind** [comment]
@eSPiYa Iam happy to help you. If you are forking https://github.com/kedarvaidya/AspNetCore.Identity.Marten, you don't need to setup a new namespace etc, keep the ones "as is" in the source project. You can change the code to work with latest Marten and sent a Pull Request to kedarvaidya.

You can give it a shot to make changes by forking the indicated project. If you can wait for 2-3days, I can put together one for you using the latest Marten version or can fork the same project.

**Comment by eSPiYa** [comment]
@mysticmind Thanks! Not really rushing this because I'm still in the middle of learning Marten. Just want some kind of project to test it out, and making some useful library/tools is like hitting two birds with one stone.

Already forked the project and his codes are really decent. I have lots learned from reading it, though there is no instruction on how to make the sample project work so it took me a lot of time change things to somehow make it run.

**Comment by jeremydmiller** [comment]
Since there is an ongoing project for this one, I'm going to call the issue here closed.
