### ISSUE TITLE
Buffer pooling for large objects

### ISSUE THREAD

**Issue by Scooletz** [JasperFx/marten#684]
Currently, when a big object is serialized, `CharArrayTextWriter` responsible for `char[]` pooling will be extended to the length needed to serialize an object. When a big buffer is needed from time to time this resizing might be not optimal, allocating to much memory which later will be used to serialize small objects.

There are various ways that can be used to address this:
- issue a PR against `npgsql` allowing some kind of chaining of `CharArrayTextWriter`. Then, when a big object was written, it would span across multiple writers
- create pools of different buffer sizes. When resizing, instead of allocating a `new char[]`, `CharArrayTextWriter` would use a buffer from "a bigger pool"
- skip using pooling for big objects
- enable to opt out from pooling for specific scenarios

This is a follow up issue to this https://github.com/JasperFx/marten/issues/680#issuecomment-280756950

**Comment by jeremydmiller** [comment]
Closed by #680
