### ISSUE TITLE
StartStream in EventStore does not verify that stream does not exist

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#685]
If I use

```
session.Events.StartStream<Aggregate>(Guid.NewGuid(), new Event());
```

Then I would expect this to throw some sort of optimistic concurrency exception if a stream already exists with the provided stream id. After all, I am calling a method called `StartStream`, not `Append`. But currently this seems to work similar to `Append`.

**Comment by jeremydmiller** [comment]
For 2.0, I can see this one being fine.
