### ISSUE TITLE
Suggestion: Supporting events as interfaces?

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#686]
This is mainly meant as a probing discussion item to see what you would think of adding a feature like this.

Currently if you have an event like this

```
public interface IPickedUpWeapon {
    string WeaponType { get; }
}
public class PickedUpWeapon : IPickedUpWeapon {
   public string WeaponType { get; set; }
}
```

then the aggregate still needs to refer to the concrete type in order for `AggregateAsync` to apply it properly

```
public class AdventurerAggregate {
    // .....
    public Apply(IPickedUpWeapon e) {
        // This will not be called 
    }
}
```

Im currently using Jil as a serializer, and from what I can see Jil has no problems with serializing and deserializing interfaces (and doesnt need to store any additional type information in the events to do so), but of course then Marten wont actually apply the events even if they serialize/deserialize properly.

One problem with allowing for interfaces instead of only concrete classes would be if an event implements several interfaces.

```
public interface IPickedUpWeapon { string WeaponType { get; } }
public interface IPickedUpArmor { string ArmorType { get; } }
public interface IPickedUpWeaponAndArmor : IPickedUpWeapon, IPickedUpArmor { }
```

then applying this event to an aggregate with handlers for some combination of the events would be a bit weird. I think that it would be ok to call all matching appliers with the event and just document that the order that they are called in is undefined and should not be relied on. (If ordering for this case is really necessary for an aggregate it could probably be done by decorating the apply methods with interfaces or adding some sort of marker interface, but I dont really think that it should be necessary).

**Comment by cylwit** [comment]
To add some context to this, we're currently using MassTransit for our messaging fabric which encourages the use of interfaces as message contracts, naturally including events.  So, we currently expose a common "message contracts" library per (sub)domain containing all of the [read only] interfaces for commands & events, and only implement concrete classes where we plan to publish/send new messages.  It would feel natural for us to be able to read out the events as [read only] interfaces from the event store (primarily thinking of async projections here) the same way we would receive them on the bus, instead of needing to share concrete implementations with setters, which breaks the convention that we're currently using (impl where creating new events).

**Comment by jeffdoolittle** [comment]
same issue here regarding MassTransit

**Comment by wastaz** [comment]
A year later I am less convinced about this being a good idea (and more convinced that maybe MassTransit is the weird one for using interfaces as they do).

**Comment by oskardudycz** [comment]
@wastaz could you elaborate and share some lessons learned?

**Comment by jeffdoolittle** [comment]
I would questions whether events in the Marten event stream should be directly put on a messaging wire. These are different models that I believe are better served by encapsulation. This would require lots of mapping logic to maintain the separation, but ultimately I think that's a price that's worth paying for keeping things encapsulated. Just my $0.02.

**Comment by wastaz** [comment]
@oskardudycz Sure thing. Ill try to do a braindump and we'll see what comes out ;)

1) The exact reason that @jeffdoolittle states. It sounds very nice in the beginning to just publish all eventsourced messages on the eventbus (both words starts with "event" after all!). But it turns out (who would have thunk) that this sometimes leads to exposing "private" state to other domains. While this might not always be a problem (apart from sending around a lot of information that didnt need to be sent around in the first place), in some cases it does lead to some unwanted or (as when GDPR is involved) extremely problematic situations. As such, just publishing all eventsourced events to the bus has turned out for us to be a pretty bad default, and we have now introduced a non-optional mapping layer in our internal framework for integrating these things (which can of course still choose to not do any mapping at all for some event types, the amount of mapping code we needed was much less than we first thought). This also makes it easier to change your events later (its gonna happen) and not break downstream consumers.

2) Serialization woes. While Jil turned out to be able to handle serialization of interfaces pretty fine without adding unnecessary type information and other stuff, that is not the case for all serializers out there. Json.net occasionally adds a lot of typenames and other cruft and other fun stuff you might not want. We no longer use Jil for serialization and went back to json.net. Mainly because no matter what you do you still end up with json.net in your project and maintaining one serializer is easier than maintaining two (and also we had some other issues with Jil serialization of some stuff). No one likes fighting with serialization issues.

The one thing that would be nice would have been event immutability. While it should be possible to do immutable events in marten as it is today...C# is just such an annoying language to work with when it comes to immutability. So in the end the most pragmatic way of handling things is "gentleman immutability" anyway. Maybe if we finally get records in C# somewhere around C#9 those could be used instead, but yea.

**Comment by mysticmind** [comment]
Reading through this issue thread, I am deriving a conclusion that there is nothing required to be done at Marten end.  Closing the same.
