### ISSUE TITLE
Support for "contains" in a linq expression passed into where clause (query across documents, not child elements)

### ISSUE THREAD

**Issue by maxsolender** [JasperFx/marten#693]
I would like to do the following:

using (var session = _documentStore.LightweightSession())
{
      List<string> jobIds = new List<String> { "id1", "id2" };
      IList<T> resultList = await session.Query<T>().Where(
                    j => j.UserId == userId && jobIds.Contains(j.JobId)).ToListAsync()
}
 
The Marten driver throws an exception saying this it is not supported.    Will this be supported in the future?    The only work around I can do is to expand the jobids into a series of  (jobid = this OR jobid = that), but I don't want to do that.

**Comment by jeremydmiller** [comment]
@maxsolender Try the `IsOneOf()` mechanism for querying. Search for it in this one: http://jasperfx.github.io/marten/documentation/documents/querying/linq/

**Comment by jeremydmiller** [comment]
@maxsolender Hey, I don't think we'll ever support the query above. I know you've got the other issue open for IsOneOf() problems, but I need more info from you on that one.

**Comment by maxsolender** [comment]
I was able to get this one working by using "IsOneOf".    Sorry for not replying.   Thanks!
