### ISSUE TITLE
Non typed stream?

### ISSUE THREAD

**Issue by danielwertheim** [JasperFx/marten#694]
When starting the stream we are required to tie it to a certain type. Would be nice to be able to pass in a custom string and there by classifying (naming) the stream and not tie it to a certain concrete type/model.

Or is it really used for anything internally? On the way out, I get that a type could be needed, when e.g. consuming a stream with snapshots, but then I will be needed to specify a target type anyway, no?

That would allow us to use the stream state for versioning, meta etc. and consume the related events as pure events to a stream and not care about models.

Alternatively, not require a certain type being stored and the be able to pass custom meta that can be attached to the stream and acquired via FetchStreamState

**Comment by jeremydmiller** [comment]
@danielwertheim You don't **have** to express the aggregate type on a Stream. We might be missing some overloads, but you can just use `AppendEvents` and it'll create a stream on the fly if it's missing. We've talked occasionally about eliminating the StartStream() differentiation altogether.

**Comment by danielwertheim** [comment]
Yes, I have noticed that you can use Append without starting it. As long as
StartStream exists, that feels a bit "weird". But if Start is going away,
then I'll use Append.

Guess there's no real overhead for it to check for stream existence?

**Comment by jeremydmiller** [comment]
A *tiny* optimization if you're doing inline aggregated projections so that it doesn't have to pull down the existing aggregate before doing updates. That's all.

**Comment by danielwertheim** [comment]
One thing that a "type/name" could be used for, could be to search/filter
on certain types of streams. But of course that can be tracked in separate
model.

But if in the API of Marten, then it would be great if that would not be
tied to a hard type.

**Comment by jeremydmiller** [comment]
It's just a string in the database. Have another user wanting Marten to be more like GES and the way that they let you specify meaningful stream id's so you can key off that in projections or event processing. I'm wanting to push for us to just use the stream_type and maybe some kind of headers structure to do that kind of thing.

**Comment by jeremydmiller** [comment]
And I agree. This would be a quick hit PR if you're up for that.

**Comment by danielwertheim** [comment]
How would you like to handle the existance of `EventStream.AggregateType:Type`? https://github.com/JasperFx/marten/blob/master/src/Marten/Events/EventStream.cs#L29

Replace with string is breaking. Adding a sibbling `AggregateTypeName:string` next to it can potentially work and then use that here: https://github.com/JasperFx/marten/blob/master/src/Marten/Events/EventStreamAppender.cs#L27

`AggregateType:Type` would take precedence then I guess.

It might look a bit weird though...

**Comment by jeremydmiller** [comment]
@danielwertheim Sorry I dropped the ball on this one. I think that longer term in 2.0, we eliminate the AggregateType thing altogether because nobody seems to like it and it never turned out to be useful in the ways I thought it would. For 2.0, what if we have an optional "StreamType" field that you can use for whatever you want, but it's never required.

**Comment by danielwertheim** [comment]
I think it's a good decision to do it "right" in 2.0 instead.

Now, the "StreamType", would that be a Type or String?

What I'm after is a String that names/classifies/types the stream to "something". That "Something" is left to the user. There can of course be convenient extension methods etc for those that want Types.

**Comment by jeremydmiller** [comment]
Wasn't really breaking, just making the aggregate type optional. Closed by https://github.com/JasperFx/marten/commit/acf834660b77e23599149b32d4f7a3e4f1f672d7
