### ISSUE TITLE
Aggregator and AggregatorApplyPrivate, Generic method cache?

### ISSUE THREAD

**Issue by danielwertheim** [JasperFx/marten#696]
How is the access path to the constructors in these classes? Haven't investigated but if many times, a simple improvement could be to use a simple Generic method cache for the extracted methods instead of using reflection each time or am I missing something?

Talking about:
https://github.com/JasperFx/marten/blob/master/src/Marten/Events/Projections/Aggregator.cs#L17

https://github.com/JasperFx/marten/blob/master/src/Marten/Events/Projections/AggregatorApplyPrivate.cs#L11

The solution I mean would be using something like this:

```csharp
    public static class AggregatorMethods
    {
        public const string ApplyMethodName = "Apply";
    }

    internal static class AggregatorMethodsCacheFor<T> where T : class
    {
        internal static readonly MethodInfo[] Methods = typeof(T)
            .GetMethods()
            .Where(x => x.Name == AggregatorMethods.ApplyMethodName && x.GetParameters().Length == 1)
            .ToArray();
    }

    internal static class AggregatorPrivateMethodsCacheFor<T> where T : class
    {
        internal static readonly MethodInfo[] Methods = typeof(T)
            .GetMethods(BindingFlags.Instance | BindingFlags.NonPublic)
            .Where(x => x.Name == AggregatorMethods.ApplyMethodName && x.GetParameters().Length == 1)
            .ToArray();
    }
```

Which in the constructor would be used:

```csharp
public Aggregator() : this(AggregatorMethodsCacheFor<T>.Methods) { }
```

Did some quick measurements using Benchmark .NET and the improvement is really tiny so probably not worth it even though it's a small change:

 |                  Method | Count |            Mean |      StdDev |          Median |
 |------------------------ |------ |---------------- |------------ |---------------- |
 |         **UsingReflection** |     **1** |   **1,915.3307 ns** |   **3.4477 ns** |   **1,914.6578 ns** |
 | UsingGenericMethodCache |     1 |       0.0000 ns |   0.0000 ns |       0.0000 ns |
 |         **UsingReflection** |    **10** |  **19,189.0129 ns** |  **63.0405 ns** |  **19,182.1202 ns** |
 | UsingGenericMethodCache |    10 |       3.3561 ns |   0.0092 ns |       3.3587 ns |
 |         **UsingReflection** |   **100** | **190,732.5810 ns** | **347.4604 ns** | **190,768.4393 ns** |
 | UsingGenericMethodCache |   100 |      28.1663 ns |   0.1000 ns |      28.1454 ns |

**Comment by jeremydmiller** [comment]
Marten doesn't use the Reflection API at runtime, only to discover the apply methods at configuration time. The MethodInfo's are compiled into Lambda's that run within the `AggregationStep`.

**Comment by danielwertheim** [comment]
Closing as the access is only one per type and would not at all improve.
