### ISSUE TITLE
When a document is Patched and has StoreChanges called in the same session before SaveChanges is called using OptimisticConcurrency a ConcurrencyException is thrown

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#697]
Use case being we have a projection that is being rebuilt and Patch is called when Applying one event and Store is called when Applying another event. All before SaveChanges gets called. This worked back in 1.2.4 I know.

**Comment by jeremydmiller** [comment]
The operations are all executed in the same order you register them against the DocumentSession. Can you try that first before we worry about any of this?

**Comment by ericgreenmix** [comment]
Right. So we need to be able to apply the events in the exact order they are stored in the event store. 

As a simple example:

We have a `User` document/aggregate. In the event store we have a `UserNameChanged` event followed by a `UserUpdated` event. If the `UserNameChanged` event (which uses a Patch to update the name) comes right before the `UserUpdated` event (which updates multiple properties, so it uses a Query and Store operation) we hit the issue. We can't execute `UserUpdated` before `UserNameChanged` because that would rebuild the projection out of order, resulting in improper data.

**Comment by jeremydmiller** [comment]
@ericgreenmix I'm not "fixing" this one. You can easily beat this problem by doing the aggregation per stream where you can figure out in one place what to do and whether you even need a partial. I'm not sure why it would even make sense to do a partial if you're already doing a full update of the same document.

**Comment by ericgreenmix** [comment]
Okay. We aren't able to do the per stream aggregation like you are suggesting because our architecture doesn't allow for that.

My use case above wasn't the best. A better (real) use case we have is we have a command coming into our system to update a question, `UpdateQuestion`. In our command handler, we do finer grained operations on the domain object and call a method like `ChangeText` that emits `QuestionTextChanged` if the Text has changed and `ChangeQuestionMetaData` that emits `QuestionMetaDataChanged` if other properties about the question have changed. `QuestionTextChanged` was using the Patch api in an inline projection and `QuestionMetaDataChanged` was doing a Store. This caused the ConcurrencyException because it created the Patch->Store->SaveChanges scenario. Even if we were to reorganize those events so they were emitted with Store->Patch, doing a projection rebuild could still cause that breakage because two `UpdateTask` commands on the same aggregate could potentially happen which would cause a Store->Patch->Store->Patch, resulting in the exception.

In any case, we will just have to remove all Patches from our projections in favor for Store operations.

**Comment by jeremydmiller** [comment]
@ericgreenmix I really, really don't want any more special logic about reordering operations. "Fixing" your other bugs related to this just caused others, and I threw my hands up and went for having the operations done by document type, in the order that they are registered w/ the IDocumentSession. 

Sorry man, but I'm hearing a whole lot of requests for me to change things instead of you reconsidering your architecture. I think that what you're doing is setting yourself up for a world of hurt here.

Have you thought about doing in two steps? Run all the commands, gather all the emitted events, then append all of them as a set so a more intelligent projection can sort that out?

**Comment by ericgreenmix** [comment]
That is fair and I get the cascading issues. It is just hard to know what should be considered a bug versus an architectural consideration when one issue cascades to create other issues that didn't exist before. 

Appreciate the help!
