### ISSUE TITLE
Patch API supporting multiple fields

### ISSUE THREAD

**Issue by maxsolender** [JasperFx/marten#699]
I would like to be able to patch multiple fields in my json with one call (instead of calling patch N times if I want to patch N fields on the same record).

From what I have read and seen in Marten github repo , it looks like this isn't supported.

**Comment by jeremydmiller** [comment]
Should actually be pretty simple to do. I might be able to get to this one tomorrow.

**Comment by jeremydmiller** [comment]
I'm adding some syntactical sugar for the API, but it's still multiple commands. Do note that the commands are sent to Postgresql in one batch though. I'm trying to get 1.5 out fast, so the bigger perf. story to do this more inline is going to be in 2.0.

**Comment by maxsolender** [comment]
I wrapped the patch call in my code so I'm doing some "syntactical sugar" around calls to the driver.    Once this is released, I could remove some of what I did ... but the 2.0 release is what I would like to see.  What is the target release date for that?

**Comment by jeremydmiller** [comment]
Still ongoing, but I'm going to push this back to 2.1

**Comment by RapidOwl** [comment]
I think this is the same issue I asked about in the Gitter today.

I think this...
```
session.Patch<Thing>(thing.Id).Set(x => x.BooleanThing, true);
session.Patch<Thing>(thing.Id).Set(x => x.StringThing, "Thing");
session.Patch<Thing>(thing.Id).Set(x => x.OtherStringThing, "Other Thing");
```
...would currently result in 3 SQL statements being emitted.

**Comment by mysticmind** [comment]
Refer to #1834, closing this.
