### ISSUE TITLE
Support more .Net primitive types

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#7]
Need to add tests and postgres casts in `MartenExpressionParser` for:

- [ ] bit [ (n) ] --->Byte[]
- [ ] bit varying [ (n) ] --->Byte
- [ ] bytea --->Byte[]
- [ ] interval [ (p) ] --->TimeSpan

**Comment by jeremydmiller** [comment]
Splitting this issue up into separate issues for the types that actually get done;)

**Comment by ekulakov** [comment]
@jeremydmiller what result are expected? can you provide some details?

**Comment by jeremydmiller** [comment]
I'm closing this down at least for now. Newtonsoft doesn't support timespan's out of the box anyway and nobody is asking for the bit or byte types
