### ISSUE TITLE
FetchStreamState before AggregateStream throws nullreferenceexception

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#705]
On a clean `IDocumentStore`.

Given that I have a stream in the database with a typename.
If I do this

```
var state = await session.Events.FetchStreamStateAsync(streamId);
var aggregate = await session.Events.AggregateStreamAsync(streamId);
```

Then I get a nullreferenceexception in FetchStreamStateAsync that ends up in `EventGraph.AggregateTypeFor` where it doesnt seem to find the type in the `_aggregates` dictionary and as such tries to call the `AggregateType` property on a null ref.

However if we switch the order of those two lines
```
var aggregate = await session.Events.AggregateStreamAsync(streamId);
var state = await session.Events.FetchStreamStateAsync(streamId);
```

Then this works because `AggregateStreamAsync` will call `EventGraph.AggregateFor<T>` which will add the type to the `_aggregates` dictionary and as such it will be able to be resolved from there in the next call.

I would expect this to work no matter the order I call `FetchStreamState` or `AggregateStream` in.

**Comment by jeremydmiller** [comment]
@wastaz, I can't reproduce this problem. This test passes in master:

```
    public class fetching_stream_state_before_aggregator_is_registered : IntegratedFixture
    {
        [Fact]
        public async Task bug_705_order_of_operation()
        {
            var streamId = Guid.NewGuid();

            using (var session = theStore.OpenSession())
            {
                var joined = new MembersJoined { Members = new string[] { "Rand", "Matt", "Perrin", "Thom" } };
                var departed = new MembersDeparted { Members = new[] { "Thom" } };

                session.Events.StartStream<QuestParty>(streamId, joined, departed);
                session.SaveChanges();
            }

            using (var query = theStore.OpenSession())
            {
                var state = await query.Events.FetchStreamStateAsync(streamId);
                var aggregate = await query.Events.AggregateStreamAsync<QuestParty>(streamId);

                state.ShouldNotBeNull();
                aggregate.ShouldNotBeNull();
            }


        }
    }

```

If this is still failing for you, can you add a failing test that demonstrates what you're seeing?

**Comment by wastaz** [comment]
Ok, I think I didnt leave enough details to reproduce this properly.
I cant really figure out how to make a good unit test out of this but here's some more details repro steps at least

1. New console app, run the following code (the `FooEvent` and `FooAggregate` types can be anything really, so I havent included them).
```
            var store = DocumentStore.For(_ =>
            {
                _.Connection(ConfigurationManager.ConnectionStrings["Marten"].ConnectionString);
                _.Events.AddEventTypes(new[] { typeof(FooEvent), });
            });

            using (var session = testDs.OpenSession())
            {
                var aid = Guid.Parse("1442cbbb-a49a-497e-9ee8-715ed2833bf8");
                session.Events.StartStream<FooAggregate>(aid, new FooEvent());
                session.SaveChanges();
            }
```

2. Modify console app to this instead
```
            var store = DocumentStore.For(_ =>
            {
                _.Connection(ConfigurationManager.ConnectionStrings["Marten"].ConnectionString);
                _.Events.AddEventTypes(new[] { typeof(FooEvent), });
            });

            using (var session = testDs.OpenSession())
            {
                var aid = Guid.Parse("1442cbbb-a49a-497e-9ee8-715ed2833bf8");
                var state = session.Events.FetchStreamState(aid);
                // We never get to the AggregateStream call because we get a nullreference exception on the FetchStreamState call
                var aggregate = session.Events.AggregateStream<FooAggregate>(aid);
            }
```

`FetchStreamState` only throws if the stream exists, if it doesnt exist it will just return null. Im not sure why this doesnt throw as expected in your test suite? When I do this in a separate console app (or when this happens in my actual application) it is reproducible 100% of the time.

**Comment by jeremydmiller** [comment]
@wastaz This is the next thing I'm gonna look at, thanks for the repro steps

**Comment by jeremydmiller** [comment]
@wastaz Bueno, I can reproduce it now.

**Comment by jeremydmiller** [comment]
@wastaz As a temporary workaround, can you just add this line to your `DocumentStore` configuration:

```
_.Events.AggregateFor<FooAggregate>();
```

I *think* I'd like to turn this one into "rip out the AggregateType on Stream's because nobody likes that, the original use case for it never got done, and it's causing folks problems" issue for the 2.0 release.

**Comment by wastaz** [comment]
Im ok with turning this into that because I really dont like having AggregateType on the streams ;)
