### ISSUE TITLE
Option to disable PLV8

### ISSUE THREAD

**Issue by jonhilt** [JasperFx/marten#706]
If used against a Postgres installation where PLV8 can not be installed, any patches generated for migrating the db include the **mt_transform_patch_doc** function which requires the PLV8 language.

The function is preceeded with a comment (in the patch file) like so...
```
-- proposal.mt_transform_patch_doc Diff

CREATE OR REPLACE FUNCTION proposal.mt_transform_patch_doc(doc JSONB, patch JSONB) RETURNS JSONB AS $$

  var module = {export: {}};

  'use strict';

function findDeep(doc, parts){
    var element = doc;

---

```
Also it's not entirely obvious what parts of Marten will not work without PLV8 support (without consulting the docs looking for mentions).

Would it be possible to have an option to completely disable PLV8 usage which would omit any PLV8 functions from being included in migration patches and also disable any features dependent on PLV8?

**Comment by JerrySievert** [comment]
I'm curious what environment you're using that cannot have PLV8 installed. I'm happy to help with that where I can.

**Comment by jeremydmiller** [comment]
@JerrySievert Azure's new Postgresql support is the obvious outlier, but I know that's supposed to be supported later.

**Comment by jeremydmiller** [comment]
Tasking:

- [ ] StoreOptions.PLV8Enabled
- [ ] IFeatureSchema.RequiresPLV8
- [ ] Filter out PLV8 dependent features in the DDL generation when PLV8 is disabled
- [ ] Throw an exception if the user tries to use a feature that requires PLV8 when it is disabled

**Comment by jonhilt** [comment]
The infrastructure where I currently work is all self hosted, so it's
purely a decision by our own infrastructure team who do not wish to
enable/support it...

That said, I'm about to leave for a company that uses azure so may need to
use it their next...
