### ISSUE TITLE
Issues with IMartenQueryable / query enums and calling !isOneOf() or isOneOf() == false

### ISSUE THREAD

**Issue by maxsolender** [JasperFx/marten#707]
I have run into issues with running linq expressions through the IMartenQueryable when trying to query on enums and !(isOneOf()) or (isOneOf() == false).

I have a list of enums (Status1 = 1, Status2 = 2, Status3 = 3, and so on) that are essentially job statuses -- in statusListArray.

If I run this:
    return await Session.SelectManyAsync<Job<TJob>>(j => j.UserId == userId &&   (j.StatusInfo.Status.IsOneOf(statusListArray)));
   ... it works fine. No issue. Note, it is the positive case "IsOneOf" -- IsOneOf() == true.

If I run this:
    return await Session.SelectManyAsync<Job<TJob>>(j => j.UserId == userId && (!j.StatusInfo.Status.IsOneOf(statusListArray)));
   .... the IsOneOf doesn't work, it is ignored.   Notice the difference is the NOT (!) before the expression.    This is Not(IsOneOf).

If I run this,
return await Session.SelectManyAsync<Job<TJob>>(j => j.UserId == userId && (j.StatusInfo.Status.IsOneOf(statusListArray) == false ));
   ... I get a MartenCommandException with the message (another way of doing Not(IsOneOf):
"Marten Command Failure:\nselect d.data, d.id, d.mt_version from public.mt_doc_jobcontactuploadprocess as d where (d.data ->> 'UserId' = :arg0) and ((d.data -> 'StatusInfo' ->> 'Status')::int = :arg1)\n\n42883: operator does not exist: integer = boolean"

It seems like IsOneOf works properly as long as you don't try to do the inverse of IsOneOf.

**Comment by jeremydmiller** [comment]
@maxsolender, 

Hey man, I need a little more information from you here. What does your document types look like, and what was the actual Linq query that blew up? What you showed above isn't valid syntax.

**Comment by maxsolender** [comment]
Hi -

Sorry for the delay in getting back to you.

Document is:

    public class Job<T> 
    {       
        [Identity] 
        public string JobId { get; set; }
        public string UserId { get; set; }
        public string JobName { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public DateTime StartTime { get; set; }
        public JobStatusInfo StatusInfo { get; set; }
        public JobDownloadDetails DownloadDetails { get; set; }
        public T Details { get; set; }
        public int Version { get; set; }       
        public string GetModelId()
        {
            return JobId;
        }
    }

The T is:

   public class ContactUploadProcess
    {
        public Application? Application { get; set; }
        public Platform? Platform { get; set; }
        public ContextType ContextType { get; set; }
        public List<DeletedContactInfo> ContactsToDelete { get; set; }        
        public ContactUploadJobType UploadJobType { get; set; }
    }

   public class JobDownloadDetails
    {
        public int TotalBlocks { get; set; }
        public int TotalDownloadedContacts { get; set; }
        public DateTime DownloadedOn { get; set; }
    }

   public class JobStatusInfo
    {
        public JobStatus Status { get; set; }
        public ContactUploadJobStatus ContactUploadStatus { get; set; }
        public List<string> ErrorMessages { get; set; }
    }


None of these linq queries work:

  return await Session.SelectManyAsync<Job<ContactUploadProcess>>(j => j.UserId == userId &&  (statusList.Contains( j.StatusInfo.Status) == false )  );  // DOEN'T WORK
                
 return await Session.SelectManyAsync<Job<ContactUploadProcess>>(j => j.UserId == userId && (j.StatusInfo.Status.IsOneOf(statusListArray) == false )); // DOESN'T WORK
               
 return await Session.SelectManyAsync<Job<ContactUploadProcess>>(j => j.UserId == userId && (!j.StatusInfo.Status.IsOneOf(statusListArray))); // DOESN'T WORK


Please let me know if you need anything else.

Thanks,
Max

**Comment by jeremydmiller** [comment]
@maxsolender Hey, when you did this, were you persisting as `Job<ContactUploadProcess>`, or as something like:

```
public class ContactUploadProcessJob : Job<ContactUploadProcess>
{

}
```

**Comment by jeremydmiller** [comment]
@maxsolender I'm sorry, but I'm still not sure what you're saying. Your Linq queries above aren't valid syntax and there are too many details missing in the code samples. Any way I could get you to submit a PR with a failing test on this one?

**Comment by jeremydmiller** [comment]
No updates for awhile, so I'm closing.
