### ISSUE TITLE
Map IdMember by fluent API

### ISSUE THREAD

**Issue by KopIlya** [JasperFx/marten#709]
Hello. In previos version i can mapping on another Id field like this:
`var store = DocumentStore.For(x => {
                var memberInfo = typeof(ITest).GetMember("SystemId").FirstOrDefault();
                x.MappingFor(typeof(T)).IdMember = memberInfo;
            });`
But now property IdMember is readOnly. I dont wont map by attribute. 
Please, help me, how I can mapping by fluent API?

**Comment by jeremydmiller** [comment]
Done in my local branch. It'll be in 1.5.

**Comment by KopIlya** [comment]
Thanks
