### ISSUE TITLE
AutoCreate.None should do absolutely nothing?

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#711]
From a user question a week or two, don't do any kind of schema checks. If it fails, it fails. Caveat emptor? Or do we use yet another enum value?

**Comment by bradyclifford** [comment]
I would agree... None would indicate to me that it does not do any kind of schema checks.  If you added a new enum value, what would it be? NoSchemaChecks?

**Comment by jeremydmiller** [comment]
This is done in the 2.0 branch, I'm going to go ahead and close it.
