### ISSUE TITLE
AsyncProjectionDaemon might "miss" the first event

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#715]
Ive managed to make `AsyncProjectionDaemon` "skip" the first event in my eventstore. This seems to be related to the fact that I did a `DELETE FROM mt_events WHERE seq_id < 4000` to remove a lot of old crap from my dev db that was causing problems for me. 

At this point the `AsyncProjectionDaemon` started skipping the first event in my eventstore, which was highly confusing. I managed to track down the reason why in the source code and there's an incoming PR with a one-line fix.

**Comment by jeremydmiller** [comment]
Fixed by #716
