### ISSUE TITLE
switch schemas of the session object per web request

### ISSUE THREAD

**Issue by mehul230588** [JasperFx/marten#718]
Hello,

Current scenario DocumentStore is registered as singleton object using IoC container in a ASP.NET Web API project.

We are trying to switch schemas of the session object per web request by using the private field _schema of DocumentSession type through reflection so that we can save documents for different clients under different schemas. 
I understand accessing private fields is not a good idea. Is there any cleaner way to achieve this?

        public static void InsertContract(String schema)
        {
            {
                using (IDocumentSession session = Store.LightweightSession())
                {
                    //Accessing the private _schema field
                    var field = typeof(DocumentSession).GetField("_schema", BindingFlags.Instance | BindingFlags.NonPublic);

                    StoreOptions options = new StoreOptions();
                    options.Logger(new MartenDbLogger()); //Custom Logger
                    options.Connection(ConfigurationManager.ConnectionStrings["idb"].ConnectionString);
                    options.MappingFor(typeof(Contract)).DatabaseSchemaName = schema; //Data Model Classes

                    //updating the schema for the session
                    field.SetValue(session, new DocumentSchema(options, new ConnectionFactory(ConfigurationManager.ConnectionStrings["icaDatabase"].ConnectionString), options.Logger()));
                }
            }
        }

From what i understand, Every time we create the new session using Store object (e.g. Store.LightweightSession), newly created session object's schema refers to Store's schema.
Here i am creating a new schema for the Session. Store's schema is still pointing to the older schema object.

Another option is to have a separate IDocumentStore per web request. Will this have any performance implications?
Any assistance would be greatly appreciated.

**Comment by jeremydmiller** [comment]
@mehul230588 That's never going to work. You can't change the schema name on a `DocumentStore` after it's created because it has to "bake" the schema names into remembered Sql strings. We've got an open issue for multi-tenancy that might be coming up within a month, but there we're looking to do it by using a completely separate database for each tenant.

**Comment by mehul230588** [comment]
@jeremydmiller Thank you for the quick reply.
