### ISSUE TITLE
Override id member default convention

### ISSUE THREAD

**Issue by pblachut** [JasperFx/marten#719]
Hi, as far as I know currently the only way to override id member convention is to add attribute `[Identity]` in the document class field / property.

Is there any other way to achieve that (e.g. fluent declaration on store options?).

It would be nice if such fluent api would be available:
```csharp
DocumentStore.For(storeOptions =>
{
    storeOptions.Schema<TDocument>().IdMember(...)
});
```

**Comment by KopIlya** [comment]
Hello. It is done in 1.5 version.
[https://github.com/JasperFx/marten/issues/709](url)

**Comment by pblachut** [comment]
Thanks a lot!
