### ISSUE TITLE
Memory reclaim of DocumentStore

### ISSUE THREAD

**Issue by mehul230588** [JasperFx/marten#721]
i have this sample application with the following scenario
 1. i am creating a 1000 DocumentStore objects in parallel at runtime.
 2. using the store object to perform query operation
 3. Disposing this DocumentStore object created
 4. i am using performance monitor tool to check the No. of bytes on heap of the application.

i see the no. of bytes spikes up as expected for a 1000 object creation.
However the memory consumed never comes down, even after calling it's dispose.
Attached screenshot shows a flat blue line which indicates the #Bytes in all the heaps.
Am i missing something here to dispose the document store? I am new to Marten, i apologize if i used the document store incorrectly.
Appreciate your help in analyzing the issue. Thank you

    class perfmon
    {
        static void Main(string[] args)
        {
            FireRequests();
        }

        public static void FireRequests()
        {
            var tasks = new List<Task>();
            for (int i = 0; i < 1000; i++)
            {
                tasks.Add(Task.Factory.StartNew(()=>
                {
                    try
                    {
                        var result = Select<Token>(); //Here Token is the Model class
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                    }
                }));
            }

            Task.WaitAll(tasks.ToArray());
            Console.ReadLine();
        }

        public async static Task<IEnumerable<T>> Select<T>()
        {
            IEnumerable<T> result;
            IDocumentStore Store = DocumentStore.For(config =>
            {
                config.Connection(ConfigurationManager.ConnectionStrings["Database"].ConnectionString);
            });
            using (IDocumentSession session = Store.LightweightSession())
            {
                result = await session.Query<T>().ToListAsync().ConfigureAwait(false);
            }
            Store.Dispose();
            Store = null;
            return result;
        }
    }

![image](https://cloud.githubusercontent.com/assets/10287231/24729337/bb0eacf6-1a2b-11e7-98e0-0acf5633e2f7.png)

**Comment by jeremydmiller** [comment]
@mehul230588 Idiomatic usage is to just create a single `DocumentStore` for your application, and its lifetime is basically the same as the application itself. Your use case up above isn't something that I think is valid.

**Comment by mehul230588** [comment]
Thank you @jeremydmiller for quick reply.
However the current requirement is a design for multiple user each having separate schema and we will get schema at runtime based on the logged in user. From what i understand multi-tenancy is currently not supported with marten.
So we decided to create a new Store for each schema.

In the above example, i tried to simulate a situation with 1000 parallel request. 
In which case we will end up creating 1000 document store object and then dispose them.
However i see memory is not reclaimed even after disposing it.

**Comment by jeremydmiller** [comment]
It would be if you let the DocumentStore go out of memory. The DocumentStore is kind of expensive to build. For the multi-tenancy, we're only going to support having a separate db for each tenant.

**Comment by jeremydmiller** [comment]
There's nothing to do here, I'm closing this.
