### ISSUE TITLE
Marten 1.5.0 - Detected package downgrade: System.Data.Common from 4.3.0 to 4.1.0 

### ISSUE THREAD

**Issue by vadimline** [JasperFx/marten#722]
Marten (>= 1.5.0) -> Npgsql (>= 3.2.2) -> System.Data.Common (>= 4.3.0) 
Marten (>= 1.5.0) -> System.Data.Common (>= 4.1.0)

**Comment by jeremydmiller** [comment]
@vadimline I've spent my entire morning fixing Nuget issues for other folks. This is only a **warning** that doesn't actually matter. If it bothers you, feel free to send a PR for it.

**Comment by vadimline** [comment]
Agree, not critical. Will send PR for it. I think we can close this issue since it is not critical.
