### ISSUE TITLE
Suggestion: Any way to create tables during application start?

### ISSUE THREAD

**Issue by cchongchong** [JasperFx/marten#725]
Hi There,

We couldn't find a way to let marten create the table for all models. The reason we need all tables there is we still have to write SQL scripts for the complex query, may get an error if that table is not there.

If there is a way to scan all models (let it configurable) in the application and create tables for them, that would be better.

Thanks,
Chongzhao

**Comment by cchongchong** [comment]
Currently, we're using our own models scanner, and calling IDocumentSchema.EnsureStorageExists();

**Comment by jeremydmiller** [comment]
See the 3rd section in this one link: http://jasperfx.github.io/marten/documentation/schema/migrations/

**Comment by cchongchong** [comment]
@jeremydmiller Thank you for your response. Yes, this is what we're using from the beginning, but seems it's not working to create all tables at the start, and also not working if added new model but without any action on it (neither query/load or store). 

Our expected result is like: let's say, we have 10 data models, then we need that 10 tables to be created automatically during the application start, there is no data at all at that time.
But the true is, the table can be only created when we use it with marten. If we use SQL scripts to query it before use marten, we get an error message because it's not there.

That's why we came up that solution: scan all models and call that "EnsureStorageExists()".

If this "AutoCreateSchemaObjects = AutoCreate.All" can work like it says, how it knows the models in our application? Any way to define the method to scan them?

**Comment by jeremydmiller** [comment]
It doesn't know the models in your system. Our big team does some type scanning at bootstrapping time to "know" what the possible document types are upfront. You'll have to do something similar.

**Comment by cchongchong** [comment]
@jeremydmiller Thanks! Then we will keep our current implementation.
