### ISSUE TITLE
Method string.ToLower() doesn't works in Query

### ISSUE THREAD

**Issue by KopIlya** [JasperFx/marten#729]
Hello. From Documentation I understand what I can write query like this:
`session.Query<Target>().Where(x => x.String.Equals("The same thing", StringComparison.OrdinalIgnoreCase));`

But if I write like this:
`session.Query<Target>().Where(x => x.String.ToLower() == "The same thing".ToLower());`
doesnt work.
If `x.String` saved like lowerCase, then my query was successful. I think the method `ToLower()` doesn't works in linq query.

This is normal behavior or bug?

**Comment by jeremydmiller** [comment]
You can do a string insensitive search in Marten's Linq support, but no, we haven't explicitly coded for your exact case (and I'd guess it's `x.String.ToLower()` that's causing your problem).

See http://jasperfx.github.io/marten/documentation/documents/querying/linq/ and the section on string searching. It's missing in the docs, but you can do `Equals(StringComparison)`

**Comment by KopIlya** [comment]
Thanks, I saw this topick on your link.
Will the implementation of the method `x.String.ToLower()` in the near future?

**Comment by jeremydmiller** [comment]
Probably not because there's an easy workaround and that sounds like a lot of work to get it to interpret the Linq query that way. I would take a pull request for the shorter EqualsIgnoreCase() method in Baseline. That's actually a lot easier to do. Jeremy D. Miller
The Shade Tree Developer
jeremydmiller@yahoo.com
 

    On Wednesday, April 12, 2017 2:03 AM, KopIlya <notifications@github.com> wrote:
 

 Thanks, I saw this topick on your link.
Will the implementation of the method x.String.ToLower() in the near future?—

**Comment by KopIlya** [comment]
I have a problem.
I'm developing cross platform application that working with postgresql (thanks to the marten) and mongodb.
Linq queries the same for both implementations.
Query 
`session.Query<Target>().Where(x => x.String.ToLower() == "The same thing".ToLower());`
works in mongodb c# driver, but doesnt works in marten.
And query
`session.Query<Target>().Where(x => x.String.Equals("The same thing", StringComparison.OrdinalIgnoreCase));`
works in marten, but doesnt works in mongodb c# driver.

In jira.mongodb my questions was ignored.
Hope, you will propose a solution for me.
I will be grateful.

**Comment by mysticmind** [comment]
@KopIlya you could probably use the workaround as below:
```csharp
// combine both mongodb and marten linq condition using an or expression
string compareVal = "The same thing";

Expression<Func<Target, bool>> predicate1 = 
x => (x.String.ToLower() == compareVal.ToLower() 
|| x.String.Equals(compareVal, StringComparison.OrdinalIgnoreCase));

session.Query<Target>().Where(predicate1);
```

I know it is kind of an ugly hack/workaround to write the same condition twice but will get you going...

**Comment by jeremydmiller** [comment]
Any update on this one?

**Comment by KopIlya** [comment]
No. I hope somebody can take this issue like up-for-grabs. I think the solution like string.EqualsIgnoreCase doesn't solve my problem with mongodb.

**Comment by KopIlya** [comment]
There is a similar question.
How to be with `.Contains()` method? It does not accept parameter `StringComparison.OrdinalIgnoreCase`.

**Comment by mysticmind** [comment]
If you use `using Marten.Util;` which provides additional extensions via `StringExtensionMethods`, now you will be able to pass `StringComparison.OrdinalIgnoreCase` as second parameter for `.Contains()`

Can you please check and close this issue?

**Comment by KopIlya** [comment]
It work! Thanks
