### ISSUE TITLE
Linq query Contains stored field in list of items

### ISSUE THREAD

**Issue by KopIlya** [JasperFx/marten#738]
Hello.
I see topic http://jasperfx.github.io/marten/documentation/documents/querying/linq/ Searching within Child Collections.
But I have another situation.
In class i have stored property `public string Name { get; set; }`

Query like this doesn't work
`List<string> names = new List<string>() { "ivan", "petr" };`
`var result = martenQueryable.Where(o => names.Contains(o.Name)).ToList();`

Query like this not supported yet or this is bug?

**Comment by mysticmind** [comment]
Use` IsOneOf` method, sample below:
```csharp
List<string> names = new List<string>() { "ivan", "petr" };
var result = martenQueryable.Where(o => o.Name.IsOneOf(names.ToArray()));
```

**Comment by KopIlya** [comment]
Sorry, my fault.
The method `Contains()` works as it should.
