### ISSUE TITLE
Wrong mapping on IdMember in linq query

### ISSUE THREAD

**Issue by KopIlya** [JasperFx/marten#739]
Hello. I have classes.
```javascript
    public interface IIdentity
    {
        string Id { get; set; }
    }
    public interface IStorableObject : IIdentity
    {
        string SystemId { get; set; }        
        int Version { get; set; }
    }
    public abstract class PocoStorableObject : IStorableObject
    {
        public string Id { get; set; }
        public string SystemId { get; set; }
        public int Version { get; set; }
    }
    public class BaseClass : PocoStorableObject
    {
        public string Name { get; set; }
    }
```
The IdMember is SystemId not a Id. 
```javascript
DocumentStore store = DocumentStore.For(x =>
            {
                var memberInfo = typeof(BaseClass).GetMember("SystemId").FirstOrDefault();
                x.MappingFor(typeof(BaseClass)).IdMember = memberInfo;
};
```
In postgre stored correctly.
Stored a few objects.
```javascript
new BaseClass() {Id = "qwe", SystemId = "123"},
new BaseClass() {Id = "asd", SystemId = "456"},
new BaseClass() {Id = "zxc", SystemId = "789"}
```
I have 2 list:
```javascript
var listIds = new List<string>() { "qwe", "zxc" };
var listSystemIds = new List<string>() { "123", "456" };
```
Mapping in linq not working.
```javascript
var resultId1 = martenQueryable.Count(o => listIds.Contains(o.Id)); // result 0
var resultId2 = martenQueryable.Count(o => listSystemIds.Contains(o.Id)); // result 2
var resultSystemId3 = martenQueryable.Count(o => listIds.Contains(o.SystemId)); // result 0
var resultSystemId4 = martenQueryable.Count(o => listSystemIds.Contains(o.SystemId)); // result 2
```

All query search by Id property, but need for searching by SystemId property.

**Comment by mysticmind** [comment]
if you would want to search by IdMember, use the below:
```csharp
var listSystemIds = new List<string>() { "123", "456" };
// this query will allow you to fetch by the Identity field and then you can get count
var result = session.LoadMany<BaseClass>(listSystemIds.ToArray());

// your last query as below should work as well
var resultSystemId4 = martenQueryable.Count(o => listSystemIds.Contains(o.SystemId));
```

Note that Marten stores the data as below:
``` 
 id                        | character varying <== this will have the id value stored which is SystemId
 data                    | jsonb <== serialized data which also contains SystemId
 mt_last_modified | timestamp with time zone
 mt_version          | uuid
 mt_dotnet_type   | character varying

123 | {"Id": "qwe", "Name": null, "Version": 0, "SystemId": "123"} | 2017-04-25 18:53:24.311813+05:30 | 015ba547-e5ec-4ffe-8ac4-1f446ae69885 | MartenTest1.BaseClass
 456 | {"Id": "asd", "Name": null, "Version": 0, "SystemId": "456"} | 2017-04-25 18:53:24.311813+05:30 | 015ba547-e5ec-488e-b940-e06ec7e1c036 | MartenTest1.BaseClass
 789 | {"Id": "zxc", "Name": null, "Version": 0, "SystemId": "789"} | 2017-04-25 18:53:24.311813+05:30 | 015ba547-e5ec-4b1a-b66b-0e55e1436f65 | MartenTest1.BaseClass
```

`session.Load<T>` or `session.LoadMany<T>` methods will allow you to access records based on the Identity column i.e. id in table.

`Count(...)` or `Where(...)` are queries which are applied on the document i.e. data column in table

**Comment by KopIlya** [comment]
Searching by `SystemId` works well. 
The question is how I can search by `Id` property that not the `IdMember`.
This is query search by SystemId, not by Id:
```javascript
var resultId1 = martenQueryable.Count(o => listIds.Contains(o.Id)); // result 0
```

**Comment by mysticmind** [comment]
I understood you issue. `When you query with a property name `Id`, Marten runs the query against `id` column in the table and not the Id property in document stored in jsonb `data` column.

I certainly think it is not a good idea to have a both `Id` as a property and also a different property as IdMember column.

**Comment by KopIlya** [comment]
Yes, you understood me.
Martens allows you to store another property as `IdMember`. I use it. 
The same use case of stored casses I used in mongodb. Mapped in `SystemId`. All query works well. 
It seems to me normal storage option `Id` property and `SystemId` property.

**Comment by KopIlya** [comment]
Can anyone tell me if there are plans to solve this issue?

**Comment by jeremydmiller** [comment]
@KopIlya Same thing, if there really is an issue here, could you add a pull request with a failing test to the 1.5 branch that demonstrates this one?

**Comment by KopIlya** [comment]
I created pull request [https://github.com/JasperFx/marten/pull/759](url)

**Comment by jeremydmiller** [comment]
@KopIlya Got it. I did change the tests a little bit. You'll want to use the `IsOneOf()` method or `IQuerySession.LoadMany<T>` to load documents by an array of id's.

See the commit that'll be tagged against this issue in a second. This'll be in 1.5.2
