### ISSUE TITLE
Cannot create DocumentMapping for Entities without conventional Id member

### ISSUE THREAD

**Issue by jimgolfgti** [JasperFx/marten#743]
Altering the test in `using_natural_identity_keys.cs` illustrates the issue.

```
[Fact]
public void can_override_the_identity_member_with_the_fluent_interface()
{
    StoreOptions(_ => _.Schema.For<OverriddenIdDoc>().Identity(x => x.Name));

    var mapping = theStore.Schema.MappingFor(typeof(OverriddenIdDoc)).As<DocumentMapping>();
    mapping.IdType.ShouldBe(typeof(string));
    mapping.IdMember.Name.ShouldBe(nameof(OverriddenIdDoc.Name));
    mapping.IdStrategy.ShouldBeOfType<StringIdGeneration>();
}
public class OverriddenIdDoc
{
    //public Guid Id { get; set; }

    public string Name { get; set; }

    public DateTime Date { get; set; }
}
```
The guard triggering the exception can be found @ https://github.com/JasperFx/marten/blob/1.5/src/Marten/StoreOptions.cs#L124

**Comment by stristan** [comment]
Can I vote for the quick fix of this issue, please.

**Comment by jimgolfgti** [comment]
@stristan a workaround in the meantime, assumes you are using Newtonsoft, the default, as your serialiser. 
```csharp
public class Entity
{
    [Newtonsoft.Json.JsonIgnore]
    public readonly int Id = -1;
    public string IdMember{ get; set; }
}
```
I would have had a go at patching this myself but that guard is fairly fundamental to everything, we need to look at the impact of not having it there and where it can be moved to.

**Comment by stristan** [comment]
@jimgolfgti Thank you!
