### ISSUE TITLE
Examine the possibility of eliminating some of the CASTing that propagates from JsonLocatorField

### ISSUE THREAD

**Issue by jokokko** [JasperFx/marten#744]
Touched in #740 and discussed in Gitter, I think this a possible area of (massive) perf gains, especially when indices are concerned.

**Comment by jeremydmiller** [comment]
@jokokko Can you make this one a bit more concrete? I don't see `JsonLocatorField` as something we can't change later after the 2.0 release. As for some of what you're talking about in #740, you'd have to break into individual Linq parsing to effect some of those changes. There won't be any quick, easy fix to JsonLocatorField by itself.

**Comment by jeremydmiller** [comment]
Meh, *I* hit some of this today. 

Couple thoughts:

* In some places, we need a "raw" locator that gives you the JSONB element
* In other places, we need it cast to an exact type
* In still other places, we may need it corrected a bit for usage in JSONB_ARRAY_**** functions
* There are two different constructors for JsonLocatorField, one for shallow fields and one for complex fields, **and they do not have consistent logic applied to them**.

**Comment by jeremydmiller** [comment]
Wimping out and pushing this to 3.0.

**Comment by jeremydmiller** [comment]
Finally working on this now
