### ISSUE TITLE
Utilize GitHub Releases

### ISSUE THREAD

**Issue by bradyclifford** [JasperFx/marten#746]
I might not be looking in the right place, but I don't see a good place to go that tells me what Issues are resolved in what Nuget release of Marten.

I really like how Npgsql does it.  They tag their release, utilizing the Release feature of GitHub.  I can see a brief description of the release notes and then, if I want, drill down and see all the issues resolved in that release.

- [Release Notes](https://github.com/npgsql/Npgsql/releases)
- [Issues resolved in that release](https://github.com/npgsql/npgsql/milestone/41?closed=1)

**Comment by jeremydmiller** [comment]
Sorry Brady, but I'm just not gonna sign up to do this. We do track issues to GH milestones matching Nuget versions.
