### ISSUE TITLE
Multi-Tenancy for the Event Store

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#754]
This one is problematic because of the async daemon. We've gotta think carefully about this one.

**Comment by jeffdoolittle** [comment]
Complications with the complications

**Comment by jeremydmiller** [comment]
@jeffdoolittle I think it would be relatively easy with the "tenant id in the same table" approach, but other than that, I'm really not sure.

**Comment by jeffdoolittle** [comment]
Yeah, I was thinking of difficulties with the "database per tenant" approach. <shudder>
