### ISSUE TITLE
default index on DocumentTypeColumn

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#765]
There's no index created on the field DocumentTypeColumn when hiearchies/subclasses are stored in the same table.

**Comment by jeremydmiller** [comment]
Would you mind taking that one? Having it add an index automatically if it's hierarchical?

**Comment by mdissel** [comment]
see #766

**Comment by mdissel** [comment]
The other system fields like Deleted also don't have an index. Should I add an index to those fields?

**Comment by jeremydmiller** [comment]
Deleted, yes, because that's queried so often. I don't think I'd add anything to anything beyond that.

**Comment by mdissel** [comment]
done!

**Comment by jeremydmiller** [comment]
It's in.
