### ISSUE TITLE
Enable Travis CI build for running unit tests on Linux environment

### ISSUE THREAD

**Issue by mysticmind** [JasperFx/marten#775]
- [ ] Enable repo in Travis CI
- [ ] Update readme with the Travis CI build status badge

Note: Travis CI config is already in master via merged PR #767

**Comment by mysticmind** [comment]
@jeremydmiller This should be a quick one to do since it is just enabling the project in Travis CI which allow us to run unit tests on a Linux env. Config is already in master and it will start working right of the bat.

**Comment by jeremydmiller** [comment]
So, um, what do I need to do?

**Comment by mysticmind** [comment]
1. Sign in to travis-ci.org site using "Sign in with GitHub" 
2. Goto your profile page(click on your name link on top right) within the site. This will start syncing the projects list from Github
3. Enable jasperfx/marten

Since we already have the Travis CI config `.travis.yml` in our root folder. CI build will start working automatically. 

Let me know once you do that, I will send a PR to add a build badge for Travis CI in the readme file.
