### ISSUE TITLE
Add ability to register custom Postgres Functions and Indexes in StoreOptions so Schema Patches will work with them 

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#782]
Currently (specifically with adding an index to a table using a function) when exporting the schema patches it will see the schema as out of sync and give drop commands for these custom indexes.

**Comment by mdissel** [comment]
Or only accept objects with the prefix mt_ (or pk_mt) as part of Marten and ignore the others.

**Comment by jeremydmiller** [comment]
@ericgreenmix @mdissel The relevant code in Marten already filters out anything that doesn't have the "mt_" prefix when it compares indexes. What was yours named?

**Comment by ericgreenmix** [comment]
Mine are prefixed with `mt_` because they are being created with a custom function like...

```
CREATE INDEX ON mt_doc_projectoverview USING gin (transform_jsonb_array_element_to_jsonb_array(mt_doc_projectoverview));"
```

**Comment by jeremydmiller** [comment]
@ericgreenmix Can't you just supply an index name there?

```
CREATE INDEX custom_index_name ON mt_doc_projectoverview USING gin (transform_jsonb_array_element_to_jsonb_array(mt_doc_projectoverview));"
```

**Comment by ericgreenmix** [comment]
Good point. That did solve this specific issue for me. Maybe the only thing that needs to be done here is to add a note to the docs that these patch differences only apply to objects that have the `mt_` prefix.
