### ISSUE TITLE
Using Collection.Contains() within a compiled query

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#784]
Looks like the Linq parsing blows up with the combination of `Collection.Contains()` within a compiled query

**Comment by jeremydmiller** [comment]
Nasty, this was a little harder than I'd anticipated. The collection operator works differently than basically every other where clause, and the compiled query determination of how parameters are filled can't handle this one. I'll attempt to address this one in the 2.0 release.

Here's a test to show the problem:

```
    public class Bug_784_Collection_Contains_within_compiled_query : IntegratedFixture
    {
        [Fact]
        public void do_not_blow_up_with_exceptions()
        {
            var targets = Target.GenerateRandomData(100).ToArray();
            targets[1].NumberArray = new[] {3, 4, 5};
            targets[5].NumberArray = new[] {3, 4, 5};
            targets[20].NumberArray = new[] {5, 6, 7};


            theStore.BulkInsert(targets);

            using (var query = theStore.QuerySession())
            {
                var actuals = query.Query(new FunnyTargetQuery());
                actuals.Any(x => x.Id == targets[1].Id).ShouldBeTrue();
                actuals.Any(x => x.Id == targets[5].Id).ShouldBeTrue();
                actuals.Any(x => x.Id == targets[20].Id).ShouldBeTrue();
            }
        }

        public class FunnyTargetQuery : ICompiledListQuery<Target>
        {
            public Expression<Func<IQueryable<Target>, IEnumerable<Target>>> QueryIs()
            {
                return q => q.Where(x => x.Flag && x.NumberArray.Contains(Number));
            }

            public int Number { get; set; }
        }
    }
```

cc @stevematney

**Comment by david-driscoll** [comment]
Has there been any traction on this?  I tried to figure it out, but my Expression knowledge is really rusty.

**Comment by jeremydmiller** [comment]
Meh, the Linq support as it is handles that kind of search, but the compiled query mechanics are off. I haven't touched it since just because there's a workaround. As I recall, we had issues trying to figure out the order of the parameter as well as a new type of parameter to coerce the value into the dictionary that operator needs to use to query Postgresql.

**Comment by jeremydmiller** [comment]
And this took a few years longer than we'd hoped. Was fixed just by the v4 Linq overhaul.
