### ISSUE TITLE
Projection from events to flat database table

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#786]
Mostly to prove out #785 and because I know it's going to cause some changes to the tenancy/schema object creation.

I've got some vague ideas about syntax and mechanics here, but nothing too concrete.

cc @wastaz

**Comment by oskardudycz** [comment]
I'm closing this Issue as it duplicates https://github.com/JasperFx/marten/issues/670

**Comment by jeremydmiller** [comment]
I'm reopening today. I think we *might* consider a flat projection of documents to a flat table or view in the future, but this is specifically to write events to a flat table.
