### ISSUE TITLE
2.0 Punchlist

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#790]
## Coding Work

- [x] Linq tests against the Json serializer w/ the camel casing setting
- [x] Love to replace `FetchResult` in everything but the dirty checked identity map
- [x] Eliminate the `ILoader` interface
- [x] Evaluate all other [Obsolete] tags
- [x] Run through the TODO's in the code
- [x] Try to fix all the Nuget downgrade warnings in the build

## Docs -- besides the other open doc issues

- [ ] FI support for overriding the id member. See #709
- [x] Add AppendIfNotExists and InsertIfNotExists to patching API (might already be done, but verify)
- [x] multi-tenancy via tenant id
- [x] using multi-tenancy from `IDocumentSession` and `IDocumentStore`
- [x] New document mapping policies
- [x] Disabling PLV8
- [ ] Querying across tenants
- [ ] Updating to a named tenant
- [x] Non-typed event store streams
- [x] Event store with string identifiers
- [x] "Overwrite" session mode
- [x] EventStore.StartStream() mechanics
- [x] Created field on StreamState
- [x] Camel Cased JSON
- [x] Insert-only operations
- [x] Update-only operations
- [x] `EqualsIgnoreCase` Linq support

**Comment by ejsmith** [comment]
Would the changes you are making for camelCasing also help with snake_casing?

**Comment by niemyjski** [comment]
Also, should any other breaking changes be considered as an item here. I'm also for having versioning be a long and not a guid. Might be good to get any and all known breaking changes in 2.0 :).

**Comment by jeremydmiller** [comment]
@niemyjski The camel casing option is not a breaking change. 

@ejsmith Yes. Not sure *why* you'd want to do that, but yes.

**Comment by ejsmith** [comment]
Haha yeah, it was a poor choice on my part a while back to try and mimic the best REST APIs (Stripe, GitHub, etc). It's a choice I have come to regret. If I had it to do over again I'd go with the standard naming convention for JS which is camelCased.

**Comment by jeremydmiller** [comment]
I'm declaring victory
