### ISSUE TITLE
Problem with String comparison in VB.NET

### ISSUE THREAD

**Issue by compucen** [JasperFx/marten#795]
Using VB.NET if i make a query that checks equality on a string field like this :

        Using st = store.QuerySession
            Dim rs = st.Query(Of User).Where(Function(a) a.Name = "Kevin")
            For Each itm In rs
                Console.WriteLine(itm.Id.ToString)
            Next
        End Using

i get :
System.ArgumentNullException: 'Value cannot be null.'

i must substitute '=' with a.Name.Equals() to get it done
but in this case, i can't use NOT to negate it 
or i can substitute '=' with 'Is' or 'IsNot'  but this is not properly the same, i think...

**Comment by mysticmind** [comment]
@compucen you can use `Dim rs = st.Query(Of User).Where(Function(a) Not a.Name = "Kevin")`, this works!
