### ISSUE TITLE
Why "json" and not "jsonb"

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/Marten#8]
I'm curious why documents are being stored with the "json" data type, and not the "jsonb" datatype?

https://github.com/JasperFx/Marten/blob/02e104e6b8d567e3dd86c4bf5d8112975ee7bb20/src/Marten/Generation/Templates/DocumentTable.txt#L4

http://stackoverflow.com/a/22910602/627205

**Comment by jeremydmiller** [comment]
@jeffdoolittle  At pretty well the exact time you posted this, I was having a conversation w/ @coreykaylor about exactly that. I'm going to switch to jsonb tomorrow morning and see if I can drop the "CAST" 's I have to do w/ the JSON type to query w/ anything that's not a string.

**Comment by jeremydmiller** [comment]
or belay that, jsonb worked as is, but I'm still gonna try to optimize the queries for jsonb tomorrow.

**Comment by jeffdoolittle** [comment]
That sounds great. I'd be interested in contributing as the project progresses as well. I was thinking about building a very similar project and then I saw you create this repo and I thought "why duplicate effort?" :)

**Comment by jeffdoolittle** [comment]
Also, I'm curious if you saw this blog post series from @robconery - there are some interesting ideas about querying and indexing:

http://rob.conery.io/2015/08/20/designing-a-postgresql-document-api/
http://rob.conery.io/2015/08/21/postgresql-document-api-part-2-full-text-search-and-bulk-save/
http://rob.conery.io/2015/08/25/postgresql-document-api-part-3-finding-things/
http://rob.conery.io/2015/09/01/postgresql-document-api-part-4-complex-queries/

**Comment by jeremydmiller** [comment]
@jeffdoolittle Just added you to the gitter room for this. I'd happily take all the help we could get.

https://gitter.im/JasperFx/Marten?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by jeremydmiller** [comment]
Gonna close this one because we are on JSONB now;)
