### ISSUE TITLE
Soft deletes behaves inconsistently

### ISSUE THREAD

**Issue by mariusin79** [JasperFx/marten#808]
// this loads the document, regardless of the mt_deleted flag
var stream = await session.LoadAsync<Stream>(command.StreamId);

// this filters out deleted documents
await session.Query<Stream>().Where(s => ..)

// query with inline sql does not filter out deleted documents
session.Query<Stream>($"where (data->>'UtcStartTime')::date <= '{scheduledToRunOnDate:O}'::date AND (data->>'UtcEndTime')::date >= '{scheduledToRunOnDate:O}'::date").ToArray();

// this upserts a deleted document, BUT DOES NOT undelete it
session.Store(new Stream{Id=..})

Expected behavior:

Query with and without user-specified sql should behave the same
Load should respect mt_deleted, explicitly opt in to load deleted documents
Upsert should undelete the document which is transparently updated when using session.Store

**Comment by jeremydmiller** [comment]
"Query with and without user-specified sql should behave the same" - I'm going to disagree with you there. That shouldn't have any magic behavior in manipulating the sql IMO

"Load should respect mt_deleted, explicitly opt in to load deleted documents" -- the behavior you are seeing was by design. If you have the id, my assumption was that you knew what you were doing

"Upsert should undelete the document which is transparently updated when using session.Store"

- definitely a detail we missed. Would be pretty easy to address

**Comment by mariusin79** [comment]
"That shouldn't have any magic behavior in manipulating the sql IMO"

That's no problem once you know it, but the docs could state it more clearly as its an easy assumption to make.

" the behavior you are seeing was by design. If you have the id, my assumption was that you knew what you were doing"

I don't see how "know what you are doing" relates to the framework returning the object regardless of its deleted state. In my case, the id which I use to load the document is provided by the client, I can't assume that the client behaves correctly and I don't want the client to operate on a deleted document in that particular case.

**Comment by jimgolfgti** [comment]
Agree with `Load` behaviour, if you know the id exists then you may load. I would say you should be able to opt out of that with either an overload or based on session configuration.

Custom queries I'm with @jeremydmiller on this one, when using that overload you want what you asked for, how would the method call look to opt out of additional clauses? We try hard not to fall back to custom queries as much as possible by implementing custom linq parsers if necessary, http://jasperfx.github.io/marten/documentation/documents/advanced/customizing_linq/

I think that un-delete should also be an explicit operation. I thought about it a little bit when implementing `DeletedBeforeParser` & `DeletedAfterParser` but at the time did not have a use case for resurrecting documents but did decide that if I did it would be something I'd wouldn't want to do unconsciously.

**Comment by jeremydmiller** [comment]
Some of this is part of #826. We're not gonna do the rest of the changes
