### ISSUE TITLE
Passthrough SQL where clause

### ISSUE THREAD

**Issue by ejsmith** [JasperFx/marten#817]
How do you feel about a LINQ extension that lets you pass a raw where expression through to the SQL command? In my use case I have some other logic that is generating a where expression and I would like to combine that with other LINQ operators like Skip and Take. So I was thinking that I would add a IMethodCallParser to let me do that. Thoughts? Also, is that something you would be interested in a pull request for?

**Comment by jeremydmiller** [comment]
That *shouldn't* be that crazy to do, and yep, I'd take a PR for that

**Comment by ejsmith** [comment]
Think it would just be an overload of Where that takes a SQL string and parameters?

**Comment by ejsmith** [comment]
It was super easy to get this working:

```csharp
var user = session.Query<User>()
  .FirstOrDefault(x => x.MatchesWhereFragment("first_name = ? and last_name = ?", "Han", "Solo"));
```

What do you think?

**Comment by jeremydmiller** [comment]
Might even go for just `x.MatchesSql()` or something shorter, but yep, go for it

**Comment by jeremydmiller** [comment]
This is done.
