### ISSUE TITLE
Query view model serialization

### ISSUE THREAD

**Issue by ejsmith** [JasperFx/marten#819]
I want to query a specific collection of documents, but have the results serialized into a model that is a subset of that model. Is that currently possible? Like ideally I want something like:

`session.Query<T, TView>()`

Where you would query from the T document collection and retrieve those documents, but then the results would actually be serialized to the TView model and that would be the return type of the LINQ query.

**Comment by jeremydmiller** [comment]
Yes. http://jasperfx.github.io/marten/documentation/documents/querying/projections/

You can also use JS functions like so: http://jasperfx.github.io/marten/documentation/documents/advanced/javascript_transformations/

**Comment by cocowalla** [comment]
You could also use [AutoMapper](http://automapper.org), which has a `ProjectTo` method that could project your subset onto a type. So instead of monkey code like `.Select(x => new User2{ First = x.FirstName, Last = x.LastName })`, you can do `.ProjectTo<User2>()`

**Comment by jeremydmiller** [comment]
Using AutoMapper would be way less efficient at runtime though. Much more so if you take advantage of Marten's ability to just give you the raw Json of the select transform and write that directly to the http response

**Comment by ejsmith** [comment]
Thanks guys! I am going to dig into the transformations. One of the use cases that I have is doing server side exclusions. One of our apps has a very large field in the documents and isn't needed in 99% of the time.
