### ISSUE TITLE
Where doesn't work with PredicateBuilder

### ISSUE THREAD

**Issue by migajek** [JasperFx/marten#821]
The common usage scenario for PredicateBuilder (http://www.albahari.com/nutshell/predicatebuilder.aspx) is to build the conditions as following:

```
      var predicate = PredicateBuilder.True<AssetProjection>();

            if (!request.NumberStartsWith.IsNullOrEmpty())
                predicate = predicate.And(x => x.Number.StartsWith(request.NumberStartsWith));
```

applying the predicate to the query `DocumentSession.Query<AssetProjection>().Where(predicate).ToList()` doesn't work, i.e. it behaves like there is no filtering at all.

I believe this is due to the way PredicateBuilder works, i.e. the built predicate is 
`True AND <x.Number.StartsWith>`

according to https://github.com/JasperFx/marten/issues/548 constant booleans are not supported.

first of all it'd be great to support that as this is quite common.

it's a shame Marten doesn't throw exception, I strongly believe it should yield loudly when the query is not supported, instead of behaving like everything was ok :)

**Comment by jeremydmiller** [comment]
"I strongly believe it should yield loudly when the query is not supported, instead of behaving like everything was ok :)" -- sure, I do too, but that pretty well means having some explicit code somewhere in the Linq provider that recognizes what it can't handle to throw that exception. I've never quite been able to get folks to understand exactly how laborious the Linq provider support is.

Dunno anything about the PredicateBuilder because I've never used it. I'd happily take a pull request if you wanna dig into the Linq provider code to support the missing pathways here.

**Comment by ejsmith** [comment]
@migajek have you tried the newer version of PredicateBuilder that has the ExpressionStarter and eliminates the default expression of True.

https://github.com/scottksmith95/LINQKit/blob/master/src/LinqKit.Core/ExpressionStarter.cs

**Comment by migajek** [comment]
@ejsmith thanks, haven't heard of the newer version.
I've come up with a temporary workaround, which "reduces" the constant expression. The implementation is naive and unsafe, it should take the operator (and/or) and the constant value (true/false) into account to make sure the expression can be safely "trimmed", however it works well until the PR is hopefully merged :)

```
public static Expression<Func<T, bool>> ReduceConstantBool<T>(this Expression<Func<T, bool>> expression)
        {
            var body = expression.Body as BinaryExpression;
            if (body?.NodeType == ExpressionType.AndAlso || body?.NodeType == ExpressionType.OrElse)
            {
                var right = body.Right.NodeType == ExpressionType.Constant ? body.Left : body.Right;
                return Expression.Lambda<Func<T, bool>>(right, expression.Parameters.ToArray());
            }
            return expression;
        }
```
