### ISSUE TITLE
Store raw json

### ISSUE THREAD

**Issue by ejsmith** [JasperFx/marten#827]
The query API has the ability to return raw JSON, but there isn't currently any way to persist raw JSON documents. I typically work with the raw JSON when doing any sort of data migrations. So I need to retrieve the raw JSON data, manipulate it and then store it back to the db preferably without serializing / deserializing.

**Comment by jeremydmiller** [comment]
This came up in another user question recently. I'm not super excited about it. You'd need to generate yet another function that was good enough to pull the id and any duplicated fields out of the JSON document in order to do that update. Plus know how to fill in the metadata columns as well.

**Comment by ejsmith** [comment]
Yeah, I can see how that would be challenging. I had a thought as I was digging into the internals of Marten. Would it be better to create triggers that pull the values out of the JSON document and populate the duplicated fields instead of having to always go through the insert/upsert functions? It seems like doing triggers would simplify things a bit while also making it easier for someone to change data without using Marten.

**Comment by jeremydmiller** [comment]
We've thrown that idea around a couple times, but I'm leery of using Triggers. Wouldn't get you all the way there anyway, and it would make normal operations a little slower. I'm gonna vote no to the trigger.

**Comment by ejsmith** [comment]
Ok, thanks. Considering the technical feasibility of this issue I'm going to go ahead and close it.
