### ISSUE TITLE
linq support for any and startswith

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#834]
My model is:
```
public class Contact {
	List<string> Tags {get;set;}
}
```
and now trying to count all contacts that have a specific Tag that starts with X
`session.Query<Contact>().Count(x => x.Tags.Any(y => y.StartsWith("X"))`

Currently (v2 rc) I get a NotSupportedException. Any workarounds?

**Comment by jeremydmiller** [comment]
Like I say every single time a Linq problem comes up, you almost have to explicitly code for every possible permutation of operators. I don't think that that usage could be done very easily if at all with the current JSONB operators.

As a workaround, you can add a read only property to your Contact document like:

```
public bool HasXTags
{
    get
    {
          return Tags.Any(y => y.StartsWith("X");

     }
}
```

then query by:

```
session.Query<Contact>().Count(x => x.HasXTags)
```

**Comment by mdissel** [comment]
I tried to find a sql command for this, but didn't find a simple solution other then unnest the array. 
In my case i'm storing a tree structure like ["'/1/2/3/4'", "1/2/4"] and i want to find all the childs of "/1/" for example, so a simple property at the top level will not help in this case. A workaround for now is a OR combination of every child, but that's not very efficient with large number of combinations
`session.Query<Contact>().Count(x => x.Tags.Contains("/1/") || x.Tags.Contains("/1/2/") || etc...);`

**Comment by jokokko** [comment]
@mdissel 
```cs
session.Query<Contact>(@"
SELECT d.data
FROM public.mt_doc_contact d,
    LATERAL jsonb_array_elements_text(d.data -> 'Tags') t
WHERE t.value LIKE 'X%'")
```

**Comment by mdissel** [comment]
Thanks!!

**Comment by jeffdoolittle** [comment]
@mdissel or @jokokko - want to turn that into an `IMethodCallParser` and submit a PR?

http://jasperfx.github.io/marten/documentation/documents/advanced/customizing_linq/

**Comment by jokokko** [comment]
@jeffdoolittle I think I can take a stab at it. Might not be totally trivial though, because of the LATERAL...

**Comment by jeffdoolittle** [comment]
Helpful place to start: 

https://github.com/JasperFx/marten/blob/8069bb0657c42672b5fcfaf600b0aae20d93936e/src/Marten/Linq/Parsing/IsOneOf.cs

**Comment by jokokko** [comment]
Thanks. I hope I can manage. I have a pending PR for one IMethodCallParser already }:]

**Comment by jeremydmiller** [comment]
That's gonna be harder than you'd hope because of the LATERAL. It won't fall into the IMethodCallParser pattern because you'd need to change the FROM clause

**Comment by jokokko** [comment]
@jeremydmiller Exactly. Didn't have the codebase open, but I recalled this would likely be the case :(

**Comment by jeffdoolittle** [comment]
Ah, yes. bummer.

**Comment by jeremydmiller** [comment]
We could have some kind of extended interface that would expose extra from clauses. Just turns this into a bigger story than you'd hope it would be.

**Comment by jeffdoolittle** [comment]
Are you talking about extending `IMethodCallParser` in this way? Or something else?

**Comment by mdissel** [comment]
alternative would be to create a sub-query where EXISTS (...), but I think that the queryplan is not very efficient.

**Comment by jeffdoolittle** [comment]
Might be good to just start there and get some test coverage, then migrating to the `FROM` clause approach would already have coverage to ensure it's working properly.
