### ISSUE TITLE
query by runtime type

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#836]
Currently the Query<T> are all generic methods, but in some situations you need to query on a runtime type. I can't find a method to query like:
`session.Query(typeof(User), "where ...")`

**Comment by jeremydmiller** [comment]
Got it with https://github.com/JasperFx/marten/pull/853. Thanks @jokokko !

**Comment by mdissel** [comment]
I've added two overloads to support type and id when using session.Load(..). If this is the correct way to solve this, should I create a pull request for this?

```
public static object Load(this IDocumentSession session, Type type, long id) {
	return session.Query(type, "where id = ? limit 1", id).FirstOrDefault();
}

public static async Task<object> LoadAsync(this IDocumentSession session, Type type, long id, CancellationToken token = default(CancellationToken)) {
	return (await session.QueryAsync(type, "where id = ? limit 1", token, id)).FirstOrDefault();
}
```

**Comment by mysticmind** [comment]
@mdissel I think it would be better to add docs for the extension methods you have outlined rather than making it available in Marten.

**Comment by jeremydmiller** [comment]
@mdissel I agree w/ what @mysticmind. To bring that into Marten itself, I'd say that we'd need to do it differently to bring things through the identity map, version tracking, etc. There's just a lot more going on than just the pure loading of the doc.

**Comment by mdissel** [comment]
>There's just a lot more going on than just the pure loading of the doc.
Agreed, in my situation I don't update the object, so that's currently no issue for me. Create a separate issue to add support for this in the identity map?

**Comment by jeremydmiller** [comment]
I'd rather just deal with this with documentation if we could. I'd prefer not to add any more overloads of `Load()` to the main `IQuerySession` interface.

**Comment by mdissel** [comment]
We could make a separate LoadByType(..)
