### ISSUE TITLE
Missing function mt_immutable_timestamp when initializing new schema

### ISSUE THREAD

**Issue by Husqvik** [JasperFx/marten#837]
Getting `42883: function marten_test.mt_immutable_timestamp(text) does not exist` if auto creating new schema using new Marten 2.0.

```
void Main()
{
	using (var store =
		DocumentStore.For(
			o =>
			{
				o.AutoCreateSchemaObjects = AutoCreate.All;
				o.DatabaseSchemaName = "marten_test";
				o.Connection("host=localhost;database=postgres;password=secret;username=postgres");
				o.Logger(new ConsoleMartenLogger());
			}))
	{
		using (var session = store.OpenSession())
			session.Query<Test>().FirstOrDefault(m => m.Time > DateTimeOffset.Now);
	}
}

class Test
{
	public Guid Id { get; set; }
	public DateTimeOffset Time { get; set; }
}
````

**Comment by jeremydmiller** [comment]
@Husqvik Is it throwing any errors? Have you made any kind of customization of your database permissions maybe?

**Comment by Husqvik** [comment]
line `session.Query<Test>().FirstOrDefault(m => m.Time > DateTimeOffset.Now)` throws `MartenCommandException` with InnerException of `PostgresException` with message `42883: function marten_test.mt_immutable_timestamp(text) does not exist`. No customization. DB user is superuser so I have all privileges. Postgres version is 9.5.4

**Comment by mysticmind** [comment]
I did some repro on this issue and observing the following:
- `mt_immutable_timestamp` gets created in the `public` schema even though a `DatabaseSchemaName` is set
- When a query is run it is looking for a database schema name scoped `mt_immutable_timestamp`.

**Comment by jeremydmiller** [comment]
Fixed, will be in 2.1

**Comment by stvoidmain** [comment]
First of all, i love marten, fantastic work, keep it up!!!
Now, for the matter:
It should never look for it in public schema, why we assume there is always one? It's just a convention, my Postgre databases almost never have a public schema i keep droping it after creating database 99% od the times, and, in any case, it would be better to fix the Add of SystemFunctions to take DabaseSchemaName into account, or is there any reason that i'm missing to have all in public schmea and make all marten user to have a default schema by martens convention?

**Comment by stvoidmain** [comment]
Today I have again the same problem, despite the fact that i'm setting DatabaseSchemaName and the functions are there (in that schema) Marten still looks for it in public schema... I don't know why but is easy to reproduce, create a new class store and configure it with a schema that is not "public" with a couple of int or string fields, its all fine and dandy, run your code, maybe save one or two entities and then, stop it and add a DateTime field (of course you have to avoid having the functions already created in public schema or the public shhema dropped) and then you can see it fail horribly with a message like this:

```
42883: no existe la función public.mt_immutable_timestamp(text) ---> Npgsql.PostgresException: 42883: no existe la función public.mt_immutable_timestamp(text)
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 446
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 332
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1218   
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
   at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature)
   --- End of inner exception stack trace ---
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature)
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType)
   at Marten.Storage.Tenant.StorageFor(Type documentType)
   at Marten.DocumentSession.Store[T](T[] entities)
```

**Comment by cocowalla** [comment]
@stvoidmain I'm having the same problem - when using the patch API it tries to execute a statement that includes `public.mt_immutable_timestamptz`, and then I get this error message from the database:

```
schema "public" does not exist
```

Did you find any way around this?

**Comment by oskardudycz** [comment]
@stvoidmain @cocowalla could you open separate issue and reference this one? It's much easier for us (maintainers) to track new issues than reopen new one (especially if that issue was closed over 2 years ago ;)
Thank you in advance :)

**Comment by cocowalla** [comment]
@oskardudycz I was going to open one shortly, just wanted to check if a workaround was already known

**Comment by cocowalla** [comment]
@oskardudycz opened #1378 and sent PR #1379 😃

**Comment by oskardudycz** [comment]
@cocowalla thank you! 👍 😄 👍
