### ISSUE TITLE
Marten Icon/logo suggestion

### ISSUE THREAD

**Issue by mysticmind** [JasperFx/marten#839]
https://www.flaticon.com/free-icon/marten_185844

![image](https://user-images.githubusercontent.com/2864208/28884394-4895b208-77cf-11e7-9b0b-495bebea9fc5.png)

This can be freely used with the attribution as below:
```
<div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
```

Just a thought/suggestion...

**Comment by cocowalla** [comment]
Doesn't Marten already have a [logo](http://jasperfx.github.io/marten/)

**Comment by mysticmind** [comment]
It does, thought of something better...

**Comment by cocowalla** [comment]
TBH, I quite like the existing logo

**Comment by mysticmind** [comment]
Alright, without further ado, closing this :-)
