### ISSUE TITLE
Decimal values linq tests fail on none US machines

### ISSUE THREAD

**Issue by tim-cools** [JasperFx/marten#84]
When I run the tests on my machine which uses , for decimals some ST tests fail because ST can't convert the decimal values. When i change

```
    <TheDocumentsAre-row Name="C" Double="6.5" />
    <TheDocumentsAre-row Name="E" Double="10.1" />
```

To 

```
    <TheDocumentsAre-row Name="C" Double="6,5" />
    <TheDocumentsAre-row Name="E" Double="10,1" />
```

All tests pass. This is however no solution. I guess this needs to be fixed in ST so that the conversion to decimal always use InvariantCulture?

**Comment by jeremydmiller** [comment]
Yeah, ST itself, and yep. I'm a little surprised this hasn't happened before. I can maybe get that addressed on Monday. I had some other ST todo items coming from Marten work.

**Comment by jeremydmiller** [comment]
@nieve has a workaround for this kind of thing in the integrated fixtures to just force the Thread.Culture to "en-US." I'll probably do the same here.

Go ahead and say "ugly American"

**Comment by jeremydmiller** [comment]
@tim-cools How bad would it be if I solved this by forcing ST to do all conversions with a given culture? Something like st.exe open [folder] --culture en-US ?

**Comment by tim-cools** [comment]
@jeremydmiller sounds good to me! 
Initially I was thinking about an application setting, but this makes more sense in the case of ST...
