### ISSUE TITLE
Less optimistic concurrency exception and auditing

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#842]
To prevent concurrency problems I split my json document over multiple tables, but for viewing purposes I always need all the different parts. For editing purposes the document will be updated by a background process potentially causing a concurrency problem for the user on the frond end ( i know this could be solved with websockets, etc)
For auditing purposes I want to store the JSON DIFF result in an update trigger.

Proposal:
- add an optional concurrency pattern named "MergeOrThrow"  (or whatever) configured at table level.
- the update function in postgres is changed in
. create json diff object from the new data and the current data in the table
. check version, if version is equal (or no version supplied) just update the table. if version is not equal try to execute a json merge with original data and the json diff object. if no conflicts update the field else throw a concurrency exception
. insert the json diff object into an audit table

The auditing action can of course be made optional so you can activate this for some tables.
plv8 will be required and some helpers methods for the json diff and merge actions

The json merge helper method can also be used to support json Patch commands.

**Comment by jeremydmiller** [comment]
I just don't see this happening or getting enough usage to justify being in Marten core, and there's been no updates in 18 mos.  I'm closing.
