### ISSUE TITLE
DateTime UTC query parameter is treated as localized date time

### ISSUE THREAD

**Issue by mariusin79** [JasperFx/marten#852]
My localpostgres server is running with time zone UTC:

select * from pg_settings where name = 'TimeZone'; // yields UTC

If I execute the following: 

                var streams = await session.Query<Stream>()
                    .Where(s => s.UtcWhen.EndTime >= command.UtcStartTime).ToListAsync();

The generated query parameter for "command.UtcStartTime" is correctly sent to my local server as:

'2017-08-17 13:01:00.826+00' // command.UtcStartTime has Kind == UTC

On the other postgres-server, which are running in local timezone, this gets messed up. The above query parameter is passed as '2017-08-17 15:01:00.826+02', which is semantically the same as the first parameter (only localized), but fails when the generated query gets executed against the database:

select d.data, d.id, d.mt_version from yourdb.mt_doc_stream as d where ((CAST(d.data -> 'UtcWhen' ->> 'EndTime' as timestamp without time zone) >= $2) and d.mt_deleted = False)

We treat all datetimes as UTC server-side, so the stored json looks like this:
{
  "StartTime": "2017-08-16T12:00:00.558Z",
  "EndTime": "2017-08-16T15:00:00.558Z",
}

The CAST in the auto-generated query will treat the persisted UTC-date as localized and compare it to the given parameter, thus yielding no results when executed against servers which are localized.

Is it possible to fix this by using DateTimeOffset instead of DateTime or do you have any other suggestions? We do not want to introduce a dependency where all our postgres-servers need to be set up as not localized in order to fix this.

Cheers

**Comment by jeremydmiller** [comment]
@mariusin79 Did you try DateTimeOffset yet? I'd have to dig into the code, but I think in that case we force all comparisons in the Linq to UTC with that immutable timestamp function, but I've never tried the exact use case you're doing there.

**Comment by mariusin79** [comment]
Tried DateTimeOffset, this causes the datetimes to be stored localized server side (with timezone offset) instead of as utc, so it's a workaround at best.

Also tried adding a document listener:

        public override async Task BeforeSaveChangesAsync(IDocumentSession session, CancellationToken token)
        {
            using (var command = session.Connection.CreateCommand())
            {
                command.CommandText = "SET timezone='utc';";
                await command.ExecuteNonQueryAsync(token);
            }

            await base.BeforeSaveChangesAsync(session, token);
        }

But Marten seems to drop all session state, so this does not work either:

LOG:  execute <unnamed>: SET timezone='utc'
LOG:  statement: DISCARD ALL
LOG:  execute <unnamed>: 
	SELECT pg_get_functiondef(pg_proc.oid) 
...

**Comment by jeremydmiller** [comment]
@mariusin79 I honestly don't know. I spent a full day at one point working over the ability to query w/ DateTime & DateTimeOffset with time zone issues. A PR with a fix would certainly be best, but at a minimum can you add a PR with a failing test that demonstrates the issue?

**Comment by oskardudycz** [comment]
@mariusin79 see my comment in other issue. https://github.com/JasperFx/marten/issues/908#issuecomment-464858253

Closing for now. If that doesn't answer your question - feel free to send the feedback.
