### ISSUE TITLE
Using multiple OR expressions in a query causes SoftDelete and Tenancy filters to be appended incorrectly

### ISSUE THREAD

**Issue by barryhagan** [JasperFx/marten#854]
When upgrading our app from 1.5.2->2.1, I found that any query that contains multiple OR expressions against an object configured for Soft Deletes will return all objects of that type instead of the expected filtered list.

It appears to be a problem when adding the soft delete clause to the database query.  If there are multiple expressions that need to be OR'd, then the `d.mt_deleted = False` clause is also added as an OR instead of an AND.

Multiple expressions will cause incorrect behavior:
`var query = session.Query<SoftDeletedItem>().Where(x => x.Number == 1 || x.Number == 2);`
=>
`select d.data, d.id, d.mt_version from public.mt_doc_softdeleteditem as d where (CAST(d.data ->> 'Number' as integer) = $1 or CAST(d.data ->> 'Number' as integer) = $2 or d.mt_deleted = False)`

Single expression is fine:
`var query = session.Query<SoftDeletedItem>().Where(x => x.Number == 1);`
=>
`select d.data, d.id, d.mt_version from public.mt_doc_softdeleteditem as d where (CAST(d.data ->> 'Number' as integer) = $1 and d.mt_deleted = False)`

Failing test:
https://github.com/barryhagan/marten/commit/dd95f38bc9c47b326310b4f47ac2c3a4c281501c

**Comment by barryhagan** [comment]
This is also an issue for multi-tenancy.

https://github.com/barryhagan/marten/commit/0087b32f67f0bd57098f5f32890a144b6214f991

**Comment by jeremydmiller** [comment]
Addressed by https://github.com/JasperFx/marten/pull/860
