### ISSUE TITLE
When AutoCreateSchemaObjects is set to AutoCreate.None DocumentStore.Schema.WritePatch doesn't work

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#855]
It will never produce any patch, even if there is one to be made. If you change AutoCreateSchemaObjects to anything but `None` it will properly create the patch.

Looks to be possibly linked to https://github.com/JasperFx/marten/issues/711

**Comment by ericgreenmix** [comment]
@jeremydmiller The cause of this issue seems to be right here https://github.com/JasperFx/marten/blob/660ea5c6a2fe04b0bcf67540f267b38cfc56fa5d/src/Marten/Schema/SchemaPatch.cs#L176 

This is all related to #711, since it isn't doing any schema checks on `AutoCreate.None`, it is unable to to produce this during a migration. What do you think of adding an optional parameter to `WritePatch` that will enable schema checks for `AutoCreate.None`? Marten's CLI could use this and anyone wanting to generate Migrations could as well.

**Comment by jeremydmiller** [comment]
@ericgreenmix I can't recreate this one. How were you making this happen?

If you follow the code, you should see that `WritePatch()` pushes in a set value of `AutoCreate` rather than using the value from `StoreOptions`

**Comment by ericgreenmix** [comment]
All I am doing is changing the `AutoCreate` in the `StoreOptions` between `None` and `All`. Isn't this call right here using the `StoreOptions` AutoCreate? https://github.com/JasperFx/marten/blob/02a98cf1ee89abdb21800e1d1265b00678b71ae4/src/Marten/Storage/TenantSchema.cs#L127

**Comment by jeremydmiller** [comment]
In that case, yes. I tried a straight up `IDocumentStore.Schema.WritePatch()`. Again, can you either add a failing test as a PR or just fix this? Shouldn't be any big deal here.

**Comment by ericgreenmix** [comment]
Yep. I will get you are PR for this as soon as I get some time this week.

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/marten/pull/861
