### ISSUE TITLE
When updating from Marten 1 to Marten 2 doing a WritePatch to get the migration file using AutoCreate.CreateOrUpdate or AutoCreate.Create throws exception

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#857]
The patch sql file is generated correctly if `AutoCreate.All` is used. But throws this exception if that is changed to `AutoCreate.CreateOrUpdate` or `AutoCreate.Create`. As per #855 I couldn't test this with `AutoCreate.None`.

I assume this exception isn't going to be specific to updating from Marten 1 to 2, but this is my current test case.

```
ERROR: System.InvalidOperationException: Marten cannot derive updates for objects public.mt_streams

   at Marten.Schema.SchemaPatch.AssertPatchingIsValid(AutoCreate autoCreate)
   at Marten.Storage.
TenantSchema.ToPatch(Boolean withSchemas)
   at Marten.Storage.TenantSchema.AssertDatabaseMatchesCo
nfiguration()
   at Marten.CommandLine.PatchCommand.execute(IDocumentStore store, PatchInput input)

   at Marten.CommandLine.MartenCommand`1.Execute(T input)
   at Oakton.OaktonCommand`1.Oakton.IOak
tonCommand.Execute(Object input)
   at Oakton.CommandRun.Execute()
   at Oakton.CommandExecutor.<>c
__DisplayClass15_0.<Execute>b__0()
   at Oakton.CommandExecutor.execute(Func`1 execute)
```

**Comment by ericgreenmix** [comment]
Also, when `AutoCreate.All` is set, the patch changes for the mt_streams table (adding the created and tenant_id) are not being generated and the patch to modify the `mt_append_event` function is generated every time, even after it has already been ran.

**Comment by jeremydmiller** [comment]
I don't know Eric. I really wish you would have tried this out months ago when 2.0 was sitting in alpha.

**Comment by ericgreenmix** [comment]
Yeah, I wish we had time to start updating before last week. We found workarounds for these issues but I thought they should be documented in issues.

**Comment by jeremydmiller** [comment]
@ericgreenmix Try 2.2 when it's up on Nuget.

**Comment by ericgreenmix** [comment]
Yes, the main issue with this is fixed now. I am creating a separate issue for the `mt_append_event` function being generated every time and have a failing test for that I will be submitting
