### ISSUE TITLE
Patch API sub-array object find support

### ISSUE THREAD

**Issue by slashben** [JasperFx/marten#858]
Would it be reasonable to add sub-array object find support to the patching array?

I'd like to be able to find an object in a sub-list before patching it. It doesn't seem to be working for me. There is no error, but the object is not updated in the database.

For example:
`theSession.Patch<Target>(target.Id).Set(x => x.subList.anotherSubList.First(o => o.prop == "someValue").Number, 10);`

**Comment by jeremydmiller** [comment]
I don't see that happening very easily. You're just talking about way, way too many permutations to account for. We don't have anything *quite* like what you're talking about, but I think it'd be way easier to use the Javascript transform feature for these kinds of unusual patches.

It's not just a "sub-array" object, it's understanding the `First()` within the expression that's the killer there.

**Comment by jeremydmiller** [comment]
This probably isn't going to get done. I'm recommend using a javascript function transform here. We *could* do better JS transforms that allow for inputs. Maybe an extensible patching model I guess.
