### ISSUE TITLE
Try out Utf8Json as a Json serializer option

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#885]
See https://github.com/neuecc/Utf8Json.

Just as an experiment, let's just do a branch that uses that as the default serializer in the test suite and see how it goes

**Comment by timdoke** [comment]
Here's an implementation... The only issue I ran into in my tests was on ToJson.. I had to dispose the writer for it to work correctly..

```
using System;
using System.IO;
using Marten;
using Marten.Services;
using Utf8Json;
using Utf8Json.Formatters;
using Utf8Json.Resolvers;
using JsonSerializer = Utf8Json.JsonSerializer;

namespace Repository.Serializers
{
    public class Utf8JsonSerializerWrapper : ISerializer
    {
        static Utf8JsonSerializerWrapper()
        {
            CompositeResolver.RegisterAndSetAsDefault(new IJsonFormatter[] {
                // add custom formatters, use other DateTime format.
                // if target type is struct, requires add nullable formatter too(use NullableXxxFormatter or StaticNullableFormatter(innerFormatter))
                //new DateTimeFormatter("yyyy-MM-dd HH:mm:ss"),
                //new NullableDateTimeFormatter("yyyy-MM-dd HH:mm:ss")
            }, new[] {
                // resolve custom types first
                EnumResolver.UnderlyingValue,
                
                // finally choose standard resolver
                StandardResolver.Default
            });
        }
        

        public void ToJson(object document, TextWriter writer)
        {
            using (writer)
            {
                var data = JsonSerializer.NonGeneric.ToJsonString(document);
                writer.Write(data);
            }

            //JsonSerializer.NonGeneric.Serialize(writer, document);

            //JsonSerializer.NonGeneric.Serialize(writer, document);
        }

        public string ToJson(object document)
        {
            //string jsonOther = JsonConvert.SerializeObject(document);
            
            string output = JsonSerializer.NonGeneric.ToJsonString(document);

            return output;
            
        }

        public T FromJson<T>(string json)
        {
            return JsonSerializer.Deserialize<T>(json);
        }

        public T FromJson<T>(Stream stream)
        {
            return JsonSerializer.Deserialize<T>(stream);
        }

        public object FromJson(Type type, string json)
        {
            return JsonSerializer.NonGeneric.Deserialize(type, json);
        }

        public T FromJson<T>(TextReader reader)
        {
            return JsonSerializer.Deserialize<T>(reader.ReadToEnd());
        }

        public object FromJson(Type type, TextReader reader)
        {
            return JsonSerializer.NonGeneric.Deserialize(type, reader.ReadToEnd());
        }

        public string ToCleanJson(object document)
        {
            return ToJson(document);
        }

        public EnumStorage EnumStorage { get; set; } = EnumStorage.AsInteger;

        public Casing Casing { get; set; } = Marten.Casing.Default;

        
    }
}

```

**Comment by jeremydmiller** [comment]
@timdoke Sweet. How did you test it?

**Comment by timdoke** [comment]
@jeremydmiller About 100 different integration tests at my work.. create, search, delete, etc.. I actually replaced newtonsoft with this as the default serializer for webapi too.. that was more complicated

**Comment by timdoke** [comment]
One other issue I noticed..  
```public EnumStorage EnumStorage { get; set; } = EnumStorage.AsInteger;
```
seemed to get ignored.  That's why I had to add the composite serializer options.

**Comment by oskardudycz** [comment]
I think that we should more focus on the Json improvements on .NET Core 3.0 - https://github.com/dotnet/corefx/issues/33115 

@jeremydmiller @mysticmind @jokokko thoughts?

**Comment by timdoke** [comment]
For what it's worth.. It's very simple to change to use utf8json, and I had a several hundreds of percent performance improvement versus newtonsoft.  I'm actually using it in all of my projects at work.  The reason I never went forward further with this as a published package, was I don't really have a place to publish, and I'm not sure how challenging it would be to manage bugs -- seeing as how I don't own that utf8json project.  But, I've been using it for over a year now and have had no issues that are attributable to this library.  One thing Jeremy asked a long time ago, is if utf8json supported JsonProperty attributes -- it doesn't, that is specific to Newtonsoft -- but, it does support the Datamember syntax.

**Comment by cocowalla** [comment]
@oskardudycz according to [this](https://github.com/dotnet/corefx/issues/33115#issuecomment-468178867), they will be shipping an MVP for .NET Core 3.0. While the CoreFx team have tackled this new JSON serialiser with far more gusto than expected, it could be a while before it's fully featured. I imagine it could also be a while before it's available for a .NET Standard target... and as for .NET Framework, well, who knows :disappointed:

**Comment by jeremydmiller** [comment]
@timdoke Long term, maybe/probably. Shorter term, I think we just invest a little bit in a quick way to be able to run the test suites in a matrix so that you could quickly swap the serializers in and out and find compliance problems (inevitably around enums and maybe dates). Newtonsoft is never the default serializer because it's the fastest thing on Earth, but it's always the one most likely to actually work for whatever you throw at it.

**Comment by mysticmind** [comment]
@jeremydmiller I will look at adding the matrix test runs

**Comment by timdoke** [comment]
@jeremydmiller  the biggest problem I ran in to (and this was using at to serialize web api calls, not postgres), was there is no implicit conversion from a string to int -- for example, "1" does not convert to 1 with utf8json as it does with newtonsoft.

**Comment by Miggleness** [comment]
While not exhaustive, my tests still has Utf8Json faster than Net Core 3's implementation.

https://github.com/Miggleness/DotNetJsonBenchmarks

**Comment by jeremydmiller** [comment]
Not sure how everyone feels about this, but the Utf8Json project sure looks like abandonware to me after looking over their GitHub page today.

**Comment by mysticmind** [comment]
Yes, agree with you @jeremydmiller . The last release was on Jan 2018 and the last commit in the repo is Jun 2018. It is not actively maintained.

**Comment by jeremydmiller** [comment]
Then I'm closing this one. Nothing stopping users from using it though.
