### ISSUE TITLE
DocumentSession.Store() throws Exception

### ISSUE THREAD

**Issue by brainwipe** [JasperFx/marten#888]
When calling `Store()` on a new entity, `ArgumentNullException` is thrown.

## Versions

- Marten version: 2.3.2 (installed via nuget in Visual Studio), includes: Baseline 1.3.0, FastExpressionCompiler 1.1.1, Newtonsoft.Json 9.0.1, Npgsql 3.2.5, Remotion.Linq 2.1.1, System.Threading.Tasks.Dataflow 4.7.0.
- IDE: Visual Studio 2017 (15.3.5)
- Framework: .NET Core 2.0
- Postgres: 9.5.2 running on localhost:5432.

## Stack Trace:
```
System.ArgumentNullException: Value cannot be null. Parameter name: type

System.ArgumentNullException occurred
  HResult=0x80004003
  Message=Value cannot be null.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at Baseline.TypeExtensions.IsNullable(Type type)
   at Marten.Util.ReflectionExtensions.GetMemberType(MemberInfo member)
   at Marten.Storage.DocumentTable..ctor(DocumentMapping mapping)
   at Marten.Schema.DocumentMapping.<toSchemaObjects>d__129.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature)
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType)
   at Marten.Storage.Tenant.StorageFor(Type documentType)
   at Marten.DocumentSession.Store[T](T[] entities)
   at MartenPOC.Program.Main(String[] args) in C:\Projects\MartenPOC\Program.cs:line 28
```

## Code
Running in a .NET Core Console App, set to framework 2.0.

```
using System;
using Marten;

namespace MartenPOC
{
    class Program
    {
        static void Main(string[] args)
        {
            var store = DocumentStore
                .For(
                    s =>
                    {
                        s.DatabaseSchemaName = "dbo";
                        s.Connection("Server=127.0.0.1;Port=5432;Database=martenpoc;User Id=mcodevuser;Password=password");
                        s.AutoCreateSchemaObjects = AutoCreate.All;
                    });

            using (var session = store.LightweightSession())
            {
                var patient = new PatientDetail
                {
                    Email = "rob@stuff.com",
                    Name = "Rob"
                };

                session.Store(patient); // Exception thrown here
                session.SaveChanges();
            }
        }

        public class PatientDetail
        {
            public string Email { get; set; }

            public string Name { get; set; }
        }
    }
}
```

## Example Project
[MartenPOC.zip](https://github.com/JasperFx/marten/files/1362654/MartenPOC.zip)

## Postgres Setup
- Created new database (martenpoc), user (mcodevuser) and schema (dbo)
- Made user schema owner
- Give user full authorization to db and schema

## Steps to reproduce
- Open Visual Studio 2017
- File -> New -> Project
- Installed/Visual C#/.NET Core/ Console App (.NET Core)
- Give it a name and a save location
- In Solution Explorer, right click project and select properties
- In Application tab, select Target Framework as .NET Core 2.0
- Right Click the project and select Manage Nuget Packages
- On Browse tab, search for Marten and install latest release (Include Pre Release is not checked, nuget restore success)
- Insert the code into the Program.cs file.
- Hit F5 and it breaks on the line shown above.

## Other things I've tried / noticed
- I tried restoring packages, uninstall and reinstall, switch it off, switch it on again.
- I tried with .NET Core 1.0, same error
- I tried with .NET 4.6.2 but got the BaseLine nuget Id issue.
- I noticed that the only thing created in the database was the function `mt_immutable_timstamp(TEXT)`
- I can connect to the Postgres schema using EF Core (+Npgsql) and run migrations, so I believe the user permissions to be OK.

I hope there's some PEBKAC going on here (somewhere in the config), thanks in advance for your help and your time.

**Comment by mdissel** [comment]
It seems that you're missing the ID / Identity column in the PatientDetail class

**Comment by jeremydmiller** [comment]
@brainwipe What @mdissel said about the identity missing. We *used* to have a good defensive check for that that I got lost, but this PR will put it back on the very next Nuget push: https://github.com/JasperFx/marten/pull/884

As for the Baseline thing, we're pulling our hair out a bit. Can you try explicitly adding the Baseline nuget? Pretty sure I'm going to break down and just inline the bits of Baseline we use into Marten to side step whatever it is that various Nuget clients can't handle.

**Comment by brainwipe** [comment]
We have a PEBKAC! Thank you guys, that was it. The documentation _is_ clear, I just failed to read it properly. Please do close this ticket - with a flourish if you feel the need.

@jeremydmiller - adding Baseline first _then_ adding Marten works. An OK workaround but will catch out newbies as it's an odd error from nuget. I'd like to get off nuget but we aim to "git clone then press F5" for our products.

**Comment by mysticmind** [comment]
@brainwipe with regards to Baseline Nuget issue, I think to have found out the issue, take a look my blog [post](https://medium.com/@babuannamalai/vs-2017-nuget-package-manager-dependency-resolution-issue-when-using-packages-config-ed5983c872a0) for details and resolution.
