### ISSUE TITLE
Make ViewProjection.ProjectEvent<> accept an IEvent instead of a ProjectionEvent.

### ISSUE THREAD

**Issue by adebisi-fa** [JasperFx/marten#894]
Hello,

I ran into a use-case where my **ViewProjection** handler requires the **StreamId**/**StreamKey** of an event; unfortunately, those are not available on ProjectionEvent.

Is there a technical reason why ViewProjection.**ProjectEvent<>** was made to accept a **ProjectionEvent** rather than just vanilla **IEvent** (as implemented in **Event**)?  

Why it can't just be:

```c#
vwProjection.ProjectEvent<Event<CharacterKilled>>(idOrIdsGenerator, projectionMutator);
```
instead of
```c#
vwProjection.ProjectEvent<ProjectionEvent<CharacterKilled>>(idOrIdsGenerator, projectionMutator);
```
?

I was able to create a working **ViewProjection.ProjectEvent<>** that's compatible with both **ProjectionEvent** and **IEvent** (so tests won't break). 

Can I send a pull request for this?

Thanks for the awesome work you guys are doing with Marten!  As a developer coming from NEventStore/LiquidProjection playground, Marten saves a whole lot of time and stress, and it's highly maintainable.

**Comment by adebisi-fa** [comment]
As an alternative, **ProjectionEvent** could be updated to include **StreamId** and/or **StreamKey**, along with other important properties of IEvent, with its constructor refactored to reflect this.

Whichever option, please.

Thanks.

**Comment by jeremydmiller** [comment]
@adebisi-fa Not sure what you mean. There isn't a class called `ProjectionEvent`, and you can get access to the `Stream` with metadata or the raw `Event<T>` objects in the projections

**Comment by adebisi-fa** [comment]
Hi @jeremydmiller,

> There isn't a class called ```ProjectionEvent```

It's there in the ```ViewProjection``` source file:  [```ProjectionEvent```](https://github.com/JasperFx/marten/blob/master/src/Marten/Events/Projections/ViewProjection.cs#L383) class.

An instance of the ```ProjectionEvent``` class was [created via reflection](https://github.com/JasperFx/marten/blob/master/src/Marten/Events/Projections/ViewProjection.cs#L340), with a subset of the ```IEvent``` object, viz:

```c#
private void appendProjections(List<EventProjection> projections, EventHandler handler, IDocumentSession session, IEvent streamEvent, Type eventType, bool isProjectionEvent)
        {
            object projectionEvent = null;
            if (isProjectionEvent)
            {
                var timestamp = streamEvent.Timestamp.UtcDateTime;
                projectionEvent = Activator.CreateInstance(
                    eventType,
                    streamEvent.Id,
                    streamEvent.Version,
                    // Inline projections don't have the timestamp set, set it manually
                    timestamp == default(DateTime) ? DateTime.UtcNow : timestamp,
                    streamEvent.Data);
            }
. . .
}
```
 
> Not sure what you mean.

I'm suggesting we:

1. Make ```ViewProjection.ProjectEvent<>(idSelector, handler)``` accept ```Event<>``` as a generic parameter, instead of the much limited ```ProjectionEvent<>``` (has only a subset of IEvent properties). ([This line refers](https://github.com/JasperFx/marten/blob/master/src/Marten/Events/Projections/ViewProjection.cs#L324)) The ```ViewProjection``` feature is awesome, as it makes multi-stream projections possible,

2. Include the missing properties of ```IEvent``` into ```ProjectionEvent```.

**Comment by jeremydmiller** [comment]
Ah, okay. Going to let @ericgreenmix take this one then;)

**Comment by ericgreenmix** [comment]
@adebisi-fa This seems like a good change to me. Go ahead and submit a PR and I will take a look at it. Thanks!

**Comment by adebisi-fa** [comment]
PR submitted #895.
