### ISSUE TITLE
Pending operations being performed in incorrect order

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#899]
I have an interface `IDocument` and an implementing type `InvoiceDocument`. I want to create a new version of an `InvoiceDocument`, but soft-deleting the old one and adding a new one:

```
// Load the existing version
var doc= await session.LoadAsync<InvoiceDocument>(myGuid);

// Soft-delete the existing version
session.Delete<InvoiceDocument>(myGuid);

// Change the ID of the document, so it can be added as a new version
doc.Id = Guid.NewGuid();

session.Store(doc);
```

I've configured a unique index to ensure there is only ever one version of each document with `mt_deleted = false` (that is, only ever one 'active' version) - so the order of operations is important; I need to soft-delete the existing version before adding the new one.

But Marten is trying to perform them out of order, so I get an exception. If I examine `session.PendingChanges._operations` just prior to the call to `SaveChanges()`, I see 2 values in the list:

1. Upsert the `InvoiceDocument`
2. Delete an `IDocument`

If I change the first line to:

`var doc= await session.LoadAsync<IDocument>(myGuid);`

... then it works, with both operations being added in the correct order in a single `_operations` list value. I guess there is some kind of issue with inheritance here?

**Comment by jeremydmiller** [comment]
What version of Marten are you on? I thought we'd finally managed to get the operations to run in exactly the order you cause them on IDocumentSession. And were you using an auto dirty checked session by chance?

**Comment by cocowalla** [comment]
I'm on the latest on Nuget, 2.3.2, and I'm using `LightweightSession()`

**Comment by jeremydmiller** [comment]
Would you mind making a PR with a failing test for this? It's perfectly possible that it's related to the type hierarchy here.

**Comment by cocowalla** [comment]
Sure, will do

**Comment by cocowalla** [comment]
I opened PR #900 with a failing test for this.

This is a bit of an odd one... the bug only seems to manifest when:

- there are multiple implementations of `BaseAccountingDocument`
- there are multiple levels of inheritance
- `BaseAccountingDocument` contains multiple properties with non-builtin types
