### ISSUE TITLE
Nested generic types can generate invalid table names.

### ISSUE THREAD

**Issue by mavnn** [JasperFx/marten#902]
Assume I have a generic type ``MartenStoredState<T>``

If I store a non-generic type in it (say string), all is well and a table is created called: ``mt_doc_postgresql_martenstoredstatestring``.

If I attempt to store an instance of "MartenStoredState<Dictionary<string, string>>" it instead tries to create a table called ``mt_doc_postgresql_martenstoredstatedictionarystring, string`` which breaks.

**Comment by mysticmind** [comment]
For the document class type, you should just use simple POCO class
(non-generic type). Within that class, you can have any number of
properties/fields including generics.

This is quite similar in comparison to how you define a model in Entity
Framework which translates to a table with the same name as your model
class in db.

**Comment by jeremydmiller** [comment]
@mavnn Why would you want to do that? It'd be ugly as all heck in your own code to use that over just `MyDocument : MartenStoredState<Dictionary<string, string>>`. I think if anything, the "fix" would be just a defensive programming exception to tell a user "don't do that"

**Comment by mavnn** [comment]
@jeremydmiller I have a long running workflow across multiple processes; any node on the cluster can pick up a work flow, load some state from Marten, and then persist an updated state for the next step to run (whenever and where ever that ends up being).

The workflow manager library is storing and retrieving the state from Marten, hence the "wrapper" generic type with an Id property.

The programmer defining the workflow defines the type of the state to be "stashed", and one of the first things tried (because people be lazy...) was to make the workflow state a Dictionary<string, string>. Individual workflow steps do not know or care what the "Id" of this instance of the workflow is, that's handled by the manager library behind the scenes.

So! That's the why... In terms of reporting it, I thought you'd want to know given that code has obviously been written to support generic types but seems to break here.

**Comment by jeremydmiller** [comment]
If this is really valuable then, I'd take a pull request to straighten out the derived table naming then

**Comment by mavnn** [comment]
Thanks @jeremydmiller !
