### ISSUE TITLE
Add ability to use existing Npgsql Connection and NpgsqlTransaction

### ISSUE THREAD

**Issue by SimonCropp** [JasperFx/marten#905]
I would like the ability to perform actions an existing Npgsql Connection and NpgsqlTransaction

so the connection would be open and the transaction in progress

so something like this
```
        var sessionOptions = new SessionOptions
        {
            ExistingConnection = myNpgsqlConnection,
            ExistingTransaction = myNpgsqlTransaction
        };
        using (var martenSession = martenStore.OpenSession(sessionOptions))
        {
```

and given the openening of the connection and the begin of the transaction  are done outside the scope of the marten session. then the cleanup and commit should also be outside the scope of the session.

**Comment by jeremydmiller** [comment]
@SimonCropp I'm working on this today. Shooting for end of next week on the 2.4 release if that's good enough

**Comment by SimonCropp** [comment]
That is awesome. Thanks
