### ISSUE TITLE
Double Take() query works incorrectly

### ISSUE THREAD

**Issue by KopIlya** [JasperFx/marten#906]
I used to describe the situation [link](https://github.com/JasperFx/marten/issues/261).
In query 
`var result = session.Query<T>().Take(10).Take(4).ToList();`
I expect `result` contain 4 elements. But `result.Count()` = 14.

**Comment by jeremydmiller** [comment]
@KopIlya The tests that we put in place for the original bug are all passing.

Just for fun, I tried your scenario above in master and this passes just fine:

```
        [Fact]
        public void one_more_try()
        {
            var targets = Target.GenerateRandomData(100);
            theStore.BulkInsert(targets.ToArray());

            var result = theSession.Query<Target>().Take(10).Take(4).ToList();
            result.Count.ShouldBe(4);
        }
```

**Comment by KopIlya** [comment]
Sorry. this is work. BUT!
`var result = theSession.Query<Target>().Take(10).Take(40).ToList();`
This is code returned 40 items. But after first `Take()` it should not take more than 10 items.

**Comment by jeremydmiller** [comment]
That's not how it's designed. Marten is coded now to honor the **last** `Take()` call if there are multiples.
