### ISSUE TITLE
When projecting documents in linq query, resulting `DateTime`s are of kind `Unspecified`

### ISSUE THREAD

**Issue by nikodemrafalski** [JasperFx/marten#908]
Hi, I'm getting inconsistent query results depending on if I'm projecting the documents inside the db or not.

`class Document
{
    DateTime SomeDate {get;set;}
   // other properties
}`

`class NarrowedDocument
{
    DateTime SomeDate {get;set;}
}`

When doing:
`var narrowed = await querySession.Query<Document>().Select(d => new NarrowedDocument{SomeDate = d.SomeDate}).ToListAsync`

the resulting DateTimes have Kind === Unspecified

`var docs = await querySession.Query<Document>().ToListAsync()`

the resulting DateTimes have kind set to UTC (other numeric values are same hour, minute etc_

I also tried to switch to DateTimeOffset type, bu then I'm getting another type of incosistency.
The projected data milliseconds number is being rounded

**Comment by oskardudycz** [comment]
@nikodemrafalski did you check https://www.npgsql.org/doc/types/datetime.html? It seems to be that it looks like default Npgsql behaviour. See also more in: https://github.com/JasperFx/marten/pull/1179/files#diff-1cba330cd6d502458bc5457860747537R9

**Comment by oskardudycz** [comment]
@nikodemrafalski I'm closing this issue, if you disagree with my comment, please send the feedback I'll open this issue again
