### ISSUE TITLE
ITransform projections are not created until something has been projected into them

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#920]
Problem:
If I have a transform `ITransform<MyEvent, MyProjection>` then the table for `MyProjection` is not created until the first event has been transformed. This is problematic if you are querying that projection with "regular" sql from somewhere else in the code.

Suggested solution:
When registering transforms in the docstore setup, if autocreate is enabled then automatically create the table for the transform.

Workaround:
When creating documentstore, `docStore.Tenancy.Default.EnsureStorageExists(typeof(MyProjection))`

**Comment by jeremydmiller** [comment]
@wastaz Hey, I responded in the Gitter room this morning. You might wanna check this out: http://jasperfx.github.io/marten/documentation/schema/migrations/.

**Comment by wastaz** [comment]
@jeremydmiller I am using `AutoCreate.All` though, shouldn't that be enough?

**Comment by jeremydmiller** [comment]
Not if you're writing SQL straight to document tables

**Comment by wastaz** [comment]
@jeremydmiller Ah, my bad. I thought that `DocumentStore` ought to pre-build the tables when its initialized. But that's maybe not the way it should work.

**Comment by jeremydmiller** [comment]
Yeah, no, we went with making it lazy for perf reasons in testing scenarios as I recall.
