### ISSUE TITLE
Cleaning Events per Stream

### ISSUE THREAD

**Issue by kwoodhouse** [JasperFx/marten#923]
As an enhancement to the cleanup capabilities, it would be nice to have a standard method to remove all event data for a given event stream.  My use case is dev testing of events, particularly the use of `expectedVersion`.

I had thought that `IDocument.Store.Advanced.Clean.DeleteAllDocuments()` would have worked thinking that event data was just another document.  Had to resort to `IDocument.Store.Advanced.Clean.CompletelyRemoveAll()`.

**Comment by jeremydmiller** [comment]
@kwoodhouse That would be a relatively simple pull request if you're interested in doing that

**Comment by kwoodhouse** [comment]
Looked around the code a little and found that `DeleteAllEventData`,  has been added.  Tried it out and it works as advertised.  Not on a per stream basis, but works for what I need at the moment.
