### ISSUE TITLE
Question: Migration in marten.

### ISSUE THREAD

**Issue by rdcm** [JasperFx/marten#924]
Hi!

My question about this article:
http://jasperfx.github.io/marten/documentation/schema/migrations/

In my app, at startup i have following code:
```
var connectionString = Configuration["json...section"];
...
services.AddSingleton<IDocumentStore>(InitializeDocumentStore(connectionString));
...

private static IDocumentStore InitializeDocumentStore(string connectionString)
{
	return DocumentStore.For(o =>
	{
		o.Connection(connectionString);
		o.Schema.For<Person>();
		o.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
		...
	});
}
```
Person class look like this:
```
public class Person
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```
After adding new field to Person class and restarting app, i expect updating existing documents, my expectation wrong?

What is the best approach for updating old documents?

**Comment by mysticmind** [comment]
@rdcm for the example use case which you have posted, any new documents which you add will have the new field in person. Marten won't update existing documents i.e. the json stored in the data column. You will need to use the patch api to transform the existing documents.

**Comment by rdcm** [comment]
@mysticmind  Ok, thanks for answer! But, what does this methods do?

```
store.Schema.ApplyAllConfiguredChangesToDatabase();
store.Schema.AssertDatabaseMatchesConfiguration();
```
For me its looks like marten took old document schema and compare it with new schema and after detect changes, apply changes to existing documents in db.

**Comment by jeremydmiller** [comment]
@rdcm All of those functions above are strictly for the *database* schema, and have nothing to do with the actual JSON document structure stuffed into the JSONB fields. 

Like @mysticmind said, you can use the patch API for simpler document structure changes, or if you really need to do something exotic or bigger to existing JSON documents, you've also got this: http://jasperfx.github.io/marten/documentation/documents/advanced/javascript_transformations/

**Comment by rdcm** [comment]
Ok, thanks all for replies!
