### ISSUE TITLE
System.ArgumentNullException when reading event log

### ISSUE THREAD

**Issue by RytisLT** [JasperFx/marten#928]
If event log contains an event type form not loaded assembly a ArgumentNullException is thrown because the dotNetType cannot be resolved see:

https://github.com/JasperFx/marten/blob/5bd4b03266ff4b91b565a9d58c8cfc87e5f42741/src/Marten/Events/EventSelector.cs#L45

**Comment by mysticmind** [comment]
@RytisLT can you please provide a repro test case for this issue?

**Comment by jeremydmiller** [comment]
@RytisLT What would you expect to happen here though? Better error message? Some facility to try to load the assembly? Some facility to move the event types?

**Comment by mysticmind** [comment]
@jeremydmiller immaterial of what we would eventually want to do based on reply from @RytisLT. We can check and add a better error message like `EventTypeNotFound` as a first step. Thoughts?

**Comment by jeremydmiller** [comment]
I don't have any better ideas tbh. We probably should be thinking about some kind of way to migrate events if the underlying .Net types change or move around.

**Comment by jeremydmiller** [comment]
We've got a better exception message now at the least in 2.9.0
