### ISSUE TITLE
AsPageList could be done with one database query

### ISSUE THREAD

**Issue by karelg** [JasperFx/marten#930]
AsPageList is executing two database queries, but can actually be implemented to use only one using the [Stats Linq operator](http://jasperfx.github.io/marten/documentation/documents/querying/paging/).

**Comment by mysticmind** [comment]
@karelg I don't think you could pull it off with one query since `Stats` will provide the total records for the specific query in question. For fetching paged records, we will need to find out the total records to compute the number of pages based on the page size and then fetch the records for a specific page.

**Comment by karelg** [comment]
@mysticmind I don't know if I'm missing something here, but I actually don't see any reason, why we can not fetch the page before computing the number of pages? _PageNumber_ and _pageSize_ should be sufficient input for that?

**Comment by mysticmind** [comment]
@karelg Probably I should have detailed this in my earlier comment, `AsPagedList` does a little more to provide you details such as PageCount, HasPreviousPage, HasNextPage, IsFirstPage, IsLastPage etc which requires 2 calls. This nicely dovetails with the requirements of  a navigation type interface and also can validate if a page number is valid.

Agree with you that if you are only interested in getting records for a page for a given page number and page size, you can directly use a LINQ query using `Skip` and `Take`, pull it off with a single query. You don't need to use `AsPagedList`.

**Comment by karelg** [comment]
@mysticmind I misunderstood from current [documentation](http://jasperfx.github.io/marten/documentation/documents/querying/paging/) that `Stats` was actually implemented as `IQueryable` extension method, but actually it's implemented as `MartenQueryable` method, so it's not currently possible to access this in `AsPagedList`, which operates over `IQueryable`. So I think, currently there is no simple way to make `AsPagedList` work with only a single round trip. Sorry for confusion.

**Comment by mysticmind** [comment]
@karelg Thanks for your reply. Can you please go ahead and close this issue?

**Comment by karelg** [comment]
@mysticmind Thanks! I will close this issue, given there is no trivial way for now to make 'AsPagedList' work with single round trip to database! But we can always easily implement a custom optimized paging solution for our applications using the 'Stats' method if performance is an issue.

**Comment by mysticmind** [comment]
@karelg FYI, I have refactored the AsPagedList implementation to use QueryStatistics which will result in a single round trip to db.
