### ISSUE TITLE
[DuplicateField] attribute does not create duplicate column in table for any array or list of primitives types

### ISSUE THREAD

**Issue by mysticmind** [JasperFx/marten#931]
If you have a document class as below:
```
public class Test
{
    public Guid Id { get; set; }
    
    [DuplicateField(PgType = "text[]")]
    public string[] Tags { get; set; } 
}
```

for the above case duplicate field does not get created. Same issue applies for say `List<string> Tags { get; set;}`. Effectively any array or list of primitives types have the same issue.

Note that if you add a duplicate field using StoreOptions, it works fine.

I have zeroed in on the issue to be with this code block in `DocumentMappings` as below:

https://github.com/JasperFx/marten/blob/99eeddcc384a4120a7c5bc1e25ba59b8997d92ca/src/Marten/Schema/DocumentMapping.cs#L82-L93

Properties and Fields are filtered based on `TypeMappings` which does not have array or list of the primitive types in type mappings.

I will add a repro test and will look at fixing the same.

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/marten/pull/936. Thanks @mysticmind !
