### ISSUE TITLE
LINQ expression not parsed correctly when querying inherited class with at least one OR in the query

### ISSUE THREAD

**Issue by VladanStojanovic** [JasperFx/marten#932]
The final query has `**or** mt_doc_type = 'INHERITED_CLASS'` instead of `**and** mt_doc_type = 'INHERITED_CLASS'` appended in where fragment, making the query ignore all conditions and just return all the data of inherited type.

Test class (based on existing tests in Marten.Testing/Bugs) is attached.

[Bug_932_or_query_in_inherited_class.zip](https://github.com/JasperFx/marten/files/1569706/Bug_932_or_query_in_inherited_class.zip)

**Comment by jeremydmiller** [comment]
@VladanStojanovic Instead of zip files, can you do a PR with the failing tests? That's a whole lot easier on us to consume and fix.

**Comment by VladanStojanovic** [comment]
@jeremydmiller Yep, doing it now. Thanks for the quick response.

**Comment by VladanStojanovic** [comment]
@jeremydmiller Added a PR. Will try debugging the tests and see if I can figure out anything else that can be helpful.

**Comment by VladanStojanovic** [comment]
The problem seems to stem from the way user-defined query is combined with doc type `where` fragment, always using the user-defined query's operator to combine them. User-defined query in `SubClassMapping.FilterDocuments` should be wrapped in a query utilizing the `and` operator before Appending the doc type fragment. But I don't know if it would break some other functionality.

A workaround is to always define your query with a clause that always evaluates to `true`, like so:

> session.Query<Doc>().Where(x => **true &&** (x.Id == 1 || x.Id == 2)).Count();

**Comment by jeremydmiller** [comment]
@kYann did a fix for this one. Will be in Marten 2.8.0.
