### ISSUE TITLE
Table delta not evaluating differences for USER-DEFINED type columns correctly

### ISSUE THREAD

**Issue by VladanStojanovic** [JasperFx/marten#934]
I have configured a postgis `geometry` as a duplicate column (property is of type Npgsql.PostgisPoint) like so:

> (..).Duplicate(x => x.Geolocation, "geometry")

Running `AssertDatabaseMatchesConfiguration` reports a difference in that duplicated column, because `data_type` returned by Postgres is `user-defined` and not `geometry`.

I propose changing the SQL in Table.cs `ConfigureQueryCommand` to make it properly handle user-defined data types.

From:
> select column_name, **data_type**, character_maximum_length

to:
> select column_name, **CASE WHEN data_type='USER-DEFINED' THEN udt_name ELSE data_type END AS data_type**, character_maximum_length 

Would that kind of change break some other functionality (all tests seem to pass)?

I can create a pull request with the proposed change if you think the change is safe.

**Comment by jeremydmiller** [comment]
If all the tests pass, that's fine by me -- and probably 2/3 of the tests would hit that query, so it's probably covered well;)

What are you doing with the Postgis functionality? We've had other folks ask about it from time to time, but we've never added any direct support because we didn't have concrete use cases to develop against.

**Comment by VladanStojanovic** [comment]
Nothing too fancy with Postgis, I just have a point that I want to be able to apply geometric SQL queries easily to and have Marten read/write it properly. That works ok.

There seems to be another issue with schema diff when using `CreateOrUpdate` - `hilo` table always gets recreated because Marten generates the column type as `biging default(0)` and compares with `bigint` from the query referenced above. Will try to include a fix for that in the pull request as well.

**Comment by VladanStojanovic** [comment]
Aah. Fixing the hilo comparison issue just lead me to issue with function comparison, which is not that trivial. The generated and function returned from Postgres don't seem to be that different, though (only the delimiters, language directive position etc).

**Comment by jeremydmiller** [comment]
@VladanStojanovic Hey, do you have this PR you could submit? Even if the function comparison is failing. I can address that one when I pull it in.

**Comment by jeremydmiller** [comment]
Duplicate issue with #959
