### ISSUE TITLE
Conversion Issue

### ISSUE THREAD

**Issue by bobmcallan** [JasperFx/marten#937]
The following SQL statement, should convert to the class, however results in the following cast error: "GetTextReader() not supported for type int4",

SQL
-----------------------------
select  Count(*)::integer as Count, 
                                    (d.data ->> 'Level')::text as Level, 
                                    (d.data ->> 'Level')::text as Name, 
                                    date_trunc('hour', (d.data ->> 'DateTimeStamp')::timestamp with time zone) as DateTimeStamp,
                                    2 as Type
                              from public.mt_doc_eventcache as d 
                             where (d.data ->> 'CacheType')::int = 0
                             group by (d.data ->> 'Level'), date_trunc('hour', (d.data ->> 'DateTimeStamp')::timestamp with time zone);"

 
Class
-----------------------------
public class Counter
{
        public string Name { get; set; }
        public string Level { get; set; }
        public int Count { get; set; }
        public DateTimeOffset DateTimeStamp { get; set; }
 }

Code
-----------------------------
using (var session = store.LightweightSession())
{
       return session.Query<Metric>(query).ToList();
}

**Comment by jeremydmiller** [comment]
@bobmcallan What you're doing just isn't going to work, because that method doesn't really support custom SELECT clauses. Why would you want to do it that way?

**Comment by bobmcallan** [comment]
Primary reason for writing the custom SQL was to perform a 'group by'. I could not locate this function in the documentation.

**Comment by jeremydmiller** [comment]
@bobmcallan Sorry, but you're going to have to do that one completely by hand. We have an open story to add GroupBy support to the Linq provider, but other than a quick spike one day last year nothing has happened with that.

**Comment by bobmcallan** [comment]
Thanks for the advise. Great library and documentation, very easy to set up.
