### ISSUE TITLE
Ability to pass in instance of Aggregate when applying events for a Stream

### ISSUE THREAD

**Issue by Sacrelicious** [JasperFx/marten#939]
We need to supply some external information to the Aggregate we are building to support Applying certain events, as such we need to be able to pass in an instantiated instance of the Aggregate type, instead of just relying on `new T()` every time we call `AggregateStream<T>...`

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/commit/502793528001c9144e3c6c4ac2d3c56c9c0aa936
