### ISSUE TITLE
DocumentStorage code generation fails under DNX (dnx451)

### ISSUE THREAD

**Issue by tetious** [JasperFx/marten#94]
When running under DNX, Rosyln generates project assemblies dynamically in memory; they have no location on disk. This means assembly.Location is empty, which makes the current code generation strategy fail when it tries to add the MetadataReference:

```
_references.Add(MetadataReference.CreateFromFile(assembly.Location));
```

I'm not sure how to fix this in a non-hacky way without changing the overall strategy away from code generation. Perhaps using some form of reflection based system that generates lambdas via expression trees?

**Comment by jeremydmiller** [comment]
@tetious 

"Perhaps using some form of reflection based system that generates lambdas via expression trees?" -- been there, done that, no thank you. Let me bug the Roslyn guys about that and see what they say because I can see some SO threads where this has come up before. There's surely a way to get around that.

There *is* a way to do this that's marked [Obsolete]: https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/MetadataReference/MetadataReference.cs#L260-L265

Thanks for the heads up.

**Comment by tetious** [comment]
Yeah, I did look at the obsolete method. It is using Location internally, and throws a NotSupportedException if Location is empty. 

I poked around in the roslyn project and found a PR where they added that exception seemingly in response to someone reporting this problem:
https://github.com/dotnet/roslyn/pull/6254

**Comment by jeremydmiller** [comment]
Ugh, okay. You can see my discussion w/ @pilchie on twitter (@jeremydmiller). I've got nothing offhand. I hate to say this, but my thought for right now is to hope for a fix from their side.

**Comment by Pilchie** [comment]
I'm not aware of a way offhand to resolve this.  You'd probably have to track back to where the `Assembly` is created, pass the bytes along and use something like `CreateFromStream()`.

**Comment by jeremydmiller** [comment]
That won't quite work because we're going to need to have the application assemblies holding the user's document types that are going to be outside of this codebase.

**Comment by Pilchie** [comment]
Hey @gkhanna79 - is there a way to get back to a `byte[]`/`Stream` for a given `Assembly`?

Also tagging @tmat.

**Comment by tmat** [comment]
TryGetMetadata might be what you're looking for:
https://github.com/dotnet/corefx/issues/2768

**Comment by jeremydmiller** [comment]
@tmat @Pilchie Is that extension method only in the CoreCLR version of System.Reflection? I'm assuming yes.

**Comment by tmat** [comment]
@jeremydmiller Correct. There is no such API on desktop CLR.

**Comment by jeremydmiller** [comment]
@tetious So it looks like we *could* address the DNX + CoreCLR combination here (assuming that Npgsql supports CoreCLR now), but not .Net 4.5-4.6 + DNX. Doing the CoreCLR multi-targeting thing for the nugets I control is just an exercise in mild tediousness, but we'd be dependent upon everything else supporting it too.
