### ISSUE TITLE
[DuplicateField] on a non-primitive data type

### ISSUE THREAD

**Issue by AKlaus** [JasperFx/marten#942]
I have the following model:
```
    public class Document
    {
	[DuplicateField]
        public DateTime Timestamp { get; set; }
	[DuplicateField]
        public IEntityReference RelatedTo { get; set; }
        ...
    }

    public interface IEntityReference
    {
        Guid Id { get; }
        string Name { get; set; }
    }
```
where I'd like to improve performance on querying by `RelatedTo.Id`. 

The recommended way is to [duplicated fields for faster querying](http://jasperfx.github.io/marten/documentation/documents/customizing/duplicated_fields/), so I tried to add `DuplicateField` attribute, but it didn't generate a new column(s) on the table.

Therefore
- How hard would be to add a parameter to `DuplicateField` to indicate which property of the linked object we want to duplicate in the table (e.g. `DuplicateField(nameof(IEntityReference.Name))`)?
- Is there a way to setup mapping between a duplicated field/column in the table and a field in the data model?
- Is there a benchmark on querying by a duplicated field vs a JSON field?

P.S. To give you some context, the structure above is used to avoid including related documents when  most of the requests use just a small field set from the related entity (in this case just `ID` and `Name` fields).

**Comment by jeremydmiller** [comment]
@AKlaus You can use a calculated index against RelatedTo.Name to get what you're looking for here. See http://jasperfx.github.io/marten/documentation/documents/customizing/computed_index/

**Comment by mysticmind** [comment]
@AKlaus DuplicateField attribute not creating duplicate field is a bug, ref to #931. It has been already fixed and will be available in the next release.

**Comment by mysticmind** [comment]
@AKlaus FYI, I removed my comment since it is not correct as an answer.
