### ISSUE TITLE
IDocumentSession in ViewProjections handlers

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#946]
I have a bit of a...let's just say "special"...data model in one of my applications using Marten. And in order to perform the projections that I need to do I need to get access to an `IDocumentSession` in the actual handler methods in my viewprojection. 

While I can do this by just creating a new `IDocumentSession` in my handlers that will cause them to be enlisted in a separate transaction from the view updating which feels wrong (also, causing an unnecessary extra trip to postgres).

Basically what I do today is something like

```
public class MyProjection : ViewProjection<MyData, Guid>
{
    private readonly IDocumentStore _store;

    public MyProjection(IDocumentStore store)
    {
        _store = store;
        ProjectEvent<MyEvent>(x => x.Id, Handle);
    }

    private void Handle(MyData entry, MyEvent evt)
    {
        using(var session = _store.LightweightSession())
        {
            var other = session.Load<OtherThing>(evt.OtherId);
            entry.Other = other.Blah;
        }
    }
}
```

This is of course a very simple and basic example, I have some more complex stuff done in other places. But basically it would be nice to instead be able to write the handler just like this

```
    private void Handle(IDocumentSession session, MyData entry, MyEvent evt)
    {
        var other = session.Load<OtherThing>(evt.OtherId);
        entry.Other = other.Blah;
    }
```

...and having the `IDocumentSession` instance be the same instance as used by the ViewProjection base class.

This change could easily be backwards compatible, it would just involve adding some more overloads to `ProjectEvent` and `ProjectEventAsync` in `ViewProjection` and passing the session along.

I can send you a PR with this feature if it feels like a good idea :)

**Comment by ericgreenmix** [comment]
I just want to mention with this issue that when using the `IDocumentSession` in the Handler like shown above can be dangerous. Loading other documents in this case gives your projection a dependency on those documents and the current state of that document at the time the projection was built. If you have to go back and rebuild your projection, and the state of your dependent document has changed, it can lead to your projected document being inconsistent in state for a given point in time of the event stream.

I would highly suggest augmenting your events, if possible, and avoid doing any type of querying of other documents in the projection itself.

**Comment by wastaz** [comment]
@ericgreenmix Yes, this is true. In this case though I am using it in an "eventsourced" model where I must be able to forget some data completely without actually rewriting the stream, and in this certain case what you are describing is actually a feature in this specific case (and putting the data in the events would either give me a ton of trouble with the lawyers or require me to go in and rewrite events in the stream).
