### ISSUE TITLE
Connection is not disposed when opening inside transaction

### ISSUE THREAD

**Issue by jacobpovar** [JasperFx/marten#949]
Hi, first of all I want to thank you for this awesome library!

I've encountered an issue when using event store with implicit transaction scope: connections to database opened by marten never get closed. 
This behaviour can be reproduced by running test `enlist_in_transaction_scope` and executing sql query  
```
select *
from pg_stat_activity
where datname = 'postgres'
```
after 
`scope.Complete()` is called but before DocumentStore is disposed. There should be two open connections. And since documentStore is singleton object, in production environment Marten never closes such connections, eventually leading to postgres exception.  

To my understanding that is happening because of this:

-  When calling `buildManagedConnection` new connection is opened by Marten and `commandRunnerMode` is set to `CommandRunnerMode.External`. 
```
// Hate crap like this, but if we don't control the transation, use External to direct
            // IManagedConnection not to call commit or rollback
            if (!options.OwnsTransactionLifecycle && commandRunnerMode != CommandRunnerMode.ReadOnly)
            {
                commandRunnerMode = CommandRunnerMode.External;
            }

            if (options.Transaction != null) options.Connection = options.Transaction.Connection;

#if NET46 || NETSTANDARD2_0
            if (options.Connection == null && options.DotNetTransaction != null)
            {
                var connection = tenant.CreateConnection();
                connection.Open();
               ....

```
 
- when committing changes connection disposal is skipped due to external mode. 

```
public void Commit()
        {
            if (_mode == CommandRunnerMode.External) return;
```

As a temporary workaround I open connection manually and pass it to session. Everything works fine. But it would be awesome if this can be fixed inside marten itself. 

Thanks. Jacob.

**Comment by jeremydmiller** [comment]
@jacobpovar Connections aren't being closed when you dispose the IDocumentSession? Can you put a little more information about how you're using Marten?

**Comment by jacobpovar** [comment]
@jeremydmiller yes, connections are being left open. 
Here is small example that illustrates the issue: 

```
    static void Main(string[] args)
    {
        using (var theStore = DocumentStore.For(storeOptions =>
        {
            var connectionString = 
                "User ID=postgres;Password=...;Host=localhost;Port=5432;Database=postgres;Pooling=true;Maximum Pool Size=200;";
            storeOptions.Connection(connectionString);
        }))
        {
            for (int i = 0; i < 1000; i++)
            {
                // this reaches 200, than crashes
                
                Console.WriteLine($"Inserting {i}");
                using (var scope = new TransactionScope())
                {
                    using (var session = theStore.OpenSession(SessionOptions.ForCurrentTransaction()))
                    {
                        session.Store(new EntityToSave());
                        session.SaveChanges();
                    }

                    scope.Complete();
                }
            }
        }
    }

    class EntityToSave
    {
        public Guid Id { get; set; }
    }


```

**Comment by jeremydmiller** [comment]
I'm looking at this now finally

**Comment by jeremydmiller** [comment]
Actually, first question. Why do you need to use the TransactionScope here?

**Comment by jacobpovar** [comment]
I had a requirement to write both to marten and other data source inside same transaction scope. 

the example posted above is slightly modified version of the test `enlist_in_transaction_scope` from  `ability_to_use_an_existing_connection_and_transaction` only repeated. 
there is no reason to open transaction explicitly there but it shows the problems.

**Comment by jacobpovar** [comment]
@jeremydmiller thanks!
