### ISSUE TITLE
Deleting Documents & Multi-Tenancy 

### ISSUE THREAD

**Issue by abrovko** [JasperFx/marten#950]
Is it possible to explicitly specify tenant id when a document is being deleted?
I found how to query documents from all tenants (Where(i => i.AnyTenant()))
It is also possible to store document explicitly specifying tenant id (session.Store with tenantId parameter)
I just can't figure out how to delete a document if I have a session not bound to a tenant. 
I tried DeleteWhere<>(i => i.AnyTenant() && i.Id == me.Id) but it does not seem to be working. Did I miss anything or the only option would be to create a new session for a specific tenant and delete from there?

**Comment by jeremydmiller** [comment]
@abrovko No, we don't have that today, but this has come up before. I don't see any open enhancement issue for this in the backlog today, but it is something I'd accept as a PR.

**Comment by abrovko** [comment]
Thanks for the quick response. I quickly checked hoping to just replicate code from Store(tenantId...). But it does not seem to be that straightforward. I am new to Marten, just started poking around yesterday, but I will see if I can figure this out.

**Comment by jeremydmiller** [comment]
We'll need this for #952 as well. The `IDocumentSession` needs overloads of `Store()`, `Insert()`, `Update()`, and `DeleteWhere` that allows you to specify a tenant id

**Comment by jeremydmiller** [comment]
Basically done in a branch.
