### ISSUE TITLE
Async Daemon & Multi-Tenancy

### ISSUE THREAD

**Issue by abrovko** [JasperFx/marten#952]
Async Daemon & Multi-Tenancy - is this scenario currently supported? 
It looks like when async demon applies projections it uses the DEFAULT tenant. As a result ViewProjection results are stored under the DEFAULT tenant. Or if I implement IProjection manually - I also get session bound to the DEFAULT tenant and have to remember to explicitly specify tenantid everywhere or create a new tenant specific session but in this case it is not clear how to manage it in terms of transactions\unit of work

**Comment by jeremydmiller** [comment]
@abrovko No, it doesn't. There *should* be an open issue for adding this support, because I know I didn't get this done in the 2.0 release.

**Comment by jeremydmiller** [comment]
Replaced by #1609
