### ISSUE TITLE
EnsureStorageExists fails on subsequent calls if an index name is greater than 63 chars

### ISSUE THREAD

**Issue by barryhagan** [JasperFx/marten#953]
If the combination of a class name and property cause an index identifier to be greater than 63 characters, the index id will be silently truncated during creation by the Postgresql database the first time it is added.

Then, if EnsureStorageExists(Type documentType) is called again for this type, it will always fail because it is attempting to delete and recreate the index but does not account for the actual truncated index name.

-- Marten.Storage.DocumentTable
CREATE INDEX mt_doc_longenoughnametocauseidtruncation_idx_why_would_you_name_something_this_long ON public.mt_doc_longenoughnametocauseidtruncation ((CAST(data ->> 'WhyWouldYouNameSomethingThisLong' as uuid)));

-- Marten.Storage.DocumentTable
drop index concurrently if exists public.mt_doc_longenoughnametocauseidtruncation_idx_why_would_you_name;

Npgsql.PostgresException : 42P07: relation "mt_doc_longenoughnametocauseidtruncation_idx_why_would_you_name" already exists

**Comment by barryhagan** [comment]
```
    public class LongEnoughNameToCauseIdTruncation
    {
        public Guid Id { get; set; }
        public Guid WhyWouldYouNameSomethingThisLong { get; set; }
        public Guid ShortEnough { get; set; }
    }

    public class Bug_953_index_identifier_length
    {
        [Fact]
        public void can_ensure_storage_with_index_id_greater_than_63_bytes()
        {
            using (var store1 = TestingDocumentStore.For(_ =>
            {
                _.Schema.For<LongEnoughNameToCauseIdTruncation>().Index(x => x.WhyWouldYouNameSomethingThisLong);
            }))
            {
                store1.Tenancy.Default.EnsureStorageExists(typeof(LongEnoughNameToCauseIdTruncation));

                store1.Schema.ApplyAllConfiguredChangesToDatabase();

                store1.Tenancy.Default.EnsureStorageExists(typeof(LongEnoughNameToCauseIdTruncation));
            }
        }
    }
```

**Comment by jeremydmiller** [comment]
@barryhagan It should have been warning you about identifiers that are too long in Marten. There is a setting in Postgresql itself where you can move the limit up so it doesn't mangle your names.

**Comment by barryhagan** [comment]
I saw that `PostgresqlIdentifierTooLongException` is thrown from AssertValidIdentifier() on StoreOptions, but that code is only used by unit tests.

Changing the NAMEDATALEN property requires a recompile, which I can't do using Postgres with AWS RDS.

**Comment by jeremydmiller** [comment]
@barryhagan I'm gonna finesse this one a little bit just today. All I'm doing is adding an assertion on the name lengths so it'll blow up if you go over your namedatalength. I'll add an ancillary issue to make sure that all db object names can be modified for 2.7.0 soon-ish
