### ISSUE TITLE
Events StreamId in multi tenant scenario

### ISSUE THREAD

**Issue by abrovko** [JasperFx/marten#954]
In my app I derive event stream ids from ids coming from an external source. On the external source IDs are unique within a tenant (that system is also multi-tenant), but there is no guarantee that IDs are globally unique. 
Looking a the mt_events table
`CONSTRAINT pk_mt_events_stream_and_version UNIQUE (stream_id, version),`
currently stream_id is supposed to be globally unique. I would expect it to be unique only within a tenant, similar to how document ids are unique within a tenant. Otherwise I will have to include tenantid into  stream_id to ensure global uniqueness which I think defeats the purpose of built-in multi-tenancy. 
Is this just an oversight\missing feature or am I using stream_ids incorrectly?

**Comment by jeremydmiller** [comment]
You're simply bumping into the fact that this is an OSS project where the primary author does not have infinite bandwidth. We know there are missing features for the event store + multi-tenancy, and we also know it'd help to have some level of sharding and probably more identity options. The event store is the place where I need to most help, so if you're volunteering....

**Comment by abrovko** [comment]
I absolutely understand and accept that. 
In terms of real usage I am new to almost everything here starting from document databases to event sourcing and to Marten itself. Sorry for asking obvious things. Just want to make sure I am not missing anything before working on potentially crazy workarounds.

With this specific issue - it seems to be pretty straightforward. Events\streams tables always include tenantid column, so it looks like it is just a matter of changing constraints to include tenantid and then updating mt_append_event function accordingly. Does it sound about right? I can try to create a PR for this. 
Also so far I could not figure out how Migrations work or where to add a migration to update constraints and the function on existing databases

**Comment by jeremydmiller** [comment]
"With this specific issue - it seems to be pretty straightforward." -- it's not simple or straightforward at all if you look at all of the usage. Yes, changing the constraint would be easy, but you'd have to change a lot of internals in the event store to be tenant aware to effectively use composite keys. And most of the time it's not multi-tenanted. 

I'm sorry, but this isn't likely to be changed any time soon and I'm going to close this just in the name of bookkeeping.
