### ISSUE TITLE
AutoCreate.CreateOrUpdateOnce

### ISSUE THREAD

**Issue by mariusin79** [JasperFx/marten#958]
We are using a different patching tool than Marten, which means that we are handling table and index creation outside of Marten. We do not however want to fiddle with the insert/upcerts/hilo/function-stuff as we consider that to a part of the framework. We have managed to get Marten and RoundhousE (db-patching tool) to work together by using the AutoCreate.CreateOrUpdate - mode, which ensures that Marten will lay off our generated tables and indexes and still generate the upcerts/etc. But: if I profile I see that Marten keeps checking the schema all the time. 

It would be great to have an option to do "CreateOrUpdate" - once and then get on with it. AutoCreate.None does not do the trick because then I have to maintain all the functions as well (you know "schema less" = "less schema" :-)). AutoCreate.CreateOnly does not seem to patch upcerts so no dice there ether.

Cheers

**Comment by jeremydmiller** [comment]
@mariusin79 You already have the ability to force Marten to update all the known storage upfront. Why or how is this any different?

**Comment by mariusin79** [comment]
Do you have a reference to the documentation on that? Or a short explanation on how/which method to invoke?

**Comment by jeremydmiller** [comment]
I was just talking about the `ApplyAllConfiguredChangesToDatabase()` method here: http://jasperfx.github.io/marten/documentation/schema/migrations/

**Comment by mariusin79** [comment]
Which I am already using in my example, if you look at it. Perhaps if you have a tip on less verbose/smoother way of doing it than I am doing it above you can share it.

**Comment by mysticmind** [comment]
GH-1330 has the ability to set `AutoCreate.None` for `DocumentStore.StoreOptions` and independently run `ApplyAllConfiguredChangesToDatabase` once as you see it fit. This is scheduled to be available in 3.7.0

**Comment by oskardudycz** [comment]
Fixed by https://github.com/JasperFx/marten/pull/1330 and already available in `v3.7.0`
