### ISSUE TITLE
DocumentStore ctor calls IInitialData.Populate before all store properties are set

### ISSUE THREAD

**Issue by KahuKirikiri** [JasperFx/marten#962]
Opening an `IDocumentSession` inside an implementation of `IInitialData` will cause a null reference exception as the `DocumentSession` ctor tries to construct a new `EventStore`.

**Found in:** 2.5.0

**Here's a test to prove the bug**
```c#
public class bug_initial_data_opening_session_causes_null_ref_ex
{
    [Fact]
    public void open_session_in_initial_data_populate()
    {
        var ex = Exception<NullReferenceException>.ShouldBeThrownBy(() =>
        {
            var store = TestingDocumentStore.For(_ =>
            {
                _.InitialData.Add(new TestingInitialData());
            });
        });
    }

    public class TestingInitialData : IInitialData
    {
        public void Populate(IDocumentStore store)
        {
            using (var session = store.LightweightSession())
            {
            }
        }
    }
}
```
**Bug is happening because the `DocumentStore.Events` property is not set until after the `InitialData` is populated and opening the session will eventually try to access the `Events`. See the `DocumentStore` ctor**
```c#
public DocumentStore(StoreOptions options)
{
    // ...code excluded for brevity

    options.InitialData.Each(x => x.Populate(this));

    // ...code excluded for brevity

    Events = options.Events;
}
```
**Possible fixes**
Either move the mappings of the `StoreOption` properties to their corresponding `DocumentStore` properties to earlier in the `DocumentStore` ctor.
```c#
public DocumentStore(StoreOptions options)
{            
    options.ApplyConfiguration();
    options.CreatePatching();
    options.Validate();
    Options = options;

    // MOVE MAPPINGS HERE
    _logger = options.Logger();
    Events = options.Events;
    Tenancy = options.Tenancy;
    Storage = options.Storage;
    Serializer = options.Serializer();

    // ... rest of the code as is
}
```
Or, given that those properties are all read only anyway we could just read their values from `Options` (which is also read only).
```c#
public ITenancy Tenancy { get { return Options.Tenancy; } }

public EventGraph Events { get { return Options.Events; } }

etc
```

**Comment by jeremydmiller** [comment]
@KahuKirikiri I'd rather just do the calculated getters to avoid this issue. Do you feel like doing the PR? Looks like you're already on it.

**Comment by KahuKirikiri** [comment]
@jeremydmiller Will do. You'll see from my forked branch that I also had to upgrade xunit and its Visual Studio runner in order to get the tests to run on the latest version of VS

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/marten/pull/972
