### ISSUE TITLE
AssertDatabaseMatchesConfiguration does not work when AutoCreate.None

### ISSUE THREAD

**Issue by afmuller** [JasperFx/marten#965]
It appears that when AutoCreateSchemaObjects = AutoCreate.None, store.Schema.AssertDatabaseMatchesConfiguration() does not detect if the schema is up-to-date or not (i.e. it does not throw an exception if the schema does not match configuration). 

In production, I need to check if the database schema is up-to-date or not and I wanted to use AssertDatabaseMatchesConfiguration - but cannot use it if AutoCreateSchemaObjects = AutoCreate.None (which I presume is the correct setting in production).

Is this by design? Or is this a bug?

**Comment by jeremydmiller** [comment]
You’re going to have to provide a lot more context about what you’re seeing and trying to do. We do have passing tests on AutoCreate.none and no, we didn’t purposely put out misleading or nonfunctional code. I can’t fix “it doesn’t work,” but we most likely can if you can give a much better bug report here

**Comment by afmuller** [comment]
My apologies - I have found a work-around and will close this issue.
I am very impressed with Marten and did not mean to insinuate anything. 
Thank you for a great product.

**Comment by gunndabad** [comment]
@jeremydmiller I have a question along these lines too. Given an empty/invalid database and AutoCreateSchemaObjects set to AutoCreate.None, AssertDatabaseMatchesConfiguration() does not throw. When set to AutoCreate.All it does throw.

```
public class Document
{
    public int Id { get; set; }
}
...
var store = DocumentStore.For(cfg =>
{
    cfg.Connection(connStr);
    cfg.Schema.For<Document>();

    cfg.AutoCreateSchemaObjects = AutoCreate.None;
});

store.Schema.AssertDatabaseMatchesConfiguration();  // does not throw
```

I was under the impression that AutoCreateSchemaObjects was to control whether Marten would automatically patch up the schema.

**Comment by jeremydmiller** [comment]
@gunndabad Dunno offhand, that code has changed so many times by so many folks. Wanna a separate issue for that?

**Comment by gunndabad** [comment]
@jeremydmiller Done: https://github.com/JasperFx/marten/issues/983
