### ISSUE TITLE
Exclude types from multi-tenancy

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#966]
From the docs, we can apply multi-tenancy by default using either of

```
storeOptions.Policies.AllDocumentsAreMultiTenanted();
storeOptions.Policies.ForAllDocuments(x => x.TenancyStyle = TenancyStyle.Conjoined);  
```

The docs also show how to override a single-tenant policy by making a specific type multi-tenanted:

```
storeOptions.Policies.ForAllDocuments(x => x.TenancyStyle = TenancyStyle.Single);  
storeOptions.Schema.For<Target>().MultiTenanted();
```

I'd like to do the opposite though, setting all types as multi-tenant by default, and then excluding a couple of types:
```
storeOptions.Policies.ForAllDocuments(x => x.TenancyStyle = TenancyStyle.Conjoined);
storeOptions.Schema.For<Target>().... // ?
```
Can this be done?

**Comment by jeremydmiller** [comment]
You've got a couple options, I think mostly documented here: http://jasperfx.github.io/marten/documentation/documents/customizing/. You *could*:

1. Use a custom attribute to opt out or into the multi-tenancy
1. Use a custom document policy to switch multi-tenancy on or off depending on your own app's rules: http://jasperfx.github.io/marten/documentation/documents/customizing/document_policies/

**Comment by cocowalla** [comment]
Option 2 looks good - not sure why I hadn't seen this in the docs before.
