### ISSUE TITLE
fetch event stream by range

### ISSUE THREAD

**Issue by jinhong-** [JasperFx/marten#967]
Is there any way to fetch event stream by a start and end range? I only see APIs to fetch events up till a certain version

**Comment by jeremydmiller** [comment]
@jinhong- You can use `IDocumentSession.Events.QueryAllRawEvents()` to run Linq queries against the raw event data that will let you query on any element of the event store metadata. That should get you what you want here.

**Comment by jinhong-** [comment]
Ah okay thanks!
