### ISSUE TITLE
Async Daemon Cluster

### ISSUE THREAD

**Issue by jinhong-** [JasperFx/marten#969]
Hi, any support for async Daemon clustering? Basically the idea is to have hot spares or some sort of load distribution mechanism so that multiple async daemons can be ran at the same time

**Comment by jeremydmiller** [comment]
Not at the moment, but I've got a concept to do that using Postgresql advisory locks somewhat like I talk about in this blog post: https://jeremydmiller.com/2018/02/06/durable-messaging-in-jasper/.

**Comment by jinhong-** [comment]
I managed to solve this by utilizing the Start function, I was able to split each ViewType processing into different nodes by using Consistent Hashing and Consul for node discovery. Seems to work well enough and since the Aggregate is pretty much idempotent there isn't a worry of duplicate writes. Still, i am very interested in a built in/recommended solution

**Comment by jeremydmiller** [comment]
@jinhong- What I was suggesting isn't that dissimilar to what you already did. Any chance I could talk you into writing something up for our docs about how you did that? Or at least doing that here?

**Comment by jinhong-** [comment]
@jeremydmiller I recently started a blog and decided to put the information on how I achieved it inside. If you do not mind I could share the link here

**Comment by jeremydmiller** [comment]
@jinhong- Please do share the link here. Makes Marten look a whole lot better if other folks blog about it;)

**Comment by jinhong-** [comment]
Here it is. Enjoy! https://jin.ministry-of.tech/scaling-out-with-marten-async-projections-daemon/

**Comment by jeremydmiller** [comment]
I'd still like to come back and have some out of the box solutions for this. One possible approach would be to use postgresql advisory locks to take control of one view type at a time. Then the "cold" nodes would keep polling to try to take over the async daemon later.

**Comment by jeremydmiller** [comment]
This is being subsumed into #1609
