### ISSUE TITLE
Make HiLo's Lo value configurable. 

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#97]
Currently the default is 1000, starting / stopping my app during development means my IDs jump very high very quickly. 

While it would be nice to set the `Lo` on a document collection basis. 

For now it would be great to configure this globally. Something like:

```c#
public interface IHiLoSettingProvider
{
    public int Lo { get; }
}

public class DevelopmentHiLoSettings : IHiLoSettingProvider
{
    public int { get { return 32; } }
}

var store = Marten.DocumentStore.For(_ =>
{
    _.HiLoSettings(new DevelopmentHiLoSettings());
});
```

Or something like that. 

Hope that makes sense.

**Comment by phillip-haydon** [comment]
Also:

http://jasperfx.github.io/marten/documentation/documents/document_ids/

The link to HiLo is broken.

![image](https://cloud.githubusercontent.com/assets/895629/11899831/d496a24c-a5dc-11e5-8283-b8ef9aa5c50f.png)

**Comment by jeremydmiller** [comment]
@phillip-haydon We can do that, and I'll fix the link too;)

**Comment by jeremydmiller** [comment]
@phillip-haydon Were you thinking that you'd want this to be configurable per document type, or per the entire schema?

**Comment by phillip-haydon** [comment]
Both. 

For dev I just wanna globally set it lower. In production would be nice to set low frequent inserted docs to a low Hi, while frequent inserted docs to have a larger Hi.

**Comment by phillip-haydon** [comment]
:+1: :shipit:
