### ISSUE TITLE
Fetching meta data for multiple records

### ISSUE THREAD

**Issue by jansivans** [JasperFx/marten#971]
I need to fetch meta data for multiple items. I can do this by using `MetadataFor` for each item, but this becomes slow if I have many records.

**Use-case**
Imagine I have an object with fields `field1` and `field2`. I now want to return to user a list of these objects with additional fields `isDeleted` and `lastUpdated`.
Currently to accomplish this I need to fetch all objects then fetch meta data for each object and finally merge fetched information together.

**Request**
Add a method to fetch meta data for multiple records or allow to fetch meta data at the same time as you do actual data fetching.

**Comment by mysticmind** [comment]
@jeremydmiller can you please review this to see if we need to keep it open as an enhancement or close this.

**Comment by jeremydmiller** [comment]
Meh, I don't know. It's not huge, but I don't see it being super commonly used either. I think I vote to close.

**Comment by jeremydmiller** [comment]
Here, I'm calling this one. I don't think this would get used enough to be justified
