### ISSUE TITLE
Async Daemon Start always rebuilds

### ISSUE THREAD

**Issue by jinhong-** [JasperFx/marten#979]
Async Daemon Start does not have the same behavior as StartAll. It will always replay event streams from the beginning rather than from the last known position. I digged a little and realized it is because StartAll calls findCurrentEventLogPositions. And this isn't present is Start

**Comment by jeremydmiller** [comment]
@jinhong- Feel like shooting us a little PR to do that check? Not something that ever got tested apparently.

**Comment by jinhong-** [comment]
i discovered it while trying to create some sort of clustering. I don't mind doing a PR for this but I am not sure what is the best way to approach this. It isn't an issue for StartAll, but with Start it's a different story. If we were to put the update code into Start as well, what if i called Start multiple times? That would mean that I will hit the database several times to get the position. What if we exposed yet another method called StartMultiple as well? So that we're able to decrease the number of times the database is hit
