### ISSUE TITLE
Querying does not create document collections (tables)

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#98]
I have a setup of seed data which checks to see if data exists then updates it first.

```c#
public static void SeedEmailTemplates(this Marten.IDocumentStore store)
{
    var currentDirectory = System.IO.Directory.GetCurrentDirectory();
    var files = System.IO.Directory.GetFiles(currentDirectory + @"\email-templates\", "*.html");

    using (var session = store.OpenSession())
    {
        // ReSharper disable once ForCanBeConvertedToForeach
        for (var i = 0; i < files.Length; i++)
        {
            var template = files[i];
            var file = System.IO.File.ReadAllText(template);
            var templateName = template.Replace(".html", "")
                                        .Split(new[] { "\\", "/" }, StringSplitOptions.RemoveEmptyEntries)
                                        .Last();

            var emailTemplate = session.Query<EmailTemplate>().FirstOrDefault(x => x.Name == templateName);

            if (emailTemplate == null)
            {
                emailTemplate = new EmailTemplate();

                session.Store(emailTemplate);
            }

            emailTemplate.Name = templateName;
            emailTemplate.Html = file;
        }

        session.SaveChanges();
    }
}
```

If I do an insert first, it forces the creation of the table. The querying will work perfectly fine.

Without the table. `var emailTemplate = session.Query<EmailTemplate>().FirstOrDefault(x => x.Name == templateName);` this will fail because the table does not exist yet.

![image](https://cloud.githubusercontent.com/assets/895629/11899908/547d4b6e-a5dd-11e5-8dc5-a39b9c71efc1.png)

In my opinion the table should be created when this exception is thrown, and null returned as if the query failed to return a result. So that it happens transparently.

**Comment by jeremydmiller** [comment]
@phillip-haydon I'm gonna have to check this out. I could swear that that should already be happening. Were you in the "auto-create"/ development mode when that happened?

**Comment by phillip-haydon** [comment]
Yup, I have the auto schema option explicitly set at the moment.

It only happens on Queries that occur before the first Store.
