### ISSUE TITLE
Cannot Bulk Insert Multi-Tenant Sub Class Docs

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#980]
I have a hierarchy of multi-tenanted classes registered like:

`For<IMessage>().AddSubClassHierarchy()`

I'm using a custom `IDocumentPolicy` to make everything `Conjoined` *unless* it implements an interface `INotMultiTenant`. I've stepped through the code and can see that, as expected, a `DocumentMapping` is being created for `IMessage` and its implementing types, setting `TenancyStyle` to `Conjoined`.

However, when I try to use `store.BulkInsertDocuments` on a list of `IMessage` documents, it throws `ArgumentOutOfRangeException` with message:

`Marten cannot do bulk inserts of Namespace.MyMessage`

(where `MyMessage` is a type than implements `IMessage`). Stack trace:
```
at Marten.Storage.Tenant.<BulkLoaderFor>b__28_0[T](Type t)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Marten.Storage.Tenant.BulkLoaderFor[T]()
at Marten.Storage.BulkInsertion.bulkInsertDocuments[T](T[] documents, Int32 batchSize, NpgsqlConnection conn, BulkInsertMode mode)
at Marten.Storage.BulkInsertion.BulkInserter`1.BulkInsert(Int32 batchSize, NpgsqlConnection connection, BulkInsertion parent, BulkInsertMode mode)
at Marten.Storage.BulkInsertion.BulkInsertDocuments(IEnumerable`1 documents, BulkInsertMode mode, Int32 batchSize)
```

The issue is [L214](https://github.com/JasperFx/marten/blob/40164b3e088137afa79c5e54cc2d29667782975d/src/Marten/Storage/Tenant.cs#L214) in the Tenant class - it throws if the mapping is not a `DocumentMapping`, and for sub-classes it's a `SubClassMapping`.

Is Marten meant to support bulk insert of tenanted, sub-class documents?

**Comment by jeremydmiller** [comment]
"Is Marten meant to support bulk insert of tenanted, sub-class documents?" -- no, we don't purposely put out bugs, this is just an oversight that no one has thought of before. Do you feel like doing the PR on this one so that it really does the bulk insert with the parent mapping because this one shouldn't be that bad? Or you can workaround it by forcing it to do the bulk insert against the ultimate parent type.

**Comment by cocowalla** [comment]
I wasn't trying to be cheeky - before I spent time on a PR, I just wanted to check with someone more au fait with the code base, incase there were any good reasons or hidden complexities that meant this wasn't supported :)

Happy to do a PR for this one - will try and get it done tonight.

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/commit/be58c81e58d85f18b42eb49aa8c629eb1082d17a
