### ISSUE TITLE
Issue with DuplicateField on integer arrays. (Marten 2.7.0)

### ISSUE THREAD

**Issue by pereiraarun** [JasperFx/marten#986]
When trying to insert into a class with an int array as duplicate field, insert fails with the following error: 

`
      Inner Exception 1:
      PostgresException: 42883: function public.mt_upsert_user(arg_carriers => integer[], arg_creator_id =>       integer, arg_customers => integer[], arg_email => text, arg_first_name => text, arg_is_active => boolean, arg_last_name => text, arg_partners => integer[], arg_sites => integer[], doc => jsonb, docdotnettype => character varying, docid => integer, docversion => uuid) does not exist
`

`
Marten.MartenCommandException
  HResult=0x80131500
  Message=Marten Command Failure:
select public.mt_upsert_user(arg_carriers := :arg0, arg_creator_id := :arg1, arg_customers := :arg2, arg_email := :arg3, arg_first_name := :arg4, arg_is_active := :arg5, arg_last_name := :arg6, arg_partners := :arg7, arg_sites := :arg8, doc := :arg9, docDotNetType := :arg10, docId := :arg11, docVersion := :arg12);select public.mt_upsert_user(arg_carriers := :arg13, arg_creator_id := :arg14, arg_customers := :arg15, arg_email := :arg16, arg_first_name := :arg17, arg_is_active := :arg18, arg_last_name := :arg19, arg_partners := :arg20, arg_sites := :arg21, doc := :arg22, docDotNetType := :arg23, docId := :arg24, docVersion := :arg25);select public.mt_upsert_user(arg_carriers := :arg26, arg_creator_id := :arg27, arg_customers := :arg28, arg_email := :arg29, arg_first_name := :arg30, arg_is_active := :arg31, arg_last_name := :arg32, arg_partners := :arg33, arg_sites := :arg34, doc := :arg35, docDotNetType := :arg36, docId := :arg37, docVersion := :arg38);select public.mt_upsert_user(arg_carriers := :arg39, arg_creator_id := :arg40, arg_customers := :arg41, arg_email := :arg42, arg_first_name := :arg43, arg_is_active := :arg44, arg_last_name := :arg45, arg_partners := :arg46, arg_sites := :arg47, doc := :arg48, docDotNetType := :arg49, docId := :arg50, docVersion := :arg51);select public.mt_upsert_user(arg_carriers := :arg52, arg_creator_id := :arg53, arg_customers := :arg54, arg_email := :arg55, arg_first_name := :arg56, arg_is_active := :arg57, arg_last_name := :arg58, arg_partners := :arg59, arg_sites := :arg60, doc := :arg61, docDotNetType := :arg62, docId := :arg63, docVersion := :arg64);select public.mt_upsert_user(arg_carriers := :arg65, arg_creator_id := :arg66, arg_customers := :arg67, arg_email := :arg68, arg_first_name := :arg69, arg_is_active := :arg70, arg_last_name := :arg71, arg_partners := :arg72, arg_sites := :arg73, doc := :arg74, docDotNetType := :arg75, docId := :arg76, docVersion := :arg77);select public.mt_upsert_user(arg_carriers := :arg78, arg_creator_id := :arg79, arg_customers := :arg80, arg_email := :arg81, arg_first_name := :arg82, arg_is_active := :arg83, arg_last_name := :arg84, arg_partners := :arg85, arg_sites := :arg86, doc := :arg87, docDotNetType := :arg88, docId := :arg89, docVersion := :arg90);select public.mt_upsert_user(arg_carriers := :arg91, arg_creator_id := :arg92, arg_customers := :arg93, arg_email := :arg94, arg_first_name := :arg95, arg_is_active := :arg96, arg_last_name := :arg97, arg_partners := :arg98, arg_sites := :arg99, doc := :arg100, docDotNetType := :arg101, docId := :arg102, docVersion := :arg103);select public.mt_upsert_user(arg_carriers := :arg104, arg_creator_id := :arg105, arg_customers := :arg106, arg_email := :arg107, arg_first_name := :arg108, arg_is_active := :arg109, arg_last_name := :arg110, arg_partners := :arg111, arg_sites := :arg112, doc := :arg113, docDotNetType := :arg114, docId := :arg115, docVersion := :arg116);select public.mt_upsert_user(arg_carriers := :arg117, arg_creator_id := :arg118, arg_customers := :arg119, arg_email := :arg120, arg_first_name := :arg121, arg_is_active := :arg122, arg_last_name := :arg123, arg_partners := :arg124, arg_sites := :arg125, doc := :arg126, docDotNetType := :arg127, docId := :arg128, docVersion := :arg129);select public.mt_upsert_user(arg_carriers := :arg130, arg_creator_id := :arg131, arg_customers := :arg132, arg_email := :arg133, arg_first_name := :arg134, arg_is_active := :arg135, arg_last_name := :arg136, arg_partners := :arg137, arg_sites := :arg138, doc := :arg139, docDotNetType := :arg140, docId := :arg141, docVersion := :arg142)

42883: function public.mt_upsert_user(arg_carriers => integer[], arg_creator_id => integer, arg_customers => integer[], arg_email => text, arg_first_name => text, arg_is_active => boolean, arg_last_name => text, arg_partners => integer[], arg_sites => integer[], doc => jsonb, docdotnettype => character varying, docid => integer, docversion => uuid) does not exist
  Source=Marten
  StackTrace:
   at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e)
   at Marten.Services.ManagedConnection.Execute(NpgsqlCommand cmd, Action`1 action)
   at Marten.Services.UpdateBatch.Execute()
   at Marten.Services.UnitOfWork.ApplyChanges(UpdateBatch batch)
   at Marten.DocumentSession.SaveChanges()
`

Here's the class:

      public class User
      {
        /// <summary>
        /// Gets or sets the id of the user.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the first name.
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets the last name.
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets the email
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets the hashed and salted password for the user.
        /// </summary>
        public string Password { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the user is active
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the user is locked.
        /// </summary>
        public bool IsLocked { get; set; }

        /// <summary>
        /// Gets or sets the date and time of entity creation
        /// </summary>
        public DateTimeOffset CreatedOnUtc { get; set; }

        /// <summary>
        /// Gets or sets the id of the user that created this user.
        /// </summary>
        public int CreatorId { get; set; }

        /// <summary>
        /// Gets or sets the type of the user.
        /// </summary>
        public UserType Type { get; set; }

        /// <summary>
        /// Gets or sets the carrier to which the user has access.
        /// </summary>
        public int[] Carriers { get; set; }

        /// <summary>
        /// Gets or sets the partner to which the user has access.
        /// </summary>
        public int[] Partners { get; set; }

        /// <summary>
        /// Gets or sets the customers to which the user has access.
        /// </summary>
        public int[] Customers { get; set; }

        /// <summary>
        /// Gets or sets the sites to which the user has access.
        /// </summary>
        public int[] Sites { get; set; }

        /// <summary>
        /// Gets or sets the postgres id for the object.
        /// </summary>
        public int PgId { get; set; }

        /// <summary>
        /// Gets or sets the service type for the object.
        /// </summary>
        public List<string> Permissions { get; set; }
    }
`

Here's the registry definition for the class:

`
                this.For<User>()
                .Duplicate(x => x.FirstName)
                .Duplicate(x => x.LastName)
                .Duplicate(x => x.Email)
                .Duplicate(x => x.IsActive)
                .Duplicate(x => x.CreatorId)
                .Duplicate(x => x.Carriers)
                .Duplicate(x => x.Partners)
                .Duplicate(x => x.Customers)
                .Duplicate(x => x.Sites);
`

**Comment by jeremydmiller** [comment]
@pereiraarun At that point, is it even worth it to be using Marten if you're going to duplicate all those things? You might be better off going to Dapper at this point. Dunno if it handles int[] any better than Marten does here.

How are you managing schema objects? Does the function actually exist, and Marten doesn't quite match up between the arg types it thinks the db should have, or is the function completely missing?

**Comment by pereiraarun** [comment]
@jeremydmiller To be honest, marten's worked out amazingly well. Significantly better than my experience with RavenDb. The reason I duplicate those fields is that I gathered from the documentation that it provides better performance for queries involving searches.

The function exists. Inserts fail. From a cursory inspection, it looks like a type mismatch. Currently, I've removed the duplication of those array types. I've provided the bug report merely to document the issue. I've used MatchesSql to work with the data so moving to dapper isn't necessary. In fact, MatchesSql worked out better since I was able to use subselects to avoid having to round-trip values to the API.

        users = users.Where(
                    x => x.MatchesSql($" TRANSLATE(data->>'Customers', '[]', '{{}}')::int[] && '{{{joinedCustomers}}}'")

The only thing that duplicate provides, in this case, is saving the call to TRANSLATE and making it a bit easier to read.

**Comment by jeremydmiller** [comment]
Ah, gotcha. We definitely still have a bug w/ `int[]` duplicated fields. For indexing, calculated indexes are probably more efficient overall. The biggest reason to use them really is exactly what you're doingl

**Comment by jeremydmiller** [comment]
Easy money, but we'll need to watch the schema validation logic

**Comment by jeremydmiller** [comment]
This will be in Marten 2.8.0 next week-ish maybe.
