### ISSUE TITLE
Changing the identity can cause the routine to be incorrect and not updated

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#99]
Initially I created a new class with a `string` `Id` field. This generated the table + routine, and notified me correctly that I did not supply an Id.

Updating the field to use an int instead of string, it setup the HiLo for the table but then could not find the matching routine since the first was created `VARCHAR, JSONB` but is looking for `INTEGER, JSONB`

Not sure how this should be handled. I would have expected it to just update accordingly but I realise that may not be right since the table would be created with a `string` identifier and would require being dropped and re-created. 

Possibly just need to handle this scenario with a nicely structured error message.

**Comment by phillip-haydon** [comment]
routine -> function

I've been using Jet Brains new DataGrip IDE.

**Comment by jeremydmiller** [comment]
@phillip-haydon What I think we should do (and I think I was putting off), is the first time a document type is used in "development mode" *after* seeing that the table already exists is to do a column by column check against the existing table and what the document mapping *should* be. If you've changed the Id type or added searchable fields or whatever else, blow away the database table & upsert command and re-generate.
