### ISSUE TITLE
IfNotExists methods should rely on IdentityAttribute

### ISSUE THREAD

**Issue by sw-carlin** [JasperFx/marten#990]
I expected the IfNotExists methods available through the patch API to use the Identity property on an object but it's doing an exact match check which doesn't play nicely with objects that have timestamps on them.

Code location:
https://github.com/JasperFx/marten/blob/fd733681aa607657e58e93f9da4b35e2b7b2eda2/src/Marten/Schema/SQL/mt_patching.js#L109-L110

**Comment by jeremydmiller** [comment]
Can you provide a little more context about what you're doing?

**Comment by sw-carlin** [comment]
Here's some examples that might help clarify:

# InsertIfNotExists/AppendIfNotExists
Given I have a sub-document with a property that holds the created timestamp of that sub-document
And I have inserted it into an array in the parent document
When I InsertIfNotExists that same sub-document with a new timestamp
Then I expect nothing to happen because the id is the same
But I instead have a duplicate item with the only difference being the timestamp

Example Classes:
```
Class MyParent
{
    [Identity]
    string Id {get;set}
    List<MyChild> Children {get;set;}
}

Class MyChild
{
    [Identity]
    string Id {get;set}
    DateTime CreationDate {get;set}
    string Name {get;set}
}
```

# Remove sub-document
Given I have a sub-document stored in an array
And the C# class has changed
When I try to Remove the item from the array
Then I expect the item to be removed because the data is "identical"
But the item remains because the C# class serializes differently now

# Summary
Due to this aforementioned issues I've told my team to not use the patch API for managing items within an array. It's safer to read the whole array into memory, update it in C# and then set the array. This isn't efficient but it's the only way we can be sure we don't experience silent failures that will bite us later.

**Comment by jeremydmiller** [comment]
@sw-carlin Finally getting into this more for the v4 release. I think you might have over-generalized the issue a little bit here. Dollars to donuts this is an issue specific to DateTimeOffset/DateTime precision and probably not something we can actually beat easily. I think at most this needs to be handled with documentation warning you about the DateTime precision issue. And this isn't the first bug related to DateTime precision we've faced.

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/commit/7f434269879f6f6bdebf8009714a6ec40fb3a21e
