### ISSUE TITLE
Consider using "tombstone" placeholders in the event table

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#996]
Use “tombstone” event placeholders in place of failures. This might make the async daemon **way** easier.

**Comment by jeffdoolittle** [comment]
Can you provide more details on the nature of the problem and the proposed solution?

**Comment by jeremydmiller** [comment]
I'm folding this into #1584

**Comment by jeremydmiller** [comment]
I did a terrible job of this in #1584 and I'm reopening this separately today to redo it. The tombstones have to be interleaved w/ the events for this to matter.
